(() => {
  'use strict';
  const APP={name:'Anomaly Array',emoji:'◈',category:'play',version:'1.0.0',summary:'Locate shifting signal clusters with row clues, limited scans, and escalating spatial deductions.',description:'A local-only spatial deduction game. Read row and column signal counts, spend scarce scans, mark likely cells, account for a shifting anomaly, and clear increasingly complex arrays before stability runs out.'};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const SHAPES=[[[0,0],[1,0],[0,1]],[[0,0],[1,0],[2,0]],[[0,0],[0,1],[1,1]],[[0,0],[1,0],[1,1],[2,1]],[[0,0],[1,0],[2,0],[1,1]]];
  function style(){if($('#anomaly-array-style'))return;const e=document.createElement('style');e.id='anomaly-array-style';e.textContent=`.array{max-width:980px;display:grid;gap:12px}.array-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.array-stat,.array-card{border:1px solid var(--line);border-radius:16px;background:#fff}.array-stat{padding:8px}.array-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.array-layout{display:grid;grid-template-columns:1fr .8fr;gap:12px}.array-card{padding:14px}.array-board-wrap{display:grid;grid-template-columns:28px 1fr;grid-template-rows:28px 1fr;gap:5px;max-width:520px;margin:auto}.array-cols{grid-column:2;display:grid}.array-rows{grid-row:2;display:grid}.array-clue{display:grid;place-items:center;font-weight:900;color:var(--muted)}.array-board{grid-column:2;grid-row:2;display:grid;gap:5px;touch-action:manipulation}.array-cell{aspect-ratio:1;border:1px solid var(--line);border-radius:10px;background:#f8fafc;display:grid;place-items:center;font-size:1.15rem;font-weight:900;min-width:34px}.array-cell:hover{background:#eef2ff}.array-cell:focus-visible{outline:3px solid #7c3aed;outline-offset:2px}.array-cell[data-state="mark"]{background:#ede9fe;border-color:#7c3aed}.array-cell[data-state="hit"]{background:#dcfce7;border-color:#16a34a}.array-cell[data-state="miss"]{background:#fff1f2;border-color:#e11d48}.array-cell[data-scan="true"]{box-shadow:inset 0 0 0 3px #f59e0b}.array-actions,.array-modes{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.array button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;color:inherit;font-weight:800;padding:9px}.array button[aria-pressed="true"]{background:#ede9fe;border-color:#7c3aed}.array button:disabled{opacity:.48}.array-log{min-height:92px}.array-log strong,.array-log small{display:block}.array-meter{height:10px;border-radius:999px;background:#e2e8f0;overflow:hidden}.array-meter span{display:block;height:100%;background:linear-gradient(90deg,#ef4444,#f59e0b,#22c55e);transition:width .25s}.array-legend{display:grid;gap:7px;font-size:.82rem}.array-legend span{display:flex;gap:8px;align-items:center}.array-dot{width:18px;height:18px;border-radius:5px;border:1px solid var(--line);display:inline-block}.array-dot.mark{background:#ede9fe}.array-dot.scan{box-shadow:inset 0 0 0 3px #f59e0b}.array-complete{animation:arrayPop .35s ease}@keyframes arrayPop{50%{transform:scale(1.02)}}@media(max-width:800px){.array-layout{grid-template-columns:1fr}.array-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:520px){.array-hud{grid-template-columns:repeat(2,1fr)}.array-actions,.array-modes{grid-template-columns:1fr}.array-cell{min-width:0;border-radius:7px}.array-board-wrap{grid-template-columns:24px 1fr;grid-template-rows:24px 1fr}}@media(prefers-reduced-motion:reduce){.array *{animation:none!important;transition:none!important}}`;document.head.append(e)}
  function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-anomaly-array]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.anomalyArray='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
  function boot(){style();let n=0;const r=()=>{card();if(!$('[data-anomaly-array]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.arrayBound)return;b.dataset.arrayBound='1';b.addEventListener('click',()=>setTimeout(card))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · spatial deduction';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel array';root.innerHTML=`<div class="array-hud">${['Array','Signals','Scans','Stability','Streak','Score'].map((x,i)=>`<div class="array-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="array-layout"><section class="array-card"><div class="array-board-wrap"><div></div><div class="array-cols" data-cols></div><div class="array-rows" data-rows></div><div class="array-board" role="grid" aria-label="Signal array" data-board></div></div></section><aside class="array-card"><p class="eyebrow">Deduction console</p><h3>Locate the anomaly</h3><p data-brief></p><div class="array-meter" aria-label="Stability"><span data-meter></span></div><h3>Input mode</h3><div class="array-modes"><button data-mode="probe" aria-pressed="true">Probe cell</button><button data-mode="mark" aria-pressed="false">Mark suspect</button></div><h3>Actions</h3><div class="array-actions"><button data-a="scan">Scan selected row</button><button data-a="shift">Predict shift</button><button data-a="next">Next array</button><button data-a="restart">Restart run</button></div><div class="result-card array-log" aria-live="polite"></div><div class="array-legend"><span><i class="array-dot mark"></i>Marked suspect</span><span><i class="array-dot scan"></i>Scanned line</span></div><p><small>Keyboard: arrows move, Enter acts, M toggles mark mode, S scans the selected row. No data is stored or sent.</small></p></aside></div>`;stage.append(root);
    let st,grid,shape,selected=0,mode='probe',hits=new Set(),marks=new Set(),scanned=new Set(),finished=false;
    const log=(a,b)=>{const l=$('.array-log',root);l.replaceChildren(Object.assign(document.createElement('strong'),{textContent:a}),Object.assign(document.createElement('small'),{textContent:b}))};
    function makeShape(size,count){const base=SHAPES[Math.min(SHAPES.length-1,count-1)],rot=Math.floor(Math.random()*4),pts=base.map(([x,y])=>{for(let i=0;i<rot;i++)[x,y]=[y,-x];return[x,y]});const minX=Math.min(...pts.map(p=>p[0])),maxX=Math.max(...pts.map(p=>p[0])),minY=Math.min(...pts.map(p=>p[1])),maxY=Math.max(...pts.map(p=>p[1]));const ox=Math.floor(Math.random()*(size-(maxX-minX)))-minX,oy=Math.floor(Math.random()*(size-(maxY-minY)))-minY;return new Set(pts.map(([x,y])=>(y+oy)*size+(x+ox)))}
    function setup(){const size=Math.min(7,4+Math.floor((st.level-1)/2)),signals=Math.min(5,3+Math.floor((st.level-1)/2));st.size=size;st.signals=signals;st.scans=Math.max(1,4-Math.floor(st.level/3));st.stability=5;grid=Array(size*size).fill(0);shape=makeShape(size,signals);shape.forEach(i=>grid[i]=1);selected=0;mode='probe';hits=new Set();marks=new Set();scanned=new Set();finished=false;log('New array online.',`Find ${signals} connected signals. Row and column counts are exact.`);draw()}
    function reset(){st={level:1,score:0,streak:0};setup()}
    function counts(axis){return Array.from({length:st.size},(_,n)=>grid.reduce((a,v,i)=>a+(v&&((axis==='r'?Math.floor(i/st.size):i%st.size)===n)?1:0),0))}
    function act(i){if(finished)return;if(mode==='mark'){marks.has(i)?marks.delete(i):marks.add(i);draw();return}if(hits.has(i))return;const hit=grid[i]===1;hits.add(i);if(hit){st.score+=10+st.streak*2;st.streak++;log('Signal confirmed.',`${shape.size-hitsFound()} remain.`)}else{st.stability--;st.streak=0;log('Empty cell.',st.stability?'The anomaly remains stable.':'The array destabilized.');if(st.level>=3&&!finished)drift()}check();draw()}
    function hitsFound(){return [...hits].filter(i=>grid[i]).length}
    function drift(){const unresolved=[...shape].filter(i=>!hits.has(i));if(!unresolved.length)return;const from=unresolved[Math.floor(Math.random()*unresolved.length)],dirs=[1,-1,st.size,-st.size],choices=dirs.map(d=>from+d).filter(n=>n>=0&&n<grid.length&&Math.abs((n%st.size)-(from%st.size))<=1&&!shape.has(n));if(!choices.length)return;const to=choices[Math.floor(Math.random()*choices.length)];shape.delete(from);shape.add(to);grid[from]=0;grid[to]=1;log('The anomaly shifted.','One unresolved signal moved after the miss. Recheck your deductions.')}
    function scan(){if(finished||st.scans<1)return log('No scans available.','Use the row and column counts.');const row=Math.floor(selected/st.size);st.scans--;scanned.add(row);const exact=counts('r')[row];log('Row scan complete.',`Row ${row+1} contains ${exact} signal${exact===1?'':'s'}; scanned cells are outlined.`);draw()}
    function predict(){if(finished)return;const suspects=[...marks].filter(i=>grid[i]&&!hits.has(i));if(!suspects.length){st.stability--;log('Prediction missed.','None of the marked cells currently holds an unresolved signal.')}else{const i=suspects[0];hits.add(i);marks.delete(i);st.score+=18;st.streak++;log('Shift predicted.','A marked signal was intercepted without spending a probe.')}check();draw()}
    function check(){if(hitsFound()===shape.size){finished=true;st.score+=st.stability*8+st.scans*5;root.classList.add('array-complete');log('Array resolved.',`Level ${st.level} cleared with ${st.stability} stability remaining.`)}else if(st.stability<=0){finished=true;log('Array lost.','Restart the run and use scans or marks earlier.')}}
    function next(){if(!finished||st.stability<=0)return log('Array incomplete.','Confirm every signal before advancing.');st.level++;setup()}
    function draw(){const vals=[st.level,shape.size,st.scans,st.stability,st.streak,st.score];$$('[data-h]',root).forEach((e,i)=>e.textContent=vals[i]);$('[data-meter]',root).style.width=`${clamp(st.stability/5*100,0,100)}%`;$('[data-brief]',root).textContent=`${st.size}×${st.size} grid. Exact clues show signals per row and column. From level 3 onward, a missed probe can move one unresolved signal.`;const rc=counts('r'),cc=counts('c');$('[data-cols]',root).style.gridTemplateColumns=`repeat(${st.size},1fr)`;$('[data-rows]',root).style.gridTemplateRows=`repeat(${st.size},1fr)`;$('[data-cols]',root).innerHTML=cc.map(n=>`<span class="array-clue">${n}</span>`).join('');$('[data-rows]',root).innerHTML=rc.map(n=>`<span class="array-clue">${n}</span>`).join('');const b=$('[data-board]',root);b.style.gridTemplateColumns=`repeat(${st.size},1fr)`;b.innerHTML=grid.map((_,i)=>{const state=hits.has(i)?(grid[i]?'hit':'miss'):(marks.has(i)?'mark':'');const symbol=state==='hit'?'◆':state==='miss'?'×':state==='mark'?'?':'';return `<button class="array-cell" role="gridcell" data-i="${i}" data-state="${state}" data-scan="${scanned.has(Math.floor(i/st.size))}" aria-label="Row ${Math.floor(i/st.size)+1}, column ${i%st.size+1}${state?`, ${state}`:''}" ${i===selected?'tabindex="0"':'tabindex="-1"'}>${symbol}</button>`}).join('');$$('[data-mode]',root).forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.mode===mode)));$('[data-a="scan"]',root).disabled=!st.scans||finished;$('[data-a="next"]',root).disabled=!finished||st.stability<=0;requestAnimationFrame(()=>$('.array-cell[data-i="'+selected+'"]',root)?.focus({preventScroll:true}))}
    root.addEventListener('click',e=>{const c=e.target.closest('[data-i]'),m=e.target.closest('[data-mode]'),a=e.target.closest('[data-a]');if(c){selected=+c.dataset.i;act(selected)}else if(m){mode=m.dataset.mode;draw()}else if(a){if(a.dataset.a==='scan')scan();else if(a.dataset.a==='shift')predict();else if(a.dataset.a==='next')next();else reset()}});
    const key=e=>{if(!dialog.open)return;const row=Math.floor(selected/st.size),col=selected%st.size;if(e.key==='ArrowRight')selected=row*st.size+Math.min(st.size-1,col+1);else if(e.key==='ArrowLeft')selected=row*st.size+Math.max(0,col-1);else if(e.key==='ArrowDown')selected=Math.min(st.size-1,row+1)*st.size+col;else if(e.key==='ArrowUp')selected=Math.max(0,row-1)*st.size+col;else if(e.key==='Enter'||e.key===' '){e.preventDefault();act(selected);return}else if(e.key.toLowerCase()==='m'){mode=mode==='probe'?'mark':'probe'}else if(e.key.toLowerCase()==='s'){scan();return}else return;e.preventDefault();draw()};document.addEventListener('keydown',key);dialog.addEventListener('close',()=>document.removeEventListener('keydown',key),{once:true});reset()
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
