(() => {
  'use strict';
  const APP={name:'Aquifer Commons',emoji:'💧',category:'play',version:'1.1.0',summary:'Negotiate a water compact while balancing reserves, salinity, trust, and six competing districts.',description:'A procedural local water-governance strategy game with stakeholder bargaining, promises, policy votes, seasonal shocks, aquifer links, pumping, conservation, recharge, transfers, scoring, recovery, session unlocks, keyboard and touch controls, reduced motion, and teardown.'};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const scenarios={valley:{name:'Learning valley',turns:8,budget:10,recharge:8,unlock:0},coast:{name:'Coastal basin',turns:10,budget:11,recharge:6,unlock:1},drought:{name:'Drought compact',turns:12,budget:13,recharge:3,unlock:2}};
  const districtSeeds=[
    {name:'North town',type:'town',demand:7,priority:'reliable household supply'},
    {name:'Orchards',type:'farm',demand:9,priority:'protect perennial crops'},
    {name:'Wetland',type:'wetland',demand:5,priority:'keep habitat above minimum flow'},
    {name:'Harbor town',type:'town',demand:8,priority:'stop coastal salt intrusion'},
    {name:'South farms',type:'farm',demand:10,priority:'preserve seasonal allocations'},
    {name:'Recharge plain',type:'recharge',demand:2,priority:'reserve land for infiltration'}
  ];
  const policies={cap:{name:'Shared pumping cap',cost:1,detail:'All pumping yields 1 less supply, but every district gains trust and salt rises more slowly.'},wetland:{name:'Wetland floor',cost:2,detail:'Wetland demand is automatically met first; towns and farms accept a smaller score ceiling.'},bank:{name:'Recharge bank',cost:3,detail:'Recharge projects add more reserve and create one shared emergency credit.'}};
  const shocks=[
    {name:'Dry wind',text:'Farm demand rises by 2 this season.',apply:s=>{s.cells.forEach((c,i)=>{if(s.districts[i].type==='farm')c.tempDemand+=2;});}},
    {name:'Pipe break',text:'One town loses 3 stored supply.',apply:s=>{const ids=s.districts.map((d,i)=>d.type==='town'?i:-1).filter(i=>i>=0);const i=ids[Math.floor(Math.random()*ids.length)];s.cells[i].supply=Math.max(0,s.cells[i].supply-3);}},
    {name:'Recharge pulse',text:'The two lowest reserves gain 6 level.',apply:s=>{[...s.cells].map((c,i)=>({i,v:c.level})).sort((a,b)=>a.v-b.v).slice(0,2).forEach(x=>s.cells[x.i].level=Math.min(100,s.cells[x.i].level+6));}},
    {name:'Public hearing',text:'Broken promises cost double trust this season.',apply:s=>{s.hearing=true;}},
    {name:'Salt wedge',text:'Coastal salt risk rises by 8 unless recharge is active.',apply:s=>{const i=s.districts.findIndex(d=>d.name==='Harbor town');s.cells[i].salt=Math.min(100,s.cells[i].salt+(s.cells[i].recharge?2:8));}}
  ];
  function installStyles(){if($('#aqc-style'))return;const style=document.createElement('style');style.id='aqc-style';style.textContent=`
    .aqc{max-width:1120px;display:grid;gap:12px}.aqc-hud{display:grid;grid-template-columns:repeat(7,1fr);gap:7px}.aqc-stat,.aqc-panel{border:1px solid var(--line);border-radius:18px;background:#fff}.aqc-stat{padding:9px}.aqc-stat span{display:block;font-size:.6rem;font-weight:900;text-transform:uppercase;color:var(--muted)}.aqc-main{display:grid;grid-template-columns:1.18fr .82fr;gap:12px}.aqc-panel{padding:14px}.aqc-board{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.aqc-cell{min-height:158px;border:1px solid #94a3b8;border-radius:14px;padding:10px;background:linear-gradient(#eff6ff,#dbeafe);position:relative;overflow:hidden}.aqc-cell.selected{outline:3px solid #2563eb}.aqc-cell button{width:100%;text-align:left;background:transparent;border:0;padding:0;position:relative;z-index:2;color:inherit}.aqc-cell h4{margin:0 0 3px}.aqc-level{position:absolute;left:0;right:0;bottom:0;background:rgba(37,99,235,.18);pointer-events:none}.aqc-risk{position:absolute;right:8px;bottom:7px;font-size:.72rem;font-weight:900}.aqc-trust{display:flex;gap:3px;margin-top:6px}.aqc-trust i{width:13px;height:5px;border-radius:99px;background:#cbd5e1}.aqc-trust i.on{background:#16a34a}.aqc-controls,.aqc-scenarios,.aqc-actions,.aqc-policies{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.aqc button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800;color:inherit}.aqc button[aria-pressed=true]{background:#dbeafe;border-color:#2563eb}.aqc button:focus-visible{outline:3px solid #2563eb;outline-offset:2px}.aqc-meter{height:12px;border-radius:999px;background:#e2e8f0;overflow:hidden}.aqc-meter span{display:block;height:100%;background:linear-gradient(90deg,#ef4444,#facc15,#22c55e);transition:width .25s}.aqc-log{min-height:105px}.aqc-council{margin-top:10px;padding:10px;border-radius:14px;background:#f8fafc}.aqc-council p{margin:4px 0}.aqc-promise{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center}.aqc-promise small{color:var(--muted)}.aqc-policy{padding:9px;text-align:left}.aqc-policy strong,.aqc-policy small{display:block}.aqc-policy small{margin-top:3px;color:var(--muted)}
    @media(max-width:900px){.aqc-main{grid-template-columns:1fr}.aqc-hud{grid-template-columns:repeat(4,1fr)}}@media(max-width:620px){.aqc-hud{grid-template-columns:repeat(2,1fr)}.aqc-controls,.aqc-scenarios,.aqc-actions,.aqc-policies,.aqc-board{grid-template-columns:1fr}.aqc-cell{min-height:132px}}@media(prefers-reduced-motion:reduce){.aqc *{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
  `;document.head.append(style);}
  function addCard(){const grid=$('#app-grid'),template=$('#app-card-template');if(!grid||!template||$('[data-aqc]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=template.content.cloneNode(true);$('.app-card',f).dataset.aqc='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',openApp);grid.append(f);}
  function boot(){installStyles();let attempts=0;const retry=()=>{addCard();if(!$('[data-aqc]')&&attempts++<20)setTimeout(retry,120);};retry();$$('.filter').forEach(b=>{if(b.dataset.aqcBound)return;b.dataset.aqcBound='1';b.addEventListener('click',()=>setTimeout(addCard));});}
  function openApp(){const dialog=$('#app-dialog'),stage=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · water governance';$('#dialog-description').textContent=APP.description;$('#dialog-feedback').href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Aquifer%20Commons';stage.replaceChildren();startGame(stage,dialog);dialog.showModal();}
  function startGame(stage,dialog){
    const root=document.createElement('section');root.className='tool-panel aqc';root.innerHTML=`<div class="aqc-hud">${['Scenario','Season','Budget','Permits','Reserve','Salt risk','Council trust'].map((x,i)=>`<div class="aqc-stat"><span>${x}</span><strong data-h="${i}"></strong></div>`).join('')}</div><div class="aqc-main"><section class="aqc-panel"><h3>Shared aquifer board</h3><div class="aqc-board" role="group" aria-label="Aquifer districts and water conditions"></div><div class="aqc-council"><strong>Council promise</strong><div class="aqc-promise"><p data-promise></p><button data-action="promise">Make promise</button></div></div><p><small>Select a district, negotiate a promise, allocate supply or resilience, then advance the season.</small></p></section><aside class="aqc-panel"><div class="aqc-scenarios"></div><h3>District actions</h3><div class="aqc-controls"><button data-action="pump">Issue pumping permit</button><button data-action="conserve">Fund conservation</button><button data-action="recharge">Build recharge basin</button><button data-action="trade">Transfer water right</button></div><h3>Compact policy</h3><div class="aqc-policies"></div><div class="aqc-actions"><button data-action="advance">Advance season</button><button data-action="forecast">Review forecast</button><button data-action="recover">Emergency compact</button><button data-action="submit">End compact</button><button data-action="restart">Restart scenario</button></div><p><strong>Commons health</strong></p><div class="aqc-meter"><span></span></div><div class="aqc-log result-card" aria-live="polite"></div><small>Keyboard: arrows select, P pump, C conserve, B recharge, T transfer, M promise, F forecast, Space advance, E emergency compact, Enter finish, R restart.</small></aside></div>`;stage.append(root);
    let unlocked=0,cumulative=0,state;
    const announce=(title,detail)=>{$('.aqc-log',root).replaceChildren(Object.assign(document.createElement('strong'),{textContent:title}),Object.assign(document.createElement('small'),{textContent:detail}));};
    const shuffled=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;};
    function begin(key){const sc=scenarios[key],order=shuffled(districtSeeds);state={key,turn:0,budget:sc.budget,permits:5,forecast:2,recovery:1,selected:0,score:0,finished:false,hearing:false,policy:null,credit:0,promise:null,districts:order,cells:order.map((d,i)=>({level:56+Math.floor(Math.random()*15)-(i%3)*3,salt:key==='coast'&&d.name==='Harbor town'?30:6+Math.floor(Math.random()*8),supply:0,conserve:0,recharge:0,tempDemand:0,trust:3,broken:0}))};announce('Compact opened.','The basin layout and council order changed. Keep water safe while honoring enough promises to retain consent.');draw();}
    function select(i){state.selected=(i+state.districts.length)%state.districts.length;draw();}
    function makePromise(){if(state.finished)return;const i=state.selected,d=state.districts[i],c=state.cells[i];if(state.promise&&state.promise.turn===state.turn)return announce('Promise already recorded.','Advance the season before negotiating another commitment.');state.promise={index:i,turn:state.turn,target:Math.max(3,d.demand-c.conserve),name:d.name};announce('Public promise made.',`${d.name} expects ${state.promise.target} supply this season for ${d.priority}.`);draw();}
    function enactPolicy(key){if(state.finished||state.policy)return;const p=policies[key];if(state.budget<p.cost)return announce('Policy vote failed.',`The council needs ${p.cost} budget.`);const average=state.cells.reduce((n,c)=>n+c.trust,0)/state.cells.length;if(average<2.5)return announce('Policy vote failed.','Council trust is too low for a basin-wide rule.');state.budget-=p.cost;state.policy=key;if(key==='bank')state.credit=1;state.cells.forEach(c=>c.trust=Math.min(5,c.trust+1));announce(`${p.name} adopted.`,p.detail);draw();}
    function act(kind){if(state.finished)return;const c=state.cells[state.selected],d=state.districts[state.selected];if(kind==='pump'){if(state.permits<1||c.level<15)return announce('Permit denied.','No permits remain or the local water table is too low.');state.permits--;const yieldAmount=state.policy==='cap'?5:6;c.supply+=yieldAmount;c.level-=6;c.salt+=state.key==='coast'&&d.type==='town'?(state.policy==='cap'?2:4):(state.policy==='cap'?1:2);announce('Pumping permit issued.',`${d.name} gained ${yieldAmount} supply but lost local reserve.`);}if(kind==='conserve'){if(state.budget<2)return announce('Budget too low.','Conservation requires 2 budget.');state.budget-=2;c.conserve+=3;c.trust=Math.min(5,c.trust+1);announce('Conservation funded.',`${d.name} demand falls by 3 and local trust improves.`);}if(kind==='recharge'){if(state.budget<3)return announce('Budget too low.','Managed recharge requires 3 budget.');state.budget-=3;const gain=state.policy==='bank'?8:5;c.recharge+=gain;c.level=Math.min(100,c.level+gain);c.salt=Math.max(0,c.salt-5);announce('Recharge basin built.',`${d.name} gained reserve and reduced salt pressure.`);}if(kind==='trade'){if(state.budget<1)return announce('Budget too low.','A transfer costs 1 budget.');const donor=state.cells.reduce((best,x,i)=>x.supply>state.cells[best].supply?i:best,0);if(donor===state.selected||state.cells[donor].supply<2)return announce('No transferable allocation.','Pump another district first or conserve locally.');state.budget--;state.cells[donor].supply-=2;c.supply+=2;state.cells[donor].trust=Math.max(0,state.cells[donor].trust-1);c.trust=Math.min(5,c.trust+1);announce('Water right transferred.',`${state.districts[donor].name} sent 2 supply to ${d.name}; the donor council noticed.`);}draw();}
    function forecast(){if(!state.forecast)return announce('Forecast reviews spent.','Plan from current recharge and salinity trends.');state.forecast--;const base=scenarios[state.key].recharge,expected=Math.max(0,base+(state.turn%3===0?2:-1)-(state.key==='drought'&&state.turn>4?2:0));const next=shocks[(state.turn+1)%shocks.length];announce('Seasonal forecast.',`Expected recharge ${expected}. Likely pressure: ${next.name.toLowerCase()}.`);draw();}
    function advance(){if(state.finished)return;const sc=scenarios[state.key];state.hearing=false;state.cells.forEach(c=>c.tempDemand=0);const shock=shocks[(state.turn+Math.floor(Math.random()*shocks.length))%shocks.length];shock.apply(state);let failures=0,broken=0;const natural=Math.max(0,sc.recharge+(state.turn%3===0?2:-1)-(state.key==='drought'&&state.turn>4?2:0));state.cells.forEach((c,i)=>{const d=state.districts[i],need=Math.max(1,d.demand+c.tempDemand-c.conserve);let reserved=0;if(state.policy==='wetland'&&d.type==='wetland')reserved=Math.min(need,c.supply);const met=Math.min(need,c.supply+reserved);c.supply=Math.max(0,c.supply-met);c.level=Math.max(0,Math.min(100,c.level+natural/3+c.recharge*.35-(need-met)*.7));c.salt=Math.max(0,Math.min(100,c.salt+(c.level<35?5:0)+(state.key==='coast'&&d.name==='Harbor town'?3:0)-c.recharge*.3));if(met<need||c.level<15||c.salt>70){failures++;c.trust=Math.max(0,c.trust-1);}else c.trust=Math.min(5,c.trust+0.25);c.conserve=Math.max(0,c.conserve-1);c.recharge=Math.max(0,c.recharge-1);});if(state.promise&&state.promise.turn===state.turn){const c=state.cells[state.promise.index],kept=c.supply>=0&&c.level>15; if(!kept){const loss=state.hearing?2:1;c.trust=Math.max(0,c.trust-loss);c.broken++;broken=1;}else{c.trust=Math.min(5,c.trust+1);state.score+=45;}state.promise=null;}state.turn++;state.permits=Math.min(6,state.permits+2);state.budget+=2;state.score+=Math.max(0,130-failures*30-broken*35);announce(`${shock.name}.`,`${shock.text} ${failures?`${failures} districts crossed a service or safety threshold.`:'The compact absorbed the shock.'}`);if(state.cells.some(c=>c.level===0||c.salt===100)||state.cells.filter(c=>c.trust===0).length>=3){state.finished=true;announce('Compact failed.','Aquifer collapse, salt intrusion, or a council walkout ended the agreement.');}if(state.turn>=sc.turns&&!state.finished)finish();draw();}
    function recover(){if(!state.recovery&&!state.credit)return announce('Recovery options spent.','Finish with remaining permits and budget.');if(state.credit)state.credit=0;else state.recovery=0;state.cells.forEach(c=>{c.level=Math.max(25,c.level);c.salt=Math.max(0,c.salt-12);c.supply+=2;c.trust=Math.max(1,c.trust);});state.budget=Math.max(state.budget,3);state.score-=100;announce('Emergency compact activated.','Shared reserves and minimum trust stabilized, but the score ceiling fell.');draw();}
    function finish(){if(state.finished)return;const avg=state.cells.reduce((n,c)=>n+c.level,0)/6,maxSalt=Math.max(...state.cells.map(c=>c.salt)),avgTrust=state.cells.reduce((n,c)=>n+c.trust,0)/6,broken=state.cells.reduce((n,c)=>n+c.broken,0);state.score+=Math.round(avg*4+(100-maxSalt)*3+avgTrust*55+state.budget*15-broken*45);state.finished=true;const certified=avg>=43&&maxSalt<65&&avgTrust>=2.8&&broken<=2&&state.turn>=Math.min(5,scenarios[state.key].turns-2);if(certified){if(state.key==='valley')unlocked=Math.max(unlocked,1);if(state.key==='coast')unlocked=Math.max(unlocked,2);cumulative+=state.score;announce('Compact certified.',`Reserve ${Math.round(avg)}, salt ${Math.round(maxSalt)}, trust ${avgTrust.toFixed(1)}, broken promises ${broken}.`);}else announce('Compact incomplete.',`Targets: reserve 43+, salt below 65, trust 2.8+, no more than two broken promises. Current: ${Math.round(avg)}, ${Math.round(maxSalt)}, ${avgTrust.toFixed(1)}, ${broken}.`);draw();}
    function draw(){const sc=scenarios[state.key],avg=state.cells.reduce((n,c)=>n+c.level,0)/6,maxSalt=Math.max(...state.cells.map(c=>c.salt)),avgTrust=state.cells.reduce((n,c)=>n+c.trust,0)/6,health=Math.max(0,Math.min(100,avg-maxSalt*.35+avgTrust*8+20)),vals=[sc.name,`${state.turn}/${sc.turns}`,state.budget,state.permits,Math.round(avg),Math.round(maxSalt),avgTrust.toFixed(1)];$$('[data-h]',root).forEach((e,i)=>e.textContent=vals[i]);$('.aqc-meter span',root).style.width=`${health}%`;$('.aqc-board',root).innerHTML=state.cells.map((c,i)=>{const d=state.districts[i],need=Math.max(1,d.demand+c.tempDemand-c.conserve);return `<div class="aqc-cell ${i===state.selected?'selected':''}"><div class="aqc-level" style="height:${c.level}%"></div><button data-cell="${i}" aria-label="Select ${d.name}, water level ${Math.round(c.level)}, salt risk ${Math.round(c.salt)}, trust ${c.trust.toFixed(1)}"><h4>${d.name}</h4><div>${d.type} · supply ${c.supply}/${need}</div><small>Level ${Math.round(c.level)} · Salt ${Math.round(c.salt)}</small><small>${d.priority}</small><span class="aqc-trust" aria-hidden="true">${[1,2,3,4,5].map(n=>`<i class="${c.trust>=n?'on':''}"></i>`).join('')}</span></button><span class="aqc-risk">${c.salt>55?'⚠ salt':c.trust<2?'⚠ trust':'stable'}</span></div>`;}).join('');$('.aqc-scenarios',root).innerHTML=Object.entries(scenarios).map(([k,x])=>`<button data-scenario="${k}" ${x.unlock>unlocked?'disabled':''} aria-pressed="${k===state.key}">${x.name}${x.unlock>unlocked?' · locked':''}</button>`).join('');$('.aqc-policies',root).innerHTML=Object.entries(policies).map(([k,p])=>`<button class="aqc-policy" data-policy="${k}" ${state.policy&&state.policy!==k?'disabled':''} aria-pressed="${state.policy===k}"><strong>${p.name}</strong><small>${p.cost} budget · ${p.detail}</small></button>`).join('');$('[data-promise]',root).textContent=state.promise?`${state.promise.name}: deliver ${state.promise.target} supply this season.`:`No promise recorded for season ${state.turn+1}.`;$$('[data-action]',root).forEach(b=>{b.disabled=state.finished&&b.dataset.action!=='restart';});}
    root.addEventListener('click',e=>{const cell=e.target.closest('[data-cell]');if(cell)select(Number(cell.dataset.cell));const sc=e.target.closest('[data-scenario]');if(sc)begin(sc.dataset.scenario);const pol=e.target.closest('[data-policy]');if(pol)enactPolicy(pol.dataset.policy);const a=e.target.closest('[data-action]')?.dataset.action;if(['pump','conserve','recharge','trade'].includes(a))act(a);if(a==='promise')makePromise();if(a==='advance')advance();if(a==='forecast')forecast();if(a==='recover')recover();if(a==='submit')finish();if(a==='restart')begin(state.key);});
    const keydown=e=>{if(!dialog.open)return;if(['ArrowRight','ArrowDown'].includes(e.key)){e.preventDefault();select(state.selected+1);}if(['ArrowLeft','ArrowUp'].includes(e.key)){e.preventDefault();select(state.selected-1);}const k=e.key.toLowerCase();if(k==='p')act('pump');if(k==='c')act('conserve');if(k==='b')act('recharge');if(k==='t')act('trade');if(k==='m')makePromise();if(k==='f')forecast();if(e.key===' '){e.preventDefault();advance();}if(k==='e')recover();if(e.key==='Enter')finish();if(k==='r')begin(state.key);};window.addEventListener('keydown',keydown);dialog.addEventListener('close',()=>{window.removeEventListener('keydown',keydown);$('#aqc-style')?.remove();},{once:true});begin('valley');
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();