(() => {
  const APP={name:'Battery Bazaar',emoji:'🔋',category:'play',version:'1.0.0',summary:'Run a tiny home microgrid by trading solar, battery charge, comfort, and blackout risk.',description:'A local energy-management strategy game with hourly weather and price shifts, battery and comfort tradeoffs, storm-mode unlock, scoring, recovery choices, keyboard and touch controls, reduced-motion behavior, optional audio, and teardown.'};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s)),label=v=>v==='play'?'Play':v==='useful'?'Useful':'Experiment';
  function css(){if($('#battery-bazaar-styles'))return;const st=document.createElement('style');st.id='battery-bazaar-styles';st.textContent=`
  .bb-card{animation:bb-in .22s ease both}.bb-game{max-width:1100px;gap:14px}.bb-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.bb-stat,.bb-board,.bb-panel,.bb-log{border:1px solid var(--line);border-radius:18px;background:#fff}.bb-stat{padding:10px 12px}.bb-stat span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.bb-stat strong{display:block;margin-top:4px}.bb-layout{display:grid;grid-template-columns:1.12fr .88fr;gap:12px}.bb-board{position:relative;min-height:440px;overflow:hidden;background:linear-gradient(145deg,#082f49,#14532d);color:white}.bb-sky{position:absolute;inset:0;background:radial-gradient(circle at var(--sun,22%) 18%,#fde68a 0 6%,transparent 7%),linear-gradient(180deg,rgba(56,189,248,.5),transparent 55%)}.bb-grid{position:absolute;inset:28px;display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.bb-node{border:1px solid rgba(255,255,255,.32);border-radius:20px;display:grid;place-items:center;text-align:center;padding:12px;background:rgba(255,255,255,.12);backdrop-filter:blur(4px)}.bb-node strong{font-size:clamp(1.1rem,3vw,2rem)}.bb-flow{position:absolute;height:8px;border-radius:999px;background:rgba(250,204,21,.78);box-shadow:0 0 18px rgba(250,204,21,.55);transform-origin:left center}.bb-panel{padding:14px;display:grid;gap:12px}.bb-actions,.bb-modes{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.bb-actions button,.bb-modes button{min-height:44px;border:1px solid var(--line);border-radius:14px;background:#fff;font-weight:900}.bb-modes button.is-active{box-shadow:0 0 0 3px #facc15 inset}.bb-bar{height:13px;border-radius:999px;background:#e5e7eb;overflow:hidden}.bb-bar span{display:block;height:100%;width:0;background:linear-gradient(90deg,#22c55e,#facc15)}.bb-log{min-height:112px;padding:17px 19px}.bb-help{font-size:.88rem;color:var(--muted)}.bb-actions button:focus-visible,.bb-modes button:focus-visible{outline:4px solid var(--accent);outline-offset:2px}@media(max-width:900px){.bb-layout{grid-template-columns:1fr}.bb-hud{grid-template-columns:repeat(2,1fr)}.bb-board{min-height:380px}}@media(max-width:560px){.bb-panel{padding:9px}.bb-board{min-height:330px}.bb-grid{inset:14px;grid-template-columns:1fr 1fr}.bb-actions,.bb-modes{grid-template-columns:1fr 1fr}.bb-hud{gap:6px}.bb-stat{padding:8px}}@media(prefers-reduced-motion:reduce){.bb-card{animation:none!important}.bb-flow{transition:none!important}}@keyframes bb-in{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}`;document.head.append(st);}
  function addCard(){const grid=$('#app-grid'),template=$('#app-card-template');if(!grid||!template||$('[data-battery-bazaar-card]'))return;const f=$('.filter.is-active')?.dataset.filter||'all';if(f!=='all'&&f!==APP.category)return;css();const node=template.content.cloneNode(true),card=$('.app-card',node);card.dataset.category=APP.category;card.dataset.batteryBazaarCard='true';card.classList.add('bb-card');$('.app-icon',node).textContent=APP.emoji;$('.app-meta',node).textContent=`${label(APP.category)} · v${APP.version}`;$('.app-name',node).textContent=APP.name;$('.app-summary',node).textContent=APP.summary;const b=$('.app-card-button',node);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);grid.append(node);}
  function boot(){css();let tries=0;const retry=()=>{addCard();if(!$('[data-battery-bazaar-card]')&&tries++<20)setTimeout(retry,120);};retry();$$('.filter').forEach(b=>{if(b.dataset.bbRefresh)return;b.dataset.bbRefresh='1';b.addEventListener('click',()=>setTimeout(addCard,0));});}
  function open(){const dialog=$('#app-dialog'),stage=$('#app-stage');if(!dialog||!stage)return;$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent=`${label(APP.category)} · ${APP.emoji}`;$('#dialog-description').textContent=APP.description;$('#dialog-feedback').href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Battery%20Bazaar';stage.replaceChildren();game(stage,dialog);dialog.showModal();}
  function game(stage,dialog){
    const root=document.createElement('section');root.className='tool-panel bb-game';root.innerHTML=`<div class="bb-hud"><div class="bb-stat"><span>Hour</span><strong id="bb-hour">6</strong></div><div class="bb-stat"><span>Solar</span><strong id="bb-solar">0</strong></div><div class="bb-stat"><span>Battery</span><strong id="bb-battery">50</strong></div><div class="bb-stat"><span>Comfort</span><strong id="bb-comfort">80</strong></div><div class="bb-stat"><span>Credits</span><strong id="bb-credits">0</strong></div><div class="bb-stat"><span>Score</span><strong id="bb-score">0</strong></div></div><div class="bb-layout"><div class="bb-board" aria-label="Animated microgrid board"><div class="bb-sky"></div><div class="bb-grid"><div class="bb-node"><strong>☀️</strong><span>Roof solar</span></div><div class="bb-node"><strong>🏠</strong><span>Home load</span></div><div class="bb-node"><strong>🔋</strong><span>Battery bank</span></div><div class="bb-node"><strong>⚡</strong><span>Street grid</span></div></div><div class="bb-flow" id="bb-flow"></div></div><div class="bb-panel"><div class="bb-modes" aria-label="Contracts"></div><p class="bb-help">Each hour, route energy before advancing. Home protects comfort, battery protects evening peaks, and grid sales earn credits but can leave you exposed. Keys: H home, B battery, G grid, N next, R reset, S sound.</p><div><strong>Battery reserve</strong><div class="bb-bar"><span id="bb-bar"></span></div></div><div class="bb-actions"><button data-act="home" type="button">To home</button><button data-act="battery" type="button">To battery</button><button data-act="grid" type="button">Sell grid</button><button data-act="next" type="button">Next hour</button><button data-act="reset" type="button">Reset</button><button data-act="sound" type="button" aria-pressed="false">Sound off</button></div><div class="bb-log result-card" aria-live="polite"><strong>Open the morning market.</strong><small>Route solar and stored charge through one day without losing comfort.</small></div></div></div>`;stage.append(root);
    const modes={family:{name:'Family plan',demand:12,goal:70},frugal:{name:'Frugal bid',demand:9,goal:58},storm:{name:'Storm watch',demand:14,goal:76,locked:true}};const weather=['clear','clear','cloud','clear','heat','cloud','peak','peak','dusk','night','night','night'];
    const st={mode:'family',hour:6,step:0,battery:50,comfort:82,credits:0,score:0,solar:0,route:'home',unlocked:false,played:0,sound:false,ac:null,closed:false};
    const log=$('.bb-log',root),flow=$('#bb-flow',root);
    function tone(kind){if(!st.sound)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;st.ac ||= new A();st.ac.resume();const o=st.ac.createOscillator(),g=st.ac.createGain();o.type=kind==='bad'?'square':'sine';o.frequency.value=kind==='win'?720:kind==='move'?440:190;g.gain.setValueAtTime(.0001,st.ac.currentTime);g.gain.exponentialRampToValueAtTime(.04,st.ac.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,st.ac.currentTime+.18);o.connect(g).connect(st.ac.destination);o.start();o.stop(st.ac.currentTime+.2);}
    function note(a,b='Balance comfort, reserve, and credits before the evening peak.'){log.innerHTML=`<strong>${a}</strong><small>${b}</small>`;}
    function solarFor(){const w=weather[st.step]||'night';return Math.max(0,{clear:18,cloud:8,heat:22,peak:4,dusk:2,night:0}[w]+(st.mode==='storm'&&st.step>5?-4:0));}
    function price(){return st.step>6&&st.step<10?5:st.step<4?2:3;}
    function setRoute(r){st.route=r;note(r==='home'?'Solar routed home.':r==='battery'?'Solar routed to battery.':'Solar offered to the grid.',`Next hour will use the ${r} priority. Demand is ${modes[st.mode].demand}, price is ${price()} credits.`);tone('move');render();}
    function next(){if(st.step>=11){finish();return;}const d=modes[st.mode].demand,s=st.solar;let used=0;if(st.route==='home'){used=Math.min(s,d);st.comfort+=used>=d?3:-6;st.battery-=Math.max(0,d-used);}else if(st.route==='battery'){st.battery+=Math.floor(s*.8);st.battery-=d;st.comfort-=st.battery<18?8:1;}else{st.credits+=s*price();st.battery-=d;st.comfort-=st.battery<22?10:3;}if(weather[st.step]==='heat')st.comfort-=6;if(weather[st.step]==='peak')st.credits-=Math.max(0,18-st.battery);st.battery=Math.max(0,Math.min(100,st.battery));st.comfort=Math.max(0,Math.min(100,st.comfort));st.step++;st.hour++;st.solar=solarFor();st.score=Math.round(st.credits+st.comfort+st.battery*.7);note(`${weather[st.step]||'midnight'} hour begins.`,st.battery<15?'Reserve is low. Recover by routing to battery or comfort will fall.':'Choose a route, then advance.');tone(st.battery<10?'bad':'move');render();}
    function finish(){const goal=modes[st.mode].goal,pass=st.comfort>=goal&&st.battery>18;st.played++;st.score=Math.round(st.score+(pass?80:0));if(pass&&st.played>1&&!st.unlocked){st.unlocked=true;note('Storm watch unlocked.','A harder contract now cuts solar during the evening peak.');}else note(pass?`Contract cleared: ${st.score}.`:`Contract missed: ${st.score}.`,pass?'Replay for better credits without draining reserve.':'Recover by keeping more reserve before peak hours.');tone(pass?'win':'bad');render();}
    function reset(mode=st.mode){st.mode=mode;st.hour=6;st.step=0;st.battery=50;st.comfort=82;st.credits=0;st.score=0;st.route='home';st.solar=solarFor();note(`${modes[st.mode].name} ready.`,`Keep comfort above ${modes[st.mode].goal} and finish with reserve.`);render();}
    function render(){st.solar=solarFor();$('#bb-hour',root).textContent=st.hour>17?'Done':`${st.hour}:00`;$('#bb-solar',root).textContent=st.solar;$('#bb-battery',root).textContent=st.battery;$('#bb-comfort',root).textContent=st.comfort;$('#bb-credits',root).textContent=st.credits;$('#bb-score',root).textContent=st.score;$('#bb-bar',root).style.width=`${st.battery}%`;$('.bb-sky',root).style.setProperty('--sun',`${15+st.step*7}%`);flow.style.width=`${80+st.solar*5}px`;flow.style.left=st.route==='home'?'16%':st.route==='battery'?'38%':'62%';flow.style.top=st.route==='grid'?'73%':'50%';const modeBox=$('.bb-modes',root);modeBox.innerHTML='';Object.entries(modes).forEach(([k,v])=>{const b=document.createElement('button');b.type='button';b.textContent=v.locked&&!st.unlocked?'Locked':v.name;b.disabled=!!(v.locked&&!st.unlocked);b.className=k===st.mode?'is-active':'';b.onclick=()=>reset(k);modeBox.append(b);});$$('[data-act]',root).forEach(b=>{b.onclick=()=>({home:()=>setRoute('home'),battery:()=>setRoute('battery'),grid:()=>setRoute('grid'),next,reset:()=>reset(),sound:()=>{st.sound=!st.sound;b.textContent=st.sound?'Sound on':'Sound off';b.setAttribute('aria-pressed',String(st.sound));tone('win');}}[b.dataset.act]());});}
    const keys=e=>{if(!dialog.open||!root.isConnected)return;const k=e.key.toLowerCase();if({h:'home',b:'battery',g:'grid'}[k])setRoute({h:'home',b:'battery',g:'grid'}[k]);if(k==='n')next();if(k==='r')reset();if(k==='s')$('[data-act="sound"]',root).click();};
    document.addEventListener('keydown',keys);dialog.addEventListener('close',()=>{document.removeEventListener('keydown',keys);st.closed=true;try{st.ac?.close();}catch{}},{once:true});reset();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();