(() => {
  const APP={name:'Beacon Builder',emoji:'🔦',category:'play',version:'1.0.0',summary:'Place mirrors and splitters to route lighthouse beams through fog gates before power runs out.',description:'A local optics-routing puzzle with rotatable mirrors, splitters, fog gates, batteries, adaptive rounds, recoverable darkouts, session-only prism mode, scoring, responsive SVG rendering, touch and keyboard controls, optional local audio, reduced-motion behavior, and teardown.'};
  const labelCategory=v=>v==='play'?'Play':v==='useful'?'Useful':'Experiment';
  const filter=()=>document.querySelector('.filter.is-active')?.dataset.filter||'all';
  const eligible=()=>filter()==='all'||filter()===APP.category;
  function installStyles(){ if(document.querySelector('#beacon-builder-styles')) return; const s=document.createElement('style'); s.id='beacon-builder-styles'; s.textContent=`.beacon-card{animation:beacon-rise .28s ease both}.beacon-game{max-width:1040px;gap:14px}.beacon-hud{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.beacon-stat{border:1px solid var(--line);border-radius:15px;background:#fff;padding:10px 12px}.beacon-stat span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.beacon-stat strong{display:block;margin-top:4px;font-size:.98rem}.beacon-board{border:0;border-radius:26px;background:#08111f;color:white;padding:0;overflow:hidden;touch-action:manipulation;box-shadow:inset 0 0 0 1px rgba(255,255,255,.14)}.beacon-board:focus-visible{outline:4px solid var(--accent);outline-offset:4px}.beacon-board svg{display:block;width:100%;height:min(58vh,510px);min-height:360px}.beacon-console{display:grid;grid-template-columns:1fr 1fr;gap:10px}.beacon-panel,.beacon-rules{border:1px solid var(--line);border-radius:18px;background:#fff;padding:13px}.beacon-tools,.beacon-legend{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.beacon-chip,.beacon-legend span{border:1px solid var(--line);border-radius:999px;background:#fff;color:var(--ink);padding:8px 11px;font-weight:900}.beacon-chip.is-active{background:#111827;color:#fff}.beacon-log{min-height:92px;padding:17px 19px}@media(max-width:760px){.beacon-hud{grid-template-columns:repeat(2,1fr)}.beacon-console{grid-template-columns:1fr}.beacon-board svg{height:56vh;min-height:340px}}@media(prefers-reduced-motion:reduce){.beacon-card{animation:none}.beacon-board svg{min-height:330px}}@keyframes beacon-rise{from{opacity:0;transform:translateY(12px) scale(.98)}to{opacity:1;transform:translateY(0) scale(1)}}`; document.head.append(s); }
  function initCard(){ const grid=document.querySelector('#app-grid'),template=document.querySelector('#app-card-template'); if(!grid||!template||document.querySelector('[data-beacon-builder-card]')||!eligible()) return; installStyles(); const node=template.content.cloneNode(true),card=node.querySelector('.app-card'); card.dataset.category=APP.category; card.dataset.beaconBuilderCard='true'; card.classList.add('beacon-card'); node.querySelector('.app-icon').textContent=APP.emoji; node.querySelector('.app-meta').textContent=`${labelCategory(APP.category)} · v${APP.version}`; node.querySelector('.app-name').textContent=APP.name; node.querySelector('.app-summary').textContent=APP.summary; const open=node.querySelector('.app-card-button'); open.setAttribute('aria-label',`Open ${APP.name}`); open.addEventListener('click',openApp); grid.append(node); }
  function wireFilterRefresh(){ document.querySelectorAll('.filter').forEach(b=>{ if(b.dataset.beaconRefresh) return; b.dataset.beaconRefresh='true'; b.addEventListener('click',()=>setTimeout(initCard,0)); }); }
  function openApp(){ const dialog=document.querySelector('#app-dialog'),stage=document.querySelector('#app-stage'),title=document.querySelector('#dialog-title'),category=document.querySelector('#dialog-category'),description=document.querySelector('#dialog-description'),feedback=document.querySelector('#dialog-feedback'); if(!dialog||!stage||!title||!category||!description||!feedback) return; title.textContent=APP.name; category.textContent=`${labelCategory(APP.category)} · ${APP.emoji}`; description.textContent=APP.description; feedback.href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Beacon%20Builder'; stage.replaceChildren(); renderGame(stage,dialog); dialog.showModal(); }
  function renderGame(stage,dialog){
    const root=document.createElement('section'); root.className='tool-panel beacon-game';
    const hud=document.createElement('div'); hud.className='beacon-hud'; hud.innerHTML='<div class="beacon-stat"><span>Round</span><strong id="bb-round">1 / 5</strong></div><div class="beacon-stat"><span>Score</span><strong id="bb-score">0</strong></div><div class="beacon-stat"><span>Power</span><strong id="bb-power">10</strong></div><div class="beacon-stat"><span>Targets</span><strong id="bb-targets">0 / 0</strong></div><div class="beacon-stat"><span>Leaks</span><strong id="bb-leaks">0</strong></div>';
    const board=document.createElement('button'); board.type='button'; board.className='beacon-board'; board.setAttribute('aria-label','Beacon Builder grid. Select a tool, choose a cell, rotate mirrors, then test the beam. Use arrow keys to move, M for mirror, S for splitter, R to rotate, Enter to place or rotate, T to test, Backspace to clear, and N for a new run.'); board.innerHTML='<svg aria-hidden="true" viewBox="0 0 820 540"></svg>';
    const consoleBox=document.createElement('div'); consoleBox.className='beacon-console'; consoleBox.innerHTML='<div class="beacon-panel"><strong>Tools</strong><p>Route light from the tower through every beacon target. Mirrors turn a beam, splitters branch it, fog gates drain power, and leaks cost score.</p><div class="beacon-tools"></div></div><div class="beacon-rules"><strong>Harbor rules</strong><div class="beacon-legend"><span>◎ target</span><span>▒ fog costs 2</span><span>◆ battery restores 2</span><span>× rock blocks</span></div></div>';
    const log=document.createElement('div'); log.className='result-card beacon-log'; log.setAttribute('aria-live','polite'); const foot=document.createElement('div'); foot.className='tool-actions'; root.append(hud,board,consoleBox,log,foot); stage.append(root);
    const svg=board.querySelector('svg'),toolsBox=consoleBox.querySelector('.beacon-tools'),reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    const dirs=[[1,0],[0,1],[-1,0],[0,-1]],toolDefs=[['mirror','Mirror A'],['mirror2','Mirror B'],['split','Splitter'],['clear','Clear']];
    const state={round:1,rounds:5,score:0,power:10,leaks:0,cursor:0,tool:'mirror',grid:[],targets:[],lit:new Set(),beam:[],unlocked:false,prism:false,raf:0,tick:0,audio:false,ac:null};
    toolDefs.forEach(([id,label])=>{ const b=document.createElement('button'); b.type='button'; b.className='beacon-chip'; b.textContent=label; b.dataset.tool=id; b.addEventListener('click',()=>{state.tool=id; renderTools(); draw();}); toolsBox.append(b); });
    const testBtn=makeButton('Test beam',()=>test(true),true),newBtn=makeButton('New run',newRun,true),prismBtn=makeButton('Prism mode',togglePrism,true),soundBtn=makeButton('Sound off',toggleSound,true); foot.append(testBtn,newBtn,prismBtn,soundBtn);
    board.addEventListener('click',place); board.addEventListener('keydown',onKey); board.addEventListener('pointermove',onPointer); dialog.addEventListener('close',teardown,{once:true});
    function makeButton(text,fn,secondary){ const b=document.createElement('button'); b.type='button'; b.className=secondary?'button button-secondary':'button'; b.textContent=text; b.addEventListener('click',fn); return b; }
    function say(html){ log.innerHTML=html; }
    function cell(x,y){ return y*8+x; } function xy(i){ return [i%8,Math.floor(i/8)]; } function inb(x,y){ return x>=0&&x<8&&y>=0&&y<6; }
    function generate(){ state.power=11-state.round+(state.prism?-1:0); state.leaks=0; state.lit=new Set(); state.beam=[]; state.cursor=cell(1,2); state.grid=Array(48).fill(null).map(()=>({kind:'empty',rot:0})); for(let y=0;y<6;y++) state.grid[cell(0,y)]={kind:y===2?'source':'rock',rot:0}; const targetCount=2+(state.round>2?1:0)+(state.prism?1:0); state.targets=[]; for(let i=0;i<targetCount;i++){ const x=5+(i%3), y=(i*2+state.round)%6; state.grid[cell(x,y)]={kind:'target',rot:0}; state.targets.push(cell(x,y)); } for(let i=0;i<5+state.round;i++){ const x=2+((i*3+state.round)%4), y=(i*2+1)%6, idx=cell(x,y); if(state.grid[idx].kind==='empty') state.grid[idx]={kind:i%3===0?'fog':i%4===0?'battery':'rock',rot:0}; } renderTools(); test(false); say(`<strong>Round ${state.round}: light every beacon.</strong><small>Place mirrors or splitters, then test. Failed routes keep the puzzle playable.</small>`); }
    function renderTools(){ toolsBox.querySelectorAll('.beacon-chip').forEach(b=>b.classList.toggle('is-active',b.dataset.tool===state.tool)); updateHud(); }
    function place(){ const c=state.grid[state.cursor]; if(['source','target','rock','fog','battery'].includes(c.kind)){ say('<strong>That cell is reserved.</strong><small>Use open water for mirrors and splitters.</small>'); return; } if(state.tool==='clear'){ state.grid[state.cursor]={kind:'empty',rot:0}; } else if(c.kind===state.tool || (state.tool==='mirror'&&c.kind==='mirror') || (state.tool==='mirror2'&&c.kind==='mirror2')) c.rot=(c.rot+1)%4; else state.grid[state.cursor]={kind:state.tool,rot:0}; test(false); draw(); }
    function rotate(){ const c=state.grid[state.cursor]; if(['mirror','mirror2','split'].includes(c.kind)){ c.rot=(c.rot+1)%4; test(false); draw(); } }
    function test(advance=true){ state.lit=new Set(); state.beam=[]; let queue=[{x:1,y:2,d:0,p:state.power}], leaks=0, guard=0; while(queue.length&&guard++<220){ const ray=queue.shift(); let {x,y,d,p}=ray; while(p>0&&guard++<220){ x+=dirs[d][0]; y+=dirs[d][1]; if(!inb(x,y)){ leaks++; break; } const idx=cell(x,y), c=state.grid[idx]; state.beam.push({x,y,d,p}); if(c.kind==='rock') break; if(c.kind==='fog') p-=2; else if(c.kind==='battery') p+=2; else p--; if(c.kind==='target') state.lit.add(idx); if(c.kind==='mirror') d = c.rot%2===0 ? [3,2,1,0][d] : [1,0,3,2][d]; if(c.kind==='mirror2') d = c.rot%2===0 ? [1,0,3,2][d] : [3,2,1,0][d]; if(c.kind==='split'){ const nd=(d+1+c.rot)%4; queue.push({x,y,d:nd,p:Math.max(1,p-1)}); if(state.prism) queue.push({x,y,d:(d+3)%4,p:Math.max(1,p-2)}); } } }
      state.leaks=leaks; const hit=state.lit.size; if(advance&&hit===state.targets.length){ const gain=120+state.power*8+Math.max(0,50-leaks*10)+state.round*15; state.score+=gain; state.unlocked=state.unlocked||state.score>=520; beep('good'); if(state.round>=state.rounds) say(`<strong>Harbor lit: ${state.score}.</strong><small>${state.unlocked?'Prism mode is unlocked for this session.':'Score 520 to unlock prism mode.'}</small>`); else { state.round++; generate(); } } else if(advance){ state.score=Math.max(0,state.score-8); recover(hit); } updateHud(); draw(); }
    function recover(hit){ beep('bad'); state.power=Math.max(state.power,3); say(`<strong>${hit} of ${state.targets.length} beacons lit.</strong><small>Recovery restored minimum power. Move a mirror, split a beam, or clear a bad cell.</small>`); }
    function updateHud(){ hud.querySelector('#bb-round').textContent=`${state.round} / ${state.rounds}`; hud.querySelector('#bb-score').textContent=state.score; hud.querySelector('#bb-power').textContent=state.power; hud.querySelector('#bb-targets').textContent=`${state.lit.size} / ${state.targets.length||0}`; hud.querySelector('#bb-leaks').textContent=state.leaks; }
    function togglePrism(){ if(!state.unlocked){ say('<strong>Prism mode is locked.</strong><small>Score 520 in a run to add more targets and branching beams.</small>'); return; } state.prism=!state.prism; prismBtn.textContent=state.prism?'Normal mode':'Prism mode'; newRun(); }
    function newRun(){ Object.assign(state,{round:1,score:0,leaks:0}); generate(); }
    function toggleSound(){ const AC=window.AudioContext||window.webkitAudioContext; if(!AC){ say('<strong>Sound is not available here.</strong><small>The beacon puzzle still works silently.</small>'); return; } state.audio=!state.audio; soundBtn.textContent=state.audio?'Sound on':'Sound off'; soundBtn.setAttribute('aria-pressed',String(state.audio)); if(state.audio){ state.ac ||= new AC(); state.ac.resume(); beep('good'); } }
    function beep(kind){ if(!state.audio||!state.ac) return; const now=state.ac.currentTime,o=state.ac.createOscillator(),g=state.ac.createGain(); o.type='sine'; o.frequency.value=kind==='good'?820:kind==='bad'?170:430; g.gain.setValueAtTime(.0001,now); g.gain.exponentialRampToValueAtTime(.045,now+.02); g.gain.exponentialRampToValueAtTime(.0001,now+.18); o.connect(g).connect(state.ac.destination); o.start(now); o.stop(now+.2); }
    function onPointer(e){ const r=board.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*820,y=(e.clientY-r.top)/r.height*540; if(x<90||x>730||y<54||y>534) return; state.cursor=cell(Math.max(0,Math.min(7,Math.floor((x-90)/80))),Math.max(0,Math.min(5,Math.floor((y-54)/80)))); draw(); }
    function onKey(e){ const k=e.key.toLowerCase(), [x,y]=xy(state.cursor); if(k==='arrowright'){e.preventDefault(); state.cursor=cell(Math.min(7,x+1),y); draw();} if(k==='arrowleft'){e.preventDefault(); state.cursor=cell(Math.max(0,x-1),y); draw();} if(k==='arrowdown'){e.preventDefault(); state.cursor=cell(x,Math.min(5,y+1)); draw();} if(k==='arrowup'){e.preventDefault(); state.cursor=cell(x,Math.max(0,y-1)); draw();} if(k==='m'){state.tool=state.tool==='mirror'?'mirror2':'mirror'; renderTools(); draw();} if(k==='s'){state.tool='split'; renderTools(); draw();} if(k==='backspace'||k==='delete'){e.preventDefault(); state.tool='clear'; place();} if(k==='r'){e.preventDefault(); rotate();} if(k==='enter'||k===' '){e.preventDefault(); place();} if(k==='t'){e.preventDefault(); test(true);} if(k==='n'){e.preventDefault(); newRun();} }
    function icon(c,i){ if(c.kind==='source') return '☀'; if(c.kind==='target') return state.lit.has(i)?'◉':'◎'; if(c.kind==='rock') return '×'; if(c.kind==='fog') return '▒'; if(c.kind==='battery') return '◆'; if(c.kind==='split') return 'Y'; if(c.kind==='mirror') return c.rot%2===0?'/':'╱'; if(c.kind==='mirror2') return c.rot%2===0?'|':'╲'; return ''; }
    function draw(){ const beamLines=state.beam.slice(-90).map((b,n)=>{ const x=130+b.x*80,y=94+b.y*80,dx=dirs[b.d][0]*30,dy=dirs[b.d][1]*30,op=Math.max(.2,1-n/100); return `<line x1="${x-dx/2}" y1="${y-dy/2}" x2="${x+dx/2}" y2="${y+dy/2}" stroke="#fef08a" stroke-width="6" stroke-linecap="round" opacity="${op}"/>`; }).join(''); const cells=state.grid.map((c,i)=>{ const [x,y]=xy(i),px=90+x*80,py=54+y*80,cur=i===state.cursor; return `<g><rect x="${px+5}" y="${py+5}" width="70" height="70" rx="16" fill="${cur?'#1e40af':c.kind==='empty'?'#102033':c.kind==='target'?'#134e4a':c.kind==='rock'?'#334155':c.kind==='fog'?'#475569':c.kind==='battery'?'#4a2d09':'#172554'}" stroke="${cur?'#93c5fd':'rgba(255,255,255,.18)'}" stroke-width="${cur?4:1}"/><text x="${px+40}" y="${py+48}" text-anchor="middle" font-size="30" fill="#fff" font-weight="900">${icon(c,i)}</text></g>`; }).join(''); svg.innerHTML=`<rect width="820" height="540" fill="#08111f"/><text x="96" y="34" fill="#bfdbfe" font-size="17" font-weight="900">Beacon Builder</text>${cells}${beamLines}<text x="90" y="528" fill="#cbd5e1" font-size="14">Tool: ${toolDefs.find(t=>t[0]===state.tool)?.[1]||'Mirror'} · Test with T · Rotate with R</text>`; updateHud(); }
    function loop(){ if(!reduced){ if(state.beam.length) draw(); state.raf=requestAnimationFrame(loop); } }
    function teardown(){ cancelAnimationFrame(state.raf); if(state.ac&&state.ac.state!=='closed') state.ac.close().catch(()=>{}); }
    generate(); draw(); if(!reduced) state.raf=requestAnimationFrame(loop);
  }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',()=>{ initCard(); wireFilterRefresh(); }); else { initCard(); wireFilterRefresh(); }
})();
