(() => {
  'use strict';
  const APP={name:'Bindery Bench',emoji:'📚',category:'play',version:'1.0.0',summary:'Build commissioned books by arranging signatures, matching grain, choosing stitches, balancing glue, tension, cover stock, press time, and limited materials.',description:'A local-only bookbinding strategy game with six commissions, signature sequencing, paper grain, stitch and cover systems, glue and tension controls, inventory, coins, trust, scoring, a session unlock, failure, one costly recovery, touch, keyboard controls, reduced motion, and teardown.'};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const SIGNATURES=[{name:'Text',icon:'▤',grain:'long',pages:16,cost:1},{name:'Image',icon:'▧',grain:'short',pages:12,cost:2},{name:'Foldout',icon:'↔',grain:'long',pages:8,cost:3},{name:'Endpaper',icon:'◇',grain:'short',pages:4,cost:1}];
  const STITCHES=[{name:'Pamphlet',strength:48,flex:82,cost:1},{name:'Kettle',strength:76,flex:64,cost:2},{name:'Coptic',strength:68,flex:92,cost:3},{name:'Tape',strength:92,flex:46,cost:3}];
  const COVERS=[{name:'Paper wrap',durability:42,weight:1,cost:1},{name:'Book cloth',durability:72,weight:2,cost:2},{name:'Board case',durability:94,weight:4,cost:4}];
  const JOBS=[
    {brief:'A slim poetry chapbook should open freely.',need:['Text','Endpaper'],pages:20,flex:76,durability:35,grain:'long',budget:8,target:70},
    {brief:'A field guide needs images and durable handling.',need:['Text','Image','Endpaper'],pages:32,flex:56,durability:68,grain:'long',budget:11,target:73},
    {brief:'An exhibition catalog must preserve a foldout.',need:['Text','Image','Foldout'],pages:36,flex:62,durability:70,grain:'short',budget:13,target:76},
    {brief:'A recipe journal should lie flat under use.',need:['Text','Text','Endpaper'],pages:36,flex:84,durability:72,grain:'long',budget:12,target:79},
    {brief:'An archive facsimile demands strength and clean alignment.',need:['Text','Image','Text','Endpaper'],pages:48,flex:58,durability:86,grain:'short',budget:15,target:82},
    {brief:'The final artist book combines every material without bulk failure.',need:['Endpaper','Image','Foldout','Text','Endpaper'],pages:44,flex:78,durability:88,grain:'long',budget:18,target:86}
  ];
  function style(){if($('#bindery-bench-style'))return;const e=document.createElement('style');e.id='bindery-bench-style';e.textContent=`.bindery-bench{max-width:1120px;display:grid;gap:12px}.bb-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.bb-stat,.bb-card{border:1px solid var(--line);border-radius:17px;background:#fff}.bb-stat{padding:9px}.bb-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.bb-layout{display:grid;grid-template-columns:1.1fr .9fr;gap:12px}.bb-card{padding:15px}.bb-book{min-height:350px;border-radius:24px;background:linear-gradient(145deg,#f4ead8,#d8c3a5);padding:18px;display:grid;align-content:center;gap:12px;overflow:hidden;position:relative}.bb-book:before{content:'';position:absolute;inset:0;background:repeating-linear-gradient(90deg,transparent 0 48px,rgba(86,54,32,.08) 49px 50px);pointer-events:none}.bb-stack{position:relative;z-index:1;display:grid;gap:7px}.bb-slot{min-height:54px;border:2px dashed rgba(79,50,28,.35);border-radius:12px;background:rgba(255,255,255,.52);padding:9px;text-align:left;font-weight:850}.bb-slot[aria-pressed=true]{border-style:solid;background:#fff8e8}.bb-slot:focus-visible{outline:4px solid #254d5b;outline-offset:2px}.bb-thread{position:absolute;left:36px;top:20px;bottom:20px;width:4px;background:#8b2e2e;border-radius:999px;opacity:.7}.bb-controls{display:grid;gap:10px}.bb-picks{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.bb-pick{min-height:52px;border:1px solid var(--line);border-radius:12px;background:#fff;padding:9px;text-align:left;font-weight:800}.bb-pick[aria-pressed=true]{background:#fef3c7;border-color:#92400e}.bb-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.bb-actions button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800;padding:9px}.bb-actions .primary{background:#fde68a;border-color:#92400e}.bb-log{min-height:112px}.bb-hint{font-size:.72rem;color:var(--muted);margin:0}.bb-ranges{display:grid;grid-template-columns:1fr 1fr;gap:8px}.bb-ranges label{font-size:.78rem;font-weight:800}.bb-ranges output{float:right}@media(max-width:820px){.bb-layout{grid-template-columns:1fr}.bb-hud{grid-template-columns:repeat(3,1fr)}.bb-book{min-height:310px}}@media(max-width:520px){.bb-hud{grid-template-columns:repeat(2,1fr)}.bb-picks,.bb-actions,.bb-ranges{grid-template-columns:1fr 1fr}.bb-book{padding:12px;min-height:290px}.bb-slot{min-height:50px}}@media(prefers-reduced-motion:reduce){.bindery-bench *{animation:none!important;transition:none!important}}`;document.head.append(e)}
  function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-bindery-bench]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.binderyBench='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
  function boot(){style();let n=0;const r=()=>{card();if(!$('[data-bindery-bench]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.bbBound)return;b.dataset.bbBound='1';b.addEventListener('click',()=>setTimeout(card))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · bookbinding craft strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel bindery-bench';root.innerHTML=`<div class="bb-hud">${['Job','Coins','Trust','Score','Stock','Unlock'].map((x,i)=>`<div class="bb-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="bb-layout"><section class="bb-card"><div class="bb-book" aria-label="Book signature assembly"><i class="bb-thread" aria-hidden="true"></i><div class="bb-stack"></div></div><p class="bb-hint">Choose a signature, then choose a slot. Arrow keys move through slots. Enter places or removes the selected signature.</p></section><aside class="bb-card bb-controls"><div class="result-card bb-log" aria-live="polite"></div><div><p class="eyebrow">Signature stock</p><div class="bb-picks"></div></div><label>Stitch <select data-stitch></select></label><label>Cover <select data-cover></select></label><div class="bb-ranges"><label>Thread tension <output data-tension-out></output><input data-tension type="range" min="1" max="5" value="3"></label><label>Glue coat <output data-glue-out></output><input data-glue type="range" min="0" max="4" value="2"></label><label>Press time <output data-press-out></output><input data-press type="range" min="1" max="5" value="3"></label><label>Grain plan <select data-grain><option value="long">Long</option><option value="short">Short</option></select></label></div><div class="bb-actions"><button class="primary" data-a="bind">Bind edition</button><button data-a="undo">Undo placement</button><button data-a="clear">Clear bench</button><button data-a="recover">Buy remnant kit</button><button data-a="restart">New bindery day</button></div></aside></div>`;stage.append(root);let st,timer=0,ended=false;
    function reset(){clearTimeout(timer);st={job:0,coins:28,trust:75,score:0,stock:14,unlock:false,recovery:true,selected:0,slots:Array(5).fill(null),history:[],stitch:0,cover:0,tension:3,glue:2,press:3,grain:'long'};ended=false;fillSelects();log(JOBS[0].brief,'Arrange the requested signatures, then balance flexibility, durability, grain, adhesive, and cost.');draw()}
    function fillSelects(){const a=$('[data-stitch]',root),b=$('[data-cover]',root);a.innerHTML=STITCHES.map((x,i)=>`<option value="${i}">${x.name}</option>`).join('');b.innerHTML=COVERS.map((x,i)=>`<option value="${i}">${x.name}</option>`).join('')+(st.unlock?'<option value="3">Linen laminate</option>':'')}
    function place(i){if(ended)return;st.history.push([...st.slots]);st.slots[i]=st.slots[i]===st.selected?null:st.selected;draw()}
    function evaluate(){const job=JOBS[st.job],chosen=st.slots.filter(x=>x!=null).map(i=>SIGNATURES[i]),names=chosen.map(x=>x.name);let quality=100,cost=STITCHES[st.stitch].cost+(st.cover===3?5:COVERS[st.cover].cost)+chosen.reduce((a,x)=>a+x.cost,0)+Math.ceil(st.glue/2);const pages=chosen.reduce((a,x)=>a+x.pages,0);job.need.forEach(n=>{const at=names.indexOf(n);if(at<0)quality-=18;else names.splice(at,1)});quality-=Math.abs(pages-job.pages)*1.2;const cover=st.cover===3?{durability:98,weight:2}:COVERS[st.cover],stitch=STITCHES[st.stitch];const flex=clamp(stitch.flex-st.glue*7-cover.weight*3+st.press*2,0,100);const durability=clamp((stitch.strength+cover.durability)/2+st.glue*5-Math.abs(st.tension-3)*6,0,100);quality-=Math.abs(flex-job.flex)*.45;quality-=Math.abs(durability-job.durability)*.42;quality-=chosen.filter(x=>x.grain!==st.grain).length*8;if(st.grain!==job.grain)quality-=9;if(st.tension===1||st.tension===5)quality-=12;if(st.press<2&&st.glue>2)quality-=14;quality=clamp(Math.round(quality),0,100);return{quality,cost,pages,flex:Math.round(flex),durability:Math.round(durability),used:chosen.length}}
    function bind(){if(ended)return;const out=evaluate(),job=JOBS[st.job];if(!out.used)return log('The bench is empty.','Place at least one signature before binding.');if(out.cost>st.coins)return log('This edition exceeds available coins.','Choose simpler materials or use the remnant kit.');if(out.used>st.stock)return log('Not enough signature stock remains.','Reduce the edition or use the remnant kit.');st.coins-=out.cost;st.stock-=out.used;$$('[data-a]',root).forEach(b=>b.disabled=true);timer=setTimeout(()=>{if(!root.isConnected)return;st.score+=out.quality*15+out.pages*4;st.trust=clamp(st.trust+(out.quality>=job.target?9:out.quality<55?-22:-7),0,100);if(st.score>=3500&&!st.unlock){st.unlock=true;fillSelects()}if(st.trust<=0||st.coins<=0||st.stock<=0)return finish(false);if(st.job>=JOBS.length-1)return finish(true);st.job++;st.slots=Array(5).fill(null);st.history=[];log(out.quality>=job.target?'The edition opens cleanly and holds its shape.':out.quality>=58?'The book is usable, but the spine shows compromise.':'The binding pulls, buckles, or sheds pages.',`Quality ${out.quality}; flex ${out.flex}; durability ${out.durability}. Next: ${JOBS[st.job].brief}`);draw()},window.matchMedia('(prefers-reduced-motion: reduce)').matches?80:760)}
    function recover(){if(ended||!st.recovery)return;st.recovery=false;st.coins=clamp(st.coins-7,0,99);st.trust=clamp(st.trust-12,0,100);st.stock+=6;log('A remnant kit restores paper stock.','The mixed leftovers save the run, but cost coins and client confidence.');draw()}
    function finish(success){ended=true;clearTimeout(timer);const strong=success&&st.trust>=62&&st.score>=7600;log(strong?'The bindery earns a conservation commission.':success?'The final edition ships with a fragile reputation.':'The bindery closes after repeated structural failures.',`Final score ${st.score}, trust ${st.trust}, coins ${st.coins}, stock ${st.stock}. Replay with tighter sequencing and material matching.`);draw()}
    function log(a,b){const l=$('.bb-log',root);l.replaceChildren(Object.assign(document.createElement('strong'),{textContent:a}),Object.assign(document.createElement('small'),{textContent:b}))}
    function draw(){const vals=[`${st.job+1}/6`,st.coins,st.trust,st.score,st.stock,st.unlock?'Linen cover':'Locked'];$$('[data-h]',root).forEach((e,i)=>e.textContent=vals[i]);$('.bb-picks',root).innerHTML=SIGNATURES.map((x,i)=>`<button class="bb-pick" data-pick="${i}" aria-pressed="${st.selected===i}">${x.icon} ${x.name}<small> · ${x.pages}p · ${x.grain}</small></button>`).join('');$('.bb-stack',root).innerHTML=st.slots.map((idx,i)=>{const x=idx==null?null:SIGNATURES[idx];return `<button class="bb-slot" data-slot="${i}" aria-pressed="${idx!=null}" aria-label="Signature slot ${i+1}${x?`, ${x.name}`:', empty'}">${x?`${i+1}. ${x.icon} ${x.name} · ${x.pages} pages · ${x.grain} grain`:`${i+1}. Place signature`}</button>`}).join('');$('[data-stitch]',root).value=st.stitch;$('[data-cover]',root).value=st.cover;$('[data-tension]',root).value=st.tension;$('[data-glue]',root).value=st.glue;$('[data-press]',root).value=st.press;$('[data-grain]',root).value=st.grain;$('[data-tension-out]',root).textContent=st.tension;$('[data-glue-out]',root).textContent=st.glue;$('[data-press-out]',root).textContent=st.press;$$('[data-a]',root).forEach(b=>b.disabled=ended);$('[data-a="undo"]',root).disabled=ended||!st.history.length;$('[data-a="recover"]',root).disabled=ended||!st.recovery;bindEvents()}
    function bindEvents(){$$('[data-pick]',root).forEach(b=>b.onclick=()=>{st.selected=+b.dataset.pick;draw()});$$('[data-slot]',root).forEach((b,i)=>{b.onclick=()=>place(i);b.onkeydown=e=>{if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft'].includes(e.key)){e.preventDefault();const d=e.key==='ArrowDown'||e.key==='ArrowRight'?1:-1;$$('[data-slot]',root)[(i+d+5)%5].focus()}}});$('[data-stitch]',root).onchange=e=>st.stitch=+e.target.value;$('[data-cover]',root).onchange=e=>st.cover=+e.target.value;$('[data-grain]',root).onchange=e=>st.grain=e.target.value;[['tension','tension'],['glue','glue'],['press','press']].forEach(([sel,key])=>$(`[data-${sel}]`,root).oninput=e=>{st[key]=+e.target.value;draw()});$('[data-a="bind"]',root).onclick=bind;$('[data-a="undo"]',root).onclick=()=>{if(st.history.length){st.slots=st.history.pop();draw()}};$('[data-a="clear"]',root).onclick=()=>{st.history.push([...st.slots]);st.slots=Array(5).fill(null);draw()};$('[data-a="recover"]',root).onclick=recover;$('[data-a="restart"]',root).onclick=reset}
    dialog.addEventListener('close',()=>clearTimeout(timer),{once:true});reset()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
