(() => {
  'use strict';
  const APP={name:'Blackout Atlas',emoji:'⚡',category:'play',version:'1.0.0',summary:'Restore a storm-damaged microgrid by scouting faults, routing crews, and protecting critical loads.',description:'A local-only network restoration strategy game with procedural damage, hidden faults, power propagation, limited crews and parts, batteries, cascading outages, critical facilities, scoring, failure, recovery, touch, keyboard, mobile, reduced-motion, and teardown support.'};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const N=5, DIR=[[1,0],[-1,0],[0,1],[0,-1]], TYPES=['home','home','home','clinic','shelter','water'];
  function style(){if($('#blackout-atlas-style'))return;const e=document.createElement('style');e.id='blackout-atlas-style';e.textContent=`.blackout-atlas{max-width:1080px;display:grid;gap:12px}.ba-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.ba-stat,.ba-card{border:1px solid var(--line);border-radius:16px;background:#fff}.ba-stat{padding:8px}.ba-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.ba-layout{display:grid;grid-template-columns:1.15fr .85fr;gap:12px}.ba-card{padding:14px}.ba-grid{display:grid;grid-template-columns:repeat(5,minmax(48px,1fr));gap:6px}.ba-cell{aspect-ratio:1;border:2px solid #cbd5e1;border-radius:12px;background:#f8fafc;display:grid;place-items:center;position:relative;font-size:1.45rem}.ba-cell[data-state=powered]{background:#ecfccb;border-color:#65a30d}.ba-cell[data-state=damaged]{background:#fff1f2;border-color:#e11d48}.ba-cell[data-state=unknown]{background:#f1f5f9;border-style:dashed}.ba-cell[aria-pressed=true]{outline:3px solid #0284c7;outline-offset:2px}.ba-cell small{position:absolute;bottom:3px;font-size:.58rem;font-weight:900}.ba-cell .ba-badge{position:absolute;top:3px;right:4px;font-size:.7rem}.ba-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.blackout-atlas button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;color:inherit;font-weight:800;padding:9px}.blackout-atlas button.primary,.blackout-atlas button[aria-pressed=true]{background:#e0f2fe;border-color:#0284c7}.blackout-atlas button:disabled{opacity:.45}.ba-log{min-height:92px}.ba-legend{display:flex;flex-wrap:wrap;gap:6px}.ba-tag{padding:4px 8px;border-radius:999px;background:#eef2ff;font-size:.72rem}.ba-meter{height:10px;background:#e2e8f0;border-radius:999px;overflow:hidden}.ba-meter span{display:block;height:100%;background:linear-gradient(90deg,#dc2626,#f59e0b,#16a34a);transition:width .25s}.ba-pulse{animation:baPulse .35s ease}@keyframes baPulse{50%{transform:scale(1.015)}}@media(max-width:820px){.ba-layout{grid-template-columns:1fr}.ba-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.ba-hud{grid-template-columns:repeat(2,1fr)}.ba-grid{gap:4px}.ba-cell{min-width:0;border-radius:9px;font-size:1.15rem}.ba-actions{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){.blackout-atlas *{animation:none!important;transition:none!important}}`;document.head.append(e)}
  function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-blackout-atlas]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.blackoutAtlas='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
  function boot(){style();let n=0;const r=()=>{card();if(!$('[data-blackout-atlas]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.baBound)return;b.dataset.baBound='1';b.addEventListener('click',()=>setTimeout(card))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · restoration strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel blackout-atlas';root.innerHTML=`<div class="ba-hud">${['Turn','Crews','Parts','Batteries','Trust','Powered'].map((x,i)=>`<div class="ba-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="ba-layout"><section class="ba-card"><p class="eyebrow">Storm map</p><h3>Reconnect the district</h3><div class="ba-grid" role="grid" aria-label="Five by five restoration map" data-grid></div><div class="ba-legend"><span class="ba-tag">⚡ plant</span><span class="ba-tag">🏥 clinic</span><span class="ba-tag">🛟 shelter</span><span class="ba-tag">💧 water</span><span class="ba-tag">🔋 battery</span></div><p><small>Choose a cell, then inspect, repair, or deploy a battery. Arrow keys move between cells.</small></p></section><aside class="ba-card"><p class="eyebrow">Dispatch board</p><div class="ba-meter" aria-label="District power restored"><span data-meter></span></div><h3 data-target>Select a cell</h3><p data-detail>Unknown line conditions remain after the storm.</p><div class="ba-actions"><button data-a="inspect">Inspect line<br><small>1 crew</small></button><button class="primary" data-a="repair">Repair line<br><small>1 crew · 1 part</small></button><button data-a="battery">Deploy battery<br><small>1 battery</small></button><button data-a="advance">End turn<br><small>storm may worsen</small></button><button data-a="recover">Call mutual aid<br><small>once · costs trust</small></button><button data-a="restart">New storm</button></div><h3>Dispatch record</h3><div class="result-card ba-log" aria-live="polite"></div></aside></div>`;stage.append(root);
    let cells,st,selected=0,ended=false;
    const idx=(r,c)=>r*N+c, rc=i=>[Math.floor(i/N),i%N], neighbors=i=>{const [r,c]=rc(i);return DIR.map(([dr,dc])=>[r+dr,c+dc]).filter(([a,b])=>a>=0&&a<N&&b>=0&&b<N).map(([a,b])=>idx(a,b))};
    const label=t=>({plant:'Power plant',clinic:'Clinic',shelter:'Shelter',water:'Water station',home:'Homes'}[t]);
    const icon=t=>({plant:'⚡',clinic:'🏥',shelter:'🛟',water:'💧',home:'🏠'}[t]);
    const log=(a,b)=>{const l=$('.ba-log',root);l.replaceChildren(Object.assign(document.createElement('strong'),{textContent:a}),Object.assign(document.createElement('small'),{textContent:b}))};
    function reset(){cells=Array.from({length:N*N},(_,i)=>({type:'home',damaged:Math.random()<.28,known:false,battery:false,powered:false}));cells[12]={type:'plant',damaged:false,known:true,battery:false,powered:true};const spots=[0,4,20,24,2,22].sort(()=>Math.random()-.5);['clinic','shelter','water'].forEach((t,i)=>cells[spots[i]].type=t);cells.forEach((c,i)=>{if(i!==12&&c.type!=='home')c.damaged=Math.random()<.5});st={turn:1,crews:3,parts:5,batteries:2,trust:70,recovery:true,score:0};selected=12;ended=false;propagate();log('The storm has passed.','Inspect uncertain lines, repair a connected route, and keep critical facilities online.');draw()}
    function propagate(){cells.forEach(c=>c.powered=false);const q=[12];cells[12].powered=true;while(q.length){const i=q.shift();neighbors(i).forEach(n=>{const c=cells[n];if(!c.powered&&!c.damaged){c.powered=true;q.push(n)}})}cells.forEach(c=>{if(c.battery)c.powered=true})}
    function poweredCount(){return cells.filter(c=>c.powered).length}
    function inspect(){if(ended||st.crews<1)return log('Inspection unavailable.','A crew is required.');const c=cells[selected];st.crews--;c.known=true;log(c.damaged?'Fault confirmed.':'Line is intact.',`${label(c.type)} at row ${rc(selected)[0]+1}, column ${rc(selected)[1]+1}.`);draw()}
    function repair(){if(ended||st.crews<1||st.parts<1)return log('Repair unavailable.','You need one crew and one spare part.');const c=cells[selected];if(selected===12)return log('Plant is stable.','Choose a damaged or uncertain district cell.');st.crews--;st.parts--;c.known=true;if(c.damaged){c.damaged=false;st.trust=clamp(st.trust+3,0,100);log('Line repaired.',`${label(c.type)} can reconnect if a powered route reaches it.`)}else{st.trust=clamp(st.trust-4,0,100);log('Part used on an intact line.','Inspection first avoids costly guesses.')}propagate();draw()}
    function battery(){if(ended||st.batteries<1)return log('No battery available.','Mutual aid can provide one emergency battery.');const c=cells[selected];if(c.type==='plant'||c.battery)return log('Battery not deployed.','Choose an unpowered district cell.');st.batteries--;c.battery=true;c.powered=true;c.known=true;log('Battery island online.',`${label(c.type)} has temporary local power.`);draw()}
    function criticalPowered(){return cells.filter(c=>['clinic','shelter','water'].includes(c.type)&&c.powered).length}
    function advance(){if(ended)return;const critical=criticalPowered();st.trust=clamp(st.trust+critical*3-(3-critical)*7,0,100);st.turn++;if(st.turn>7){finish();return}st.crews=3;const candidates=cells.map((c,i)=>({c,i})).filter(x=>x.i!==12&&!x.c.battery&&!x.c.damaged);if(candidates.length&&Math.random()<.72){const hit=candidates[Math.floor(Math.random()*candidates.length)];hit.c.damaged=true;hit.c.known=false;log('A wet fault cascaded.',`Turn ${st.turn}: one previously intact line failed. Crews are refreshed.`)}else log(`Turn ${st.turn} begins.`,'Crews are refreshed. The network held through the night.');propagate();if(st.trust<=0){ended=true;log('Public confidence collapsed.','Restart and protect critical loads earlier.')}draw()}
    function recover(){if(ended||!st.recovery)return log('Mutual aid unavailable.','It can be called once per storm.');st.recovery=false;st.crews+=2;st.parts+=2;st.batteries+=1;st.trust=clamp(st.trust-18,0,100);log('Mutual aid arrived.','Two crews, two parts, and one battery were added, but trust fell by 18.');draw()}
    function finish(){ended=true;propagate();const p=poweredCount(),crit=criticalPowered();st.score=p*35+crit*180+st.trust*4+st.parts*20+st.batteries*35+(st.recovery?90:0);const win=crit===3&&p>=18&&st.trust>=35;root.classList.add('ba-pulse');log(win?'District restoration secured.':'A partial restoration survived.',`${p}/25 cells powered, ${crit}/3 critical facilities online, trust ${st.trust}, score ${st.score}. ${win?'The network can withstand the next weather front.':'Replay and build a connected backbone before spending scarce parts.'}`);draw()}
    function draw(){const vals=[`${Math.min(st.turn,7)}/7`,st.crews,st.parts,st.batteries,st.trust,`${poweredCount()}/25`];$$('[data-h]',root).forEach((e,i)=>e.textContent=vals[i]);$('[data-meter]',root).style.width=`${poweredCount()/25*100}%`;const g=$('[data-grid]',root);g.innerHTML=cells.map((c,i)=>{const state=c.powered?'powered':c.known&&c.damaged?'damaged':c.known?'clear':'unknown';return `<button class="ba-cell" role="gridcell" data-i="${i}" data-state="${state}" aria-pressed="${i===selected}" aria-label="${label(c.type)}, row ${rc(i)[0]+1}, column ${rc(i)[1]+1}, ${c.powered?'powered':c.known?(c.damaged?'damaged':'intact'):'condition unknown'}">${icon(c.type)}${c.battery?'<span class="ba-badge">🔋</span>':''}<small>${c.powered?'ON':c.known&&c.damaged?'FAULT':c.known?'CLEAR':'?'}</small></button>`}).join('');$$('.ba-cell',g).forEach(b=>b.addEventListener('click',()=>{selected=+b.dataset.i;draw()}));const c=cells[selected];$('[data-target]',root).textContent=`${label(c.type)} · row ${rc(selected)[0]+1}, column ${rc(selected)[1]+1}`;$('[data-detail]',root).textContent=c.known?(c.damaged?'Confirmed line fault.':'Line inspected and intact.'):'Condition unknown. Inspection reduces repair risk.';$$('[data-a]',root).forEach(b=>{if(b.dataset.a!=='restart')b.disabled=ended});$('[data-a="recover"]',root).disabled=ended||!st.recovery}
    root.addEventListener('click',e=>{const a=e.target.closest('[data-a]')?.dataset.a;if(a==='inspect')inspect();if(a==='repair')repair();if(a==='battery')battery();if(a==='advance')advance();if(a==='recover')recover();if(a==='restart')reset()});root.addEventListener('keydown',e=>{if(!e.target.matches('.ba-cell'))return;const [r,c]=rc(selected),map={ArrowUp:[r-1,c],ArrowDown:[r+1,c],ArrowLeft:[r,c-1],ArrowRight:[r,c+1]};if(!map[e.key])return;e.preventDefault();const [nr,nc]=map[e.key];if(nr<0||nr>=N||nc<0||nc>=N)return;selected=idx(nr,nc);draw();$(`.ba-cell[data-i="${selected}"]`,root)?.focus()});dialog.addEventListener('close',()=>root.replaceChildren(),{once:true});reset()
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();