(()=> {
  const APP={name:'Canopy Guard',emoji:'🛡️',category:'play',version:'1.0.0',summary:'Defend a forest canopy by placing roots, blossoms, and owls before pest waves reach the grove.',description:'A local lane-defense strategy game with three plant tools, pest waves, water and sunlight tradeoffs, pollinator bonuses, storm pressure, recoverable damage, scoring, keyboard and touch controls, optional audio, reduced-motion behavior, and teardown.'};
  const label=v=>v==='play'?'Play':v==='useful'?'Useful':'Experiment';
  const $=s=>document.querySelector(s);
  function style(){if($('#canopy-guard-styles'))return;const s=document.createElement('style');s.id='canopy-guard-styles';s.textContent=`
.canopy-card{animation:canopy-pop .25s ease both}.canopy-game{max-width:1040px;gap:14px}.canopy-hud{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.canopy-stat{border:1px solid var(--line);border-radius:15px;background:white;padding:10px 12px}.canopy-stat span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.canopy-stat strong{display:block;margin-top:4px}.canopy-board{position:relative;border:0;border-radius:26px;background:#07140e;color:white;padding:0;overflow:hidden;touch-action:none;box-shadow:inset 0 0 0 1px rgba(255,255,255,.14)}.canopy-board:focus-visible{outline:4px solid var(--accent);outline-offset:4px}.canopy-board canvas{display:block;width:100%;height:min(58vh,500px);min-height:360px}.canopy-console{display:grid;grid-template-columns:1.2fr .8fr;gap:10px}.canopy-panel{border:1px solid var(--line);border-radius:18px;background:#fff;padding:13px}.canopy-tools,.canopy-legend{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.canopy-chip,.canopy-legend span{border:1px solid var(--line);border-radius:999px;background:#fff;color:var(--ink);padding:8px 11px;font-weight:900}.canopy-chip.is-active{background:#111827;color:#fff}.canopy-log{min-height:92px;padding:17px 19px}@media(max-width:760px){.canopy-hud{grid-template-columns:repeat(2,1fr)}.canopy-console{grid-template-columns:1fr}.canopy-board canvas{height:56vh;min-height:340px}}@media(prefers-reduced-motion:reduce){.canopy-card{animation:none}.canopy-board canvas{min-height:330px}}@keyframes canopy-pop{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}`;document.head.append(s);}
  function addCard(){const grid=$('#app-grid'),tpl=$('#app-card-template');if(!grid||!tpl||$('[data-canopy-card]'))return;const f=$('.filter.is-active')?.dataset.filter||'all';if(f!=='all'&&f!==APP.category)return;style();const node=tpl.content.cloneNode(true),card=node.querySelector('.app-card');card.dataset.category=APP.category;card.dataset.canopyCard='true';card.classList.add('canopy-card');node.querySelector('.app-icon').textContent=APP.emoji;node.querySelector('.app-meta').textContent=`${label(APP.category)} · v${APP.version}`;node.querySelector('.app-name').textContent=APP.name;node.querySelector('.app-summary').textContent=APP.summary;const btn=node.querySelector('.app-card-button');btn.setAttribute('aria-label',`Open ${APP.name}`);btn.addEventListener('click',open);grid.append(node);}
  function boot(){style();addCard();document.querySelectorAll('.filter').forEach(b=>{if(b.dataset.canopyRefresh)return;b.dataset.canopyRefresh='1';b.addEventListener('click',()=>setTimeout(addCard,0));});}
  function open(){const dialog=$('#app-dialog'),stage=$('#app-stage'),title=$('#dialog-title'),cat=$('#dialog-category'),desc=$('#dialog-description'),fb=$('#dialog-feedback');if(!dialog||!stage)return;title.textContent=APP.name;cat.textContent=`${label(APP.category)} · ${APP.emoji}`;desc.textContent=APP.description;fb.href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Canopy%20Guard';stage.replaceChildren();game(stage,dialog);dialog.showModal();}
  function game(stage,dialog){
    const root=document.createElement('section');root.className='tool-panel canopy-game';
    const hud=document.createElement('div');hud.className='canopy-hud';hud.innerHTML='<div class="canopy-stat"><span>Wave</span><strong id="cg-wave">1 / 6</strong></div><div class="canopy-stat"><span>Health</span><strong id="cg-health">12</strong></div><div class="canopy-stat"><span>Water</span><strong id="cg-water">8</strong></div><div class="canopy-stat"><span>Sun</span><strong id="cg-sun">6</strong></div><div class="canopy-stat"><span>Score</span><strong id="cg-score">0</strong></div>';
    const board=document.createElement('button');board.type='button';board.className='canopy-board';board.setAttribute('aria-label','Canopy Guard grid. Use arrows to move, one two or three to choose a tool, Enter to plant, Space to start a wave, Backspace to clear, and N for a new grove.');board.innerHTML='<canvas aria-hidden="true"></canvas>';
    const con=document.createElement('div');con.className='canopy-console';con.innerHTML='<div class="canopy-panel"><strong>Tools</strong><p>Roots slow pests, blossoms shoot pollen, and owls strike the strongest pest. Planting costs water or sun. Bees reward connected blossoms.</p><div class="canopy-tools"></div></div><div class="canopy-panel"><strong>Rules</strong><div class="canopy-legend"><span>Root: 2 water</span><span>Blossom: 2 sun</span><span>Owl: 2 water + 1 sun</span><span>Storm mode after 900</span></div></div>';
    const log=document.createElement('div');log.className='result-card canopy-log';log.setAttribute('aria-live','polite');const foot=document.createElement('div');foot.className='tool-actions';root.append(hud,board,con,log,foot);stage.append(root);
    const canvas=board.querySelector('canvas'),ctx=canvas.getContext('2d'),tools=con.querySelector('.canopy-tools'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
    const state={rows:4,cols:8,cursor:9,tool:'root',wave:1,waves:6,health:12,water:8,sun:6,score:0,storm:false,running:false,tick:0,plants:[],pests:[],raf:0,audio:false,ac:null,last:0};
    [['root','Root'],['blossom','Blossom'],['owl','Owl'],['clear','Clear']].forEach(([id,txt])=>{const b=btn(txt,()=>{state.tool=id;paintTools();draw();},true);b.classList.add('canopy-chip');b.dataset.tool=id;tools.append(b);});
    foot.append(btn('Start wave',start,true),btn('New grove',reset,true),btn('Storm mode',storm,true),btn('Sound off',sound,true));
    board.addEventListener('click',tap);board.addEventListener('pointermove',point);board.addEventListener('keydown',key);dialog.addEventListener('close',tear,{once:true});
    function btn(t,f,sec){const b=document.createElement('button');b.type='button';b.className=sec?'button button-secondary':'button';b.textContent=t;b.addEventListener('click',f);return b}
    function say(h){log.innerHTML=h}
    function cell(i){return [i%state.cols,Math.floor(i/state.cols)]} function idx(x,y){return y*state.cols+x}
    function paintTools(){tools.querySelectorAll('.canopy-chip').forEach(b=>b.classList.toggle('is-active',b.dataset.tool===state.tool));hud.querySelector('#cg-wave').textContent=`${state.wave} / ${state.waves}`;hud.querySelector('#cg-health').textContent=state.health;hud.querySelector('#cg-water').textContent=state.water;hud.querySelector('#cg-sun').textContent=state.sun;hud.querySelector('#cg-score').textContent=state.score}
    function cost(t){return t==='root'?[2,0]:t==='blossom'?[0,2]:t==='owl'?[2,1]:[0,0]}
    function plant(){const [w,s]=cost(state.tool),at=state.plants.find(p=>p.i===state.cursor);if(state.tool==='clear'){state.plants=state.plants.filter(p=>p.i!==state.cursor);state.water++;say('<strong>Cleared a cell.</strong><small>Recovered one water for rebuilding.</small>');draw();paintTools();return}if(at){say('<strong>That canopy cell is occupied.</strong><small>Clear it or choose another lane.</small>');return}if(state.water<w||state.sun<s){say('<strong>Not enough resources.</strong><small>Survive a wave or connect blossoms for more water and sun.</small>');return}state.water-=w;state.sun-=s;state.plants.push({i:state.cursor,type:state.tool,cool:0});bonus();paintTools();draw()}
    function bonus(){let bs=state.plants.filter(p=>p.type==='blossom').map(p=>p.i);if(bs.length>1&&bs.some(a=>bs.some(b=>a!==b&&Math.abs(a-b)===1))){state.sun++;state.score+=8;say('<strong>Bee chain bonus.</strong><small>Adjacent blossoms return one sun and build score.</small>')}}
    function start(){if(state.running)return;state.running=true;const n=5+state.wave+(state.storm?3:0);for(let k=0;k<n;k++)state.pests.push({x:-k*.7,y:k%state.rows,hp:2+Math.floor(state.wave/2)+(state.storm?1:0),slow:0});say(`<strong>Wave ${state.wave} is moving.</strong><small>Place during the wave, but resources are tight.</small>`);loop(0)}
    function step(){state.tick++;for(const p of state.pests){p.x+=(p.slow>0?.015:.03)+state.wave*.002;if(p.slow>0)p.slow--}for(const pl of state.plants){pl.cool--;const [x,y]=cell(pl.i);let near=state.pests.filter(p=>Math.floor(p.y)===y&&p.x>x-.3&&p.x<x+3);if(pl.type==='root')near.forEach(p=>p.slow=40);if(pl.type==='blossom'&&pl.cool<=0&&near[0]){near[0].hp--;pl.cool=22;state.score+=3;beep(520)}if(pl.type==='owl'&&pl.cool<=0){let t=state.pests.slice().sort((a,b)=>b.hp-a.hp)[0];if(t){t.hp-=2;pl.cool=46;state.score+=6;beep(260)}}}
      const before=state.pests.length;state.pests=state.pests.filter(p=>{if(p.hp<=0){state.score+=18;return false}if(p.x>state.cols){state.health--;beep(120);return false}return true});if(before&&!state.pests.length){state.running=false;state.water+=3;state.sun+=2;if(state.health<=0){say('<strong>The grove fell, but recovery is open.</strong><small>New grove resets without leaving the app.</small>')}else if(state.wave>=state.waves){state.score+=state.health*25;say(`<strong>Canopy held: ${state.score}.</strong><small>${state.score>=900?'Storm mode is unlocked for this session.':'Score 900 to unlock storm mode.'}</small>`)}else{state.wave++;say('<strong>Wave cleared.</strong><small>Resources restored. Add defenses before the next wave.</small>')}}paintTools()}
    function loop(t){if(!state.running)return;state.raf=requestAnimationFrame(loop);if(reduced&&t-state.last<90)return;state.last=t;step();draw()}
    function storm(){if(state.score<900&&!state.storm){say('<strong>Storm mode locked.</strong><small>Score 900 in a grove to add tougher pests.</small>');return}state.storm=!state.storm;reset();say(`<strong>${state.storm?'Storm':'Normal'} grove ready.</strong><small>Storm adds pests and health, but gives higher score potential.</small>`)}
    function reset(){Object.assign(state,{cursor:9,wave:1,health:state.storm?14:12,water:8,sun:6,score:0,running:false,tick:0,plants:[],pests:[]});cancelAnimationFrame(state.raf);say('<strong>New grove ready.</strong><small>Build a mixed defense, then start the wave.</small>');paintTools();draw()}
    function locate(e){const r=board.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)/r.width*state.cols),y=Math.floor((e.clientY-r.top)/r.height*state.rows);if(x>=0&&x<state.cols&&y>=0&&y<state.rows){state.cursor=idx(x,y);return true}return false}
    function point(e){if(locate(e))draw()} function tap(e){locate(e);plant()}
    function key(e){const k=e.key.toLowerCase(),[x,y]=cell(state.cursor);if(k==='arrowright'){e.preventDefault();state.cursor=idx(Math.min(7,x+1),y)}if(k==='arrowleft'){e.preventDefault();state.cursor=idx(Math.max(0,x-1),y)}if(k==='arrowdown'){e.preventDefault();state.cursor=idx(x,Math.min(3,y+1))}if(k==='arrowup'){e.preventDefault();state.cursor=idx(x,Math.max(0,y-1))}if(k==='1')state.tool='root';if(k==='2')state.tool='blossom';if(k==='3')state.tool='owl';if(k==='backspace'||k==='delete'){e.preventDefault();state.tool='clear';plant()}if(k==='enter'){e.preventDefault();plant()}if(k===' '){e.preventDefault();start()}if(k==='n'){e.preventDefault();reset()}paintTools();draw()}
    function sound(e){const b=e.currentTarget,AC=window.AudioContext||window.webkitAudioContext;if(!AC){say('<strong>Sound is not available here.</strong><small>The grove still plays silently.</small>');return}state.audio=!state.audio;b.textContent=state.audio?'Sound on':'Sound off';b.setAttribute('aria-pressed',String(state.audio));if(state.audio){state.ac ||= new AC();state.ac.resume();beep(440)}}
    function beep(f){if(!state.audio||!state.ac)return;const n=state.ac.currentTime,o=state.ac.createOscillator(),g=state.ac.createGain();o.frequency.value=f;g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(.04,n+.02);g.gain.exponentialRampToValueAtTime(.0001,n+.14);o.connect(g).connect(state.ac.destination);o.start(n);o.stop(n+.16)}
    function size(){const dpr=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=Math.max(1,r.width*dpr);canvas.height=Math.max(1,r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);return r}
    function draw(){const r=size(),cw=r.width/state.cols,ch=r.height/state.rows;ctx.clearRect(0,0,r.width,r.height);ctx.fillStyle='#07140e';ctx.fillRect(0,0,r.width,r.height);for(let y=0;y<state.rows;y++)for(let x=0;x<state.cols;x++){ctx.strokeStyle='rgba(255,255,255,.14)';ctx.strokeRect(x*cw,y*ch,cw,ch)}const [cx,cy]=cell(state.cursor);ctx.strokeStyle='#f8e08e';ctx.lineWidth=4;ctx.strokeRect(cx*cw+4,cy*ch+4,cw-8,ch-8);for(const p of state.plants){const [x,y]=cell(p.i);ctx.fillStyle=p.type==='root'?'#86efac':p.type==='blossom'?'#f0abfc':'#fdba74';ctx.beginPath();ctx.arc((x+.5)*cw,(y+.5)*ch,Math.min(cw,ch)*.28,0,7);ctx.fill();ctx.fillStyle='#07140e';ctx.font='bold 18px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(p.type==='root'?'R':p.type==='blossom'?'B':'O',(x+.5)*cw,(y+.5)*ch)}for(const p of state.pests){ctx.fillStyle=p.slow>0?'#bfdbfe':'#fecaca';if(ctx.roundRect){ctx.beginPath();ctx.roundRect(p.x*cw+8,(p.y+.23)*ch,cw*.55,ch*.54,12);ctx.fill()}else ctx.fillRect(p.x*cw+8,(p.y+.23)*ch,cw*.55,ch*.54);ctx.fillStyle='#111827';ctx.font='bold 14px sans-serif';ctx.textAlign='center';ctx.fillText(p.hp,p.x*cw+8+cw*.28,(p.y+.5)*ch)}ctx.fillStyle='rgba(134,239,172,.18)';ctx.fillRect((state.cols-.25)*cw,0,cw*.25,r.height)}
    function tear(){cancelAnimationFrame(state.raf);if(state.ac)state.ac.close().catch(()=>{});}
    reset();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else setTimeout(boot,0);
})();