(() => {
  'use strict';
  const APP={name:'Caption Control',emoji:'CC',category:'experiment',version:'1.0.0',summary:'Run an accessible live-caption desk through fast, messy public events.',description:'A local-only real-time accessibility operations game with incoming caption errors, speaker labels, terminology, latency, audience comprehension, session progression, unlocks, failure, recovery, keyboard controls, reduced motion, and complete timer teardown.'};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const EVENTS=[
    {name:'School board briefing',speakers:['Chair','Parent','Planner'],terms:['IEP','bus loop','quorum'],pace:2300},
    {name:'Science town hall',speakers:['Host','Researcher','Resident'],terms:['particulate','baseline','exposure'],pace:2100},
    {name:'Emergency update',speakers:['Director','Meteorologist','Interpreter'],terms:['evacuation','shelter-in-place','inundation'],pace:1850},
    {name:'Arts festival stream',speakers:['MC','Artist','Sponsor'],terms:['installation','matinee','access aisle'],pace:1700},
    {name:'Transit hearing',speakers:['Moderator','Rider','Engineer'],terms:['headway','paratransit','platform gap'],pace:1550}
  ];
  const LINES=[
    ['We need a clear {term} before the vote.','We need a clear {bad} before the vote.'],
    ['The {speaker} said the route changes Monday.','The speaker said the root changes Monday.'],
    ['Please use the north entrance after six.','Please use the north interest after six.'],
    ['The next update is at seven fifteen.','The next update is at seventeen fifty.'],
    ['This section describes the {term} plan.','This section describes the {bad} plant.'],
    ['Questions will be taken in arrival order.','Questions will be taken in rival order.']
  ];
  function style(){if($('#caption-control-style'))return;const e=document.createElement('style');e.id='caption-control-style';e.textContent=`.caption-control{max-width:1100px;display:grid;gap:12px}.cc-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.cc-stat,.cc-card{border:1px solid var(--line);border-radius:16px;background:#fff}.cc-stat{padding:8px}.cc-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.cc-layout{display:grid;grid-template-columns:1.15fr .85fr;gap:12px}.cc-card{padding:14px}.cc-stream{display:grid;gap:8px;min-height:310px}.cc-line{border:1px solid #cbd5e1;border-radius:12px;padding:10px;background:#f8fafc;text-align:left;min-height:58px}.cc-line[data-error=true]{border-color:#f59e0b;background:#fffbeb}.cc-line[data-selected=true]{outline:3px solid #2563eb;outline-offset:2px}.cc-line strong,.cc-line small{display:block}.cc-line small{color:var(--muted);margin-top:3px}.cc-tools,.cc-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.caption-control button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;color:inherit;font-weight:800;padding:9px}.caption-control button.primary,.caption-control button[aria-pressed=true]{background:#dbeafe;border-color:#2563eb}.cc-meter{height:10px;background:#e2e8f0;border-radius:999px;overflow:hidden;margin:4px 0 10px}.cc-meter span{display:block;height:100%;background:linear-gradient(90deg,#dc2626,#f59e0b,#16a34a)}.cc-queue{display:grid;gap:6px}.cc-badge{display:inline-block;border-radius:999px;padding:3px 7px;background:#e0e7ff;font-size:.7rem;font-weight:900}.cc-log{min-height:92px}.cc-flash{animation:ccFlash .3s ease}@keyframes ccFlash{50%{transform:translateY(-2px);box-shadow:0 8px 24px #2563eb22}}@media(max-width:840px){.cc-layout{grid-template-columns:1fr}.cc-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.cc-hud{grid-template-columns:repeat(2,1fr)}.cc-tools,.cc-actions{grid-template-columns:1fr}.cc-stream{min-height:260px}.cc-line{font-size:.92rem}}@media(prefers-reduced-motion:reduce){.caption-control *{animation:none!important;transition:none!important}}`;document.head.append(e)}
  function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-caption-control]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.captionControl='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Experiment · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
  function boot(){style();let n=0;const r=()=>{card();if(!$('[data-caption-control]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.ccBound)return;b.dataset.ccBound='1';b.addEventListener('click',()=>setTimeout(card))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Experiment · live accessibility operations';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel caption-control';root.innerHTML=`<div class="cc-hud">${['Event','Time','Comprehension','Trust','Glossary','Score'].map((x,i)=>`<div class="cc-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="cc-layout"><section class="cc-card"><p class="eyebrow">Live transcript</p><h3 data-event></h3><p data-brief></p><div class="cc-stream" role="listbox" aria-label="Incoming caption lines" data-stream></div><p><small>Use Up and Down to select a line. Press C to correct, S to label the speaker, or G to add a term to the glossary.</small></p></section><aside class="cc-card"><p class="eyebrow">Caption desk</p><div><strong>Audience comprehension</strong><div class="cc-meter"><span data-meter></span></div></div><div class="cc-tools"><button data-tool="correct">Correct text<br><small>2 focus</small></button><button data-tool="speaker">Label speaker<br><small>1 focus</small></button><button data-tool="glossary">Add term<br><small>3 focus</small></button><button data-tool="publish">Publish selected<br><small>reduces latency</small></button></div><p><strong>Focus:</strong> <span data-focus></span> · <strong>Latency:</strong> <span data-latency></span></p><div class="cc-queue" data-queue></div><div class="cc-actions"><button class="primary" data-a="advance">Advance event</button><button data-a="recover">Call relief captioner<br><small>once · -12 trust</small></button><button data-a="restart">New session</button></div><h3>Control room notes</h3><div class="result-card cc-log" aria-live="polite"></div></aside></div>`;stage.append(root);
    let st,timer=null,closed=false,nextId=1;
    const log=(a,b)=>{const l=$('.cc-log',root);l.replaceChildren(Object.assign(document.createElement('strong'),{textContent:a}),Object.assign(document.createElement('small'),{textContent:b}))};
    function lineFor(){const ev=EVENTS[st.event],pair=LINES[Math.floor(Math.random()*LINES.length)],term=ev.terms[Math.floor(Math.random()*ev.terms.length)],speaker=ev.speakers[Math.floor(Math.random()*ev.speakers.length)],bad=term.slice(0,Math.max(3,term.length-2))+'ish';return{id:nextId++,speaker,term,good:pair[0].replace('{term}',term).replace('{speaker}',speaker),text:pair[1].replace('{bad}',bad),error:true,labeled:false,glossed:false,published:false,age:0}}
    function schedule(){clearInterval(timer);if(st.ended||closed)return;timer=setInterval(()=>{if(st.lines.length<6)st.lines.push(lineFor());st.lines.forEach(x=>{if(!x.published)x.age++});st.latency=st.lines.filter(x=>!x.published).reduce((a,x)=>a+x.age,0);if(st.latency>18){st.comprehension=clamp(st.comprehension-4,0,100);st.trust=clamp(st.trust-2,0,100)}if(st.lines.some(x=>x.age>7&&!x.published)){st.comprehension=clamp(st.comprehension-3,0,100)}if(st.trust<=0||st.comprehension<=20){st.ended=true;clearInterval(timer);log('The stream lost its audience.','Restart and balance accuracy against latency. Publishing imperfect but understandable captions can be better than waiting too long.')}draw()},EVENTS[st.event].pace)}
    function reset(){clearInterval(timer);st={event:0,time:70,comprehension:78,trust:72,glossary:0,score:0,focus:8,latency:0,lines:[],selected:0,recovery:true,unlocked:false,ended:false};st.lines=[lineFor(),lineFor(),lineFor()];log('The stream is live.','Correct meaning-changing errors, label speakers, and publish before latency overwhelms the audience.');draw();schedule()}
    function selected(){return st.lines[st.selected]}
    function spend(n){if(st.focus<n){log('Not enough focus.','Publish clean lines or advance the event to recover focus.');return false}st.focus-=n;return true}
    function correct(){const x=selected();if(!x||x.published)return;if(!spend(2))return;if(x.error){x.text=x.good;x.error=false;st.comprehension=clamp(st.comprehension+5,0,100);st.score+=80;log('Meaning restored.','The correction improved comprehension, but the line still needs a speaker label or publication.')}else{st.trust=clamp(st.trust-3,0,100);log('Unnecessary edit.','Focus was spent on a line that was already accurate.')}draw()}
    function speaker(){const x=selected();if(!x||x.published)return;if(!spend(1))return;x.labeled=true;st.score+=35;st.comprehension=clamp(st.comprehension+2,0,100);log('Speaker identified.',`${x.speaker} is now clear to readers following a multi-person exchange.`);draw()}
    function glossary(){const x=selected();if(!x||x.published)return;if(!spend(3))return;if(x.glossed)return;x.glossed=true;st.glossary++;st.score+=60;st.unlocked=st.glossary>=4;log('Term added to the glossary.',st.unlocked?'Predictive terminology is unlocked: future term errors arrive pre-flagged.':'Build four entries to unlock predictive terminology.');draw()}
    function publish(){const x=selected();if(!x||x.published)return;x.published=true;const quality=(x.error?-9:8)+(x.labeled?4:0)+(x.glossed?3:0);st.comprehension=clamp(st.comprehension+quality,0,100);st.trust=clamp(st.trust+(quality>=8?2:-4),0,100);st.focus=clamp(st.focus+2,0,12);st.score+=Math.max(0,100-x.age*8+quality*5);log(x.error?'An inaccurate line went public.':'Caption published.',x.error?'Latency fell, but the meaning error damaged trust.':'Fast, accurate publication restored focus and audience confidence.');st.lines=st.lines.filter(y=>!y.published);st.selected=clamp(st.selected,0,Math.max(0,st.lines.length-1));draw()}
    function advance(){if(st.ended)return;const open=st.lines.filter(x=>!x.published);if(open.length>2){st.trust=clamp(st.trust-7,0,100);log('The handoff is overloaded.','Publish more of the queue before advancing, or accept a trust penalty.');draw();return}st.score+=st.comprehension*5+st.trust*3+st.focus*10;st.event++;if(st.event>=EVENTS.length){st.ended=true;clearInterval(timer);log(st.comprehension>=65?'Accessible broadcast completed.':'The broadcast ended with fragile access.',`Final score ${st.score}. Comprehension ${st.comprehension}, trust ${st.trust}, glossary ${st.glossary}.`);draw();return}st.time=70-st.event*6;st.focus=clamp(st.focus+5,0,12);st.lines=[lineFor(),lineFor(),lineFor()];st.selected=0;st.latency=0;log('A faster event is starting.',`${EVENTS[st.event].name} has denser terminology and less time for perfect cleanup.`);draw();schedule()}
    function recover(){if(st.ended||!st.recovery)return;st.recovery=false;st.trust=clamp(st.trust-12,0,100);st.focus=12;st.lines.forEach(x=>x.age=0);st.latency=0;log('A relief captioner cleared the latency spike.','Focus is restored, but trust fell because the handoff arrived late.');draw()}
    function draw(){const ev=EVENTS[Math.min(st.event,EVENTS.length-1)],vals=[`${Math.min(st.event+1,EVENTS.length)}/${EVENTS.length}`,`${st.time}s`,st.comprehension,st.trust,st.glossary,st.score];$$('[data-h]',root).forEach((e,i)=>e.textContent=vals[i]);$('[data-event]',root).textContent=ev.name;$('[data-brief]',root).textContent=`Speakers: ${ev.speakers.join(', ')}. Priority terms: ${ev.terms.join(', ')}.`;$('[data-meter]',root).style.width=`${st.comprehension}%`;$('[data-focus]',root).textContent=`${st.focus}/12`;$('[data-latency]',root).textContent=st.latency;$('[data-queue]',root).innerHTML=`<span class="cc-badge">${st.unlocked?'Predictive terminology active':'Glossary unlock at 4 terms'}</span><small>${st.lines.length} unpublished line${st.lines.length===1?'':'s'}</small>`;$('[data-stream]',root).innerHTML=st.lines.map((x,i)=>`<button class="cc-line" role="option" aria-selected="${i===st.selected}" data-i="${i}" data-error="${x.error}" data-selected="${i===st.selected}" ${st.ended?'disabled':''}><strong>${x.labeled?x.speaker:'Speaker ?'}</strong><span>${x.text}</span><small>${x.error?'Possible meaning error · ':''}${x.glossed?'Glossary linked · ':''}latency ${x.age}</small></button>`).join('')||'<div class="result-card">Queue clear. Advance when ready.</div>';$$('.cc-line',root).forEach(b=>b.addEventListener('click',()=>{st.selected=+b.dataset.i;draw()}));$('[data-a="recover"]',root).disabled=st.ended||!st.recovery;$$('[data-tool], [data-a="advance"]',root).forEach(b=>b.disabled=st.ended)}
    root.addEventListener('click',e=>{const tool=e.target.closest('[data-tool]')?.dataset.tool;if(tool==='correct')correct();if(tool==='speaker')speaker();if(tool==='glossary')glossary();if(tool==='publish')publish();const a=e.target.closest('[data-a]')?.dataset.a;if(a==='advance')advance();if(a==='recover')recover();if(a==='restart')reset()});
    root.addEventListener('keydown',e=>{if(!st.lines.length)return;if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();st.selected=(st.selected+(e.key==='ArrowDown'?1:-1)+st.lines.length)%st.lines.length;draw();$(`.cc-line[data-i="${st.selected}"]`,root)?.focus()}if(e.key.toLowerCase()==='c')correct();if(e.key.toLowerCase()==='s')speaker();if(e.key.toLowerCase()==='g')glossary();if(e.key==='Enter'&&e.target.matches('.cc-line')){e.preventDefault();publish()}});
    const tick=setInterval(()=>{if(st.ended||closed)return;st.time--;if(st.time<=0)advance();else draw()},1000);
    const stop=()=>{closed=true;clearInterval(timer);clearInterval(tick)};
    dialog.addEventListener('close',stop,{once:true});reset()
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot()
})();