(() => {
  'use strict';
  const APP={name:'Choreo Grid',emoji:'💃',category:'play',version:'1.0.0',summary:'Stage a six-count dance by balancing spacing, energy, symmetry, audience focus, and collision risk.',description:'A local-only choreography strategy game with four dancers, spatial movement, changing briefs, energy and focus tradeoffs, scoring, progression, a session unlock, meaningful failure, one costly rehearsal recovery, touch and keyboard controls, reduced motion, and teardown.'};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const BRIEFS=[
    {name:'Opening picture',goal:'Create a broad, balanced opening shape.',spread:7,sym:6,motion:2},
    {name:'Crossing phrase',goal:'Build motion without collisions.',spread:5,sym:2,motion:7},
    {name:'Mirror duet',goal:'Favor symmetry and clean spacing.',spread:4,sym:8,motion:4},
    {name:'Center spotlight',goal:'Bring one dancer to center while preserving depth.',spread:5,sym:4,motion:5},
    {name:'Canon build',goal:'Layer staggered movement across the stage.',spread:6,sym:3,motion:8},
    {name:'Final tableau',goal:'Finish with strong coverage and visual balance.',spread:8,sym:7,motion:5}
  ];
  function style(){if($('#choreo-grid-style'))return;const e=document.createElement('style');e.id='choreo-grid-style';e.textContent=`.choreo-grid{max-width:1080px;display:grid;gap:12px}.cg-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.cg-stat,.cg-card{border:1px solid var(--line);border-radius:17px;background:#fff}.cg-stat{padding:9px}.cg-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.cg-layout{display:grid;grid-template-columns:1.1fr .9fr;gap:12px}.cg-card{padding:15px}.cg-stage{position:relative;display:grid;grid-template-columns:repeat(5,1fr);aspect-ratio:1;border-radius:24px;overflow:hidden;background:linear-gradient(135deg,#fdf2f8,#eef2ff);border:8px solid #312e81}.cg-cell{border:1px solid rgba(49,46,129,.14);position:relative}.cg-cell[data-center=true]{background:rgba(250,204,21,.18)}.cg-dancer{position:absolute;width:13%;aspect-ratio:1;border-radius:50%;display:grid;place-items:center;color:#fff;font-weight:900;box-shadow:0 8px 18px rgba(49,46,129,.24);transition:left .35s ease,top .35s ease,transform .2s ease;transform:translate(-50%,-50%)}.cg-dancer[aria-selected=true]{outline:4px solid #f59e0b;outline-offset:3px;transform:translate(-50%,-50%) scale(1.08)}.cg-1{background:#db2777}.cg-2{background:#7c3aed}.cg-3{background:#0284c7}.cg-4{background:#059669}.cg-brief{min-height:112px}.cg-dancers,.cg-moves,.cg-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.cg-dancers button,.cg-moves button,.cg-actions button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800;padding:9px}.cg-dancers button[aria-pressed=true],.cg-actions .primary{background:#ede9fe;border-color:#7c3aed}.cg-moves{grid-template-columns:repeat(3,1fr);margin:10px 0}.cg-bars{display:grid;gap:8px;margin-top:10px}.cg-bar{display:grid;grid-template-columns:72px 1fr 38px;align-items:center;gap:8px;font-size:.72rem}.cg-bar i{display:block;height:9px;border-radius:99px;background:#e5e7eb;overflow:hidden}.cg-bar b{display:block;height:100%;background:#7c3aed}.cg-note{font-size:.75rem;color:var(--muted)}@media(max-width:820px){.cg-layout{grid-template-columns:1fr}.cg-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:520px){.cg-hud{grid-template-columns:repeat(2,1fr)}.cg-stage{aspect-ratio:1}.cg-moves{grid-template-columns:repeat(3,1fr)}}@media(prefers-reduced-motion:reduce){.choreo-grid *{animation:none!important;transition:none!important}}`;document.head.append(e)}
  function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-choreo-grid]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.choreoGrid='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
  function boot(){style();let n=0;const r=()=>{card();if(!$('[data-choreo-grid]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.cgBound)return;b.dataset.cgBound='1';b.addEventListener('click',()=>setTimeout(card))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · choreography strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel choreo-grid';root.innerHTML=`<div class="cg-hud">${['Count','Energy','Focus','Trust','Score','Unlock'].map((x,i)=>`<div class="cg-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="cg-layout"><section class="cg-card"><div class="cg-stage" role="grid" aria-label="Five by five choreography stage">${Array.from({length:25},(_,i)=>`<div class="cg-cell" role="gridcell" data-center="${i===12}"></div>`).join('')}<div class="cg-dancers"></div></div><div class="cg-bars"></div></section><aside class="cg-card"><div class="result-card cg-brief" aria-live="polite"></div><p class="eyebrow">Select dancer</p><div class="cg-dancers-list cg-dancers"></div><p class="eyebrow">Move this count</p><div class="cg-moves"><button data-m="up">↑</button><button data-m="hold">Hold</button><button data-m="right">→</button><button data-m="left">←</button><button data-m="center">Center</button><button data-m="down">↓</button></div><div class="cg-actions"><button class="primary" data-a="commit">Commit count</button><button data-a="canon">Use canon cue</button><button data-a="recover">Rehearsal reset</button><button data-a="restart">New piece</button></div><p class="cg-note">Arrow keys move the selected dancer. Number keys 1–4 select dancers.</p></aside></div>`;stage.append(root);
    let st,ended=false;
    function reset(){st={count:0,energy:100,focus:62,trust:72,score:0,selected:0,dancers:[{x:1,y:1},{x:3,y:1},{x:1,y:3},{x:3,y:3}],pending:[0,0,0,0],unlock:false,canon:false,recovery:true,lastMotion:0};ended=false;log('Rehearsal begins.',BRIEFS[0].goal);draw()}
    function move(dx,dy){if(ended)return;const d=st.dancers[st.selected];d.x=clamp(d.x+dx,0,4);d.y=clamp(d.y+dy,0,4);st.pending[st.selected]++;draw()}
    function center(){if(ended)return;st.dancers[st.selected]={x:2,y:2};st.pending[st.selected]+=2;draw()}
    function metrics(){const ds=st.dancers;let dist=0,pairs=0,collisions=0;for(let i=0;i<ds.length;i++)for(let j=i+1;j<ds.length;j++){dist+=Math.abs(ds[i].x-ds[j].x)+Math.abs(ds[i].y-ds[j].y);pairs++;if(ds[i].x===ds[j].x&&ds[i].y===ds[j].y)collisions++}const spread=dist/pairs*2.2;const sym=10-(Math.abs((ds[0].x+ds[1].x)-4)+Math.abs((ds[2].x+ds[3].x)-4)+Math.abs(ds[0].y-ds[1].y)+Math.abs(ds[2].y-ds[3].y));const motion=st.pending.reduce((a,b)=>a+b,0)*1.7+(st.canon?3:0);return{spread:clamp(spread,0,10),sym:clamp(sym,0,10),motion:clamp(motion,0,10),collisions}}
    function commit(){if(ended)return;const b=BRIEFS[st.count],m=metrics(),cost=6+st.pending.reduce((a,v)=>a+v,0)*3+(st.canon?8:0);if(st.energy<cost)return end(false,'The company runs out of energy before the phrase lands.');st.energy-=cost;const fit=100-(Math.abs(m.spread-b.spread)+Math.abs(m.sym-b.sym)+Math.abs(m.motion-b.motion))*5-m.collisions*38;const quality=clamp(Math.round(fit),0,100);st.score+=quality*18;st.focus=clamp(st.focus+(quality>=80?8:quality<50?-16:-3),0,100);st.trust=clamp(st.trust+(m.collisions?-18:quality>=75?5:-4),0,100);st.lastMotion=m.motion;st.pending=[0,0,0,0];st.canon=false;if(st.score>=5000)st.unlock=true;if(m.collisions>=2||st.trust<=0)return end(false,'Repeated collisions break the rehearsal.');if(st.count>=BRIEFS.length-1)return end(true);st.count++;log(quality>=82?'The phrase reads clearly.':quality>=60?'The phrase works, but lacks definition.':'The staging loses focus.',BRIEFS[st.count].goal);draw()}
    function canon(){if(ended||!st.unlock||st.canon)return;st.canon=true;st.pending=st.pending.map((v,i)=>v+(i%2));log('Canon cue armed.','The next count gains motion and focus, but costs more energy.');draw()}
    function recover(){if(ended||!st.recovery)return;st.recovery=false;st.energy=clamp(st.energy+28,0,100);st.trust=clamp(st.trust-12,0,100);st.score=Math.max(0,st.score-700);st.dancers=[{x:1,y:1},{x:3,y:1},{x:1,y:3},{x:3,y:3}];st.pending=[0,0,0,0];log('The choreographer calls a full reset.','Energy returns, but score and trust drop.');draw()}
    function end(success,msg){ended=true;const strong=success&&st.score>=7000&&st.trust>=55;log(msg||(strong?'The final tableau earns a standing ovation.':success?'The piece reaches opening night with a fragile finish.':'The rehearsal unravels.'),`Final score ${st.score}, trust ${st.trust}, focus ${st.focus}. Replay to test a different movement language.`);draw()}
    function log(a,b){const l=$('.cg-brief',root);l.replaceChildren(Object.assign(document.createElement('strong'),{textContent:a}),Object.assign(document.createElement('small'),{textContent:b}))}
    function draw(){const vals=[`${Math.min(st.count+1,6)}/6`,st.energy,st.focus,st.trust,st.score,st.unlock?'Canon':'Locked'];$$('[data-h]',root).forEach((e,i)=>e.textContent=vals[i]);$('.cg-dancers-list',root).innerHTML=st.dancers.map((_,i)=>`<button data-d="${i}" aria-pressed="${st.selected===i}">Dancer ${i+1}</button>`).join('');$('.cg-dancers',root).innerHTML=st.dancers.map((d,i)=>`<button class="cg-dancer cg-${i+1}" data-d="${i}" aria-selected="${st.selected===i}" style="left:${10+d.x*20}%;top:${10+d.y*20}%" aria-label="Dancer ${i+1}, column ${d.x+1}, row ${d.y+1}">${i+1}</button>`).join('');$('.cg-bars',root).innerHTML=[['Energy',st.energy],['Focus',st.focus],['Trust',st.trust]].map(([n,v])=>`<div class="cg-bar"><span>${n}</span><i><b style="width:${v}%"></b></i><strong>${v}</strong></div>`).join('');$('[data-a="commit"]',root).disabled=ended;$('[data-a="canon"]',root).disabled=ended||!st.unlock||st.canon;$('[data-a="recover"]',root).disabled=ended||!st.recovery}
    root.addEventListener('click',e=>{const d=e.target.closest('[data-d]');if(d){st.selected=Number(d.dataset.d);draw();return}const m=e.target.closest('[data-m]')?.dataset.m;if(m==='up')move(0,-1);if(m==='down')move(0,1);if(m==='left')move(-1,0);if(m==='right')move(1,0);if(m==='center')center();if(m==='hold')draw();const a=e.target.closest('[data-a]')?.dataset.a;if(a==='commit')commit();if(a==='canon')canon();if(a==='recover')recover();if(a==='restart')reset()});
    root.addEventListener('keydown',e=>{if(['1','2','3','4'].includes(e.key)){st.selected=Number(e.key)-1;draw();return}const map={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]};if(map[e.key]){e.preventDefault();move(...map[e.key])}});dialog.addEventListener('close',()=>root.replaceChildren(),{once:true});reset()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
