(() => {
  const APP={name:'Cistern Lock',emoji:'🚢',category:'play',version:'1.0.0',summary:'Move boats through a stepped canal by tuning gates, pumps, tide pressure, water levels, and queue patience.',description:'A local canal-lock strategy puzzle with stepped water chambers, boats with draft limits, gates, pumps, leaks, pressure, queue patience, adaptive rounds, recoverable floods, session-only night tide, scoring, responsive SVG rendering, touch and keyboard controls, reduced-motion behavior, optional audio, and teardown.'};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const label=v=>v==='play'?'Play':v==='useful'?'Useful':'Experiment';
  function style(){if($('#cistern-lock-styles'))return;const s=document.createElement('style');s.id='cistern-lock-styles';s.textContent=`.cistern-card{animation:cistern-in .24s ease both}.cistern-game{max-width:1100px;gap:14px}.cistern-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.cistern-stat{border:1px solid var(--line);border-radius:15px;background:#fff;padding:10px 12px}.cistern-stat span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.cistern-stat strong{display:block;margin-top:4px}.cistern-board{display:grid;grid-template-columns:1fr .82fr;gap:10px}.cistern-map{border:0;border-radius:28px;background:#071424;color:white;padding:0;overflow:hidden;touch-action:none;box-shadow:inset 0 0 0 1px rgba(255,255,255,.16)}.cistern-map:focus-visible{outline:4px solid var(--accent);outline-offset:4px}.cistern-map svg{display:block;width:100%;height:min(58vh,500px);min-height:350px}.cistern-panel{border:1px solid var(--line);border-radius:18px;background:#fff;padding:13px}.cistern-tools,.cistern-modes{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.cistern-chip{border:1px solid var(--line);border-radius:999px;background:#fff;color:var(--ink);padding:8px 11px;font-weight:900}.cistern-chip.is-active{background:#111827;color:#fff}.cistern-log{min-height:104px;padding:17px 19px}.cistern-meter{height:12px;border-radius:999px;background:#e7f5ff;overflow:hidden;margin-top:8px}.cistern-meter span{display:block;height:100%;width:30%;background:linear-gradient(90deg,#93c5fd,#38bdf8,#facc15)}@media(max-width:780px){.cistern-hud{grid-template-columns:repeat(2,1fr)}.cistern-board{grid-template-columns:1fr}.cistern-map svg{height:54vh;min-height:330px}}@media(prefers-reduced-motion:reduce){.cistern-card{animation:none}.cistern-map svg{min-height:320px}}@keyframes cistern-in{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}`;document.head.append(s);}
  function addCard(){const grid=$('#app-grid'),tpl=$('#app-card-template');if(!grid||!tpl||$('[data-cistern-card]'))return;const f=$('.filter.is-active')?.dataset.filter||'all';if(f!=='all'&&f!==APP.category)return;style();const node=tpl.content.cloneNode(true),card=$('.app-card',node);card.dataset.category=APP.category;card.dataset.cisternCard='true';card.classList.add('cistern-card');$('.app-icon',node).textContent=APP.emoji;$('.app-meta',node).textContent=`${label(APP.category)} · v${APP.version}`;$('.app-name',node).textContent=APP.name;$('.app-summary',node).textContent=APP.summary;const btn=$('.app-card-button',node);btn.setAttribute('aria-label',`Open ${APP.name}`);btn.addEventListener('click',open);grid.append(node);}
  function boot(){style();let tries=0;const retry=()=>{addCard();if(!$('[data-cistern-card]')&&tries++<20)setTimeout(retry,120)};retry();$$('.filter').forEach(b=>{if(b.dataset.cisternRefresh)return;b.dataset.cisternRefresh='1';b.addEventListener('click',()=>setTimeout(addCard,0));});}
  function open(){const dialog=$('#app-dialog'),stage=$('#app-stage'),title=$('#dialog-title'),cat=$('#dialog-category'),desc=$('#dialog-description'),fb=$('#dialog-feedback');if(!dialog||!stage)return;title.textContent=APP.name;cat.textContent=`${label(APP.category)} · ${APP.emoji}`;desc.textContent=APP.description;fb.href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Cistern%20Lock';stage.replaceChildren();game(stage,dialog);dialog.showModal();}
  function game(stage,dialog){
    const root=document.createElement('section');root.className='tool-panel cistern-game';root.innerHTML=`<div class="cistern-hud"><div class="cistern-stat"><span>Round</span><strong id="cl-round">1 / 6</strong></div><div class="cistern-stat"><span>Energy</span><strong id="cl-energy">12</strong></div><div class="cistern-stat"><span>Moved</span><strong id="cl-moved">0</strong></div><div class="cistern-stat"><span>Pressure</span><strong id="cl-pressure">0</strong></div><div class="cistern-stat"><span>Patience</span><strong id="cl-patience">9</strong></div><div class="cistern-stat"><span>Score</span><strong id="cl-score">0</strong></div></div><div class="cistern-board"><button class="cistern-map" type="button" aria-label="Cistern Lock canal. Use arrow keys to choose a chamber, Up or Down to pump water, Enter to open the next gate, Space to run a tide tick, and N for a new round."><svg role="img" aria-label="Canal lock chambers"></svg></button><div class="cistern-panel"><strong>Lock house</strong><p id="cl-task"></p><div class="cistern-meter"><span id="cl-meter"></span></div><div class="cistern-tools"><button class="button button-secondary cistern-chip" type="button" data-act="up">Pump up</button><button class="button button-secondary cistern-chip" type="button" data-act="down">Drain</button><button class="button button-secondary cistern-chip" type="button" data-act="gate">Open gate</button><button class="button button-secondary cistern-chip" type="button" data-act="tick">Tide tick</button><button class="button button-secondary cistern-chip" type="button" data-act="new">New round</button></div><p><small>Match adjacent chamber levels before opening gates. Deep cargo needs higher water, leaks add pressure, and waiting boats lose patience.</small></p></div></div><div class="result-card cistern-log" aria-live="polite"></div><div class="tool-actions"></div>`;
    stage.append(root);const svg=$('svg',root),board=$('.cistern-map',root),log=$('.cistern-log',root),meter=$('#cl-meter',root),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
    const st={round:1,rounds:6,energy:12,score:0,pressure:0,patience:9,cursor:0,moved:0,night:false,audio:false,ac:null,anim:0,levels:[],leaks:[],boats:[]};
    $('.tool-actions',root).append(btn('Night tide',night,true),btn('Sound off',sound,true));$$('[data-act]',root).forEach(b=>b.addEventListener('click',()=>act(b.dataset.act)));board.addEventListener('keydown',key);board.addEventListener('click',point);board.addEventListener('pointerdown',point);dialog.addEventListener('close',tear,{once:true});newRound();
    function btn(t,f,sec){const b=document.createElement('button');b.type='button';b.className=sec?'button button-secondary':'button';b.textContent=t;b.addEventListener('click',f);return b;}
    function say(h){log.innerHTML=h;}
    function seed(){st.levels=[2,3,4,5,4,3];st.leaks=[false,false,st.round>2,false,st.round>4||st.night,false];st.boats=Array.from({length:3+Math.floor(st.round/2)+(st.night?1:0)},(_,i)=>({pos:0,need:2+((i+st.round)%4),done:false,heavy:i%3===1}));}
    function newRound(){cancelAnimationFrame(st.anim);Object.assign(st,{energy:st.night?10:12,pressure:0,patience:9,cursor:0,moved:0});seed();say(`<strong>Round ${st.round} ready.</strong><small>Raise and drain chambers so boats can climb the lock without flooding the quay.</small>`);paint();draw();}
    function active(){return st.boats.find(b=>!b.done);}
    function safeGate(b){if(!b||b.pos>=5)return false;return Math.abs(st.levels[b.pos]-st.levels[b.pos+1])<=1&&st.levels[b.pos]>=b.need&&st.levels[b.pos+1]>=b.need-1;}
    function grade(){const waiting=st.boats.filter(b=>!b.done).length;return {waiting,done:st.boats.length-waiting,goal:st.boats.length,ok:st.pressure<12&&st.patience>0};}
    function paint(){const g=grade();$('#cl-round',root).textContent=`${st.round} / ${st.rounds}`;$('#cl-energy',root).textContent=st.energy;$('#cl-moved',root).textContent=`${g.done} / ${g.goal}`;$('#cl-pressure',root).textContent=st.pressure;$('#cl-patience',root).textContent=st.patience;$('#cl-score',root).textContent=st.score;$('#cl-task',root).textContent=`Guide ${g.goal} boats through ${st.night?'night tide':'day tide'} round ${st.round}. Keep pressure under 12 and patience above zero.`;meter.style.width=`${Math.round(g.done/g.goal*100)}%`;}
    function pump(d){if(st.energy<1){say('<strong>No pump energy.</strong><small>Run a tide tick or risk opening a gate with the levels you have.</small>');return;}const i=st.cursor;st.levels[i]=Math.max(1,Math.min(7,st.levels[i]+d));st.energy--;st.pressure+=st.leaks[i]?2:1;st.patience=Math.max(0,st.patience-(st.night?1:0));say(`<strong>Chamber ${i+1} ${d>0?'raised':'drained'}.</strong><small>${st.leaks[i]?'A leak made pressure rise faster.':'Water shifted cleanly.'}</small>`);beep(d>0?560:320);paint();draw();}
    function gate(){const b=active();if(!b){finish();return;}if(safeGate(b)){b.pos++;st.moved++;st.pressure=Math.max(0,st.pressure-1);if(b.pos>=5)b.done=true;say(`<strong>${b.heavy?'Heavy barge':'Skiff'} advanced.</strong><small>${b.done?'It cleared the canal.':'Prepare the next chamber before pressure builds.'}</small>`);beep(760);if(!active())finish();}else{st.pressure+=3;st.patience=Math.max(0,st.patience-2);say('<strong>Gate surge contained.</strong><small>Adjacent water levels or boat draft did not match. Pressure rose, but you can recover.</small>');beep(180);}paint();draw();}
    function tick(){st.energy+=st.night?2:1;st.patience=Math.max(0,st.patience-1);st.pressure+=st.leaks.filter(Boolean).length;st.levels=st.levels.map((v,i)=>Math.max(1,Math.min(7,v+(st.night&&i%2===st.round%2?1:0))));say('<strong>Tide tick passed.</strong><small>Energy returns, patience drops, and leaks keep pushing pressure upward.</small>');paint();draw();}
    function finish(){const g=grade(), pass=g.done===g.goal&&g.ok;if(pass){const gain=220+g.done*80+st.energy*12+st.patience*18-st.pressure*10;st.score+=Math.max(80,Math.round(gain));beep(920);if(st.round<st.rounds){st.round++;say('<strong>Convoy cleared.</strong><small>The next manifest adds deeper drafts and more leak risk.</small>');newRound();}else say(`<strong>Canal run complete: ${st.score}.</strong><small>${st.score>=2100?'Night tide is unlocked for this session.':'Score 2100 to unlock night tide.'}</small>`);}else{st.score=Math.max(0,st.score-100);st.energy+=3;st.pressure=Math.max(0,st.pressure-4);st.patience+=2;beep(160);say('<strong>Flood drill reset.</strong><small>Emergency crews restored energy and patience. Try matching one gate at a time.</small>');}paint();draw();}
    function act(k){if(k==='up')pump(1);if(k==='down')pump(-1);if(k==='gate')gate();if(k==='tick')tick();if(k==='new')newRound();}
    function night(e){if(!st.night&&st.score<2100)return say('<strong>Night tide locked.</strong><small>Score 2100 in day tide to unlock moving tidal water and tighter energy.</small>');st.night=!st.night;st.round=1;newRound();if(e?.currentTarget)e.currentTarget.setAttribute('aria-pressed',String(st.night));}
    function point(e){const r=svg.getBoundingClientRect(),x=(e.clientX-r.left)/r.width;st.cursor=Math.max(0,Math.min(5,Math.floor(x*6)));paint();draw();}
    function key(e){const k=e.key.toLowerCase();if(k==='arrowright'){e.preventDefault();st.cursor=Math.min(5,st.cursor+1);draw();}if(k==='arrowleft'){e.preventDefault();st.cursor=Math.max(0,st.cursor-1);draw();}if(k==='arrowup'){e.preventDefault();pump(1);}if(k==='arrowdown'){e.preventDefault();pump(-1);}if(k==='enter'){e.preventDefault();gate();}if(k===' '){e.preventDefault();tick();}if(k==='n'){e.preventDefault();newRound();}}
    function draw(){const W=720,H=420,cw=W/6;let h=`<rect width="${W}" height="${H}" fill="#071424"/>`;for(let i=0;i<6;i++){const x=i*cw+8,l=st.levels[i],wy=H-36-l*43;h+=`<rect x="${x}" y="55" width="${cw-16}" height="310" rx="18" fill="#10233a" stroke="${i===st.cursor?'#facc15':'rgba(255,255,255,.18)'}" stroke-width="${i===st.cursor?5:2}"/><rect x="${x+8}" y="${wy}" width="${cw-32}" height="${365-wy}" rx="12" fill="#38bdf8" opacity=".72"/><text x="${x+cw/2-8}" y="390" text-anchor="middle" fill="#dbeafe" font-size="18">L${l}</text>`;if(st.leaks[i])h+=`<circle cx="${x+cw-30}" cy="82" r="10" fill="#fb7185"><title>Leak pressure</title></circle>`;}st.boats.forEach((b,n)=>{if(b.done)return;const x=b.pos*cw+34,y=310-n*22-b.need*4;h+=`<path d="M${x} ${y}h70l-12 20h-46z" fill="${b.heavy?'#fbbf24':'#f8fafc'}"/><text x="${x+35}" y="${y-6}" text-anchor="middle" fill="#fff" font-size="14">D${b.need}</text>`;});h+=`<text x="24" y="34" fill="#e0f2fe" font-size="18">Selected chamber ${st.cursor+1}. Active boat needs depth ${active()?.need||'done'}.</text>`;svg.innerHTML=h;if(!reduced){cancelAnimationFrame(st.anim);st.anim=requestAnimationFrame(()=>{svg.style.transform='translateY(0)';});}}
    function sound(e){const A=window.AudioContext||window.webkitAudioContext;if(!A){say('<strong>Sound is not available here.</strong><small>The lock works without audio.</small>');return;}st.audio=!st.audio;if(e?.currentTarget){e.currentTarget.textContent=st.audio?'Sound on':'Sound off';e.currentTarget.setAttribute('aria-pressed',String(st.audio));}st.ac ||= new A();st.ac.resume();beep(480);}
    function beep(f){if(!st.audio||!st.ac)return;const o=st.ac.createOscillator(),g=st.ac.createGain(),now=st.ac.currentTime;o.type='triangle';o.frequency.setValueAtTime(f,now);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.07,now+.02);g.gain.exponentialRampToValueAtTime(.0001,now+.18);o.connect(g).connect(st.ac.destination);o.start(now);o.stop(now+.2);}
    function tear(){cancelAnimationFrame(st.anim);if(st.ac)st.ac.close().catch(()=>{});}
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();