(() => {
'use strict';
const APP={name:'Civic Ledger',emoji:'🏛️',category:'play',version:'1.0.0',summary:'Balance six city budgets through shocks, tradeoffs, public trust, equity, and long-term resilience.',description:'A local-only municipal strategy simulation with six fiscal years, competing service portfolios, changing public priorities, revenue and reserve decisions, debt, random shocks, scoring, progression, failure, recovery, a session unlock, keyboard and touch controls, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const YEARS=[
 {name:'Year 1 · Stable growth',revenue:24,target:58,shock:null,priorities:['housing','transit']},
 {name:'Year 2 · Heat season',revenue:25,target:62,shock:'heat',priorities:['health','parks']},
 {name:'Year 3 · Factory closure',revenue:22,target:65,shock:'jobs',priorities:['housing','safety']},
 {name:'Year 4 · Flood warning',revenue:26,target:69,shock:'flood',priorities:['infrastructure','health']},
 {name:'Year 5 · Population surge',revenue:29,target:73,shock:'growth',priorities:['transit','housing']},
 {name:'Year 6 · Bond referendum',revenue:31,target:77,shock:'audit',priorities:['infrastructure','parks']}
];
const SERVICES=[
 {id:'housing',label:'Housing',icon:'⌂',base:3,equity:10,trust:7,resilience:3},
 {id:'transit',label:'Transit',icon:'↔',base:3,equity:6,trust:5,resilience:7},
 {id:'health',label:'Public health',icon:'✚',base:3,equity:8,trust:6,resilience:8},
 {id:'safety',label:'Safety',icon:'◆',base:3,equity:2,trust:7,resilience:5},
 {id:'parks',label:'Parks',icon:'♣',base:2,equity:5,trust:8,resilience:4},
 {id:'infrastructure',label:'Infrastructure',icon:'▦',base:4,equity:3,trust:4,resilience:11}
];
const SHOCKS={
 heat:{label:'Record heat',text:'Health and parks need extra capacity.',need:['health','parks'],reserve:3},
 jobs:{label:'Factory closure',text:'Housing pressure and safety concerns rise.',need:['housing','safety'],reserve:3},
 flood:{label:'River crest',text:'Infrastructure and health systems are tested.',need:['infrastructure','health'],reserve:5},
 growth:{label:'Population surge',text:'Transit and housing demand outpace forecasts.',need:['transit','housing'],reserve:4},
 audit:{label:'State audit',text:'Debt and underfunded basics draw scrutiny.',need:['infrastructure','parks'],reserve:2}
};
function style(){if($('#civic-ledger-style'))return;const e=document.createElement('style');e.id='civic-ledger-style';e.textContent=`
.civic-ledger{max-width:1120px;display:grid;gap:12px}.cl-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.cl-stat,.cl-panel{border:1px solid var(--line);border-radius:17px;background:#fff}.cl-stat{padding:9px}.cl-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.cl-layout{display:grid;grid-template-columns:1.15fr .85fr;gap:12px}.cl-panel{padding:15px}.cl-banner{border-radius:18px;padding:16px;background:linear-gradient(135deg,#17233f,#315c7b);color:#fff;position:relative;overflow:hidden}.cl-banner::after{content:'';position:absolute;inset:auto -20px -50px auto;width:180px;height:180px;border-radius:50%;background:#ffffff16}.cl-priorities{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.cl-chip,.cl-line{padding:5px 8px;border-radius:999px;background:#eef3f7;font-size:.72rem}.cl-banner .cl-chip{background:#ffffff20}.cl-services{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:12px}.cl-service{border:1px solid var(--line);border-radius:13px;padding:10px;background:#fff}.cl-service-head{display:flex;justify-content:space-between;gap:8px;align-items:center}.cl-service strong{font-size:.9rem}.cl-stepper{display:grid;grid-template-columns:42px 1fr 42px;gap:6px;align-items:center;margin-top:8px}.cl-stepper button{min-height:42px;border:1px solid var(--line);border-radius:10px;background:#fff;font-size:1.1rem;font-weight:900}.cl-stepper output{text-align:center;font-weight:900}.cl-stepper button:focus-visible,.cl-actions button:focus-visible{outline:3px solid #315c7b;outline-offset:2px}.cl-meter{height:11px;background:#e8ebf1;border-radius:99px;overflow:hidden}.cl-meter span{display:block;height:100%;background:#315c7b;transition:width .25s}.cl-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.cl-actions button{min-height:46px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800}.cl-actions .primary{background:#e9f5fb;border-color:#315c7b}.cl-log{min-height:112px}.cl-summary{display:grid;gap:7px}.cl-row{display:flex;justify-content:space-between;gap:10px}.cl-warning{color:#9f3e24;font-weight:800}.cl-good{color:#1d6f4b;font-weight:800}.cl-hint{font-size:.82rem;color:var(--muted)}
@media(max-width:840px){.cl-layout{grid-template-columns:1fr}.cl-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.cl-hud{grid-template-columns:repeat(2,1fr)}.cl-services,.cl-actions{grid-template-columns:1fr}.cl-banner{padding:13px}.cl-stepper{grid-template-columns:48px 1fr 48px}}@media(prefers-reduced-motion:reduce){.civic-ledger *{animation:none!important;transition:none!important}}
`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-civic-ledger]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true),a=$('.app-card',f);a.dataset.civicLedger='1';a.dataset.category=APP.category;$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-civic-ledger]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.clBound)return;b.dataset.clBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · civic strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
 const root=document.createElement('section');root.className='tool-panel civic-ledger';root.innerHTML=`<div class="cl-hud">${['Year','Funds','Reserve','Debt','Trust','Score'].map((x,i)=>`<div class="cl-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="cl-layout"><section class="cl-panel"><div class="cl-banner"><p class="app-meta" data-year></p><h3 data-title></h3><p data-brief></p><div class="cl-priorities" data-priorities></div></div><div class="cl-services" data-services></div><p class="cl-hint">Allocate funds, preserve reserves, and submit the budget. Keyboard: 1-6 select service, ↑/↓ adjust, B issue bond, R use reserve, Enter submit.</p></section><aside class="cl-panel"><div class="result-card cl-log" aria-live="polite"></div><div class="cl-summary"><div class="cl-row"><span>Allocated</span><strong data-allocated></strong></div><div class="cl-row"><span>Equity</span><strong data-equity></strong></div><div class="cl-row"><span>Resilience</span><strong data-resilience></strong></div><div class="cl-row"><span>Public confidence</span><strong data-confidence></strong></div></div><p><strong>Budget pressure</strong></p><div class="cl-meter"><span data-meter></span></div><div class="cl-actions"><button class="primary" data-a="submit">Adopt budget</button><button data-a="bond">Issue civic bond</button><button data-a="reserve">Emergency reserve</button><button data-a="undo">Undo adjustment</button><button data-a="recover">State stabilization aid</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
 let st,ended=false,keyHandler,closeHandler;
 function current(){return YEARS[st.year]}
 function reset(){st={year:0,funds:YEARS[0].revenue,reserve:7,debt:0,trust:64,score:0,alloc:Object.fromEntries(SERVICES.map(x=>[x.id,x.base])),selected:0,history:[],aid:true,bondUsed:false,reserveUsed:false,unlock:false};ended=false;log('Council session opened.','Build a balanced budget without hollowing out the city’s future.');draw()}
 function startYear(){const y=current();st.funds=y.revenue+Math.floor(st.trust/25)-Math.ceil(st.debt/6);st.alloc=Object.fromEntries(SERVICES.map(x=>[x.id,x.base]));st.history=[];st.bondUsed=false;st.reserveUsed=false;log(y.name,y.shock?SHOCKS[y.shock].text:'No immediate crisis, but priorities still compete.');draw()}
 function allocated(){return Object.values(st.alloc).reduce((a,b)=>a+b,0)}
 function metrics(){const y=current();let equity=25,resilience=22,confidence=30;SERVICES.forEach(s=>{const n=st.alloc[s.id];equity+=n*s.equity*.55;resilience+=n*s.resilience*.52;confidence+=n*s.trust*.45;if(n<s.base){equity-=5;confidence-=7}});y.priorities.forEach(id=>{const n=st.alloc[id];equity+=(n>=5?8:-8);confidence+=(n>=5?7:-9)});const shock=y.shock&&SHOCKS[y.shock];if(shock)shock.need.forEach(id=>{resilience+=st.alloc[id]>=6?10:-14});confidence-=st.debt*1.2;equity-=Math.max(0,st.debt-10);return{equity:clamp(equity,0,100),resilience:clamp(resilience,0,100),confidence:clamp(confidence,0,100)}}
 function adjust(delta){if(ended)return;const s=SERVICES[st.selected],next=clamp(st.alloc[s.id]+delta,0,10);if(next===st.alloc[s.id])return;st.history.push({id:s.id,value:st.alloc[s.id]});st.alloc[s.id]=next;draw()}
 function undo(){if(ended||!st.history.length)return log('Nothing to undo.','No allocation change is available.');const h=st.history.pop();st.alloc[h.id]=h.value;log('Adjustment reversed.','The previous service allocation was restored.');draw()}
 function bond(){if(ended||st.bondUsed)return log('Bond unavailable.','Only one bond package may be issued per fiscal year.');st.bondUsed=true;st.funds+=6;st.debt+=7;st.trust=clamp(st.trust-4,0,100);log('Bond issued.','Six funds are available now, but debt and public skepticism rise.');draw()}
 function reserve(){if(ended||st.reserveUsed)return log('Reserve unavailable.','Emergency reserves may be drawn once per fiscal year.');if(st.reserve<3)return log('Reserve too low.','At least three reserve points are required.');st.reserveUsed=true;st.reserve-=3;st.funds+=4;st.trust=clamp(st.trust-2,0,100);log('Reserve released.','Four funds were added at the cost of future shock protection.');draw()}
 function submit(){if(ended)return;const spend=allocated(),m=metrics(),y=current(),shock=y.shock&&SHOCKS[y.shock];if(spend>st.funds)return log('Budget rejected.',`Allocated ${spend}, but only ${st.funds} funds are available.`);const unspent=st.funds-spend;st.reserve=clamp(st.reserve+Math.min(3,Math.floor(unspent/2)),0,20);let shockPenalty=0;if(shock){const covered=shock.need.filter(id=>st.alloc[id]>=6).length;shockPenalty=(2-covered)*12;if(st.reserve<shock.reserve)shockPenalty+=10}const balance=m.equity*.34+m.resilience*.34+m.confidence*.32-shockPenalty-Math.max(0,st.debt-14)*1.5;const success=balance>=y.target&&m.equity>=42&&m.resilience>=42;st.trust=clamp(st.trust+(success?8:-11)+Math.min(4,unspent)-Math.floor(st.debt/12),0,100);st.score+=Math.max(0,Math.round(balance*8+unspent*12-st.debt*3));if(st.score>=1500)st.unlock=true;if(!success){log('Budget survives, but confidence falls.',`Needed ${y.target}; achieved ${Math.round(balance)}. Equity ${Math.round(m.equity)}, resilience ${Math.round(m.resilience)}.`);if(st.trust<=18||st.debt>=32)return finish(false,'The city entered fiscal receivership.');draw();return}if(st.year===YEARS.length-1)return finish(true,`Six-year plan completed. Final score ${st.score}.`);st.year++;startYear()}
 function recover(){if(ended||!st.aid)return log('Aid unavailable.','State stabilization aid can be accepted once per session.');st.aid=false;st.score=Math.max(0,st.score-280);st.trust=clamp(st.trust-8,0,100);st.debt=Math.max(0,st.debt-5);st.reserve=Math.max(st.reserve,6);st.funds+=5;log('Stabilization aid accepted.','Debt and reserves improve, but local trust and score decline.');draw()}
 function finish(win,msg){ended=true;log(win?'Long-range plan adopted.':'Fiscal emergency.',msg);draw()}
 function log(a,b){$('.cl-log',root).innerHTML=`<strong>${a}</strong><p>${b}</p>`}
 function draw(){const y=current(),m=metrics(),spend=allocated(),pressure=clamp((spend/st.funds)*100,0,130);$$('[data-h]',root).forEach((e,i)=>e.textContent=[`${st.year+1}/6`,st.funds,st.reserve,st.debt,Math.round(st.trust),st.score][i]);$('[data-year]',root).textContent=y.name;$('[data-title]',root).textContent=y.shock?SHOCKS[y.shock].label:'Open budget cycle';$('[data-brief]',root).textContent=y.shock?SHOCKS[y.shock].text:'Revenue is steady. Build capacity before the next disruption.';$('[data-priorities]',root).innerHTML=y.priorities.map(id=>`<span class="cl-chip">Priority: ${SERVICES.find(s=>s.id===id).label}</span>`).join('')+(st.unlock?'<span class="cl-chip">Participatory grant unlocked</span>':'');$('[data-services]',root).innerHTML=SERVICES.map((s,i)=>`<article class="cl-service"><div class="cl-service-head"><strong>${s.icon} ${s.label}</strong><span>${y.priorities.includes(s.id)?'Priority':''}</span></div><div class="cl-stepper"><button type="button" data-service="${i}" data-d="-1" aria-label="Reduce ${s.label}">−</button><output aria-label="${s.label} allocation">${st.alloc[s.id]}</output><button type="button" data-service="${i}" data-d="1" aria-label="Increase ${s.label}">+</button></div></article>`).join('');$$('[data-service]',root).forEach(b=>b.addEventListener('click',()=>{st.selected=+b.dataset.service;adjust(+b.dataset.d)}));$('[data-allocated]',root).textContent=`${spend} / ${st.funds}`;$('[data-equity]',root).textContent=Math.round(m.equity);$('[data-resilience]',root).textContent=Math.round(m.resilience);$('[data-confidence]',root).textContent=Math.round(m.confidence);$('[data-meter]',root).style.width=`${Math.min(100,pressure)}%`;$('[data-meter]',root).style.background=pressure>100?'#a6402b':'#315c7b';$$('[data-a]',root).forEach(b=>{b.disabled=ended&&b.dataset.a!=='restart';if(b.dataset.a==='recover')b.disabled=ended||!st.aid})}
 root.addEventListener('click',e=>{const a=e.target.closest('[data-a]')?.dataset.a;if(a==='submit')submit();if(a==='bond')bond();if(a==='reserve')reserve();if(a==='undo')undo();if(a==='recover')recover();if(a==='restart')reset()});
 keyHandler=e=>{if(!dialog.open)return;if(/^[1-6]$/.test(e.key)){st.selected=+e.key-1;draw()}if(e.key==='ArrowUp'){e.preventDefault();adjust(1)}if(e.key==='ArrowDown'){e.preventDefault();adjust(-1)}if(e.key.toLowerCase()==='b')bond();if(e.key.toLowerCase()==='r')reserve();if(e.key==='Enter')submit()};document.addEventListener('keydown',keyHandler);
 closeHandler=()=>{document.removeEventListener('keydown',keyHandler);dialog.removeEventListener('close',closeHandler)};dialog.addEventListener('close',closeHandler);reset()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
