(()=>{'use strict';
const APP={name:'Coalition Craft',emoji:'🤝',category:'play',version:'1.0.2',summary:'Draft policies, bargain with factions, and hold a fragile coalition together across six escalating councils.',description:'A local strategy game with six councils, rotating policy hands, faction priorities, influence and trust tradeoffs, branching votes, score progression, session unlocks, exact decision rewind, failure recovery, keyboard and touch controls, reduced motion, optional audio, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const FACTIONS=[{name:'Civic League',icon:'🏛️',likes:['access','trust'],hates:'cost'},{name:'Makers Guild',icon:'⚙️',likes:['jobs','speed'],hates:'delay'},{name:'Green Bloc',icon:'🌱',likes:['climate','access'],hates:'risk'},{name:'Neighborhood Forum',icon:'🏘️',likes:['trust','safety'],hates:'speed'}];
const POLICIES=[{name:'Open workshop grants',tags:['jobs','access'],cost:2,risk:1,trust:1},{name:'Rapid permit lane',tags:['speed','jobs'],cost:1,risk:2,trust:-1},{name:'Community audit panel',tags:['trust','safety'],cost:1,risk:0,trust:2},{name:'Green retrofit fund',tags:['climate','jobs'],cost:3,risk:1,trust:1},{name:'Night delivery pilot',tags:['speed','access'],cost:1,risk:2,trust:0},{name:'Public data charter',tags:['trust','access'],cost:2,risk:0,trust:2},{name:'Resilience reserve',tags:['safety','climate'],cost:2,risk:0,trust:1},{name:'Local hiring compact',tags:['jobs','trust'],cost:2,risk:1,trust:1},{name:'Shared street redesign',tags:['access','climate'],cost:2,risk:1,trust:0},{name:'Emergency fast track',tags:['speed','safety'],cost:1,risk:3,trust:-1},{name:'Maintenance guarantee',tags:['safety','jobs'],cost:3,risk:0,trust:2},{name:'Small vendor carve-out',tags:['jobs','access'],cost:2,risk:1,trust:1}];
const COUNCILS=[['Library Annex',6,7,'Expand access without losing neighborhood trust.'],['Market Hall',6,8,'Create jobs while keeping small vendors inside the deal.'],['River Ward',7,9,'Cut climate risk without stalling urgent repairs.'],['Transit Loop',7,10,'Move faster while preserving safety and public legitimacy.'],['Harbor District',8,11,'Balance growth, resilience, and strained civic trust.'],['Citywide Accord',9,12,'Build a durable coalition across every competing priority.']];
function style(){if($('#coalition-style'))return;const e=document.createElement('style');e.id='coalition-style';e.textContent='.coalition{max-width:1120px;display:grid;gap:12px}.cc-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.cc-stat,.cc-panel{background:#fff;border:1px solid var(--line);border-radius:18px}.cc-stat,.cc-panel{padding:12px}.cc-layout{display:grid;grid-template-columns:1.05fr .95fr;gap:12px}.cc-brief{padding:14px;border-radius:16px;background:linear-gradient(135deg,#3b245f,#184a57);color:#fff}.cc-factions,.cc-hand,.cc-agenda,.cc-actions{display:grid;gap:8px;margin-top:10px}.cc-factions,.cc-agenda{grid-template-columns:repeat(2,1fr)}.cc-hand,.cc-actions{grid-template-columns:repeat(3,1fr)}.cc-faction,.cc-slot{padding:10px;border:1px solid var(--line);border-radius:14px}.cc-card{min-height:150px;text-align:left}.cc-card[aria-pressed=true]{background:#efe8f7;border-color:#62428a}.cc-meter{height:9px;background:#e9e5ef;border-radius:999px;overflow:hidden}.cc-meter span{display:block;height:100%;background:#62428a}.cc-log{min-height:96px}@media(max-width:850px){.cc-layout{grid-template-columns:1fr}.cc-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.cc-hud,.cc-factions,.cc-hand,.cc-agenda,.cc-actions{grid-template-columns:1fr}.cc-card{min-height:0}}@media(prefers-reduced-motion:reduce){.coalition *{animation:none!important;transition:none!important}}';document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-coalition]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true),a=$('.app-card',f);a.dataset.coalition='1';a.dataset.category=APP.category;$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;$('.app-card-button',f).addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-coalition]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(!b.dataset.ccBound){b.dataset.ccBound='1';b.addEventListener('click',()=>setTimeout(card))}})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · coalition strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel coalition';root.innerHTML=`<div class="cc-hud">${['Council','Budget','Influence','Trust','Score','Rank'].map((x,i)=>`<div class="cc-stat"><small>${x}</small><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="cc-layout"><section class="cc-panel"><div class="cc-brief"><p data-case></p><h3>Build a two-policy agenda, then call the vote.</h3><p data-brief></p></div><div class="cc-factions" data-factions></div><h3>Policy hand</h3><div class="cc-hand" data-hand></div><p class="map-note">Selecting an active policy rewinds every later draft or bargain so resources remain exact.</p></section><aside class="cc-panel"><h3>Agenda</h3><div class="cc-agenda" data-agenda></div><div class="cc-actions"><button data-a="bargain">Bargain</button><button data-a="undo">Undo</button><button class="button" data-a="vote">Call vote</button><button data-a="recover">Emergency caucus</button><button data-a="restart">New session</button><button data-a="sound" aria-pressed="false">Sound off</button></div><div class="result-card cc-log" aria-live="polite"></div></aside></div>`;stage.append(root);
let st,ended=false,failed=false,transitioning=false,audio=false,ac,timer=null;const h=$$('[data-h]',root),hand=$('[data-hand]',root),agenda=$('[data-agenda]',root),factions=$('[data-factions]',root),log=$('.cc-log',root);const shuffle=a=>a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1]);
function snap(){return JSON.stringify({budget:st.budget,influence:st.influence,trust:st.trust,support:st.support,hand:st.hand,agenda:st.agenda,score:st.score,rank:st.rank,events:st.events})}
function start(){if(timer)clearTimeout(timer);timer=null;transitioning=false;const c=COUNCILS[st?.round||0];st={round:st?.round||0,budget:c[1],influence:3,trust:5,score:st?.score||0,rank:st?.rank||'Convener',support:[3,3,3,3],hand:shuffle(POLICIES).slice(0,5),agenda:[],history:[],events:[],recovery:st?.recovery??true};ended=false;failed=false;draw();say(c[0],c[3])}
function restore(raw){Object.assign(st,JSON.parse(raw))}
function pick(i){if(ended||failed||transitioning)return;const p=st.hand[i];if(!p)return;const eventIndex=st.events.findIndex(e=>e.type==='policy'&&e.name===p.name);if(eventIndex>=0){const target=st.events[eventIndex].before;restore(target);draw();say('Agenda rewound.',`${p.name} and every later bargain or draft were reversed exactly.`);return}if(st.agenda.length>=2)return say('Agenda full.','Remove one policy before selecting another.');if(st.budget<p.cost)return say('Budget gap.',`${p.name} costs ${p.cost}; only ${st.budget} remains.`);const before=snap();st.history.push(before);st.events.push({type:'policy',name:p.name,before});st.agenda.push(p);st.budget-=p.cost;st.trust=clamp(st.trust+p.trust,0,10);FACTIONS.forEach((f,j)=>{const delta=p.tags.filter(t=>f.likes.includes(t)).length-(p.tags.includes(f.hates)?1:0);st.support[j]=clamp(st.support[j]+delta,0,6)});draw()}
function bargain(){if(ended||failed||transitioning||st.influence<1)return;const before=snap(),i=st.support.indexOf(Math.min(...st.support));st.history.push(before);st.events.push({type:'bargain',before});st.influence--;st.support[i]=clamp(st.support[i]+2,0,6);st.trust=clamp(st.trust-1,0,10);draw();say('Private bargain.',`${FACTIONS[i].name} gained support, but public trust fell by one.`)}
function undo(){if(!st.history.length||ended||failed||transitioning)return;restore(st.history.pop());draw();say('Decision reversed.','Agenda, resources, trust, and faction support restored.')}
function vote(){if(ended||failed||transitioning||st.agenda.length!==2)return;const yes=st.support.filter(x=>x>=3).length,quality=st.support.reduce((a,b)=>a+b,0)+st.trust-st.agenda.reduce((a,p)=>a+p.risk,0),target=COUNCILS[st.round][2];if(yes>=3&&quality>=target){const gain=100+quality*10+st.budget*8+st.influence*6;st.score+=gain;st.rank=st.score>=1200?'Coalition architect':st.score>=650?'Floor leader':'Convener';st.history=[];st.events=[];if(st.round===5){ended=true;draw();say('Citywide accord passed.',`Final score ${st.score}.`)}else{transitioning=true;st.round++;draw();timer=setTimeout(start,250)}}else{failed=true;st.score=Math.max(0,st.score-80);st.history=[];st.events=[];draw();say('Coalition fractured.',`Quality ${quality}; target ${target}.`)}}
function recover(){if(!failed||!st.recovery||transitioning)return;st.recovery=false;failed=false;st.score=Math.max(0,st.score-120);st.influence=Math.max(st.influence,2);st.trust=Math.max(st.trust,4);st.support=st.support.map(x=>Math.max(x,2));st.agenda=[];st.budget=COUNCILS[st.round][1];st.history=[];st.events=[];draw();say('Emergency caucus.','The agenda reopened with minimum support restored.')}
function say(a,b){log.innerHTML=`<strong>${a}</strong><small>${b}</small>`}
function draw(){const c=COUNCILS[st.round];h[0].textContent=`${st.round+1} / 6`;h[1].textContent=st.budget;h[2].textContent=st.influence;h[3].textContent=st.trust;h[4].textContent=st.score;h[5].textContent=st.rank;$('[data-case]',root).textContent=`${c[0]} · target ${c[2]}`;$('[data-brief]',root).textContent=transitioning?'Vote verified. The next council is loading.':c[3];factions.replaceChildren(...FACTIONS.map((f,i)=>{const d=document.createElement('div');d.className='cc-faction';d.innerHTML=`<strong>${f.icon} ${f.name}: ${st.support[i]}/6</strong><div class="cc-meter"><span style="width:${st.support[i]/6*100}%"></span></div>`;return d}));hand.replaceChildren(...st.hand.map((p,i)=>{const b=document.createElement('button');b.className='cc-card';b.type='button';b.setAttribute('aria-pressed',String(st.agenda.some(x=>x.name===p.name)));b.disabled=ended||failed||transitioning||(!st.agenda.some(x=>x.name===p.name)&&st.budget<p.cost);b.innerHTML=`<strong>${p.name}</strong><small>${p.tags.join(' · ')}<br>Cost ${p.cost} · risk ${p.risk} · trust ${p.trust>=0?'+':''}${p.trust}</small>`;b.onclick=()=>pick(i);return b}));agenda.replaceChildren(...[0,1].map(i=>{const d=document.createElement('div');d.className='cc-slot';d.textContent=st.agenda[i]?.name||'Open policy slot';return d}));$('[data-a="bargain"]',root).disabled=ended||failed||transitioning||st.influence<1;$('[data-a="undo"]',root).disabled=ended||failed||transitioning||!st.history.length;$('[data-a="vote"]',root).disabled=ended||failed||transitioning||st.agenda.length!==2;$('[data-a="recover"]',root).disabled=transitioning||!failed||!st.recovery}
root.onclick=e=>{const a=e.target.closest('[data-a]')?.dataset.a;if(a==='bargain')bargain();if(a==='undo')undo();if(a==='vote')vote();if(a==='recover')recover();if(a==='restart'){st={round:0,score:0,rank:'Convener',recovery:true};start()}if(a==='sound'){const A=window.AudioContext||window.webkitAudioContext;if(!A)return;audio=!audio;e.target.textContent=audio?'Sound on':'Sound off';e.target.setAttribute('aria-pressed',String(audio));if(audio){ac||=new A();ac.resume()}}};
const close=()=>{if(timer)clearTimeout(timer);if(ac)ac.close().catch(()=>{});dialog.removeEventListener('close',close);root.remove()};dialog.addEventListener('close',close);start()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();