(()=>{'use strict';
const APP={name:'Coalition Craft',emoji:'🤝',category:'play',version:'1.0.4',summary:'Draft policies, bargain with factions, and hold a fragile coalition together across six escalating councils.',description:'A local strategy game with six councils, rotating policy hands, faction priorities, influence and trust tradeoffs, branching votes, score progression, session unlocks, exact undo, failure recovery, keyboard and touch controls, reduced motion, optional audio, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const FACTIONS=[{id:'civic',name:'Civic League',icon:'🏛️',likes:['access','trust'],hates:'cost'},{id:'guild',name:'Makers Guild',icon:'⚙️',likes:['jobs','speed'],hates:'delay'},{id:'green',name:'Green Bloc',icon:'🌱',likes:['climate','access'],hates:'risk'},{id:'neighborhood',name:'Neighborhood Forum',icon:'🏘️',likes:['trust','safety'],hates:'speed'}];
const POLICIES=[
{name:'Open workshop grants',tags:['jobs','access'],cost:2,risk:1,trust:1},{name:'Rapid permit lane',tags:['speed','jobs'],cost:1,risk:2,trust:-1},{name:'Community audit panel',tags:['trust','safety'],cost:1,risk:0,trust:2},{name:'Green retrofit fund',tags:['climate','jobs'],cost:3,risk:1,trust:1},{name:'Night delivery pilot',tags:['speed','access'],cost:1,risk:2,trust:0},{name:'Public data charter',tags:['trust','access'],cost:2,risk:0,trust:2},{name:'Resilience reserve',tags:['safety','climate'],cost:2,risk:0,trust:1},{name:'Local hiring compact',tags:['jobs','trust'],cost:2,risk:1,trust:1},{name:'Shared street redesign',tags:['access','climate'],cost:2,risk:1,trust:0},{name:'Emergency fast track',tags:['speed','safety'],cost:1,risk:3,trust:-1},{name:'Maintenance guarantee',tags:['safety','jobs'],cost:3,risk:0,trust:2},{name:'Small vendor carve-out',tags:['jobs','access'],cost:2,risk:1,trust:1}
];
const COUNCILS=[
{name:'Library Annex',budget:6,target:7,pressure:'Expand access without losing neighborhood trust.'},
{name:'Market Hall',budget:6,target:8,pressure:'Create jobs while keeping small vendors inside the deal.'},
{name:'River Ward',budget:7,target:9,pressure:'Cut climate risk without stalling urgent repairs.'},
{name:'Transit Loop',budget:7,target:10,pressure:'Move faster while preserving safety and public legitimacy.'},
{name:'Harbor District',budget:8,target:11,pressure:'Balance growth, resilience, and strained civic trust.'},
{name:'Citywide Accord',budget:9,target:12,pressure:'Build a durable coalition across every competing priority.'}
];
function style(){if($('#coalition-style'))return;const e=document.createElement('style');e.id='coalition-style';e.textContent=`.coalition{max-width:1120px;display:grid;gap:12px}.cc-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.cc-stat,.cc-panel{background:#fff;border:1px solid var(--line);border-radius:18px}.cc-stat{padding:10px}.cc-stat span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.cc-layout{display:grid;grid-template-columns:1.05fr .95fr;gap:12px}.cc-panel{padding:14px}.cc-brief{padding:14px;border-radius:16px;background:linear-gradient(135deg,#3b245f,#184a57);color:#fff}.cc-factions,.cc-hand,.cc-agenda,.cc-actions{display:grid;gap:8px;margin-top:10px}.cc-factions{grid-template-columns:repeat(2,1fr)}.cc-faction{padding:10px;border:1px solid var(--line);border-radius:14px}.cc-faction strong{display:flex;justify-content:space-between}.cc-meter{height:9px;border-radius:999px;background:#e9e5ef;overflow:hidden;margin-top:6px}.cc-meter span{display:block;height:100%;background:#62428a}.cc-hand{grid-template-columns:repeat(3,1fr)}.cc-card{min-height:150px;text-align:left;display:grid;align-content:start;gap:6px}.cc-card[aria-pressed=true]{background:#efe8f7;border-color:#62428a}.cc-tags{font-size:.72rem;color:var(--muted)}.cc-agenda{grid-template-columns:repeat(2,1fr)}.cc-slot{padding:10px;border:1px dashed #9d8cae;border-radius:14px;min-height:76px}.cc-actions{grid-template-columns:repeat(3,1fr)}.cc-log{min-height:96px}.cc-panel button:focus-visible{outline:3px solid #62428a;outline-offset:2px}@media(max-width:850px){.cc-layout{grid-template-columns:1fr}.cc-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.cc-hud,.cc-factions,.cc-hand,.cc-agenda,.cc-actions{grid-template-columns:1fr}.cc-card{min-height:0}}@media(prefers-reduced-motion:reduce){.coalition *{animation:none!important;transition:none!important}}`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-coalition]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true),a=$('.app-card',f);a.dataset.coalition='1';a.dataset.category=APP.category;$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-coalition]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.ccBound)return;b.dataset.ccBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · coalition strategy';$('#dialog-description').textContent=APP.description;$('#dialog-feedback').href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Coalition%20Craft';s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel coalition';root.innerHTML=`<div class="cc-hud">${['Council','Budget','Influence','Trust','Score','Rank'].map((x,i)=>`<div class="cc-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="cc-layout"><section class="cc-panel"><div class="cc-brief"><p class="app-meta" data-case></p><h3>Build a two-policy agenda, then call the vote.</h3><p data-brief></p></div><div class="cc-factions" data-factions></div><h3>Policy hand</h3><div class="cc-hand" data-hand></div><p class="map-note">Keyboard: arrows move cards, Space selects, B bargains, Enter votes, U undoes.</p></section><aside class="cc-panel"><h3>Agenda</h3><div class="cc-agenda" data-agenda></div><div class="cc-actions"><button data-a="bargain">Bargain</button><button data-a="undo">Undo</button><button class="button" data-a="vote">Call vote</button><button data-a="recover">Emergency caucus</button><button data-a="restart">New session</button><button data-a="sound" aria-pressed="false">Sound off</button></div><div class="result-card cc-log" aria-live="polite"></div></aside></div>`;stage.append(root);
let st,focus=0,ended=false,failed=false,transitioning=false,audio=false,ac,keyHandler,clickHandler,closeHandler,transitionTimer=null;const h=$$('[data-h]',root),hand=$('[data-hand]',root),agenda=$('[data-agenda]',root),factions=$('[data-factions]',root),log=$('.cc-log',root);
const shuffle=a=>a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1]);
function clearTransition(){if(transitionTimer!==null){clearTimeout(transitionTimer);transitionTimer=null}transitioning=false}
function normalBase(round){const c=COUNCILS[round];return{budget:c.budget,influence:3,trust:5,support:FACTIONS.map(()=>3)}}
function baseState(){const b=st.baseline||normalBase(st.round);return{budget:b.budget,influence:b.influence,trust:b.trust,support:[...b.support],agenda:[]}}
function applyPolicy(p){st.agenda.push(p);st.budget-=p.cost;st.trust=clamp(st.trust+p.trust,0,10);FACTIONS.forEach((f,j)=>{const delta=p.tags.filter(t=>f.likes.includes(t)).length-(p.tags.includes(f.hates)?1:0);st.support[j]=clamp(st.support[j]+delta,0,6)})}
function applyBargain(){const lowest=Math.min(...st.support),i=st.support.indexOf(lowest);st.influence--;st.support[i]=clamp(st.support[i]+2,0,6);st.trust=clamp(st.trust-1,0,10)}
function replay(){const base=baseState();st.budget=base.budget;st.influence=base.influence;st.trust=base.trust;st.support=base.support;st.agenda=[];st.actions.forEach(a=>{if(a.type==='policy'){const p=st.hand.find(x=>x.name===a.name);if(p)applyPolicy(p)}else if(a.type==='bargain')applyBargain()})}
function start(){clearTransition();const round=st?.round||0,c=COUNCILS[round],baseline=normalBase(round);st={round,budget:baseline.budget,influence:baseline.influence,trust:baseline.trust,score:st?.score||0,rank:st?.rank||'Convener',support:[...baseline.support],baseline,hand:shuffle(POLICIES).slice(0,5),agenda:[],actions:[],history:[],recovery:st?.recovery??true,wild:st?.wild||false};ended=false;failed=false;focus=0;draw();say(c.name,c.pressure)}
function snap(){return JSON.stringify({budget:st.budget,influence:st.influence,trust:st.trust,support:st.support,baseline:st.baseline,hand:st.hand,agenda:st.agenda,actions:st.actions,score:st.score,rank:st.rank})}
function pick(i){if(ended||failed||transitioning)return;const p=st.hand[i];if(!p)return;if(st.agenda.some(x=>x.name===p.name)){st.history.push(snap());st.actions=st.actions.filter(a=>!(a.type==='policy'&&a.name===p.name));replay();tone('tick');draw();say('Policy removed.',`${p.name} was removed and every later bargain was replayed from the active council baseline.`);return}if(st.agenda.length>=2)return say('Agenda full.','Remove one policy before selecting another.');if(st.budget<p.cost)return say('Budget gap.',`${p.name} costs ${p.cost}; only ${st.budget} remains.`);st.history.push(snap());st.actions.push({type:'policy',name:p.name});applyPolicy(p);tone('tick');draw()}
function bargain(){if(ended||failed||transitioning)return;if(st.influence<1)return say('No influence remains.','Call the vote, undo, or restart.');st.history.push(snap());st.actions.push({type:'bargain'});applyBargain();tone('tick');draw();say('Private bargain.','The lowest-support faction gained support, but public trust fell by one.')}
function undo(){if(!st.history.length||ended||failed||transitioning)return say('Nothing to undo.','No reversible draft or bargain remains.');Object.assign(st,JSON.parse(st.history.pop()));draw();say('Decision reversed.','Agenda, resources, trust, faction support, decision order, and recovery baseline restored.')}
function vote(){if(ended||failed||transitioning)return;if(st.agenda.length!==2)return say('Incomplete agenda.','Select exactly two policies before calling the vote.');const yes=st.support.filter(x=>x>=3).length,quality=st.support.reduce((a,b)=>a+b,0)+st.trust-st.agenda.reduce((a,p)=>a+p.risk,0);const target=COUNCILS[st.round].target;if(yes>=3&&quality>=target){const gain=100+quality*10+st.budget*8+st.influence*6;st.score+=gain;st.rank=st.score>=1200?'Coalition architect':st.score>=650?'Floor leader':'Convener';tone('good');st.history=[];if(st.round===COUNCILS.length-1){ended=true;st.wild=true;draw();say('Citywide accord passed.',`Final score ${st.score}. Consensus wildcard unlocked for this session.`)}else{transitioning=true;st.round++;draw();say('Agenda passed.',`${yes} factions supported it. Score +${gain}. Preparing the next council.`);transitionTimer=setTimeout(()=>{transitionTimer=null;start()},250)}}else{failed=true;st.score=Math.max(0,st.score-80);st.history=[];tone('bad');draw();say('Coalition fractured.',`${yes} factions voted yes; coalition quality was ${quality}, target ${target}. Use the emergency caucus or restart.`)}}
function recover(){if(transitioning)return;if(!failed||!st.recovery)return say('Caucus unavailable.',st.recovery?'It becomes available after a failed vote.':'It was already used this session.');st.recovery=false;failed=false;st.score=Math.max(0,st.score-120);st.baseline={budget:COUNCILS[st.round].budget,influence:2,trust:4,support:FACTIONS.map(()=>2)};st.budget=st.baseline.budget;st.influence=st.baseline.influence;st.trust=st.baseline.trust;st.support=[...st.baseline.support];st.agenda=[];st.actions=[];st.history=[];draw();say('Emergency caucus.','The failed agenda and every bargain were cleared. Budget reopened in a fragile 2-support coalition with 2 influence and 4 trust. Policy replay now preserves this recovery baseline. The 120-point penalty is permanent.')}
function tone(k){if(!audio||!ac)return;const o=ac.createOscillator(),g=ac.createGain(),n=ac.currentTime;o.frequency.value=k==='good'?720:k==='bad'?180:420;g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(.05,n+.02);g.gain.exponentialRampToValueAtTime(.0001,n+.18);o.connect(g).connect(ac.destination);o.start(n);o.stop(n+.2)}
function say(a,b){log.innerHTML=`<strong>${a}</strong><small>${b}</small>`}
function draw(){const c=COUNCILS[st.round];h[0].textContent=`${st.round+1} / ${COUNCILS.length}`;h[1].textContent=st.budget;h[2].textContent=st.influence;h[3].textContent=st.trust;h[4].textContent=st.score;h[5].textContent=st.rank;$('[data-case]',root).textContent=`${c.name} · target ${c.target}`;$('[data-brief]',root).textContent=transitioning?'Vote verified. The next council is loading.':c.pressure;factions.replaceChildren(...FACTIONS.map((f,i)=>{const d=document.createElement('div');d.className='cc-faction';d.innerHTML=`<strong><span>${f.icon} ${f.name}</span><span>${st.support[i]}/6</span></strong><small>Likes ${f.likes.join(' + ')} · resists ${f.hates}</small><div class="cc-meter"><span style="width:${st.support[i]/6*100}%"></span></div>`;return d}));hand.replaceChildren(...st.hand.map((p,i)=>{const b=document.createElement('button');b.type='button';b.className='cc-card';b.dataset.i=i;b.setAttribute('aria-pressed',String(st.agenda.some(x=>x.name===p.name)));b.disabled=ended||failed||transitioning||(!st.agenda.some(x=>x.name===p.name)&&st.budget<p.cost);b.innerHTML=`<strong>${p.name}</strong><span class="cc-tags">${p.tags.join(' · ')}</span><small>Cost ${p.cost} · risk ${p.risk} · trust ${p.trust>=0?'+':''}${p.trust}</small>`;b.addEventListener('click',()=>pick(i));return b}));agenda.replaceChildren(...[0,1].map(i=>{const d=document.createElement('div');d.className='cc-slot';d.innerHTML=st.agenda[i]?`<strong>${st.agenda[i].name}</strong><small>${st.agenda[i].tags.join(' · ')}</small>`:'<strong>Open policy slot</strong><small>Select from the hand.</small>';return d}));$('[data-a="bargain"]',root).disabled=ended||failed||transitioning||st.influence<1;$('[data-a="undo"]',root).disabled=ended||failed||transitioning||!st.history.length;$('[data-a="vote"]',root).disabled=ended||failed||transitioning||st.agenda.length!==2;$('[data-a="recover"]',root).disabled=transitioning||!failed||!st.recovery}
clickHandler=e=>{const a=e.target.closest('[data-a]')?.dataset.a;if(!a)return;if(a==='bargain')bargain();if(a==='undo')undo();if(a==='vote')vote();if(a==='recover')recover();if(a==='restart'){clearTransition();st={round:0,score:0,rank:'Convener',recovery:true,wild:false};start()}if(a==='sound'){const A=window.AudioContext||window.webkitAudioContext;if(!A)return say('Sound unavailable.','The game remains fully playable without audio.');audio=!audio;e.target.textContent=audio?'Sound on':'Sound off';e.target.setAttribute('aria-pressed',String(audio));if(audio){ac||=new A();ac.resume();tone('tick')}}};root.addEventListener('click',clickHandler);
keyHandler=e=>{if(!dialog.open||ended||failed||transitioning)return;const tag=e.target.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag))return;if(e.key==='ArrowRight'||e.key==='ArrowDown'){e.preventDefault();focus=(focus+1)%st.hand.length;$$('.cc-card',root)[focus]?.focus()}if(e.key==='ArrowLeft'||e.key==='ArrowUp'){e.preventDefault();focus=(focus+st.hand.length-1)%st.hand.length;$$('.cc-card',root)[focus]?.focus()}if(e.key===' '){if(e.target.closest('.cc-card'))return;e.preventDefault();pick(focus)}if(e.key.toLowerCase()==='b')bargain();if(e.key.toLowerCase()==='u')undo();if(e.key==='Enter'&&!e.target.closest('button'))vote()};document.addEventListener('keydown',keyHandler);
closeHandler=()=>{clearTransition();root.removeEventListener('click',clickHandler);document.removeEventListener('keydown',keyHandler);dialog.removeEventListener('close',closeHandler);if(ac)ac.close().catch(()=>{});root.remove()};dialog.addEventListener('close',closeHandler);start()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();