(() => {
  'use strict';
  const APP={name:'Common Ground',emoji:'🕊️',category:'experiment',version:'1.0.0',summary:'Mediate a civic dispute by uncovering needs, building trust, and drafting a durable agreement.',description:'A local-only branching mediation workshop with three stakeholders, hidden priorities, evidence cards, limited time, trust and tension, adaptive objections, commitment drafting, failure, recovery, and replayable scenarios.'};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const SCENARIOS=[
    {name:'Night market hours',brief:'Residents want sleep, vendors need income, and transit staff need a predictable close.',stakeholders:[['Residents','Quiet after 10','safety'],['Vendors','Keep peak sales','access'],['Transit','Clear closing plan','cost']],evidence:['Noise peaks after 10:30','Most vendor revenue lands 8–10','One late bus can serve workers'],clauses:['Close amplified music at 10','Keep food stalls until 11','Fund one late transit run']},
    {name:'Riverside redesign',brief:'A flood project must also preserve access, habitat, and small-business foot traffic.',stakeholders:[['Neighbors','Flood protection','access'],['Ecologists','Habitat continuity','safety'],['Merchants','Visible entrances','cost']],evidence:['Two blocks flood first','Native shade reduces heat','Weekend foot traffic funds shops'],clauses:['Raise the lowest path','Protect a habitat corridor','Phase work by storefront']},
    {name:'Library makerspace',brief:'The library can add tools, but quiet study, staff capacity, and youth access are in tension.',stakeholders:[['Students','Reliable quiet zone','access'],['Makers','Evening tool time','cost'],['Staff','Safe supervision','safety']],evidence:['Quiet seats fill by 5','Demand peaks after school','Training cuts incidents'],clauses:['Glass-enclose the shop','Book supervised sessions','Reserve youth hours']}
  ];
  function style(){if($('#common-ground-style'))return;const e=document.createElement('style');e.id='common-ground-style';e.textContent=`.common-ground{max-width:1050px;display:grid;gap:12px}.cg-hud{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}.cg-stat,.cg-card{border:1px solid var(--line);border-radius:16px;background:#fff}.cg-stat{padding:8px}.cg-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.cg-layout{display:grid;grid-template-columns:1.1fr .9fr;gap:12px}.cg-card{padding:14px}.cg-people,.cg-actions,.cg-clauses{display:grid;gap:8px}.cg-people{grid-template-columns:repeat(3,1fr)}.cg-person{padding:10px;border:1px solid #d7dce5;border-radius:13px;background:#f8fafc}.cg-person strong,.cg-person small{display:block}.cg-meter{height:9px;background:#e2e8f0;border-radius:999px;overflow:hidden}.cg-meter span{display:block;height:100%;background:linear-gradient(90deg,#ef4444,#f59e0b,#16a34a);transition:width .25s}.cg-actions{grid-template-columns:repeat(2,1fr)}.common-ground button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;color:inherit;font-weight:800;padding:9px;text-align:left}.common-ground button:hover{border-color:#64748b}.common-ground button[aria-pressed=true],.common-ground button.primary{background:#e0f2fe;border-color:#0284c7}.common-ground button:disabled{opacity:.45}.cg-note{min-height:92px}.cg-note strong,.cg-note small{display:block}.cg-tag{display:inline-block;margin:3px 4px 0 0;padding:3px 7px;border-radius:999px;background:#eef2ff;font-size:.72rem}.cg-round{padding-left:18px}.cg-commit{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;border:1px solid #dbe4ee;border-radius:12px;padding:9px}.cg-outcome{animation:cgPop .35s ease}@keyframes cgPop{50%{transform:scale(1.01)}}@media(max-width:800px){.cg-layout{grid-template-columns:1fr}.cg-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.cg-hud{grid-template-columns:repeat(2,1fr)}.cg-people,.cg-actions{grid-template-columns:1fr}.cg-commit{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){.common-ground *{animation:none!important;transition:none!important}}`;document.head.append(e)}
  function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-common-ground]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.commonGround='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Experiment · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
  function boot(){style();let n=0;const r=()=>{card();if(!$('[data-common-ground]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.cgBound)return;b.dataset.cgBound='1';b.addEventListener('click',()=>setTimeout(card))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Experiment · mediation strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel common-ground';root.innerHTML=`<div class="cg-hud">${['Round','Time','Trust','Tension','Insight'].map((x,i)=>`<div class="cg-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="cg-layout"><section class="cg-card"><p class="eyebrow">Case</p><h3 data-title></h3><p data-brief></p><div class="cg-people" data-people></div><h3>Choose your move</h3><div class="cg-actions" data-actions></div><p><small>Each move costs time. Listen before proposing. Keyboard users can tab through every action.</small></p></section><aside class="cg-card"><p class="eyebrow">Mediator board</p><div class="cg-meter" aria-label="Overall trust"><span data-meter></span></div><h3>What you know</h3><div data-insights></div><h3>Draft commitments</h3><div class="cg-clauses" data-clauses></div><h3>Session record</h3><div class="result-card cg-note" aria-live="polite"></div><div class="cg-actions"><button class="primary" data-a="advance">Advance round</button><button data-a="recover">Call a cooling break</button><button data-a="restart">New case</button></div></aside></div>`;stage.append(root);
    let st,scenario,ended=false;
    const log=(a,b)=>{const l=$('.cg-note',root);l.replaceChildren(Object.assign(document.createElement('strong'),{textContent:a}),Object.assign(document.createElement('small'),{textContent:b}))};
    function reset(){scenario=SCENARIOS[Math.floor(Math.random()*SCENARIOS.length)];st={round:1,time:8,trust:[44,44,44],tension:34,insight:0,heard:[false,false,false],evidence:[false,false,false],clauses:[false,false,false],cooling:true,objection:Math.floor(Math.random()*3),score:0};ended=false;log('The table is open.',scenario.brief);draw()}
    function overall(){return Math.round(st.trust.reduce((a,b)=>a+b,0)/3)}
    function spend(n){if(st.time<n){log('Not enough time.','Advance the round or choose a shorter intervention.');return false}st.time-=n;return true}
    function listen(i){if(ended||!spend(2))return;st.heard[i]=true;st.insight+=2;st.trust[i]=clamp(st.trust[i]+10,0,100);st.tension=clamp(st.tension-4,0,100);log(`${scenario.stakeholders[i][0]} felt heard.`,`Their core need is ${scenario.stakeholders[i][1].toLowerCase()}.`);draw()}
    function testEvidence(i){if(ended||!spend(1))return;st.evidence[i]=true;st.insight++;st.tension=clamp(st.tension-2,0,100);log('Evidence surfaced.',scenario.evidence[i]);draw()}
    function propose(i){if(ended||!spend(2))return;const informed=st.heard[i]&&st.evidence[i];st.clauses[i]=true;st.trust[i]=clamp(st.trust[i]+(informed?12:-4),0,100);st.tension=clamp(st.tension+(informed?-5:8),0,100);if(i===st.objection&&!st.heard[(i+1)%3]){st.tension=clamp(st.tension+9,0,100);log('A hidden objection surfaced.',`${scenario.stakeholders[(i+1)%3][0]} says the proposal ignores ${scenario.stakeholders[(i+1)%3][1].toLowerCase()}.`)}else log(informed?'Grounded clause drafted.':'Premature clause drafted.',scenario.clauses[i]);draw()}
    function advance(){if(ended)return;if(st.round>=4){finish();return}st.round++;st.time=8;st.objection=(st.objection+1)%3;const unheards=st.heard.filter(Boolean).length;if(unheards<2){st.tension=clamp(st.tension+10,0,100);st.trust=st.trust.map(v=>clamp(v-5,0,100));log('The table carried unresolved needs forward.','Listening to at least two parties before each transition reduces escalation.')}else{st.tension=clamp(st.tension-3,0,100);log(`Round ${st.round} begins.`,'The parties are ready to test the draft against the remaining concern.')}if(st.tension>=90||overall()<=12){ended=true;log('Talks collapsed.','Restart the case and sequence listening, evidence, and clauses more carefully.')}draw()}
    function recover(){if(ended||!st.cooling)return log('Cooling break unavailable.','It can be used once during an active session.');st.cooling=false;st.tension=clamp(st.tension-22,0,100);st.trust=st.trust.map(v=>clamp(v+4,0,100));st.time=Math.max(0,st.time-2);log('Cooling break called.','Tension fell, but two units of round time were lost.');draw()}
    function finish(){ended=true;const clauses=st.clauses.filter(Boolean).length,heard=st.heard.filter(Boolean).length,evidence=st.evidence.filter(Boolean).length;st.score=overall()*5+clauses*120+heard*60+evidence*40-st.tension*3+(st.cooling?75:0);const durable=clauses===3&&overall()>=58&&st.tension<=55;root.classList.add('cg-outcome');log(durable?'Durable agreement reached.':'A fragile agreement emerged.',`Trust ${overall()}, tension ${st.tension}, ${clauses}/3 clauses, score ${st.score}. ${durable?'The commitments survived every party’s core need.':'Replay and uncover more needs before drafting.'}`);draw()}
    function draw(){const vals=[`${st.round}/4`,st.time,overall(),st.tension,st.insight];$$('[data-h]',root).forEach((e,i)=>e.textContent=vals[i]);$('[data-title]',root).textContent=scenario.name;$('[data-brief]',root).textContent=scenario.brief;$('[data-meter]',root).style.width=`${overall()}%`;$('[data-people]',root).innerHTML=scenario.stakeholders.map((p,i)=>`<article class="cg-person"><strong>${p[0]}</strong><small>${st.heard[i]?p[1]:'Core need hidden'}</small><span class="cg-tag">Trust ${st.trust[i]}</span><span class="cg-tag">${p[2]}</span></article>`).join('');$('[data-insights]',root).innerHTML=scenario.evidence.map((x,i)=>`<span class="cg-tag">${st.evidence[i]?x:'Evidence hidden'}</span>`).join('');$('[data-actions]',root).innerHTML=scenario.stakeholders.map((p,i)=>`<button data-listen="${i}" ${ended?'disabled':''}>Listen to ${p[0]}<br><small>2 time · reveal need</small></button><button data-evidence="${i}" ${ended?'disabled':''}>Test evidence ${i+1}<br><small>1 time · reduce uncertainty</small></button><button data-propose="${i}" ${ended?'disabled':''}>Draft clause ${i+1}<br><small>2 time · risk objection</small></button>`).join('');$('[data-clauses]',root).innerHTML=scenario.clauses.map((x,i)=>`<div class="cg-commit"><span>${st.clauses[i]?x:`Clause ${i+1} not drafted`}</span><strong>${st.clauses[i]?'✓':'—'}</strong></div>`).join('');$$('[data-listen]',root).forEach(b=>b.addEventListener('click',()=>listen(+b.dataset.listen)));$$('[data-evidence]',root).forEach(b=>b.addEventListener('click',()=>testEvidence(+b.dataset.evidence)));$$('[data-propose]',root).forEach(b=>b.addEventListener('click',()=>propose(+b.dataset.propose)));$('[data-a="advance"]',root).disabled=ended;$('[data-a="recover"]',root).disabled=ended||!st.cooling}
    root.addEventListener('click',e=>{const a=e.target.closest('[data-a]')?.dataset.a;if(a==='advance')advance();if(a==='recover')recover();if(a==='restart')reset()});dialog.addEventListener('close',()=>root.replaceChildren(),{once:true});reset()
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
