(() => {
  'use strict';
  const APP={name:'Compost Cascade',emoji:'♻️',category:'play',version:'1.0.0',summary:'Balance a neighborhood compost loop across sorting, heat, moisture, contamination, demand, and recovery.',description:'A local-only circular-systems strategy game. Route daily material into three bays, tune moisture and aeration, fulfill changing soil orders, manage contamination and odor, unlock upgrades, survive shocks, and recover a failing pile across six adaptive days.'};
  const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)]; const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  function style(){if($('#compost-cascade-style'))return;const e=document.createElement('style');e.id='compost-cascade-style';e.textContent=`.compost{max-width:1000px;display:grid;gap:12px}.compost-hud{display:grid;grid-template-columns:repeat(7,1fr);gap:7px}.compost-stat,.compost-card{border:1px solid var(--line);border-radius:16px;background:#fff}.compost-stat{padding:8px}.compost-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.compost-layout{display:grid;grid-template-columns:1.2fr .8fr;gap:12px}.compost-card{padding:14px}.compost-loads,.compost-bays,.compost-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.compost button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;color:inherit;font-weight:800}.compost button:focus-visible{outline:3px solid #15803d;outline-offset:2px}.compost button[aria-pressed=true]{background:#dcfce7;border-color:#15803d}.compost-bay{padding:10px;text-align:left}.compost-bay strong,.compost-bay small{display:block}.compost-meter{height:10px;border-radius:999px;background:#e2e8f0;overflow:hidden;margin:5px 0}.compost-meter span{display:block;height:100%;background:linear-gradient(90deg,#a16207,#22c55e);transition:width .25s}.compost-log{min-height:84px}.compost-upgrades{display:flex;flex-wrap:wrap;gap:6px}.compost-chip{padding:5px 8px;border-radius:999px;background:#ecfccb;font-size:.77rem;font-weight:800}.compost-warning{background:#fff7ed;border-color:#f97316}@media(max-width:820px){.compost-layout{grid-template-columns:1fr}.compost-hud{grid-template-columns:repeat(4,1fr)}}@media(max-width:560px){.compost-hud{grid-template-columns:repeat(2,1fr)}.compost-loads,.compost-bays,.compost-actions{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){.compost *{animation:none!important;transition:none!important;scroll-behavior:auto!important}}`;document.head.append(e)}
  function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-compost-cascade]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.compostCascade='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
  function boot(){style();let n=0;const r=()=>{card();if(!$('[data-compost-cascade]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.compostBound)return;b.dataset.compostBound='1';b.addEventListener('click',()=>setTimeout(card))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · circular systems strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel compost';root.innerHTML=`<div class="compost-hud">${['Day','Coins','Soil','Odor','Contam.','Demand','Score'].map((x,i)=>`<div class="compost-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="compost-layout"><section class="compost-card"><p class="eyebrow">Daily material</p><div class="compost-loads" data-loads></div><h3>Processing bays</h3><div class="compost-bays" data-bays></div><div class="compost-actions"><button data-a="water">Add water</button><button data-a="turn">Turn pile</button><button data-a="screen">Screen soil</button></div></section><aside class="compost-card"><h3>Neighborhood order</h3><p data-order></p><div class="compost-log result-card" aria-live="polite"></div><h3>Upgrades</h3><div class="compost-upgrades" data-upgrades></div><button data-a="advance">Advance day</button><button data-a="recover">Emergency carbon cover</button><button data-a="restart">Restart season</button><p><small>Keyboard: 1–3 select a load, Q/W/E select a bay, Enter routes it, A adds water, T turns, S screens, N advances. Session only; no data is stored or sent.</small></p></aside></div>`;stage.append(root);
    const loadTypes=[['Greens',3,2],['Browns',1,0],['Food scraps',4,3],['Leaves',2,0],['Coffee',3,1],['Wood chips',1,0]];
    const orders=[['Community garden',6],['School planters',8],['Stormwater beds',10],['Tree nursery',12]];
    const shocks=['Heat wave dries every bay.','Rain burst soaks the fullest bay.','Festival adds one contamination.','Volunteer day adds two free turns.'];
    let st,selLoad=0,selBay=0;
    const announce=(a,b)=>{const l=$('.compost-log',root);l.replaceChildren(Object.assign(document.createElement('strong'),{textContent:a}),Object.assign(document.createElement('small'),{textContent:b}))};
    function reset(){st={day:1,coins:6,soil:0,odor:0,contam:0,score:0,recovery:1,freeTurns:0,upgrades:[],loads:[],bays:Array.from({length:3},(_,i)=>({name:['Hot bay','Cure bay','Reserve bay'][i],mass:0,moist:50,air:50,quality:0}))};makeLoads();announce('Season ready.','Route each load, then tune the bays before advancing.');draw()}
    function makeLoads(){st.loads=Array.from({length:3},()=>{const x=loadTypes[Math.floor(Math.random()*loadTypes.length)];return {name:x[0],nitrogen:x[1],risk:x[2],used:false}})}
    function demand(){return orders[Math.min(orders.length-1,Math.floor((st.day-1)/2))]}
    function route(){const l=st.loads[selLoad],b=st.bays[selBay];if(!l||l.used)return announce('Load unavailable.','Choose an unused daily material.');l.used=true;b.mass+=2+l.nitrogen;b.quality+=l.nitrogen+(st.upgrades.includes('Sorting table')?1:0);b.moist=clamp(b.moist+l.nitrogen*3,0,100);st.contam+=Math.max(0,l.risk-(st.upgrades.includes('Sorting table')?1:0));announce(`${l.name} routed.`,`${b.name} gained mass and nutrients.`);draw()}
    function act(a){const b=st.bays[selBay];if(a==='water'){if(st.coins<1)return announce('No coins.','Advance or screen soil to earn more.');st.coins--;b.moist=clamp(b.moist+18,0,100);announce('Moisture raised.',`${b.name} is now ${b.moist}% moist.`)}else if(a==='turn'){if(st.freeTurns>0)st.freeTurns--;else if(st.coins<1)return announce('No turn available.','Use recovery or advance carefully.');else st.coins--;b.air=clamp(b.air+22,0,100);b.quality+=2;announce('Pile turned.',`${b.name} gained air and quality.`)}else if(a==='screen'){if(b.mass<6||b.quality<6)return announce('Not ready.','Build at least 6 mass and 6 quality.');const yieldAmt=Math.floor(Math.min(b.mass,b.quality)/3);b.mass-=yieldAmt*2;b.quality=Math.max(0,b.quality-yieldAmt);st.soil+=yieldAmt;st.coins+=yieldAmt;st.score+=yieldAmt*8;announce('Soil screened.',`Produced ${yieldAmt} soil and earned ${yieldAmt} coins.`)}else if(a==='recover'){if(!st.recovery)return announce('Recovery already used.','Reduce odor through better balance.');st.recovery=0;st.odor=Math.max(0,st.odor-4);st.contam=Math.max(0,st.contam-2);st.bays.forEach(x=>{x.air=clamp(x.air+15,0,100);x.moist=clamp(x.moist-10,0,100)});announce('Carbon cover deployed.','Odor and contamination fell; all bays stabilized.')}else if(a==='advance')advance();else if(a==='restart')reset();draw()}
    function advance(){if(st.loads.some(x=>!x.used))return announce('Material remains.','Route all three loads before ending the day.');st.bays.forEach(b=>{const balance=100-Math.abs(55-b.moist)-Math.abs(60-b.air);b.quality+=Math.max(0,Math.floor(balance/28));st.odor+=b.moist>78||b.air<25?2:0;b.moist=clamp(b.moist-8,0,100);b.air=clamp(b.air-10,0,100)});const [name,need]=demand();if(st.soil>=need){st.soil-=need;st.coins+=5;st.score+=25;announce('Order fulfilled.',`${name} received ${need} soil.`)}else announce('Order missed.',`${name} needed ${need}; available soil was ${st.soil}.`);if(st.day===2&&!st.upgrades.includes('Sorting table'))st.upgrades.push('Sorting table');if(st.day===4&&!st.upgrades.includes('Aeration pipes')){st.upgrades.push('Aeration pipes');st.bays.forEach(b=>b.air+=15)};const shock=shocks[Math.floor(Math.random()*shocks.length)];if(shock.startsWith('Heat'))st.bays.forEach(b=>b.moist-=15);if(shock.startsWith('Rain'))st.bays.sort((a,b)=>b.mass-a.mass)[0].moist+=25;if(shock.startsWith('Festival'))st.contam++;if(shock.startsWith('Volunteer'))st.freeTurns+=2;st.day++;if(st.odor>=8||st.contam>=7)return finish(false,'The neighborhood paused collection after odor or contamination crossed the safety limit.');if(st.day>6)return finish(true,`Season complete with ${st.score} points, ${st.soil} soil, and ${st.coins} coins.`);makeLoads();announce('New day.',shock)}
    function finish(win,text){announce(win?'Circular season certified.':'Collection suspended.',text);$('[data-a="advance"]',root).disabled=true;st.score+=win?60:0}
    function draw(){$$('[data-h]',root).forEach((e,i)=>e.textContent=[st.day,st.coins,st.soil,st.odor,st.contam,demand()[1],st.score][i]);$('[data-order]',root).textContent=`${demand()[0]} requests ${demand()[1]} screened soil.`;$('[data-loads]',root).innerHTML=st.loads.map((l,i)=>`<button data-load="${i}" aria-pressed="${i===selLoad}" ${l.used?'disabled':''}><strong>${i+1}. ${l.name}</strong><small>Nutrient ${l.nitrogen} · risk ${l.risk}</small></button>`).join('');$('[data-bays]',root).innerHTML=st.bays.map((b,i)=>`<button class="compost-bay" data-bay="${i}" aria-pressed="${i===selBay}"><strong>${['Q','W','E'][i]}. ${b.name}</strong><small>Mass ${b.mass} · quality ${b.quality}</small><small>Moisture ${b.moist}%</small><div class="compost-meter"><span style="width:${clamp(b.moist,0,100)}%"></span></div><small>Air ${b.air}%</small><div class="compost-meter"><span style="width:${clamp(b.air,0,100)}%"></span></div></button>`).join('');$('[data-upgrades]',root).innerHTML=(st.upgrades.length?st.upgrades:['No upgrades yet']).map(x=>`<span class="compost-chip">${x}</span>`).join('');root.classList.toggle('compost-warning',st.odor>=5||st.contam>=4)}
    root.addEventListener('click',e=>{const l=e.target.closest('[data-load]'),b=e.target.closest('[data-bay]'),a=e.target.closest('[data-a]');if(l){selLoad=+l.dataset.load;draw()}else if(b){selBay=+b.dataset.bay;draw()}else if(a)act(a.dataset.a)});root.addEventListener('dblclick',e=>{if(e.target.closest('[data-bay]'))route()});const key=e=>{if(!dialog.open)return;if(/[123]/.test(e.key)){selLoad=+e.key-1;draw()}else if(['q','w','e'].includes(e.key.toLowerCase())){selBay=['q','w','e'].indexOf(e.key.toLowerCase());draw()}else if(e.key==='Enter')route();else if(e.key.toLowerCase()==='a')act('water');else if(e.key.toLowerCase()==='t')act('turn');else if(e.key.toLowerCase()==='s')act('screen');else if(e.key.toLowerCase()==='n')act('advance')};document.addEventListener('keydown',key);dialog.addEventListener('close',()=>document.removeEventListener('keydown',key),{once:true});reset()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();