(() => {
'use strict';
const APP={name:"Conservator's Bench",emoji:'🖼️',category:'play',version:'1.0.0',summary:'Diagnose fragile artifacts, plan reversible treatments, and balance stability with authenticity.',description:'A local-only conservation strategy game with six escalating artifacts, material diagnosis, treatment sequencing, limited time and budget, authenticity and stability tradeoffs, delayed aging tests, progression, a session unlock, meaningful failure, recovery, keyboard, touch, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const CASES=[
 {title:'Watercolor map',material:'paper',damage:['foxing','cockling'],target:68,budget:8,turns:6},
 {title:'Gilded frame',material:'wood',damage:['flaking','grime'],target:72,budget:9,turns:7},
 {title:'Ceramic vessel',material:'ceramic',damage:['cracks','old adhesive'],target:76,budget:10,turns:7},
 {title:'Silk banner',material:'textile',damage:['fading','tears'],target:80,budget:11,turns:8},
 {title:'Bronze instrument',material:'metal',damage:['chlorides','corrosion'],target:84,budget:12,turns:8},
 {title:'Mixed-media icon',material:'mixed',damage:['lifting paint','warped support'],target:88,budget:13,turns:9}
];
const TOOLS=[
 {id:'inspect',label:'Raking-light inspection',cost:1,time:1,stability:2,auth:1,risk:-8,tags:['all']},
 {id:'sample',label:'Micro-sample analysis',cost:2,time:1,stability:3,auth:-1,risk:-12,tags:['paper','wood','ceramic','textile','metal','mixed']},
 {id:'clean',label:'Controlled cleaning',cost:2,time:1,stability:8,auth:3,risk:8,tags:['paper','wood','ceramic','metal','mixed']},
 {id:'humidify',label:'Humidity chamber',cost:2,time:2,stability:12,auth:1,risk:10,tags:['paper','textile','mixed']},
 {id:'consolidate',label:'Reversible consolidation',cost:3,time:2,stability:15,auth:-2,risk:7,tags:['wood','textile','mixed']},
 {id:'join',label:'Reversible join',cost:3,time:2,stability:17,auth:-3,risk:6,tags:['ceramic','wood','metal']},
 {id:'inpaint',label:'Visible-loss inpainting',cost:2,time:2,stability:3,auth:12,risk:5,tags:['paper','wood','ceramic','mixed']},
 {id:'coat',label:'Protective barrier coat',cost:3,time:1,stability:14,auth:-5,risk:11,tags:['metal','wood','mixed']},
 {id:'mount',label:'Supportive mount',cost:2,time:1,stability:11,auth:0,risk:3,tags:['paper','textile','ceramic','mixed']},
 {id:'microclimate',label:'Microclimate enclosure',cost:4,time:2,stability:20,auth:0,risk:-4,tags:['all'],unlock:true}
];
function style(){if($('#conservators-bench-style'))return;const e=document.createElement('style');e.id='conservators-bench-style';e.textContent=`
.conserve{max-width:1100px;display:grid;gap:12px}.cb-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.cb-stat,.cb-panel{border:1px solid var(--line);border-radius:17px;background:#fff}.cb-stat{padding:9px}.cb-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.cb-layout{display:grid;grid-template-columns:1.1fr .9fr;gap:12px}.cb-panel{padding:15px}.cb-object{min-height:210px;border-radius:18px;border:1px solid #c6b89f;background:linear-gradient(145deg,#f6efe3,#e8dcc8);display:grid;place-items:center;position:relative;overflow:hidden}.cb-object::before{content:'';width:48%;aspect-ratio:1;border-radius:28% 42% 34% 46%;background:linear-gradient(140deg,#c9a86b,#8f6d42);box-shadow:0 18px 35px #5c4a2b33;transform:rotate(-5deg)}.cb-object[data-risk='high']::after{content:'⚠';position:absolute;right:14px;top:10px;font-size:1.5rem}.cb-damage{display:flex;gap:6px;flex-wrap:wrap}.cb-tag,.cb-step{padding:5px 8px;border-radius:999px;background:#f0ece5;font-size:.72rem}.cb-tools{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.cb-tool{min-height:72px;border:1px solid var(--line);border-radius:12px;background:#fff;padding:10px;text-align:left;font-weight:800}.cb-tool small{display:block;color:var(--muted);font-weight:600}.cb-tool:focus-visible,.cb-actions button:focus-visible{outline:3px solid #8d5d35;outline-offset:2px}.cb-tool[aria-pressed=true]{background:#fff3e6;box-shadow:inset 0 0 0 2px #8d5d35}.cb-sequence{display:flex;gap:6px;flex-wrap:wrap;min-height:42px}.cb-meter{height:11px;background:#e8ebf1;border-radius:99px;overflow:hidden}.cb-meter span{display:block;height:100%;background:#8d5d35;transition:width .25s}.cb-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.cb-actions button{min-height:46px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800}.cb-actions .primary{background:#fff0df;border-color:#8d5d35}.cb-log{min-height:105px}.cb-hint{font-size:.82rem;color:var(--muted)}
@media(max-width:820px){.cb-layout{grid-template-columns:1fr}.cb-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:540px){.cb-hud{grid-template-columns:repeat(2,1fr)}.cb-tools,.cb-actions{grid-template-columns:1fr}.cb-object{min-height:150px}}@media(prefers-reduced-motion:reduce){.conserve *{animation:none!important;transition:none!important}}
`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-conservators-bench]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true),a=$('.app-card',f);a.dataset.conservatorsBench='1';a.dataset.category=APP.category;$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-conservators-bench]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.cbBound)return;b.dataset.cbBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · conservation strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
 const root=document.createElement('section');root.className='tool-panel conserve';root.innerHTML=`<div class="cb-hud">${['Artifact','Turns','Budget','Stability','Authenticity','Score'].map((x,i)=>`<div class="cb-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="cb-layout"><section class="cb-panel"><div class="cb-object" data-object role="img" aria-label="Artifact under examination"></div><h3 data-title></h3><div class="cb-damage" data-damage></div><p class="cb-hint">Build a treatment sequence, then run an aging test. Keyboard: 1-0 select tools, A apply, Z undo, Enter test.</p><div class="cb-tools" data-tools></div></section><aside class="cb-panel"><div class="result-card cb-log" aria-live="polite"></div><p><strong>Treatment sequence</strong></p><div class="cb-sequence" data-seq></div><p><strong>Failure risk</strong></p><div class="cb-meter"><span data-meter></span></div><div class="cb-actions"><button class="primary" data-a="apply">Apply selected</button><button data-a="undo">Undo last</button><button data-a="test">Run aging test</button><button data-a="recover">Senior conservator</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
 let st,ended=false,keyHandler;
 function current(){return CASES[st.case]}
 function reset(){st={case:0,turn:0,budget:CASES[0].budget,stability:34,auth:78,risk:26,score:0,selected:0,seq:[],unlock:false,recovery:true,tests:0};ended=false;log('Bench opened.','Inspect before making irreversible choices.');draw()}
 function startCase(){const c=current();st.turn=0;st.budget=c.budget;st.stability=34+st.case*2;st.auth=80;st.risk=24+st.case*5;st.selected=0;st.seq=[];st.tests=0;log(c.title,'Condition report ready.');draw()}
 function compatible(tool){return tool.tags.includes('all')||tool.tags.includes(current().material)}
 function apply(){if(ended)return;const t=TOOLS[st.selected];if(t.unlock&&!st.unlock)return log('Tool locked.','Earn 950 points to unlock the microclimate enclosure.');if(st.turn>=current().turns)return log('No bench time.','Run the aging test or use recovery.');if(st.budget<t.cost)return log('Budget exhausted.','Choose a lower-cost treatment or test now.');st.turn+=t.time;st.budget-=t.cost;let fit=compatible(t);st.stability=clamp(st.stability+t.stability*(fit?1:.35),0,100);st.auth=clamp(st.auth+t.auth-(fit?0:6),0,100);st.risk=clamp(st.risk+t.risk+(fit?0:18),0,100);if(t.id==='inspect'||t.id==='sample')st.risk=clamp(st.risk-8,0,100);if(st.seq.some(x=>x.id==='clean')&&t.id==='sample')st.auth=clamp(st.auth-7,0,100);st.seq.push(t);st.score+=fit?25:5;if(st.score>=950)st.unlock=true;log(fit?'Treatment recorded.':'Compatibility warning.',fit?`${t.label} changed the condition profile.`:`${t.label} is poorly matched to ${current().material}.`);if(st.risk>=95)return finish(false,'The artifact suffered a catastrophic treatment failure.');draw()}
 function undo(){if(ended||!st.seq.length)return log('Nothing to reverse.','The treatment history is empty.');const t=st.seq.pop();st.turn=Math.max(0,st.turn-t.time);st.budget+=Math.max(0,t.cost-1);st.stability=clamp(st.stability-t.stability*.65,0,100);st.auth=clamp(st.auth-t.auth-2,0,100);st.risk=clamp(st.risk-t.risk+4,0,100);log('Treatment reversed.',`${t.label} was removed, but one budget unit and some authenticity were lost.`);draw()}
 function test(){if(ended)return;st.tests++;const sequenceBonus=(st.seq[0]?.id==='inspect'||st.seq[0]?.id==='sample')?9:-8;const reversible=st.seq.filter(x=>['consolidate','join','mount','microclimate'].includes(x.id)).length*3;const overwork=Math.max(0,st.seq.length-5)*6;const result=st.stability+st.auth*.35-sequenceBonus/2+sequenceBonus+reversible-st.risk*.55-overwork;st.risk=clamp(st.risk+(Math.random()*12-4),0,100);if(result>=current().target&&st.auth>=48&&st.risk<78){st.score+=Math.round(result*7);if(st.case===CASES.length-1)return finish(true,`Collection stabilized. Final score ${st.score}.`);st.case++;startCase()}else{st.auth=clamp(st.auth-8,0,100);st.risk=clamp(st.risk+10,0,100);log('Aging test failed.',`Needed ${current().target}; achieved ${Math.round(result)}. Revise the sequence.`);if(st.tests>=2&&st.risk>88)return finish(false,'Repeated aging failures forced the object off exhibition.');draw()}}
 function recover(){if(ended||!st.recovery)return log('Recovery unavailable.','The senior conservator can intervene once per session.');st.recovery=false;st.score=Math.max(0,st.score-220);st.auth=clamp(st.auth-10,0,100);st.risk=Math.min(st.risk,44);st.budget=Math.max(st.budget,4);st.turn=Math.max(0,st.turn-2);st.seq=st.seq.slice(0,2);log('Senior conservator intervenes.','Risk and bench time recover, but score and authenticity fall.');draw()}
 function finish(win,msg){ended=true;log(win?'Conservation program complete.':'Program halted.',msg);draw()}
 function log(a,b){$('.cb-log',root).innerHTML=`<strong>${a}</strong><p>${b}</p>`}
 function draw(){const c=current();$$('[data-h]',root).forEach((e,i)=>e.textContent=[`${st.case+1}/6`,`${st.turn}/${c.turns}`,st.budget,Math.round(st.stability),Math.round(st.auth),st.score][i]);$('[data-title]',root).textContent=`${c.title} · ${c.material}`;$('[data-damage]',root).innerHTML=c.damage.map(x=>`<span class="cb-tag">${x}</span>`).join('');$('[data-object]',root).dataset.risk=st.risk>70?'high':'normal';$('[data-object]',root).setAttribute('aria-label',`${c.title}, ${c.material}, damage: ${c.damage.join(', ')}, risk ${Math.round(st.risk)} percent`);$('[data-tools]',root).innerHTML=TOOLS.map((t,i)=>`<button class="cb-tool" type="button" data-tool="${i}" aria-pressed="${st.selected===i}" ${t.unlock&&!st.unlock?'disabled':''}>${t.label}<small>${t.cost} budget · ${t.time} turn${t.time>1?'s':''}${t.unlock&&!st.unlock?' · unlock at 950':''}</small></button>`).join('');$$('[data-tool]',root).forEach(b=>b.addEventListener('click',()=>{st.selected=+b.dataset.tool;draw()}));$('[data-seq]',root).innerHTML=st.seq.length?st.seq.map((t,i)=>`<span class="cb-step">${i+1}. ${t.label}</span>`).join(''):'<span class="cb-step">No treatments yet</span>';$('[data-meter]',root).style.width=`${st.risk}%`;$$('[data-a]',root).forEach(b=>b.disabled=ended&&b.dataset.a!=='restart')}
 root.addEventListener('click',e=>{const a=e.target.closest('[data-a]')?.dataset.a;if(a==='apply')apply();if(a==='undo')undo();if(a==='test')test();if(a==='recover')recover();if(a==='restart')reset()});
 keyHandler=e=>{if(!dialog.open)return;if(/^[1-9]$/.test(e.key)){st.selected=+e.key-1;draw()}if(e.key==='0'){st.selected=9;draw()}if(e.key.toLowerCase()==='a')apply();if(e.key.toLowerCase()==='z')undo();if(e.key==='Enter')test()};document.addEventListener('keydown',keyHandler);
 const close=()=>{document.removeEventListener('keydown',keyHandler);dialog.removeEventListener('close',close)};dialog.addEventListener('close',close);reset()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();