(() => {
  const APP={name:'Council Commons',emoji:'🏛️',category:'play',version:'1.0.0',summary:'Build a coalition without breaking the city you serve.',description:'A local civic-negotiation strategy game with four stakeholder blocs, branching policy packages, limited influence, budget and legitimacy tradeoffs, amendment chains, random shocks, coalition thresholds, recoverable deadlock, scoring, session-only mediator and crisis-mode unlocks, pointer, touch and keyboard controls, reduced-motion behavior, optional local audio, and teardown.'};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const blocs=[
    {id:'residents',name:'Residents',icon:'🏘️',color:'#0f766e'},{id:'workers',name:'Workers',icon:'🧰',color:'#b45309'},{id:'business',name:'Business',icon:'🏪',color:'#7c3aed'},{id:'climate',name:'Climate council',icon:'🌿',color:'#15803d'}
  ];
  const proposals=[
    {name:'Cool roofs and shade',cost:5,effects:{residents:2,workers:1,business:0,climate:3},legit:1,tag:'Heat'},
    {name:'Night bus expansion',cost:4,effects:{residents:2,workers:3,business:1,climate:1},legit:1,tag:'Transit'},
    {name:'Main street grants',cost:5,effects:{residents:0,workers:1,business:3,climate:-1},legit:0,tag:'Commerce'},
    {name:'Floodable park network',cost:6,effects:{residents:1,workers:1,business:-1,climate:3},legit:2,tag:'Resilience'},
    {name:'Apprenticeship guarantee',cost:4,effects:{residents:1,workers:3,business:1,climate:0},legit:1,tag:'Jobs'},
    {name:'Delivery curb reform',cost:3,effects:{residents:0,workers:1,business:3,climate:1},legit:0,tag:'Streets'},
    {name:'Tenant repair fund',cost:5,effects:{residents:3,workers:2,business:-1,climate:1},legit:2,tag:'Housing'},
    {name:'Building retrofit code',cost:3,effects:{residents:-1,workers:2,business:-2,climate:3},legit:0,tag:'Energy'}
  ];
  const shocks=[
    {title:'Flash flood warning',text:'The river is rising. Climate and residents demand visible action.',delta:{residents:-1,workers:0,business:-1,climate:-2},budget:-1},
    {title:'Factory closure rumor',text:'Workers want job security while businesses fear new costs.',delta:{residents:0,workers:-2,business:-1,climate:0},budget:0},
    {title:'Festival weekend',text:'A busy weekend creates revenue and transit pressure.',delta:{residents:-1,workers:-1,business:2,climate:-1},budget:2},
    {title:'Youth delegation',text:'Students ask for a durable climate commitment.',delta:{residents:1,workers:0,business:0,climate:2},budget:0}
  ];
  function css(){if($('#cc-styles'))return;const s=document.createElement('style');s.id='cc-styles';s.textContent=`.cc-card{animation:cc-in .24s ease both}.cc-game{max-width:1180px;gap:14px}.cc-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.cc-stat,.cc-chamber,.cc-panel,.cc-log{border:1px solid var(--line);border-radius:18px;background:#fff}.cc-stat{padding:9px 11px}.cc-stat span{display:block;color:var(--muted);font-size:.6rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.cc-stat strong{display:block;margin-top:3px}.cc-layout{display:grid;grid-template-columns:1.1fr .9fr;gap:12px}.cc-chamber{padding:14px;background:linear-gradient(150deg,#172554,#312e81);color:#fff}.cc-ring{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.cc-bloc{border:1px solid rgba(255,255,255,.28);border-radius:16px;padding:12px;background:rgba(255,255,255,.08)}.cc-bloc header{display:flex;justify-content:space-between;gap:8px;font-weight:900}.cc-meter{height:12px;border-radius:99px;background:rgba(255,255,255,.15);overflow:hidden;margin-top:9px}.cc-meter i{display:block;height:100%;background:#fde047;transition:width .28s ease}.cc-agenda{margin-top:12px;border:1px dashed rgba(255,255,255,.35);border-radius:14px;padding:12px;min-height:90px}.cc-panel{padding:14px;display:grid;gap:10px;align-content:start}.cc-modes,.cc-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.cc-panel button{min-height:44px;border:1px solid var(--line);border-radius:14px;background:#fff;font-weight:900}.cc-panel button.is-active{box-shadow:0 0 0 3px #4338ca inset;background:#eef2ff}.cc-panel button[disabled]{opacity:.45}.cc-proposals{display:grid;gap:8px;max-height:310px;overflow:auto}.cc-proposal{text-align:left;padding:10px!important}.cc-proposal small,.cc-log small{display:block;margin-top:4px;color:var(--muted)}.cc-proposal.is-picked{background:#eef2ff;border-color:#6366f1}.cc-log{padding:14px;min-height:90px}.cc-help{font-size:.75rem;color:var(--muted)}.cc-vote{font-size:.78rem;color:#c7d2fe;margin-top:8px}@media(max-width:900px){.cc-layout{grid-template-columns:1fr}.cc-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:620px){.cc-hud,.cc-ring,.cc-modes,.cc-actions{grid-template-columns:1fr 1fr}.cc-panel button{min-height:48px}}@media(prefers-reduced-motion:reduce){.cc-card{animation:none!important}.cc-meter i{transition:none}}@keyframes cc-in{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}`;document.head.append(s)}
  function addCard(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-cc-card]'))return;const f=$('.filter.is-active')?.dataset.filter||'all';if(f!=='all'&&f!==APP.category)return;css();const n=t.content.cloneNode(true),c=$('.app-card',n);c.dataset.category=APP.category;c.dataset.ccCard='true';c.classList.add('cc-card');$('.app-icon',n).textContent=APP.emoji;$('.app-meta',n).textContent=`Play · v${APP.version}`;$('.app-name',n).textContent=APP.name;$('.app-summary',n).textContent=APP.summary;const b=$('.app-card-button',n);b.setAttribute('aria-label',`Open ${APP.name}`);b.onclick=open;g.append(n)}
  function boot(){css();let tries=0;const r=()=>{addCard();if(!$('[data-cc-card]')&&tries++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.ccRefresh)return;b.dataset.ccRefresh='1';b.addEventListener('click',()=>setTimeout(addCard,0))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');if(!d||!s)return;$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent=`Play · ${APP.emoji}`;$('#dialog-description').textContent=APP.description;$('#dialog-feedback').href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Council%20Commons';s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){
    const root=document.createElement('section');root.className='tool-panel cc-game';root.innerHTML=`<div class="cc-hud"><div class="cc-stat"><span>Round</span><strong id="cc-round">1 / 8</strong></div><div class="cc-stat"><span>Budget</span><strong id="cc-budget">18</strong></div><div class="cc-stat"><span>Influence</span><strong id="cc-influence">8</strong></div><div class="cc-stat"><span>Legitimacy</span><strong id="cc-legit">70</strong></div><div class="cc-stat"><span>Coalition</span><strong id="cc-coalition">0 / 4</strong></div><div class="cc-stat"><span>Score</span><strong id="cc-score">0</strong></div></div><div class="cc-layout"><div class="cc-chamber"><div class="cc-ring" aria-label="Stakeholder support"></div><div class="cc-agenda" aria-live="polite"></div><div class="cc-vote">A proposal passes with support of 60 or more from at least three blocs. No bloc may fall below 20.</div></div><div class="cc-panel"><div class="cc-modes" aria-label="Difficulty modes"></div><div class="cc-proposals" aria-label="Policy proposals"></div><div class="cc-actions"><button data-act="amend">Balanced amendment · 2</button><button data-act="lobby">Targeted meeting · 2</button><button data-act="vote">Call the vote</button><button data-act="recover">Listening session</button><button data-act="sound" aria-pressed="false">Sound off</button><button data-act="restart">Restart</button></div><div class="cc-help">Keyboard: 1–8 selects a proposal, A amends, L holds a meeting, Enter votes. Session progress unlocks a mediator and Crisis mode.</div><div class="cc-log result-card" aria-live="polite"><strong>Chamber opened.</strong><small>Build a package that can survive competing needs.</small></div></div></div>`;stage.append(root);
    const modes={guided:{name:'Guided',budget:22,influence:11,rounds:7},standard:{name:'Standard',budget:18,influence:8,rounds:8},crisis:{name:'Crisis',budget:15,influence:6,rounds:9,locked:true}};
    const state={mode:'standard',round:1,budget:18,influence:8,legit:70,score:0,support:{},picked:null,amended:false,mediator:false,unlocked:false,passed:0,sound:false,ac:null,ended:false};
    const note=(a,b)=>$('.cc-log',root).innerHTML=`<strong>${a}</strong><small>${b}</small>`;
    const tone=(f=440,d=.08)=>{if(!state.sound)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;state.ac||=new AC();state.ac.resume();const o=state.ac.createOscillator(),g=state.ac.createGain();o.frequency.value=f;g.gain.setValueAtTime(.0001,state.ac.currentTime);g.gain.exponentialRampToValueAtTime(.04,state.ac.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,state.ac.currentTime+d);o.connect(g).connect(state.ac.destination);o.start();o.stop(state.ac.currentTime+d+.02)};
    function reset(){const m=modes[state.mode];state.round=1;state.budget=m.budget;state.influence=m.influence;state.legit=70;state.score=0;state.support={residents:50,workers:50,business:50,climate:50};state.picked=null;state.amended=false;state.passed=0;state.ended=false;render();note('New council term.',`${m.name} mode. Pass three durable policies before the term ends.`)}
    function choose(i){if(state.ended)return;state.picked=proposals[i];state.amended=false;render();note(state.picked.name,`Costs ${state.picked.cost}. Review the support forecast, then amend, lobby, or vote.`)}
    function amend(){if(!state.picked||state.influence<2||state.ended)return;state.influence-=2;state.amended=true;blocs.forEach(b=>{if(state.picked.effects[b.id]<0)state.picked={...state.picked,effects:{...state.picked.effects,[b.id]:state.picked.effects[b.id]+1}}});state.legit=Math.min(100,state.legit+2);render();note('Package amended.','The sharpest opposition softened, but influence was spent.');tone(560)}
    function lobby(){if(!state.picked||state.influence<2||state.ended)return;const weakest=blocs.reduce((a,b)=>state.support[a.id]<state.support[b.id]?a:b);state.influence-=2;state.support[weakest.id]=Math.min(100,state.support[weakest.id]+9+(state.mediator?3:0));state.legit-=1;render();note(`Meeting with ${weakest.name}.`,'Targeted outreach improved support but slightly reduced broad legitimacy.');tone(500)}
    function vote(){if(!state.picked||state.ended)return;if(state.budget<state.picked.cost){note('Insufficient budget.','Amend the agenda or choose a less expensive proposal.');tone(150);return}const forecast={};blocs.forEach(b=>forecast[b.id]=Math.max(0,Math.min(100,state.support[b.id]+state.picked.effects[b.id]*8+(state.amended?2:0))));const yes=blocs.filter(b=>forecast[b.id]>=60).length,collapse=blocs.some(b=>forecast[b.id]<20);state.budget-=state.picked.cost;state.round++;if(yes>=3&&!collapse){state.passed++;state.score+=120+yes*25+state.legit;state.legit=Math.min(100,state.legit+state.picked.legit*3);state.support=forecast;note('Policy passed.',`${yes} blocs formed a governing coalition around ${state.picked.name}.`);tone(740)}else{state.score=Math.max(0,state.score-35);state.legit-=9;blocs.forEach(b=>state.support[b.id]=Math.max(0,forecast[b.id]-3));note('Vote failed.',collapse?'One bloc was pushed beyond the durable-coalition boundary.':'The package did not secure three blocs at 60 support.');tone(170)}state.picked=null;state.amended=false;if(Math.random()<.55&&state.round<=modes[state.mode].rounds){const s=shocks[Math.floor(Math.random()*shocks.length)];blocs.forEach(b=>state.support[b.id]=Math.max(0,Math.min(100,state.support[b.id]+s.delta[b.id]*5)));state.budget+=s.budget;note(s.title,s.text)}if(state.passed>=2&&!state.unlocked){state.unlocked=true;state.mediator=true;modes.crisis.locked=false;note('Mediator unlocked.','Future targeted meetings gain extra support, and Crisis mode is now available.')}checkEnd();render()}
    function recover(){if(state.ended||state.influence>3||state.legit>45)return;state.influence+=4;state.legit=Math.min(100,state.legit+8);blocs.forEach(b=>state.support[b.id]=Math.min(100,state.support[b.id]+4));state.score=Math.max(0,state.score-25);render();note('Listening session completed.','The coalition has room to recover, at a score cost.');tone(360)}
    function checkEnd(){const max=modes[state.mode].rounds;if(state.round>max||state.legit<=0||Object.values(state.support).some(v=>v<=0)){state.ended=true;const durable=state.passed>=3&&Math.min(...Object.values(state.support))>=25;state.score+=durable?300:0;note(durable?'Durable coalition formed.':'Council term ended.',durable?`You passed ${state.passed} policies without abandoning a bloc.`:`${state.passed} policies passed. Recover legitimacy and protect the weakest bloc next run.`);tone(durable?880:120,.18)}}
    function render(){const max=modes[state.mode].rounds;$('#cc-round',root).textContent=`${Math.min(state.round,max)} / ${max}`;$('#cc-budget',root).textContent=state.budget;$('#cc-influence',root).textContent=state.influence;$('#cc-legit',root).textContent=Math.max(0,state.legit);$('#cc-score',root).textContent=state.score;$('#cc-coalition',root).textContent=`${blocs.filter(b=>state.support[b.id]>=60).length} / 4`;const ring=$('.cc-ring',root);ring.innerHTML=blocs.map(b=>`<article class="cc-bloc"><header><span>${b.icon} ${b.name}</span><span>${state.support[b.id]}</span></header><div class="cc-meter" aria-label="${b.name} support ${state.support[b.id]} out of 100"><i style="width:${state.support[b.id]}%"></i></div></article>`).join('');const agenda=$('.cc-agenda',root);agenda.innerHTML=state.picked?`<strong>${state.picked.name}</strong><div>${state.picked.tag} · Budget ${state.picked.cost}${state.amended?' · amended':''}</div><small>Forecast: ${blocs.map(b=>`${b.name} ${Math.max(0,Math.min(100,state.support[b.id]+state.picked.effects[b.id]*8+(state.amended?2:0)))}`).join(' · ')}</small>`:'<strong>No proposal selected.</strong><div>Choose a policy card to place it on the agenda.</div>';const list=$('.cc-proposals',root);list.innerHTML='';proposals.forEach((p,i)=>{const b=document.createElement('button');b.className='cc-proposal'+(state.picked?.name===p.name?' is-picked':'');b.innerHTML=`<strong>${i+1}. ${p.name}</strong><small>${p.tag} · cost ${p.cost} · ${blocs.map(x=>`${x.name} ${p.effects[x.id]>=0?'+':''}${p.effects[x.id]}`).join(' / ')}</small>`;b.disabled=state.ended;b.onclick=()=>choose(i);list.append(b)});const modesBox=$('.cc-modes',root);modesBox.innerHTML='';Object.entries(modes).forEach(([id,m])=>{const b=document.createElement('button');b.textContent=m.locked?`${m.name} · locked`:m.name;b.disabled=m.locked;b.classList.toggle('is-active',state.mode===id);b.onclick=()=>{state.mode=id;reset()};modesBox.append(b)});$('[data-act="amend"]',root).disabled=!state.picked||state.influence<2||state.amended||state.ended;$('[data-act="lobby"]',root).disabled=!state.picked||state.influence<2||state.ended;$('[data-act="vote"]',root).disabled=!state.picked||state.ended;$('[data-act="recover"]',root).disabled=state.ended||state.influence>3||state.legit>45}
    root.addEventListener('click',e=>{const a=e.target.closest('[data-act]')?.dataset.act;if(!a)return;if(a==='amend')amend();if(a==='lobby')lobby();if(a==='vote')vote();if(a==='recover')recover();if(a==='restart')reset();if(a==='sound'){state.sound=!state.sound;e.target.textContent=state.sound?'Sound on':'Sound off';e.target.setAttribute('aria-pressed',String(state.sound));tone(440)}});
    const key=e=>{if(dialog.open&&document.activeElement?.tagName!=='INPUT'){if(/^[1-8]$/.test(e.key)){e.preventDefault();choose(Number(e.key)-1)}if(e.key.toLowerCase()==='a')amend();if(e.key.toLowerCase()==='l')lobby();if(e.key==='Enter'){e.preventDefault();vote()}}};window.addEventListener('keydown',key);dialog.addEventListener('close',()=>{window.removeEventListener('keydown',key);state.ac?.close();root.remove()},{once:true});reset();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();