(() => {
'use strict';
const APP={name:'Crisis Channel',emoji:'📡',category:'play',version:'1.0.3',summary:'Negotiate six escalating crises by balancing trust, time, intelligence, concessions, and public pressure.',description:'A local-only branching negotiation simulator with six scenarios, stakeholder motives, timed rounds, limited intelligence, reversible commitments, trust and pressure tradeoffs, visible agreement gates, adaptive consequences, scoring, progression, meaningful failure, one-use mediator recovery, keyboard and touch controls, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const CASES=[
{name:'School bus standoff',rounds:5,trust:48,pressure:25,intel:2,capital:5,target:62,needs:['safety','dignity'],risk:'panic'},
{name:'Harbor blockade',rounds:6,trust:44,pressure:32,intel:2,capital:6,target:66,needs:['livelihood','voice'],risk:'shortage'},
{name:'Hospital walkout',rounds:6,trust:42,pressure:38,intel:3,capital:6,target:70,needs:['safety','fairness'],risk:'fatigue'},
{name:'Data-center siege',rounds:7,trust:38,pressure:42,intel:3,capital:7,target:73,needs:['control','dignity'],risk:'outage'},
{name:'Border convoy',rounds:7,trust:35,pressure:48,intel:3,capital:7,target:76,needs:['voice','safety'],risk:'escalation'},
{name:'Orbital habitat mutiny',rounds:8,trust:32,pressure:54,intel:4,capital:8,target:80,needs:['fairness','control'],risk:'life support'}
];
const MOVES=[
{id:'listen',name:'Reflective listening',cost:0,intel:0,trust:9,pressure:-3,tags:['dignity','voice'],desc:'Name the concern without promising an outcome.'},
{id:'probe',name:'Ask a diagnostic question',cost:0,intel:1,trust:4,pressure:0,tags:['control','fairness'],desc:'Spend time to uncover a hidden priority.'},
{id:'pause',name:'Call a cooling pause',cost:0,intel:0,trust:2,pressure:-8,tags:['safety'],desc:'Reduce heat, but risk appearing slow.'},
{id:'offer',name:'Make a conditional offer',cost:2,intel:0,trust:8,pressure:-2,tags:['fairness','livelihood'],desc:'Trade negotiating capital for movement.'},
{id:'verify',name:'Share verified evidence',cost:1,intel:-1,trust:7,pressure:-4,tags:['safety','control'],desc:'Consume intelligence to correct assumptions.'},
{id:'deadline',name:'Set a firm deadline',cost:0,intel:0,trust:-7,pressure:12,tags:['control'],desc:'Create urgency at a relationship cost.'},
{id:'bridge',name:'Offer a face-saving bridge',cost:1,intel:0,trust:11,pressure:-1,tags:['dignity','voice'],desc:'Create a path to agreement without public defeat.'},
{id:'public',name:'Brief the public',cost:0,intel:0,trust:-2,pressure:-10,tags:['fairness'],desc:'Lower outside pressure but narrow private flexibility.'}
];
function style(){if($('#crisis-channel-style'))return;const e=document.createElement('style');e.id='crisis-channel-style';e.textContent=`.crisis-channel{max-width:1120px;display:grid;gap:12px}.cc-hud{display:grid;grid-template-columns:repeat(7,1fr);gap:7px}.cc-stat,.cc-panel{border:1px solid var(--line);border-radius:17px;background:#fff}.cc-stat{padding:9px}.cc-stat span{display:block;font-size:.6rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.cc-layout{display:grid;grid-template-columns:1.05fr .95fr;gap:12px}.cc-panel{padding:14px}.cc-brief{padding:16px;border-radius:17px;background:linear-gradient(135deg,#152b3f,#28566f);color:#fff}.cc-pressure{height:14px;border-radius:999px;background:#e7edf1;overflow:hidden;margin:12px 0}.cc-pressure span{display:block;height:100%;background:linear-gradient(90deg,#4b9a8b,#efb64d,#c65b57);transform-origin:left}.cc-transcript{min-height:190px;max-height:260px;overflow:auto;padding:12px;border:1px solid var(--line);border-radius:14px;background:#f8fafb}.cc-line{padding:9px 10px;border-radius:11px;margin-bottom:7px;background:#fff}.cc-line strong{display:block;font-size:.72rem;text-transform:uppercase;letter-spacing:.07em}.cc-line.them{border-left:4px solid #28566f}.cc-line.you{border-left:4px solid #c18431}.cc-moves{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:10px}.cc-move{min-height:76px;text-align:left;border:1px solid var(--line);border-radius:13px;background:#fff;padding:10px}.cc-move.is-selected{outline:3px solid #28566f}.cc-move small{display:block;color:var(--muted);margin-top:4px}.cc-actions,.cc-gates{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:10px}.cc-actions button{min-height:46px}.cc-actions .primary{background:#dceaf0;border-color:#28566f}.cc-gate{padding:8px;border-radius:10px;background:#f1f3f5;font-size:.75rem}.cc-gate.pass{background:#e1f4e9}.cc-log{min-height:105px}.cc-hint{font-size:.8rem;color:var(--muted)}button:focus-visible{outline:3px solid #28566f;outline-offset:2px}@media(max-width:860px){.cc-layout{grid-template-columns:1fr}.cc-hud{grid-template-columns:repeat(4,1fr)}}@media(max-width:560px){.cc-hud{grid-template-columns:repeat(2,1fr)}.cc-moves,.cc-actions,.cc-gates{grid-template-columns:1fr}.cc-move,.cc-actions button{min-height:52px}}@media(prefers-reduced-motion:reduce){.crisis-channel *{animation:none!important;transition:none!important}}`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-crisis-channel]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true),a=$('.app-card',f);a.dataset.crisisChannel='1';a.dataset.category=APP.category;$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;$('.app-card-button',f).addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-crisis-channel]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.ccBound)return;b.dataset.ccBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · branching negotiation';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
const root=document.createElement('section');root.className='tool-panel crisis-channel';root.innerHTML=`<div class="cc-hud">${['Case','Round','Trust','Pressure','Intel','Capital','Score'].map((x,i)=>`<div class="cc-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="cc-layout"><section class="cc-panel"><div class="cc-brief"><p class="app-meta" data-case></p><h3>Find an agreement before pressure breaks the channel.</h3><p data-brief></p></div><div class="cc-pressure" aria-hidden="true"><span data-meter></span></div><div class="cc-transcript" data-transcript aria-live="polite"></div><p class="cc-hint">Select a move, then commit it. Keyboard: arrows choose, 1–8 select, Space commits, I gathers intelligence, U undoes, Enter proposes settlement.</p></section><aside class="cc-panel"><div class="cc-moves" data-moves></div><div class="result-card cc-log" aria-live="polite"></div><div class="cc-gates" data-gates></div><div class="cc-actions"><button data-a="commit">Commit selected move</button><button data-a="intel">Gather intelligence</button><button data-a="undo">Undo last move</button><button data-a="recover">Bring in mediator</button><button class="primary" data-a="settle">Propose settlement</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
let st,ended=false,failed=false,keyHandler,closeHandler,actionHandler;
const current=()=>CASES[st.case];
function log(a,b){$('.cc-log',root).innerHTML=`<strong>${a}</strong><p>${b}</p>`}
function reset(){st={case:0,round:0,trust:CASES[0].trust,pressure:CASES[0].pressure,intel:CASES[0].intel,capital:CASES[0].capital,score:0,selected:0,recovery:true,unlock:false,history:[],transcript:[]};ended=false;failed=false;startCase()}
function startCase(){const c=current();failed=false;Object.assign(st,{round:0,trust:clamp(c.trust+(st.unlock?5:0),0,100),pressure:c.pressure,intel:c.intel+(st.unlock?1:0),capital:c.capital,selected:0,history:[],transcript:[{who:'them',text:`We need ${c.needs[0]} and ${c.needs[1]}. The immediate risk is ${c.risk}.`} ]});log(c.name,'Read the room, build trust, control pressure, and keep enough capital for a credible settlement.');draw()}
function snapshot(){return JSON.stringify({round:st.round,trust:st.trust,pressure:st.pressure,intel:st.intel,capital:st.capital,score:st.score,selected:st.selected,transcript:st.transcript})}
function commit(){if(ended||failed)return;const c=current(),m=MOVES[st.selected];if(st.round>=c.rounds)return log('No rounds remain.','Propose settlement, undo, or use the mediator.');if(st.capital<m.cost)return log('Not enough negotiating capital.','Choose a lower-cost move or undo.');if(m.intel<0&&st.intel<1)return log('No verified intelligence.','Gather intelligence before sharing evidence.');st.history.push(snapshot());st.round++;st.capital-=m.cost;st.intel=clamp(st.intel+m.intel,0,6);const fit=m.tags.filter(t=>c.needs.includes(t)).length;let trust=m.trust+fit*5,pressure=m.pressure;if(m.id==='deadline'&&st.pressure>55)trust-=6;if(m.id==='public'&&st.trust<45)trust-=4;if(m.id==='pause'&&st.round===c.rounds)pressure+=5;st.trust=clamp(st.trust+trust,0,100);st.pressure=clamp(st.pressure+pressure+Math.max(0,st.round-3)*2,0,100);st.transcript.push({who:'you',text:m.name});st.transcript.push({who:'them',text:fit?`That addresses ${c.needs.find(t=>m.tags.includes(t))}. Keep going.`:'That does not reach our core concern yet.'});if(st.pressure>=100)return finish(false,'Public pressure broke the channel before an agreement.');if(st.trust<=0)return finish(false,'Trust collapsed and the other side ended talks.');log('Move committed.',`${m.name}: trust ${trust>=0?'+':''}${trust}, pressure ${pressure>=0?'+':''}${pressure}.`);draw()}
function gather(){if(ended||failed)return;const c=current();if(st.round>=c.rounds)return log('No rounds remain.','The information window has closed.');if(st.capital<1)return log('No capital for intelligence.','Undo or choose a free move.');st.history.push(snapshot());st.round++;st.capital--;st.intel=clamp(st.intel+2,0,6);st.pressure=clamp(st.pressure+5,0,100);st.transcript.push({who:'you',text:'Requested a verified situation brief.'});st.transcript.push({who:'them',text:`The hidden priority is ${c.needs[1]}; delay increases ${c.risk}.`});log('Intelligence gained.','Two intelligence gained, one capital spent, and pressure rose by five.');draw()}
function undo(){if(!st.history.length||ended||failed)return log('Nothing to undo.','No reversible move remains.');Object.assign(st,JSON.parse(st.history.pop()));log('Move reversed.','Round, resources, trust, pressure, score, and transcript were restored.');draw()}
function recover(){const c=current(),eligible=failed||st.round>=c.rounds;if(ended||!st.recovery||!eligible)return log('Mediator unavailable.',!st.recovery?'This recovery is available once per session.':'The mediator steps in only after talks fail or the final round is spent.');const wasFailed=failed;failed=false;st.recovery=false;st.score=Math.max(0,st.score-300);st.trust=clamp(st.trust+12,0,100);st.pressure=clamp(st.pressure-18,0,100);st.capital+=1;st.round=Math.max(0,st.round-1);st.transcript.push({who:'them',text:'A neutral mediator reframed the dispute and reopened one round.'});log(wasFailed?'Channel reopened.':'Final round reopened.','Trust rose, pressure fell, one capital returned, and one round reopened at a score cost.');draw()}
function gates(){const c=current();return[{label:`Trust ≥ ${c.target}`,pass:st.trust>=c.target},{label:'Pressure ≤ 70',pass:st.pressure<=70},{label:'Intel ≥ 1',pass:st.intel>=1},{label:'Capital ≥ 1',pass:st.capital>=1},{label:'At least 2 moves',pass:st.round>=2}]}
function settle(){if(ended||failed)return;const c=current(),g=gates(),pass=g.every(x=>x.pass);if(!pass)return finish(false,`Settlement rejected. Trust ${st.trust}, pressure ${st.pressure}, intel ${st.intel}, capital ${st.capital}. Use the mediator to reopen talks or start a new session.`);st.score+=Math.max(0,st.trust*9+(100-st.pressure)*5+st.intel*45+st.capital*55+(c.rounds-st.round)*35);if(st.score>=3200)st.unlock=true;if(st.case===CASES.length-1)return finish(true,`All six crises resolved. Final score ${st.score}.`);st.case++;startCase()}
function finish(win,msg){ended=win;failed=!win;log(win?'Channel secured.':'Talks failed.',msg);draw()}
function draw(){const c=current(),mediatorReady=failed||st.round>=c.rounds;$$('[data-h]',root).forEach((x,i)=>x.textContent=[`${st.case+1}/6`,`${st.round}/${c.rounds}`,st.trust,st.pressure,st.intel,st.capital,st.score][i]);$('[data-case]',root).textContent=c.name;$('[data-brief]',root).textContent=`Agreement target ${c.target} trust. Core needs: ${c.needs.join(' and ')}. ${failed?'Talks are broken: use the one-use mediator or restart. ':st.round>=c.rounds?'The final round is spent: settle, undo, or use the mediator. ':''}${st.unlock?'Senior liaison unlocked: +5 trust and +1 intelligence at each new case.':''}`;$('[data-meter]',root).style.transform=`scaleX(${st.pressure/100})`;$('[data-transcript]',root).innerHTML=st.transcript.slice(-8).map(x=>`<div class="cc-line ${x.who}"><strong>${x.who==='you'?'You':'Counterpart'}</strong>${x.text}</div>`).join('');$('[data-moves]',root).innerHTML=MOVES.map((m,i)=>`<button class="cc-move ${i===st.selected?'is-selected':''}" data-m="${i}" type="button" aria-pressed="${i===st.selected}" ${ended||failed?'disabled':''}><strong>${i+1}. ${m.name}</strong><small>${m.desc}</small><small>Capital ${m.cost} · Intel ${m.intel<0?'1 required':m.intel?`+${m.intel}`:'—'}</small></button>`).join('');$$('[data-m]',root).forEach(b=>b.onclick=()=>{st.selected=+b.dataset.m;draw()});$('[data-gates]',root).innerHTML=gates().map(g=>`<div class="cc-gate ${g.pass?'pass':''}">${g.pass?'✓':'○'} ${g.label}</div>`).join('');const buttons=Object.fromEntries($$('[data-a]',root).map(b=>[b.dataset.a,b]));buttons.commit.disabled=ended||failed||st.round>=c.rounds||st.capital<MOVES[st.selected].cost||(MOVES[st.selected].intel<0&&st.intel<1);buttons.intel.disabled=ended||failed||st.round>=c.rounds||st.capital<1;buttons.undo.disabled=ended||failed||!st.history.length;buttons.recover.disabled=ended||!st.recovery||!mediatorReady;buttons.recover.title=!st.recovery?'Mediator already used':mediatorReady?'Reopen one round':'Available after failure or the final round';buttons.settle.disabled=ended||failed;buttons.commit.textContent=`Commit: ${MOVES[st.selected].name`}
}
actionHandler=e=>{const b=e.target instanceof Element?e.target.closest('[data-a]'):null;if(!b||!root.contains(b)||b.disabled)return;({commit,intel:gather,undo,recover,settle,restart:reset}[b.dataset.a]||(()=>{}))()};
keyHandler=e=>{if(!dialog.open)return;const t=e.target;if(t instanceof HTMLElement&&(t.matches('button,a,input,select,textarea,[contenteditable="true"]')||t.closest('button,a,input,select,textarea,[contenteditable="true"]')))return;if(/^[1-8]$/.test(e.key)){if(!ended&&!failed){st.selected=+e.key-1;draw()}e.preventDefault()}else if(e.key==='ArrowRight'||e.key==='ArrowDown'){if(!ended&&!failed){st.selected=(st.selected+1)%MOVES.length;draw()}e.preventDefault()}else if(e.key==='ArrowLeft'||e.key==='ArrowUp'){if(!ended&&!failed){st.selected=(st.selected+MOVES.length-1)%MOVES.length;draw()}e.preventDefault()}else if(e.key===' '){commit();e.preventDefault()}else if(e.key.toLowerCase()==='i'){gather();e.preventDefault()}else if(e.key.toLowerCase()==='u'){undo();e.preventDefault()}else if(e.key==='Enter'){settle();e.preventDefault()}};
closeHandler=()=>{document.removeEventListener('keydown',keyHandler);root.removeEventListener('click',actionHandler);dialog.removeEventListener('close',closeHandler)};root.addEventListener('click',actionHandler);document.addEventListener('keydown',keyHandler);dialog.addEventListener('close',closeHandler);reset()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();