(() => {
  'use strict';
  const APP={name:'Cut Room',emoji:'🎬',category:'play',version:'1.0.0',summary:'Assemble six-scene cuts, protect continuity, and tune pace, emotion, and runtime under deadline pressure.',description:'A local-only film-editing strategy game with six commissions, a draggable timeline, shot sequencing, continuity, pacing, sound, limited edit time, client trust, scoring, a session unlock, meaningful failure, one costly recovery, touch, keyboard controls, reduced motion, and teardown.'};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const SHOTS=[
    {id:'wide',name:'Wide establish',dur:8,pace:-2,emotion:1,clarity:4,continuity:'space'},
    {id:'close',name:'Close reaction',dur:5,pace:1,emotion:5,clarity:1,continuity:'face'},
    {id:'action',name:'Action insert',dur:4,pace:5,emotion:1,clarity:2,continuity:'motion'},
    {id:'detail',name:'Detail clue',dur:3,pace:3,emotion:2,clarity:5,continuity:'object'},
    {id:'two',name:'Two-shot',dur:7,pace:-1,emotion:3,clarity:3,continuity:'eyeline'},
    {id:'silence',name:'Held silence',dur:6,pace:-4,emotion:5,clarity:0,continuity:'breath'}
  ];
  const COMMISSIONS=[
    {brief:'A reunion must feel warm without becoming slow.',target:{pace:0,emotion:13,clarity:10},max:24,need:['space','face']},
    {brief:'A chase needs speed, geography, and one readable clue.',target:{pace:10,emotion:5,clarity:12},max:20,need:['space','motion','object']},
    {brief:'A reveal should land through reaction before explanation.',target:{pace:1,emotion:15,clarity:9},max:23,need:['face','object']},
    {brief:'A negotiation must stay tense while preserving eyelines.',target:{pace:2,emotion:12,clarity:12},max:26,need:['eyeline','face']},
    {brief:'A farewell should breathe, then finish on a decisive image.',target:{pace:-5,emotion:16,clarity:8},max:25,need:['breath','face']},
    {brief:'The finale must combine momentum, emotion, and visual logic.',target:{pace:8,emotion:15,clarity:15},max:28,need:['space','motion','face','object']}
  ];
  function style(){if($('#cut-room-style'))return;const e=document.createElement('style');e.id='cut-room-style';e.textContent=`
  .cut-room{max-width:1120px;display:grid;gap:12px}.cr-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.cr-stat,.cr-card{border:1px solid var(--line);border-radius:17px;background:#fff}.cr-stat{padding:9px}.cr-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.cr-layout{display:grid;grid-template-columns:1.15fr .85fr;gap:12px}.cr-card{padding:15px}.cr-monitor{position:relative;min-height:285px;border-radius:24px;overflow:hidden;background:#0d1117;color:white}.cr-monitor canvas{position:absolute;inset:0;width:100%;height:100%}.cr-monitor-copy{position:relative;z-index:1;min-height:285px;display:grid;place-content:end start;padding:20px;background:linear-gradient(transparent,rgba(0,0,0,.76));pointer-events:none}.cr-monitor-copy strong{font-size:clamp(1.35rem,4vw,2.4rem)}.cr-timeline{display:flex;gap:7px;overflow-x:auto;padding:10px 2px 4px;min-height:88px}.cr-clip{min-width:116px;border:2px solid transparent;border-radius:13px;background:#f3f4f6;padding:9px;text-align:left;font-weight:850;touch-action:none}.cr-clip[aria-selected=true]{border-color:#7c3aed;background:#ede9fe}.cr-clip small,.cr-shot small{display:block;color:var(--muted);font-weight:650;margin-top:4px}.cr-bank{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.cr-shot{min-height:62px;border:1px solid var(--line);border-radius:12px;background:#fff;padding:9px;text-align:left;font-weight:800}.cr-shot:disabled{opacity:.45}.cr-controls{display:grid;gap:10px}.cr-sliders{display:grid;grid-template-columns:1fr 1fr;gap:8px}.cr-sliders label{font-size:.78rem;font-weight:800}.cr-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.cr-actions button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800;padding:9px}.cr-actions .primary{background:#ede9fe;border-color:#7c3aed}.cr-log{min-height:114px}.cr-hint{font-size:.72rem;color:var(--muted);margin:0}.cr-meter{height:9px;border-radius:999px;background:#e5e7eb;overflow:hidden}.cr-meter span{display:block;height:100%;background:linear-gradient(90deg,#2563eb,#7c3aed);transform-origin:left}.cr-empty{border:1px dashed var(--line);border-radius:12px;padding:18px;color:var(--muted)}
  @media(max-width:820px){.cr-layout{grid-template-columns:1fr}.cr-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:520px){.cr-hud{grid-template-columns:repeat(2,1fr)}.cr-bank,.cr-actions,.cr-sliders{grid-template-columns:1fr 1fr}.cr-monitor,.cr-monitor-copy{min-height:235px}.cr-clip{min-width:104px}}
  @media(prefers-reduced-motion:reduce){.cut-room *{animation:none!important;transition:none!important}}
  `;document.head.append(e)}
  function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-cut-room]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.cutRoom='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
  function boot(){style();let n=0;const r=()=>{card();if(!$('[data-cut-room]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.crBound)return;b.dataset.crBound='1';b.addEventListener('click',()=>setTimeout(card))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · film editing strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){
    const root=document.createElement('section');root.className='tool-panel cut-room';root.innerHTML=`<div class="cr-hud">${['Cut','Edit time','Trust','Score','Runtime','Unlock'].map((x,i)=>`<div class="cr-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="cr-layout"><section class="cr-card"><div class="cr-monitor" aria-label="Animated edit preview"><canvas aria-hidden="true"></canvas><div class="cr-monitor-copy"><span class="eyebrow">Current sequence</span><strong data-preview>Build a cut</strong></div></div><div class="cr-timeline" role="listbox" aria-label="Edit timeline"></div><p class="cr-hint">Tap a clip, use Left and Right to reorder, Delete to remove, or drag clips on the timeline. Repeated continuity types can create jump cuts.</p></section><aside class="cr-card cr-controls"><div class="result-card cr-log" aria-live="polite"></div><div><p class="eyebrow">Footage bin</p><div class="cr-bank"></div></div><div class="cr-sliders"><label>Music intensity <input data-music type="range" min="0" max="4" value="2"></label><label>Transition polish <input data-polish type="range" min="0" max="4" value="1"></label></div><div class="cr-meter" aria-label="Commission fit"><span data-meter></span></div><div class="cr-actions"><button class="primary" data-a="screen">Screen cut</button><button data-a="undo">Undo</button><button data-a="recover">Request pickup</button><button data-a="restart">New edit reel</button></div></aside></div>`;stage.append(root);
    const canvas=$('canvas',root),ctx=canvas.getContext('2d');let st,history=[],timer=0,raf=0,ended=false,dragIndex=-1;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
    function reset(){clearTimeout(timer);cancelAnimationFrame(raf);st={cut:0,time:18,trust:72,score:0,unlock:false,recovery:true,timeline:[],selected:-1,music:2,polish:1};history=[];ended=false;log(COMMISSIONS[0].brief,'Assemble footage, tune sound and transitions, then screen the cut.');draw();animate()}
    function snapshot(){history.push(JSON.stringify(st));if(history.length>12)history.shift()}
    function add(i){if(ended||st.timeline.length>=6||st.time<1)return;const shot=SHOTS[i];if(shot.id==='silence'&&!st.unlock)return log('Held silence is locked.','Reach 4,800 points to unlock the session-only restraint cut.');snapshot();st.timeline.push(i);st.selected=st.timeline.length-1;st.time--;draw()}
    function remove(i){if(ended||i<0)return;snapshot();st.timeline.splice(i,1);st.selected=Math.min(i,st.timeline.length-1);draw()}
    function move(from,to){if(ended||from===to||from<0||to<0||to>=st.timeline.length)return;snapshot();const [x]=st.timeline.splice(from,1);st.timeline.splice(to,0,x);st.selected=to;st.time=Math.max(0,st.time-1);draw()}
    function metrics(){let pace=0,emotion=0,clarity=0,runtime=0,jumps=0;const seen=new Set();st.timeline.forEach((i,p)=>{const s=SHOTS[i];pace+=s.pace;emotion+=s.emotion;clarity+=s.clarity;runtime+=s.dur;if(p&&SHOTS[st.timeline[p-1]].continuity===s.continuity)jumps++;seen.add(s.continuity)});emotion+=st.music*2;pace+=st.music-st.polish;clarity+=st.polish*2;runtime+=st.polish;const c=COMMISSIONS[st.cut];let fit=100-Math.abs(pace-c.target.pace)*4-Math.abs(emotion-c.target.emotion)*3-Math.abs(clarity-c.target.clarity)*3-Math.max(0,runtime-c.max)*5-jumps*12-c.need.filter(x=>!seen.has(x)).length*10;if(st.timeline.length<3)fit-=24;return{pace,emotion,clarity,runtime,jumps,fit:clamp(Math.round(fit),0,100)}}
    function screen(){if(ended||!st.timeline.length)return;const m=metrics(),c=COMMISSIONS[st.cut];st.score+=m.fit*18+Math.max(0,c.max-m.runtime)*12;st.trust=clamp(st.trust+(m.fit>=72?8:m.fit<45?-22:-7),0,100);if(st.score>=4800&&!st.unlock)st.unlock=true;$$('[data-a]',root).forEach(b=>b.disabled=true);timer=setTimeout(()=>{if(!root.isConnected)return;if(st.trust<=0)return finish(false);if(st.cut>=COMMISSIONS.length-1)return finish(true);st.cut++;st.time=18;st.timeline=[];st.selected=-1;history=[];log(m.fit>=72?'The screening lands and the client approves the rhythm.':m.fit>=52?'The cut communicates, but the pacing still feels uncertain.':'The sequence confuses the room and costs trust.',`Fit ${m.fit}. Next commission: ${COMMISSIONS[st.cut].brief}`);draw()},reduced?80:650)}
    function undo(){if(ended||!history.length)return;st=JSON.parse(history.pop());draw()}
    function recover(){if(ended||!st.recovery)return;st.recovery=false;st.trust=clamp(st.trust-14,0,100);st.time+=6;st.timeline=[];st.selected=-1;history=[];log('A pickup shoot delivers replacement footage.','The extra material restores options, but the overrun damages client confidence.');draw()}
    function finish(success){ended=true;clearTimeout(timer);const strong=success&&st.trust>=60&&st.score>=9000;log(strong?'The studio promotes you to lead editor.':success?'The reel ships with a mixed but credible reputation.':'The production pulls the project after repeated failed screenings.',`Final score ${st.score}, trust ${st.trust}. Replay with stronger continuity, pacing, and runtime discipline.`);draw()}
    function log(a,b){const l=$('.cr-log',root);l.replaceChildren(Object.assign(document.createElement('strong'),{textContent:a}),Object.assign(document.createElement('small'),{textContent:b}))}
    function draw(){const m=metrics(),vals=[`${st.cut+1}/6`,`${st.time}h`,st.trust,st.score,`${m.runtime}s`,st.unlock?'Held silence':'Locked'];$$('[data-h]',root).forEach((e,i)=>e.textContent=vals[i]);$('.cr-bank',root).innerHTML=SHOTS.map((s,i)=>`<button class="cr-shot" data-shot="${i}" ${s.id==='silence'&&!st.unlock?'disabled':''}>${s.name}<small>${s.dur}s · pace ${s.pace>0?'+':''}${s.pace} · emotion ${s.emotion} · clarity ${s.clarity}</small></button>`).join('');const tl=$('.cr-timeline',root);tl.innerHTML=st.timeline.length?st.timeline.map((i,p)=>`<button class="cr-clip" draggable="true" role="option" aria-selected="${st.selected===p}" data-clip="${p}">${p+1}. ${SHOTS[i].name}<small>${SHOTS[i].continuity} · ${SHOTS[i].dur}s</small></button>`).join(''):'<div class="cr-empty">Add three to six shots from the footage bin.</div>';$('.cr-monitor-copy strong',root).textContent=st.timeline.length?st.timeline.map(i=>SHOTS[i].name).join(' → '):'Build a cut';$('[data-music]',root).value=st.music;$('[data-polish]',root).value=st.polish;$('[data-meter]',root).style.transform=`scaleX(${m.fit/100})`;$$('[data-a]',root).forEach(b=>b.disabled=ended);$('[data-a="undo"]',root).disabled=ended||!history.length;$('[data-a="recover"]',root).disabled=ended||!st.recovery;bind()}
    function bind(){$$('[data-shot]',root).forEach(b=>b.onclick=()=>add(+b.dataset.shot));$$('[data-clip]',root).forEach((b,i)=>{b.onclick=()=>{st.selected=i;draw()};b.onkeydown=e=>{if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove(i)}else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();move(i,clamp(i+(e.key==='ArrowRight'?1:-1),0,st.timeline.length-1));$$('[data-clip]',root)[st.selected]?.focus()}};b.ondragstart=()=>dragIndex=i;b.ondragover=e=>e.preventDefault();b.ondrop=e=>{e.preventDefault();move(dragIndex,i)}});$('[data-music]',root).oninput=e=>{snapshot();st.music=+e.target.value;draw()};$('[data-polish]',root).oninput=e=>{snapshot();st.polish=+e.target.value;draw()};$('[data-a="screen"]',root).onclick=screen;$('[data-a="undo"]',root).onclick=undo;$('[data-a="recover"]',root).onclick=recover;$('[data-a="restart"]',root).onclick=reset}
    function animate(){cancelAnimationFrame(raf);const loop=t=>{if(!root.isConnected||!dialog.open)return;const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d)}ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,r.width,r.height);const n=Math.max(1,st.timeline.length);for(let i=0;i<n;i++){const x=i*r.width/n,w=r.width/n+1,h=r.height;const hue=(i*47+st.cut*29)%360;ctx.fillStyle=`hsl(${hue} 45% ${24+i%2*6}%)`;ctx.fillRect(x,0,w,h);ctx.fillStyle='rgba(255,255,255,.16)';ctx.beginPath();ctx.arc(x+w*.5,h*.38,22+Math.sin((reduced?0:t/600)+i)*8,0,Math.PI*2);ctx.fill()}if(!reduced)raf=requestAnimationFrame(loop)};loop(0)}
    const cleanup=()=>{clearTimeout(timer);cancelAnimationFrame(raf)};dialog.addEventListener('close',cleanup,{once:true});reset()
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();