(() => {
  'use strict';
  const APP={name:'Exposure Lab',emoji:'📷',category:'play',version:'1.0.0',summary:'Balance light, motion, depth, framing, and limited reshoots across a six-scene photography assignment.',description:'A local-only photography strategy simulation with aperture, shutter speed, ISO, composition, moving subjects, changing light, scoring, session unlocks, failure, recovery, touch, keyboard, reduced-motion, and teardown support.'};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const SCENES=[
    {name:'Street cyclist',light:4,motion:5,depth:2,brief:'Freeze the rider while keeping the city readable.',target:{blur:1,noise:2,depth:2,frame:'lead'}},
    {name:'Window portrait',light:2,motion:1,depth:5,brief:'Separate the subject from the background without losing the eyes.',target:{blur:1,noise:2,depth:5,frame:'thirds'}},
    {name:'Night market',light:1,motion:3,depth:3,brief:'Protect atmosphere and color while preserving a human moment.',target:{blur:2,noise:3,depth:3,frame:'layer'}},
    {name:'Waterfall trail',light:5,motion:4,depth:4,brief:'Choose whether the water feels silky or crisp and support that choice.',target:{blur:4,noise:1,depth:4,frame:'anchor'}},
    {name:'Tiny workshop',light:3,motion:2,depth:5,brief:'Show the tool, the hands, and the workspace as one story.',target:{blur:2,noise:2,depth:5,frame:'layer'}},
    {name:'Festival finale',light:2,motion:5,depth:3,brief:'Catch peak action under unstable light with no safe setting.',target:{blur:1,noise:3,depth:3,frame:'lead'}}
  ];
  const AP=[1.4,2,2.8,4,5.6,8,11],SH=[1000,500,250,125,60,30,15],ISO=[100,200,400,800,1600,3200];
  function style(){if($('#exposure-lab-style'))return;const e=document.createElement('style');e.id='exposure-lab-style';e.textContent=`.exposure-lab{max-width:1120px;display:grid;gap:12px}.el-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.el-stat,.el-card{border:1px solid var(--line);border-radius:16px;background:#fff}.el-stat{padding:8px}.el-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.el-layout{display:grid;grid-template-columns:1.2fr .8fr;gap:12px}.el-card{padding:14px}.el-preview{position:relative;min-height:330px;overflow:hidden;border-radius:18px;background:#0b1020;color:#fff}.el-preview canvas{width:100%;height:330px;display:block}.el-overlay{position:absolute;inset:0;display:flex;justify-content:space-between;align-items:flex-end;padding:14px;pointer-events:none}.el-overlay strong,.el-overlay span{background:rgba(0,0,0,.58);padding:6px 9px;border-radius:999px}.el-controls{display:grid;gap:10px}.el-control{display:grid;grid-template-columns:92px 1fr 64px;align-items:center;gap:8px}.el-control input{width:100%}.el-modes{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.el-modes button,.el-actions button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;color:inherit;font-weight:800;padding:9px}.el-modes button[aria-pressed=true],.el-actions .primary{background:#e0f2fe;border-color:#0369a1}.el-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.el-brief{min-height:116px}.el-meter{height:9px;background:#e2e8f0;border-radius:999px;overflow:hidden}.el-meter span{display:block;height:100%;background:linear-gradient(90deg,#dc2626,#f59e0b,#16a34a)}.el-gridline{position:absolute;background:rgba(255,255,255,.25);pointer-events:none}.el-gridline.v{top:0;bottom:0;width:1px}.el-gridline.h{left:0;right:0;height:1px}@media(max-width:860px){.el-layout{grid-template-columns:1fr}.el-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.el-hud{grid-template-columns:repeat(2,1fr)}.el-control{grid-template-columns:78px 1fr 54px}.el-preview,.el-preview canvas{min-height:270px;height:270px}.el-actions{grid-template-columns:1fr 1fr}}@media(prefers-reduced-motion:reduce){.exposure-lab *{animation:none!important;transition:none!important}}`;document.head.append(e)}
  function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-exposure-lab]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.exposureLab='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
  function boot(){style();let n=0;const r=()=>{card();if(!$('[data-exposure-lab]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.elBound)return;b.dataset.elBound='1';b.addEventListener('click',()=>setTimeout(card))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · visual exposure strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel exposure-lab';root.innerHTML=`<div class="el-hud">${['Scene','Light','Film','Confidence','Score','Unlock'].map((x,i)=>`<div class="el-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="el-layout"><section class="el-card"><div class="el-preview"><canvas aria-label="Simulated photograph preview"></canvas><div class="el-overlay"><strong data-scene></strong><span data-readout></span></div></div></section><aside class="el-card"><p class="eyebrow">Assignment brief</p><div class="result-card el-brief" aria-live="polite"></div><div class="el-controls"><label class="el-control"><span>Aperture</span><input data-c="ap" type="range" min="0" max="6" step="1"><strong data-v="ap"></strong></label><label class="el-control"><span>Shutter</span><input data-c="sh" type="range" min="0" max="6" step="1"><strong data-v="sh"></strong></label><label class="el-control"><span>ISO</span><input data-c="iso" type="range" min="0" max="5" step="1"><strong data-v="iso"></strong></label></div><p class="eyebrow">Composition</p><div class="el-modes">${[['thirds','Rule of thirds'],['lead','Lead space'],['layer','Layered depth'],['anchor','Strong anchor']].map(([k,v])=>`<button data-frame="${k}">${v}</button>`).join('')}</div><div class="el-actions"><button class="primary" data-a="shoot">Take photo</button><button data-a="meter">Meter scene</button><button data-a="recover">Use reshoot<br><small>once · -12 confidence</small></button><button data-a="restart">New assignment</button></div></aside></div>`;stage.append(root);
    const canvas=$('canvas',root),ctx=canvas.getContext('2d');let st,scene,ended=false,raf=0,phase=0,resizeObserver;
    const log=(a,b)=>{const l=$('.el-brief',root);l.replaceChildren(Object.assign(document.createElement('strong'),{textContent:a}),Object.assign(document.createElement('small'),{textContent:b}))};
    function reset(){st={index:0,film:8,confidence:72,score:0,reshoot:true,meter:2,ap:3,sh:3,iso:2,frame:'thirds',lens:false};ended=false;scene=SCENES[0];log(scene.brief,'Balance exposure, motion, depth, noise, and framing. Metering reveals one hidden pressure.');draw();animate()}
    function metrics(){const lightGain=(6-st.ap)+(6-st.sh)*.8+st.iso*.9;const exposure=lightGain-scene.light*1.45;const blur=clamp(scene.motion-(6-st.sh),0,5);const noise=clamp(st.iso-1,0,5);const depth=clamp(st.ap+1,1,6);return{exposure,blur,noise,depth}}
    function shoot(){if(ended)return;if(st.film<=0)return finish(false);st.film--;const m=metrics();const expScore=100-Math.min(70,Math.abs(m.exposure)*18),blurScore=100-Math.abs(m.blur-scene.target.blur)*19,noiseScore=100-Math.abs(m.noise-scene.target.noise)*17,depthScore=100-Math.abs(m.depth-scene.target.depth)*16,frameScore=st.frame===scene.target.frame?100:58;let score=Math.round(clamp(expScore*.3+blurScore*.22+noiseScore*.15+depthScore*.18+frameScore*.15,0,100));if(st.lens)score=Math.min(100,score+8);st.score+=score*12;st.confidence=clamp(st.confidence+(score>=78?6:score<48?-14:-4),0,100);log(score>=82?'The frame lands.':score>=62?'Usable, with tradeoffs.':'The assignment slipped.',`Scene score ${score}. Exposure ${Math.round(m.exposure*10)/10}, motion ${m.blur}, noise ${m.noise}, depth ${m.depth}.`);if(st.score>=2500)st.lens=true;if(score>=60)next();else if(st.confidence<=0||st.film<=0)finish(false);else draw()}
    function meter(){if(ended||st.meter<=0)return;st.meter--;const pressures=[`Motion pressure is ${scene.motion}/5.`,`Available light is ${scene.light}/5.`,`Depth demand is ${scene.depth}/5.`];log('Meter reading',pressures[Math.floor(Math.random()*pressures.length)]);draw()}
    function recover(){if(ended||!st.reshoot)return;st.reshoot=false;st.confidence=clamp(st.confidence-12,0,100);st.film+=2;st.meter+=1;log('A reshoot was approved.','Two frames and one meter reading were restored, but confidence fell because the miss reached the client.');draw()}
    function next(){if(st.index>=SCENES.length-1)return finish(true);st.index++;scene=SCENES[st.index];st.ap=3;st.sh=3;st.iso=2;st.frame='thirds';if(st.index===3){st.film+=1;st.meter+=1}log(scene.brief,st.lens?'The stabilized lens is unlocked for this session and adds a small quality bonus.':'Reach 2,500 points to unlock a stabilized lens.');draw()}
    function finish(success){ended=true;cancelAnimationFrame(raf);const strong=success&&st.confidence>=55&&st.score>=4200;log(strong?'The portfolio is publication-ready.':success?'The assignment closed, but the edit is fragile.':'The client ended the assignment.',`Final score ${st.score}, confidence ${st.confidence}, film ${st.film}. Replay to make different exposure and composition tradeoffs.`);draw()}
    function draw(){const vals=[`${st.index+1}/6`,scene.light,st.film,st.confidence,st.score,st.lens?'Stabilized':'Locked'];$$('[data-h]',root).forEach((e,i)=>e.textContent=vals[i]);$('[data-scene]',root).textContent=scene.name;const m=metrics();$('[data-readout]',root).textContent=`EV ${Math.round(m.exposure*10)/10} · blur ${m.blur} · noise ${m.noise}`;$('[data-v="ap"]',root).textContent=`f/${AP[st.ap]}`;$('[data-v="sh"]',root).textContent=`1/${SH[st.sh]}`;$('[data-v="iso"]',root).textContent=ISO[st.iso];$$('[data-frame]',root).forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.frame===st.frame)));$('[data-a="meter"]',root).textContent=`Meter scene (${st.meter})`;$('[data-a="meter"]',root).disabled=ended||st.meter<=0;$('[data-a="recover"]',root).disabled=ended||!st.reshoot;$('[data-a="shoot"]',root).disabled=ended;renderPreview()}
    function renderPreview(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.floor(r.width*dpr));canvas.height=Math.max(1,Math.floor(r.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);const w=r.width,h=r.height,m=metrics(),brightness=clamp(.2+m.exposure*.08,.05,.75);ctx.fillStyle=`hsl(${210+st.index*18} 36% ${10+brightness*35}%)`;ctx.fillRect(0,0,w,h);const count=18;for(let i=0;i<count;i++){const x=(i*67+phase*(scene.motion+1))%(w+60)-30,y=(i*43)%h,size=18+(i%4)*11;ctx.globalAlpha=.22+brightness*.45;ctx.fillStyle=i%3===0?'#fbbf24':i%3===1?'#38bdf8':'#f472b6';ctx.beginPath();ctx.arc(x,y,size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.fillStyle='rgba(255,255,255,.9)';const sx=st.frame==='lead'?w*.35:st.frame==='thirds'?w*.66:w*.5,sy=st.frame==='layer'?h*.42:h*.55;ctx.fillRect(sx-10,sy-35,20,70);ctx.beginPath();ctx.arc(sx,sy-48,13,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.23)';ctx.lineWidth=1;[1,2].forEach(n=>{ctx.beginPath();ctx.moveTo(w*n/3,0);ctx.lineTo(w*n/3,h);ctx.stroke();ctx.beginPath();ctx.moveTo(0,h*n/3);ctx.lineTo(w,h*n/3);ctx.stroke()})}
    function animate(){cancelAnimationFrame(raf);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const tick=()=>{if(!document.contains(root)||ended)return;phase+=reduced?0:.35;renderPreview();raf=requestAnimationFrame(tick)};tick()}
    root.addEventListener('input',e=>{const k=e.target.dataset.c;if(k){st[k]=+e.target.value;draw()}});root.addEventListener('click',e=>{const f=e.target.closest('[data-frame]');if(f){st.frame=f.dataset.frame;draw();return}const a=e.target.closest('[data-a]')?.dataset.a;if(a==='shoot')shoot();if(a==='meter')meter();if(a==='recover')recover();if(a==='restart')reset()});
    root.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('[data-frame]')){st.frame=e.target.dataset.frame;draw()}});resizeObserver=new ResizeObserver(()=>renderPreview());resizeObserver.observe(canvas);dialog.addEventListener('close',()=>{cancelAnimationFrame(raf);resizeObserver.disconnect()},{once:true});reset()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();