(() => {
'use strict';
const APP={name:'Fabline Control',emoji:'◫',category:'play',version:'1.1.0',summary:'Run six semiconductor lots through drifting tools while balancing yield, throughput, contamination, cost, and maintenance.',description:'A local-only semiconductor process-control strategy game with six production lots, differentiated controls, hidden tool drift, inspections with uncertainty, limited wafers, maintenance tradeoffs, readiness gates, adaptive targets, failure, recovery, session progression, keyboard and touch controls, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const KNOBS=[
 {id:'temp',label:'Temperature',effect:'Raises activation and center yield; excess heat amplifies contamination.'},
 {id:'dose',label:'Exposure dose',effect:'Sharpens pattern fidelity; aggressive dose narrows the process window.'},
 {id:'pressure',label:'Chamber pressure',effect:'Improves profile control; high pressure accelerates tool drift.'},
 {id:'flow',label:'Gas flow',effect:'Improves uniformity and contamination removal; high flow costs throughput.'}
];
const LOTS=[
 {name:'Lot 1 · Baseline logic',target:72,wafers:5,ideal:{temp:7,dose:5,pressure:5,flow:5},sens:{temp:8,dose:4,pressure:4,flow:3},hint:'The chamber is running slightly cool.',window:'Temperature is the dominant lever.'},
 {name:'Lot 2 · Dense memory',target:75,wafers:5,ideal:{temp:5,dose:7,pressure:5,flow:6},sens:{temp:3,dose:9,pressure:4,flow:5},hint:'Critical dimensions are widening.',window:'Dose matters most; flow can recover uniformity.'},
 {name:'Lot 3 · Low-power node',target:78,wafers:4,ideal:{temp:6,dose:5,pressure:7,flow:5},sens:{temp:5,dose:4,pressure:9,flow:4},hint:'Sidewall profiles are becoming uneven.',window:'Pressure is dominant and carries drift risk.'},
 {name:'Lot 4 · Mixed product',target:81,wafers:4,ideal:{temp:6,dose:6,pressure:5,flow:7},sens:{temp:5,dose:5,pressure:4,flow:9},hint:'Across-wafer uniformity is slipping.',window:'Flow is dominant but reduces throughput.'},
 {name:'Lot 5 · Tool aging',target:84,wafers:3,ideal:{temp:7,dose:6,pressure:6,flow:7},sens:{temp:8,dose:6,pressure:6,flow:7},hint:'Residue is accelerating chamber drift.',window:'A balanced recipe and timely clean are required.'},
 {name:'Lot 6 · Qualification run',target:87,wafers:3,ideal:{temp:7,dose:7,pressure:6,flow:7},sens:{temp:8,dose:9,pressure:7,flow:8},hint:'The process window is narrow and unforgiving.',window:'All four controls must sit inside a tight window.'}
];
function style(){if($('#fabline-control-style'))return;const e=document.createElement('style');e.id='fabline-control-style';e.textContent=`
.fabline{max-width:1120px;display:grid;gap:12px}.fc-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.fc-stat,.fc-panel{border:1px solid var(--line);border-radius:17px;background:#fff}.fc-stat{padding:9px}.fc-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.fc-layout{display:grid;grid-template-columns:1.05fr .95fr;gap:12px}.fc-panel{padding:15px}.fc-lot{padding:16px;border-radius:18px;background:linear-gradient(135deg,#0c2338,#155e75);color:#fff}.fc-wafer{width:180px;aspect-ratio:1;border-radius:50%;margin:14px auto;background:radial-gradient(circle at 35% 30%,#d9fbff,#79cbd3 42%,#124e63 70%,#092d40);box-shadow:inset -15px -18px 30px #06253866,0 12px 28px #0a516044;position:relative;overflow:hidden}.fc-wafer:after{content:'';position:absolute;inset:14%;background:repeating-linear-gradient(90deg,#ffffff33 0 2px,transparent 2px 14px),repeating-linear-gradient(0deg,#ffffff22 0 2px,transparent 2px 14px);border-radius:50%;transform:rotate(8deg)}.fc-wafer[data-risk=high]{box-shadow:inset -15px -18px 30px #55200088,0 0 0 5px #b64b2b55,0 12px 28px #0a516044}.fc-knobs{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.fc-knob{border:1px solid var(--line);border-radius:13px;padding:10px}.fc-knob[data-selected=true]{border-color:#155e75;box-shadow:0 0 0 2px #155e7522}.fc-stepper{display:grid;grid-template-columns:42px 1fr 42px;gap:6px;align-items:center;margin-top:7px}.fc-stepper button,.fc-actions button{min-height:42px;border:1px solid var(--line);border-radius:10px;background:#fff;font-weight:900}.fc-stepper output{text-align:center;font-weight:900}.fc-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.fc-actions .primary{background:#d8f3f5;border-color:#155e75}.fc-stepper button:focus-visible,.fc-actions button:focus-visible{outline:3px solid #155e75;outline-offset:2px}.fc-row{display:flex;justify-content:space-between;gap:10px;margin:7px 0}.fc-meter{height:10px;background:#e6eef0;border-radius:99px;overflow:hidden}.fc-meter span{display:block;height:100%;background:#167d8c;transition:width .25s}.fc-log{min-height:112px}.fc-hint{font-size:.82rem;color:var(--muted)}.fc-good{color:#176642}.fc-bad{color:#9a3e26}.fc-gates{display:grid;grid-template-columns:repeat(2,1fr);gap:6px;margin:10px 0}.fc-gate{padding:7px 9px;border-radius:10px;background:#f2f5f5;font-size:.76rem;font-weight:800}.fc-gate[data-pass=true]{background:#e5f5ed;color:#176642}.fc-range{font-size:.78rem;color:var(--muted);min-height:2.4em}.fc-actions button:disabled,.fc-stepper button:disabled{opacity:.48;cursor:not-allowed}
@media(max-width:840px){.fc-layout{grid-template-columns:1fr}.fc-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.fc-hud{grid-template-columns:repeat(2,1fr)}.fc-knobs,.fc-actions,.fc-gates{grid-template-columns:1fr}.fc-stepper{grid-template-columns:52px 1fr 52px}.fc-wafer{width:145px}}@media(prefers-reduced-motion:reduce){.fabline *{animation:none!important;transition:none!important}}
`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-fabline-control]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true),a=$('.app-card',f);a.dataset.fablineControl='1';a.dataset.category=APP.category;$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-fabline-control]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.fcBound)return;b.dataset.fcBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · process control';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
 const root=document.createElement('section');root.className='tool-panel fabline';root.innerHTML=`<div class="fc-hud">${['Lot','Wafers','Yield','Trust','Cost','Score'].map((x,i)=>`<div class="fc-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="fc-layout"><section class="fc-panel"><div class="fc-lot"><p class="app-meta" data-set></p><h3 data-title></h3><p data-hint></p></div><div class="fc-wafer" aria-hidden="true"></div><div class="fc-knobs" data-knobs></div><p class="fc-hint">Keyboard: 1-4 select a process knob, ↑/↓ adjust, I inspect, M clean, Enter run wafer.</p></section><aside class="fc-panel"><div class="result-card fc-log" aria-live="polite"></div><div class="fc-row"><span>Predicted yield</span><strong data-yield></strong></div><div class="fc-meter"><span data-meter></span></div><p class="fc-range" data-range></p><div class="fc-gates" data-gates></div><div class="fc-row"><span>Contamination</span><strong data-contam></strong></div><div class="fc-row"><span>Tool drift</span><strong data-drift></strong></div><div class="fc-row"><span>Throughput</span><strong data-throughput></strong></div><div class="fc-actions"><button class="primary" data-a="run">Run wafer</button><button data-a="inspect">Inspect sample</button><button data-a="maintain">Clean chamber</button><button data-a="recover">Call process engineer</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
 let st,ended=false,keyHandler,closeHandler;
 const nominal=()=>({temp:5,dose:5,pressure:5,flow:5});
 function reset(){st={level:0,wafers:LOTS[0].wafers,trust:72,cost:0,score:0,knobs:nominal(),selected:0,contam:8,drift:18,inspections:2,engineer:true,unlock:false,last:0,audited:false,estimate:null};ended=false;log('Line ready.','Tune the process, inspect sparingly, and preserve enough wafers to qualify each lot.');draw()}
 function lot(){return LOTS[st.level]}
 function metrics(){const l=lot();let recipeError=0;KNOBS.forEach(k=>{recipeError+=Math.abs(st.knobs[k.id]-l.ideal[k.id])*l.sens[k.id]});const tempOver=Math.max(0,st.knobs.temp-7)*st.contam*.08;const doseOver=Math.max(0,st.knobs.dose-7)*4;const pressureOver=Math.max(0,st.knobs.pressure-6)*st.drift*.08;const flowBenefit=Math.max(0,st.knobs.flow-5)*1.4;const penalty=st.contam*.28+st.drift*.34+tempOver+doseOver+pressureOver-flowBenefit;const yieldValue=clamp(100-recipeError-penalty+(st.unlock?3:0),0,100);const throughput=clamp(100-st.cost/12-Math.max(0,st.knobs.flow-6)*5,0,100);return{yieldValue,throughput,recipeError,ready:yieldValue>=l.target,clean:st.contam<55,stable:st.drift<60,economic:throughput>=35}}
 function adjust(delta){if(ended)return;const id=KNOBS[st.selected].id;st.knobs[id]=clamp(st.knobs[id]+delta,0,10);st.audited=false;st.estimate=null;draw()}
 function inspect(){if(ended||st.inspections<=0)return log('No inspections left.','Commit a wafer or use the engineer recovery.');st.inspections--;const m=metrics(),spread=Math.max(2,Math.round(8-st.level*.7));st.audited=true;st.estimate=[clamp(Math.round(m.yieldValue-spread),0,100),clamp(Math.round(m.yieldValue+spread),0,100)];log(`Metrology range: ${st.estimate[0]}–${st.estimate[1]}% yield.`,`${lot().hint} ${lot().window}`);draw()}
 function maintain(){if(ended||st.cost>640)return log('Maintenance budget constrained.','The line cannot absorb another full clean.');st.cost+=180;st.contam=Math.max(0,st.contam-22);st.drift=Math.max(4,st.drift-12);st.audited=false;st.estimate=null;log('Chamber cleaned.','Contamination and drift fell, but cost increased and throughput was lost.');draw()}
 function run(){if(ended||st.wafers<=0)return;const m=metrics(),l=lot();st.wafers--;st.last=m.yieldValue;st.contam=clamp(st.contam+5+Math.max(0,st.knobs.temp-6)*1.5-Math.max(0,st.knobs.flow-5)*.8,0,100);st.drift=clamp(st.drift+3+Math.max(0,st.knobs.pressure-6)*1.7,0,100);st.cost+=70;st.audited=false;st.estimate=null;const pass=m.ready&&m.clean&&m.stable;if(pass){st.trust=clamp(st.trust+5,0,100);st.score+=Math.round(m.yieldValue*10+st.wafers*35+m.throughput*2);if(st.score>=2600)st.unlock=true;if(st.level===LOTS.length-1)return finish(true,`Qualification complete with ${st.score} points.`);st.level++;st.wafers=lot().wafers+(st.unlock?1:0);st.knobs=nominal();st.inspections=2;st.contam=Math.max(10,st.contam-8);log('Lot qualified.',`Yield ${Math.round(m.yieldValue)}% cleared every release gate. The next lot has a tighter window.`);draw();return}st.trust=clamp(st.trust-12,0,100);st.score=Math.max(0,st.score-140);const failed=[];if(!m.ready)failed.push(`yield below ${l.target}%`);if(!m.clean)failed.push('contamination gate');if(!m.stable)failed.push('drift gate');log('Wafer scrapped.',`Release failed: ${failed.join(', ')}.`);if(st.wafers<=0||st.trust<=18)return finish(false,'The qualification campaign stopped after repeated yield loss.');draw()}
 function recover(){if(ended||!st.engineer)return log('Engineer unavailable.','The one session intervention has already been used.');st.engineer=false;st.cost+=260;st.trust=Math.max(0,st.trust-5);st.inspections+=1;st.contam=Math.max(0,st.contam-14);st.drift=Math.max(3,st.drift-10);st.knobs={...lot().ideal};st.audited=true;const m=metrics();st.estimate=[Math.max(0,Math.round(m.yieldValue-3)),Math.min(100,Math.round(m.yieldValue+3))];log('Process engineer intervened.','The recipe was centered on the current lot and one inspection returned, but cost and trust consequences remain.');draw()}
 function finish(win,msg){ended=true;log(win?'Fab qualification complete.':'Line halted.',msg);draw()}
 function log(a,b){$('.fc-log',root).innerHTML=`<strong>${a}</strong><p>${b}</p>`}
 function draw(){const m=metrics(),l=lot();$$('[data-h]',root).forEach((e,i)=>e.textContent=[`${st.level+1}/6`,st.wafers,`${Math.round(st.last||m.yieldValue)}%`,Math.round(st.trust),`$${st.cost}`,st.score][i]);$('[data-set]',root).textContent=l.name;$('[data-title]',root).textContent=`Target yield ${l.target}%`;$('[data-hint]',root).textContent=st.unlock?'Advanced endpoint control unlocked: +3 predicted yield and one extra wafer per new lot.':l.window;$('[data-knobs]',root).innerHTML=KNOBS.map((k,i)=>`<div class="fc-knob" data-selected="${i===st.selected}"><div class="fc-row"><strong>${i+1}. ${k.label}</strong>${i===st.selected?'<span>Selected</span>':''}</div><p class="fc-range">${k.effect}</p><div class="fc-stepper"><button data-k="${i}" data-d="-1" aria-label="Decrease ${k.label}">−</button><output>${st.knobs[k.id]}</output><button data-k="${i}" data-d="1" aria-label="Increase ${k.label}">+</button></div></div>`).join('');$('[data-yield]',root).textContent=st.audited&&st.estimate?`${st.estimate[0]}–${st.estimate[1]}%`:`~${Math.round(m.yieldValue/5)*5}%`;$('[data-range]',root).textContent=st.audited?'Audited range reflects current recipe and tool condition.':'Unaudited estimate is rounded; inspect to reveal uncertainty and the dominant process clue.';$('[data-meter]',root).style.width=`${m.yieldValue}%`;$('[data-contam]',root).textContent=Math.round(st.contam);$('[data-drift]',root).textContent=Math.round(st.drift);$('[data-throughput]',root).textContent=`${Math.round(m.throughput)}%`;$('[data-gates]',root).innerHTML=[[`Yield ≥ ${l.target}%`,m.ready],['Contamination < 55',m.clean],['Drift < 60',m.stable],['Throughput ≥ 35%',m.economic]].map(([label,pass])=>`<div class="fc-gate" data-pass="${pass}">${pass?'✓':'○'} ${label}</div>`).join('');$('.fc-wafer',root).dataset.risk=(!m.clean||!m.stable)?'high':'normal';$$('[data-k]',root).forEach(b=>b.addEventListener('click',()=>{st.selected=+b.dataset.k;adjust(+b.dataset.d)}));$$('[data-a]',root).forEach(b=>{const a=b.dataset.a;b.disabled=(ended&&a!=='restart')||(a==='run'&&st.wafers<=0)||(a==='inspect'&&st.inspections<=0)||(a==='maintain'&&st.cost>640)||(a==='recover'&&!st.engineer);b.onclick=()=>({run,inspect,maintain,recover,restart:reset}[a]||(()=>{}))()})}
 keyHandler=e=>{if(!dialog.open)return;if(['1','2','3','4'].includes(e.key)){st.selected=+e.key-1;draw()}else if(e.key==='ArrowUp'){e.preventDefault();adjust(1)}else if(e.key==='ArrowDown'){e.preventDefault();adjust(-1)}else if(e.key.toLowerCase()==='i')inspect();else if(e.key.toLowerCase()==='m')maintain();else if(e.key==='Enter')run()};document.addEventListener('keydown',keyHandler);
 closeHandler=()=>{document.removeEventListener('keydown',keyHandler);dialog.removeEventListener('close',closeHandler)};dialog.addEventListener('close',closeHandler);reset()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
