(() => {
'use strict';
const APP={name:'Fabline Control',emoji:'◫',category:'play',version:'1.0.0',summary:'Run six semiconductor lots through drifting tools while balancing yield, throughput, contamination, cost, and maintenance.',description:'A local-only semiconductor process-control strategy game with six production lots, tool drift, contamination, hidden faults, limited inspections, maintenance tradeoffs, adaptive targets, failure, recovery, session progression, keyboard and touch controls, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const KNOBS=[['temp','Temperature'],['dose','Exposure dose'],['pressure','Chamber pressure'],['flow','Gas flow']];
const LOTS=[
{name:'Lot 1 · Baseline logic',target:72,wafers:5,drift:'temp',hint:'The chamber is running slightly cool.'},
{name:'Lot 2 · Dense memory',target:75,wafers:5,drift:'dose',hint:'Critical dimensions are widening.'},
{name:'Lot 3 · Low-power node',target:78,wafers:4,drift:'pressure',hint:'Sidewall profiles are becoming uneven.'},
{name:'Lot 4 · Mixed product',target:81,wafers:4,drift:'flow',hint:'Across-wafer uniformity is slipping.'},
{name:'Lot 5 · Tool aging',target:84,wafers:3,drift:'temp',hint:'Residue is accelerating chamber drift.'},
{name:'Lot 6 · Qualification run',target:87,wafers:3,drift:'dose',hint:'The process window is narrow and unforgiving.'}
];
function style(){if($('#fabline-control-style'))return;const e=document.createElement('style');e.id='fabline-control-style';e.textContent=`
.fabline{max-width:1120px;display:grid;gap:12px}.fc-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.fc-stat,.fc-panel{border:1px solid var(--line);border-radius:17px;background:#fff}.fc-stat{padding:9px}.fc-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.fc-layout{display:grid;grid-template-columns:1.05fr .95fr;gap:12px}.fc-panel{padding:15px}.fc-lot{padding:16px;border-radius:18px;background:linear-gradient(135deg,#0c2338,#155e75);color:#fff}.fc-wafer{width:180px;aspect-ratio:1;border-radius:50%;margin:14px auto;background:radial-gradient(circle at 35% 30%,#d9fbff,#79cbd3 42%,#124e63 70%,#092d40);box-shadow:inset -15px -18px 30px #06253866,0 12px 28px #0a516044;position:relative;overflow:hidden}.fc-wafer:after{content:'';position:absolute;inset:14%;background:repeating-linear-gradient(90deg,#ffffff33 0 2px,transparent 2px 14px),repeating-linear-gradient(0deg,#ffffff22 0 2px,transparent 2px 14px);border-radius:50%;transform:rotate(8deg)}.fc-knobs{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.fc-knob{border:1px solid var(--line);border-radius:13px;padding:10px}.fc-stepper{display:grid;grid-template-columns:42px 1fr 42px;gap:6px;align-items:center;margin-top:7px}.fc-stepper button,.fc-actions button{min-height:42px;border:1px solid var(--line);border-radius:10px;background:#fff;font-weight:900}.fc-stepper output{text-align:center;font-weight:900}.fc-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.fc-actions .primary{background:#d8f3f5;border-color:#155e75}.fc-stepper button:focus-visible,.fc-actions button:focus-visible{outline:3px solid #155e75;outline-offset:2px}.fc-row{display:flex;justify-content:space-between;gap:10px;margin:7px 0}.fc-meter{height:10px;background:#e6eef0;border-radius:99px;overflow:hidden}.fc-meter span{display:block;height:100%;background:#167d8c;transition:width .25s}.fc-log{min-height:112px}.fc-hint{font-size:.82rem;color:var(--muted)}.fc-good{color:#176642}.fc-bad{color:#9a3e26}
@media(max-width:840px){.fc-layout{grid-template-columns:1fr}.fc-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.fc-hud{grid-template-columns:repeat(2,1fr)}.fc-knobs,.fc-actions{grid-template-columns:1fr}.fc-stepper{grid-template-columns:48px 1fr 48px}.fc-wafer{width:145px}}@media(prefers-reduced-motion:reduce){.fabline *{animation:none!important;transition:none!important}}
`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-fabline-control]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true),a=$('.app-card',f);a.dataset.fablineControl='1';a.dataset.category=APP.category;$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-fabline-control]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.fcBound)return;b.dataset.fcBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · process control';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
 const root=document.createElement('section');root.className='tool-panel fabline';root.innerHTML=`<div class="fc-hud">${['Lot','Wafers','Yield','Trust','Cost','Score'].map((x,i)=>`<div class="fc-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="fc-layout"><section class="fc-panel"><div class="fc-lot"><p class="app-meta" data-set></p><h3 data-title></h3><p data-hint></p></div><div class="fc-wafer" aria-hidden="true"></div><div class="fc-knobs" data-knobs></div><p class="fc-hint">Keyboard: 1-4 select a process knob, ↑/↓ adjust, I inspect, Enter run wafer.</p></section><aside class="fc-panel"><div class="result-card fc-log" aria-live="polite"></div><div class="fc-row"><span>Predicted yield</span><strong data-yield></strong></div><div class="fc-meter"><span data-meter></span></div><div class="fc-row"><span>Contamination</span><strong data-contam></strong></div><div class="fc-row"><span>Tool drift</span><strong data-drift></strong></div><div class="fc-row"><span>Throughput</span><strong data-throughput></strong></div><div class="fc-actions"><button class="primary" data-a="run">Run wafer</button><button data-a="inspect">Inspect sample</button><button data-a="maintain">Clean chamber</button><button data-a="recover">Call process engineer</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
 let st,ended=false,keyHandler,closeHandler;
 const nominal=()=>({temp:5,dose:5,pressure:5,flow:5});
 function reset(){st={level:0,wafers:LOTS[0].wafers,trust:72,cost:0,score:0,knobs:nominal(),selected:0,contam:8,drift:18,inspections:2,engineer:true,unlock:false,last:0};ended=false;log('Line ready.','Tune the process, inspect sparingly, and preserve enough wafers to qualify each lot.');draw()}
 function lot(){return LOTS[st.level]}
 function quality(){const l=lot(),target={temp:5,dose:5,pressure:5,flow:5};target[l.drift]=7;const error=KNOBS.reduce((n,[id])=>n+Math.abs(st.knobs[id]-target[id])*7,0);const penalty=st.contam*.32+st.drift*.38;const stability=100-error-penalty;return clamp(stability+(st.unlock?3:0),0,100)}
 function adjust(delta){if(ended)return;const id=KNOBS[st.selected][0];st.knobs[id]=clamp(st.knobs[id]+delta,0,10);draw()}
 function inspect(){if(ended||st.inspections<=0)return log('No inspections left.','Commit a wafer or use the engineer recovery.');st.inspections--;const q=quality();log(`Metrology estimate: ${Math.round(q)}% yield.`,`${lot().hint} ${KNOBS.find(k=>k[0]===lot().drift)[1]} is the strongest lever.`);draw()}
 function maintain(){if(ended||st.cost>640)return log('Maintenance budget constrained.','The line cannot absorb another full clean.');st.cost+=180;st.contam=Math.max(0,st.contam-22);st.drift=Math.max(4,st.drift-12);log('Chamber cleaned.','Contamination and drift fell, but cost increased and throughput was lost.');draw()}
 function run(){if(ended||st.wafers<=0)return;const q=quality(),l=lot();st.wafers--;st.last=q;st.contam=clamp(st.contam+7,0,100);st.drift=clamp(st.drift+4,0,100);st.cost+=70;const pass=q>=l.target;if(pass){st.trust=clamp(st.trust+5,0,100);st.score+=Math.round(q*10+st.wafers*35-Math.max(0,st.cost-300)*.2);if(st.score>=2600)st.unlock=true;if(st.level===LOTS.length-1)return finish(true,`Qualification complete with ${st.score} points.`);st.level++;st.wafers=lot().wafers+(st.unlock?1:0);st.knobs=nominal();st.inspections=2;st.contam=Math.max(10,st.contam-8);log('Lot qualified.',`Yield ${Math.round(q)}% cleared target. The next lot has a tighter window.`);draw();return}st.trust=clamp(st.trust-12,0,100);st.score=Math.max(0,st.score-140);log('Wafer scrapped.',`Yield ${Math.round(q)}% missed the ${l.target}% target.`);if(st.wafers<=0||st.trust<=18)return finish(false,'The qualification campaign stopped after repeated yield loss.');draw()}
 function recover(){if(ended||!st.engineer)return log('Engineer unavailable.','The one session intervention has already been used.');st.engineer=false;st.cost+=260;st.trust=Math.max(0,st.trust-5);st.inspections+=1;st.contam=Math.max(0,st.contam-14);st.drift=Math.max(3,st.drift-10);st.knobs=nominal();st.knobs[lot().drift]=7;log('Process engineer intervened.','Nominal settings were restored and one inspection returned, but cost and trust consequences remain.');draw()}
 function finish(win,msg){ended=true;log(win?'Fab qualification complete.':'Line halted.',msg);draw()}
 function log(a,b){$('.fc-log',root).innerHTML=`<strong>${a}</strong><p>${b}</p>`}
 function draw(){const q=quality();$$('[data-h]',root).forEach((e,i)=>e.textContent=[`${st.level+1}/6`,st.wafers,`${Math.round(st.last||q)}%`,Math.round(st.trust),`$${st.cost}`,st.score][i]);$('[data-set]',root).textContent=lot().name;$('[data-title]',root).textContent=`Target yield ${lot().target}%`;$('[data-hint]',root).textContent=st.unlock?'Advanced endpoint control unlocked: +3 predicted yield and one extra wafer per new lot.':'Each wafer raises contamination and tool drift.';$('[data-knobs]',root).innerHTML=KNOBS.map(([id,label],i)=>`<div class="fc-knob"><div class="fc-row"><strong>${i+1}. ${label}</strong>${i===st.selected?'<span>Selected</span>':''}</div><div class="fc-stepper"><button data-k="${i}" data-d="-1" aria-label="Decrease ${label}">−</button><output>${st.knobs[id]}</output><button data-k="${i}" data-d="1" aria-label="Increase ${label}">+</button></div></div>`).join('');$('[data-yield]',root).textContent=`${Math.round(q)}%`;$('[data-meter]',root).style.width=`${q}%`;$('[data-contam]',root).textContent=Math.round(st.contam);$('[data-drift]',root).textContent=Math.round(st.drift);$('[data-throughput]',root).textContent=`${Math.max(0,100-st.cost/12).toFixed(0)}%`;$$('[data-k]',root).forEach(b=>b.addEventListener('click',()=>{st.selected=+b.dataset.k;adjust(+b.dataset.d)}));$$('[data-a]',root).forEach(b=>{b.disabled=ended&&b.dataset.a!=='restart';b.onclick=()=>({run,inspect,maintain,recover,restart:reset}[b.dataset.a]||(()=>{}))()})}
 keyHandler=e=>{if(!dialog.open)return;if(['1','2','3','4'].includes(e.key)){st.selected=+e.key-1;draw()}else if(e.key==='ArrowUp'){e.preventDefault();adjust(1)}else if(e.key==='ArrowDown'){e.preventDefault();adjust(-1)}else if(e.key.toLowerCase()==='i')inspect();else if(e.key==='Enter')run()};document.addEventListener('keydown',keyHandler);
 closeHandler=()=>{document.removeEventListener('keydown',keyHandler);dialog.removeEventListener('close',closeHandler)};dialog.addEventListener('close',closeHandler);reset()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();