(()=> {
  const APP={name:'Festival Flow',emoji:'🎪',category:'play',version:'1.0.0',summary:'Guide festival crowds with signs, shade, medics, and gates before congestion turns unsafe.',description:'A local crowd-flow strategy simulation with moving guests, drag-to-place amenities, budget tradeoffs, heat and patience pressure, wave goals, unlockable night rush, scoring, responsive canvas rendering, touch and keyboard controls, optional local audio, reduced-motion behavior, and teardown.'};
  const label=v=>v==='play'?'Play':v==='useful'?'Useful':'Experiment';
  const $=s=>document.querySelector(s);
  function style(){if($('#festival-flow-styles'))return;const s=document.createElement('style');s.id='festival-flow-styles';s.textContent=`
.festival-card{animation:festival-pop .25s ease both}.festival-game{max-width:1040px;gap:14px}.festival-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.festival-stat{border:1px solid var(--line);border-radius:15px;background:white;padding:10px 12px}.festival-stat span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.festival-stat strong{display:block;margin-top:4px}.festival-board{position:relative;border:0;border-radius:26px;background:#08121d;color:white;padding:0;overflow:hidden;touch-action:none;box-shadow:inset 0 0 0 1px rgba(255,255,255,.14)}.festival-board:focus-visible{outline:4px solid var(--accent);outline-offset:4px}.festival-board canvas{display:block;width:100%;height:min(58vh,500px);min-height:360px}.festival-console{display:grid;grid-template-columns:1fr 1fr;gap:10px}.festival-panel{border:1px solid var(--line);border-radius:18px;background:#fff;padding:13px}.festival-tools,.festival-legend{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.festival-chip,.festival-legend span{border:1px solid var(--line);border-radius:999px;background:#fff;color:var(--ink);padding:8px 11px;font-weight:900}.festival-chip.is-active{background:#111827;color:#fff}.festival-log{min-height:92px;padding:17px 19px}@media(max-width:760px){.festival-hud{grid-template-columns:repeat(2,1fr)}.festival-console{grid-template-columns:1fr}.festival-board canvas{height:56vh;min-height:340px}}@media(prefers-reduced-motion:reduce){.festival-card{animation:none}.festival-board canvas{min-height:330px}}@keyframes festival-pop{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}`;document.head.append(s);}
  function addCard(){const grid=$('#app-grid'),tpl=$('#app-card-template');if(!grid||!tpl||$('[data-festival-card]'))return;const f=$('.filter.is-active')?.dataset.filter||'all';if(f!=='all'&&f!==APP.category)return;style();const node=tpl.content.cloneNode(true),card=node.querySelector('.app-card');card.dataset.category=APP.category;card.dataset.festivalCard='true';card.classList.add('festival-card');node.querySelector('.app-icon').textContent=APP.emoji;node.querySelector('.app-meta').textContent=`${label(APP.category)} · v${APP.version}`;node.querySelector('.app-name').textContent=APP.name;node.querySelector('.app-summary').textContent=APP.summary;const btn=node.querySelector('.app-card-button');btn.setAttribute('aria-label',`Open ${APP.name}`);btn.addEventListener('click',open);grid.append(node);}
  function boot(){style();addCard();document.querySelectorAll('.filter').forEach(b=>{if(b.dataset.festivalRefresh)return;b.dataset.festivalRefresh='1';b.addEventListener('click',()=>setTimeout(addCard,0));});}
  function open(){const dialog=$('#app-dialog'),stage=$('#app-stage'),title=$('#dialog-title'),cat=$('#dialog-category'),desc=$('#dialog-description'),fb=$('#dialog-feedback');if(!dialog||!stage)return;title.textContent=APP.name;cat.textContent=`${label(APP.category)} · ${APP.emoji}`;desc.textContent=APP.description;fb.href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Festival%20Flow';stage.replaceChildren();game(stage,dialog);dialog.showModal();}
  function game(stage,dialog){
    const root=document.createElement('section');root.className='tool-panel festival-game';
    const hud=document.createElement('div');hud.className='festival-hud';hud.innerHTML='<div class="festival-stat"><span>Wave</span><strong id="ff-wave">1 / 5</strong></div><div class="festival-stat"><span>Budget</span><strong id="ff-budget">10</strong></div><div class="festival-stat"><span>Guests safe</span><strong id="ff-safe">0</strong></div><div class="festival-stat"><span>Comfort</span><strong id="ff-comfort">100</strong></div><div class="festival-stat"><span>Incidents</span><strong id="ff-incidents">0</strong></div><div class="festival-stat"><span>Score</span><strong id="ff-score">0</strong></div>';
    const board=document.createElement('button');board.type='button';board.className='festival-board';board.setAttribute('aria-label','Festival Flow map. Use arrows to move the cursor, one through five to choose signs, shade, medic, gate, or clear, Enter to place, Space to start a wave, and N for a new festival.');board.innerHTML='<canvas aria-hidden="true"></canvas>';
    const con=document.createElement('div');con.className='festival-console';con.innerHTML='<div class="festival-panel"><strong>Build plan</strong><p>Guests enter from the west and need a safe route to the stage, water, and exits. Signs steer, shade cools, medics recover incidents, and gates relieve chokepoints.</p><div class="festival-tools"></div></div><div class="festival-panel"><strong>Pressure</strong><div class="festival-legend"><span>Signs: 2</span><span>Shade: 3</span><span>Medic: 4</span><span>Gate: 3</span><span>Night rush after 850</span></div></div>';
    const log=document.createElement('div');log.className='result-card festival-log';log.setAttribute('aria-live','polite');const foot=document.createElement('div');foot.className='tool-actions';root.append(hud,board,con,log,foot);stage.append(root);
    const canvas=board.querySelector('canvas'),ctx=canvas.getContext('2d'),tools=con.querySelector('.festival-tools'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
    const state={rows:5,cols:9,cursor:22,tool:'sign',wave:1,waves:5,budget:10,safe:0,comfort:100,incidents:0,score:0,night:false,running:false,guests:[],builds:[],raf:0,last:0,audio:false,ac:null};
    [['sign','Sign'],['shade','Shade'],['medic','Medic'],['gate','Gate'],['clear','Clear']].forEach(([id,txt])=>{const b=btn(txt,()=>{state.tool=id;paint();draw();},true);b.classList.add('festival-chip');b.dataset.tool=id;tools.append(b);});
    foot.append(btn('Start wave',start,true),btn('New festival',reset,true),btn('Night rush',night,true),btn('Sound off',sound,true));
    board.addEventListener('click',tap);board.addEventListener('pointermove',point);board.addEventListener('keydown',key);dialog.addEventListener('close',tear,{once:true});
    function btn(t,f,sec){const b=document.createElement('button');b.type='button';b.className=sec?'button button-secondary':'button';b.textContent=t;b.addEventListener('click',f);return b}
    function say(h){log.innerHTML=h}
    function cell(i){return [i%state.cols,Math.floor(i/state.cols)]} function idx(x,y){return y*state.cols+x}
    function buildAt(i){return state.builds.find(b=>b.i===i)}
    function cost(t){return t==='sign'?2:t==='shade'?3:t==='medic'?4:t==='gate'?3:0}
    function paint(){tools.querySelectorAll('.festival-chip').forEach(b=>b.classList.toggle('is-active',b.dataset.tool===state.tool));hud.querySelector('#ff-wave').textContent=`${state.wave} / ${state.waves}`;hud.querySelector('#ff-budget').textContent=state.budget;hud.querySelector('#ff-safe').textContent=state.safe;hud.querySelector('#ff-comfort').textContent=Math.max(0,Math.round(state.comfort));hud.querySelector('#ff-incidents').textContent=state.incidents;hud.querySelector('#ff-score').textContent=state.score}
    function place(){const existing=buildAt(state.cursor);if(state.tool==='clear'){if(existing){state.builds=state.builds.filter(b=>b!==existing);state.budget++;say('<strong>Cell cleared.</strong><small>One budget returned for recovery.</small>');beep(240)}paint();draw();return}if(existing){say('<strong>Already occupied.</strong><small>Clear that cell or build somewhere else.</small>');return}const c=cost(state.tool);if(state.budget<c){say('<strong>Budget is short.</strong><small>Finish waves safely to earn more capacity.</small>');return}state.budget-=c;state.builds.push({i:state.cursor,type:state.tool,pulse:0});say(`<strong>${state.tool} placed.</strong><small>Start the wave when the route looks ready.</small>`);paint();draw()}
    function start(){if(state.running)return;state.running=true;const total=9+state.wave*3+(state.night?5:0);for(let k=0;k<total;k++)state.guests.push({x:-k*.38,y:1+(k%3),want:k%3,heat:0,patience:100,served:false,speed:.020+Math.random()*.01});say(`<strong>Wave ${state.wave} opened.</strong><small>Watch for heat, clumps, and missed service stops.</small>`);loop(0)}
    function nearest(type,g){let best=null,dist=99;for(const b of state.builds.filter(x=>x.type===type)){const [x,y]=cell(b.i),d=Math.abs(x-g.x)+Math.abs(y-g.y);if(d<dist){best=b;dist=d}}return best&&dist<3?best:null}
    function step(){for(const g of state.guests){const sign=nearest('sign',g),shade=nearest('shade',g),med=nearest('medic',g),gate=nearest('gate',g);let targetY=g.want===0?1:g.want===1?2:3;if(sign){const [,sy]=cell(sign.i);targetY=sy;sign.pulse=10}if(shade){g.heat=Math.max(0,g.heat-1.2);shade.pulse=8}else g.heat+=state.night?.18:.34;if(med&&g.heat>55){g.heat-=2.4;g.patience+=.8;med.pulse=9}const crowd=state.guests.filter(o=>Math.abs(o.x-g.x)<.35&&Math.abs(o.y-g.y)<.55).length;g.patience-=crowd>2?.75:.12;g.y+=(targetY-g.y)*.035;g.x+=g.speed+(gate?.03||0)-(crowd>3?.012:0);if(g.x>3.8&&g.x<4.8&&!g.served){g.served=true;state.score+=14;state.comfort+=.5}if(g.heat>85||g.patience<8){state.incidents++;state.comfort-=8;g.heat=48;g.patience=40;beep(150)}}state.builds.forEach(b=>b.pulse=Math.max(0,b.pulse-1));const before=state.guests.length;state.guests=state.guests.filter(g=>{if(g.x>state.cols){state.safe++;state.score+=24+Math.round(g.patience/8)-Math.round(g.heat/12);return false}return true});if(before&&!state.guests.length){state.running=false;state.budget+=4;state.comfort-=state.incidents*1.5;if(state.comfort<=0){say('<strong>The festival lost flow.</strong><small>Start a new festival and open more gates before crowds bunch up.</small>')}else if(state.wave>=state.waves){state.score+=Math.max(0,Math.round(state.comfort))*3-state.incidents*10;say(`<strong>Festival closed safely: ${state.score}.</strong><small>${state.score>=850?'Night rush is unlocked for this session.':'Score 850 to unlock night rush.'}</small>`)}else{state.wave++;say('<strong>Wave cleared.</strong><small>Budget restored. Add service points before the next arrival surge.</small>')}}paint()}
    function loop(t){if(!state.running)return;state.raf=requestAnimationFrame(loop);if(reduced&&t-state.last<90)return;state.last=t;step();draw()}
    function night(){if(state.score<850&&!state.night){say('<strong>Night rush locked.</strong><small>Score 850 in a festival to add larger, hotter crowds.</small>');return}state.night=!state.night;reset();say(`<strong>${state.night?'Night':'Day'} festival ready.</strong><small>${state.night?'More guests arrive with less comfort margin.':'Standard crowd pressure restored.'}</small>`)}
    function reset(){Object.assign(state,{cursor:22,wave:1,budget:10,safe:0,comfort:100,incidents:0,score:0,running:false,guests:[],builds:[]});cancelAnimationFrame(state.raf);say('<strong>Festival gates ready.</strong><small>Place service points, then start the first crowd wave.</small>');paint();draw()}
    function locate(e){const r=board.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)/r.width*state.cols),y=Math.floor((e.clientY-r.top)/r.height*state.rows);if(x>=0&&x<state.cols&&y>=0&&y<state.rows){state.cursor=idx(x,y);return true}return false}
    function point(e){if(locate(e))draw()} function tap(e){locate(e);place()}
    function key(e){const k=e.key.toLowerCase(),[x,y]=cell(state.cursor);if(k==='arrowright'){e.preventDefault();state.cursor=idx(Math.min(state.cols-1,x+1),y)}if(k==='arrowleft'){e.preventDefault();state.cursor=idx(Math.max(0,x-1),y)}if(k==='arrowdown'){e.preventDefault();state.cursor=idx(x,Math.min(state.rows-1,y+1))}if(k==='arrowup'){e.preventDefault();state.cursor=idx(x,Math.max(0,y-1))}if(k==='1')state.tool='sign';if(k==='2')state.tool='shade';if(k==='3')state.tool='medic';if(k==='4')state.tool='gate';if(k==='5')state.tool='clear';if(k==='backspace'||k==='delete'){e.preventDefault();state.tool='clear';place()}if(k==='enter'){e.preventDefault();place()}if(k===' '){e.preventDefault();start()}if(k==='n'){e.preventDefault();reset()}paint();draw()}
    function sound(e){const b=e.currentTarget,AC=window.AudioContext||window.webkitAudioContext;if(!AC){say('<strong>Sound is not available here.</strong><small>The simulation still runs silently.</small>');return}state.audio=!state.audio;b.textContent=state.audio?'Sound on':'Sound off';b.setAttribute('aria-pressed',String(state.audio));if(state.audio){state.ac ||= new AC();state.ac.resume();beep(440)}}
    function beep(f){if(!state.audio||!state.ac)return;const n=state.ac.currentTime,o=state.ac.createOscillator(),g=state.ac.createGain();o.frequency.value=f;g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(.04,n+.02);g.gain.exponentialRampToValueAtTime(.0001,n+.13);o.connect(g).connect(state.ac.destination);o.start(n);o.stop(n+.15)}
    function size(){const dpr=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=Math.max(1,r.width*dpr);canvas.height=Math.max(1,r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);return r}
    function draw(){const r=size(),cw=r.width/state.cols,ch=r.height/state.rows;ctx.clearRect(0,0,r.width,r.height);ctx.fillStyle=state.night?'#060914':'#08121d';ctx.fillRect(0,0,r.width,r.height);ctx.fillStyle='rgba(191,231,209,.16)';ctx.fillRect(4*cw,0,cw,state.rows*ch);ctx.fillStyle='rgba(255,111,74,.2)';ctx.fillRect(8*cw,0,cw,state.rows*ch);for(let y=0;y<state.rows;y++)for(let x=0;x<state.cols;x++){ctx.strokeStyle='rgba(255,255,255,.13)';ctx.strokeRect(x*cw,y*ch,cw,ch)}ctx.fillStyle='#fff2bd';ctx.font='bold 13px sans-serif';ctx.textAlign='center';ctx.fillText('stage',4.5*cw,18);ctx.fillText('exit',8.5*cw,18);const [cx,cy]=cell(state.cursor);ctx.strokeStyle='#f8e08e';ctx.lineWidth=4;ctx.strokeRect(cx*cw+4,cy*ch+4,cw-8,ch-8);for(const b of state.builds){const [x,y]=cell(b.i),px=(x+.5)*cw,py=(y+.5)*ch,rad=Math.min(cw,ch)*(.24+b.pulse*.008);ctx.fillStyle=b.type==='sign'?'#93c5fd':b.type==='shade'?'#86efac':b.type==='medic'?'#fca5a5':'#fdba74';ctx.beginPath();ctx.arc(px,py,rad,0,7);ctx.fill();ctx.fillStyle='#08121d';ctx.font='bold 17px sans-serif';ctx.textBaseline='middle';ctx.fillText(b.type==='sign'?'S':b.type==='shade'?'H':b.type==='medic'?'M':'G',px,py)}for(const g of state.guests){const px=(g.x+.5)*cw,py=(g.y+.5)*ch;ctx.fillStyle=g.heat>70||g.patience<20?'#f87171':g.served?'#bfe7d1':'#fffdf7';ctx.beginPath();ctx.arc(px,py,Math.max(5,Math.min(cw,ch)*.12),0,7);ctx.fill();ctx.strokeStyle='rgba(0,0,0,.25)';ctx.stroke()} }
    function tear(){cancelAnimationFrame(state.raf);if(state.ac)state.ac.close().catch(()=>{});board.removeEventListener('click',tap);board.removeEventListener('pointermove',point);board.removeEventListener('keydown',key)}
    reset();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
