(() => {
  const APP={name:'Floodgate Ferry',emoji:'⛴️',category:'play',version:'1.0.0',summary:'Guide ferries through rotating floodgates before tide, hull, and passenger patience run out.',description:'A local spatial routing strategy game with rotatable current gates, moving ferries, cargo-specific exits, tide steps, limited rudder actions, hull damage, patience pressure, repair choices, adaptive contracts, session-only storm lock unlock, touch and keyboard controls, reduced-motion behavior, optional local audio, and teardown.'};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const label=v=>v==='play'?'Play':v==='useful'?'Useful':'Experiment';
  function styles(){if($('#floodgate-ferry-styles'))return;const st=document.createElement('style');st.id='floodgate-ferry-styles';st.textContent=`.fgf-card{animation:fgf-rise .22s ease both}.fgf-game{max-width:1120px;gap:14px}.fgf-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.fgf-stat,.fgf-map,.fgf-panel{border:1px solid var(--line);border-radius:18px;background:#fff}.fgf-stat{padding:10px 12px}.fgf-stat span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.fgf-stat strong{display:block;margin-top:4px}.fgf-layout{display:grid;grid-template-columns:1.05fr .95fr;gap:12px}.fgf-map{padding:12px;background:linear-gradient(135deg,#dbeafe,#ecfeff);touch-action:none}.fgf-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:6px;max-width:540px;margin:auto}.fgf-cell,.fgf-mode button,.fgf-actions button{min-height:58px;border:1px solid #bae6fd;border-radius:14px;background:#eff6ff;font-weight:900;position:relative;display:grid;place-items:center}.fgf-cell:focus-visible,.fgf-mode button:focus-visible,.fgf-actions button:focus-visible{outline:4px solid var(--accent);outline-offset:2px}.fgf-cell.hot{box-shadow:inset 0 0 0 3px #0369a1}.fgf-cell.rock{background:repeating-linear-gradient(45deg,#a8a29e 0 8px,#d6d3d1 8px 16px);color:#44403c}.fgf-cell.exit-east{border-right:6px solid #22c55e}.fgf-cell.exit-north{border-top:6px solid #a855f7}.fgf-cell.exit-south{border-bottom:6px solid #f97316}.fgf-boat{position:absolute;inset:7px;border-radius:999px;display:grid;place-items:center;background:white;box-shadow:0 8px 20px rgba(14,116,144,.2);font-size:1.25rem}.fgf-panel{padding:14px;display:grid;gap:12px}.fgf-mode,.fgf-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.fgf-mode button{background:white}.fgf-mode button.is-active{box-shadow:0 0 0 3px #7dd3fc inset}.fgf-contract,.fgf-queue{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.fgf-chip,.fgf-rule{border:1px solid var(--line);border-radius:14px;padding:10px;background:#f8fafc}.fgf-chip strong,.fgf-rule strong{display:block}.fgf-rule.done{background:#dcfce7}.fgf-log{min-height:104px;padding:17px 19px}.fgf-legend{font-size:.88rem;color:var(--muted)}@media(max-width:880px){.fgf-hud{grid-template-columns:repeat(2,1fr)}.fgf-layout{grid-template-columns:1fr}}@media(max-width:520px){.fgf-cell{min-height:46px}.fgf-panel{padding:9px}.fgf-mode,.fgf-actions,.fgf-contract,.fgf-queue{grid-template-columns:1fr 1fr}}@media(prefers-reduced-motion:reduce){.fgf-card{animation:none;transition:none}}@keyframes fgf-rise{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}`;document.head.append(st);}
  function addCard(){const grid=$('#app-grid'),template=$('#app-card-template');if(!grid||!template||$('[data-floodgate-ferry-card]'))return;const f=$('.filter.is-active')?.dataset.filter||'all';if(f!=='all'&&f!==APP.category)return;styles();const node=template.content.cloneNode(true),card=$('.app-card',node);card.dataset.category=APP.category;card.dataset.floodgateFerryCard='true';card.classList.add('fgf-card');$('.app-icon',node).textContent=APP.emoji;$('.app-meta',node).textContent=`${label(APP.category)} · v${APP.version}`;$('.app-name',node).textContent=APP.name;$('.app-summary',node).textContent=APP.summary;const b=$('.app-card-button',node);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);grid.append(node);}
  function boot(){styles();let tries=0;const retry=()=>{addCard();if(!$('[data-floodgate-ferry-card]')&&tries++<20)setTimeout(retry,120)};retry();$$('.filter').forEach(b=>{if(b.dataset.fgfRefresh)return;b.dataset.fgfRefresh='1';b.addEventListener('click',()=>setTimeout(addCard,0));});}
  function open(){const dialog=$('#app-dialog'),stage=$('#app-stage');if(!dialog||!stage)return;$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent=`${label(APP.category)} · ${APP.emoji}`;$('#dialog-description').textContent=APP.description;$('#dialog-feedback').href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Floodgate%20Ferry';stage.replaceChildren();game(stage,dialog);dialog.showModal();}
  function game(stage,dialog){
    const root=document.createElement('section');root.className='tool-panel fgf-game';root.innerHTML=`<div class="fgf-hud"><div class="fgf-stat"><span>Harbor</span><strong id="fgf-mode-name">Morning locks</strong></div><div class="fgf-stat"><span>Tide</span><strong id="fgf-tide">12</strong></div><div class="fgf-stat"><span>Rudders</span><strong id="fgf-rudders">10</strong></div><div class="fgf-stat"><span>Hull</span><strong id="fgf-hull">6</strong></div><div class="fgf-stat"><span>Patience</span><strong id="fgf-patience">8</strong></div><div class="fgf-stat"><span>Score</span><strong id="fgf-score">0</strong></div></div><div class="fgf-layout"><div class="fgf-map"><div class="fgf-grid" role="grid" aria-label="Floodgate grid. Rotate gates, launch ferries, then advance the tide."></div></div><div class="fgf-panel"><div class="fgf-mode" aria-label="Harbor contracts"></div><div><strong>Ferry queue</strong><div class="fgf-queue"></div></div><div><strong>Delivery contract</strong><div class="fgf-contract"></div></div><p class="fgf-legend">Mail exits east. Medicine exits north. Grain exits south. Rocks damage the hull.</p><div class="fgf-actions"><button class="button" data-act="launch" type="button">Launch ferry</button><button class="button" data-act="tide" type="button">Advance tide</button><button class="button button-secondary" data-act="patch" type="button">Patch hull</button><button class="button button-secondary" data-act="reset" type="button">New harbor</button><button class="button button-secondary" data-act="sound" type="button" aria-pressed="false">Sound off</button></div></div></div><div class="result-card fgf-log" aria-live="polite"><strong>Rotate the floodgates.</strong><small>Tap cells or use arrow keys and Enter. Spend rudders before launching the next ferry.</small></div>`;stage.append(root);
    const modes={morning:{name:'Morning locks',tide:12,rudders:10,hull:6,patience:8,quota:{mail:2,med:1,grain:1}},market:{name:'Market rush',tide:11,rudders:9,hull:5,patience:6,quota:{mail:2,med:2,grain:2}},storm:{name:'Storm lock',tide:10,rudders:8,hull:4,patience:5,quota:{mail:3,med:2,grain:2}}};
    const cargo={mail:['mail','✉️','East dock'],med:['med','💊','North dock'],grain:['grain','🌾','South dock']};
    const arrows=['→','↓','←','↑'], dirs=[[0,1],[1,0],[0,-1],[-1,0]];
    const st={mode:'morning',unlocked:false,grid:[],boats:[],queue:[],delivered:{mail:0,med:0,grain:0},tide:12,rudders:10,hull:6,patience:8,score:0,focus:0,sound:false,ac:null,low:matchMedia('(prefers-reduced-motion: reduce)').matches};
    const grid=$('.fgf-grid',root),modeBox=$('.fgf-mode',root),queueBox=$('.fgf-queue',root),contract=$('.fgf-contract',root),log=$('.fgf-log',root);
    const mode=()=>modes[st.mode];
    function tone(kind){if(!st.sound)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;st.ac||=new A();st.ac.resume();const o=st.ac.createOscillator(),g=st.ac.createGain();o.type=kind==='bad'?'sawtooth':'sine';o.frequency.value=kind==='move'?420:kind==='win'?820:180;g.gain.setValueAtTime(.0001,st.ac.currentTime);g.gain.exponentialRampToValueAtTime(.045,st.ac.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,st.ac.currentTime+.15);o.connect(g).connect(st.ac.destination);o.start();o.stop(st.ac.currentTime+.18);}
    function note(m,s='Plan a route before the next tide step.'){log.innerHTML=`<strong>${m}</strong><small>${s}</small>`;}
    function makeQueue(){const q=mode().quota, list=[];Object.keys(q).forEach(k=>{for(let i=0;i<q[k]+1;i++)list.push(k);});return list.sort(()=>Math.random()-.5);}
    function seed(){const rocks=new Set([8,15,22,27]);st.grid=Array.from({length:36},(_,i)=>rocks.has(i)?'rock':Math.floor(Math.random()*4));st.boats=[];st.queue=makeQueue();st.delivered={mail:0,med:0,grain:0};st.tide=mode().tide;st.rudders=mode().rudders;st.hull=mode().hull;st.patience=mode().patience;st.score=0;st.focus=0;note('Harbor reset.','Rotate gates, launch one ferry, then advance tide to carry it.');render();}
    function goals(){return Object.entries(mode().quota).map(([k,v])=>({id:k,label:`${cargo[k][2]}: ${st.delivered[k]} / ${v}`,done:st.delivered[k]>=v}));}
    function render(){const done=goals().filter(g=>g.done).length;$('#fgf-mode-name',root).textContent=mode().name;$('#fgf-tide',root).textContent=st.tide;$('#fgf-rudders',root).textContent=st.rudders;$('#fgf-hull',root).textContent=st.hull;$('#fgf-patience',root).textContent=st.patience;$('#fgf-score',root).textContent=st.score;modeBox.innerHTML='';Object.entries(modes).forEach(([id,m])=>{const b=document.createElement('button');b.type='button';b.textContent=m.name;b.className=id===st.mode?'is-active':'';b.disabled=id==='storm'&&!st.unlocked;b.title=b.disabled?'Deliver all goals once to unlock Storm lock this session.':'';b.addEventListener('click',()=>{st.mode=id;seed();});modeBox.append(b);});queueBox.innerHTML='';st.queue.slice(0,3).forEach(k=>{const e=document.createElement('div');e.className='fgf-chip';e.innerHTML=`<strong>${cargo[k][1]} ${cargo[k][2]}</strong>${k}`;queueBox.append(e);});contract.innerHTML='';goals().forEach(g=>{const e=document.createElement('div');e.className=`fgf-rule${g.done?' done':''}`;e.innerHTML=`<strong>${g.done?'Met':'Open'}</strong>${g.label}`;contract.append(e);});grid.innerHTML='';st.grid.forEach((v,i)=>{const cell=document.createElement('button');cell.type='button';const r=Math.floor(i/6),c=i%6;cell.className=`fgf-cell${v==='rock'?' rock':''}${i===st.focus?' hot':''}${c===5?' exit-east':''}${r===0?' exit-north':''}${r===5?' exit-south':''}`;cell.setAttribute('role','gridcell');cell.setAttribute('aria-label',v==='rock'?`Cell ${i+1} is a rock bar`:`Cell ${i+1} current points ${arrows[v]}`);cell.textContent=v==='rock'?'◆':arrows[v];const boat=st.boats.find(b=>b.i===i);if(boat){const mark=document.createElement('span');mark.className='fgf-boat';mark.textContent=cargo[boat.kind][1];cell.append(mark);}cell.addEventListener('click',()=>rotate(i));cell.addEventListener('pointerenter',e=>{if(e.buttons)rotate(i,true);});grid.append(cell);});if(done===3&&st.boats.length===0){st.unlocked=true;}}
    function rotate(i,drag=false){if(st.grid[i]==='rock')return;if(st.rudders<=0){note('No rudders left.','Advance the tide or patch the hull if needed.');return;}st.grid[i]=(st.grid[i]+1)%4;st.rudders--;st.focus=i;st.score=Math.max(0,st.score-3);if(!drag)note('Gate rotated.',`Cell ${i+1} now sends ferries ${arrows[st.grid[i]]}.`);render();}
    function launch(){if(!st.queue.length){note('No ferries waiting.','Advance remaining boats or bind the harbor result.');return;}if(st.boats.some(b=>b.i%6===0)){note('Entry blocked.','Clear the west channel before launching another ferry.');return;}const kind=st.queue.shift();st.boats.push({kind,i:18,age:0});st.patience=Math.max(0,st.patience-1);st.score+=25;tone('move');note('Ferry launched.',`${cargo[kind][1]} ${cargo[kind][2]} needs the ${cargo[kind][2].toLowerCase()}.`);render();}
    function advance(){if(st.tide<=0){note('Tide is gone.','Start a new harbor or patch and try to finish nearby ferries.');return;}st.tide--;const next=[];for(const b of st.boats){const dir=st.grid[b.i];if(dir==='rock'){hit('Rock bar hit.');continue;}const r=Math.floor(b.i/6),c=b.i%6,[dr,dc]=dirs[dir],nr=r+dr,nc=c+dc;if(nr<0||nr>5||nc<0||nc>5){if((b.kind==='mail'&&nc>5)||(b.kind==='med'&&nr<0)||(b.kind==='grain'&&nr>5)){st.delivered[b.kind]++;st.score+=160+st.tide*8;note('Clean delivery.',`${cargo[b.kind][2]} received ${cargo[b.kind][1]}.`);tone('win');}else hit('Wrong dock.',`${cargo[b.kind][1]} missed ${cargo[b.kind][2]}.`);continue;}const ni=nr*6+nc;if(st.grid[ni]==='rock'){hit('Rock bar hit.','Patch the hull or route around sandbars.');continue;}next.push({...b,i:ni,age:b.age+1});}
      st.boats=next;st.patience=Math.max(0,st.patience-st.boats.filter(b=>b.age>5).length);if(!st.boats.length&&goals().every(g=>g.done)){st.unlocked=true;st.score+=260;note('Harbor contract complete.',`Score ${st.score}. Storm lock unlocked for this session.`);tone('win');}else if(st.hull<=0||st.patience<=0){note('Harbor failed.',st.hull<=0?'Hull gave out. Repair earlier next run.':'Passengers lost patience. Launch fewer ferries at once.');tone('bad');}else if(st.tide===0){note('Tide spent.',`Delivered ${Object.values(st.delivered).reduce((a,b)=>a+b,0)} ferries. Replay for a cleaner route.`);}else note('Tide advanced.','Rotate more gates, launch the next ferry, or patch before the next move.');render();}
    function hit(m,s='Hull damage costs score and patience.'){st.hull--;st.patience=Math.max(0,st.patience-1);st.score=Math.max(0,st.score-45);note(m,s);tone('bad');}
    function patch(){if(st.rudders<2){note('Need two rudders to patch.','Advance the tide or reset the harbor.');return;}st.rudders-=2;st.hull++;st.score=Math.max(0,st.score-35);note('Hull patched.','Repair buys safety but spends scarce route control.');render();}
    root.addEventListener('keydown',e=>{if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter',' '].includes(e.key))return;e.preventDefault();const r=Math.floor(st.focus/6),c=st.focus%6;if(e.key==='ArrowUp')st.focus=Math.max(0,r-1)*6+c;if(e.key==='ArrowDown')st.focus=Math.min(5,r+1)*6+c;if(e.key==='ArrowLeft')st.focus=r*6+Math.max(0,c-1);if(e.key==='ArrowRight')st.focus=r*6+Math.min(5,c+1);if(e.key==='Enter'||e.key===' ')rotate(st.focus);render();});
    root.addEventListener('click',e=>{const a=e.target.closest('[data-act]')?.dataset.act;if(!a)return;if(a==='launch')launch();if(a==='tide')advance();if(a==='patch')patch();if(a==='reset')seed();if(a==='sound'){st.sound=!st.sound;e.target.textContent=st.sound?'Sound on':'Sound off';e.target.setAttribute('aria-pressed',String(st.sound));tone('move');}});
    dialog.addEventListener('close',()=>{if(st.ac)st.ac.close();},{once:true});
    seed();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
