(() => {
'use strict';
const APP={name:'Fold Lab',emoji:'📐',category:'play',version:'1.0.0',summary:'Plan crease sequences, manage paper stress, and engineer six foldable structures.',description:'A local-only origami engineering game with six commissions, crease sequencing, mountain and valley folds, symmetry, paper grain, stress, precision, limited actions, session unlocks, meaningful collapse, one costly recovery, touch, keyboard, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const JOBS=[
 {title:'Wind Pinwheel',brief:'Build a balanced four-vane spinner.',target:['D1','D2'],sym:2,stress:42,grain:'either'},
 {title:'Standing Crane',brief:'Create a narrow base with a stable lifted neck.',target:['V','D1','H'],sym:1,stress:48,grain:'vertical'},
 {title:'Gift Box',brief:'Form four walls without tearing the corners.',target:['V','H','D1','D2'],sym:2,stress:58,grain:'either'},
 {title:'Glider Wing',brief:'Balance lift and stiffness across a long center spine.',target:['V','D1','D2'],sym:2,stress:52,grain:'horizontal'},
 {title:'Water Lily',brief:'Layer radial petals while keeping the center flexible.',target:['D1','D2','H','V'],sym:2,stress:64,grain:'either'},
 {title:'Deployable Shelter',brief:'Engineer a compact fold that opens into a rigid canopy.',target:['V','H','D1','D2','K'],sym:3,stress:72,grain:'vertical'}
];
const CREASES={V:{name:'Vertical',path:'M160 25 V295'},H:{name:'Horizontal',path:'M25 160 H295'},D1:{name:'Diagonal ↘',path:'M35 35 L285 285'},D2:{name:'Diagonal ↙',path:'M285 35 L35 285'},K:{name:'Kite reverse',path:'M160 35 L240 160 L160 285 L80 160 Z'}};
function style(){if($('#fold-lab-style'))return;const e=document.createElement('style');e.id='fold-lab-style';e.textContent=`
.fold-lab{max-width:1120px;display:grid;gap:12px}.fl-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.fl-stat,.fl-card{border:1px solid var(--line);border-radius:17px;background:#fff}.fl-stat{padding:9px}.fl-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.fl-layout{display:grid;grid-template-columns:1fr .95fr;gap:12px}.fl-card{padding:15px}.fl-board{min-height:370px;border-radius:24px;background:linear-gradient(145deg,#f2f6ff,#fff4df);display:grid;place-items:center;position:relative;overflow:hidden}.fl-board svg{width:min(88%,380px);height:auto;filter:drop-shadow(0 16px 16px rgba(34,44,74,.18))}.fl-paper{fill:#fffdf7;stroke:#405175;stroke-width:3}.fl-crease{fill:none;stroke:#6c7fa8;stroke-width:4;stroke-dasharray:8 7;opacity:.18;transition:.25s}.fl-crease.active{opacity:.9}.fl-crease.mountain{stroke:#bd5b55}.fl-crease.valley{stroke:#467cb8}.fl-paper.pulse{animation:fl-fold .55s ease-out}@keyframes fl-fold{50%{transform:scale(.94) rotate(1deg)}}.fl-controls{display:grid;gap:10px}.fl-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.fl-grid button,.fl-actions button{min-height:46px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800;padding:9px}.fl-grid button[aria-pressed=true]{outline:3px solid #91a8dd;background:#edf2ff}.fl-mode{display:grid;grid-template-columns:1fr 1fr;gap:8px}.fl-mode button{min-height:42px;border:1px solid var(--line);border-radius:10px;background:#fff;font-weight:800}.fl-mode button[aria-pressed=true]{background:#e5edff;border-color:#4967b0}.fl-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.fl-actions .primary{background:#e4ecff;border-color:#4967b0}.fl-log{min-height:108px}.fl-tags{display:flex;gap:6px;flex-wrap:wrap}.fl-tag{font-size:.69rem;padding:4px 7px;border-radius:999px;background:#eef2ff}.fl-seq{display:flex;gap:6px;flex-wrap:wrap;min-height:32px}.fl-step{font-size:.72rem;border-radius:9px;background:#f3f3f3;padding:6px 8px}.fl-step b{color:#355b9a}.fl-hint{font-size:.82rem;color:var(--muted)}
@media(max-width:820px){.fl-layout{grid-template-columns:1fr}.fl-hud{grid-template-columns:repeat(3,1fr)}.fl-board{min-height:310px}}@media(max-width:520px){.fl-hud{grid-template-columns:repeat(2,1fr)}.fl-board{min-height:270px}.fl-actions{grid-template-columns:1fr}.fl-grid button{min-height:50px}}@media(prefers-reduced-motion:reduce){.fold-lab *{animation:none!important;transition:none!important}}
`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-fold-lab]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.foldLab='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-fold-lab]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.flBound)return;b.dataset.flBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · geometric engineering';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
 const root=document.createElement('section');root.className='tool-panel fold-lab';root.innerHTML=`<div class="fl-hud">${['Job','Actions','Stress','Precision','Score','Unlock'].map((x,i)=>`<div class="fl-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="fl-layout"><section class="fl-card"><div class="fl-board" aria-label="Origami crease plan"><svg viewBox="0 0 320 320" role="img" aria-label="Square paper with active creases"><rect class="fl-paper" x="25" y="25" width="270" height="270" rx="8"/>${Object.entries(CREASES).map(([k,v])=>`<path class="fl-crease" data-line="${k}" d="${v.path}"/>`).join('')}</svg></div><h3 data-title></h3><p data-brief></p><div class="fl-tags" data-tags></div><p class="fl-hint">Choose a crease, then mountain or valley. Order matters: early diagonals improve symmetry, but repeated crossings raise stress. Keyboard: 1–5 choose creases, M/V choose mode, Enter folds, U undoes.</p></section><aside class="fl-card fl-controls"><div class="result-card fl-log" aria-live="polite"></div><div class="fl-seq" data-seq></div><div class="fl-grid">${Object.entries(CREASES).map(([k,v],i)=>`<button data-crease="${k}" aria-pressed="false"><span aria-hidden="true">${i+1}</span> ${v.name}</button>`).join('')}</div><div class="fl-mode"><button data-mode="mountain" aria-pressed="true">Mountain fold</button><button data-mode="valley" aria-pressed="false">Valley fold</button></div><div class="fl-actions"><button class="primary" data-a="fold">Commit fold</button><button data-a="undo">Undo crease</button><button data-a="test">Test structure</button><button data-a="recover">Use fresh sheet</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
 let st,timer=0,ended=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 function reset(){clearTimeout(timer);st={job:0,actions:8,stress:0,precision:72,score:0,unlock:false,recovery:true,selected:'V',mode:'mountain',seq:[],grain:Math.random()>.5?'vertical':'horizontal'};ended=false;log(JOBS[0].brief,'Plan a crease sequence, then test the structure.');draw()}
 function expectedMode(k){return ['V','D2','K'].includes(k)?'mountain':'valley'}
 function fold(){if(ended||st.actions<=0)return;const k=st.selected;if(k==='K'&&!st.unlock)return log('Kite reverse is locked.','Reach 3,200 points to unlock it for this session.');const repeats=st.seq.filter(x=>x.k===k).length,cross=st.seq.filter(x=>x.k!==k).length;st.seq.push({k,m:st.mode});st.actions--;st.stress=clamp(st.stress+7+repeats*9+Math.max(0,cross-2),0,100);st.precision=clamp(st.precision+(st.mode===expectedMode(k)?3:-5)-repeats*4,0,100);$('.fl-paper',root).classList.add('pulse');clearTimeout(timer);timer=setTimeout(()=>$('.fl-paper',root)?.classList.remove('pulse'),reduced?40:560);log(`${CREASES[k].name} committed as a ${st.mode} fold.`,repeats?'Repeated creases concentrate stress.':'The crease joins the current plan.');draw()}
 function undo(){if(ended||!st.seq.length)return;const x=st.seq.pop();st.actions++;st.stress=clamp(st.stress-8,0,100);st.precision=clamp(st.precision-1,0,100);log(`${CREASES[x.k].name} removed.`,'The paper keeps a faint memory of the crease, so precision drops slightly.');draw()}
 function metrics(){const j=JOBS[st.job],keys=st.seq.map(x=>x.k),unique=[...new Set(keys)],matched=j.target.filter(x=>unique.includes(x)).length,extra=unique.filter(x=>!j.target.includes(x)).length,pairs=(unique.includes('D1')&&unique.includes('D2')?1:0)+(unique.includes('V')&&unique.includes('H')?1:0),orderBonus=keys[0]?.startsWith('D')?8:0,modeGood=st.seq.filter(x=>x.m===expectedMode(x.k)).length;const completeness=Math.round(matched/j.target.length*100),sym=clamp(38+pairs*24+orderBonus-extra*8,0,100),structure=clamp(st.precision+modeGood*4-st.stress*.55+(j.grain==='either'||j.grain===st.grain?8:-12),0,100);return{completeness,sym,structure,extra}}
 function test(){if(ended||st.actions<1)return;st.actions--;const j=JOBS[st.job],m=metrics(),ok=m.completeness>=100&&m.sym>=45+j.sym*5&&m.structure>=48&&st.stress<=j.stress;const gain=Math.max(0,Math.round(m.completeness*7+m.sym*5+m.structure*8-st.stress*3));st.score+=ok?gain:Math.round(gain*.25);if(st.score>=3200)st.unlock=true;if(ok){if(st.job===JOBS.length-1)return finish(true,`Final score ${st.score}. Every structure deployed.`);st.job++;st.actions=8;st.stress=Math.max(0,st.stress-18);st.precision=clamp(st.precision+4,0,100);st.seq=[];st.grain=Math.random()>.5?'vertical':'horizontal';log('Structure holds.',`Next commission: ${JOBS[st.job].brief}`)}else{st.precision=clamp(st.precision-8,0,100);log('The structure buckles.',`Completeness ${m.completeness}, symmetry ${m.sym}, structure ${m.structure}. Stress limit ${j.stress}.`);if(st.actions<=0||st.stress>=95)finish(false,'The paper is too damaged for another test.')}draw()}
 function recover(){if(ended||!st.recovery)return;st.recovery=false;st.actions=6;st.stress=0;st.precision=clamp(st.precision-14,35,100);st.seq=[];log('You open the reserve paper pack.','Stress resets, but the unfamiliar sheet reduces precision. This recovery is available once.');draw()}
 function finish(win,msg){ended=true;clearTimeout(timer);log(win?'Portfolio complete.':'Paper collapse.',msg);draw()}
 function log(a,b){$('.fl-log',root).innerHTML=`<strong>${a}</strong><p>${b}</p>`}
 function draw(){const j=JOBS[st.job],m=metrics(),hv=[`${st.job+1}/6`,st.actions,st.stress,st.precision,st.score,st.unlock?'Kite reverse':'Locked'];$$('[data-h]',root).forEach((x,i)=>x.textContent=hv[i]);$('[data-title]',root).textContent=j.title;$('[data-brief]',root).textContent=j.brief;$('[data-tags]',root).innerHTML=`<span class="fl-tag">Grain ${st.grain}</span><span class="fl-tag">Need ${j.target.map(k=>CREASES[k].name).join(', ')}</span><span class="fl-tag">Stress limit ${j.stress}</span><span class="fl-tag">Symmetry ${m.sym}</span>`;$('[data-seq]',root).innerHTML=st.seq.length?st.seq.map((x,i)=>`<span class="fl-step">${i+1}. <b>${x.m[0].toUpperCase()}</b> ${CREASES[x.k].name}</span>`).join(''):'<span class="fl-step">No creases yet</span>';$$('[data-crease]',root).forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.crease===st.selected));b.disabled=ended||(b.dataset.crease==='K'&&!st.unlock)});$$('[data-mode]',root).forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===st.mode)));$$('[data-line]',root).forEach(p=>{const found=[...st.seq].reverse().find(x=>x.k===p.dataset.line);p.classList.toggle('active',!!found);p.classList.toggle('mountain',found?.m==='mountain');p.classList.toggle('valley',found?.m==='valley')});$('[data-a="fold"]',root).disabled=ended||st.actions<=0;$('[data-a="undo"]',root).disabled=ended||!st.seq.length;$('[data-a="test"]',root).disabled=ended||st.actions<1||!st.seq.length;$('[data-a="recover"]',root).disabled=ended||!st.recovery;$('[data-a="restart"]',root).disabled=false}
 root.addEventListener('click',e=>{const c=e.target.closest('[data-crease]'),m=e.target.closest('[data-mode]'),a=e.target.closest('[data-a]');if(c){st.selected=c.dataset.crease;draw()}else if(m){st.mode=m.dataset.mode;draw()}else if(a){({fold,undo,test,recover,restart:reset}[a.dataset.a]||(()=>{}))()}});
 function keys(e){if(!root.isConnected)return;if(/^[1-5]$/.test(e.key)){const k=Object.keys(CREASES)[+e.key-1];if(k!=='K'||st.unlock){st.selected=k;draw();e.preventDefault()}}else if(e.key.toLowerCase()==='m'){st.mode='mountain';draw()}else if(e.key.toLowerCase()==='v'){st.mode='valley';draw()}else if(e.key.toLowerCase()==='u'){undo()}else if(e.key==='Enter'){fold();e.preventDefault()}}
 document.addEventListener('keydown',keys);dialog.addEventListener('close',()=>{clearTimeout(timer);document.removeEventListener('keydown',keys)},{once:true});reset()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
