(() => {
  'use strict';
  const gallery=document.querySelector('#gallery'),grid=document.querySelector('#app-grid');
  if(!gallery||!grid)return;
  const routes={
    strategist:{name:'Systems strategist',description:'Tradeoffs, planning, evidence, and recovery.',categories:['useful','play','experiment','useful'],lenses:['constraint','resource','recovery','signal'],prompts:['Find the constraint that changes your first instinct.','Spend one scarce resource before you feel ready.','Recover from one harmless failure instead of restarting.','Name the signal that would make you change course.']},
    maker:{name:'Creative maker',description:'Combination, motion, practical use, and remix.',categories:['experiment','play','useful','experiment'],lenses:['combination','motion','use','remix'],prompts:['Combine two things that normally do not belong together.','Use motion, timing, or space as part of the idea.','Turn the strongest result into one practical next step.','Remix the result by changing only one rule.']},
    explorer:{name:'Curious explorer',description:'Observation, risk, replay, and transfer.',categories:['play','experiment','play','useful'],lenses:['pattern','risk','strategy','transfer'],prompts:['Learn the rule by observing before acting.','Choose the unfamiliar option rather than the safest one.','Try a second run with a different strategy.','Carry one insight into a useful tool.']}
  };
  const state={apps:[],routeKey:'',step:0,completed:[],picks:[],opened:false,notes:[],tokens:2,swaps:0,startedAt:0};
  const safe=(value)=>String(value??'').replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const root=document.createElement('section');root.className='forge-trails';root.setAttribute('aria-labelledby','forge-trails-title');root.innerHTML='<div class="forge-trails__head"><div><p class="eyebrow">Guided discovery</p><h3 id="forge-trails-title">Take a four-stop Forge Trail</h3><p>Open each app, test a focused challenge, and record one observation. Two route tokens let you replace stops without saving or transmitting activity.</p></div><button class="trail-action forge-trails__reset" type="button" hidden>Reset trail</button></div><div class="forge-trails__routes" role="group" aria-label="Choose a Forge Trail"></div><div class="forge-trails__journey" hidden aria-live="polite"></div>';
  const radar=gallery.querySelector('.release-radar');if(radar)radar.after(root);else grid.before(root);
  const routeList=root.querySelector('.forge-trails__routes'),journey=root.querySelector('.forge-trails__journey'),reset=root.querySelector('.forge-trails__reset');
  Object.entries(routes).forEach(([key,route])=>{const b=document.createElement('button');b.className='trail-route';b.type='button';b.dataset.route=key;b.setAttribute('aria-pressed','false');b.innerHTML=`<strong>${safe(route.name)}</strong><span>${safe(route.description)}</span>`;routeList.append(b);});
  function shuffled(items){const copy=[...items];for(let i=copy.length-1;i>0;i-=1){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
  function buildPicks(route){const used=new Set();return route.categories.map((category)=>{const preferred=state.apps.filter((app)=>app.category===category&&!used.has(app.id));const pool=preferred.length?preferred:state.apps.filter((app)=>!used.has(app.id));const pick=shuffled(pool)[0];if(pick)used.add(pick.id);return pick;});}
  function selectRoute(key){if(!routes[key]||state.apps.length<4)return;Object.assign(state,{routeKey:key,step:0,completed:[],notes:[],tokens:2,swaps:0,opened:false,startedAt:Date.now(),picks:buildPicks(routes[key])});routeList.querySelectorAll('.trail-route').forEach((b)=>b.setAttribute('aria-pressed',String(b.dataset.route===key)));reset.hidden=false;render();}
  function openCurrent(){const app=state.picks[state.step];if(!app)return;state.opened=true;render();const card=[...grid.querySelectorAll('.app-card')].find((item)=>item.querySelector('.app-name')?.textContent?.trim()===app.name);if(card?.hidden)card.hidden=false;const opener=card?.querySelector('.app-card-button');if(opener){opener.click();return;}const search=document.querySelector('#radar-search');if(search){search.value=app.name;search.dispatchEvent(new Event('input',{bubbles:true}));grid.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}}
  function completeCurrent(){const app=state.picks[state.step],note=journey.querySelector('[data-trail-note]')?.value.trim();if(!app||!state.opened||!note)return;state.completed.push(app.id);state.notes.push({app:app.name,note:note.slice(0,180)});state.step+=1;state.opened=false;render();journey.querySelector('button,textarea')?.focus();}
  function swapCurrent(){if(state.tokens<1)return;const route=routes[state.routeKey],category=route.categories[state.step],used=new Set(state.picks.map((app)=>app?.id)),choices=shuffled(state.apps.filter((app)=>app.category===category&&!used.has(app.id)));if(!choices.length)return;state.picks[state.step]=choices[0];state.tokens-=1;state.swaps+=1;state.opened=false;render();}
  function render(){if(!state.routeKey){journey.hidden=true;return;}journey.hidden=false;const route=routes[state.routeKey];if(state.step>=4){const elapsed=Math.max(1,Math.round((Date.now()-state.startedAt)/60000)),score=Math.max(40,100-state.swaps*8+Math.min(12,state.notes.reduce((sum,item)=>sum+Math.min(item.note.length,45),0)/15));journey.innerHTML=`<div class="trail-summary"><p class="eyebrow">Trail complete</p><h4>${safe(route.name)} finished</h4><div class="trail-score"><strong>${Math.round(score)}</strong><span>trail score</span></div><p>${elapsed} minute session · ${state.swaps} stop swap${state.swaps===1?'':'s'} · ${state.tokens} token${state.tokens===1?'':'s'} left</p><div class="trail-reflections">${state.notes.map((item,index)=>`<article><span>${index+1}</span><div><strong>${safe(item.app)}</strong><p>${safe(item.note)}</p></div></article>`).join('')}</div><div><button class="trail-action trail-action--primary" type="button" data-action="again">Build another route</button></div></div>`;return;}const app=state.picks[state.step],progress=[0,1,2,3].map((index)=>`<li class="${index<state.step?'is-complete':index===state.step?'is-current':''}"${index===state.step?' aria-current="step"':''}>Stop ${index+1}</li>`).join('');journey.innerHTML=`<div class="trail-status"><span>${state.tokens} route token${state.tokens===1?'':'s'}</span><span>${state.completed.length}/4 observations</span></div><ol class="trail-progress">${progress}</ol><div class="trail-card"><div><p class="eyebrow">${safe(route.name)} · ${safe(route.lenses[state.step])} lens</p><h4>${safe(app.name)}</h4><p>${safe(app.summary)}</p><p class="trail-prompt">Trail challenge: ${safe(route.prompts[state.step])}</p><label class="trail-note"><span>What changed, surprised you, or failed?</span><textarea data-trail-note maxlength="180" rows="3" ${state.opened?'':'disabled'} placeholder="Open the app before recording the observation."></textarea></label></div><div class="trail-actions"><button class="trail-action" type="button" data-action="swap" ${state.tokens<1?'disabled':''}>Swap stop · 1 token</button><button class="trail-action trail-action--primary" type="button" data-action="open">${state.opened?'Reopen app':'Open app'}</button><button class="trail-action" type="button" data-action="complete" ${state.opened?'':'disabled'}>Complete observation</button></div></div>`;}
  routeList.addEventListener('click',(event)=>{const b=event.target.closest('[data-route]');if(b)selectRoute(b.dataset.route);});journey.addEventListener('click',(event)=>{const action=event.target.closest('[data-action]')?.dataset.action;if(action==='open')openCurrent();if(action==='complete')completeCurrent();if(action==='swap')swapCurrent();if(action==='again')selectRoute(state.routeKey);});reset.addEventListener('click',()=>{Object.assign(state,{routeKey:'',step:0,completed:[],notes:[],picks:[],opened:false});reset.hidden=true;routeList.querySelectorAll('.trail-route').forEach((b)=>b.setAttribute('aria-pressed','false'));render();routeList.querySelector('.trail-route')?.focus();});
  fetch('./registry/apps.json',{cache:'no-store'}).then((response)=>{if(!response.ok)throw new Error(`Registry returned ${response.status}`);return response.json();}).then((data)=>{state.apps=Array.isArray(data.apps)?data.apps.filter((app)=>app.id&&app.name&&app.summary&&app.category):[];if(state.apps.length<4)throw new Error('Not enough apps to build a trail');}).catch((error)=>{routeList.innerHTML='<p>The guided trails could not load. The full gallery remains available below.</p>';console.error(error);});window.addEventListener('pagehide',()=>{state.apps=[];state.picks=[];state.completed=[];state.notes=[];},{once:true});
})();