(() => {
  const APP = { name: 'Fossil Layers', emoji: '🦴', category: 'play', version: '1.0.0', summary: 'Excavate a layered dig site without destroying the story buried in the soil.', description: 'A local stratigraphy puzzle with layered excavation, brush and pick tradeoffs, scan pulses, catalog timing, contamination risk, ordered evidence scoring, adaptive dig contracts, session-only night trench unlock, touch and keyboard controls, reduced-motion behavior, optional local audio, and teardown.' };
  const $ = (s, r = document) => r.querySelector(s), $$ = (s, r = document) => Array.from(r.querySelectorAll(s));
  const label = v => v === 'play' ? 'Play' : v === 'useful' ? 'Useful' : 'Experiment';
  function styles() { if ($('#fossil-layers-styles')) return; const st = document.createElement('style'); st.id = 'fossil-layers-styles'; st.textContent = `.fol-card{animation:fol-rise .24s ease both}.fol-game{max-width:1120px;gap:14px}.fol-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.fol-stat,.fol-site,.fol-panel{border:1px solid var(--line);border-radius:18px;background:#fff}.fol-stat{padding:10px 12px}.fol-stat span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.fol-stat strong{display:block;margin-top:4px}.fol-layout{display:grid;grid-template-columns:1.05fr .95fr;gap:12px}.fol-site{position:relative;overflow:hidden;min-height:430px;padding:14px;background:linear-gradient(180deg,#fde68a,#a16207);touch-action:none}.fol-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:7px;height:100%}.fol-cell{min-height:62px;border:2px solid rgba(120,53,15,.34);border-radius:16px;background:#854d0e;color:#fff;font-weight:900;display:grid;place-items:center;position:relative;box-shadow:inset 0 -12px 0 rgba(0,0,0,.13);touch-action:manipulation}.fol-cell:focus-visible,.fol-mode button:focus-visible,.fol-actions button:focus-visible{outline:4px solid var(--accent);outline-offset:2px}.fol-cell.is-selected{border-color:#fff;box-shadow:0 0 0 4px #facc15,inset 0 -12px 0 rgba(0,0,0,.13)}.fol-cell small{position:absolute;left:6px;top:5px;font-size:.64rem;opacity:.82}.fol-cell[data-depth="3"]{background:#713f12}.fol-cell[data-depth="2"]{background:#92400e}.fol-cell[data-depth="1"]{background:#b45309}.fol-cell[data-depth="0"]{background:#fef3c7;color:#3f2c12}.fol-cell.is-scanned::after{content:'scan';position:absolute;right:6px;bottom:5px;font-size:.58rem;letter-spacing:.08em;text-transform:uppercase}.fol-panel{padding:14px;display:grid;gap:12px}.fol-mode,.fol-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.fol-mode button{min-height:44px;border:1px solid var(--line);border-radius:14px;background:#fff;font-weight:900}.fol-mode button.is-active{box-shadow:0 0 0 3px #fde68a inset}.fol-contract,.fol-tray{display:grid;gap:7px}.fol-rule,.fol-find{border:1px solid var(--line);border-radius:14px;padding:9px;background:#f8fafc}.fol-rule.done{background:#dcfce7}.fol-find.bad{background:#fee2e2}.fol-log{min-height:104px;padding:17px 19px}.fol-help{font-size:.88rem;color:var(--muted)}@media(max-width:880px){.fol-hud{grid-template-columns:repeat(2,1fr)}.fol-layout{grid-template-columns:1fr}.fol-site{min-height:370px}}@media(max-width:520px){.fol-site{padding:8px;min-height:320px}.fol-grid{gap:5px}.fol-cell{min-height:48px;border-radius:12px}.fol-panel{padding:9px}.fol-mode,.fol-actions{grid-template-columns:1fr 1fr}}@media(prefers-reduced-motion:reduce){.fol-card{animation:none!important;transition:none!important}}@keyframes fol-rise{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}`; document.head.append(st); }
  function addCard() { const grid = $('#app-grid'), template = $('#app-card-template'); if (!grid || !template || $('[data-fossil-layers-card]')) return; const f = $('.filter.is-active')?.dataset.filter || 'all'; if (f !== 'all' && f !== APP.category) return; styles(); const node = template.content.cloneNode(true), card = $('.app-card', node); card.dataset.category = APP.category; card.dataset.fossilLayersCard = 'true'; card.classList.add('fol-card'); $('.app-icon', node).textContent = APP.emoji; $('.app-meta', node).textContent = `${label(APP.category)} · v${APP.version}`; $('.app-name', node).textContent = APP.name; $('.app-summary', node).textContent = APP.summary; const b = $('.app-card-button', node); b.setAttribute('aria-label', `Open ${APP.name}`); b.addEventListener('click', open); grid.append(node); }
  function boot() { styles(); let tries = 0; const retry = () => { addCard(); if (!$('[data-fossil-layers-card]') && tries++ < 20) setTimeout(retry, 120); }; retry(); $$('.filter').forEach(b => { if (b.dataset.folRefresh) return; b.dataset.folRefresh = '1'; b.addEventListener('click', () => setTimeout(addCard, 0)); }); }
  function open() { const dialog = $('#app-dialog'), stage = $('#app-stage'); if (!dialog || !stage) return; $('#dialog-title').textContent = APP.name; $('#dialog-category').textContent = `${label(APP.category)} · ${APP.emoji}`; $('#dialog-description').textContent = APP.description; $('#dialog-feedback').href = 'https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Fossil%20Layers'; stage.replaceChildren(); game(stage, dialog); dialog.showModal(); }
  function game(stage, dialog) {
    const root = document.createElement('section'); root.className = 'tool-panel fol-game'; root.innerHTML = `<div class="fol-hud"><div class="fol-stat"><span>Contract</span><strong id="fol-mode-name">River bank</strong></div><div class="fol-stat"><span>Days</span><strong id="fol-days">10</strong></div><div class="fol-stat"><span>Context</span><strong id="fol-context">100%</strong></div><div class="fol-stat"><span>Scans</span><strong id="fol-scans">3</strong></div><div class="fol-stat"><span>Finds</span><strong id="fol-finds">0</strong></div><div class="fol-stat"><span>Score</span><strong id="fol-score">0</strong></div></div><div class="fol-layout"><div class="fol-site" aria-label="Layered excavation grid"><div class="fol-grid" role="grid"></div></div><div class="fol-panel"><div class="fol-mode" aria-label="Dig contracts"></div><div><strong>Contract checks</strong><div class="fol-contract"></div></div><p class="fol-help">Tap a square, or use arrows to move. Brush is safe but slow. Pick is fast but hurts context if a find is close. Scan marks likely evidence. Catalog only when the square is fully exposed.</p><div class="fol-actions"><button class="button" data-act="brush" type="button">Brush layer</button><button class="button" data-act="pick" type="button">Careful pick</button><button class="button" data-act="scan" type="button">Scan pulse</button><button class="button" data-act="catalog" type="button">Catalog find</button><button class="button button-secondary" data-act="reset" type="button">New trench</button><button class="button button-secondary" data-act="sound" type="button" aria-pressed="false">Sound off</button></div></div></div><div><strong>Field tray</strong><div class="fol-tray"></div></div><div class="result-card fol-log" aria-live="polite"><strong>Open a clean trench.</strong><small>Preserve context, expose finds, then catalog from oldest layer to youngest for bonus evidence.</small></div>`; stage.append(root);
    const modes = { river: { name: 'River bank', days: 10, scans: 3, target: 4, context: 70 }, quarry: { name: 'Quarry rescue', days: 8, scans: 2, target: 5, context: 62 }, night: { name: 'Night trench', days: 7, scans: 2, target: 6, context: 68 } };
    const icons = ['shell', 'tool', 'bone', 'seed', 'coin', 'print']; const glyph = { shell: '◓', tool: '⌁', bone: '◇', seed: '✶', coin: '●', print: '▣' };
    const st = { mode: 'river', unlocked: false, sel: 0, days: 10, context: 100, scans: 3, score: 0, finds: [], sound: false, ac: null, cells: [] };
    const grid = $('.fol-grid', root), modeBox = $('.fol-mode', root), contract = $('.fol-contract', root), tray = $('.fol-tray', root), log = $('.fol-log', root); const mode = () => modes[st.mode]; const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
    function tone(kind) { if (!st.sound) return; const A = window.AudioContext || window.webkitAudioContext; if (!A) return; st.ac ||= new A(); st.ac.resume(); const o = st.ac.createOscillator(), g = st.ac.createGain(); o.type = kind === 'bad' ? 'square' : 'sine'; o.frequency.value = kind === 'win' ? 820 : kind === 'ping' ? 520 : 180; g.gain.setValueAtTime(.0001, st.ac.currentTime); g.gain.exponentialRampToValueAtTime(.05, st.ac.currentTime + .02); g.gain.exponentialRampToValueAtTime(.0001, st.ac.currentTime + .22); o.connect(g).connect(st.ac.destination); o.start(); o.stop(st.ac.currentTime + .24); }
    function note(m, s = 'Brush, scan, and catalog without losing the layer story.') { log.innerHTML = `<strong>${m}</strong><small>${s}</small>`; }
    function seed() { st.days = mode().days; st.scans = mode().scans; st.context = 100; st.score = 0; st.finds = []; st.sel = 0; st.cells = Array.from({ length: 30 }, (_, i) => ({ depth: 1 + Math.floor(Math.random() * 3), find: null, scanned: false, damaged: false, seen: false, row: Math.floor(i / 6) })); const slots = [...Array(30).keys()].sort(() => Math.random() - .5).slice(0, 8); slots.forEach((n, i) => { st.cells[n].find = { type: icons[i % icons.length], age: 900 - st.cells[n].row * 120 - i * 17 }; }); note('Fresh trench opened.', 'Older finds tend to sit lower. Catalog in a believable order for sequence bonuses.'); render(); }
    function render() { $('#fol-mode-name', root).textContent = mode().name; $('#fol-days', root).textContent = st.days; $('#fol-context', root).textContent = `${st.context}%`; $('#fol-scans', root).textContent = st.scans; $('#fol-finds', root).textContent = st.finds.length; $('#fol-score', root).textContent = st.score; modeBox.innerHTML = ''; Object.entries(modes).forEach(([id, m]) => { const b = document.createElement('button'); b.type = 'button'; b.textContent = m.name; b.className = id === st.mode ? 'is-active' : ''; b.disabled = id === 'night' && !st.unlocked; b.title = b.disabled ? 'Catalog five clean finds with 70% context to unlock this session.' : ''; b.addEventListener('click', () => { st.mode = id; seed(); }); modeBox.append(b); }); contract.innerHTML = ''; [{ a: `${mode().target} finds cataloged`, d: st.finds.length >= mode().target }, { a: `Context at least ${mode().context}%`, d: st.context >= mode().context }, { a: 'Sequence mostly ordered', d: sequenceScore() >= 2 }].forEach(r => { const e = document.createElement('div'); e.className = `fol-rule${r.d ? ' done' : ''}`; e.innerHTML = `<strong>${r.d ? 'Met' : 'Open'}</strong> ${r.a}`; contract.append(e); }); tray.innerHTML = st.finds.length ? '' : '<div class="fol-find">No cataloged finds yet.</div>'; st.finds.forEach((f, i) => { const e = document.createElement('div'); e.className = `fol-find${f.damaged ? ' bad' : ''}`; e.innerHTML = `<strong>${glyph[f.type]} ${f.type}</strong><br><small>Layer age ${f.age}. ${f.damaged ? 'Context damaged.' : i && f.age > st.finds[i - 1].age ? 'Sequence question.' : 'Clean record.'}</small>`; tray.append(e); }); grid.innerHTML = ''; st.cells.forEach((c, i) => { const b = document.createElement('button'); b.type = 'button'; b.className = `fol-cell${i === st.sel ? ' is-selected' : ''}${c.scanned ? ' is-scanned' : ''}`; b.dataset.depth = c.depth; b.setAttribute('role', 'gridcell'); b.setAttribute('aria-label', cellLabel(c, i)); b.innerHTML = `<small>${i + 1}</small>${c.depth ? '▦'.repeat(c.depth) : c.find ? glyph[c.find.type] : '·'}`; b.addEventListener('click', () => { st.sel = i; render(); }); grid.append(b); }); }
    function cellLabel(c, i) { return `Square ${i + 1}, ${c.depth ? c.depth + ' layers covered' : c.find ? 'exposed ' + c.find.type : 'empty'}, ${c.scanned ? 'scanned' : 'unscanned'}`; }
    function sequenceScore() { let ok = 0; for (let i = 1; i < st.finds.length; i++) if (st.finds[i].age <= st.finds[i - 1].age) ok++; return ok; }
    function spendDay(n = 1) { st.days = clamp(st.days - n, 0, 99); if (!st.days) finish(); }
    function brush() { const c = st.cells[st.sel]; if (!c.depth) { note('Already exposed.', 'Scan or catalog this square, or move to a covered one.'); return; } c.depth--; st.score += 18; spendDay(); if (!c.depth && c.find) note('Find exposed cleanly.', 'Catalog it now, or inspect nearby squares before committing the sequence.'); else note('Layer brushed.', c.depth ? `${c.depth} layer(s) still cover this square.` : 'No find here, but the context stayed clean.'); tone('ping'); render(); }
    function pick() { const c = st.cells[st.sel]; if (!c.depth) { note('Pick would add no value.', 'Use catalog or move to covered soil.'); return; } c.depth = Math.max(0, c.depth - 2); spendDay(); st.score += 26; if (!c.depth && c.find) { c.damaged = true; st.context = clamp(st.context - 12, 0, 100); note('Fast pick damaged context.', 'The object is visible, but the layer story lost detail.'); tone('bad'); } else { st.context = clamp(st.context - 3, 0, 100); note('Pick cleared soil quickly.', 'A small context cost buys speed.'); tone('ping'); } render(); }
    function scan() { if (st.scans <= 0) { note('No scans remain.', 'Use careful brushing from here.'); return; } st.scans--; const around = [st.sel, st.sel - 1, st.sel + 1, st.sel - 6, st.sel + 6].filter(i => i >= 0 && i < 30); around.forEach(i => { if (st.cells[i].find) st.cells[i].scanned = true; }); st.score += 12; note('Scan pulse sent.', 'Marked nearby squares that likely contain evidence.'); tone('ping'); render(); }
    function catalog() { const c = st.cells[st.sel]; if (c.depth || !c.find) { note('Nothing ready to catalog.', 'A find must be fully exposed first.'); return; } const f = { ...c.find, damaged: c.damaged }; st.finds.push(f); c.find = null; c.seen = true; const order = st.finds.length < 2 || f.age <= st.finds[st.finds.length - 2].age; st.score += (f.damaged ? 80 : 150) + (order ? 55 : -25) + Math.max(0, st.context - 60); if (!order) st.context = clamp(st.context - 5, 0, 100); if (st.finds.length >= 5 && st.context >= 70) st.unlocked = true; note(order ? 'Find cataloged.' : 'Find cataloged with sequence doubts.', `${f.type} recorded at layer age ${f.age}. ${st.unlocked ? 'Night trench unlocked this session.' : 'Keep the sequence clean.'}`); tone(order ? 'win' : 'bad'); render(); if (st.finds.length >= mode().target) finish(); }
    function finish() { const pass = st.finds.length >= mode().target && st.context >= mode().context; st.score += pass ? 240 : 0; note(pass ? 'Exhibit accepted.' : 'Dig closed for review.', pass ? `Final score ${st.score}. The trench tells a coherent story.` : `Final score ${st.score}. More clean evidence or context was needed.`); tone(pass ? 'win' : 'bad'); render(); }
    root.addEventListener('click', e => { const a = e.target.closest('[data-act]')?.dataset.act; if (!a) return; if (a === 'brush') brush(); if (a === 'pick') pick(); if (a === 'scan') scan(); if (a === 'catalog') catalog(); if (a === 'reset') seed(); if (a === 'sound') { st.sound = !st.sound; e.target.textContent = st.sound ? 'Sound on' : 'Sound off'; e.target.setAttribute('aria-pressed', String(st.sound)); tone('ping'); } });
    root.addEventListener('keydown', e => { const col = st.sel % 6; if (e.key === 'ArrowRight') st.sel = col === 5 ? st.sel : st.sel + 1; else if (e.key === 'ArrowLeft') st.sel = col === 0 ? st.sel : st.sel - 1; else if (e.key === 'ArrowDown') st.sel = Math.min(29, st.sel + 6); else if (e.key === 'ArrowUp') st.sel = Math.max(0, st.sel - 6); else if (e.key === ' ') brush(); else if (e.key === 'Enter') catalog(); else return; e.preventDefault(); render(); $('.fol-cell.is-selected', root)?.focus(); });
    const close = () => { if (st.ac) st.ac.close().catch(() => {}); dialog.removeEventListener('close', close); };
    dialog.addEventListener('close', close); seed();
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot, { once: true }); else boot();
})();
