(() => {
'use strict';
const APP={name:'Gallery Gambit',emoji:'🖼️',category:'play',version:'1.0.2',summary:'Route visitor groups through six museum days while balancing access, crowding, conservation, and satisfaction.',description:'A local-only spatial planning game with connected routes, timed visitor groups, accessibility needs, fragile-gallery closures, conservation limits, budget and planning tradeoffs, visible opening gates, scoring, progression, failure, recovery, keyboard and touch controls, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const DAYS=[
{name:'School opening',turns:7,budget:7,target:62,groups:[['Class A','learning',3,false],['Class B','learning',3,false],['Family','wonder',2,true]]},
{name:'Rainy Saturday',turns:7,budget:8,target:68,groups:[['Families','wonder',4,true],['Tour','history',3,false],['Teens','energy',3,false]]},
{name:'Quiet access hour',turns:7,budget:8,target:72,groups:[['Sensory group','calm',3,true],['Senior tour','history',3,true],['Researchers','depth',2,false]]},
{name:'Blockbuster loan',turns:9,budget:9,target:76,groups:[['Members','depth',3,false],['Press','history',2,false],['Families','wonder',4,true],['Walk-ins','energy',3,false]]},
{name:'Climate alert',turns:9,budget:10,target:72,groups:[['School','learning',4,true],['Donors','depth',3,false],['Tourists','wonder',4,false],['Community','history',3,true]]},
{name:'Festival night',turns:11,budget:11,target:76,groups:[['Families','wonder',4,true],['Students','energy',4,false],['Members','depth',3,false],['Visitors','history',4,true],['Late crowd','energy',3,false]]}
];
const ROOMS=[
{id:'atrium',name:'Atrium',x:80,y:190,cap:6,tags:['wonder','energy'],access:true,fragile:false},
{id:'history',name:'Origins',x:230,y:85,cap:4,tags:['history','learning'],access:true,fragile:false},
{id:'studio',name:'Studio',x:230,y:295,cap:3,tags:['energy','learning'],access:true,fragile:false},
{id:'vault',name:'Rare Works',x:410,y:85,cap:2,tags:['depth','history'],access:false,fragile:true},
{id:'garden',name:'Light Garden',x:410,y:295,cap:4,tags:['wonder','calm'],access:true,fragile:true},
{id:'archive',name:'Open Archive',x:590,y:190,cap:3,tags:['depth','calm'],access:true,fragile:false}
];
const LINKS=[['atrium','history'],['atrium','studio'],['history','vault'],['history','garden'],['studio','garden'],['vault','archive'],['garden','archive']];
function style(){if($('#gallery-gambit-style'))return;const e=document.createElement('style');e.id='gallery-gambit-style';e.textContent=`.gallery-gambit{max-width:1120px;display:grid;gap:12px}.gg-hud{display:grid;grid-template-columns:repeat(7,1fr);gap:7px}.gg-stat,.gg-panel{border:1px solid var(--line);border-radius:17px;background:#fff}.gg-stat{padding:9px}.gg-stat span{display:block;font-size:.6rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.gg-layout{display:grid;grid-template-columns:1.25fr .75fr;gap:12px}.gg-panel{padding:14px}.gg-brief{border-radius:17px;padding:15px;background:linear-gradient(135deg,#432c5f,#76508a);color:#fff}.gg-board{margin-top:10px;border:1px solid #d8cfe0;border-radius:16px;overflow:hidden;background:radial-gradient(circle at 50% 45%,#fff,#f5eff8)}.gg-board svg{width:100%;height:390px;display:block}.gg-link{stroke:#b8a8c5;stroke-width:8;stroke-linecap:round}.gg-room{cursor:pointer}.gg-room rect{fill:#fff;stroke:#513667;stroke-width:2}.gg-room.is-selected rect{stroke:#c77b14;stroke-width:5}.gg-room.is-closed rect{fill:#eee8f0;stroke-dasharray:6 4}.gg-room text{font-size:12px;font-weight:900;pointer-events:none}.gg-room .sub{font-size:10px;font-weight:700;fill:#6f6177}.gg-actions,.gg-gates,.gg-groups{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin-top:10px}.gg-actions button,.gg-group{min-height:46px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800}.gg-group{padding:8px;text-align:left}.gg-group.is-active{outline:3px solid #76508a}.gg-actions .primary{background:#eee5f4;border-color:#513667}.gg-actions button:focus-visible,.gg-room:focus-visible,.gg-group:focus-visible{outline:3px solid #76508a;outline-offset:2px}.gg-gate{padding:7px;border-radius:10px;background:#f1f3f5;font-size:.74rem}.gg-gate.pass{background:#e1f4e9}.gg-log{min-height:105px}.gg-hint{font-size:.8rem;color:var(--muted)}@media(max-width:860px){.gg-layout{grid-template-columns:1fr}.gg-hud{grid-template-columns:repeat(4,1fr)}}@media(max-width:560px){.gg-hud{grid-template-columns:repeat(2,1fr)}.gg-actions,.gg-gates,.gg-groups{grid-template-columns:1fr}.gg-board svg{height:330px}.gg-actions button,.gg-group{min-height:50px}}@media(prefers-reduced-motion:reduce){.gallery-gambit *{animation:none!important;transition:none!important}}`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-gallery-gambit]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true),a=$('.app-card',f);a.dataset.galleryGambit='1';a.dataset.category=APP.category;$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;$('.app-card-button',f).addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-gallery-gambit]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.ggBound)return;b.dataset.ggBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · museum route strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
const root=document.createElement('section');root.className='tool-panel gallery-gambit';root.innerHTML=`<div class="gg-hud">${['Day','Plans','Budget','Satisfaction','Access','Conservation','Score'].map((x,i)=>`<div class="gg-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="gg-layout"><section class="gg-panel"><div class="gg-brief"><p class="app-meta" data-day></p><h3>Build routes that work for people and objects.</h3><p data-target></p></div><div class="gg-board" data-board aria-label="Museum gallery map"></div><p class="gg-hint">Choose a group, then rooms in route order. Protecting or reopening a fragile gallery uses one planning action; protection returns one budget. Keyboard: arrows select rooms, 1–5 groups, A add room, C protect fragile room, U undo, Enter open doors.</p></section><aside class="gg-panel"><div class="gg-groups" data-groups></div><div class="result-card gg-log" aria-live="polite"></div><div class="gg-gates" data-gates></div><div class="gg-actions"><button data-a="add">Add selected room</button><button data-a="close">Protect selected fragile gallery</button><button data-a="undo">Undo route step</button><button data-a="clear">Clear active route</button><button data-a="recover">Call floor team</button><button class="primary" data-a="run">Open museum</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
let st,ended=false,keyHandler,closeHandler;
const current=()=>DAYS[st.day];
function log(a,b){$('.gg-log',root).innerHTML=`<strong>${a}</strong><p>${b}</p>`}
function reset(){st={day:0,turn:0,budget:DAYS[0].budget,satisfaction:50,access:100,conservation:100,score:0,recovery:true,unlock:false,selected:0,active:0,routes:[],closed:[],history:[]};ended=false;startDay()}
function startDay(){const d=current();Object.assign(st,{turn:0,budget:d.budget+(st.unlock?2:0),selected:0,active:0,routes:d.groups.map(()=>[]),closed:[],history:[]});log(d.name,'Assign every group a connected route, then open the museum.');draw()}
function snapshot(){return JSON.stringify({turn:st.turn,budget:st.budget,satisfaction:st.satisfaction,access:st.access,conservation:st.conservation,score:st.score,selected:st.selected,active:st.active,routes:st.routes,closed:st.closed})}
function room(id){return ROOMS.find(r=>r.id===id)}
function linked(a,b){return LINKS.some(x=>x.includes(a)&&x.includes(b))}
function add(){if(ended)return;const d=current(),r=ROOMS[st.selected],route=st.routes[st.active],g=d.groups[st.active];if(st.closed.includes(r.id))return log('Gallery protected.','Reopen it or choose another room.');if(route.includes(r.id))return log('Already on route.','Choose a different gallery.');if(route.length&&!linked(route.at(-1),r.id))return log('Route disconnected.','The next gallery must share a corridor with the last one.');if(g[3]&&!r.access)return log('Route inaccessible.','This group requires a step-free route.');if(st.turn>=d.turns)return log('Planning time exhausted.','Open the museum, undo, or call the floor team.');if(st.budget<1)return log('Budget exhausted.','Undo, protect an unused fragile gallery, or call the floor team.');st.history.push(snapshot());route.push(r.id);st.turn++;st.budget--;log('Gallery added.',`${r.name} is now stop ${route.length} for ${g[0]}.`);draw()}
function toggleClose(){if(ended)return;const d=current(),r=ROOMS[st.selected],isClosed=st.closed.includes(r.id);if(!r.fragile)return log('Standard gallery.','Only fragile galleries can be protected for conservation.');if(st.routes.some(x=>x.includes(r.id)))return log('Gallery already routed.','Clear affected routes before changing its protection status.');if(st.turn>=d.turns)return log('Planning time exhausted.','Protection changes require one planning action. Undo or call the floor team.');if(isClosed&&st.budget<1)return log('Reopening costs one budget.','Undo another choice or call the floor team first.');st.history.push(snapshot());st.closed=isClosed?st.closed.filter(x=>x!==r.id):[...st.closed,r.id];st.turn++;st.budget+=isClosed?-1:1;log(isClosed?'Gallery reopened.':'Fragile gallery protected.',isClosed?'Capacity returns at a budget and planning cost.':'Conservation improves and one budget returns, but one planning action and route option are spent.');draw()}
function undo(){if(!st.history.length||ended)return log('Nothing to undo.','No reversible planning step remains.');Object.assign(st,JSON.parse(st.history.pop()));log('Planning step reversed.','Routes, protection choices, planning time, and budget were restored.');draw()}
function clear(){if(ended)return;const route=st.routes[st.active];if(!route.length)return log('Route already empty.','Select another group or add a gallery.');st.history.push(snapshot());st.turn=Math.max(0,st.turn-route.length);st.budget+=route.length;st.routes[st.active]=[];log('Route cleared.','Planning time and budget were returned.');draw()}
function evaluate(){const d=current();let sat=0,access=100,cons=100,missing=0;d.groups.forEach((g,i)=>{const route=st.routes[i];if(route.length<2){missing++;return}let match=0;route.forEach(id=>{const r=room(id),over=Math.max(0,g[2]-r.cap);if(r.tags.includes(g[1]))match++;if(g[3]&&!r.access)access-=25;if(r.fragile)cons-=g[2]*3;sat-=over*7;cons-=over*(r.fragile?8:2)});sat+=35+match*18+route.length*5});cons+=st.closed.length*12;return {sat:Math.round(sat/d.groups.length),access:clamp(access,0,100),cons:clamp(cons,0,100),missing}}
function run(){if(ended)return;const d=current(),e=evaluate();st.satisfaction=e.sat;st.access=e.access;st.conservation=e.cons;if(e.missing)return log('Routes incomplete.',`${e.missing} group${e.missing===1?'':'s'} still need at least two connected galleries.`);const pass=e.sat>=d.target&&e.access>=85&&e.cons>=68&&st.budget>=0;st.score+=Math.max(0,e.sat*8+e.access*4+e.cons*4+st.budget*25);if(st.score>=2600)st.unlock=true;if(!pass)return finish(false,`Opening failed: satisfaction ${e.sat}, access ${e.access}, conservation ${e.cons}, budget ${st.budget}.`);if(st.day===DAYS.length-1)return finish(true,`All six museum days completed. Final score ${st.score}.`);st.day++;st.satisfaction=clamp(st.satisfaction+4,0,100);st.access=100;st.conservation=100;startDay()}
function recover(){if(ended||!st.recovery)return log('Floor team unavailable.','This recovery is available once per session.');st.recovery=false;st.score=Math.max(0,st.score-250);st.budget+=3;st.turn=Math.max(0,st.turn-2);log('Floor team deployed.','Three budget and two planning actions returned at a score cost.');draw()}
function finish(win,msg){ended=true;log(win?'Museum season complete.':'Opening cancelled.',msg);draw()}
function gates(){const d=current(),e=evaluate();return[{label:`Satisfaction ≥ ${d.target}`,pass:e.sat>=d.target},{label:'Access ≥ 85',pass:e.access>=85},{label:'Conservation ≥ 68',pass:e.cons>=68},{label:'Every route complete',pass:e.missing===0},{label:'Budget nonnegative',pass:st.budget>=0}]}
function draw(){const d=current(),e=evaluate(),selectedRoom=ROOMS[st.selected],selectedClosed=st.closed.includes(selectedRoom.id);$$('[data-h]',root).forEach((x,i)=>x.textContent=[`${st.day+1}/6`,`${st.turn}/${d.turns}`,st.budget,e.sat,e.access,e.cons,st.score][i]);$('[data-day]',root).textContent=d.name;$('[data-target]',root).textContent=`Target satisfaction ${d.target}. ${st.unlock?'Pop-up guide desk unlocked: +2 starting budget.':''}`;$('[data-groups]',root).innerHTML=d.groups.map((g,i)=>`<button class="gg-group ${i===st.active?'is-active':''}" data-g="${i}" type="button" aria-pressed="${i===st.active}"><strong>${g[0]}</strong><br><small>${g[1]} · size ${g[2]}${g[3]?' · step-free':''}</small><br><small>${st.routes[i].map(id=>room(id).name).join(' → ')||'No route'}</small></button>`).join('');$$('[data-g]',root).forEach(b=>b.onclick=()=>{st.active=+b.dataset.g;draw()});$('[data-board]',root).innerHTML=`<svg viewBox="0 0 680 380" role="group" aria-label="Museum plan">${LINKS.map(([a,b])=>{const A=room(a),B=room(b);return `<line class="gg-link" x1="${A.x}" y1="${A.y}" x2="${B.x}" y2="${B.y}"/>`}).join('')}${ROOMS.map((r,i)=>`<g class="gg-room ${i===st.selected?'is-selected':''} ${st.closed.includes(r.id)?'is-closed':''}" data-room="${i}" role="button" tabindex="0" aria-label="${r.name}, capacity ${r.cap}${r.access?', step-free':''}${r.fragile?', fragile':''}${st.closed.includes(r.id)?', protected':''}"><rect x="${r.x-58}" y="${r.y-28}" width="116" height="56" rx="13"/><text x="${r.x}" y="${r.y-4}" text-anchor="middle">${r.name}</text><text class="sub" x="${r.x}" y="${r.y+13}" text-anchor="middle">cap ${r.cap}${r.fragile?' · fragile':''}${st.closed.includes(r.id)?' · protected':''}</text></g>`).join('')}</svg>`;$$('[data-room]',root).forEach(n=>{n.onclick=()=>{st.selected=+n.dataset.room;draw()};n.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();st.selected=+n.dataset.room;draw()}}});$('[data-gates]',root).innerHTML=gates().map(g=>`<div class="gg-gate ${g.pass?'pass':''}">${g.pass?'✓':'○'} ${g.label}</div>`).join('');$$('[data-a]',root).forEach(b=>{const k=b.dataset.a;b.disabled=(ended&&k!=='restart')||(k==='recover'&&!st.recovery)||(k==='add'&&(st.turn>=d.turns||st.budget<1))||(k==='close'&&(!selectedRoom.fragile||st.routes.some(x=>x.includes(selectedRoom.id))||st.turn>=d.turns||(selectedClosed&&st.budget<1)))||(k==='undo'&&!st.history.length);if(k==='close')b.textContent=selectedClosed?'Reopen selected fragile gallery':'Protect selected fragile gallery'})}
root.addEventListener('click',e=>{const a=e.target.closest('[data-a]')?.dataset.a;if(!a)return;({add,close:toggleClose,undo,clear,recover,run,restart:reset}[a])()});
const interactive=t=>t?.closest?.('button,a,input,select,textarea,[contenteditable="true"]');keyHandler=e=>{if(!dialog.open||interactive(e.target))return;const map={ArrowRight:1,ArrowDown:1,ArrowLeft:-1,ArrowUp:-1};if(map[e.key]){e.preventDefault();st.selected=(st.selected+map[e.key]+ROOMS.length)%ROOMS.length;draw()}else if(/^[1-5]$/.test(e.key)&&+e.key<=current().groups.length){st.active=+e.key-1;draw()}else if(e.key.toLowerCase()==='a')add();else if(e.key.toLowerCase()==='c')toggleClose();else if(e.key.toLowerCase()==='u')undo();else if(e.key==='Enter')run()};document.addEventListener('keydown',keyHandler);closeHandler=()=>{document.removeEventListener('keydown',keyHandler);dialog.removeEventListener('close',closeHandler)};dialog.addEventListener('close',closeHandler);reset()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
