(() => {
'use strict';
const APP={name:'Glassline Studio',emoji:'🔥',category:'play',version:'1.0.0',summary:'Shape molten glass through heat, rotation, tools, color, and annealing before the piece slumps or cracks.',description:'A local-only glassblowing strategy game with six commissions, changing heat, rotation, wall thickness, color compatibility, timed tool actions, scoring, progression, a session unlock, meaningful failure, one costly recovery, touch, keyboard, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const JOBS=[
 {title:'Amber tumbler',goal:'A balanced cup with even walls and a warm amber trail.',shape:52,wall:58,color:'amber',budget:8,time:12},
 {title:'Sea-glass vase',goal:'Build height without thinning the neck. Finish in cool teal.',shape:68,wall:62,color:'teal',budget:9,time:13},
 {title:'Ruby paperweight',goal:'Compact, dense, and bright with minimal bubbles.',shape:35,wall:82,color:'ruby',budget:10,time:12},
 {title:'Smoke decanter',goal:'A tall body, narrow neck, and controlled charcoal veil.',shape:78,wall:55,color:'smoke',budget:11,time:14},
 {title:'Cobalt lantern',goal:'A broad vessel with durable walls and luminous cobalt.',shape:64,wall:72,color:'cobalt',budget:12,time:15},
 {title:'Aurora vessel',goal:'Balance height, thinness, two colors, and a flawless anneal.',shape:82,wall:48,color:'aurora',budget:14,time:16}
];
const COLORS={clear:{name:'Clear',heat:0,stress:0},amber:{name:'Amber',heat:2,stress:2},teal:{name:'Teal',heat:-1,stress:3},ruby:{name:'Ruby',heat:3,stress:5},smoke:{name:'Smoke',heat:-2,stress:4},cobalt:{name:'Cobalt',heat:1,stress:4},aurora:{name:'Aurora mix',heat:2,stress:7}};
function style(){if($('#glassline-style'))return;const e=document.createElement('style');e.id='glassline-style';e.textContent=`
.glassline{max-width:1120px;display:grid;gap:12px}.gl-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.gl-stat,.gl-card{border:1px solid var(--line);border-radius:17px;background:#fff}.gl-stat{padding:9px}.gl-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.gl-layout{display:grid;grid-template-columns:1.1fr .9fr;gap:12px}.gl-card{padding:15px}.gl-stage{position:relative;min-height:350px;border-radius:25px;overflow:hidden;background:radial-gradient(circle at 50% 70%,#ffb35c22,transparent 35%),linear-gradient(180deg,#17161f,#2d2030 65%,#4a2d28);border:1px solid #34243b}.gl-furnace{position:absolute;right:5%;top:8%;width:80px;height:120px;border-radius:35px 35px 18px 18px;background:radial-gradient(circle,#fff3a0 0,#ff8c32 35%,#7f2519 70%);box-shadow:0 0 40px #ff8a3d88}.gl-pipe{position:absolute;left:7%;right:18%;top:48%;height:8px;border-radius:99px;background:linear-gradient(90deg,#8c8c92,#d3d3d8)}.gl-glass{position:absolute;left:53%;top:38%;width:92px;height:112px;transform-origin:50% 10%;border-radius:45% 45% 38% 38%;background:linear-gradient(135deg,#fff8d5aa,#ffb44d99 45%,#dd543d99);border:3px solid rgba(255,255,255,.55);box-shadow:0 0 28px #ffb25388,inset 0 0 26px rgba(255,255,255,.35);transition:all .25s}.gl-glass.spin{animation:gl-spin .7s linear infinite}.gl-glass.crack:after{content:'';position:absolute;inset:12px 42px 8px 41px;background:#fff;clip-path:polygon(40% 0,70% 35%,48% 56%,80% 100%,32% 62%,50% 38%)}@keyframes gl-spin{to{transform:rotate(360deg)}}.gl-heat{position:absolute;left:5%;right:5%;bottom:7%;height:14px;border-radius:99px;background:#ffffff22;overflow:hidden}.gl-heat span{display:block;height:100%;background:linear-gradient(90deg,#6dd5ff,#ffd45c,#ff572f);transition:width .2s}.gl-label{position:absolute;left:5%;bottom:12%;color:white;font-weight:800}.gl-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.gl-grid button,.gl-actions button,.gl-colors button{min-height:46px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800}.gl-grid button[aria-pressed=true],.gl-colors button[aria-pressed=true]{outline:3px solid #ffb35c;background:#fff6e9}.gl-colors{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.gl-meter{height:10px;border-radius:99px;background:#ece8ef;overflow:hidden}.gl-meter span{display:block;height:100%;background:#d76a42;transition:width .25s}.gl-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.gl-actions .primary{background:#fff0df;border-color:#b85c35}.gl-log{min-height:112px}.gl-hint{font-size:.8rem;color:var(--muted)}
@media(max-width:840px){.gl-layout{grid-template-columns:1fr}.gl-hud{grid-template-columns:repeat(3,1fr)}.gl-stage{min-height:320px}}@media(max-width:520px){.gl-hud{grid-template-columns:repeat(2,1fr)}.gl-grid,.gl-actions{grid-template-columns:1fr}.gl-colors{grid-template-columns:repeat(2,1fr)}.gl-grid button,.gl-actions button,.gl-colors button{min-height:50px}}@media(prefers-reduced-motion:reduce){.glassline *{animation:none!important;transition:none!important}}
`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-glassline]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.glassline='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-glassline]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.glBound)return;b.dataset.glBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · material timing';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
 const root=document.createElement('section');root.className='tool-panel glassline';root.innerHTML=`<div class="gl-hud">${['Commission','Heat','Shape','Wall','Trust','Score'].map((x,i)=>`<div class="gl-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="gl-layout"><section class="gl-card"><div class="gl-stage" role="img" aria-label="Glassblowing bench with furnace, pipe, and molten vessel"><div class="gl-furnace"></div><div class="gl-pipe"></div><div class="gl-glass"></div><div class="gl-label">Working heat</div><div class="gl-heat"><span></span></div></div><h3 data-title></h3><p data-goal></p><div class="gl-grid"><button data-tool="heat">1. Reheat</button><button data-tool="spin">2. Spin</button><button data-tool="blow">3. Blow</button><button data-tool="shape">4. Shape</button><button data-tool="trim">5. Trim</button><button data-tool="cool">6. Cool</button></div><p class="gl-hint">Keys 1–6 use tools. C cycles color. Enter anneals. Backspace undoes the last action.</p></section><aside class="gl-card"><div class="result-card gl-log" aria-live="polite"></div><h3>Color trail</h3><div class="gl-colors">${Object.entries(COLORS).map(([k,v])=>`<button data-color="${k}">${v.name}</button>`).join('')}</div><h3>Stress</h3><div class="gl-meter"><span data-stress></span></div><div class="gl-actions"><button data-a="undo">Undo action</button><button data-a="inspect">Inspect walls</button><button class="primary" data-a="anneal">Anneal piece</button><button data-a="recover">Gather fresh glass</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
 let st,ended=false,timer=0,history=[];
 const log=(a,b='')=>{$('.gl-log',root).innerHTML=`<strong>${a}</strong><small>${b}</small>`};
 function reset(){clearInterval(timer);st={job:0,heat:68,shape:35,wall:76,stress:8,trust:3,score:0,color:'clear',actions:JOBS[0].budget,unlock:false,recovery:true};ended=false;history=[];startClock();log('Gather on the pipe.',JOBS[0].goal);draw()}
 function startClock(){clearInterval(timer);timer=setInterval(()=>{if(ended)return;st.heat-=1.4;if(st.heat<22){st.stress+=2;st.wall-=1}if(st.heat>92)st.stress+=2;if(st.stress>=100||st.wall<=0)fail('The piece cracked on the pipe.');draw()},1000)}
 function save(){history.push({...st});if(history.length>8)history.shift()}
 function tool(k){if(ended)return;if(st.actions<=0)return log('No bench time remains.','Anneal now or use the one recovery.');save();st.actions--;if(k==='heat'){st.heat+=22;st.stress+=st.heat>80?8:2}else if(k==='spin'){st.shape+=5;st.wall+=3;st.heat-=5;st.stress-=3}else if(k==='blow'){st.shape+=13;st.wall-=9;st.heat-=8;st.stress+=4}else if(k==='shape'){st.shape+=7;st.wall-=3;st.heat-=6;st.stress+=2}else if(k==='trim'){st.shape-=5;st.wall+=2;st.heat-=7;st.stress+=1}else if(k==='cool'){st.heat-=18;st.stress+=st.heat<35?9:-4}st.heat=clamp(st.heat,0,110);st.shape=clamp(st.shape,0,100);st.wall=clamp(st.wall,0,100);st.stress=clamp(st.stress,0,100);log(`${k[0].toUpperCase()+k.slice(1)} applied.`,`Heat ${Math.round(st.heat)} · shape ${Math.round(st.shape)} · wall ${Math.round(st.wall)}.`);draw()}
 function color(k){if(ended)return;if(k==='aurora'&&!st.unlock)return log('Aurora mix is locked.','Reach 650 score to unlock it this session.');save();st.color=k;st.heat+=COLORS[k].heat;st.stress+=COLORS[k].stress;log(`${COLORS[k].name} selected.`,'Color changes heat and stress.');draw()}
 function undo(){if(ended||!history.length)return log('Nothing to undo.','Use a tool or choose a color first.');st=history.pop();log('Last action undone.','Bench time and material state restored.');draw()}
 function inspect(){const j=JOBS[st.job],gap=Math.round(Math.abs(st.shape-j.shape)+Math.abs(st.wall-j.wall));log('Wall inspection.',`Target gap ${gap}. Stress ${Math.round(st.stress)}. ${st.actions} actions remain.`)}
 function anneal(){if(ended)return;const j=JOBS[st.job],colorFit=st.color===j.color||(j.color==='aurora'&&st.color==='aurora')?100:st.color==='clear'?45:65;const heatFit=100-Math.abs(st.heat-48)*2;const shapeFit=100-Math.abs(st.shape-j.shape)*2;const wallFit=100-Math.abs(st.wall-j.wall)*2;const quality=clamp(Math.round(shapeFit*.28+wallFit*.28+heatFit*.2+colorFit*.16-st.stress*.25+st.actions*2),0,100);if(quality<42)return fail('The anneal revealed a failed piece.');const gain=quality*2+st.actions*7;st.score+=gain;st.trust=clamp(st.trust+(quality>=78?1:0),0,5);if(st.score>=650)st.unlock=true;if(st.job===JOBS.length-1){ended=true;clearInterval(timer);log('Studio season complete.',`Final score ${st.score}. ${quality>=80?'Masterful control.':'A hard-won body of work.'}`);return draw()}st.job++;st.heat=68;st.shape=35;st.wall=76;st.stress=8;st.color='clear';st.actions=JOBS[st.job].budget;history=[];log(`Commission accepted · ${quality}%`,`Earned ${gain} points. ${JOBS[st.job].goal}`);draw()}
 function fail(msg){ended=true;clearInterval(timer);st.trust--;log(msg,st.recovery?'Use Gather fresh glass once, losing score and trust.':'Start a new session to try again.');draw()}
 function recover(){if(!ended||!st.recovery)return log('Recovery unavailable.','It can only restore a failed run once.');st.recovery=false;st.score=Math.max(0,st.score-180);st.trust=Math.max(1,st.trust-1);st.heat=62;st.shape=32;st.wall=72;st.stress=16;st.actions=Math.max(5,JOBS[st.job].budget-2);ended=false;history=[];startClock();log('Fresh gather prepared.','You lost score, trust, and bench time, but the commission continues.');draw()}
 function draw(){const j=JOBS[st.job],h=$$('[data-h]',root);[`${st.job+1}/${JOBS.length}`,Math.round(st.heat),Math.round(st.shape),Math.round(st.wall),st.trust,st.score].forEach((v,i)=>h[i].textContent=v);$('[data-title]',root).textContent=j.title;$('[data-goal]',root).textContent=j.goal;$('.gl-heat span',root).style.width=`${clamp(st.heat,0,100)}%`;$('[data-stress]',root).style.width=`${st.stress}%`;const glass=$('.gl-glass',root);glass.style.height=`${72+st.shape}px`;glass.style.width=`${Math.max(54,118-st.wall/2)}px`;glass.style.opacity=`${.55+st.heat/250}`;glass.classList.toggle('spin',!ended&&st.heat>35&&!matchMedia('(prefers-reduced-motion: reduce)').matches);glass.classList.toggle('crack',ended&&st.stress>=100);$$('[data-color]',root).forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.color===st.color));b.disabled=b.dataset.color==='aurora'&&!st.unlock});$$('[data-tool]',root).forEach(b=>b.disabled=ended)}
 $$('[data-tool]',root).forEach(b=>b.addEventListener('click',()=>tool(b.dataset.tool)));$$('[data-color]',root).forEach(b=>b.addEventListener('click',()=>color(b.dataset.color)));$('[data-a="undo"]',root).addEventListener('click',undo);$('[data-a="inspect"]',root).addEventListener('click',inspect);$('[data-a="anneal"]',root).addEventListener('click',anneal);$('[data-a="recover"]',root).addEventListener('click',recover);$('[data-a="restart"]',root).addEventListener('click',reset);
 let colorIndex=0;const key=e=>{if(!dialog.open)return;if(/^[1-6]$/.test(e.key)){e.preventDefault();tool(['heat','spin','blow','shape','trim','cool'][+e.key-1])}else if(e.key==='Enter'){e.preventDefault();anneal()}else if(e.key==='Backspace'){e.preventDefault();undo()}else if(e.key.toLowerCase()==='c'){colorIndex=(colorIndex+1)%Object.keys(COLORS).length;color(Object.keys(COLORS)[colorIndex])}};document.addEventListener('keydown',key);dialog.addEventListener('close',()=>{clearInterval(timer);document.removeEventListener('keydown',key)},{once:true});reset()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();