(() => {
  const APP = { name: 'Glyph Foundry', emoji: '🔣', category: 'play', version: '1.0.0', summary: 'Forge symbol orders by arranging glyph tiles under heat, budget, resonance, and flaw pressure.', description: 'A local spatial crafting game with shifting customer orders, draggable glyphs, heat and alloy tradeoffs, flaw recovery, adaptive scoring, session-only masterwork unlocks, SVG motion, keyboard and touch controls, optional audio, reduced-motion behavior, and teardown.' };
  const $ = (s) => document.querySelector(s);
  const label = (v) => v === 'play' ? 'Play' : v === 'useful' ? 'Useful' : 'Experiment';
  function style() {
    if ($('#glyph-foundry-styles')) return;
    const s = document.createElement('style');
    s.id = 'glyph-foundry-styles';
    s.textContent = `.glyph-card{animation:glyph-rise .24s ease both}.glyph-game{max-width:1060px;gap:14px}.glyph-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.glyph-stat{border:1px solid var(--line);border-radius:15px;background:#fff;padding:10px 12px}.glyph-stat span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.glyph-stat strong{display:block;margin-top:4px}.glyph-board{display:grid;grid-template-columns:1fr .92fr;gap:10px}.glyph-canvas{border:0;border-radius:26px;background:#17121f;color:white;padding:0;overflow:hidden;touch-action:none;box-shadow:inset 0 0 0 1px rgba(255,255,255,.14)}.glyph-canvas:focus-visible{outline:4px solid var(--accent);outline-offset:4px}.glyph-canvas svg{display:block;width:100%;height:min(56vh,500px);min-height:350px}.glyph-panel{border:1px solid var(--line);border-radius:18px;background:#fff;padding:13px}.glyph-tools,.glyph-orders,.glyph-tray{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.glyph-chip{border:1px solid var(--line);border-radius:999px;background:#fff;color:var(--ink);padding:8px 11px;font-weight:900}.glyph-chip.is-active{background:#111827;color:#fff}.glyph-log{min-height:98px;padding:17px 19px}.glyph-tray button{min-width:58px}.glyph-meter{height:12px;border-radius:999px;background:#ece7f7;overflow:hidden;margin-top:8px}.glyph-meter span{display:block;height:100%;width:40%;background:linear-gradient(90deg,#9af0d0,#ffd166,#f97316)}@media(max-width:780px){.glyph-hud{grid-template-columns:repeat(2,1fr)}.glyph-board{grid-template-columns:1fr}.glyph-canvas svg{height:54vh;min-height:340px}}@media(prefers-reduced-motion:reduce){.glyph-card{animation:none}.glyph-canvas svg{min-height:330px}}@keyframes glyph-rise{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}`;
    document.head.append(s);
  }
  function addCard() {
    const grid = $('#app-grid'), tpl = $('#app-card-template');
    if (!grid || !tpl || $('[data-glyph-card]')) return;
    const f = $('.filter.is-active')?.dataset.filter || 'all';
    if (f !== 'all' && f !== APP.category) return;
    style();
    const node = tpl.content.cloneNode(true), card = node.querySelector('.app-card');
    card.dataset.category = APP.category; card.dataset.glyphCard = 'true'; card.classList.add('glyph-card');
    node.querySelector('.app-icon').textContent = APP.emoji;
    node.querySelector('.app-meta').textContent = `${label(APP.category)} · v${APP.version}`;
    node.querySelector('.app-name').textContent = APP.name;
    node.querySelector('.app-summary').textContent = APP.summary;
    const btn = node.querySelector('.app-card-button');
    btn.setAttribute('aria-label', `Open ${APP.name}`);
    btn.addEventListener('click', open);
    grid.append(node);
  }
  function boot() {
    style(); addCard();
    document.querySelectorAll('.filter').forEach((b) => {
      if (b.dataset.glyphRefresh) return;
      b.dataset.glyphRefresh = '1';
      b.addEventListener('click', () => setTimeout(addCard, 0));
    });
  }
  function open() {
    const dialog = $('#app-dialog'), stage = $('#app-stage'), title = $('#dialog-title'), cat = $('#dialog-category'), desc = $('#dialog-description'), fb = $('#dialog-feedback');
    if (!dialog || !stage) return;
    title.textContent = APP.name; cat.textContent = `${label(APP.category)} · ${APP.emoji}`; desc.textContent = APP.description;
    fb.href = 'https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Glyph%20Foundry';
    stage.replaceChildren(); game(stage, dialog); dialog.showModal();
  }
  function game(stage, dialog) {
    const root = document.createElement('section');
    root.className = 'tool-panel glyph-game';
    root.innerHTML = `<div class="glyph-hud"><div class="glyph-stat"><span>Order</span><strong id="gf-order">1 / 6</strong></div><div class="glyph-stat"><span>Alloy</span><strong id="gf-alloy">12</strong></div><div class="glyph-stat"><span>Heat</span><strong id="gf-heat">0</strong></div><div class="glyph-stat"><span>Flaws</span><strong id="gf-flaws">0</strong></div><div class="glyph-stat"><span>Score</span><strong id="gf-score">0</strong></div><div class="glyph-stat"><span>Mode</span><strong id="gf-mode">Journeyman</strong></div></div><div class="glyph-board"><button class="glyph-canvas" type="button" aria-label="Glyph Foundry board. Use arrow keys to move the cursor, number keys to choose glyphs, Enter to place, Backspace to reclaim, F to fire, R to rework, and N for a new order."><svg role="img" aria-label="Animated glyph grid"></svg></button><div class="glyph-panel"><strong>Customer order</strong><p id="gf-brief"></p><div class="glyph-orders"><span class="glyph-chip">Match target traits</span><span class="glyph-chip">Avoid forbidden traits</span><span class="glyph-chip">Adjacency creates resonance</span><span class="glyph-chip">Flaws can be reworked</span></div><div class="glyph-meter"><span id="gf-meter"></span></div><strong style="display:block;margin-top:12px">Glyph tray</strong><div class="glyph-tray"></div><div class="glyph-tools"><button class="button button-secondary glyph-chip" type="button" data-act="fire">Fire order</button><button class="button button-secondary glyph-chip" type="button" data-act="rework">Rework flaw</button><button class="button button-secondary glyph-chip" type="button" data-act="new">New order</button></div></div></div><div class="result-card glyph-log" aria-live="polite"></div><div class="tool-actions"></div>`;
    stage.append(root);
    const svg = root.querySelector('svg'), board = root.querySelector('.glyph-canvas'), log = root.querySelector('.glyph-log'), tray = root.querySelector('.glyph-tray'), actions = root.querySelector('.tool-actions'), meter = root.querySelector('#gf-meter'), reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
    const glyphs = [
      { k:'1', mark:'△', name:'spire', traits:['sky','edge'], cost:2 }, { k:'2', mark:'○', name:'well', traits:['water','echo'], cost:2 },
      { k:'3', mark:'◇', name:'gem', traits:['light','edge'], cost:3 }, { k:'4', mark:'✶', name:'star', traits:['sky','light'], cost:3 },
      { k:'5', mark:'〰', name:'river', traits:['water','flow'], cost:2 }, { k:'6', mark:'⬡', name:'hive', traits:['echo','flow'], cost:3 }
    ];
    const patrons = ['Lighthouse guild','Rain archivist','Sky beekeeper','Glass ferry','Echo tailor','Canal astronomer'];
    const goals = [['light','sky'],['water','echo'],['sky','flow'],['edge','light'],['echo','flow'],['water','edge']];
    const st = { order:1, orders:6, alloy:12, heat:0, flaws:0, score:0, cursor:12, selected:0, master:false, audio:false, ac:null, anim:0, cells:Array(25).fill(null), target:[], avoid:'', patron:'' };
    actions.append(btn('Masterwork', master, true), btn('Sound off', sound, true));
    root.querySelectorAll('[data-act]').forEach((b) => b.addEventListener('click', () => action(b.dataset.act)));
    board.addEventListener('keydown', key); board.addEventListener('click', place); board.addEventListener('pointerdown', point); dialog.addEventListener('close', tear, { once:true });
    newOrder();
    function btn(t,f,sec){const b=document.createElement('button');b.type='button';b.className=sec?'button button-secondary':'button';b.textContent=t;b.addEventListener('click',f);return b;}
    function say(h){log.innerHTML=h;}
    function newOrder(){cancelAnimationFrame(st.anim); Object.assign(st,{alloy:st.master?10:12,heat:0,flaws:0,cursor:12,cells:Array(25).fill(null)}); const i=(st.order-1)%goals.length; st.target=goals[i]; st.avoid=['edge','water','echo','sky','flow','light'][(i+3)%6]; st.patron=patrons[i]; say(`<strong>${st.patron} commission opened.</strong><small>Forge ${st.target.join(' + ')} while avoiding ${st.avoid}. Resonant neighbors matter.</small>`); paint(); draw();}
    function paint(){root.querySelector('#gf-order').textContent=`${st.order} / ${st.orders}`; root.querySelector('#gf-alloy').textContent=st.alloy; root.querySelector('#gf-heat').textContent=st.heat; root.querySelector('#gf-flaws').textContent=st.flaws; root.querySelector('#gf-score').textContent=st.score; root.querySelector('#gf-mode').textContent=st.master?'Masterwork':'Journeyman'; root.querySelector('#gf-brief').textContent=`${st.patron} needs ${st.target.join(' and ')}. Avoid ${st.avoid}, keep heat below ${st.master?8:10}, and place matching glyphs beside each other for resonance.`; tray.replaceChildren(...glyphs.map((g,i)=>{const b=btn(`${g.k} ${g.mark} ${g.name}`,()=>{st.selected=i;paint();draw();},true); b.classList.toggle('is-active',i===st.selected); b.setAttribute('aria-label',`Choose ${g.name} glyph`); return b;})); meter.style.width=`${Math.min(100,scoreDraft().quality)}%`;}
    function place(){const g=glyphs[st.selected]; if(st.alloy<g.cost){say('<strong>Not enough alloy.</strong><small>Fire the current design or rework a flaw before placing more.</small>'); return;} const old=st.cells[st.cursor]; if(old) st.alloy+=old.cost; st.cells[st.cursor]=g; st.alloy-=g.cost; st.heat+=g.traits.includes(st.avoid)?2:1; if(g.traits.includes(st.avoid)) st.flaws+=1; beep(520); say(`<strong>${g.name} set into cell ${st.cursor+1}.</strong><small>${g.traits.join(' + ')} traits added. ${g.traits.includes(st.avoid)?'A forbidden resonance created a flaw.':'The alloy held cleanly.'}</small>`); paint(); draw();}
    function point(e){const r=svg.getBoundingClientRect(); const x=(e.clientX-r.left)/r.width, y=(e.clientY-r.top)/r.height; const c=Math.max(0,Math.min(4,Math.floor(x*5))), row=Math.max(0,Math.min(4,Math.floor(y*5))); st.cursor=row*5+c; paint(); draw();}
    function action(kind){if(kind==='fire')fire(); if(kind==='rework')rework(); if(kind==='new')newOrder();}
    function rework(){if(st.flaws<1||st.alloy<1){say('<strong>Rework unavailable.</strong><small>You need one flaw and one alloy to burn it clean.</small>'); return;} st.flaws-=1; st.alloy-=1; st.heat=Math.max(0,st.heat-3); beep(330); say('<strong>Flaw reworked.</strong><small>Alloy spent, heat dropped, and the commission recovered.</small>'); paint(); draw();}
    function scoreDraft(){const counts={}; let res=0, used=0; st.cells.forEach((g,i)=>{if(!g)return; used+=1; g.traits.forEach(t=>counts[t]=(counts[t]||0)+1); [1,5].forEach(d=>{const n=st.cells[i+d]; if(n&&n.traits.some(t=>g.traits.includes(t)))res+=1;});}); const match=st.target.reduce((s,t)=>s+(counts[t]||0),0)*18; const bad=(counts[st.avoid]||0)*16+st.flaws*12+Math.max(0,st.heat-(st.master?8:10))*10; const quality=Math.max(0,Math.min(100,match+res*6+used*2-bad)); return {quality,res};}
    function fire(){const q=scoreDraft(); if(!st.cells.some(Boolean)){say('<strong>No glyphs placed.</strong><small>Set at least one symbol before firing the kiln.</small>'); return;} const pass=q.quality>=60; const gain=pass?Math.round(q.quality*2+st.alloy*8+q.res*10-st.flaws*15):Math.round(q.quality-st.flaws*20); st.score=Math.max(0,st.score+gain); beep(pass?820:220); if(pass&&st.order<st.orders){st.order+=1; say(`<strong>Order accepted: ${q.quality}% quality.</strong><small>${gain} points earned. The next customer wants a different trait balance.</small>`); newOrder();} else if(pass){say(`<strong>Foundry run complete: ${st.score}.</strong><small>${st.score>=980?'Masterwork unlocked for this session.':'Reach 980 to unlock masterwork pressure.'}</small>`);} else {st.flaws+=1; st.heat=Math.max(0,st.heat-2); say(`<strong>Commission rejected: ${q.quality}% quality.</strong><small>Recover by reworking flaws, changing adjacency, or starting a fresh order.</small>`);} paint(); draw();}
    function master(){if(!st.master&&st.score<980)return say('<strong>Masterwork locked.</strong><small>Score 980 in journeyman mode to unlock tighter alloy and heat limits.</small>'); st.master=!st.master; st.order=1; newOrder(); say(`<strong>${st.master?'Masterwork':'Journeyman'} mode active.</strong><small>${st.master?'Less alloy, harsher heat ceiling, larger scoring upside.':'Standard pacing restored.'}</small>`);}
    function key(e){const k=e.key.toLowerCase(); if(k>='1'&&k<='6'){e.preventDefault();st.selected=Number(k)-1;paint();draw();} if(k==='arrowright'){e.preventDefault();st.cursor=Math.min(24,st.cursor+1);draw();} if(k==='arrowleft'){e.preventDefault();st.cursor=Math.max(0,st.cursor-1);draw();} if(k==='arrowdown'){e.preventDefault();st.cursor=Math.min(24,st.cursor+5);draw();} if(k==='arrowup'){e.preventDefault();st.cursor=Math.max(0,st.cursor-5);draw();} if(k==='enter'){e.preventDefault();place();} if(k==='backspace'){e.preventDefault();const g=st.cells[st.cursor]; if(g){st.alloy+=Math.max(1,g.cost-1);st.cells[st.cursor]=null;paint();draw();say('<strong>Glyph reclaimed.</strong><small>Some alloy was lost in the pull.</small>');}} if(k==='f'){e.preventDefault();fire();} if(k==='r'){e.preventDefault();rework();} if(k==='n'){e.preventDefault();newOrder();}}
    function draw(){const w=720,h=520,cell=86,gap=8,ox=118,oy=38,t=performance.now()/850; let html=`<rect width="${w}" height="${h}" rx="28" fill="#17121f"/><defs><radialGradient id="gf-glow"><stop offset="0" stop-color="#ffd166" stop-opacity=".7"/><stop offset="1" stop-color="#9af0d0" stop-opacity=".05"/></radialGradient></defs><circle cx="${360+Math.sin(t)*24}" cy="${268+Math.cos(t*.8)*18}" r="190" fill="url(#gf-glow)"/>`; for(let i=0;i<25;i++){const x=ox+(i%5)*(cell+gap), y=oy+Math.floor(i/5)*(cell+gap), g=st.cells[i], cur=i===st.cursor; html+=`<rect x="${x}" y="${y}" width="${cell}" height="${cell}" rx="18" fill="${cur?'#2e2745':'#241b31'}" stroke="${cur?'#ffd166':'rgba(255,255,255,.18)'}" stroke-width="${cur?4:1}"/>`; if(g) html+=`<text x="${x+cell/2}" y="${y+52}" text-anchor="middle" font-size="38" fill="white">${g.mark}</text><text x="${x+cell/2}" y="${y+73}" text-anchor="middle" font-size="10" fill="#c7f9df">${g.traits.join('/')}</text>`;} const q=scoreDraft(); html+=`<text x="28" y="38" fill="#fff" font-size="15" font-weight="800">${st.patron}</text><text x="28" y="62" fill="#c7f9df" font-size="12">Target: ${st.target.join(' + ')}</text><text x="28" y="82" fill="#ffd6a5" font-size="12">Avoid: ${st.avoid}</text><text x="28" y="496" fill="#fff" font-size="13">Draft quality ${q.quality}% · resonance ${q.res}</text>`; svg.innerHTML=html; if(!reduced) st.anim=requestAnimationFrame(draw);}
    function sound(){const b=actions.lastElementChild, A=window.AudioContext||window.webkitAudioContext; if(!A){say('<strong>Sound is not available here.</strong><small>The foundry still works without audio.</small>');return;} st.audio=!st.audio; b.textContent=st.audio?'Sound on':'Sound off'; b.setAttribute('aria-pressed',String(st.audio)); if(st.audio){st.ac ||= new A(); st.ac.resume(); beep(660);}}
    function beep(f){if(!st.audio||!st.ac)return; const now=st.ac.currentTime,o=st.ac.createOscillator(),g=st.ac.createGain(); o.type='triangle'; o.frequency.setValueAtTime(f,now); g.gain.setValueAtTime(.0001,now); g.gain.exponentialRampToValueAtTime(.06,now+.02); g.gain.exponentialRampToValueAtTime(.0001,now+.18); o.connect(g).connect(st.ac.destination); o.start(now); o.stop(now+.2);}
    function tear(){cancelAnimationFrame(st.anim); if(st.ac&&st.ac.state!=='closed')st.ac.close();}
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot, { once:true }); else boot();
})();
