(() => {
'use strict';
const APP={name:'Graft Garden',emoji:'🌿',category:'play',version:'1.0.0',summary:'Match rootstocks and scions, align living tissue, manage disease risk, and grow six orchard commissions.',description:'A local-only botanical grafting strategy game with six seasonal commissions, compatibility, cambium alignment, cut choice, binding tension, aftercare, weather, limited stock, trust, scoring, a session unlock, delayed outcomes, meaningful failure, one costly recovery, touch, keyboard, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const ROOTS=[
{id:'dwarf',name:'Dwarf M9',vigor:1,hardy:2,disease:2,cost:2,family:'apple'},
{id:'semi',name:'Semi-dwarf M26',vigor:2,hardy:3,disease:1,cost:2,family:'apple'},
{id:'pear',name:'Quince A',vigor:2,hardy:2,disease:2,cost:3,family:'pear'},
{id:'stone',name:'Myrobalan',vigor:4,hardy:3,disease:1,cost:3,family:'stone'}];
const SCIONS=[
{id:'crisp',name:'Crisp apple',family:'apple',yield:4,flavor:3,hardy:2},
{id:'heirloom',name:'Heirloom apple',family:'apple',yield:2,flavor:5,hardy:3},
{id:'pear',name:'Dessert pear',family:'pear',yield:3,flavor:4,hardy:2},
{id:'plum',name:'Early plum',family:'stone',yield:4,flavor:3,hardy:2},
{id:'bridge',name:'Bridge interstem',family:'bridge',yield:1,flavor:1,hardy:4}];
const CUTS=[{id:'whip',name:'Whip & tongue',align:4,risk:2,time:3},{id:'cleft',name:'Cleft',align:3,risk:1,time:2},{id:'bud',name:'Chip bud',align:2,risk:1,time:1},{id:'side',name:'Side veneer',align:3,risk:3,time:2}];
const DAYS=[
{brief:'Build a compact school orchard with reliable fruit and low maintenance.',family:'apple',need:{vigor:1,hardy:2,yield:3,flavor:2},weather:'mild',risk:1},
{brief:'Preserve an heirloom apple for a windy community garden.',family:'apple',need:{vigor:2,hardy:3,yield:2,flavor:4},weather:'wind',risk:2},
{brief:'Create a dessert pear tree for a small courtyard.',family:'pear',need:{vigor:2,hardy:2,yield:3,flavor:4},weather:'dry',risk:2},
{brief:'Establish an early plum with strong spring recovery.',family:'stone',need:{vigor:3,hardy:3,yield:4,flavor:2},weather:'cold',risk:3},
{brief:'Rescue an incompatible heritage cutting using an interstem.',family:'bridge',need:{vigor:2,hardy:4,yield:2,flavor:3},weather:'wet',risk:3},
{brief:'Deliver a resilient demonstration orchard balancing yield, flavor, and long-term health.',family:'any',need:{vigor:3,hardy:4,yield:4,flavor:4},weather:'swing',risk:4}
];
function style(){if($('#graft-garden-style'))return;const e=document.createElement('style');e.id='graft-garden-style';e.textContent=`
.graft-garden{max-width:1120px;display:grid;gap:12px}.gg-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.gg-stat,.gg-card{border:1px solid var(--line);border-radius:17px;background:#fff}.gg-stat{padding:9px}.gg-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.gg-layout{display:grid;grid-template-columns:1.05fr .95fr;gap:12px}.gg-card{padding:15px}.gg-orchard{position:relative;min-height:310px;border-radius:24px;overflow:hidden;background:linear-gradient(#dff5ef 0 58%,#c9ad7a 58%);color:#17382d}.gg-orchard svg{position:absolute;inset:0;width:100%;height:100%}.gg-copy{position:relative;z-index:2;min-height:310px;display:grid;align-content:start;gap:6px;padding:18px;pointer-events:none}.gg-copy strong{max-width:600px;font-size:clamp(1.25rem,3vw,2rem)}.gg-controls{display:grid;gap:10px}.gg-group{display:grid;gap:6px}.gg-options{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.gg-option{min-height:58px;border:1px solid var(--line);border-radius:12px;background:#fff;padding:9px;text-align:left;font-weight:800}.gg-option[aria-pressed=true]{border-color:#23845b;background:#e4f7ee}.gg-option small{display:block;color:var(--muted);font-weight:650;margin-top:3px}.gg-sliders{display:grid;grid-template-columns:1fr 1fr;gap:8px}.gg-sliders label{font-size:.78rem;font-weight:800}.gg-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.gg-actions button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800;padding:9px}.gg-actions .primary{background:#dff5e8;border-color:#23845b}.gg-log{min-height:110px}.gg-meter{height:9px;border-radius:999px;background:#e5e7eb;overflow:hidden}.gg-meter span{display:block;height:100%;background:linear-gradient(90deg,#b7782d,#23845b);transform-origin:left}.gg-hint{font-size:.72rem;color:var(--muted);margin:0}.gg-tags{display:flex;flex-wrap:wrap;gap:5px}.gg-tag{font-size:.68rem;border-radius:999px;background:#eef4f0;padding:4px 7px}.gg-tree{transform-origin:50% 90%;animation:gg-sway 4s ease-in-out infinite alternate}.gg-callus{opacity:.15}.gg-growing .gg-callus{animation:gg-heal .8s ease-out forwards}@keyframes gg-sway{to{transform:rotate(1.3deg)}}@keyframes gg-heal{to{opacity:.9;transform:scale(1.12)}}
@media(max-width:820px){.gg-layout{grid-template-columns:1fr}.gg-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:520px){.gg-hud{grid-template-columns:repeat(2,1fr)}.gg-options,.gg-actions,.gg-sliders{grid-template-columns:1fr 1fr}.gg-orchard,.gg-copy{min-height:260px}.gg-option{min-height:52px;padding:8px}}
@media(prefers-reduced-motion:reduce){.graft-garden *{animation:none!important;transition:none!important}}
`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-graft-garden]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.graftGarden='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-graft-garden]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.ggBound)return;b.dataset.ggBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · botanical strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
 const root=document.createElement('section');root.className='tool-panel graft-garden';root.innerHTML=`<div class="gg-hud">${['Commission','Hours','Stock','Trust','Score','Unlock'].map((x,i)=>`<div class="gg-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="gg-layout"><section class="gg-card"><div class="gg-orchard" aria-label="Animated graft preview"><svg viewBox="0 0 600 360" aria-hidden="true"><g class="gg-tree"><path d="M300 330 C292 270 300 220 296 150" fill="none" stroke="#6f4b2e" stroke-width="24" stroke-linecap="round"/><path d="M296 178 C245 135 210 120 165 104 M299 150 C344 112 390 100 438 82" fill="none" stroke="#6f4b2e" stroke-width="14" stroke-linecap="round"/><circle class="gg-callus" cx="297" cy="177" r="18" fill="#d7be74"/><g fill="#27875f"><circle cx="160" cy="102" r="30"/><circle cx="215" cy="125" r="25"/><circle cx="440" cy="82" r="34"/><circle cx="390" cy="105" r="26"/></g><g data-fruit fill="#ef6a45"></g></g></svg><div class="gg-copy"><span class="eyebrow">Living union</span><strong data-preview>Select rootstock, scion, and cut</strong><div class="gg-tags" data-tags></div></div></div><p class="gg-hint">Use Tab and Enter to choose materials. Arrow keys adjust alignment and binding controls. Outcomes appear after a short healing phase.</p></section><aside class="gg-card gg-controls"><div class="result-card gg-log" aria-live="polite"></div><div class="gg-group"><span class="eyebrow">Rootstock</span><div class="gg-options" data-roots></div></div><div class="gg-group"><span class="eyebrow">Scion</span><div class="gg-options" data-scions></div></div><div class="gg-group"><span class="eyebrow">Cut</span><div class="gg-options" data-cuts></div></div><div class="gg-sliders"><label>Cambium alignment <input data-align type="range" min="0" max="4" value="2"></label><label>Binding tension <input data-bind type="range" min="0" max="4" value="2"></label></div><div class="gg-meter" aria-label="Predicted graft fit"><span data-meter></span></div><div class="gg-actions"><button class="primary" data-a="graft">Set graft</button><button data-a="undo">Undo</button><button data-a="recover">Use nursery reserve</button><button data-a="restart">New orchard</button></div></aside></div>`;stage.append(root);
 let st,history=[],timer=0,ended=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 function reset(){clearTimeout(timer);st={day:0,hours:18,stock:12,trust:74,score:0,unlock:false,recovery:true,root:0,scion:0,cut:0,align:2,bind:2};history=[];ended=false;log(DAYS[0].brief,'Choose compatible living material, then balance precision, time, and disease exposure.');draw()}
 function snap(){history.push(JSON.stringify(st));if(history.length>10)history.shift()}
 function compatible(){const r=ROOTS[st.root],s=SCIONS[st.scion],d=DAYS[st.day];if(s.family==='bridge')return st.unlock&&d.family==='bridge';return r.family===s.family&&(d.family==='any'||d.family===s.family)}
 function metrics(){const r=ROOTS[st.root],s=SCIONS[st.scion],c=CUTS[st.cut],d=DAYS[st.day];const precision=c.align+st.align-Math.abs(st.bind-2);const weatherPenalty={mild:0,wind:1,dry:1,cold:2,wet:2,swing:2}[d.weather];const disease=clamp(d.risk+c.risk+r.disease+weatherPenalty-st.bind-(st.unlock?1:0),0,10);let fit=100-Math.abs(r.vigor-d.need.vigor)*9-Math.abs(r.hardy+s.hardy-d.need.hardy*2)*5-Math.abs(s.yield-d.need.yield)*7-Math.abs(s.flavor-d.need.flavor)*7-disease*5+precision*5;if(!compatible())fit-=48;if(st.align<2)fit-=20;if(st.bind===0||st.bind===4)fit-=12;return{fit:clamp(Math.round(fit),0,100),disease,precision,cost:r.cost+1,time:c.time+Math.max(0,4-st.align)}}
 function choose(type,i){if(ended)return;snap();st[type]=i;draw()}
 function graft(){if(ended)return;const m=metrics();if(st.hours<m.time||st.stock<m.cost)return log('The bench is short on materials.','Use the reserve once or redesign with a cheaper combination.');st.hours-=m.time;st.stock-=m.cost;$$('[data-a],.gg-option,input',root).forEach(x=>x.disabled=true);$('.gg-orchard',root).classList.add('gg-growing');timer=setTimeout(()=>{if(!root.isConnected)return;$('.gg-orchard',root).classList.remove('gg-growing');st.score+=m.fit*19+Math.max(0,8-m.disease)*24;st.trust=clamp(st.trust+(m.fit>=75?8:m.fit<48?-23:-7),0,100);if(st.score>=5200&&!st.unlock)st.unlock=true;if(st.trust<=0)return finish(false);if(st.day>=DAYS.length-1)return finish(true);st.day++;st.hours=18;history=[];log(m.fit>=75?'The union calluses cleanly and pushes healthy growth.':m.fit>=52?'The graft survives, but vigor and disease control are uneven.':'The union fails and the commission loses confidence.',`Fit ${m.fit}, disease pressure ${m.disease}. Next: ${DAYS[st.day].brief}`);draw()},reduced?80:760)}
 function undo(){if(ended||!history.length)return;st=JSON.parse(history.pop());draw()}
 function recover(){if(ended||!st.recovery)return;st.recovery=false;st.trust=clamp(st.trust-14,0,100);st.hours+=6;st.stock+=5;history=[];log('The nursery opens its reserve bench.','Fresh stock and labor restore options, but the emergency order costs trust.');draw()}
 function finish(success){ended=true;clearTimeout(timer);const strong=success&&st.trust>=60&&st.score>=10500;log(strong?'The orchard board names you lead propagator.':success?'The orchard opens with a mixed but credible collection.':'Repeated graft failures close the propagation bench.',`Final score ${st.score}, trust ${st.trust}. Replay with stronger compatibility, alignment, and disease control.`);draw()}
 function log(a,b){const l=$('.gg-log',root);l.replaceChildren(Object.assign(document.createElement('strong'),{textContent:a}),Object.assign(document.createElement('small'),{textContent:b}))}
 function draw(){const m=metrics(),d=DAYS[st.day],vals=[`${st.day+1}/6`,`${st.hours}h`,st.stock,st.trust,st.score,st.unlock?'Bridge tape':'Locked'];$$('[data-h]',root).forEach((e,i)=>e.textContent=vals[i]);$('[data-roots]',root).innerHTML=ROOTS.map((x,i)=>`<button class="gg-option" data-root="${i}" aria-pressed="${st.root===i}">${x.name}<small>vigor ${x.vigor} · hardy ${x.hardy} · stock ${x.cost}</small></button>`).join('');$('[data-scions]',root).innerHTML=SCIONS.map((x,i)=>`<button class="gg-option" data-scion="${i}" aria-pressed="${st.scion===i}" ${x.id==='bridge'&&!st.unlock?'disabled':''}>${x.name}<small>yield ${x.yield} · flavor ${x.flavor} · hardy ${x.hardy}</small></button>`).join('');$('[data-cuts]',root).innerHTML=CUTS.map((x,i)=>`<button class="gg-option" data-cut="${i}" aria-pressed="${st.cut===i}">${x.name}<small>align ${x.align} · risk ${x.risk} · ${x.time}h</small></button>`).join('');$('[data-align]',root).value=st.align;$('[data-bind]',root).value=st.bind;$('[data-meter]',root).style.transform=`scaleX(${m.fit/100})`;$('[data-preview]',root).textContent=`${ROOTS[st.root].name} + ${SCIONS[st.scion].name} · ${CUTS[st.cut].name}`;$('[data-tags]',root).innerHTML=[d.weather,compatible()?'compatible':'incompatible',`risk ${m.disease}`,`fit ${m.fit}`].map(x=>`<span class="gg-tag">${x}</span>`).join('');const fruit=$('[data-fruit]',root);fruit.innerHTML=Array.from({length:Math.floor(m.fit/22)},(_,i)=>`<circle cx="${170+i*68}" cy="${105+(i%2)*42}" r="9"/>`).join('');$$('[data-a]',root).forEach(b=>b.disabled=ended);$('[data-a="undo"]',root).disabled=ended||!history.length;$('[data-a="recover"]',root).disabled=ended||!st.recovery;bind()}
 function bind(){$$('[data-root]',root).forEach(b=>b.onclick=()=>choose('root',+b.dataset.root));$$('[data-scion]',root).forEach(b=>b.onclick=()=>choose('scion',+b.dataset.scion));$$('[data-cut]',root).forEach(b=>b.onclick=()=>choose('cut',+b.dataset.cut));$('[data-align]',root).onchange=e=>{snap();st.align=+e.target.value;draw()};$('[data-bind]',root).onchange=e=>{snap();st.bind=+e.target.value;draw()};$('[data-a="graft"]',root).onclick=graft;$('[data-a="undo"]',root).onclick=undo;$('[data-a="recover"]',root).onclick=recover;$('[data-a="restart"]',root).onclick=reset}
 const close=()=>{clearTimeout(timer)};dialog.addEventListener('close',close,{once:true});reset()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
