(()=>{'use strict';
const APP={name:'Habitat Mosaic',emoji:'🦋',category:'play',version:'1.0.0',summary:'Restore six landscapes by linking habitat, water, shelter, and migration corridors before seasonal shocks arrive.',description:'A local spatial ecology strategy game with six landscapes, a 5×5 habitat grid, adjacency and corridor scoring, limited actions and budget, seasonal disturbances, species goals, progression, exact undo, one-use recovery, keyboard and touch controls, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const CASES=[
{name:'Meadow Return',turns:8,budget:11,target:48,species:'Butterfly',need:{flower:5,water:1,shelter:1,corridor:3},shock:'dry'},
{name:'Frog Passage',turns:9,budget:13,target:55,species:'Tree frog',need:{flower:2,water:4,shelter:2,corridor:4},shock:'heat'},
{name:'Hedgehog Night',turns:9,budget:14,target:60,species:'Hedgehog',need:{flower:2,water:1,shelter:5,corridor:5},shock:'storm'},
{name:'Bee Commons',turns:10,budget:15,target:66,species:'Native bee',need:{flower:7,water:2,shelter:2,corridor:5},shock:'dry'},
{name:'Otter Thread',turns:11,budget:17,target:72,species:'River otter',need:{flower:1,water:7,shelter:4,corridor:6},shock:'storm'},
{name:'Living Mosaic',turns:12,budget:19,target:78,species:'Mixed guild',need:{flower:6,water:5,shelter:5,corridor:8},shock:'heat'}];
const TYPES={empty:{label:'Open',icon:'·',cost:0},flower:{label:'Flower',icon:'✿',cost:1},water:{label:'Water',icon:'≈',cost:2},shelter:{label:'Shelter',icon:'⌂',cost:2},corridor:{label:'Corridor',icon:'↔',cost:1}};
function style(){if($('#habitat-mosaic-style'))return;const e=document.createElement('style');e.id='habitat-mosaic-style';e.textContent=`.habitat-mosaic{max-width:1100px;display:grid;gap:12px}.hm-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.hm-stat,.hm-panel{background:#fff;border:1px solid var(--line);border-radius:17px}.hm-stat{padding:9px}.hm-stat span{display:block;font-size:.61rem;font-weight:900;text-transform:uppercase;letter-spacing:.06em;color:var(--muted)}.hm-layout{display:grid;grid-template-columns:1.05fr .95fr;gap:12px}.hm-panel{padding:14px}.hm-brief{padding:15px;border-radius:16px;background:linear-gradient(135deg,#173f35,#477f5d);color:white}.hm-grid{display:grid;grid-template-columns:repeat(5,minmax(48px,1fr));gap:6px;margin-top:12px}.hm-cell{aspect-ratio:1;border:1px solid #b9c8bf;border-radius:12px;background:#f4f7f4;font-size:1.45rem;font-weight:900;position:relative}.hm-cell[data-type=flower]{background:#fff0b8}.hm-cell[data-type=water]{background:#cdebf5}.hm-cell[data-type=shelter]{background:#d9c9b3}.hm-cell[data-type=corridor]{background:#d9ecd9}.hm-cell.shock{box-shadow:inset 0 0 0 4px #b94a3d}.hm-tools,.hm-actions,.hm-gates{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:10px}.hm-tools button[aria-pressed=true]{background:#285d48;color:#fff}.hm-actions button{min-height:46px}.hm-actions .primary{background:#daf0df;border-color:#285d48}.hm-gate{padding:8px;border-radius:10px;background:#f1f3f2;font-size:.76rem}.hm-gate.pass{background:#daf0df}.hm-log{min-height:120px}.hm-map-note{font-size:.8rem;color:var(--muted)}.hm-cell:focus-visible,.habitat-mosaic button:focus-visible{outline:3px solid #285d48;outline-offset:2px}@media(max-width:850px){.hm-layout{grid-template-columns:1fr}.hm-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:520px){.hm-hud{grid-template-columns:repeat(2,1fr)}.hm-grid{grid-template-columns:repeat(5,minmax(44px,1fr));gap:4px;overflow:auto}.hm-tools,.hm-actions,.hm-gates{grid-template-columns:1fr}.hm-cell{min-width:44px}}@media(prefers-reduced-motion:reduce){.habitat-mosaic *{animation:none!important;transition:none!important}}`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-habitat-mosaic]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true),a=$('.app-card',f);a.dataset.habitatMosaic='1';a.dataset.category=APP.category;$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;$('.app-card-button',f).addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-habitat-mosaic]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.hmBound)return;b.dataset.hmBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · spatial ecology';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel habitat-mosaic';root.innerHTML=`<div class="hm-hud">${['Landscape','Actions','Budget','Season','Score','Streak'].map((x,i)=>`<div class="hm-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="hm-layout"><section class="hm-panel"><div class="hm-brief"><p class="app-meta" data-case></p><h3>Build a connected refuge before the fourth season.</h3><p data-brief></p></div><div class="hm-grid" data-grid role="grid" aria-label="Five by five habitat restoration grid"></div><p class="hm-map-note">Choose a habitat tool, then tap a cell. Arrow keys move focus; Space or Enter builds. Disturbance strikes after every third action.</p></section><aside class="hm-panel"><div class="hm-tools" data-tools aria-label="Habitat tools"></div><div class="hm-log result-card" aria-live="polite"></div><div class="hm-gates" data-gates></div><div class="hm-actions"><button data-a="undo">Undo action</button><button data-a="adapt">Emergency adaptation</button><button data-a="survey">Survey network</button><button class="primary" data-a="submit">Open habitat</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
let st,ended=false,failed=false,keyHandler,clickHandler,closeHandler;const current=()=>CASES[st.case],idx=(r,c)=>r*5+c,neighbors=i=>{const r=Math.floor(i/5),c=i%5;return[[r-1,c],[r+1,c],[r,c-1],[r,c+1]].filter(([a,b])=>a>=0&&a<5&&b>=0&&b<5).map(([a,b])=>idx(a,b))};
function seed(){const g=Array(25).fill('empty');g[12]='corridor';g[6]='flower';g[18]='shelter';return g}
function reset(){st={case:0,actions:0,budget:0,season:1,score:0,streak:0,tool:'flower',cursor:12,grid:seed(),damaged:[],history:[],recovery:true,unlock:false};ended=false;failed=false;startCase()}
function startCase(){const c=current();st.actions=c.turns;st.budget=c.budget+(st.unlock?2:0);st.season=1;st.grid=seed();st.damaged=[];st.history=[];failed=false;log(c.name,`${c.species} needs a resilient network. The forecast calls for ${c.shock}.`);draw()}
function snapshot(){return JSON.stringify({actions:st.actions,budget:st.budget,season:st.season,score:st.score,streak:st.streak,tool:st.tool,cursor:st.cursor,grid:st.grid,damaged:st.damaged})}
function counts(){const o={flower:0,water:0,shelter:0,corridor:0};st.grid.forEach(x=>{if(o[x]!==undefined)o[x]++});return o}
function connected(){const active=st.grid.map((x,i)=>x!=='empty'&&!st.damaged.includes(i)?i:null).filter(x=>x!==null);if(!active.length)return 0;const seen=new Set([active[0]]),q=[active[0]];while(q.length){neighbors(q.shift()).forEach(n=>{if(!seen.has(n)&&st.grid[n]!=='empty'&&!st.damaged.includes(n)){seen.add(n);q.push(n)}})}return seen.size}
function metrics(){const c=counts(),conn=connected(),edges=st.grid.reduce((n,x,i)=>n+(x!=='empty'?neighbors(i).filter(j=>j>i&&st.grid[j]!=='empty').length:0),0),diversity=['flower','water','shelter'].filter(k=>c[k]>0).length;return{c,conn,edges,diversity,quality:clamp(Math.round(conn*4+edges*2+diversity*8-st.damaged.length*7),0,100)}}
function gates(){const n=current().need,m=metrics();return[{label:`Quality ≥ ${current().target}`,pass:m.quality>=current().target},{label:`Flowers ≥ ${n.flower}`,pass:m.c.flower>=n.flower},{label:`Water ≥ ${n.water}`,pass:m.c.water>=n.water},{label:`Shelter ≥ ${n.shelter}`,pass:m.c.shelter>=n.shelter},{label:`Connected habitat ≥ ${n.corridor}`,pass:m.conn>=n.corridor}]}
function shock(){const occupied=st.grid.map((x,i)=>x!=='empty'&&!st.damaged.includes(i)?i:null).filter(x=>x!==null);if(!occupied.length)return;const c=current(),rank=occupied.sort((a,b)=>{const vulnerability=i=>c.shock==='dry'?(st.grid[i]==='water'?-2:st.grid[i]==='flower'?2:0):c.shock==='heat'?(st.grid[i]==='shelter'?-2:st.grid[i]==='water'?1:0):(neighbors(i).filter(n=>st.grid[n]!=='empty').length<2?2:0);return vulnerability(b)-vulnerability(a)||a-b});const hit=rank[0];if(!st.damaged.includes(hit))st.damaged.push(hit);st.season=Math.min(4,st.season+1);log(`${c.shock[0].toUpperCase()+c.shock.slice(1)} disturbance.`,`One vulnerable habitat tile was stressed. Adapt or route around it.`)}
function build(i){if(ended||failed)return;if(st.actions<=0)return log('No actions remain.','Open the habitat, undo, or use emergency adaptation.');const cost=TYPES[st.tool].cost,old=st.grid[i],refund=TYPES[old].cost;if(st.budget+refund<cost)return log('Budget too low.',`This tile costs ${cost}. Replace a costly tile or choose a cheaper tool.`);st.history.push(snapshot());st.budget=st.budget+refund-cost;st.actions--;st.grid[i]=st.tool;st.cursor=i;st.damaged=st.damaged.filter(x=>x!==i);if(st.actions>0&&st.actions%3===0)shock();else log('Habitat placed.',`${TYPES[st.tool].label} added at row ${Math.floor(i/5)+1}, column ${i%5+1}.`);draw()}
function undo(){if(!st.history.length||ended||failed)return log('Nothing to undo.','No reversible restoration action remains.');Object.assign(st,JSON.parse(st.history.pop()));log('Action reversed.','Budget, season, disturbance, score, and grid restored.');draw()}
function adapt(){if(ended||!st.recovery||(!failed&&st.actions>0))return log('Adaptation unavailable.',!st.recovery?'It is available once per session.':'Use it after failure or when actions are exhausted.');failed=false;st.recovery=false;st.history=[];st.score=Math.max(0,st.score-200);st.actions=Math.max(st.actions,3);st.budget+=2;st.damaged=[];log('Emergency adaptation deployed.','Stress cleared, two budget restored, and at least three actions remain.');draw()}
function survey(){const m=metrics();log('Network survey.',`${m.conn} connected tiles, ${m.edges} links, quality ${m.quality}. ${st.damaged.length} tile${st.damaged.length===1?' is':'s are'} stressed.`)}
function submit(){if(ended||failed)return;const pass=gates().every(x=>x.pass);if(!pass){failed=true;st.streak=0;st.history=[];log('Habitat opening failed.','Use emergency adaptation or begin a new session.');draw();return}const q=metrics().quality;st.score+=q*10+st.actions*30+st.budget*12;st.streak++;if(st.streak>=3)st.unlock=true;if(st.case===CASES.length-1){ended=true;log('Restoration season complete.',`All six landscapes opened. Final score ${st.score}.`);draw();return}st.case++;startCase()}
function log(a,b){$('.hm-log',root).innerHTML=`<strong>${a}</strong><p>${b}</p>`}
function draw(){const c=current();$$('[data-h]',root).forEach((x,i)=>x.textContent=[`${st.case+1}/6`,st.actions,st.budget,st.season,st.score,st.streak][i]);$('[data-case]',root).textContent=`${c.name} · ${c.species}`;$('[data-brief]',root).textContent=`Need ${c.need.flower} flower, ${c.need.water} water, ${c.need.shelter} shelter, and at least ${c.need.corridor} connected habitat tiles. Forecast: ${c.shock}.`;$('[data-tools]',root).innerHTML=Object.entries(TYPES).filter(([k])=>k!=='empty').map(([k,v])=>`<button data-tool="${k}" aria-pressed="${st.tool===k}">${v.icon} ${v.label} · ${v.cost}</button>`).join('');$('[data-grid]',root).innerHTML=st.grid.map((t,i)=>`<button class="hm-cell${st.damaged.includes(i)?' shock':''}" role="gridcell" data-cell="${i}" data-type="${t}" tabindex="${i===st.cursor?0:-1}" aria-label="Row ${Math.floor(i/5)+1}, column ${i%5+1}: ${TYPES[t].label}${st.damaged.includes(i)?', stressed':''}">${TYPES[t].icon}</button>`).join('');$('[data-gates]',root).innerHTML=gates().map(g=>`<div class="hm-gate ${g.pass?'pass':''}">${g.pass?'✓':'○'} ${g.label}</div>`).join('')}
clickHandler=e=>{const cell=e.target.closest('[data-cell]'),tool=e.target.closest('[data-tool]'),a=e.target.closest('[data-a]');if(cell)return build(Number(cell.dataset.cell));if(tool){st.tool=tool.dataset.tool;draw();return}if(!a)return;({undo,adapt,survey,submit,restart:reset}[a.dataset.a]||(()=>{}))()};root.addEventListener('click',clickHandler);
keyHandler=e=>{if(dialog.open===false)return;const cell=e.target.closest('.hm-cell');if(cell&&['ArrowRight','ArrowLeft','ArrowUp','ArrowDown',' ','Enter'].includes(e.key)){e.preventDefault();let i=Number(cell.dataset.cell),r=Math.floor(i/5),c=i%5;if(e.key==='ArrowRight')c=(c+1)%5;else if(e.key==='ArrowLeft')c=(c+4)%5;else if(e.key==='ArrowDown')r=(r+1)%5;else if(e.key==='ArrowUp')r=(r+4)%5;else return build(i);st.cursor=r*5+c;draw();$(`[data-cell="${st.cursor}"]`,root)?.focus()}};document.addEventListener('keydown',keyHandler);
closeHandler=()=>{root.removeEventListener('click',clickHandler);document.removeEventListener('keydown',keyHandler);dialog.removeEventListener('close',closeHandler)};dialog.addEventListener('close',closeHandler,{once:true});reset()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
