(() => {
'use strict';
const APP={name:'Harbor Pilot',emoji:'⚓',category:'play',version:'1.1.0',summary:'Guide working ships through wind, current, traffic, and narrow channels without grounding or collision.',description:'A local-only harbor navigation strategy game with six missions, continuous vessel motion, wind and current drift, throttle and rudder control, moving traffic, fuel, hull, trust, scoring, progression, a session bow-thruster unlock, meaningful failure, one costly tug recovery, touch, keyboard, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const MISSIONS=[
 {title:'Dawn ferry',goal:'Dock at Pier A with hull above 75 and fuel above 35.',wind:[.02,.01],current:[.015,0],traffic:1,time:55,dock:[86,18]},
 {title:'Container arrival',goal:'Thread the west buoys and berth the freighter at Pier B.',wind:[-.02,.015],current:[.01,.015],traffic:2,time:62,dock:[84,76]},
 {title:'Storm ambulance',goal:'Reach the hospital quay quickly while preserving hull integrity.',wind:[.03,.025],current:[-.015,.02],traffic:2,time:48,dock:[18,16]},
 {title:'Night tanker',goal:'Use low speed near the refinery berth and avoid wake penalties.',wind:[-.025,-.015],current:[.02,-.01],traffic:3,time:68,dock:[16,80]},
 {title:'Regatta crossing',goal:'Cross dense traffic and dock without entering the exclusion zone.',wind:[.018,-.025],current:[-.012,.02],traffic:4,time:70,dock:[86,20]},
 {title:'Gale escort',goal:'Bring the rescue ship home through severe drift. Bow thruster available.',wind:[.04,.03],current:[-.025,.025],traffic:4,time:72,dock:[82,78]}
];
function style(){if($('#harbor-pilot-style'))return;const e=document.createElement('style');e.id='harbor-pilot-style';e.textContent=`
.harbor-pilot{max-width:1120px;display:grid;gap:12px}.hp-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.hp-stat,.hp-card{border:1px solid var(--line);border-radius:17px;background:#fff}.hp-stat{padding:9px}.hp-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.hp-layout{display:grid;grid-template-columns:1.25fr .75fr;gap:12px}.hp-card{padding:15px}.hp-water{position:relative;min-height:430px;border-radius:25px;overflow:hidden;background:linear-gradient(145deg,#0d5269,#167b8c 55%,#0b3d55);border:1px solid #0a4458;touch-action:none}.hp-grid{position:absolute;inset:0;background-image:linear-gradient(#ffffff0c 1px,transparent 1px),linear-gradient(90deg,#ffffff0c 1px,transparent 1px);background-size:10% 10%}.hp-shore{position:absolute;background:#b99e71;border:4px solid #7a684f}.hp-shore.a{left:-6%;top:-8%;width:43%;height:27%;border-radius:0 0 50% 0}.hp-shore.b{right:-8%;bottom:-10%;width:48%;height:34%;border-radius:55% 0 0 0}.hp-dock{position:absolute;width:38px;height:54px;border-radius:7px;background:#f3d17b;border:3px solid #6d5221;transform:translate(-50%,-50%)}.hp-buoy{position:absolute;width:15px;height:15px;border-radius:50%;background:#ffdb66;border:2px solid #6d4f00;transform:translate(-50%,-50%);box-shadow:0 0 0 5px #ffffff22}.hp-zone{position:absolute;left:43%;top:34%;width:18%;height:30%;border:2px dashed #ff9b8f;border-radius:50%;background:#ff4c3a18}.hp-ship,.hp-traffic{position:absolute;transform:translate(-50%,-50%);transition:filter .15s}.hp-ship{width:38px;height:18px;border-radius:60% 22% 22% 60%;background:#fff4cf;border:3px solid #203a45;z-index:5;box-shadow:0 7px 14px #001c2e55}.hp-ship:after{content:'';position:absolute;right:-10px;top:4px;border-left:12px solid #203a45;border-top:4px solid transparent;border-bottom:4px solid transparent}.hp-traffic{width:28px;height:13px;border-radius:50% 20% 20% 50%;background:#f27c65;border:2px solid #6d2d27}.hp-controls{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.hp-controls button,.hp-actions button{min-height:48px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800}.hp-controls button[aria-pressed=true]{outline:3px solid #42b8d0;background:#ebfbff}.hp-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.hp-actions .primary{background:#e8f9ff;border-color:#267d93}.hp-meter{height:10px;border-radius:99px;background:#e4edf0;overflow:hidden}.hp-meter span{display:block;height:100%;background:#2588a1;transition:width .2s}.hp-log{min-height:112px}.hp-note{font-size:.8rem;color:var(--muted)}
@media(max-width:840px){.hp-layout{grid-template-columns:1fr}.hp-hud{grid-template-columns:repeat(3,1fr)}.hp-water{min-height:390px}}@media(max-width:520px){.hp-hud{grid-template-columns:repeat(2,1fr)}.hp-controls{grid-template-columns:repeat(2,1fr)}.hp-actions{grid-template-columns:1fr}.hp-water{min-height:360px}.hp-controls button,.hp-actions button{min-height:52px}}@media(prefers-reduced-motion:reduce){.harbor-pilot *{animation:none!important;transition:none!important}}
`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-harbor-pilot]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.harborPilot='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-harbor-pilot]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.hpBound)return;b.dataset.hpBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · navigation simulation';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
 const root=document.createElement('section');root.className='tool-panel harbor-pilot';root.innerHTML=`<div class="hp-hud">${['Mission','Time','Fuel','Hull','Trust','Score'].map((x,i)=>`<div class="hp-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="hp-layout"><section class="hp-card"><div class="hp-water" role="application" tabindex="0" aria-label="Harbor chart. Use arrow keys or controls to steer the ship."><div class="hp-grid"></div><div class="hp-shore a"></div><div class="hp-shore b"></div><div class="hp-zone" aria-hidden="true"></div><div class="hp-dock"></div><div class="hp-ship"></div></div><h3 data-title></h3><p data-goal></p><p class="hp-note">Arrow keys steer and change throttle. Space pauses. B uses the unlocked bow thruster. Enter attempts docking.</p></section><aside class="hp-card"><div class="result-card hp-log" aria-live="polite"></div><h3>Helm</h3><div class="hp-controls"><button data-c="left">Turn left</button><button data-c="ahead">Throttle +</button><button data-c="right">Turn right</button><button data-c="astern">Throttle −</button><button data-c="pause">Pause</button><button data-c="thruster">Bow thruster</button></div><h3>Throttle</h3><div class="hp-meter"><span data-throttle></span></div><h3>Hull</h3><div class="hp-meter"><span data-hull></span></div><div class="hp-actions"><button data-a="scan">Sound traffic horn</button><button class="primary" data-a="dock">Attempt docking</button><button data-a="recover">Call harbor tug</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
 let st,timer=0,ended=false,paused=false,traffic=[];
 const water=$('.hp-water',root),ship=$('.hp-ship',root),dock=$('.hp-dock',root),log=(a,b='')=>{$('.hp-log',root).innerHTML=`<strong>${a}</strong><small>${b}</small>`};
 function newMission(index=0,carry=null){clearInterval(timer);const m=MISSIONS[index];st={mission:index,x:index%2?18:22,y:index%3?24:76,angle:index%2?12:-18,speed:.35,throttle:32,fuel:100,hull:100,trust:carry?.trust??3,score:carry?.score??0,time:m.time,unlock:carry?.unlock??false,recovery:carry?.recovery??true,thruster:3};ended=false;paused=false;makeTraffic();placeMarkers();timer=setInterval(tick,120);log(m.title,m.goal);draw()}
 function makeTraffic(){traffic.forEach(t=>t.el.remove());traffic=[];for(let i=0;i<MISSIONS[st.mission].traffic;i++){const el=document.createElement('div');el.className='hp-traffic';water.append(el);traffic.push({el,x:30+i*15,y:20+(i*23)%62,dx:(i%2?.12:-.1),dy:(i%3-1)*.035})}}
 function placeMarkers(){const m=MISSIONS[st.mission];dock.style.left=m.dock[0]+'%';dock.style.top=m.dock[1]+'%';$$('.hp-buoy',root).forEach(e=>e.remove());[[37,24],[42,39],[39,61],[46,77]].forEach(([x,y])=>{const b=document.createElement('div');b.className='hp-buoy';b.style.left=x+'%';b.style.top=y+'%';water.append(b)})}
 function helm(k){if(ended)return;if(k==='left')st.angle-=10;if(k==='right')st.angle+=10;if(k==='ahead')st.throttle=clamp(st.throttle+12,0,100);if(k==='astern')st.throttle=clamp(st.throttle-15,0,100);if(k==='pause')paused=!paused;if(k==='thruster'){if(!st.unlock)return log('Bow thruster locked.','Reach 700 score this session.');if(st.thruster<=0)return log('Thruster reserve empty.','Three bursts are available per mission.');st.thruster--;st.x+=Math.cos((st.angle+90)*Math.PI/180)*3;st.y+=Math.sin((st.angle+90)*Math.PI/180)*3;st.fuel-=4;log('Bow thruster fired.',`${st.thruster} bursts remain.`)}draw()}
 function tick(){if(ended||paused)return;const m=MISSIONS[st.mission],rad=st.angle*Math.PI/180,target=.06+st.throttle/135;st.speed+=(target-st.speed)*.12;st.x+=Math.cos(rad)*st.speed+m.wind[0]+m.current[0];st.y+=Math.sin(rad)*st.speed+m.wind[1]+m.current[1];st.fuel-=.035+st.throttle*.0008;st.time-=.12;traffic.forEach(t=>{t.x+=t.dx;t.y+=t.dy;if(t.x<8||t.x>92)t.dx*=-1;if(t.y<10||t.y>90)t.dy*=-1;const d=Math.hypot(st.x-t.x,st.y-t.y);if(d<5){st.hull-=2.2;st.trust=Math.max(0,st.trust-.02)}});if(st.x<5||st.x>95||st.y<7||st.y>93){st.hull-=2.4;st.speed*=.7}const inZone=st.x>43&&st.x<61&&st.y>34&&st.y<64;if(inZone&&st.mission>=4){st.trust=Math.max(0,st.trust-.025);st.score=Math.max(0,st.score-1)}if(st.throttle>72&&Math.hypot(st.x-m.dock[0],st.y-m.dock[1])<14){st.trust=Math.max(0,st.trust-.02);st.score=Math.max(0,st.score-1)}if(st.fuel<=0)fail('The engine went dry in the channel.');else if(st.hull<=0)fail('The vessel grounded beyond recovery.');else if(st.time<=0)fail('The harbor window closed.');draw()}
 function attemptDock(){if(ended)return;const m=MISSIONS[st.mission],dist=Math.hypot(st.x-m.dock[0],st.y-m.dock[1]);if(dist>8)return log('Too far from the berth.',`Close another ${Math.ceil(dist-8)} chart units.`);if(st.throttle>45)return log('Approach too fast.','Reduce throttle below 45 before docking.');const quality=clamp(Math.round(100-dist*7-Math.max(0,st.throttle-20)*.7-(100-st.hull)*.5+st.fuel*.12),0,100);if(quality<38)return fail('The docking approach damaged the vessel.');const gain=quality*2+Math.round(st.fuel)+Math.round(st.time*2);st.score+=gain;st.trust=clamp(st.trust+(quality>=78?1:0),0,5);if(st.score>=700)st.unlock=true;if(st.mission===MISSIONS.length-1){ended=true;clearInterval(timer);log('Harbor season complete.',`Final score ${st.score}. ${quality>=80?'Master pilotage.':'A hard-earned license.'}`);return draw()}const carry={score:st.score,trust:st.trust,unlock:st.unlock,recovery:st.recovery};newMission(st.mission+1,carry);log(`Berth secured · ${quality}%`,`Earned ${gain} points. ${MISSIONS[st.mission].goal}`);draw()}
 function fail(msg){ended=true;clearInterval(timer);st.trust=Math.max(0,st.trust-1);log(msg,st.recovery?'Call the harbor tug once, losing score and trust.':'Start a new session to try again.');draw()}
 function recover(){if(!ended||!st.recovery)return log('Tug unavailable.','It can restore one failed mission per session.');st.recovery=false;st.score=Math.max(0,st.score-220);st.trust=Math.max(1,st.trust-1);st.x=24;st.y=72;st.angle=-18;st.throttle=22;st.fuel=58;st.hull=62;st.time=Math.max(30,MISSIONS[st.mission].time*.65);ended=false;paused=false;timer=setInterval(tick,120);log('Harbor tug released the vessel.','Score, trust, fuel, hull, and time were reduced.');draw()}
 function draw(){const m=MISSIONS[st.mission],h=$$('[data-h]',root);[`${st.mission+1}/${MISSIONS.length}`,Math.ceil(st.time),Math.max(0,Math.round(st.fuel)),Math.max(0,Math.round(st.hull)),Math.round(st.trust),st.score].forEach((v,i)=>h[i].textContent=v);$('[data-title]',root).textContent=m.title;$('[data-goal]',root).textContent=m.goal;ship.style.left=st.x+'%';ship.style.top=st.y+'%';ship.style.transform=`translate(-50%,-50%) rotate(${st.angle}deg)`;traffic.forEach(t=>{t.el.style.left=t.x+'%';t.el.style.top=t.y+'%';t.el.style.transform=`translate(-50%,-50%) rotate(${Math.atan2(t.dy,t.dx)*180/Math.PI}deg)`});$('[data-throttle]',root).style.width=st.throttle+'%';$('[data-hull]',root).style.width=clamp(st.hull,0,100)+'%';$('[data-c="pause"]',root).textContent=paused?'Resume':'Pause';$('[data-c="thruster"]',root).disabled=!st.unlock||ended;$$('[data-c]',root).forEach(b=>{if(b.dataset.c!=='thruster')b.disabled=ended});$('[data-a="dock"]',root).disabled=ended}
 $$('[data-c]',root).forEach(b=>b.addEventListener('click',()=>helm(b.dataset.c)));$('[data-a="dock"]',root).addEventListener('click',attemptDock);$('[data-a="recover"]',root).addEventListener('click',recover);$('[data-a="restart"]',root).addEventListener('click',()=>newMission(0));$('[data-a="scan"]',root).addEventListener('click',()=>{if(ended)return;st.fuel=Math.max(0,st.fuel-2);traffic.forEach(t=>t.el.style.filter='drop-shadow(0 0 8px white)');setTimeout(()=>traffic.forEach(t=>t.el.style.filter=''),650);log('Traffic horn sounded.','Nearby vessels are highlighted briefly at a small fuel cost.')});
 const key=e=>{if(!dialog.open)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','Enter','b','B'].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')helm('left');if(e.key==='ArrowRight')helm('right');if(e.key==='ArrowUp')helm('ahead');if(e.key==='ArrowDown')helm('astern');if(e.key===' ')helm('pause');if(e.key==='Enter')attemptDock();if(e.key==='b'||e.key==='B')helm('thruster')};document.addEventListener('keydown',key);const cleanup=()=>{clearInterval(timer);document.removeEventListener('keydown',key);dialog.removeEventListener('close',cleanup)};dialog.addEventListener('close',cleanup);newMission(0)
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();