(() => {
  const APP={name:'Kitchen Pass',emoji:'🍳',category:'play',version:'1.0.0',summary:'Orchestrate a tiny dinner service across burners, ovens, prep, timing, quality, and guest patience.',description:'A local kitchen-management strategy game with three service modes, simultaneous orders, four stations, ingredient and heat tradeoffs, doneness, holding quality, guest patience, scoring, failure recovery, adaptive rushes, a session-only tasting-menu unlock, touch, pointer and keyboard controls, reduced-motion behavior, optional local audio, and teardown.'};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  function css(){if($('#kp-styles'))return;const s=document.createElement('style');s.id='kp-styles';s.textContent=`.kp-card{animation:kp-in .24s ease both}.kp-game{max-width:1120px;gap:14px}.kp-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.kp-stat,.kp-board,.kp-panel,.kp-log{border:1px solid var(--line);border-radius:18px;background:#fff}.kp-stat{padding:9px 11px}.kp-stat span{display:block;color:var(--muted);font-size:.6rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.kp-stat strong{display:block;margin-top:3px}.kp-layout{display:grid;grid-template-columns:1.25fr .75fr;gap:12px}.kp-board{padding:12px;background:linear-gradient(160deg,#3f1d0b,#7c2d12);color:#fff}.kp-orders{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.kp-order{border:1px solid rgba(255,255,255,.25);border-radius:15px;padding:10px;background:rgba(255,255,255,.1);min-height:126px}.kp-order.is-selected{outline:3px solid #fde68a}.kp-order strong,.kp-order small{display:block}.kp-meter{height:8px;background:rgba(255,255,255,.2);border-radius:999px;overflow:hidden;margin:7px 0}.kp-meter i{display:block;height:100%;background:#fde68a}.kp-stations{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:10px}.kp-station{border:1px solid rgba(255,255,255,.25);border-radius:15px;padding:10px;background:rgba(0,0,0,.16);min-height:105px}.kp-station button{width:100%;min-height:42px;margin-top:8px;border:0;border-radius:12px;font-weight:900}.kp-panel{padding:14px;display:grid;gap:10px;align-content:start}.kp-modes,.kp-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.kp-panel button{min-height:44px;border:1px solid var(--line);border-radius:14px;background:#fff;font-weight:900}.kp-panel button.is-active{box-shadow:0 0 0 3px #c2410c inset;background:#fff7ed}.kp-panel button[disabled]{opacity:.45}.kp-help,.kp-summary{font-size:.82rem;color:var(--muted);margin:0}.kp-summary{border:1px dashed var(--line);border-radius:12px;padding:10px;background:#fafafa}.kp-log{padding:14px;min-height:90px}.kp-log small{display:block;margin-top:5px}@media(max-width:900px){.kp-layout{grid-template-columns:1fr}.kp-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:620px){.kp-orders{grid-template-columns:1fr}.kp-hud{grid-template-columns:repeat(2,1fr)}.kp-stations{grid-template-columns:1fr}.kp-actions{grid-template-columns:1fr 1fr}}@media(prefers-reduced-motion:reduce){.kp-card{animation:none!important}}@keyframes kp-in{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}`;document.head.append(s)}
  function addCard(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-kp-card]'))return;const f=$('.filter.is-active')?.dataset.filter||'all';if(f!=='all'&&f!==APP.category)return;css();const n=t.content.cloneNode(true),c=$('.app-card',n);c.dataset.category=APP.category;c.dataset.kpCard='true';c.classList.add('kp-card');$('.app-icon',n).textContent=APP.emoji;$('.app-meta',n).textContent=`Play · v${APP.version}`;$('.app-name',n).textContent=APP.name;$('.app-summary',n).textContent=APP.summary;const b=$('.app-card-button',n);b.setAttribute('aria-label',`Open ${APP.name}`);b.onclick=open;g.append(n)}
  function boot(){css();let tries=0;const r=()=>{addCard();if(!$('[data-kp-card]')&&tries++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.kpRefresh)return;b.dataset.kpRefresh='1';b.addEventListener('click',()=>setTimeout(addCard,0))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');if(!d||!s)return;$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent=`Play · ${APP.emoji}`;$('#dialog-description').textContent=APP.description;$('#dialog-feedback').href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Kitchen%20Pass';s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel kp-game';root.innerHTML=`<div class="kp-hud"><div class="kp-stat"><span>Minute</span><strong id="kp-minute">1 / 12</strong></div><div class="kp-stat"><span>Coins</span><strong id="kp-coins">18</strong></div><div class="kp-stat"><span>Reputation</span><strong id="kp-rep">50</strong></div><div class="kp-stat"><span>Waste</span><strong id="kp-waste">0</strong></div><div class="kp-stat"><span>Combo</span><strong id="kp-combo">0</strong></div><div class="kp-stat"><span>Score</span><strong id="kp-score">0</strong></div></div><div class="kp-layout"><div class="kp-board"><div class="kp-orders" aria-label="Active guest orders"></div><div class="kp-stations" aria-label="Kitchen stations"></div></div><div class="kp-panel"><div class="kp-modes" aria-label="Service modes"></div><p class="kp-help">Select an order, then send its next step to a station. Advance time carefully: food cooks, holds, cools, and can burn while guests lose patience. Serve only when every step is complete.</p><div class="kp-actions"><button data-act="advance">Advance minute</button><button data-act="serve">Serve selected</button><button data-act="expedite">Expedite · 3</button><button data-act="recover">Staff meal recovery</button><button data-act="sound" aria-pressed="false">Sound off</button><button data-act="restart">Restart</button></div><div class="kp-summary" aria-live="polite"></div><div class="kp-log result-card" aria-live="polite"><strong>Doors open.</strong><small>Select an order and assign its first preparation step.</small></div></div></div>`;stage.append(root);
    const ordersBox=$('.kp-orders',root),stationsBox=$('.kp-stations',root),log=$('.kp-log',root),summary=$('.kp-summary',root);
    const recipes=[{name:'Garden pasta',steps:[['Prep',2],['Burner',3],['Pass',1]],value:12},{name:'Roast bowl',steps:[['Prep',1],['Oven',4],['Pass',1]],value:14},{name:'Seared fish',steps:[['Prep',2],['Burner',2],['Pass',1]],value:16},{name:'Flatbread',steps:[['Prep',1],['Oven',3],['Pass',2]],value:13},{name:'Tasting trio',steps:[['Prep',2],['Burner',2],['Oven',2],['Pass',2]],value:22,locked:true}];
    const modes={training:{name:'Training',minutes:14,patience:16,coins:22},service:{name:'Service',minutes:12,patience:13,coins:18},rush:{name:'Rush',minutes:10,patience:10,coins:16,locked:true}};
    const stationNames=['Prep','Burner','Oven','Pass'];
    const state={mode:'service',minute:1,coins:18,rep:50,waste:0,combo:0,score:0,selected:0,orders:[],stations:{},nextId:1,sound:false,ac:null,unlocked:false,tasting:false,ended:false};
    const note=(a,b)=>log.innerHTML=`<strong>${a}</strong><small>${b}</small>`;
    const tone=(f=440,d=.08)=>{if(!state.sound)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;state.ac||=new AC();state.ac.resume();const o=state.ac.createOscillator(),g=state.ac.createGain();o.frequency.value=f;g.gain.setValueAtTime(.0001,state.ac.currentTime);g.gain.exponentialRampToValueAtTime(.04,state.ac.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,state.ac.currentTime+d);o.connect(g).connect(state.ac.destination);o.start();o.stop(state.ac.currentTime+d+.02)};
    function newOrder(force){const pool=recipes.filter(r=>!r.locked||state.tasting),r=force||pool[Math.floor(Math.random()*pool.length)],m=modes[state.mode];return{id:state.nextId++,recipe:r,step:0,progress:0,patience:m.patience-Math.floor(Math.random()*3),quality:100,ready:false,served:false}}
    function reset(){const m=modes[state.mode];state.minute=1;state.coins=m.coins;state.rep=50;state.waste=0;state.combo=0;state.score=0;state.selected=0;state.orders=[newOrder(),newOrder(),newOrder()];state.stations={Prep:null,Burner:null,Oven:null,Pass:null};state.ended=false;render();note('Fresh service started.','Sequence prep, cooking, and pass work without letting food or guests wait too long.')}
    function renderModes(){const box=$('.kp-modes',root);box.replaceChildren();Object.entries(modes).forEach(([k,m])=>{const b=document.createElement('button');b.textContent=m.name+(m.locked&&!state.unlocked?' 🔒':'');b.disabled=!!(m.locked&&!state.unlocked);b.classList.toggle('is-active',state.mode===k);b.onclick=()=>{state.mode=k;reset();renderModes()};box.append(b)})}
    function renderOrders(){ordersBox.replaceChildren();state.orders.forEach((o,i)=>{const d=document.createElement('button');d.type='button';d.className='kp-order';d.classList.toggle('is-selected',state.selected===i);d.disabled=o.served;const next=o.ready?'Ready to serve':(o.recipe.steps[o.step]?.[0]||'Complete');const pct=Math.max(0,Math.min(100,o.patience/(modes[state.mode].patience)*100));d.innerHTML=`<strong>${o.recipe.name}</strong><small>Next: ${next}</small><div class="kp-meter"><i style="width:${pct}%"></i></div><small>Patience ${Math.max(0,o.patience)} · Quality ${Math.max(0,Math.round(o.quality))}</small>`;d.onclick=()=>{state.selected=i;render()};ordersBox.append(d)})}
    function renderStations(){stationsBox.replaceChildren();stationNames.forEach(name=>{const slot=state.stations[name],d=document.createElement('div');d.className='kp-station';if(slot){const o=state.orders.find(x=>x.id===slot.id);d.innerHTML=`<strong>${name}</strong><small>${o?o.recipe.name:'Order'} · ${slot.remaining} min</small><div class="kp-meter"><i style="width:${Math.max(8,100-slot.remaining*20)}%"></i></div>`}else d.innerHTML=`<strong>${name}</strong><small>Available</small>`;const b=document.createElement('button');b.textContent=slot?'Occupied':'Assign selected';b.disabled=!!slot||state.ended;b.onclick=()=>assign(name);d.append(b);stationsBox.append(d)})}
    function render(){renderOrders();renderStations();const max=modes[state.mode].minutes;$('#kp-minute').textContent=`${state.minute} / ${max}`;$('#kp-coins').textContent=state.coins;$('#kp-rep').textContent=Math.max(0,Math.round(state.rep));$('#kp-waste').textContent=state.waste;$('#kp-combo').textContent=state.combo;$('#kp-score').textContent=Math.round(state.score);const o=state.orders[state.selected];summary.textContent=o?`${o.recipe.name}: step ${Math.min(o.step+1,o.recipe.steps.length)} of ${o.recipe.steps.length}. ${o.ready?'All steps complete. Serve now.':`Needs ${o.recipe.steps[o.step]?.[0]||'service'} for ${o.recipe.steps[o.step]?.[1]||0} minute(s).`}`:'No order selected.'}
    function assign(name){if(state.ended)return;const o=state.orders[state.selected];if(!o||o.served||o.ready){note('Assignment blocked.','Choose an unfinished order.');tone(170);return}const step=o.recipe.steps[o.step];if(step[0]!==name){note('Wrong station.',`${o.recipe.name} needs ${step[0]} next. Re-sequence before advancing time.`);tone(170);return}state.stations[name]={id:o.id,remaining:step[1]};note(`${o.recipe.name} sent to ${name}.`,`It needs ${step[1]} minute(s). Other stations can work in parallel.`);tone(520);render()}
    function advance(){if(state.ended)return;state.minute++;for(const name of stationNames){const slot=state.stations[name];if(!slot)continue;slot.remaining--;const o=state.orders.find(x=>x.id===slot.id);if(!o){state.stations[name]=null;continue}if(slot.remaining<=0){o.step++;o.progress=0;o.ready=o.step>=o.recipe.steps.length;state.stations[name]=null;tone(620)}}for(const o of state.orders){if(o.served)continue;o.patience--;const active=Object.values(state.stations).some(s=>s?.id===o.id);if(o.ready)o.quality-=7;else if(!active)o.quality-=2;if(o.patience<=0){o.served=true;state.rep-=12;state.combo=0;state.waste++;note('A guest walked out.',`${o.recipe.name} expired. Recover by serving the remaining orders cleanly.`);tone(150)}}if(state.minute%3===0&&state.orders.filter(o=>!o.served).length<3)state.orders.push(newOrder());if(state.minute>modes[state.mode].minutes)finish();else render()}
    function serve(){if(state.ended)return;const o=state.orders[state.selected];if(!o||o.served||!o.ready){note('Not ready to serve.','Complete every recipe step first.');tone(170);return}o.served=true;const q=Math.max(0,o.quality),p=Math.max(0,o.patience),earned=Math.round(o.recipe.value*(.5+q/200)+state.combo);state.coins+=earned;state.rep+=q>70?4:q>45?1:-4;state.combo=q>65?state.combo+1:0;state.score+=earned*10+p*4+state.combo*15;tone(q>65?760:420);note(`${o.recipe.name} served.`,`Earned ${earned} coins at ${Math.round(q)} quality with ${p} patience remaining.`);if(state.score>=650&&!state.unlocked){state.unlocked=true;modes.rush.locked=false;state.tasting=true;note('Rush and tasting menu unlocked.','A strong service opened a faster mode and the four-station Tasting trio order for this session.');renderModes()}state.orders.push(newOrder());state.selected=state.orders.length-1;render()}
    function expedite(){if(state.ended)return;if(state.coins<3){note('Not enough coins.','Expediting costs 3 coins.');return}const o=state.orders[state.selected];const slot=Object.values(state.stations).find(s=>s?.id===o?.id);if(!slot){note('Nothing to expedite.','Assign the selected order to its next station first.');return}state.coins-=3;slot.remaining=Math.max(0,slot.remaining-1);note('Order expedited.','One minute was removed, but the coin reserve is smaller.');if(slot.remaining===0)advance();else render()}
    function recover(){if(state.ended)return;if(state.waste<1){note('Recovery unavailable.','A staff meal recovery becomes available after one failed order.');return}state.waste--;state.rep=Math.min(100,state.rep+6);state.coins=Math.max(0,state.coins-2);note('Team recovered.','A failed dish became a staff meal. Reputation improved at a small coin cost.');render()}
    function finish(){state.ended=true;const remaining=state.orders.filter(o=>!o.served).length;state.rep-=remaining*3;state.score+=Math.max(0,state.rep)*5-state.waste*40;note(state.rep>=65?'Service complete.':'Service closed.',`Final score ${Math.round(state.score)}. Reputation ${Math.round(state.rep)}, waste ${state.waste}, and ${remaining} unfinished order(s).`);render()}
    root.addEventListener('click',e=>{const a=e.target.closest('[data-act]')?.dataset.act;if(a==='advance')advance();if(a==='serve')serve();if(a==='expedite')expedite();if(a==='recover')recover();if(a==='restart')reset();if(a==='sound'){state.sound=!state.sound;e.target.textContent=state.sound?'Sound on':'Sound off';e.target.setAttribute('aria-pressed',String(state.sound));tone(520)}});
    const key=e=>{if(!dialog.open)return;if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();state.selected=(state.selected+(e.key==='ArrowRight'?1:-1)+state.orders.length)%state.orders.length;render()}if(e.key===' '){e.preventDefault();advance()}if(e.key==='Enter'){e.preventDefault();serve()}if(['1','2','3','4'].includes(e.key))assign(stationNames[Number(e.key)-1])};document.addEventListener('keydown',key);
    const close=()=>{document.removeEventListener('keydown',key);state.ac?.close();dialog.removeEventListener('close',close)};dialog.addEventListener('close',close);renderModes();reset()
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();