(() => {
  const APP = {
    name: 'Lantern Lanes', emoji: '🏮', category: 'play', version: '1.1.0',
    summary: 'Learn patrol timing in a guided practice lane, then steal keys and escape across three stealth maps.',
    description: 'A local stealth-timing mini-game with a narrated practice run, visible patrol beats, moving sight lines, keys, gates, smoke decoys, adaptive maps, scoring, touch and keyboard controls, reduced-motion behavior, and clean teardown.'
  };
  const PRACTICE = { name:'Practice courtyard', walls:[[3,1],[3,2],[3,3],[7,4],[8,4]], start:[1,4], exit:[10,4], keys:[[6,2]], guards:[{x:6,y:4,dir:-1,path:[[6,4],[6,1]]}], practice:true };
  const MAPS = [
    { name:'Market roofs', walls:[[2,2],[3,2],[6,2],[7,2],[2,5],[5,5],[6,5],[9,5]], start:[1,7], exit:[10,1], keys:[[1,1],[8,7]], guards:[{x:5,y:1,dir:1,path:[[5,1],[5,7]]},{x:10,y:6,dir:-1,path:[[10,6],[4,6]]}] },
    { name:'Canal arcade', walls:[[4,1],[4,2],[4,3],[7,4],[8,4],[9,4],[2,6],[3,6],[6,6]], start:[1,1], exit:[10,7], keys:[[9,1],[2,7]], guards:[{x:7,y:2,dir:1,path:[[7,2],[7,7]]},{x:2,y:4,dir:1,path:[[2,4],[10,4]]}] },
    { name:'Temple walk', walls:[[2,1],[2,2],[5,2],[6,2],[8,2],[8,3],[3,5],[4,5],[7,6],[8,6]], start:[10,7], exit:[1,1], keys:[[6,7],[10,2]], guards:[{x:5,y:7,dir:-1,path:[[5,7],[5,1]]},{x:9,y:4,dir:-1,path:[[9,4],[1,4]]}] }
  ];
  const LESSONS = [
    {title:'Step 1: move once', text:'Use an arrow key or tap one adjacent square. Every move advances the patrol one beat.', test:s=>s.turn>=1},
    {title:'Step 2: wait safely', text:'Use Space or Wait to let the lantern move without changing your square.', test:s=>s.waits>=1},
    {title:'Step 3: read the cone', text:'Gold squares are the guard sight line. Crossing one adds two alarm. Move around it or wait for the guard to turn.', test:s=>s.turn>=3},
    {title:'Step 4: collect the key', text:'Touch the gold key. The exit remains locked until every key is collected.', test:s=>s.got.size>=1},
    {title:'Step 5: use smoke', text:'Press S or Drop smoke. Smoke hides your current square through the next patrol sweep.', test:s=>s.smokeUsed>=1},
    {title:'Step 6: reach the gate', text:'Move onto the outlined gate. Practice does not fail, so experiment until the route makes sense.', test:s=>s.done}
  ];
  function installStyles() {
    if (document.querySelector('#lantern-lanes-styles')) return;
    const style = document.createElement('style'); style.id = 'lantern-lanes-styles';
    style.textContent = `.lantern-card{animation:lantern-rise .32s ease both}.lantern-game{max-width:1080px;gap:14px}.lantern-modebar,.lantern-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.lantern-modebar button,.lantern-actions button{min-height:48px;border:1px solid var(--line);border-radius:16px;background:white;padding:10px;text-align:left;color:var(--ink)}.lantern-modebar button[aria-pressed=true],.lantern-actions button[aria-pressed=true]{outline:3px solid var(--accent);outline-offset:2px}.lantern-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.lantern-stat{border:1px solid var(--line);border-radius:15px;background:white;padding:10px 12px}.lantern-stat span,.lantern-actions span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.lantern-stat strong{display:block;margin-top:4px;font-size:1rem}.lantern-board{position:relative;border:0;border-radius:26px;padding:0;overflow:hidden;background:#111827;color:white;cursor:pointer;touch-action:manipulation;box-shadow:inset 0 0 0 1px rgba(255,255,255,.14)}.lantern-board:focus-visible{outline:4px solid var(--accent);outline-offset:4px}.lantern-board canvas{display:block;width:100%;min-height:430px}.lantern-overlay{position:absolute;left:18px;right:18px;bottom:16px;display:flex;justify-content:space-between;gap:12px;align-items:end;pointer-events:none}.lantern-overlay strong{font-size:clamp(1.05rem,3vw,1.55rem)}.lantern-overlay small{display:block;max-width:720px;color:rgba(255,255,255,.78)}.lantern-badge{padding:7px 9px;border-radius:999px;background:rgba(251,191,36,.16);color:#fde68a;font-size:.68rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.lantern-guide{display:grid;grid-template-columns:1.2fr .8fr;gap:10px}.lantern-guide>div{border:1px solid var(--line);border-radius:18px;padding:15px;background:white}.lantern-guide ol{margin:.5rem 0 0;padding-left:1.2rem}.lantern-guide li{margin:.35rem 0;color:var(--muted)}.lantern-guide li[data-done=true]{color:var(--ink);font-weight:800}.lantern-log{min-height:104px;padding:17px 19px}.lantern-log strong{font-size:clamp(1.08rem,3vw,1.5rem)}@media(max-width:820px){.lantern-hud{grid-template-columns:repeat(2,1fr)}.lantern-modebar,.lantern-actions,.lantern-guide{grid-template-columns:1fr}.lantern-board canvas{min-height:380px}.lantern-overlay{align-items:start;flex-direction:column}}@media(prefers-reduced-motion:reduce){.lantern-card{animation:none}}@keyframes lantern-rise{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}}`;
    document.head.append(style);
  }
  function initCard() {
    const grid=document.querySelector('#app-grid'), template=document.querySelector('#app-card-template');
    if(!grid||!template||document.querySelector('[data-lantern-lanes-card]')) return;
    installStyles(); const node=template.content.cloneNode(true), card=node.querySelector('.app-card');
    card.dataset.category=APP.category; card.dataset.lanternLanesCard='true'; card.classList.add('lantern-card');
    node.querySelector('.app-icon').textContent=APP.emoji; node.querySelector('.app-meta').textContent=`Play · v${APP.version}`;
    node.querySelector('.app-name').textContent=APP.name; node.querySelector('.app-summary').textContent=APP.summary;
    const open=node.querySelector('.app-card-button'); open.setAttribute('aria-label',`Open ${APP.name}`); open.addEventListener('click',openLanternLanes); grid.append(node);
  }
  function openLanternLanes() {
    const dialog=document.querySelector('#app-dialog'),stage=document.querySelector('#app-stage'),title=document.querySelector('#dialog-title'),category=document.querySelector('#dialog-category'),description=document.querySelector('#dialog-description'),feedback=document.querySelector('#dialog-feedback');
    if(!dialog||!stage||!title||!category||!description||!feedback) return;
    title.textContent=APP.name; category.textContent=`Play · ${APP.emoji}`; description.textContent=APP.description;
    feedback.href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Lantern%20Lanes';
    stage.replaceChildren(); renderGame(stage,dialog); dialog.showModal();
  }
  function renderGame(stage,dialog) {
    const root=document.createElement('section'); root.className='tool-panel lantern-game';
    const modebar=document.createElement('div'); modebar.className='lantern-modebar';
    const practiceButton=makeButton('Guided practice','Six narrated steps, no failure.',()=>setMode('practice'));
    const runButton=makeButton('Start campaign','Three maps, score and alarm.',()=>setMode('campaign'));
    const helpButton=makeButton('Show route guide','Rules, symbols and controls.',()=>{state.help=!state.help; update();});
    modebar.append(practiceButton,runButton,helpButton);
    const hud=document.createElement('div'); hud.className='lantern-hud'; hud.innerHTML='<div class="lantern-stat"><span>Mode</span><strong id="lantern-mode">Practice</strong></div><div class="lantern-stat"><span>Map</span><strong id="lantern-map">Practice</strong></div><div class="lantern-stat"><span>Keys</span><strong id="lantern-keys">0 / 1</strong></div><div class="lantern-stat"><span>Smoke</span><strong id="lantern-smoke">3</strong></div><div class="lantern-stat"><span>Alarm</span><strong id="lantern-alarm">0 / 6</strong></div><div class="lantern-stat"><span>Score</span><strong id="lantern-score">0</strong></div>';
    const board=document.createElement('button'); board.type='button'; board.className='lantern-board'; board.setAttribute('aria-label','Lantern Lanes board. Use arrow keys to move, Space to wait, and S to drop smoke.');
    board.innerHTML='<canvas aria-hidden="true"></canvas><span class="lantern-overlay"><span><strong>Move between the light.</strong><small>Gold cones are dangerous. Keys unlock the outlined gate. Every move or wait advances patrols one beat.</small></span><span class="lantern-badge">Guided stealth</span></span>';
    const canvas=board.querySelector('canvas'),ctx=canvas.getContext('2d');
    const guide=document.createElement('div'); guide.className='lantern-guide';
    const actions=document.createElement('div'); actions.className='lantern-actions';
    const log=document.createElement('div'); log.className='result-card lantern-log'; log.setAttribute('aria-live','polite');
    const controls=document.createElement('div'); controls.className='tool-actions';
    const waitButton=makeButton('Wait for patrol','Advance one beat.',()=>step(0,0)); const smokeButton=makeButton('Drop smoke','Hide this tile briefly.',dropSmoke); const restartButton=makeButton('Restart map','Reset the current lesson or run.',reset);
    controls.append(waitButton,smokeButton,restartButton); root.append(modebar,hud,guide,board,actions,log,controls); stage.append(root);
    const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    const state={mode:'practice',mapIndex:0,player:{x:1,y:4},keys:[],got:new Set(),guards:[],smoke:3,alarm:0,score:0,turn:0,waits:0,smokeUsed:0,done:false,raf:0,smokeCells:[],lesson:0,help:true};
    dialog.addEventListener('close',teardown,{once:true});
    function makeButton(titleText,smallText,fn){const b=document.createElement('button');b.type='button';b.innerHTML=`<strong>${titleText}</strong><small>${smallText}</small>`;b.addEventListener('click',fn);return b;}
    function current(){return state.mode==='practice'?PRACTICE:MAPS[state.mapIndex];}
    function setMode(mode){state.mode=mode;state.mapIndex=0;state.help=mode==='practice';reset();board.focus();}
    function reset(){const m=current();state.player={x:m.start[0],y:m.start[1]};state.keys=m.keys.map((k,i)=>({x:k[0],y:k[1],id:i}));state.got=new Set();state.guards=m.guards.map(g=>({x:g.x,y:g.y,dir:g.dir,path:g.path.map(p=>({x:p[0],y:p[1]}))}));state.smoke=m.practice?3:2;state.alarm=0;state.score=0;state.turn=0;state.waits=0;state.smokeUsed=0;state.done=false;state.smokeCells=[];state.lesson=0;say(`<strong>${m.name}.</strong><small>${m.practice?'Follow the six steps below. Practice cannot fail.':'Collect every key, then reach the gate before alarm reaches six.'}</small>`);update();}
    function wall(x,y){return x<0||y<0||x>11||y>8||current().walls.some(w=>w[0]===x&&w[1]===y);}
    function cone(g){const dx=g.path[0].x===g.path[1].x?0:g.dir,dy=g.path[0].y===g.path[1].y?0:g.dir,cells=[];for(let i=1;i<=3;i+=1){const x=g.x+dx*i,y=g.y+dy*i;if(wall(x,y))break;cells.push({x,y});}return cells;}
    function seen(x,y){return state.guards.some(g=>cone(g).some(p=>p.x===x&&p.y===y))&&!state.smokeCells.some(p=>p.x===x&&p.y===y);}
    function moveGuards(){state.guards.forEach(g=>{const a=g.path[0],b=g.path[1];if(a.x===b.x){g.y+=g.dir;if(g.y===a.y||g.y===b.y)g.dir*=-1;}else{g.x+=g.dir;if(g.x===a.x||g.x===b.x)g.dir*=-1;}});}
    function step(dx,dy){if(state.done)return;const nx=state.player.x+dx,ny=state.player.y+dy;if(dx===0&&dy===0)state.waits+=1;else if(!wall(nx,ny))state.player={x:nx,y:ny};else if(state.mode!=='practice')state.alarm+=1;state.turn+=1;state.smokeCells=state.smokeCells.filter(p=>p.life-- >0);collect();moveGuards();if(seen(state.player.x,state.player.y)&&state.mode!=='practice')state.alarm+=2;const m=current();if(state.player.x===m.exit[0]&&state.player.y===m.exit[1]&&state.got.size===state.keys.length)return win();if(state.alarm>=6)return lose();advanceLesson();say(`<strong>${seen(state.player.x,state.player.y)?'Lantern cone on your tile.':'Still quiet.'}</strong><small>${state.keys.length-state.got.size} keys remain. Patrol beat ${state.turn}.</small>`);update();}
    function collect(){state.keys.forEach(k=>{if(k.x===state.player.x&&k.y===state.player.y&&!state.got.has(k.id)){state.got.add(k.id);state.score+=60;}});}
    function dropSmoke(){if(state.done)return;if(state.smoke<=0){say('<strong>No smoke left.</strong><small>Wait for the patrol or choose another lane.</small>');return update();}state.smoke-=1;state.smokeUsed+=1;state.smokeCells.push({x:state.player.x,y:state.player.y,life:2});state.score+=10;advanceLesson();say('<strong>Smoke down.</strong><small>Your current square is hidden through the next patrol sweep.</small>');update();}
    function advanceLesson(){if(state.mode!=='practice')return;while(state.lesson<LESSONS.length&&LESSONS[state.lesson].test(state))state.lesson+=1;}
    function win(){state.done=true;if(state.mode==='practice'){state.lesson=LESSONS.length;state.score=200;say('<strong>Practice complete.</strong><small>You moved, waited, read a cone, collected a key, used smoke, and opened the gate. Start the campaign when ready.</small>');}else{const bonus=Math.max(0,260-state.turn*8-state.alarm*20+state.smoke*35);state.score+=bonus;say(`<strong>Gate reached: ${state.score} points.</strong><small>Bonus ${bonus}. Restart to replay or continue to the next map.</small>`);state.mapIndex=(state.mapIndex+1)%MAPS.length;}update();}
    function lose(){state.done=true;say(`<strong>The alarm filled.</strong><small>Final score ${state.score}. Restart, wait for a turn, or spend smoke before crossing a cone.</small>`);update();}
    function say(html){log.innerHTML=html;}
    function update(){practiceButton.setAttribute('aria-pressed',String(state.mode==='practice'));runButton.setAttribute('aria-pressed',String(state.mode==='campaign'));helpButton.setAttribute('aria-pressed',String(state.help));hud.querySelector('#lantern-mode').textContent=state.mode==='practice'?'Practice':'Campaign';hud.querySelector('#lantern-map').textContent=state.mode==='practice'?'Lesson':`${state.mapIndex+1} / ${MAPS.length}`;hud.querySelector('#lantern-keys').textContent=`${state.got.size} / ${state.keys.length}`;hud.querySelector('#lantern-smoke').textContent=state.smoke;hud.querySelector('#lantern-alarm').textContent=state.mode==='practice'?'Safe':`${state.alarm} / 6`;hud.querySelector('#lantern-score').textContent=state.score;guide.hidden=!state.help;guide.innerHTML=`<div><strong>${state.mode==='practice'&&state.lesson<LESSONS.length?LESSONS[state.lesson].title:'Route guide'}</strong><p>${state.mode==='practice'&&state.lesson<LESSONS.length?LESSONS[state.lesson].text:'Move one square at a time. Gold cones add alarm. Keys open the gate. Smoke hides one square for two beats.'}</p></div><div><strong>Controls and symbols</strong><ol><li data-done="${state.turn>0}">Arrows or adjacent tap: move</li><li data-done="${state.waits>0}">Space or Wait: advance patrol</li><li data-done="${state.smokeUsed>0}">S or Drop smoke: hide</li><li data-done="${state.got.size>0}">Gold dot: key</li><li data-done="${state.done}">Outlined square: exit</li></ol></div>`;actions.replaceChildren();[['↑','Move north',0,-1],['←','Move west',-1,0],['→','Move east',1,0],['↓','Move south',0,1],['•','Wait',0,0],['S','Smoke',0,0]].forEach(a=>{const b=document.createElement('button');b.type='button';b.innerHTML=`<span>${a[0]}</span><strong>${a[1]}</strong><small>${a[1]==='Smoke'?'Hide this tile.':'Advance one patrol beat.'}</small>`;b.addEventListener('click',()=>a[1]==='Smoke'?dropSmoke():step(a[2],a[3]));actions.append(b);});draw();}
    function resize(){const rect=canvas.getBoundingClientRect(),dpr=Math.max(1,Math.min(2,window.devicePixelRatio||1));canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(Math.max(380,rect.height||430)*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw();}
    function draw(){const w=canvas.clientWidth||900,h=canvas.clientHeight||430,cols=12,rows=9,pad=24,cell=Math.min((w-pad*2)/cols,(h-105)/rows),ox=(w-cell*cols)/2,oy=22;ctx.clearRect(0,0,w,h);const grad=ctx.createLinearGradient(0,0,w,h);grad.addColorStop(0,'#1f2937');grad.addColorStop(1,'#030712');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);for(let y=0;y<rows;y+=1)for(let x=0;x<cols;x+=1){ctx.fillStyle=(x+y)%2?'rgba(255,255,255,.05)':'rgba(255,255,255,.08)';ctx.fillRect(ox+x*cell,oy+y*cell,cell-1,cell-1);}current().walls.forEach(p=>{ctx.fillStyle='#374151';ctx.fillRect(ox+p[0]*cell,oy+p[1]*cell,cell-1,cell-1);});state.guards.forEach(g=>cone(g).forEach(p=>{ctx.fillStyle='rgba(251,191,36,.25)';ctx.fillRect(ox+p.x*cell,oy+p.y*cell,cell-1,cell-1);}));state.smokeCells.forEach(p=>{ctx.fillStyle='rgba(209,213,219,.58)';ctx.beginPath();ctx.arc(ox+(p.x+.5)*cell,oy+(p.y+.5)*cell,cell*.42,0,Math.PI*2);ctx.fill();});state.keys.forEach(k=>{if(state.got.has(k.id))return;ctx.fillStyle='#fde68a';ctx.beginPath();ctx.arc(ox+(k.x+.5)*cell,oy+(k.y+.5)*cell,cell*.18,0,Math.PI*2);ctx.fill();});const exit=current().exit;ctx.strokeStyle=state.got.size===state.keys.length?'#86efac':'#64748b';ctx.lineWidth=4;ctx.strokeRect(ox+exit[0]*cell+5,oy+exit[1]*cell+5,cell-11,cell-11);state.guards.forEach(g=>{ctx.fillStyle='#f97316';ctx.beginPath();ctx.arc(ox+(g.x+.5)*cell,oy+(g.y+.5)*cell,cell*.28,0,Math.PI*2);ctx.fill();});ctx.fillStyle=seen(state.player.x,state.player.y)?'#fecaca':'#bfdbfe';ctx.beginPath();ctx.arc(ox+(state.player.x+.5)*cell,oy+(state.player.y+.5)*cell,cell*.3,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(255,255,255,.86)';ctx.font='700 12px system-ui';ctx.fillText(`Patrol beat ${state.turn}. Gold cones show the next sight line.`,24,h-36);}
    function onKey(event){const k=event.key;if(k==='ArrowUp')step(0,-1);else if(k==='ArrowDown')step(0,1);else if(k==='ArrowLeft')step(-1,0);else if(k==='ArrowRight')step(1,0);else if(k===' '||k==='Enter')step(0,0);else if(k.toLowerCase()==='s')dropSmoke();else return;event.preventDefault();}
    function onPointer(event){const rect=canvas.getBoundingClientRect(),w=canvas.clientWidth||900,h=canvas.clientHeight||430,cell=Math.min((w-48)/12,(h-105)/9),ox=(w-cell*12)/2,oy=22,x=Math.floor((event.clientX-rect.left-ox)/cell),y=Math.floor((event.clientY-rect.top-oy)/cell),dx=Math.max(-1,Math.min(1,x-state.player.x)),dy=Math.max(-1,Math.min(1,y-state.player.y));if(Math.abs(dx)+Math.abs(dy)<=1)step(dx,dy);}
    function loop(){if(!reduced&&!state.done){draw();state.raf=requestAnimationFrame(loop);}}
    function teardown(){cancelAnimationFrame(state.raf);window.removeEventListener('resize',resize);board.removeEventListener('keydown',onKey);board.removeEventListener('click',onPointer);}
    board.addEventListener('keydown',onKey);board.addEventListener('click',onPointer);window.addEventListener('resize',resize);reset();requestAnimationFrame(resize);state.raf=requestAnimationFrame(loop);
  }
  const start=()=>setTimeout(initCard,0); if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
