(() => {
'use strict';
const APP={name:'Mediation Table',emoji:'🤝',category:'play',version:'1.0.0',summary:'Read hidden priorities, trade concessions, and guide six disputes toward durable settlements.',description:'A local-only mediation strategy game with six escalating disputes, hidden stakeholder priorities, issue packages, reciprocal concessions, trust and fatigue, branching offers, caucus intel, session unlocks, meaningful impasse, one costly reset, touch, keyboard, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const CASES=[
{title:'Shared Courtyard',brief:'Two neighbors disagree over evening events, access, and cleanup.',sides:['Residents','Cafe'],issues:[['Hours',3,1],['Access',2,3],['Cleanup',1,2],['Notice',2,2]],pressure:1},
{title:'Studio Credit',brief:'A designer and engineer dispute authorship, launch timing, and revision authority.',sides:['Design','Engineering'],issues:[['Credit',3,1],['Launch',1,3],['Revisions',2,2],['Portfolio use',3,2]],pressure:2},
{title:'Market Stall',brief:'Vendors contest prime space, power access, setup time, and shared signage.',sides:['Food vendors','Craft vendors'],issues:[['Placement',3,2],['Power',3,1],['Setup',1,3],['Signage',2,2]],pressure:2},
{title:'River Path',brief:'Cyclists and conservationists need a seasonal access plan.',sides:['Cyclists','Conservation'],issues:[['Route',3,2],['Season',1,3],['Speed',2,3],['Monitoring',1,2]],pressure:3},
{title:'Festival Stage',brief:'Two groups share one stage, a fixed curfew, and limited sound checks.',sides:['Headliners','Community acts'],issues:[['Set length',3,2],['Order',2,3],['Sound check',3,1],['Encore',2,2]],pressure:3},
{title:'Harbor Accord',brief:'Fishers, tour operators, and residents need a durable operating compact.',sides:['Working harbor','Waterfront residents'],issues:[['Quiet hours',1,3],['Berths',3,1],['Waste rules',2,3],['Review cycle',2,2]],pressure:4}
];
function style(){if($('#mediation-table-style'))return;const e=document.createElement('style');e.id='mediation-table-style';e.textContent=`
.mediation-table{max-width:1120px;display:grid;gap:12px}.mt-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.mt-stat,.mt-card{border:1px solid var(--line);border-radius:17px;background:#fff}.mt-stat{padding:9px}.mt-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.mt-layout{display:grid;grid-template-columns:1.03fr .97fr;gap:12px}.mt-card{padding:15px}.mt-room{position:relative;min-height:320px;border-radius:24px;overflow:hidden;background:linear-gradient(145deg,#edf4ff,#f8efe7);color:#24314a}.mt-room svg{position:absolute;inset:0;width:100%;height:100%}.mt-copy{position:relative;z-index:2;min-height:320px;padding:18px;display:grid;align-content:start;gap:7px;pointer-events:none}.mt-copy strong{max-width:640px;font-size:clamp(1.3rem,3vw,2.05rem)}.mt-balance{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:auto}.mt-party{background:rgba(255,255,255,.78);border-radius:14px;padding:10px}.mt-party meter{width:100%}.mt-controls{display:grid;gap:10px}.mt-issues{display:grid;gap:7px}.mt-issue{display:grid;grid-template-columns:1fr auto auto;gap:7px;align-items:center;border:1px solid var(--line);border-radius:12px;padding:8px}.mt-issue button{min-width:42px;min-height:40px;border:1px solid var(--line);border-radius:10px;background:#fff;font-weight:900}.mt-issue output{min-width:58px;text-align:center;font-weight:900}.mt-tools,.mt-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.mt-tools button,.mt-actions button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800;padding:9px}.mt-actions .primary{background:#e4ecff;border-color:#4967b0}.mt-tags{display:flex;gap:5px;flex-wrap:wrap}.mt-tag{font-size:.68rem;padding:4px 7px;border-radius:999px;background:#eef2ff}.mt-log{min-height:112px}.mt-pulse{animation:mt-pulse .7s ease-out}@keyframes mt-pulse{50%{transform:scale(1.025)}}.mt-hand{animation:mt-hand 3s ease-in-out infinite alternate;transform-origin:center}@keyframes mt-hand{to{transform:translateY(-5px)}}
@media(max-width:820px){.mt-layout{grid-template-columns:1fr}.mt-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:520px){.mt-hud{grid-template-columns:repeat(2,1fr)}.mt-tools,.mt-actions{grid-template-columns:1fr 1fr}.mt-room,.mt-copy{min-height:280px}.mt-issue{grid-template-columns:1fr 42px 42px}.mt-issue output{grid-column:1/-1;text-align:left}}
@media(prefers-reduced-motion:reduce){.mediation-table *{animation:none!important;transition:none!important}}
`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-mediation-table]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.mediationTable='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-mediation-table]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.mtBound)return;b.dataset.mtBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · negotiation strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
 const root=document.createElement('section');root.className='tool-panel mediation-table';root.innerHTML=`<div class="mt-hud">${['Case','Time','Trust A','Trust B','Score','Tool'].map((x,i)=>`<div class="mt-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="mt-layout"><section class="mt-card"><div class="mt-room" aria-label="Animated mediation room"><svg viewBox="0 0 640 360" aria-hidden="true"><ellipse cx="320" cy="260" rx="210" ry="58" fill="#c9a982"/><rect x="205" y="220" width="230" height="65" rx="26" fill="#9c7655"/><g class="mt-hand"><circle cx="210" cy="158" r="42" fill="#7f9ac9"/><circle cx="430" cy="158" r="42" fill="#d18e79"/><path d="M250 205 Q320 175 390 205" fill="none" stroke="#f4c9a2" stroke-width="24" stroke-linecap="round"/></g><path data-bridge d="M270 205 Q320 150 370 205" fill="none" stroke="#5c7bc2" stroke-width="8" stroke-linecap="round" opacity=".35"/></svg><div class="mt-copy"><span class="eyebrow">Neutral room</span><strong data-title></strong><p data-brief></p><div class="mt-tags" data-tags></div><div class="mt-balance"><div class="mt-party"><b data-pa></b><meter data-ma min="0" max="100"></meter></div><div class="mt-party"><b data-pb></b><meter data-mb min="0" max="100"></meter></div></div></div></div><p class="mt-hint">Build a package before presenting it. Tab through controls; use Enter on − and +. Caucus reveals one hidden priority but costs time and neutrality.</p></section><aside class="mt-card mt-controls"><div class="result-card mt-log" aria-live="polite"></div><div class="mt-issues" data-issues></div><div class="mt-tools"><button data-a="caucus">Private caucus</button><button data-a="reframe">Reframe interests</button><button data-a="reciprocal">Reciprocal clause</button><button data-a="undo">Undo package</button></div><div class="mt-actions"><button class="primary" data-a="offer">Present package</button><button data-a="recover">Reset the room</button><button data-a="restart">New docket</button></div></aside></div>`;stage.append(root);
 let st,history=[],timer=0,ended=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 function reset(){clearTimeout(timer);st={case:0,time:12,trust:[72,72],score:0,unlock:false,recovery:true,reframes:2,caucus:2,reciprocal:false,known:[[],[]],alloc:[2,2,2,2]};history=[];ended=false;log(CASES[0].brief,'Move each issue toward one party or keep it balanced. Durable deals usually trade across priorities rather than splitting everything evenly.');draw()}
 function snap(){history.push(JSON.stringify(st));if(history.length>12)history.shift()}
 function value(side){const c=CASES[st.case];let total=0,max=0;c.issues.forEach((it,i)=>{const weight=it[side+1],x=st.alloc[i];max+=weight*4;total+=weight*(side===0?4-x:x)});return Math.round(total/max*100)}
 function durability(){const a=value(0),b=value(1),spread=Math.abs(a-b),balanced=st.alloc.filter(x=>x===2).length;let d=Math.min(a,b)-spread*.35-balanced*3+(st.reciprocal?10:0);if(st.unlock&&st.alloc.some(x=>x===1)&&st.alloc.some(x=>x===3))d+=6;return clamp(Math.round(d),0,100)}
 function shift(i,n){if(ended)return;snap();st.alloc[i]=clamp(st.alloc[i]+n,0,4);draw()}
 function caucus(){if(ended||st.caucus<=0||st.time<2)return;const side=st.known[0].length<=st.known[1].length?0:1;const unknown=CASES[st.case].issues.map((_,i)=>i).filter(i=>!st.known[side].includes(i));if(!unknown.length)return;const best=unknown.sort((a,b)=>CASES[st.case].issues[b][side+1]-CASES[st.case].issues[a][side+1])[0];snap();st.known[side].push(best);st.caucus--;st.time-=2;st.trust[1-side]=clamp(st.trust[1-side]-4,0,100);log(`Caucus reveals ${CASES[st.case].sides[side]} care most about ${CASES[st.case].issues[best][0].toLowerCase()}.`,'The other side notices the private time and becomes slightly wary.');draw()}
 function reframe(){if(ended||st.reframes<=0||st.time<1)return;snap();st.reframes--;st.time--;st.trust=st.trust.map(x=>clamp(x+5,0,100));log('You reframe positions as underlying needs.','Both parties become more willing to trade across issues.');draw()}
 function reciprocal(){if(ended||!st.unlock||st.reciprocal||st.time<2)return;snap();st.reciprocal=true;st.time-=2;log('You add a reciprocal review clause.','The package can adapt if the agreement creates an unforeseen burden.');draw()}
 function undo(){if(ended||!history.length)return;st=JSON.parse(history.pop());draw()}
 function offer(){if(ended||st.time<2)return;const a=value(0),b=value(1),d=durability(),c=CASES[st.case];st.time-=2;$$('button',root).forEach(x=>x.disabled=true);root.querySelector('.mt-room').classList.add('mt-pulse');timer=setTimeout(()=>{if(!root.isConnected)return;root.querySelector('.mt-room').classList.remove('mt-pulse');const threshold=44+c.pressure*4;const accepted=a>=threshold&&b>=threshold&&d>=42;st.trust[0]=clamp(st.trust[0]+(accepted?7:-12)+(a>=b?2:-2),0,100);st.trust[1]=clamp(st.trust[1]+(accepted?7:-12)+(b>=a?2:-2),0,100);st.score+=accepted?d*22+Math.min(a,b)*8:Math.max(0,d*4);if(st.score>=4600)st.unlock=true;if(!accepted&&st.time<=0)return finish(false,'The parties leave without enough time for another package.');if(st.trust.some(x=>x<=0))return finish(false,'One party no longer trusts the process.');if(accepted){if(st.case>=CASES.length-1)return finish(true);st.case++;st.time=12;st.reframes=2;st.caucus=2;st.reciprocal=false;st.known=[[],[]];st.alloc=[2,2,2,2];history=[];log('Agreement reached.',`Durability ${d}. Next case: ${CASES[st.case].brief}`)}else log('The package is rejected.',`Support was ${a}/${b}; durability ${d}. Trade across the high-value issues or gather better information.`);draw()},reduced?80:650)}
 function recover(){if(ended||!st.recovery)return;st.recovery=false;st.time=8;st.trust=st.trust.map(x=>clamp(x-14,1,100));st.alloc=[2,2,2,2];history=[];log('A senior mediator resets the room.','You regain time and a neutral package, but both parties lose confidence in the process.');draw()}
 function finish(win,msg){ended=true;clearTimeout(timer);log(win?'Docket complete.':'Impasse.',msg||(win?`Final score ${st.score}. You built agreements under rising pressure.`:'The mediation ended without a durable agreement.'));draw()}
 function log(a,b){const el=$('.mt-log',root);el.innerHTML=`<strong>${a}</strong><p>${b}</p>`}
 function draw(){const c=CASES[st.case],a=value(0),b=value(1),d=durability();const hv=[`${st.case+1}/6`,st.time,st.trust[0],st.trust[1],st.score,st.unlock?'Review clause':'Locked'];$$('[data-h]',root).forEach((x,i)=>x.textContent=hv[i]);$('[data-title]',root).textContent=c.title;$('[data-brief]',root).textContent=c.brief;$('[data-pa]',root).textContent=`${c.sides[0]} · ${a}`;$('[data-pb]',root).textContent=`${c.sides[1]} · ${b}`;$('[data-ma]',root).value=a;$('[data-mb]',root).value=b;$('[data-bridge]',root).style.opacity=String(.2+d/140);$('[data-tags]',root).innerHTML=`<span class="mt-tag">Durability ${d}</span><span class="mt-tag">Pressure ${c.pressure}/4</span><span class="mt-tag">Caucus ${st.caucus}</span><span class="mt-tag">Reframes ${st.reframes}</span>${st.reciprocal?'<span class="mt-tag">Review clause active</span>':''}`;$('[data-issues]',root).innerHTML=c.issues.map((it,i)=>{const knownA=st.known[0].includes(i)?`A priority ${it[1]}`:'A priority ?';const knownB=st.known[1].includes(i)?`B priority ${it[2]}`:'B priority ?';return `<div class="mt-issue"><div><b>${it[0]}</b><small>${knownA} · ${knownB}</small></div><button data-i="${i}" data-n="-1" aria-label="Move ${it[0]} toward ${c.sides[0]}">−</button><button data-i="${i}" data-n="1" aria-label="Move ${it[0]} toward ${c.sides[1]}">+</button><output>${['All A','Lean A','Shared','Lean B','All B'][st.alloc[i]]}</output></div>`}).join('');$$('[data-i]',root).forEach(x=>x.addEventListener('click',()=>shift(+x.dataset.i,+x.dataset.n)));$('[data-a="caucus"]',root).disabled=ended||st.caucus<=0||st.time<2;$('[data-a="reframe"]',root).disabled=ended||st.reframes<=0||st.time<1;$('[data-a="reciprocal"]',root).disabled=ended||!st.unlock||st.reciprocal||st.time<2;$('[data-a="undo"]',root).disabled=ended||!history.length;$('[data-a="offer"]',root).disabled=ended||st.time<2;$('[data-a="recover"]',root).disabled=ended||!st.recovery;$('[data-a="restart"]',root).disabled=false}
 $('[data-a="caucus"]',root).addEventListener('click',caucus);$('[data-a="reframe"]',root).addEventListener('click',reframe);$('[data-a="reciprocal"]',root).addEventListener('click',reciprocal);$('[data-a="undo"]',root).addEventListener('click',undo);$('[data-a="offer"]',root).addEventListener('click',offer);$('[data-a="recover"]',root).addEventListener('click',recover);$('[data-a="restart"]',root).addEventListener('click',reset);const close=()=>{clearTimeout(timer);dialog.removeEventListener('close',close)};dialog.addEventListener('close',close);reset()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
