(() => {
'use strict';
const APP={name:'Outbreak Atlas',emoji:'🧭',category:'play',version:'1.0.2',summary:'Contain six evolving outbreaks across a contact network with limited tests, vaccines, tracing, and public trust.',description:'A local-only outbreak strategy game with a spatial contact network, hidden infections, confirmed-risk highlighting, deterministic undo, testing, vaccination, quarantine, tracing, day-bounded spread, resource tradeoffs, progression, failure, recovery, keyboard and touch controls, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const SCENARIOS=[
{name:'Campus cluster',nodes:9,edges:12,days:7,tests:5,vax:3,trace:3,target:2,spread:.30,trust:72},
{name:'Festival spillover',nodes:10,edges:15,days:8,tests:5,vax:4,trace:3,target:3,spread:.34,trust:70},
{name:'Transit corridor',nodes:11,edges:17,days:8,tests:6,vax:4,trace:4,target:3,spread:.37,trust:68},
{name:'Care network',nodes:12,edges:18,days:9,tests:6,vax:5,trace:4,target:3,spread:.40,trust:66},
{name:'Regional surge',nodes:13,edges:21,days:9,tests:7,vax:5,trace:5,target:4,spread:.43,trust:64},
{name:'Variant weekend',nodes:14,edges:24,days:10,tests:7,vax:6,trace:5,target:4,spread:.47,trust:62}
];
function style(){if($('#outbreak-atlas-style'))return;const e=document.createElement('style');e.id='outbreak-atlas-style';e.textContent=`.outbreak-atlas{max-width:1120px;display:grid;gap:12px}.oa-hud{display:grid;grid-template-columns:repeat(7,1fr);gap:7px}.oa-stat,.oa-panel{border:1px solid var(--line);border-radius:17px;background:#fff}.oa-stat{padding:9px}.oa-stat span{display:block;font-size:.6rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.oa-layout{display:grid;grid-template-columns:1.2fr .8fr;gap:12px}.oa-panel{padding:14px}.oa-brief{border-radius:17px;padding:15px;background:linear-gradient(135deg,#123c46,#255f63);color:#fff}.oa-board{position:relative;min-height:430px;margin-top:10px;border:1px solid #c8d4d6;border-radius:16px;overflow:hidden;background:radial-gradient(circle at 50% 30%,#f7fbfa,#e8f2f1)}.oa-board svg{width:100%;height:430px;display:block}.oa-node{cursor:pointer}.oa-node circle{stroke:#173f45;stroke-width:2}.oa-node text{font-size:12px;font-weight:900;pointer-events:none}.oa-node.is-selected circle{stroke:#c57a00;stroke-width:5}.oa-node.is-positive circle{fill:#f6b8ad}.oa-node.is-clear circle{fill:#bfe4cc}.oa-node.is-unknown circle{fill:#dbe7e8}.oa-node.is-vax circle{stroke:#4f46e5;stroke-dasharray:4 3}.oa-node.is-quarantine circle{stroke:#8b2f2f;stroke-width:5}.oa-edge{stroke:#8ba5a8;stroke-width:3}.oa-edge.hot{stroke:#d46755;stroke-width:5}.oa-actions,.oa-gates{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin-top:10px}.oa-actions button{min-height:46px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800}.oa-actions .primary{background:#e3f0ed;border-color:#235b5f}.oa-actions button:focus-visible,.oa-node:focus-visible{outline:3px solid #235b5f;outline-offset:2px}.oa-log{min-height:110px}.oa-gate{padding:7px;border-radius:10px;background:#f1f3f5;font-size:.74rem}.oa-gate.pass{background:#e1f4e9}.oa-legend{display:flex;flex-wrap:wrap;gap:8px;margin-top:8px;font-size:.74rem}.oa-chip{display:inline-flex;align-items:center;gap:5px}.oa-dot{width:11px;height:11px;border-radius:50%;border:1px solid #173f45;background:#dbe7e8}.oa-dot.pos{background:#f6b8ad}.oa-dot.clear{background:#bfe4cc}.oa-hint{font-size:.8rem;color:var(--muted)}@media(max-width:860px){.oa-layout{grid-template-columns:1fr}.oa-hud{grid-template-columns:repeat(4,1fr)}}@media(max-width:560px){.oa-hud{grid-template-columns:repeat(2,1fr)}.oa-actions,.oa-gates{grid-template-columns:1fr}.oa-board,.oa-board svg{min-height:360px;height:360px}.oa-actions button{min-height:50px}}@media(prefers-reduced-motion:reduce){.outbreak-atlas *{animation:none!important;transition:none!important}}`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-outbreak-atlas]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true),a=$('.app-card',f);a.dataset.outbreakAtlas='1';a.dataset.category=APP.category;$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-outbreak-atlas]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.oaBound)return;b.dataset.oaBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · outbreak network strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
const root=document.createElement('section');root.className='tool-panel outbreak-atlas';root.innerHTML=`<div class="oa-hud">${['Scenario','Day','Tests','Vaccines','Tracing','Trust','Score'].map((x,i)=>`<div class="oa-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="oa-layout"><section class="oa-panel"><div class="oa-brief"><p class="app-meta" data-scenario></p><h3 data-brief></h3><p data-target></p></div><div class="oa-board" data-board aria-label="Contact network"></div><div class="oa-legend"><span class="oa-chip"><span class="oa-dot"></span>Unknown</span><span class="oa-chip"><span class="oa-dot pos"></span>Positive</span><span class="oa-chip"><span class="oa-dot clear"></span>Cleared</span></div><p class="oa-hint">Select a person, then act. Keyboard: arrows change selection, T test, V vaccinate, Q quarantine, C trace, Enter advance day, U undo.</p></section><aside class="oa-panel"><div class="result-card oa-log" aria-live="polite"></div><div class="oa-gates" data-gates></div><div class="oa-actions"><button data-a="test">Test selected</button><button data-a="vax">Vaccinate</button><button data-a="quarantine">Toggle quarantine</button><button data-a="trace">Trace contacts</button><button data-a="undo">Undo action</button><button class="primary" data-a="advance">Advance day</button><button data-a="recover">Call field team</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
let st,ended=false,keyHandler,closeHandler;
const current=()=>SCENARIOS[st.scenario],rand=()=>{st.seed=(st.seed*1664525+1013904223)>>>0;return st.seed/4294967296};
function log(a,b){$('.oa-log',root).innerHTML=`<strong>${a}</strong><p>${b}</p>`}
function graph(n,e){const nodes=Array.from({length:n},(_,i)=>({id:i,infected:false,revealed:false,vax:false,q:false}));const edges=[];for(let i=0;i<n;i++)edges.push([i,(i+1)%n]);let k=0;while(edges.length<e&&k++<100){const a=Math.floor(rand()*n),b=Math.floor(rand()*n);if(a!==b&&!edges.some(([x,y])=>(x===a&&y===b)||(x===b&&y===a)))edges.push([a,b])}const first=Math.floor(rand()*n);let second=Math.floor(rand()*(n-1));if(second>=first)second++;nodes[first].infected=true;nodes[second].infected=true;return {nodes,edges}}
function reset(){st={scenario:0,score:0,trust:SCENARIOS[0].trust,field:true,unlock:false,seed:Date.now()>>>0,history:[]};ended=false;startScenario()}
function startScenario(){const s=current(),g=graph(s.nodes,s.edges);Object.assign(st,{day:1,tests:s.tests+(st.unlock?2:0),vax:s.vax+(st.unlock?1:0),trace:s.trace,selected:0,nodes:g.nodes,edges:g.edges,history:[]});log(s.name,'Two hidden infections are moving through the network. Contain them before the final day.');draw()}
function snapshot(){return JSON.stringify({tests:st.tests,vax:st.vax,trace:st.trace,trust:st.trust,score:st.score,day:st.day,seed:st.seed,selected:st.selected,nodes:st.nodes})}
function act(kind){if(ended)return;const n=st.nodes[st.selected];if(kind==='test'){if(st.tests<=0)return log('No tests remain.','Advance with current information or call the field team.');st.history.push(snapshot());st.tests--;n.revealed=true;st.trust=clamp(st.trust+1,0,100);log(n.infected?'Positive result.':'Negative result.',n.infected?'Quarantine or trace this person before advancing.':'This person is currently clear.')}if(kind==='vax'){if(st.vax<=0)return log('No vaccines remain.','Reserve protection for the highest-degree contacts.');if(n.vax)return log('Already vaccinated.','Choose another person.');st.history.push(snapshot());st.vax--;n.vax=true;st.trust=clamp(st.trust-1,0,100);log('Vaccination placed.','Future infection risk is reduced, but public trust shifts slightly.')}if(kind==='quarantine'){st.history.push(snapshot());n.q=!n.q;st.trust=clamp(st.trust+(n.infected&&n.revealed?1:-2),0,100);log(n.q?'Quarantine active.':'Quarantine lifted.',n.q?'This node can no longer transmit while isolated.':'This person returns to the network.')}if(kind==='trace'){if(st.trace<=0)return log('No tracing teams remain.','Use visible network structure and test selectively.');st.history.push(snapshot());st.trace--;const ids=new Set(st.edges.filter(e=>e.includes(n.id)).flat());ids.delete(n.id);ids.forEach(id=>{if(rand()<.65)st.nodes[id].revealed=true});log('Contacts traced.',`${ids.size} linked people were investigated; some statuses are now visible.`)}draw()}
function undo(){if(ended||!st.history.length)return log('Nothing to undo.','No reversible action is available.');const x=JSON.parse(st.history.pop());Object.assign(st,x);log('Action reversed.','Resources, selection, network state, and the random stream were restored.');draw()}
function degree(id){return st.edges.filter(e=>e.includes(id)).length}
function advance(){if(ended)return;const s=current(),infectious=st.nodes.map(n=>n.infected&&!n.q);let newCases=0;for(const [a,b] of st.edges){for(const [from,to] of [[a,b],[b,a]]){const A=st.nodes[from],B=st.nodes[to];if(infectious[from]&&!B.infected&&!B.q){const p=s.spread*(A.vax?.8:1)*(B.vax?.28:1)*(1+Math.max(0,degree(to)-2)*.05);if(rand()<p){B.infected=true;newCases++}}}}st.nodes.forEach(n=>{if(n.infected&&rand()<.16)n.infected=false});st.day++;st.history=[];st.trust=clamp(st.trust-(newCases*2)-st.nodes.filter(n=>n.q&&!n.infected).length,0,100);const active=st.nodes.filter(n=>n.infected&&!n.q).length,contained=st.nodes.filter(n=>n.infected&&n.q).length;st.score+=Math.max(0,180-contained*5-newCases*35+st.trust);if(st.score>=1800)st.unlock=true;if(st.trust<=10)return finish(false,'Public trust collapsed under broad or poorly targeted controls.');if(st.day>s.days){if(active<=s.target)return winScenario(active);return finish(false,`${active} uncontrolled infections remained; the target was ${s.target}.`)}log('Day advanced.',`${newCases} new infection${newCases===1?'':'s'} occurred. New cases cannot transmit until the next day. ${active} remain uncontrolled.`);draw()}
function winScenario(active){if(st.scenario===SCENARIOS.length-1)return finish(true,`All six outbreaks contained. Final score ${st.score}.`);st.score+=500-active*60;st.trust=clamp(st.trust+8,0,100);st.scenario++;startScenario()}
function recover(){if(ended||!st.field)return log('Field team unavailable.','This recovery can be used once per session.');st.field=false;st.score=Math.max(0,st.score-300);st.trust=clamp(st.trust-5,0,100);st.tests+=3;st.vax+=2;st.trace+=2;log('Field team deployed.','Tests, vaccines, and tracing return at a score and trust cost.');draw()}
function finish(win,msg){ended=true;log(win?'Containment achieved.':'Containment failed.',msg);draw()}
function gates(){const s=current(),active=st.nodes.filter(n=>n.infected&&!n.q).length,unknown=st.nodes.filter(n=>!n.revealed).length,over=st.nodes.filter(n=>n.q&&!n.infected).length;return[{label:`Uncontrolled ≤ ${s.target}`,pass:active<=s.target},{label:'Trust ≥ 35',pass:st.trust>=35},{label:'Unknown statuses ≤ half',pass:unknown<=Math.floor(st.nodes.length/2)},{label:'Uninfected quarantines ≤ 2',pass:over<=2}]}
function draw(){const s=current();$$('[data-h]',root).forEach((e,n)=>e.textContent=[`${st.scenario+1}/6`,`${st.day}/${s.days}`,st.tests,st.vax,st.trace,Math.round(st.trust),st.score][n]);$('[data-scenario]',root).textContent=s.name;$('[data-brief]',root).textContent='Map hidden infections. Protect hubs. Avoid unnecessary isolation.';$('[data-target]',root).textContent=`Finish with at most ${s.target} uncontrolled infections. ${st.unlock?'Rapid-response cache unlocked.':''}`;const w=700,h=430,pts=st.nodes.map((n,i)=>({x:w*(.5+.39*Math.cos(i*2.399)),y:h*(.5+.39*Math.sin(i*2.399))}));$('[data-board]',root).innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="group" aria-label="${s.name} contact network">${st.edges.map(([a,b])=>`<line class="oa-edge ${((st.nodes[a].revealed&&st.nodes[a].infected&&!st.nodes[a].q)||(st.nodes[b].revealed&&st.nodes[b].infected&&!st.nodes[b].q))?'hot':''}" x1="${pts[a].x}" y1="${pts[a].y}" x2="${pts[b].x}" y2="${pts[b].y}"/>`).join('')}${st.nodes.map((n,i)=>`<g class="oa-node ${i===st.selected?'is-selected':''} ${n.revealed?(n.infected?'is-positive':'is-clear'):'is-unknown'} ${n.vax?'is-vax':''} ${n.q?'is-quarantine':''}" data-node="${i}" tabindex="0" role="button" aria-label="Person ${i+1}, ${n.revealed?(n.infected?'positive':'clear'):'status unknown'}${n.vax?', vaccinated':''}${n.q?', quarantined':''}"><circle cx="${pts[i].x}" cy="${pts[i].y}" r="${20+degree(i)*2}"/><text x="${pts[i].x}" y="${pts[i].y+4}" text-anchor="middle">${i+1}</text></g>`).join('')}</svg>`;$('[data-gates]',root).innerHTML=gates().map(g=>`<div class="oa-gate ${g.pass?'pass':''}">${g.pass?'✓':'○'} ${g.label}</div>`).join('');$$('[data-node]',root).forEach(b=>b.addEventListener('click',()=>{st.selected=Number(b.dataset.node);draw()}));const disabled=ended;$$('[data-a]',root).forEach(b=>b.disabled=disabled&&b.dataset.a!=='restart');$('[data-a="test"]',root).disabled=disabled||st.tests<=0;$('[data-a="vax"]',root).disabled=disabled||st.vax<=0||st.nodes[st.selected].vax;$('[data-a="trace"]',root).disabled=disabled||st.trace<=0;$('[data-a="undo"]',root).disabled=disabled||!st.history.length;$('[data-a="recover"]',root).disabled=disabled||!st.field}
root.addEventListener('click',e=>{const a=e.target.closest('[data-a]')?.dataset.a;if(!a)return;({test:()=>act('test'),vax:()=>act('vax'),quarantine:()=>act('quarantine'),trace:()=>act('trace'),undo,advance,recover,restart:reset}[a]||(()=>{}))()});
keyHandler=e=>{if(!dialog.open)return;const t=e.target;if(t?.matches?.('button,input,select,textarea,a,[contenteditable="true"]'))return;const k=e.key.toLowerCase();if(['arrowright','arrowdown'].includes(k)){e.preventDefault();st.selected=(st.selected+1)%st.nodes.length;draw()}else if(['arrowleft','arrowup'].includes(k)){e.preventDefault();st.selected=(st.selected-1+st.nodes.length)%st.nodes.length;draw()}else if(k==='t')act('test');else if(k==='v')act('vax');else if(k==='q')act('quarantine');else if(k==='c')act('trace');else if(k==='u')undo();else if(e.key==='Enter'){e.preventDefault();advance()}};
document.addEventListener('keydown',keyHandler);closeHandler=()=>{document.removeEventListener('keydown',keyHandler);dialog.removeEventListener('close',closeHandler)};dialog.addEventListener('close',closeHandler);reset()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
