(() => {
'use strict';
const APP={name:'Panelcraft',emoji:'🕹️',category:'play',version:'1.0.2',summary:'Design six safety-critical control panels by balancing reach, scan time, workload, errors, budget, and operator fatigue.',description:'A local-only human-factors strategy game with six control-room incidents, spatial control placement, enforced design-action limits, limited usability drills, shifting operator needs, budget and fatigue tradeoffs, scoring, progression, failure, recovery, a session unlock, keyboard and touch controls, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const CONTROLS=[
{id:'alarm',label:'Alarm acknowledge',icon:'!',priority:5,reach:5,scan:4,load:1},
{id:'stop',label:'Emergency stop',icon:'■',priority:5,reach:5,scan:5,load:1},
{id:'trend',label:'Trend display',icon:'⌁',priority:3,reach:2,scan:5,load:2},
{id:'mode',label:'Mode selector',icon:'◇',priority:4,reach:4,scan:3,load:3},
{id:'comms',label:'Team comms',icon:'◉',priority:3,reach:4,scan:3,load:2},
{id:'diagnostic',label:'Diagnostics',icon:'∿',priority:2,reach:2,scan:4,load:4},
{id:'reset',label:'System reset',icon:'↻',priority:2,reach:3,scan:2,load:3},
{id:'checklist',label:'Checklist',icon:'✓',priority:3,reach:2,scan:4,load:1}
];
const ZONES=[
{id:'primary',label:'Primary reach',reach:5,scan:5,capacity:2,cost:4},
{id:'secondary',label:'Secondary reach',reach:4,scan:3,capacity:2,cost:2},
{id:'display',label:'Display band',reach:2,scan:5,capacity:2,cost:3},
{id:'support',label:'Support rail',reach:2,scan:2,capacity:3,cost:1}
];
const INCIDENTS=[
{name:'Cooling pump trip',turns:8,budget:18,target:68,focus:['alarm','stop','trend'],shift:'Fast acknowledgement matters more than deep diagnostics.'},
{name:'Night-shift handoff',turns:8,budget:19,target:70,focus:['checklist','comms','mode'],shift:'A tired operator needs obvious state and clean handoff controls.'},
{name:'Sensor disagreement',turns:8,budget:20,target:72,focus:['trend','diagnostic','mode'],shift:'Conflicting readings increase scan and interpretation pressure.'},
{name:'Grid frequency event',turns:8,budget:21,target:74,focus:['alarm','trend','comms','stop'],shift:'Multiple teams need rapid shared awareness.'},
{name:'Smoke in equipment bay',turns:8,budget:22,target:76,focus:['alarm','stop','checklist','comms'],shift:'Stress narrows attention and makes hidden controls dangerous.'},
{name:'Cascading plant upset',turns:8,budget:24,target:78,focus:['alarm','stop','trend','mode','comms'],shift:'Every extra search and mistaken action compounds the incident.'}
];
function style(){if($('#panelcraft-style'))return;const e=document.createElement('style');e.id='panelcraft-style';e.textContent=`.panelcraft{max-width:1120px;display:grid;gap:12px}.pc-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.pc-stat,.pc-panel{border:1px solid var(--line);border-radius:17px;background:#fff}.pc-stat{padding:9px}.pc-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.pc-layout{display:grid;grid-template-columns:1.15fr .85fr;gap:12px}.pc-panel{padding:14px}.pc-brief{border-radius:17px;padding:15px;background:linear-gradient(135deg,#18263d,#254660);color:#fff}.pc-brief p{margin:.35rem 0 0}.pc-board{display:grid;grid-template-columns:repeat(2,1fr);gap:9px;margin-top:11px}.pc-zone{min-height:142px;border:2px dashed #b8c3ce;border-radius:15px;padding:9px;background:#f7f9fb}.pc-zone:disabled{cursor:not-allowed;opacity:.68}.pc-zone-head{display:flex;justify-content:space-between;gap:8px;font-size:.78rem}.pc-slots{display:grid;gap:6px;margin-top:8px}.pc-control{display:flex;align-items:center;justify-content:space-between;gap:8px;min-height:42px;border:1px solid #cbd4dc;border-radius:10px;background:#fff;padding:7px 9px;text-align:left}.pc-control.is-focus{outline:3px solid #efb44c;outline-offset:1px}.pc-control.is-selected{border-color:#245c78;background:#e7f2f6}.pc-icon{display:inline-grid;place-items:center;width:28px;height:28px;border-radius:8px;background:#e9eef2;font-weight:900}.pc-palette,.pc-actions,.pc-gates{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin-top:10px}.pc-actions button,.pc-zone,.pc-control{cursor:pointer}.pc-actions button{min-height:46px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800}.pc-actions .primary{background:#e6f1f5;border-color:#245c78}.pc-actions button:focus-visible,.pc-zone:focus-visible,.pc-control:focus-visible{outline:3px solid #245c78;outline-offset:2px}.pc-grid{display:grid;gap:7px;margin-top:10px}.pc-row{display:grid;grid-template-columns:88px 1fr 38px;gap:8px;align-items:center}.pc-meter{height:11px;background:#e8edf1;border-radius:99px;overflow:hidden}.pc-meter span{display:block;height:100%;background:#245c78;transition:width .3s}.pc-log{min-height:102px}.pc-gate{padding:7px;border-radius:10px;background:#f1f3f5;font-size:.74rem}.pc-gate.pass{background:#e1f4e9}.pc-hint{font-size:.8rem;color:var(--muted)}@media(max-width:850px){.pc-layout{grid-template-columns:1fr}.pc-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.pc-hud{grid-template-columns:repeat(2,1fr)}.pc-board,.pc-palette,.pc-actions,.pc-gates{grid-template-columns:1fr}.pc-zone{min-height:110px}.pc-control{min-height:48px}}@media(prefers-reduced-motion:reduce){.panelcraft *{animation:none!important;transition:none!important}}`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-panelcraft]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true),a=$('.app-card',f);a.dataset.panelcraft='1';a.dataset.category=APP.category;$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-panelcraft]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.pcBound)return;b.dataset.pcBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · human-factors strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
const root=document.createElement('section');root.className='tool-panel panelcraft';root.innerHTML=`<div class="pc-hud">${['Incident','Actions','Budget','Fatigue','Trust','Score'].map((x,i)=>`<div class="pc-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="pc-layout"><section class="pc-panel"><div class="pc-brief"><p class="app-meta" data-incident></p><h3 data-shift></h3><p data-target></p></div><div class="pc-board" data-board></div><p class="pc-hint">Each placement spends one design action. Select a control, then a zone. Keyboard: 1-8 select control, Q/W/E/R choose zone, D drill, Enter commission, U undo.</p><div class="pc-palette" data-palette></div></section><aside class="pc-panel"><div class="result-card pc-log" aria-live="polite"></div><div class="pc-grid" data-metrics></div><div class="pc-gates" data-gates></div><div class="pc-actions"><button data-a="drill">Run usability drill</button><button data-a="undo">Undo placement</button><button class="primary" data-a="commission">Commission panel</button><button data-a="recover">Call human-factors lead</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
let st,ended=false,keyHandler,closeHandler;
const current=()=>INCIDENTS[st.incident],zoneItems=id=>CONTROLS.filter(c=>st.placements[c.id]===id);
function log(a,b){$('.pc-log',root).innerHTML=`<strong>${a}</strong><p>${b}</p>`}
function reset(){st={incident:0,time:INCIDENTS[0].turns,budget:INCIDENTS[0].budget,fatigue:8,trust:64,score:0,selected:0,placements:{},history:[],drills:2,assist:true,unlock:false,lastAudit:null};ended=false;log('Blank panel ready.','Place all eight controls within the action and budget limits, then meet at least five commissioning gates.');draw()}
function place(zoneId){if(ended)return;const c=CONTROLS[st.selected],z=ZONES.find(x=>x.id===zoneId),items=zoneItems(zoneId),old=st.placements[c.id];if(old===zoneId)return log('Already placed.',`${c.label} is already in ${z.label}.`);if(st.time<=0)return log('No design actions remain.','Commission the current panel, undo a placement, or call the human-factors lead for emergency time.');if(items.length>=z.capacity)return log('Zone full.',`${z.label} has no open position.`);const cost=z.cost;if(cost>st.budget)return log('Budget limit reached.','Use a lower-cost zone or undo a placement.');st.history.push({id:c.id,old,budget:st.budget,time:st.time});st.placements[c.id]=zoneId;st.budget-=cost;st.time--;st.lastAudit=null;log('Control placed.',`${c.label} moved to ${z.label}. ${st.time} design action${st.time===1?'':'s'} remain.`);draw()}
function undo(){if(ended||!st.history.length)return log('Nothing to undo.','No placement change is available.');const h=st.history.pop();if(h.old)st.placements[h.id]=h.old;else delete st.placements[h.id];st.budget=h.budget;st.time=h.time;st.lastAudit=null;log('Placement restored.','The previous panel change and its design action were restored.');draw()}
function metrics(){let reach=30,scan=30,load=10,errors=8;const inc=current();CONTROLS.forEach(c=>{const zid=st.placements[c.id];if(!zid){errors+=c.priority*4;load+=c.load*2;return}const z=ZONES.find(x=>x.id===zid),focus=inc.focus.includes(c.id)?1.45:1;reach+=Math.max(0,6-Math.abs(c.reach-z.reach)*2)*c.priority*focus;scan+=Math.max(0,6-Math.abs(c.scan-z.scan)*2)*c.priority*focus;load+=Math.abs(c.reach-z.reach)*c.load*focus*.7;errors+=Math.max(0,3-Math.min(z.reach,z.scan))*c.priority*focus*.8});const crowd=ZONES.reduce((n,z)=>n+Math.max(0,zoneItems(z.id).length-1)*2,0);load+=crowd+st.fatigue*.2;errors+=crowd*.4+st.fatigue*.15;return {reach:clamp(Math.round(reach/3),0,100),scan:clamp(Math.round(scan/3),0,100),load:clamp(Math.round(load),0,100),errors:clamp(Math.round(errors),0,100)}}
function gates(){const m=metrics(),placed=Object.keys(st.placements).length,focus=current().focus.filter(id=>st.placements[id]).length;return [{label:'Critical controls placed',pass:focus===current().focus.length},{label:'Reach ≥ 58',pass:m.reach>=58},{label:'Scan ≥ 58',pass:m.scan>=58},{label:'Errors ≤ 45',pass:m.errors<=45},{label:'Workload ≤ 60',pass:m.load<=60},{label:'All controls assigned',pass:placed===CONTROLS.length}]}
function drill(){if(ended||st.drills<=0)return log('No drills remain.','Commission with current evidence or use recovery support.');st.drills--;const m=metrics(),weak=[['reach',m.reach],['scan',m.scan],['errors',100-m.errors],['workload',100-m.load]].sort((a,b)=>a[1]-b[1])[0];st.lastAudit=weak[0];st.fatigue=clamp(st.fatigue+6,0,100);log('Usability drill complete.',`The weakest dimension is ${weak[0]}. ${gates().filter(g=>!g.pass).length} commissioning gates remain blocked.`);draw()}
function commission(){if(ended)return;const inc=current(),m=metrics(),passed=gates().filter(g=>g.pass).length,quality=Math.round((m.reach+m.scan+(100-m.load)+(100-m.errors))/4);st.fatigue=clamp(st.fatigue+Math.max(5,m.load/12),0,100);st.trust=clamp(st.trust+(quality>=inc.target&&passed>=5?9:-12)-(m.errors>55?6:0),0,100);st.score+=Math.max(0,quality*8+passed*55-Math.round(st.fatigue*2));if(st.score>=2100)st.unlock=true;if(st.trust<=12||st.fatigue>=95)return finish(false,'Operators lost confidence before the final incident.');if(quality<inc.target||passed<5)return finish(false,`Panel quality ${quality} missed the ${inc.target} target or left too many gates blocked.`);if(st.incident===INCIDENTS.length-1)return finish(true,`All six control rooms commissioned. Final score ${st.score}.`);st.incident++;startIncident()}
function startIncident(){const i=current();Object.assign(st,{time:i.turns,budget:i.budget+(st.unlock?3:0),placements:{},history:[],drills:2,lastAudit:null,fatigue:Math.max(5,st.fatigue-14)});log(i.name,i.shift);draw()}
function recover(){if(ended||!st.assist)return log('Lead unavailable.','This intervention can be used once per session.');st.assist=false;st.score=Math.max(0,st.score-280);st.trust=clamp(st.trust-6,0,100);st.fatigue=Math.max(0,st.fatigue-24);st.budget+=6;st.time+=2;st.drills++;log('Human-factors lead joins.','Two design actions, budget, and one drill return, but score and trust fall.');draw()}
function finish(win,msg){ended=true;log(win?'Panels commissioned.':'Design review failed.',msg);draw()}
function draw(){const i=current(),m=metrics();$$('[data-h]',root).forEach((e,n)=>e.textContent=[`${st.incident+1}/6`,st.time,st.budget,Math.round(st.fatigue),Math.round(st.trust),st.score][n]);$('[data-incident]',root).textContent=i.name;$('[data-shift]',root).textContent=i.shift;$('[data-target]',root).textContent=`Commissioning target ${i.target}. ${st.drills} drill${st.drills===1?'':'s'} available${st.unlock?' · expert budget unlocked':''}.`;$('[data-board]',root).innerHTML=ZONES.map((z,zi)=>`<button type="button" class="pc-zone" data-zone="${z.id}" aria-label="Place selected control in ${z.label}" ${ended||st.time<=0?'disabled':''}><span class="pc-zone-head"><strong>${['Q','W','E','R'][zi]} · ${z.label}</strong><span>${zoneItems(z.id).length}/${z.capacity}</span></span><span class="pc-slots">${zoneItems(z.id).map(c=>`<span class="pc-control ${i.focus.includes(c.id)?'is-focus':''}"><span><span class="pc-icon">${c.icon}</span> ${c.label}</span></span>`).join('')||'<span class="pc-hint">Open positions</span>'}</span></button>`).join('');$('[data-palette]',root).innerHTML=CONTROLS.map((c,n)=>`<button type="button" class="pc-control ${n===st.selected?'is-selected':''} ${i.focus.includes(c.id)?'is-focus':''}" data-control="${n}" aria-pressed="${n===st.selected}"><span><span class="pc-icon">${c.icon}</span> ${n+1}. ${c.label}</span><small>${st.placements[c.id]?ZONES.find(z=>z.id===st.placements[c.id]).label:'Unplaced'}</small></button>`).join('');$('[data-metrics]',root).innerHTML=[['Reach',m.reach],['Scan',m.scan],['Workload',m.load],['Error risk',m.errors]].map(([k,v])=>`<div class="pc-row"><span>${k}</span><span class="pc-meter"><span style="width:${v}%"></span></span><strong>${v}</strong></div>`).join('');$('[data-gates]',root).innerHTML=gates().map(g=>`<div class="pc-gate ${g.pass?'pass':''}">${g.pass?'✓':'○'} ${g.label}</div>`).join('');$$('[data-control]',root).forEach(b=>b.addEventListener('click',()=>{st.selected=Number(b.dataset.control);draw()}));$$('[data-zone]',root).forEach(b=>b.addEventListener('click',()=>place(b.dataset.zone)));const disabled=ended;$$('[data-a]',root).forEach(b=>b.disabled=disabled&&b.dataset.a!=='restart');$('[data-a="drill"]',root).disabled=disabled||st.drills<=0;$('[data-a="undo"]',root).disabled=disabled||!st.history.length;$('[data-a="recover"]',root).disabled=disabled||!st.assist}
root.addEventListener('click',e=>{const a=e.target.closest('[data-a]')?.dataset.a;if(!a)return;({drill,undo,commission,recover,restart:reset}[a]||(()=>{}))()});
keyHandler=e=>{if(!dialog.open)return;const target=e.target;if(target?.matches?.('button,input,select,textarea,a,[contenteditable="true"]'))return;if(/^[1-8]$/.test(e.key)){st.selected=Number(e.key)-1;draw();return}const zone={q:'primary',w:'secondary',e:'display',r:'support'}[e.key.toLowerCase()];if(zone){e.preventDefault();place(zone);return}if(e.key.toLowerCase()==='d')drill();else if(e.key.toLowerCase()==='u')undo();else if(e.key==='Enter'){e.preventDefault();commission()}};
document.addEventListener('keydown',keyHandler);closeHandler=()=>{document.removeEventListener('keydown',keyHandler);dialog.removeEventListener('close',closeHandler)};dialog.addEventListener('close',closeHandler);reset()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
