(() => {
  const APP={name:'Pantry Planner',emoji:'🥕',category:'play',version:'1.0.0',summary:'Stock a community pantry across volatile weeks while balancing nutrition, spoilage, fairness, cash, and trust.',description:'A local resource-management simulation with three neighborhoods, weekly demand shocks, perishable inventory, purchasing tradeoffs, household needs, fairness, waste, scoring, session unlocks, keyboard and touch controls, reduced motion, and teardown.'};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const SCENARIOS={starter:{name:'Starter block',weeks:5,cash:120,households:18,target:68},school:{name:'School break',weeks:6,cash:145,households:24,target:76},storm:{name:'Storm recovery',weeks:7,cash:165,households:30,target:84}};
  const FOODS=[{id:'produce',name:'Fresh produce',cost:12,servings:10,life:2,nutrition:3},{id:'protein',name:'Shelf-stable protein',cost:18,servings:9,life:5,nutrition:4},{id:'grains',name:'Whole grains',cost:10,servings:12,life:6,nutrition:2},{id:'comfort',name:'Comfort staples',cost:9,servings:11,life:5,nutrition:1}];
  function css(){if($('#pp-style'))return;const s=document.createElement('style');s.id='pp-style';s.textContent=`.pp{max-width:1050px;display:grid;gap:12px}.pp-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.pp-stat,.pp-panel{border:1px solid var(--line);border-radius:18px;background:#fff}.pp-stat{padding:9px}.pp-stat span{display:block;font-size:.58rem;font-weight:900;text-transform:uppercase;color:var(--muted)}.pp-main{display:grid;grid-template-columns:1.1fr .9fr;gap:12px}.pp-panel{padding:14px}.pp-shelves{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;min-height:230px;align-items:end}.pp-bin{border-radius:14px 14px 7px 7px;background:linear-gradient(#f8fafc,#e2e8f0);border:1px solid var(--line);padding:8px;display:grid;align-content:end;min-height:170px}.pp-fill{border-radius:8px;background:linear-gradient(#86efac,#22c55e);min-height:8px;transition:height .25s ease}.pp-bin strong,.pp-bin small{display:block}.pp-grid,.pp-actions,.pp-scenarios{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.pp button,.pp select{min-height:44px}.pp button{border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800}.pp button.on{background:#dcfce7}.pp button:disabled{opacity:.45}.pp-order{display:grid;grid-template-columns:1fr auto auto;gap:6px;align-items:center;border-top:1px solid var(--line);padding:8px 0}.pp-order input{width:74px;min-height:42px}.pp-log{min-height:110px}.pp button:focus-visible,.pp input:focus-visible{outline:4px solid var(--accent);outline-offset:2px}@media(max-width:780px){.pp-main{grid-template-columns:1fr}.pp-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:520px){.pp-hud{grid-template-columns:repeat(2,1fr)}.pp-grid,.pp-actions,.pp-scenarios{grid-template-columns:1fr}.pp-shelves{grid-template-columns:repeat(2,1fr)}.pp-bin{min-height:130px}}@media(prefers-reduced-motion:reduce){.pp *{animation:none!important;transition:none!important;scroll-behavior:auto!important}}`;document.head.append(s)}
  function card(){const grid=$('#app-grid'),t=$('#app-card-template');if(!grid||!t||$('[data-pp]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;css();const n=t.content.cloneNode(true),c=$('.app-card',n);c.dataset.pp='1';$('.app-icon',n).textContent=APP.emoji;$('.app-meta',n).textContent='Play · v'+APP.version;$('.app-name',n).textContent=APP.name;$('.app-summary',n).textContent=APP.summary;const b=$('.app-card-button',n);b.setAttribute('aria-label','Open '+APP.name);b.onclick=open;grid.append(n)}
  function boot(){css();let tries=0;const add=()=>{card();if(!$('[data-pp]')&&tries++<20)setTimeout(add,120)};add();$$('.filter').forEach(b=>{if(b.dataset.pp)return;b.dataset.pp='1';b.addEventListener('click',()=>setTimeout(card))})}
  function open(){const d=$('#app-dialog'),p=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · community logistics';$('#dialog-description').textContent=APP.description;$('#dialog-feedback').href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Pantry%20Planner';p.replaceChildren();game(p,d);d.showModal()}
  function game(p,d){const root=document.createElement('section');root.className='tool-panel pp';root.innerHTML=`<div class="pp-hud">${['Week','Cash','Households','Coverage','Trust','Score'].map((x,i)=>`<div class="pp-stat"><span>${x}</span><strong data-h="${i}"></strong></div>`).join('')}</div><div class="pp-main"><section class="pp-panel"><h3>Pantry shelves</h3><div class="pp-shelves" aria-label="Pantry inventory"></div><div class="pp-grid"><div><strong>Demand forecast</strong><p class="pp-demand"></p></div><div><strong>Community condition</strong><p class="pp-shock"></p></div></div><small>Fresh food improves nutrition but spoils quickly. Shelf-stable food protects coverage. Uneven distribution lowers trust.</small></section><aside class="pp-panel"><div class="pp-scenarios"></div><h3>Order for next week</h3><div class="pp-orders"></div><div class="pp-actions"><button class="pp-buy">Place order</button><button class="pp-serve">Serve households</button><button class="pp-recover">Emergency donation</button><button class="pp-restart">Restart</button></div><div class="pp-log result-card" aria-live="polite"></div><small>Keyboard: 1-4 selects an item, Left and Right change quantity, B buys, Enter serves, D requests one donation, R restarts.</small></aside></div>`;p.append(root);
    let unlock=0,total=0,state,selected=0;
    const msg=(a,b)=>$('.pp-log',root).innerHTML=`<strong>${a}</strong><small>${b}</small>`;
    function begin(key){const s=SCENARIOS[key];state={key,week:1,cash:s.cash,trust:72,score:0,donation:1,orders:[0,0,0,0],stock:FOODS.map((f,i)=>({qty:i===2?10:6,age:0})),finished:false};msg('Pantry opened.','Review the forecast, place an order, then serve the week.');draw()}
    function demand(){const base=Math.ceil(SCENARIOS[state.key].households*(.75+state.week*.04));const swings=[0,3,-2,5,1,6,-1];return Math.max(8,base+swings[(state.week+state.key.length)%swings.length])}
    function shock(){return ['Bus route disruption raises walk-in demand.','A produce donation improves fresh supply.','School meals pause this week.','A refrigerator outage threatens fresh stock.','A local event brings extra volunteers.'][(state.week+state.key.length)%5]}
    function buy(){if(state.finished)return;let cost=0;state.orders.forEach((q,i)=>cost+=q*FOODS[i].cost);if(cost>state.cash)return msg('Order exceeds cash.','Reduce quantities or wait for an emergency donation.');if(!cost)return msg('No items ordered.','Set at least one case before placing the order.');state.cash-=cost;state.orders.forEach((q,i)=>{state.stock[i].qty+=q*FOODS[i].servings;state.orders[i]=0});state.score+=Math.round(cost*.4);msg('Order received.',`Spent $${cost}. Balance variety against spoilage before serving.`);draw()}
    function serve(){if(state.finished)return;const need=demand();const available=state.stock.reduce((n,x)=>n+x.qty,0);if(!available)return msg('Shelves are empty.','Use the emergency donation or restart the scenario.');let remaining=Math.min(need,available),served=0,nutrition=0;const order=[0,1,2,3];order.forEach(i=>{const use=Math.min(state.stock[i].qty,Math.ceil(remaining/order.length)+1);state.stock[i].qty-=use;remaining-=use;served+=use;nutrition+=use*FOODS[i].nutrition});const coverage=Math.min(100,Math.round(served/need*100));const variety=state.stock.filter(x=>x.qty>0).length;state.trust=Math.max(0,Math.min(100,state.trust+(coverage>=90?5:-9)+(variety>=3?3:-4)));state.score+=coverage+variety*10+Math.round(nutrition/8);let waste=0;state.stock.forEach((x,i)=>{x.age++;if(x.age>=FOODS[i].life&&x.qty){const lost=Math.ceil(x.qty*.45);x.qty-=lost;waste+=lost}});if(waste){state.trust=Math.max(0,state.trust-5);state.score=Math.max(0,state.score-waste*2)};if(shock().startsWith('A produce donation'))state.stock[0].qty+=8;if(shock().startsWith('A refrigerator outage')){const lost=Math.min(6,state.stock[0].qty);state.stock[0].qty-=lost;waste+=lost}state.week++;if(state.week>SCENARIOS[state.key].weeks)finish();else msg(coverage>=90?'Week served.':'Coverage gap.',`${served}/${need} household portions covered. ${waste?`${waste} servings spoiled. `:''}Plan the next order.`);draw()}
    function donate(){if(state.finished||state.donation<1)return msg('Donation unavailable.','Each scenario allows one emergency recovery.');state.donation--;state.stock[1].qty+=8;state.stock[2].qty+=10;state.trust=Math.max(0,state.trust-3);state.score=Math.max(0,state.score-25);msg('Emergency donation received.','Coverage improved, but relying on emergency supply costs trust and score.');draw()}
    function finish(){state.finished=true;const target=SCENARIOS[state.key].target,final=Math.round((state.trust+Math.min(100,state.score/7))/2),passed=final>=target;total+=state.score;if(state.key==='starter'&&passed)unlock=Math.max(unlock,1);if(state.key==='school'&&passed)unlock=Math.max(unlock,2);msg(passed?'Scenario cleared.':'Scenario needs another plan.',`Final resilience ${final}, target ${target}. Replay with a different purchasing mix.`);scenarioButtons()}
    function scenarioButtons(){const wrap=$('.pp-scenarios',root);wrap.replaceChildren();Object.entries(SCENARIOS).forEach(([k,v],i)=>{const b=document.createElement('button');b.textContent=i>unlock?v.name+' · locked':v.name;b.disabled=i>unlock;b.classList.toggle('on',state?.key===k);b.onclick=()=>begin(k);wrap.append(b)})}
    function draw(){const s=SCENARIOS[state.key],need=demand(),available=state.stock.reduce((n,x)=>n+x.qty,0),coverage=Math.min(100,Math.round(available/need*100));const hs=$$('[data-h]',root);[`${Math.min(state.week,s.weeks)}/${s.weeks}`,'$'+state.cash,s.households,coverage+'%',Math.round(state.trust),total+state.score].forEach((v,i)=>hs[i].textContent=v);const shelves=$('.pp-shelves',root);shelves.replaceChildren();FOODS.forEach((f,i)=>{const x=state.stock[i],b=document.createElement('div');b.className='pp-bin';b.innerHTML=`<div class="pp-fill" style="height:${Math.min(130,x.qty*4)}px"></div><strong>${f.name}</strong><small>${x.qty} servings · life ${Math.max(0,f.life-x.age)} weeks</small>`;shelves.append(b)});$('.pp-demand',root).textContent=`About ${need} portions expected next week.`;$('.pp-shock',root).textContent=shock();const orders=$('.pp-orders',root);orders.replaceChildren();FOODS.forEach((f,i)=>{const row=document.createElement('label');row.className='pp-order';row.innerHTML=`<span>${f.name}<small>$${f.cost} · ${f.servings} servings</small></span><input type="number" min="0" max="6" value="${state.orders[i]}" aria-label="Cases of ${f.name}"><strong>$${state.orders[i]*f.cost}</strong>`;const input=$('input',row);input.onfocus=()=>selected=i;input.oninput=e=>{state.orders[i]=Math.max(0,Math.min(6,+e.target.value||0));draw()};orders.append(row)});$('.pp-buy',root).disabled=state.finished;$('.pp-serve',root).disabled=state.finished;$('.pp-recover',root).disabled=state.finished||!state.donation;$('.pp-recover',root).textContent=`Emergency donation · ${state.donation}`}
    $('.pp-buy',root).onclick=buy;$('.pp-serve',root).onclick=serve;$('.pp-recover',root).onclick=donate;$('.pp-restart',root).onclick=()=>begin(state.key);
    const key=e=>{if(!d.open||['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;const k=e.key.toLowerCase();if(/^[1-4]$/.test(k)){selected=+k-1;return}if(k==='arrowleft')state.orders[selected]=Math.max(0,state.orders[selected]-1);else if(k==='arrowright')state.orders[selected]=Math.min(6,state.orders[selected]+1);else if(k==='b')return buy();else if(k==='enter')return serve();else if(k==='d')return donate();else if(k==='r')return begin(state.key);else return;draw();e.preventDefault()};document.addEventListener('keydown',key);
    const obs=new MutationObserver(()=>{if(!d.open){document.removeEventListener('keydown',key);obs.disconnect();root.remove();$('#pp-style')?.remove()}});obs.observe(d,{attributes:true,attributeFilter:['open']});scenarioButtons();begin('starter')
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();