(() => {
  'use strict';
  const APP={name:'Pattern Table',emoji:'🧵',category:'play',version:'1.0.0',summary:'Draft, rotate, and place garment pieces while balancing fit, grain, defects, waste, and client trust.',description:'A local-only garment-pattern strategy game with spatial placement, rotating pieces, fabric defects, grain rules, fit scoring, limited pins and alterations, session progression, an unlock, meaningful failure, one recovery, keyboard and touch controls, reduced motion, and teardown.'};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const JOBS=[
    {name:'Raincoat repair',brief:'Keep the hood upright and avoid the water-stained strip.',grain:'v',pieces:[['Body',3,3,'v'],['Hood',2,2,'v'],['Pocket',2,1,'h']]},
    {name:'Stage vest',brief:'Favor symmetry and keep both fronts on the same grain.',grain:'v',pieces:[['Back',3,3,'v'],['Front L',2,3,'v'],['Front R',2,3,'v']]},
    {name:'Cycling jersey',brief:'Use the cross-grain panel without wasting stretch fabric.',grain:'h',pieces:[['Torso',3,3,'v'],['Sleeve',3,1,'h'],['Panel',2,2,'h']]},
    {name:'Winter cape',brief:'Large pieces reward planning. Leave room for the collar.',grain:'v',pieces:[['Cape',4,3,'v'],['Collar',3,1,'h'],['Facing',2,2,'v']]},
    {name:'Final commission',brief:'Complete a mixed-grain layout with minimal waste and no defect contact.',grain:'v',pieces:[['Shell',4,3,'v'],['Sleeve',3,2,'h'],['Collar',3,1,'h'],['Pocket',2,1,'v']]}
  ];
  function style(){if($('#pattern-table-style'))return;const e=document.createElement('style');e.id='pattern-table-style';e.textContent=`.pattern-table{max-width:1120px;display:grid;gap:12px}.pt-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.pt-stat,.pt-card{border:1px solid var(--line);border-radius:16px;background:#fff}.pt-stat{padding:9px}.pt-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.pt-layout{display:grid;grid-template-columns:1.15fr .85fr;gap:12px}.pt-card{padding:14px}.pt-board{display:grid;grid-template-columns:repeat(8,1fr);gap:4px;aspect-ratio:8/7;background:#f4f1ea;border:1px solid var(--line);border-radius:16px;padding:8px}.pt-cell{min-width:0;border:1px solid #d9d3c5;border-radius:6px;background:linear-gradient(90deg,rgba(120,113,108,.06) 1px,transparent 1px);position:relative}.pt-cell[aria-selected=true]{outline:3px solid #7c3aed;outline-offset:1px}.pt-cell.defect::after{content:'×';position:absolute;inset:0;display:grid;place-items:center;color:#b91c1c;font-weight:900}.pt-cell.filled{background:#ddd6fe;border-color:#7c3aed}.pt-cell.bad{background:#fecaca}.pt-piece-list,.pt-actions{display:grid;gap:8px}.pt-piece{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;padding:9px;text-align:left;font-weight:800}.pt-piece[aria-pressed=true]{background:#ede9fe;border-color:#6d28d9}.pt-actions{grid-template-columns:repeat(2,1fr)}.pt-actions button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800;padding:9px}.pt-actions .primary{background:#ede9fe;border-color:#6d28d9}.pt-log{min-height:120px}.pt-legend{display:flex;gap:8px;flex-wrap:wrap;font-size:.77rem}.pt-chip{border-radius:999px;background:#f3f4f6;padding:5px 8px}@media(max-width:860px){.pt-layout{grid-template-columns:1fr}.pt-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.pt-hud{grid-template-columns:repeat(2,1fr)}.pt-board{gap:3px;padding:5px}.pt-actions{grid-template-columns:1fr 1fr}}@media(prefers-reduced-motion:reduce){.pattern-table *{animation:none!important;transition:none!important}}`;document.head.append(e)}
  function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-pattern-table]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.patternTable='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
  function boot(){style();let n=0;const r=()=>{card();if(!$('[data-pattern-table]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.ptBound)return;b.dataset.ptBound='1';b.addEventListener('click',()=>setTimeout(card))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · spatial garment strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel pattern-table';root.innerHTML=`<div class="pt-hud">${['Job','Pins','Alterations','Trust','Score','Unlock'].map((x,i)=>`<div class="pt-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="pt-layout"><section class="pt-card"><div class="pt-board" role="grid" aria-label="Fabric cutting table"></div><div class="pt-legend"><span class="pt-chip">Purple: placed piece</span><span class="pt-chip">Red ×: fabric defect</span><span class="pt-chip">Arrow keys move cursor</span></div></section><aside class="pt-card"><div class="result-card pt-log" aria-live="polite"></div><p class="eyebrow">Pattern pieces</p><div class="pt-piece-list"></div><div class="pt-actions"><button class="primary" data-a="place">Place piece</button><button data-a="rotate">Rotate</button><button data-a="undo">Undo last</button><button data-a="finish">Cut layout</button><button data-a="recover">Open remnant roll</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
    const W=8,H=7;let st,ended=false;const board=$('.pt-board',root);
    function makeDefects(seed){const d=[];for(let i=0;i<3;i++)d.push((seed*11+i*17+7)%(W*H));return [...new Set(d)]}
    function reset(){st={job:0,pins:8,alts:3,trust:72,score:0,selected:0,rotated:false,cursor:0,placements:[],defects:makeDefects(1),unlock:false,recovery:true};ended=false;log(JOBS[0].brief,'Select a piece, move the cursor, rotate when needed, and place every piece without overlap.');draw()}
    function job(){return JOBS[st.job]}
    function piece(i=st.selected){const p=job().pieces[i];return{name:p[0],w:st.rotated?p[2]:p[1],h:st.rotated?p[1]:p[2],grain:st.rotated?(p[3]==='v'?'h':'v'):p[3]}}
    function cellsFor(p,origin){const x=origin%W,y=Math.floor(origin/W),out=[];for(let yy=0;yy<p.h;yy++)for(let xx=0;xx<p.w;xx++){if(x+xx>=W||y+yy>=H)return null;out.push((y+yy)*W+x+xx)}return out}
    function occupied(){return new Set(st.placements.flatMap(x=>x.cells))}
    function place(){if(ended)return;const p=piece(),cells=cellsFor(p,st.cursor),used=occupied();if(!cells||cells.some(c=>used.has(c))){log('That piece does not fit there.','Move the cursor or rotate the pattern before placing it.');return}if(st.pins<=0){log('No pins remain.','Undo a piece, finish the layout, or use the remnant recovery if available.');return}st.pins--;st.placements.push({index:st.selected,cells,grain:p.grain,name:p.name,defect:cells.some(c=>st.defects.includes(c))});st.selected=Math.min(job().pieces.length-1,st.selected+1);st.rotated=false;draw()}
    function undo(){if(ended||!st.placements.length)return;const last=st.placements.pop();st.pins++;st.selected=last.index;st.rotated=false;log('Last piece lifted.','The pin returned, but the client clock keeps running.');draw()}
    function finish(){if(ended)return;const count=new Set(st.placements.map(x=>x.index)).size;if(count<job().pieces.length){log('The layout is incomplete.',`Place all ${job().pieces.length} unique pieces before cutting.`);return}const used=occupied().size,waste=W*H-used,defects=st.placements.filter(x=>x.defect).length,grain=st.placements.filter(x=>x.grain===job().grain).length;let round=110-waste-defects*30+grain*9+(st.unlock?8:0);round=clamp(Math.round(round),0,100);st.score+=round*12;st.trust=clamp(st.trust+(round>=78?8:round<55?-18:-6),0,100);st.alts-=defects;log(round>=84?'The cut plan is production-ready.':round>=64?'The garment can be saved with careful sewing.':'The layout creates costly fit problems.',`Layout ${round}. Waste ${waste} cells, ${defects} defect contact${defects===1?'':'s'}, ${grain}/${st.placements.length} pieces follow the preferred grain.`);if(st.score>=2500)st.unlock=true;if(st.trust<=0||st.alts<0)return end(false);if(st.job>=JOBS.length-1)return end(true);st.job++;st.pins=Math.min(10,st.pins+3);st.placements=[];st.selected=0;st.rotated=false;st.cursor=0;st.defects=makeDefects(st.job+2);draw()}
    function recover(){if(ended||!st.recovery)return;st.recovery=false;st.trust=clamp(st.trust-14,0,100);st.pins+=3;st.alts+=1;st.placements=[];st.selected=0;st.rotated=false;log('A remnant roll replaced the spoiled layout.','Pins and one alteration returned, but the delay reduced client trust.');draw()}
    function end(success){ended=true;const strong=success&&st.trust>=55&&st.score>=4300;log(strong?'The collection reaches the runway.':success?'The final garment ships with fragile margins.':'The studio loses the commission.',`Final score ${st.score}, trust ${st.trust}, alterations ${st.alts}. Replay to reduce waste and align more pieces to grain.`);draw()}
    function log(a,b){const l=$('.pt-log',root);l.replaceChildren(Object.assign(document.createElement('strong'),{textContent:a}),Object.assign(document.createElement('small'),{textContent:b}))}
    function draw(){const vals=[`${st.job+1}/5`,st.pins,st.alts,st.trust,st.score,st.unlock?'Bias cut':'Locked'];$$('[data-h]',root).forEach((e,i)=>e.textContent=vals[i]);$('.pt-piece-list',root).innerHTML=job().pieces.map((p,i)=>`<button class="pt-piece" data-piece="${i}" aria-pressed="${st.selected===i}">${p[0]} · ${p[1]}×${p[2]} · ${p[3]==='v'?'vertical':'cross'} grain</button>`).join('');const used=new Map(st.placements.flatMap(p=>p.cells.map(c=>[c,p])));board.innerHTML=Array.from({length:W*H},(_,i)=>{const p=used.get(i),def=st.defects.includes(i);return `<button class="pt-cell${p?' filled':''}${p?.defect?' bad':''}${def?' defect':''}" role="gridcell" data-cell="${i}" aria-selected="${st.cursor===i}" aria-label="Cell ${i+1}${def?', defect':''}${p?', occupied by '+p.name:''}"></button>`}).join('');const preview=piece(),cells=cellsFor(preview,st.cursor);if(cells)cells.forEach(c=>{const el=$(`[data-cell="${c}"]`,board);if(el&&!el.classList.contains('filled'))el.style.boxShadow='inset 0 0 0 2px rgba(124,58,237,.45)'});$('[data-a="finish"]',root).disabled=ended;$('[data-a="place"]',root).disabled=ended;$('[data-a="undo"]',root).disabled=ended||!st.placements.length;$('[data-a="recover"]',root).disabled=ended||!st.recovery;log(job().brief,st.unlock?'Bias cut unlocked: each finished layout gains a small craftsmanship bonus.':`Preferred fabric grain: ${job().grain==='v'?'vertical':'crosswise'}. Reach 2,500 points to unlock bias cutting.`)}
    root.addEventListener('click',e=>{const p=e.target.closest('[data-piece]');if(p){st.selected=+p.dataset.piece;st.rotated=false;draw();return}const c=e.target.closest('[data-cell]');if(c){st.cursor=+c.dataset.cell;draw();return}const a=e.target.closest('[data-a]')?.dataset.a;if(a==='place')place();if(a==='rotate'){st.rotated=!st.rotated;draw()}if(a==='undo')undo();if(a==='finish')finish();if(a==='recover')recover();if(a==='restart')reset()});
    root.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const x=st.cursor%W,y=Math.floor(st.cursor/W);if(e.key==='ArrowLeft')st.cursor=y*W+Math.max(0,x-1);if(e.key==='ArrowRight')st.cursor=y*W+Math.min(W-1,x+1);if(e.key==='ArrowUp')st.cursor=Math.max(0,y-1)*W+x;if(e.key==='ArrowDown')st.cursor=Math.min(H-1,y+1)*W+x;draw();$(`[data-cell="${st.cursor}"]`,board)?.focus()});
    dialog.addEventListener('close',()=>root.replaceChildren(),{once:true});reset()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();