(() => {
  const APP = { name: 'Petri Pursuit', emoji: '🧫', category: 'play', version: '1.0.0', summary: 'Grow helpful cultures across a dish while containing blight, toxins, heat, and scarce lab actions.', description: 'A local cellular-growth strategy game with adaptive lab briefs, spreading cultures, blight containment, nutrients, shields, antibiotics, mutations, scarce actions, recoverable contamination, session-only outbreak mode unlocks, scoring, responsive SVG rendering, touch and keyboard controls, reduced-motion behavior, optional audio, and teardown.' };
  const $ = (s) => document.querySelector(s);
  const label = (v) => v === 'play' ? 'Play' : v === 'useful' ? 'Useful' : 'Experiment';
  function style() {
    if ($('#petri-pursuit-styles')) return;
    const s = document.createElement('style');
    s.id = 'petri-pursuit-styles';
    s.textContent = `.petri-card{animation:petri-rise .24s ease both}.petri-game{max-width:1060px;gap:14px}.petri-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.petri-stat{border:1px solid var(--line);border-radius:15px;background:#fff;padding:10px 12px}.petri-stat span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.petri-stat strong{display:block;margin-top:4px}.petri-board{display:grid;grid-template-columns:1fr .9fr;gap:10px}.petri-dish{border:0;border-radius:28px;background:#07131a;color:white;padding:0;overflow:hidden;touch-action:none;box-shadow:inset 0 0 0 1px rgba(255,255,255,.14)}.petri-dish:focus-visible{outline:4px solid var(--accent);outline-offset:4px}.petri-dish svg{display:block;width:100%;height:min(58vh,520px);min-height:360px}.petri-panel{border:1px solid var(--line);border-radius:18px;background:#fff;padding:13px}.petri-tools,.petri-modes{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.petri-chip{border:1px solid var(--line);border-radius:999px;background:#fff;color:var(--ink);padding:8px 11px;font-weight:900}.petri-chip.is-active{background:#111827;color:#fff}.petri-log{min-height:100px;padding:17px 19px}.petri-meter{height:12px;border-radius:999px;background:#e8f5f1;overflow:hidden;margin-top:8px}.petri-meter span{display:block;height:100%;width:35%;background:linear-gradient(90deg,#86efac,#facc15,#fb7185)}@media(max-width:780px){.petri-hud{grid-template-columns:repeat(2,1fr)}.petri-board{grid-template-columns:1fr}.petri-dish svg{height:54vh;min-height:340px}}@media(prefers-reduced-motion:reduce){.petri-card{animation:none}.petri-dish svg{min-height:330px}}@keyframes petri-rise{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}`;
    document.head.append(s);
  }
  function addCard() {
    const grid = $('#app-grid'), tpl = $('#app-card-template');
    if (!grid || !tpl || $('[data-petri-card]')) return;
    const f = $('.filter.is-active')?.dataset.filter || 'all';
    if (f !== 'all' && f !== APP.category) return;
    style();
    const node = tpl.content.cloneNode(true), card = node.querySelector('.app-card');
    card.dataset.category = APP.category; card.dataset.petriCard = 'true'; card.classList.add('petri-card');
    node.querySelector('.app-icon').textContent = APP.emoji;
    node.querySelector('.app-meta').textContent = `${label(APP.category)} · v${APP.version}`;
    node.querySelector('.app-name').textContent = APP.name;
    node.querySelector('.app-summary').textContent = APP.summary;
    const btn = node.querySelector('.app-card-button');
    btn.setAttribute('aria-label', `Open ${APP.name}`);
    btn.addEventListener('click', open);
    grid.append(node);
  }
  function boot() {
    style(); addCard();
    document.querySelectorAll('.filter').forEach((b) => {
      if (b.dataset.petriRefresh) return;
      b.dataset.petriRefresh = '1';
      b.addEventListener('click', () => setTimeout(addCard, 0));
    });
  }
  function open() {
    const dialog = $('#app-dialog'), stage = $('#app-stage'), title = $('#dialog-title'), cat = $('#dialog-category'), desc = $('#dialog-description'), fb = $('#dialog-feedback');
    if (!dialog || !stage) return;
    title.textContent = APP.name; cat.textContent = `${label(APP.category)} · ${APP.emoji}`; desc.textContent = APP.description;
    fb.href = 'https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Petri%20Pursuit';
    stage.replaceChildren(); game(stage, dialog); dialog.showModal();
  }
  function game(stage, dialog) {
    const root = document.createElement('section');
    root.className = 'tool-panel petri-game';
    root.innerHTML = `<div class="petri-hud"><div class="petri-stat"><span>Brief</span><strong id="pp-brief">1 / 6</strong></div><div class="petri-stat"><span>Actions</span><strong id="pp-actions">8</strong></div><div class="petri-stat"><span>Culture</span><strong id="pp-culture">0</strong></div><div class="petri-stat"><span>Blight</span><strong id="pp-blight">0</strong></div><div class="petri-stat"><span>Heat</span><strong id="pp-heat">0</strong></div><div class="petri-stat"><span>Score</span><strong id="pp-score">0</strong></div></div><div class="petri-board"><button class="petri-dish" type="button" aria-label="Petri Pursuit dish. Use arrow keys to move, one for nutrient, two for shield, three for antibiotic, Enter to use the selected tool, Space to incubate, and N for a new brief."><svg role="img" aria-label="Animated petri dish grid"></svg></button><div class="petri-panel"><strong>Lab brief</strong><p id="pp-task"></p><div class="petri-meter"><span id="pp-meter"></span></div><div class="petri-modes"><button class="petri-chip is-active" type="button" data-tool="nutrient">1 Nutrient</button><button class="petri-chip" type="button" data-tool="shield">2 Shield</button><button class="petri-chip" type="button" data-tool="antibiotic">3 Antibiotic</button></div><div class="petri-tools"><button class="button button-secondary petri-chip" type="button" data-act="incubate">Incubate</button><button class="button button-secondary petri-chip" type="button" data-act="scrub">Scrub heat</button><button class="button button-secondary petri-chip" type="button" data-act="new">New brief</button></div><p><small>Goal: grow green culture into target zones while keeping red blight contained. Nutrients spread culture, shields block spread, antibiotics clear blight but add heat.</small></p></div></div><div class="result-card petri-log" aria-live="polite"></div><div class="tool-actions"></div>`;
    stage.append(root);
    const svg = root.querySelector('svg'), board = root.querySelector('.petri-dish'), log = root.querySelector('.petri-log'), meter = root.querySelector('#pp-meter'), reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
    const st = { brief:1, briefs:6, actions:8, heat:0, score:0, cursor:40, tool:'nutrient', outbreak:false, audio:false, ac:null, anim:0, cells:[], targets:[] };
    const W = 9, H = 9, N = W * H;
    root.querySelector('.tool-actions').append(btn('Outbreak mode', outbreak, true), btn('Sound off', sound, true));
    root.querySelectorAll('[data-tool]').forEach((b) => b.addEventListener('click', () => setTool(b.dataset.tool)));
    root.querySelectorAll('[data-act]').forEach((b) => b.addEventListener('click', () => action(b.dataset.act)));
    board.addEventListener('keydown', key); board.addEventListener('click', useTool); board.addEventListener('pointerdown', point); dialog.addEventListener('close', tear, { once:true });
    newBrief();
    function btn(t,f,sec){const b=document.createElement('button');b.type='button';b.className=sec?'button button-secondary':'button';b.textContent=t;b.addEventListener('click',f);return b;}
    function say(h){log.innerHTML=h;}
    function seed(){st.cells=Array.from({length:N},()=>({kind:'empty',age:0})); const targetSets=[[10,11,19,20,28],[6,7,15,24,33],[48,57,66,67,68],[36,37,38,46,54],[22,31,40,49,58],[2,12,22,32,42]]; st.targets=targetSets[(st.brief-1)%targetSets.length].slice(); const blights=[70,63,56,8,17,26,72,64]; for(let i=0;i<(st.outbreak?4:2)+Math.floor(st.brief/2);i++) st.cells[blights[i%blights.length]]={kind:'blight',age:1}; st.cells[40]={kind:'culture',age:2};}
    function newBrief(){cancelAnimationFrame(st.anim); Object.assign(st,{actions:st.outbreak?7:8,heat:0,cursor:40,tool:'nutrient'}); seed(); say(`<strong>Brief ${st.brief} opened.</strong><small>Reach at least ${st.outbreak?4:3} target wells before contamination overwhelms the dish.</small>`); paint(); draw();}
    function counts(){let culture=0, blight=0, shield=0, targets=0; st.cells.forEach((c,i)=>{if(c.kind==='culture')culture++; if(c.kind==='blight')blight++; if(c.kind==='shield')shield++; if(c.kind==='culture'&&st.targets.includes(i))targets++;}); return {culture, blight, shield, targets};}
    function paint(){const c=counts(); root.querySelector('#pp-brief').textContent=`${st.brief} / ${st.briefs}`; root.querySelector('#pp-actions').textContent=st.actions; root.querySelector('#pp-culture').textContent=c.culture; root.querySelector('#pp-blight').textContent=c.blight; root.querySelector('#pp-heat').textContent=st.heat; root.querySelector('#pp-score').textContent=st.score; root.querySelector('#pp-task').textContent=`Stabilize ${st.outbreak?'outbreak':'standard'} dish ${st.brief}: occupy target wells, keep blight under ${st.outbreak?11:9}, and finish before heat reaches ${st.outbreak?11:10}.`; meter.style.width=`${Math.min(100,Math.round((c.targets/(st.outbreak?4:3))*100))}%`; root.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('is-active',b.dataset.tool===st.tool));}
    function setTool(t){st.tool=t; paint(); draw();}
    function useTool(){if(st.actions<1){say('<strong>No actions left.</strong><small>Incubate to resolve the dish, or start a new brief.</small>'); return;} const c=st.cells[st.cursor]; if(st.tool==='nutrient'){st.cells[st.cursor]={kind:'culture',age:(c.age||0)+2}; st.actions--; st.heat++; say('<strong>Nutrient placed.</strong><small>Culture will spread from this well during incubation.</small>'); beep(520);} if(st.tool==='shield'){st.cells[st.cursor]={kind:'shield',age:1}; st.actions--; say('<strong>Shield set.</strong><small>This well blocks both culture and blight spread.</small>'); beep(380);} if(st.tool==='antibiotic'){st.cells[st.cursor]={kind:'empty',age:0}; st.actions--; st.heat+=2; say('<strong>Antibiotic pulse fired.</strong><small>Blight cleared, but dish heat rose.</small>'); beep(250);} paint(); draw();}
    function neighbors(i){const x=i%W,y=Math.floor(i/W), out=[]; [[1,0],[-1,0],[0,1],[0,-1]].forEach(([dx,dy])=>{const nx=x+dx,ny=y+dy;if(nx>=0&&nx<W&&ny>=0&&ny<H)out.push(ny*W+nx);}); return out;}
    function incubate(){const next=st.cells.map(c=>({...c})); st.cells.forEach((c,i)=>{if(c.kind==='culture'){neighbors(i).forEach(n=>{if(next[n].kind==='empty'&&Math.random()<(.36+Math.min(.24,c.age*.04)))next[n]={kind:'culture',age:1};}); next[i].age=Math.min(9,c.age+1);} if(c.kind==='blight'){neighbors(i).forEach(n=>{if(next[n].kind==='empty'&&Math.random()<(st.outbreak ? .42 : .32))next[n]={kind:'blight',age:1}; if(next[n].kind==='culture'&&Math.random()<.24)next[n]={kind:'blight',age:1};}); next[i].age=Math.min(9,c.age+1);}}); st.cells=next; st.actions=Math.max(0,st.actions-1); st.heat+=1; const c=counts(), pass=c.targets>=(st.outbreak?4:3)&&c.blight<(st.outbreak?11:9)&&st.heat<(st.outbreak?11:10); if(pass){const gain=160+c.targets*90+c.culture*4+st.actions*20-c.blight*12-st.heat*8; st.score+=Math.max(40,Math.round(gain)); beep(820); if(st.brief<st.briefs){st.brief++; say(`<strong>Dish stabilized.</strong><small>${c.targets} target wells colonized. Next brief increases the spread pressure.</small>`); newBrief();} else {say(`<strong>Run complete: ${st.score}.</strong><small>${st.score>=1450?'Outbreak mode unlocked for this session.':'Reach 1450 to unlock outbreak mode.'}</small>`);} } else if(c.blight>=14||st.heat>=13||st.actions<=0){st.score=Math.max(0,st.score-80); st.actions+=2; st.heat=Math.max(0,st.heat-3); beep(190); say('<strong>Containment failed, but the sample is recoverable.</strong><small>Two emergency actions restored. Clear blight or shield the target route.</small>');} else {say('<strong>Incubation advanced.</strong><small>Culture and blight both spread. Choose the next intervention carefully.</small>'); beep(460);} paint(); draw();}
    function action(k){if(k==='incubate')incubate(); if(k==='scrub'){if(st.actions<1)return say('<strong>Scrub unavailable.</strong><small>You need one action to vent heat.</small>');st.actions--;st.heat=Math.max(0,st.heat-4);say('<strong>Heat scrubbed.</strong><small>One action spent to keep the dish viable.</small>');paint();draw();} if(k==='new')newBrief();}
    function outbreak(){if(!st.outbreak&&st.score<1450)return say('<strong>Outbreak mode locked.</strong><small>Score 1450 in standard mode to unlock faster blight and fewer actions.</small>'); st.outbreak=!st.outbreak; st.brief=1; newBrief(); say(`<strong>${st.outbreak?'Outbreak':'Standard'} mode active.</strong><small>${st.outbreak?'Faster blight, fewer actions, bigger scoring upside.':'Standard lab rules restored.'}</small>`);}
    function point(e){const r=svg.getBoundingClientRect(); const x=(e.clientX-r.left)/r.width, y=(e.clientY-r.top)/r.height; const c=Math.max(0,Math.min(W-1,Math.floor(x*W))), row=Math.max(0,Math.min(H-1,Math.floor(y*H))); st.cursor=row*W+c; paint(); draw();}
    function key(e){const k=e.key.toLowerCase(); if(k==='1'){e.preventDefault();setTool('nutrient');} if(k==='2'){e.preventDefault();setTool('shield');} if(k==='3'){e.preventDefault();setTool('antibiotic');} if(k==='arrowright'){e.preventDefault();st.cursor=Math.min(N-1,st.cursor+1);draw();} if(k==='arrowleft'){e.preventDefault();st.cursor=Math.max(0,st.cursor-1);draw();} if(k==='arrowdown'){e.preventDefault();st.cursor=Math.min(N-1,st.cursor+W);draw();} if(k==='arrowup'){e.preventDefault();st.cursor=Math.max(0,st.cursor-W);draw();} if(k==='enter'){e.preventDefault();useTool();} if(k===' '){e.preventDefault();incubate();} if(k==='n'){e.preventDefault();newBrief();}}
    function draw(){const size=720, cell=size/W, c=counts(); let h=`<rect width="720" height="720" fill="#07131a"/><circle cx="360" cy="360" r="342" fill="#0d2630" stroke="rgba(255,255,255,.25)" stroke-width="12"/>`; for(let i=0;i<N;i++){const x=(i%W)*cell+cell/2, y=Math.floor(i/W)*cell+cell/2, cellData=st.cells[i], target=st.targets.includes(i); if(target)h+=`<circle cx="${x}" cy="${y}" r="${cell*.36}" fill="rgba(250,204,21,.16)" stroke="rgba(250,204,21,.75)" stroke-width="4"/>`; if(cellData.kind==='shield')h+=`<rect x="${x-cell*.3}" y="${y-cell*.3}" width="${cell*.6}" height="${cell*.6}" rx="14" fill="#93c5fd" opacity=".78"/>`; if(cellData.kind==='culture')h+=`<circle cx="${x}" cy="${y}" r="${cell*(.22+Math.min(.14,cellData.age*.018))}" fill="#86efac" opacity=".9"/><circle cx="${x+8}" cy="${y-8}" r="${cell*.08}" fill="#dcfce7" opacity=".7"/>`; if(cellData.kind==='blight')h+=`<path d="M ${x} ${y-cell*.28} L ${x+cell*.26} ${y+cell*.2} L ${x-cell*.26} ${y+cell*.2} Z" fill="#fb7185" opacity=".9"/><circle cx="${x}" cy="${y}" r="${cell*.1}" fill="#fecdd3"/>`; h+=`<rect x="${x-cell/2}" y="${y-cell/2}" width="${cell}" height="${cell}" fill="transparent" stroke="rgba(255,255,255,.05)"/>`; } const pulse=reduced?0:(Math.sin(Date.now()/280)+1)*3; const cx=(st.cursor%W)*cell+cell/2, cy=Math.floor(st.cursor/W)*cell+cell/2; h+=`<circle cx="${cx}" cy="${cy}" r="${cell*.43+pulse}" fill="none" stroke="#fff2bd" stroke-width="5"/><text x="360" y="692" text-anchor="middle" fill="rgba(255,255,255,.76)" font-size="22" font-weight="800">Targets ${c.targets} · Blight ${c.blight} · Tool ${st.tool}</text>`; svg.setAttribute('viewBox','0 0 720 720'); svg.innerHTML=h; if(!reduced)st.anim=requestAnimationFrame(draw);}
    function sound(e){const b=e.currentTarget, A=window.AudioContext||window.webkitAudioContext; if(!A)return say('<strong>Sound is not available here.</strong><small>The game still works without audio.</small>'); st.audio=!st.audio; b.textContent=st.audio?'Sound on':'Sound off'; b.setAttribute('aria-pressed',String(st.audio)); st.ac ||= new A(); st.ac.resume(); beep(600);}
    function beep(f){if(!st.audio||!st.ac)return; const now=st.ac.currentTime,o=st.ac.createOscillator(),g=st.ac.createGain(); o.type='sine'; o.frequency.setValueAtTime(f,now); g.gain.setValueAtTime(.0001,now); g.gain.exponentialRampToValueAtTime(.06,now+.02); g.gain.exponentialRampToValueAtTime(.0001,now+.18); o.connect(g).connect(st.ac.destination); o.start(now); o.stop(now+.2);}
    function tear(){cancelAnimationFrame(st.anim); if(st.ac)st.ac.close();}
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot); else boot();
})();
