(() => {
'use strict';
const APP={name:'Privacy Ledger',emoji:'◉',category:'play',version:'1.1.0',summary:'Publish six useful datasets while balancing privacy budget, utility, equity, and evolving attack pressure.',description:'A local-only privacy-engineering strategy game with six release rounds, differentiated protection controls, cumulative privacy budget, hidden linkage pressure, scarce audits, utility and equity targets, readiness feedback, progression, failure, recovery, a session unlock, keyboard and touch controls, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const CONTROLS=[
 {id:'noise',label:'Noise',help:'Blurs individual values. Strong against repeated-pattern attacks, but directly reduces analytical precision.',utility:4.4,risk:5.3,equity:-.4,budget:1.9},
 {id:'aggregation',label:'Aggregation',help:'Combines rows into broader groups. Best for rare geography and service categories; usually protects equity.',utility:3.1,risk:4.5,equity:1.8,budget:1.25},
 {id:'suppression',label:'Suppression',help:'Removes rare records. Powerful for small cohorts, but can erase vulnerable groups from the release.',utility:4.8,risk:5.7,equity:-5.8,budget:.95},
 {id:'sampling',label:'Sampling',help:'Publishes only part of the source. Limits linkage reach, but weakens coverage and representativeness.',utility:2.7,risk:3.7,equity:-3.9,budget:.85}
];
const RELEASES=[
 {name:'Release 1 · Transit demand',utility:55,risk:58,equity:54,focus:'noise',attack:'repeated travel signatures',hint:'Repeated travel patterns make individual routes easier to infer.'},
 {name:'Release 2 · School access',utility:59,risk:54,equity:53,focus:'suppression',attack:'small-cohort singling out',hint:'Small cohorts create a singling-out risk, but excessive suppression hides underserved students.'},
 {name:'Release 3 · Clinic capacity',utility:63,risk:49,equity:54,focus:'aggregation',attack:'rare-service geography linkage',hint:'Fine geographic detail reveals too much about rare services.'},
 {name:'Release 4 · Housing pressure',utility:67,risk:44,equity:52,focus:'sampling',attack:'full-population linkage',hint:'A complete extract makes linkage attacks unusually effective.'},
 {name:'Release 5 · Benefits uptake',utility:70,risk:39,equity:51,focus:'suppression',attack:'rare household combinations',hint:'Rare combinations identify vulnerable households, while broad suppression can erase them.'},
 {name:'Release 6 · Public research pack',utility:73,risk:34,equity:50,focus:'noise',attack:'cross-release composition',hint:'Multiple releases can be combined, so cumulative privacy loss matters.'}
];
function style(){if($('#privacy-ledger-style'))return;const e=document.createElement('style');e.id='privacy-ledger-style';e.textContent=`
.privacy-ledger{max-width:1120px;display:grid;gap:12px}.pl-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.pl-stat,.pl-panel{border:1px solid var(--line);border-radius:17px;background:#fff}.pl-stat{padding:9px}.pl-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.pl-layout{display:grid;grid-template-columns:1.08fr .92fr;gap:12px}.pl-panel{padding:15px}.pl-brief{padding:16px;border-radius:18px;background:linear-gradient(135deg,#26124a,#6d28d9);color:#fff}.pl-brief p{margin:.4rem 0}.pl-map{display:grid;grid-template-columns:repeat(7,1fr);gap:5px;margin:14px 0}.pl-cell{aspect-ratio:1;border-radius:8px;background:#ede9fe;transform:scale(calc(.72 + var(--v)*.003));opacity:calc(.45 + var(--v)*.005)}.pl-controls{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.pl-control{border:1px solid var(--line);border-radius:13px;padding:10px}.pl-control.is-selected{border-color:#6d28d9;box-shadow:0 0 0 2px #ede9fe}.pl-control p{min-height:3.2em;margin:.35rem 0;font-size:.78rem;color:var(--muted)}.pl-impact{font-size:.72rem;font-weight:800;color:#4c1d95}.pl-stepper{display:grid;grid-template-columns:46px 1fr 46px;gap:6px;align-items:center;margin-top:7px}.pl-stepper button,.pl-actions button{min-height:44px;border:1px solid var(--line);border-radius:10px;background:#fff;font-weight:900}.pl-stepper output{text-align:center;font-weight:900}.pl-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.pl-actions .primary{background:#ede9fe;border-color:#6d28d9}.pl-stepper button:focus-visible,.pl-actions button:focus-visible{outline:3px solid #6d28d9;outline-offset:2px}.pl-row{display:flex;justify-content:space-between;gap:10px;margin:7px 0}.pl-meter{height:10px;background:#eeeaf5;border-radius:99px;overflow:hidden}.pl-meter span{display:block;height:100%;background:#7c3aed;transition:width .25s}.pl-meter.bad span{background:#b91c1c}.pl-checks{display:grid;gap:6px;margin:12px 0}.pl-check{display:flex;justify-content:space-between;gap:8px;padding:8px 10px;border-radius:10px;background:#f7f5fb;font-size:.8rem}.pl-check strong.ok{color:#167345}.pl-check strong.no{color:#b42318}.pl-log{min-height:112px}.pl-hint{font-size:.82rem;color:var(--muted)}.pl-audit{padding:9px 10px;border-radius:10px;background:#f5f3ff;font-size:.8rem;margin:10px 0}
@media(max-width:840px){.pl-layout{grid-template-columns:1fr}.pl-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.pl-hud{grid-template-columns:repeat(2,1fr)}.pl-controls,.pl-actions{grid-template-columns:1fr}.pl-stepper{grid-template-columns:52px 1fr 52px}.pl-map{grid-template-columns:repeat(6,1fr)}.pl-control p{min-height:0}}@media(prefers-reduced-motion:reduce){.privacy-ledger *{animation:none!important;transition:none!important}}
`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-privacy-ledger]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true),a=$('.app-card',f);a.dataset.privacyLedger='1';a.dataset.category=APP.category;$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-privacy-ledger]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.plBound)return;b.dataset.plBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · privacy strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
 const root=document.createElement('section');root.className='tool-panel privacy-ledger';root.innerHTML=`<div class="pl-hud">${['Release','Budget','Utility','Risk','Trust','Score'].map((x,i)=>`<div class="pl-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="pl-layout"><section class="pl-panel"><div class="pl-brief"><p class="app-meta" data-set></p><h3 data-title></h3><p data-hint></p></div><div class="pl-map" aria-hidden="true" data-map></div><div class="pl-controls" data-controls></div><p class="pl-hint">Keyboard: 1-4 select a control, ↑/↓ adjust, A audit, Enter publish.</p></section><aside class="pl-panel"><div class="result-card pl-log" aria-live="polite"></div><div class="pl-row"><span>Projected utility</span><strong data-utility></strong></div><div class="pl-meter"><span data-umeter></span></div><div class="pl-row"><span>Projected disclosure risk</span><strong data-risk></strong></div><div class="pl-meter bad"><span data-rmeter></span></div><div class="pl-row"><span>Projected equity</span><strong data-equity></strong></div><div class="pl-row"><span>Projected budget spend</span><strong data-spend></strong></div><div class="pl-audit" data-audit>Attack pressure is estimated until you spend an audit.</div><div class="pl-checks" data-checks></div><div class="pl-row"><span>Audits left</span><strong data-audits></strong></div><div class="pl-actions"><button class="primary" data-a="publish">Publish release</button><button data-a="audit">Run attack audit</button><button data-a="recover">Call privacy counsel</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
 let st,ended=false,keyHandler,closeHandler;
 function reset(){st={level:0,budget:100,trust:74,score:0,controls:{noise:4,aggregation:4,suppression:3,sampling:3},selected:0,audits:2,counsel:true,unlock:false,lastUtility:0,lastRisk:0,attack:12,audited:false};ended=false;log('Release board ready.','Tune the controls until utility, disclosure risk, equity, and cumulative budget all clear the release gate.');draw()}
 function release(){return RELEASES[st.level]}
 function metrics(){const r=release(),c=st.controls;let protection=0,utilityLoss=0,equity=98,spend=24;CONTROLS.forEach(x=>{const v=c[x.id],focus=x.id===r.focus?1.35:1;protection+=v*x.risk*focus;utilityLoss+=v*x.utility;equity+=v*x.equity;spend-=v*x.budget});const utility=clamp(104-utilityLoss,0,100),risk=clamp(92-protection+st.attack-(st.unlock?4:0),0,100);return{utility,risk,equity:clamp(equity,0,100),spend:Math.max(4,spend)}}
 function adjust(delta){if(ended)return;const id=CONTROLS[st.selected].id;st.controls[id]=clamp(st.controls[id]+delta,0,10);st.audited=false;draw()}
 function audit(){if(ended||st.audits<=0)return log('No audits left.','Publish with current evidence or use the one session recovery.');st.audits--;st.audited=true;const m=metrics();log(`Attack audit: ${Math.round(m.risk)} risk.`,`${release().hint} ${CONTROLS.find(x=>x.id===release().focus).label} is the strongest protection lever in this release.`);draw()}
 function publish(){if(ended)return;const m=metrics(),r=release();st.lastUtility=m.utility;st.lastRisk=m.risk;st.budget=clamp(st.budget-m.spend,0,100);st.attack=clamp(st.attack+4,0,35);const pass=m.utility>=r.utility&&m.risk<=r.risk&&m.equity>=r.equity&&st.budget>5;if(pass){st.trust=clamp(st.trust+5,0,100);st.score+=Math.round(m.utility*7+(100-m.risk)*8+m.equity*3+st.budget*2);if(st.score>=3000)st.unlock=true;if(st.level===RELEASES.length-1)return finish(true,`Research pack published with ${st.score} points and ${Math.round(st.budget)} privacy budget remaining.`);st.level++;st.audits=Math.min(3,st.audits+1);st.audited=false;log('Release approved.',`Utility ${Math.round(m.utility)}, risk ${Math.round(m.risk)}, equity ${Math.round(m.equity)}, and budget spend ${Math.round(m.spend)} cleared the board.`);draw();return}st.trust=clamp(st.trust-14,0,100);st.score=Math.max(0,st.score-180);log('Release rejected.',`The readiness panel shows which gates failed. Rebalance instead of simply maximizing every protection control.`);if(st.trust<=18||st.budget<=5)return finish(false,'The publication program stopped after privacy confidence or cumulative budget collapsed.');draw()}
 function recover(){if(ended||!st.counsel)return log('Counsel unavailable.','The one session intervention has already been used.');st.counsel=false;st.trust=Math.max(0,st.trust-8);st.budget=Math.max(0,st.budget-12);st.audits+=1;st.controls={noise:6,aggregation:6,suppression:4,sampling:4};st.audited=true;log('Privacy counsel intervened.','A safer baseline and one audit returned, but the intervention costs 12 budget and 8 trust.');draw()}
 function finish(win,msg){ended=true;log(win?'Publication program complete.':'Program halted.',msg);draw()}
 function log(a,b){$('.pl-log',root).innerHTML=`<strong>${a}</strong><p>${b}</p>`}
 function draw(){const m=metrics(),r=release(),riskText=st.audited?Math.round(m.risk):`${Math.max(0,Math.round(m.risk-6))}–${Math.min(100,Math.round(m.risk+6))}`;$$('[data-h]',root).forEach((e,i)=>e.textContent=[`${st.level+1}/6`,Math.round(st.budget),Math.round(st.lastUtility||m.utility),Math.round(st.lastRisk||m.risk),Math.round(st.trust),st.score][i]);$('[data-set]',root).textContent=r.name;$('[data-title]',root).textContent=`Need utility ${r.utility}+ · risk ${r.risk}− · equity ${r.equity}+`;$('[data-hint]',root).textContent=st.unlock?'Composition accounting unlocked: projected risk is reduced by 4.':'Each publication increases future linkage pressure.';$('[data-controls]',root).innerHTML=CONTROLS.map((x,i)=>`<div class="pl-control ${i===st.selected?'is-selected':''}"><div class="pl-row"><strong>${i+1}. ${x.label}</strong>${i===st.selected?'<span>Selected</span>':''}</div><p>${x.help}</p><div class="pl-impact">Current level ${st.controls[x.id]}${x.id===r.focus?' · scenario bonus':''}</div><div class="pl-stepper"><button data-k="${i}" data-d="-1" aria-label="Decrease ${x.label}">−</button><output aria-label="${x.label} level">${st.controls[x.id]}</output><button data-k="${i}" data-d="1" aria-label="Increase ${x.label}">+</button></div></div>`).join('');$('[data-utility]',root).textContent=Math.round(m.utility);$('[data-umeter]',root).style.width=`${m.utility}%`;$('[data-risk]',root).textContent=riskText;$('[data-rmeter]',root).style.width=`${m.risk}%`;$('[data-equity]',root).textContent=Math.round(m.equity);$('[data-spend]',root).textContent=Math.round(m.spend);$('[data-audits]',root).textContent=st.audits;$('[data-audit]',root).textContent=st.audited?`Audit confirmed ${r.attack} at ${Math.round(m.risk)} projected risk.`:`Unaudited estimate: risk may vary by ±6. Suspected vector: ${r.attack}.`;$('[data-checks]',root).innerHTML=[['Utility',m.utility>=r.utility,`${Math.round(m.utility)} / ${r.utility}`],['Risk',m.risk<=r.risk,`${Math.round(m.risk)} / ${r.risk} max`],['Equity',m.equity>=r.equity,`${Math.round(m.equity)} / ${r.equity}`],['Budget after publish',st.budget-m.spend>5,`${Math.round(st.budget-m.spend)} remaining`]].map(([label,ok,value])=>`<div class="pl-check"><span>${label}</span><strong class="${ok?'ok':'no'}">${ok?'Ready':'Not ready'} · ${value}</strong></div>`).join('');$('[data-map]',root).innerHTML=Array.from({length:42},(_,i)=>`<span class="pl-cell" style="--v:${clamp(m.utility-m.risk+(i%7)*5,5,95)}"></span>`).join('');$$('[data-k]',root).forEach(b=>b.addEventListener('click',()=>{st.selected=+b.dataset.k;adjust(+b.dataset.d)}));$$('[data-a]',root).forEach(b=>{const action=b.dataset.a;b.disabled=(ended&&action!=='restart')||(action==='audit'&&st.audits<=0)||(action==='recover'&&!st.counsel);b.onclick=()=>({publish,audit,recover,restart:reset}[action]||(()=>{}))()})}
 keyHandler=e=>{if(!dialog.open)return;if(['1','2','3','4'].includes(e.key)){st.selected=+e.key-1;draw()}else if(e.key==='ArrowUp'){e.preventDefault();adjust(1)}else if(e.key==='ArrowDown'){e.preventDefault();adjust(-1)}else if(e.key.toLowerCase()==='a')audit();else if(e.key==='Enter')publish()};document.addEventListener('keydown',keyHandler);
 closeHandler=()=>{document.removeEventListener('keydown',keyHandler);dialog.removeEventListener('close',closeHandler)};dialog.addEventListener('close',closeHandler);reset()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
