(() => {
'use strict';
const APP={name:'Privacy Ledger',emoji:'◉',category:'play',version:'1.0.0',summary:'Publish six useful datasets without exhausting privacy budget or exposing vulnerable groups.',description:'A local-only privacy-engineering strategy game with six release rounds, adjustable noise, aggregation, suppression, and sampling, hidden attack pressure, limited audits, utility and equity targets, cumulative privacy budget, trust, progression, failure, recovery, a session unlock, keyboard and touch controls, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const CONTROLS=[['noise','Noise'],['aggregation','Aggregation'],['suppression','Suppression'],['sampling','Sampling']];
const RELEASES=[
{name:'Release 1 · Transit demand',utility:55,risk:58,budget:18,focus:'noise',hint:'Repeated travel patterns make individual routes easier to infer.'},
{name:'Release 2 · School access',utility:59,risk:54,budget:17,focus:'suppression',hint:'Small cohorts create a singling-out risk.'},
{name:'Release 3 · Clinic capacity',utility:63,risk:49,budget:16,focus:'aggregation',hint:'Fine geographic detail reveals too much about rare services.'},
{name:'Release 4 · Housing pressure',utility:67,risk:44,budget:15,focus:'sampling',hint:'A complete extract makes linkage attacks unusually effective.'},
{name:'Release 5 · Benefits uptake',utility:70,risk:39,budget:14,focus:'suppression',hint:'Rare combinations can identify vulnerable households.'},
{name:'Release 6 · Public research pack',utility:73,risk:34,budget:13,focus:'noise',hint:'Multiple releases can be combined, so cumulative privacy loss matters.'}
];
function style(){if($('#privacy-ledger-style'))return;const e=document.createElement('style');e.id='privacy-ledger-style';e.textContent=`
.privacy-ledger{max-width:1120px;display:grid;gap:12px}.pl-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.pl-stat,.pl-panel{border:1px solid var(--line);border-radius:17px;background:#fff}.pl-stat{padding:9px}.pl-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.pl-layout{display:grid;grid-template-columns:1.05fr .95fr;gap:12px}.pl-panel{padding:15px}.pl-brief{padding:16px;border-radius:18px;background:linear-gradient(135deg,#26124a,#6d28d9);color:#fff}.pl-map{display:grid;grid-template-columns:repeat(7,1fr);gap:5px;margin:14px 0}.pl-cell{aspect-ratio:1;border-radius:8px;background:#ede9fe;transform:scale(calc(.72 + var(--v)*.003));opacity:calc(.45 + var(--v)*.005)}.pl-controls{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.pl-control{border:1px solid var(--line);border-radius:13px;padding:10px}.pl-stepper{display:grid;grid-template-columns:42px 1fr 42px;gap:6px;align-items:center;margin-top:7px}.pl-stepper button,.pl-actions button{min-height:42px;border:1px solid var(--line);border-radius:10px;background:#fff;font-weight:900}.pl-stepper output{text-align:center;font-weight:900}.pl-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.pl-actions .primary{background:#ede9fe;border-color:#6d28d9}.pl-stepper button:focus-visible,.pl-actions button:focus-visible{outline:3px solid #6d28d9;outline-offset:2px}.pl-row{display:flex;justify-content:space-between;gap:10px;margin:7px 0}.pl-meter{height:10px;background:#eeeaf5;border-radius:99px;overflow:hidden}.pl-meter span{display:block;height:100%;background:#7c3aed;transition:width .25s}.pl-log{min-height:112px}.pl-hint{font-size:.82rem;color:var(--muted)}
@media(max-width:840px){.pl-layout{grid-template-columns:1fr}.pl-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.pl-hud{grid-template-columns:repeat(2,1fr)}.pl-controls,.pl-actions{grid-template-columns:1fr}.pl-stepper{grid-template-columns:48px 1fr 48px}.pl-map{grid-template-columns:repeat(6,1fr)}}@media(prefers-reduced-motion:reduce){.privacy-ledger *{animation:none!important;transition:none!important}}
`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-privacy-ledger]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true),a=$('.app-card',f);a.dataset.privacyLedger='1';a.dataset.category=APP.category;$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-privacy-ledger]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.plBound)return;b.dataset.plBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · privacy strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
 const root=document.createElement('section');root.className='tool-panel privacy-ledger';root.innerHTML=`<div class="pl-hud">${['Release','Budget','Utility','Risk','Trust','Score'].map((x,i)=>`<div class="pl-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="pl-layout"><section class="pl-panel"><div class="pl-brief"><p class="app-meta" data-set></p><h3 data-title></h3><p data-hint></p></div><div class="pl-map" aria-hidden="true" data-map></div><div class="pl-controls" data-controls></div><p class="pl-hint">Keyboard: 1-4 select a control, ↑/↓ adjust, A audit, Enter publish.</p></section><aside class="pl-panel"><div class="result-card pl-log" aria-live="polite"></div><div class="pl-row"><span>Projected utility</span><strong data-utility></strong></div><div class="pl-meter"><span data-umeter></span></div><div class="pl-row"><span>Projected disclosure risk</span><strong data-risk></strong></div><div class="pl-meter"><span data-rmeter></span></div><div class="pl-row"><span>Equity coverage</span><strong data-equity></strong></div><div class="pl-row"><span>Audits left</span><strong data-audits></strong></div><div class="pl-actions"><button class="primary" data-a="publish">Publish release</button><button data-a="audit">Run attack audit</button><button data-a="recover">Call privacy counsel</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
 let st,ended=false,keyHandler,closeHandler;
 function reset(){st={level:0,budget:100,trust:74,score:0,controls:{noise:4,aggregation:4,suppression:3,sampling:3},selected:0,audits:2,counsel:true,unlock:false,lastUtility:0,lastRisk:0,attack:12};ended=false;log('Release board ready.','Preserve useful analysis while keeping disclosure risk below each release threshold.');draw()}
 function release(){return RELEASES[st.level]}
 function metrics(){const r=release(),c=st.controls;const protection=c.noise*5+c.aggregation*4.5+c.suppression*5.5+c.sampling*3.5+(st.unlock?4:0);const utility=clamp(104-c.noise*4-c.aggregation*3-c.suppression*4.5-c.sampling*2.5,0,100);const risk=clamp(92-protection+st.attack,0,100);const equity=clamp(98-c.suppression*6-c.sampling*4+c.aggregation*2,0,100);const spend=Math.max(4,24-c.noise*1.8-c.aggregation*1.2-c.suppression*.9-c.sampling*.8);return{utility,risk,equity,spend}}
 function adjust(delta){if(ended)return;const id=CONTROLS[st.selected][0];st.controls[id]=clamp(st.controls[id]+delta,0,10);draw()}
 function audit(){if(ended||st.audits<=0)return log('No audits left.','Publish with current evidence or use the one session recovery.');st.audits--;const m=metrics();log(`Attack audit: ${Math.round(m.risk)} risk.`,`${release().hint} ${CONTROLS.find(x=>x[0]===release().focus)[1]} is the strongest protection lever.`);draw()}
 function publish(){if(ended)return;const m=metrics(),r=release();st.lastUtility=m.utility;st.lastRisk=m.risk;st.budget=clamp(st.budget-m.spend,0,100);st.attack=clamp(st.attack+4,0,35);const pass=m.utility>=r.utility&&m.risk<=r.risk&&m.equity>=48&&st.budget>=0;if(pass){st.trust=clamp(st.trust+5,0,100);st.score+=Math.round(m.utility*7+(100-m.risk)*8+m.equity*3+st.budget*2);if(st.score>=3000)st.unlock=true;if(st.level===RELEASES.length-1)return finish(true,`Research pack published with ${st.score} points and ${Math.round(st.budget)} privacy budget remaining.`);st.level++;st.audits=Math.min(3,st.audits+1);log('Release approved.',`Utility ${Math.round(m.utility)}, risk ${Math.round(m.risk)}, and equity ${Math.round(m.equity)} cleared the board.`);draw();return}st.trust=clamp(st.trust-14,0,100);st.score=Math.max(0,st.score-180);log('Release rejected.',`Targets missed: utility ${Math.round(m.utility)}/${r.utility}, risk ${Math.round(m.risk)}/${r.risk}, equity ${Math.round(m.equity)}/48.`);if(st.trust<=18||st.budget<=5)return finish(false,'The publication program stopped after privacy confidence collapsed.');draw()}
 function recover(){if(ended||!st.counsel)return log('Counsel unavailable.','The one session intervention has already been used.');st.counsel=false;st.trust=Math.max(0,st.trust-6);st.budget=Math.max(0,st.budget-10);st.audits+=1;st.controls={noise:6,aggregation:6,suppression:5,sampling:4};log('Privacy counsel intervened.','A safer baseline and one audit returned, but trust and cumulative budget costs remain.');draw()}
 function finish(win,msg){ended=true;log(win?'Publication program complete.':'Program halted.',msg);draw()}
 function log(a,b){$('.pl-log',root).innerHTML=`<strong>${a}</strong><p>${b}</p>`}
 function draw(){const m=metrics(),r=release();$$('[data-h]',root).forEach((e,i)=>e.textContent=[`${st.level+1}/6`,Math.round(st.budget),Math.round(st.lastUtility||m.utility),Math.round(st.lastRisk||m.risk),Math.round(st.trust),st.score][i]);$('[data-set]',root).textContent=r.name;$('[data-title]',root).textContent=`Need utility ${r.utility}+ · risk ${r.risk}−`;$('[data-hint]',root).textContent=st.unlock?'Privacy ledger unlock active: stronger composition accounting lowers projected risk by 4.':'Every publication increases future linkage pressure.';$('[data-controls]',root).innerHTML=CONTROLS.map(([id,label],i)=>`<div class="pl-control"><div class="pl-row"><strong>${i+1}. ${label}</strong>${i===st.selected?'<span>Selected</span>':''}</div><div class="pl-stepper"><button data-k="${i}" data-d="-1" aria-label="Decrease ${label}">−</button><output>${st.controls[id]}</output><button data-k="${i}" data-d="1" aria-label="Increase ${label}">+</button></div></div>`).join('');$('[data-utility]',root).textContent=Math.round(m.utility);$('[data-umeter]',root).style.width=`${m.utility}%`;$('[data-risk]',root).textContent=Math.round(m.risk);$('[data-rmeter]',root).style.width=`${m.risk}%`;$('[data-equity]',root).textContent=Math.round(m.equity);$('[data-audits]',root).textContent=st.audits;$('[data-map]',root).innerHTML=Array.from({length:42},(_,i)=>`<span class="pl-cell" style="--v:${clamp(m.utility-m.risk+(i%7)*5,5,95)}"></span>`).join('');$$('[data-k]',root).forEach(b=>b.addEventListener('click',()=>{st.selected=+b.dataset.k;adjust(+b.dataset.d)}));$$('[data-a]',root).forEach(b=>{b.disabled=ended&&b.dataset.a!=='restart';b.onclick=()=>({publish,audit,recover,restart:reset}[b.dataset.a]||(()=>{}))()})}
 keyHandler=e=>{if(!dialog.open)return;if(['1','2','3','4'].includes(e.key)){st.selected=+e.key-1;draw()}else if(e.key==='ArrowUp'){e.preventDefault();adjust(1)}else if(e.key==='ArrowDown'){e.preventDefault();adjust(-1)}else if(e.key.toLowerCase()==='a')audit();else if(e.key==='Enter')publish()};document.addEventListener('keydown',keyHandler);
 closeHandler=()=>{document.removeEventListener('keydown',keyHandler);dialog.removeEventListener('close',closeHandler)};dialog.addEventListener('close',closeHandler);reset()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
