(() => {
  'use strict';
  const APP={name:'Pulse Loom',emoji:'🎛️',category:'play',version:'1.0.0',summary:'Weave four musical lanes into evolving patterns while meeting changing crowd briefs.',description:'A local-only tactile arrangement game with a four-lane step sequencer, changing briefs, energy and crowd tradeoffs, combo scoring, unlockable accents, optional Web Audio, touch, keyboard, mobile, reduced-motion, and teardown support.'};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const LANES=[['Kick','●',80],['Snare','▲',180],['Hat','◆',420],['Accent','✦',640]],BRIEFS=[{name:'Steady opener',need:[2,2,3,0],rule:'Build a readable pulse.'},{name:'Offbeat lift',need:[2,2,4,1],rule:'Favor odd-numbered hat steps.'},{name:'Space to breathe',need:[2,1,3,1],rule:'Keep at least 18 empty cells.'},{name:'Peak hour',need:[3,3,5,2],rule:'Use every lane without draining energy.'},{name:'Broken mirror',need:[3,2,4,2],rule:'Match the first four steps in reverse.'},{name:'Final weave',need:[3,3,5,3],rule:'Finish with crowd 60+ and energy 20+.'}];
  function style(){if($('#pulse-loom-style'))return;const e=document.createElement('style');e.id='pulse-loom-style';e.textContent=`.pulse-loom{max-width:1080px;display:grid;gap:12px}.pl-hud{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}.pl-stat,.pl-card{border:1px solid var(--line);border-radius:16px;background:#fff}.pl-stat{padding:8px}.pl-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.pl-layout{display:grid;grid-template-columns:1.2fr .8fr;gap:12px}.pl-card{padding:14px}.pl-board{display:grid;grid-template-columns:72px repeat(8,minmax(34px,1fr));gap:5px;align-items:center}.pl-label{font-size:.72rem;font-weight:900}.pl-step{aspect-ratio:1;border:2px solid #cbd5e1;border-radius:10px;background:#f8fafc;font-size:1rem}.pl-step[aria-pressed=true]{background:#ede9fe;border-color:#7c3aed;box-shadow:inset 0 0 0 2px #fff}.pl-step[data-play=true]{outline:3px solid #f59e0b;outline-offset:1px}.pl-step:disabled{opacity:.35}.pl-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.pulse-loom button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;color:inherit;font-weight:800;padding:9px}.pulse-loom button.primary,.pulse-loom button[aria-pressed=true]{background:#ede9fe;border-color:#7c3aed}.pl-meter{height:10px;background:#e2e8f0;border-radius:999px;overflow:hidden}.pl-meter span{display:block;height:100%;background:linear-gradient(90deg,#dc2626,#f59e0b,#16a34a);transition:width .2s}.pl-log{min-height:100px}.pl-brief{padding:10px;border-radius:12px;background:#faf5ff}.pl-badges{display:flex;flex-wrap:wrap;gap:6px}.pl-tag{padding:4px 8px;border-radius:999px;background:#eef2ff;font-size:.72rem}.pl-pulse{animation:plPulse .25s ease}@keyframes plPulse{50%{transform:scale(1.012)}}@media(max-width:820px){.pl-layout{grid-template-columns:1fr}.pl-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.pl-hud{grid-template-columns:repeat(2,1fr)}.pl-board{grid-template-columns:55px repeat(8,minmax(27px,1fr));gap:3px}.pl-step{border-radius:7px;padding:2px}.pl-actions{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){.pulse-loom *{animation:none!important;transition:none!important}}`;document.head.append(e)}
  function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-pulse-loom]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.pulseLoom='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
  function boot(){style();let n=0;const r=()=>{card();if(!$('[data-pulse-loom]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.plBound)return;b.dataset.plBound='1';b.addEventListener('click',()=>setTimeout(card))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · arrangement strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel pulse-loom';root.innerHTML=`<div class="pl-hud">${['Set','Energy','Crowd','Combo','Score'].map((x,i)=>`<div class="pl-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="pl-layout"><section class="pl-card"><p class="eyebrow">Pattern loom</p><h3>Shape the eight-step loop</h3><div class="pl-board" role="grid" aria-label="Four lane by eight step music sequencer" data-board></div><p><small>Tap cells to add or remove hits. Arrow keys move; Space toggles a focused cell.</small></p><div class="pl-badges"><span class="pl-tag">Kick costs 2</span><span class="pl-tag">Snare costs 2</span><span class="pl-tag">Hat costs 1</span><span class="pl-tag">Accent costs 3</span></div></section><aside class="pl-card"><p class="eyebrow">Crowd brief</p><div class="pl-brief"><strong data-brief></strong><p data-rule></p><div class="pl-meter" aria-label="Brief match"><span data-meter></span></div></div><div class="pl-actions"><button class="primary" data-a="preview">Preview loop</button><button data-a="submit">Play the set</button><button data-a="clear">Clear pattern</button><button data-a="audio" aria-pressed="false">Audio off</button><button data-a="recover">Drop to halftime<br><small>once · -12 crowd</small></button><button data-a="restart">New session</button></div><h3>Producer notes</h3><div class="result-card pl-log" aria-live="polite"></div></aside></div>`;stage.append(root);
    let grid,st,timer=null,ctx=null,playing=false,ended=false;
    const cost=[2,2,1,3],log=(a,b)=>{const l=$('.pl-log',root);l.replaceChildren(Object.assign(document.createElement('strong'),{textContent:a}),Object.assign(document.createElement('small'),{textContent:b}))};
    function reset(){stop();grid=Array.from({length:4},()=>Array(8).fill(false));st={round:0,energy:72,crowd:45,combo:0,score:0,recovery:true,audio:false,accent:false};ended=false;log('The room is waiting.','Build the opener, preview it, then commit the set. Accent unlocks after 900 points.');draw()}
    function counts(){return grid.map(r=>r.filter(Boolean).length)}
    function symmetry(){let n=0;for(let r=0;r<4;r++)for(let c=0;c<4;c++)if(grid[r][c]===grid[r][7-c])n++;return n}
    function oddHats(){return [0,2,4,6].filter(c=>grid[2][c]).length}
    function match(){const b=BRIEFS[st.round],c=counts();let m=c.reduce((s,v,i)=>s+Math.max(0,4-Math.abs(v-b.need[i])*1.25),0);if(st.round===1)m+=oddHats()*1.2;if(st.round===2)m+=Math.max(0,24-c.reduce((a,v)=>a+v,0))*.35;if(st.round===4)m+=symmetry()*.35;return clamp(Math.round(m/22*100),0,100)}
    function toggle(r,c){if(ended||r===3&&!st.accent)return;const next=!grid[r][c],delta=next?-cost[r]:cost[r];if(next&&st.energy<cost[r])return log('Not enough energy.','Remove hits, use halftime recovery, or submit a leaner pattern.');grid[r][c]=next;st.energy=clamp(st.energy+delta,0,99);draw()}
    function tone(freq,t){if(!ctx||!st.audio)return;const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=freq;o.type=freq<100?'sine':'triangle';g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.09,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+.12);o.connect(g).connect(ctx.destination);o.start(t);o.stop(t+.14)}
    function stop(){if(timer){clearInterval(timer);timer=null}playing=false;$$('.pl-step',root).forEach(b=>b.dataset.play='false')}
    function preview(){if(playing){stop();draw();return}playing=true;let c=0;const tick=()=>{$$('.pl-step',root).forEach(b=>b.dataset.play=String(+b.dataset.c===c));grid.forEach((r,i)=>{if(r[c])tone(LANES[i][2],ctx?.currentTime||0)});c=(c+1)%8};tick();timer=setInterval(tick,180);setTimeout(()=>{if(playing){stop();draw()}},8*180+60)}
    function submit(){if(ended)return;stop();const q=match(),hits=counts().reduce((a,v)=>a+v,0);if(hits<5)return log('The loop is too thin.','Use at least five hits before playing the set.');const gain=Math.round((q-50)/5);st.crowd=clamp(st.crowd+gain,0,100);st.combo=q>=72?st.combo+1:0;const pts=Math.max(0,q*8+st.combo*90+st.energy*2);st.score+=pts;if(st.score>=900)st.accent=true;root.classList.add('pl-pulse');setTimeout(()=>root.classList.remove('pl-pulse'),260);if(st.crowd<=0||st.energy<=0){ended=true;log('The room lost the thread.',`Crowd ${st.crowd}, energy ${st.energy}. Restart and leave more space between peaks.`);draw();return}st.round++;if(st.round>=BRIEFS.length){ended=true;const win=st.crowd>=60&&st.energy>=20;log(win?'Headline set secured.':'The set survived, but never fully landed.',`Final crowd ${st.crowd}, energy ${st.energy}, score ${st.score}. ${win?'Your arrangement balanced repetition, surprise, and restraint.':'Replay and protect energy before the final weave.'}`);draw();return}st.energy=clamp(st.energy+14,0,99);log(q>=72?'The crowd locked in.':'The transition felt uncertain.',`Brief match ${q}%. ${pts} points. New energy arrived for set ${st.round+1}.`);draw()}
    function recover(){if(ended||!st.recovery)return;st.recovery=false;st.energy=clamp(st.energy+28,0,99);st.crowd=clamp(st.crowd-12,0,100);st.combo=0;log('Halftime breakdown engaged.','Energy rose by 28, crowd fell by 12, and the combo reset.');draw()}
    function draw(){const b=BRIEFS[Math.min(st.round,BRIEFS.length-1)],vals=[`${Math.min(st.round+1,6)}/6`,st.energy,st.crowd,st.combo,st.score];$$('[data-h]',root).forEach((e,i)=>e.textContent=vals[i]);$('[data-brief]',root).textContent=b.name;$('[data-rule]',root).textContent=b.rule;$('[data-meter]',root).style.width=`${match()}%`;const board=$('[data-board]',root);board.innerHTML=LANES.map((l,r)=>`<span class="pl-label">${l[1]} ${l[0]}</span>${grid[r].map((on,c)=>`<button class="pl-step" role="gridcell" data-r="${r}" data-c="${c}" aria-pressed="${on}" aria-label="${l[0]} step ${c+1}, ${on?'on':'off'}" ${r===3&&!st.accent?'disabled':''}>${on?l[1]:c+1}</button>`).join('')}`).join('');$$('.pl-step',board).forEach(x=>x.addEventListener('click',()=>toggle(+x.dataset.r,+x.dataset.c)));$('[data-a="audio"]',root).textContent=st.audio?'Audio on':'Audio off';$('[data-a="audio"]',root).setAttribute('aria-pressed',String(st.audio));$('[data-a="recover"]',root).disabled=ended||!st.recovery;$$('[data-a]',root).forEach(x=>{if(!['restart','audio'].includes(x.dataset.a))x.disabled=ended});}
    root.addEventListener('click',e=>{const a=e.target.closest('[data-a]')?.dataset.a;if(a==='preview')preview();if(a==='submit')submit();if(a==='clear'){grid.forEach(r=>r.fill(false));st.energy=clamp(st.energy+16,0,99);log('Pattern cleared.','A partial energy refund was returned.');draw()}if(a==='audio'){if(!ctx)ctx=new (window.AudioContext||window.webkitAudioContext)();st.audio=!st.audio;draw()}if(a==='recover')recover();if(a==='restart')reset()});root.addEventListener('keydown',e=>{if(!e.target.matches('.pl-step'))return;const r=+e.target.dataset.r,c=+e.target.dataset.c;if(e.key===' '||e.key==='Enter'){e.preventDefault();toggle(r,c);$(`.pl-step[data-r="${r}"][data-c="${c}"]`,root)?.focus();return}const d={ArrowUp:[r-1,c],ArrowDown:[r+1,c],ArrowLeft:[r,c-1],ArrowRight:[r,c+1]}[e.key];if(!d)return;e.preventDefault();const [nr,nc]=d;if(nr<0||nr>3||nc<0||nc>7)return;$(`.pl-step[data-r="${nr}"][data-c="${nc}"]`,root)?.focus()});dialog.addEventListener('close',()=>{stop();if(ctx)ctx.close();root.replaceChildren()},{once:true});reset()
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();