(() => {
'use strict';
const APP={name:'Pulse Atelier',emoji:'🎛️',category:'play',version:'1.0.0',summary:'Shape six evolving soundscapes by balancing rhythm, harmony, energy, clarity, and limited studio moves.',description:'A permission-free local composition game with six commissions, a four-track step sequencer, mode changes, resource tradeoffs, live synthesis, scoring, progression, failure, exact undo, one-use recovery, keyboard and touch controls, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const COMMISSIONS=[
{name:'Dawn Platform',turns:9,target:58,energy:[25,55],clarity:55,tension:[10,45],mode:'warm',brief:'Build a calm departure cue with room to breathe.'},
{name:'Rain Arcade',turns:10,target:64,energy:[35,68],clarity:52,tension:[20,58],mode:'glass',brief:'Layer motion without burying the pulse.'},
{name:'Night Kitchen',turns:10,target:68,energy:[45,74],clarity:48,tension:[28,66],mode:'warm',brief:'Make a playful groove that still leaves conversational space.'},
{name:'Signal Ridge',turns:11,target:73,energy:[55,82],clarity:50,tension:[35,72],mode:'bright',brief:'Create forward momentum with a clean melodic beacon.'},
{name:'Storm Archive',turns:12,target:77,energy:[48,78],clarity:58,tension:[48,82],mode:'glass',brief:'Hold dramatic tension while preserving intelligibility.'},
{name:'Orbital Garden',turns:12,target:82,energy:[60,88],clarity:56,tension:[42,76],mode:'bright',brief:'Finish with a living machine: energetic, balanced, and memorable.'}
];
const TRACKS=[{name:'Pulse',freq:110},{name:'Bass',freq:164.81},{name:'Chime',freq:329.63},{name:'Air',freq:493.88}];
const MODES={warm:[0,2,4,7,9],glass:[0,3,5,7,10],bright:[0,2,5,7,11]};
function style(){if($('#pulse-atelier-style'))return;const e=document.createElement('style');e.id='pulse-atelier-style';e.textContent=`.pulse-atelier{max-width:1120px;display:grid;gap:12px}.pa-hud{display:grid;grid-template-columns:repeat(7,1fr);gap:7px}.pa-stat,.pa-panel{border:1px solid var(--line);border-radius:17px;background:#fff}.pa-stat{padding:9px}.pa-stat span{display:block;font-size:.6rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.pa-layout{display:grid;grid-template-columns:1.1fr .9fr;gap:12px}.pa-panel{padding:14px}.pa-brief{padding:16px;border-radius:17px;background:linear-gradient(135deg,#221637,#59437f);color:#fff}.pa-grid{display:grid;grid-template-columns:72px repeat(8,1fr);gap:5px;margin-top:12px}.pa-label{display:grid;place-items:center;font-size:.72rem;font-weight:900;color:var(--muted)}.pa-step{aspect-ratio:1;border:1px solid var(--line);border-radius:9px;background:#f5f3f8;min-width:32px}.pa-step.on{background:#7d5bb2;border-color:#49316f;box-shadow:inset 0 0 0 2px rgba(255,255,255,.4)}.pa-step.playing{outline:3px solid #e0ad3d;outline-offset:1px}.pa-controls,.pa-actions,.pa-gates{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:10px}.pa-controls button,.pa-actions button{min-height:46px}.pa-actions .primary{background:#eee5fb;border-color:#5c3d86}.pa-gate{padding:8px;border-radius:10px;background:#f1f3f5;font-size:.75rem}.pa-gate.pass{background:#e1f4e9}.pa-meters{display:grid;gap:9px}.pa-meter label{display:flex;justify-content:space-between;font-size:.75rem;font-weight:800}.pa-bar{height:12px;border-radius:999px;background:#ece8f1;overflow:hidden}.pa-bar span{display:block;height:100%;background:linear-gradient(90deg,#5c3d86,#d29a3a);transform-origin:left}.pa-log{min-height:118px}.pa-hint{font-size:.8rem;color:var(--muted)}.pa-mode{display:flex;gap:6px;flex-wrap:wrap}.pa-mode button[aria-pressed=true]{background:#5c3d86;color:#fff}.pa-grid button:focus-visible,.pulse-atelier button:focus-visible{outline:3px solid #5c3d86;outline-offset:2px}@media(max-width:860px){.pa-layout{grid-template-columns:1fr}.pa-hud{grid-template-columns:repeat(4,1fr)}}@media(max-width:560px){.pa-hud{grid-template-columns:repeat(2,1fr)}.pa-grid{grid-template-columns:58px repeat(8,minmax(30px,1fr));gap:3px;overflow-x:auto}.pa-controls,.pa-actions,.pa-gates{grid-template-columns:1fr}.pa-step{min-width:30px}}@media(prefers-reduced-motion:reduce){.pulse-atelier *{animation:none!important;transition:none!important}}`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-pulse-atelier]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true),a=$('.app-card',f);a.dataset.pulseAtelier='1';a.dataset.category=APP.category;$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;$('.app-card-button',f).addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-pulse-atelier]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.paBound)return;b.dataset.paBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · local audio strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel pulse-atelier';root.innerHTML=`<div class="pa-hud">${['Commission','Moves','Energy','Clarity','Tension','Score','Streak'].map((x,i)=>`<div class="pa-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="pa-layout"><section class="pa-panel"><div class="pa-brief"><p class="app-meta" data-case></p><h3>Compose to the brief before studio moves run out.</h3><p data-brief></p></div><div class="pa-grid" data-grid aria-label="Four track, eight step sequencer"></div><p class="pa-hint">Tap steps or use arrows to move. Space toggles, P plays, U undoes, Enter submits.</p></section><aside class="pa-panel"><div class="pa-meters" data-meters></div><div class="pa-mode" data-modes aria-label="Harmonic mode"></div><div class="pa-controls"><button data-a="rotate">Rotate selected track</button><button data-a="thin">Thin arrangement</button><button data-a="accent">Accent downbeat</button><button data-a="swap">Swap two tracks</button></div><div class="result-card pa-log" aria-live="polite"></div><div class="pa-gates" data-gates></div><div class="pa-actions"><button data-a="play">Play loop</button><button data-a="undo">Undo move</button><button data-a="recover">Call studio reset</button><button class="primary" data-a="submit">Submit commission</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
let st,ended=false,failed=false,timer=null,audio=null,keyHandler,closeHandler,clickHandler,step=0;const current=()=>COMMISSIONS[st.case];
function blank(){return TRACKS.map(()=>Array(8).fill(false))}
function seedGrid(){const g=blank();g[0][0]=g[0][4]=true;g[1][0]=g[1][3]=g[1][6]=true;g[2][2]=g[2][6]=true;g[3][1]=g[3][5]=true;return g}
function reset(){st={case:0,moves:0,score:0,streak:0,mode:'warm',grid:seedGrid(),cursor:0,recovery:true,unlock:false,history:[]};ended=false;failed=false;startCase()}
function startCase(){const c=current();st.moves=c.turns;st.mode=c.mode;st.grid=seedGrid();if(st.unlock){st.grid[2][4]=true;st.moves++}st.history=[];failed=false;log(c.name,'Shape the loop, listen, and meet every visible gate.');draw()}
function snapshot(){return JSON.stringify({moves:st.moves,score:st.score,streak:st.streak,mode:st.mode,grid:st.grid,cursor:st.cursor})}
function metrics(){const hits=st.grid.map(r=>r.filter(Boolean).length),total=hits.reduce((a,b)=>a+b,0),pulse=hits[0],bass=hits[1],mel=hits[2]+hits[3],collisions=Array.from({length:8},(_,i)=>st.grid.reduce((n,r)=>n+(r[i]?1:0),0)).filter(n=>n>=3).length,sync=st.grid[0].filter((v,i)=>v&&st.grid[1][i]).length;return{energy:clamp(Math.round(total*4.2+pulse*2),0,100),clarity:clamp(Math.round(92-collisions*14-Math.max(0,total-18)*3+sync*2),0,100),tension:clamp(Math.round(mel*6+collisions*9+(st.mode==='glass'?8:st.mode==='bright'?4:0)),0,100),variety:new Set(st.grid.map(r=>r.join(''))).size}}
function gates(){const c=current(),m=metrics();return[{label:`Quality ≥ ${c.target}`,pass:quality()>=c.target},{label:`Energy ${c.energy[0]}–${c.energy[1]}`,pass:m.energy>=c.energy[0]&&m.energy<=c.energy[1]},{label:`Clarity ≥ ${c.clarity}`,pass:m.clarity>=c.clarity},{label:`Tension ${c.tension[0]}–${c.tension[1]}`,pass:m.tension>=c.tension[0]&&m.tension<=c.tension[1]},{label:'3+ distinct tracks',pass:m.variety>=3}]}
function quality(){const c=current(),m=metrics(),mid=(c.energy[0]+c.energy[1])/2,tmid=(c.tension[0]+c.tension[1])/2;return clamp(Math.round(100-Math.abs(m.energy-mid)*1.2-Math.max(0,c.clarity-m.clarity)*1.5-Math.abs(m.tension-tmid)*.8+(st.mode===c.mode?7:0)),0,100)}
function spend(action){if(ended||failed)return false;if(st.moves<=0){log('No studio moves remain.','Submit, undo, or use the one-use reset.');return false}st.history.push(snapshot());st.moves--;action();draw();return true}
function toggle(i){spend(()=>{const r=Math.floor(i/8),c=i%8;st.grid[r][c]=!st.grid[r][c];st.cursor=i;log('Step changed.',`${TRACKS[r].name}, beat ${c+1}.`)})}
function rotate(){spend(()=>{const r=Math.floor(st.cursor/8),row=st.grid[r];row.unshift(row.pop());log('Track rotated.',`${TRACKS[r].name} shifted one beat.`)})}
function thin(){spend(()=>{let removed=0;for(let c=7;c>=0&&removed<2;c--)for(let r=3;r>=0&&removed<2;r--)if(st.grid[r][c]){st.grid[r][c]=false;removed++}log('Arrangement thinned.',`${removed} late events removed to improve clarity.`)})}
function accent(){spend(()=>{st.grid[0][0]=true;st.grid[1][0]=true;log('Downbeat accented.','Pulse and bass now meet on beat one.')})}
function swap(){spend(()=>{[st.grid[1],st.grid[2]]=[st.grid[2],st.grid[1]];log('Tracks swapped.','Bass and chime patterns exchanged roles.')})}
function setMode(mode){if(mode===st.mode)return;spend(()=>{st.mode=mode;log('Mode changed.',`${mode} harmony selected.`)})}
function undo(){if(!st.history.length||ended||failed)return log('Nothing to undo.','No reversible studio move remains.');Object.assign(st,JSON.parse(st.history.pop()));log('Move reversed.','Pattern, mode, score, streak, moves, and cursor restored.');draw()}
function recover(){if(ended||!st.recovery||(!failed&&st.moves>0))return log('Studio reset unavailable.',!st.recovery?'It is available once per session.':'Use it only after failure or when moves are exhausted.');failed=false;st.recovery=false;st.score=Math.max(0,st.score-250);st.moves+=3;log('Studio reset complete.','Three emergency moves restored at a score cost.');draw()}
function submit(){if(ended||failed)return;const pass=gates().every(x=>x.pass);if(!pass){failed=true;st.streak=0;log('Commission rejected.','Use the studio reset or begin a new session.');draw();return}const q=quality();st.score+=q*10+st.moves*35;st.streak++;if(st.streak>=3)st.unlock=true;if(st.case===COMMISSIONS.length-1){ended=true;stop();log('Season complete.',`All six commissions delivered. Final score ${st.score}.`);draw();return}st.case++;startCase()}
function ensureAudio(){const A=window.AudioContext||window.webkitAudioContext;if(!A)return null;audio||=new A();audio.resume();return audio}
function tone(freq,dur=.12,type='sine',gain=.045){const a=ensureAudio();if(!a)return;const o=a.createOscillator(),g=a.createGain(),now=a.currentTime;o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(gain,now+.01);g.gain.exponentialRampToValueAtTime(.0001,now+dur);o.connect(g).connect(a.destination);o.start(now);o.stop(now+dur+.02)}
function playStep(){const degrees=MODES[st.mode];TRACKS.forEach((t,r)=>{if(!st.grid[r][step])return;const semis=degrees[(step+r)%degrees.length]+(r>1?12:0);tone(t.freq*Math.pow(2,semis/12),r===3?.18:.11,r===0?'square':r===1?'triangle':'sine',r===0?.025:.04)});drawCursor();step=(step+1)%8}
function play(){if(timer){stop();log('Playback stopped.','The pattern is ready for editing.');return}if(!ensureAudio()){log('Audio unavailable.','You can still compose and submit silently.');return}step=0;playStep();timer=setInterval(playStep,260);log('Playback running.','Play uses synthesized local audio only.');draw()}
function stop(){if(timer){clearInterval(timer);timer=null}$$('.pa-step',root).forEach(x=>x.classList.remove('playing'))}
function drawCursor(){$$('.pa-step',root).forEach((x,i)=>x.classList.toggle('playing',Boolean(timer)&&i%8===step))}
function log(a,b){$('.pa-log',root).innerHTML=`<strong>${a}</strong><p>${b}</p>`}
function draw(){const c=current(),m=metrics();$$('[data-h]',root).forEach((x,i)=>x.textContent=[`${st.case+1}/6`,st.moves,m.energy,m.clarity,m.tension,st.score,st.streak][i]);$('[data-case]',root).textContent=c.name;$('[data-brief]',root).textContent=`${c.brief} Preferred mode: ${c.mode}. ${failed?'The take failed: use reset or restart. ':''}${st.unlock?'Master bus unlocked: +1 move and an extra chime at each new commission.':''}`;const grid=$('[data-grid]',root);grid.replaceChildren();TRACKS.forEach((t,r)=>{const l=document.createElement('span');l.className='pa-label';l.textContent=t.name;grid.append(l);for(let c2=0;c2<8;c2++){const i=r*8+c2,b=document.createElement('button');b.type='button';b.className=`pa-step ${st.grid[r][c2]?'on':''}`;b.dataset.step=i;b.setAttribute('aria-label',`${t.name} beat ${c2+1}, ${st.grid[r][c2]?'on':'off'}`);b.setAttribute('aria-pressed',String(st.grid[r][c2]));b.tabIndex=i===st.cursor?0:-1;b.disabled=ended||failed||st.moves<=0;grid.append(b)}});$('[data-meters]',root).innerHTML=[['Energy',m.energy],['Clarity',m.clarity],['Tension',m.tension],['Quality',quality()]].map(([n,v])=>`<div class="pa-meter"><label>${n}<span>${v}</span></label><div class="pa-bar"><span style="transform:scaleX(${v/100})"></span></div></div>`).join('');$('[data-modes]',root).innerHTML=Object.keys(MODES).map(x=>`<button type="button" data-mode="${x}" aria-pressed="${x===st.mode}" ${ended||failed||st.moves<=0?'disabled':''}>${x}</button>`).join('');$('[data-gates]',root).innerHTML=gates().map(g=>`<div class="pa-gate ${g.pass?'pass':''}">${g.pass?'✓':'○'} ${g.label}</div>`).join('');const blocked=ended||failed;$$('[data-a]',root).forEach(b=>{const a=b.dataset.a;b.disabled=a==='restart'?false:a==='recover'?(ended||!st.recovery||(!failed&&st.moves>0)):a==='play'?ended:blocked||(a!=='submit'&&a!=='undo'&&st.moves<=0)});$('[data-a=play]',root).textContent=timer?'Stop loop':'Play loop';drawCursor()}
clickHandler=e=>{const stepButton=e.target.closest('[data-step]');if(stepButton)return toggle(Number(stepButton.dataset.step));const mode=e.target.closest('[data-mode]');if(mode)return setMode(mode.dataset.mode);const a=e.target.closest('[data-a]')?.dataset.a;if(!a)return;({rotate,thin,accent,swap,play,undo,recover,submit,restart:reset})[a]?.()};root.addEventListener('click',clickHandler);
keyHandler=e=>{if(dialog.open===false)return;const interactive=e.target.closest('button,input,select,textarea,a,[contenteditable=true]');if(interactive&&!e.target.classList.contains('pa-step'))return;let next=st.cursor;if(['ArrowRight','ArrowLeft','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();next=clamp(next+(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:e.key==='ArrowDown'?8:-8),0,31);st.cursor=next;draw();$(`[data-step="${next}"]`,root)?.focus()}else if(e.key===' '){e.preventDefault();toggle(st.cursor)}else if(e.key.toLowerCase()==='p'){e.preventDefault();play()}else if(e.key.toLowerCase()==='u'){e.preventDefault();undo()}else if(e.key==='Enter'){e.preventDefault();submit()}};document.addEventListener('keydown',keyHandler);
closeHandler=()=>{stop();root.removeEventListener('click',clickHandler);document.removeEventListener('keydown',keyHandler);dialog.removeEventListener('close',closeHandler);if(audio&&audio.state!=='closed')audio.close()};dialog.addEventListener('close',closeHandler,{once:true});reset()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();