(() => {
  const APP = { name: 'Reed Regatta', emoji: '🛶', category: 'play', version: '1.0.0', summary: 'Steer a tiny boat through gates, currents, cargo choices, and recoverable river trouble.', description: 'A local river-slalom strategy game with lane planning, paddle energy, drift, gates, cargo weight, eddy recovery, adaptive rapids, session-only moon run unlocks, scoring, responsive SVG motion, touch and keyboard controls, reduced-motion behavior, optional audio, and teardown.' };
  const $ = (s, r = document) => r.querySelector(s);
  const $$ = (s, r = document) => Array.from(r.querySelectorAll(s));
  const label = (v) => v === 'play' ? 'Play' : v === 'useful' ? 'Useful' : 'Experiment';
  const modes = { creek:{name:'Creek sprint', legs:5, energy:10, quota:330}, gorge:{name:'Gorge run', legs:6, energy:11, quota:430}, moon:{name:'Moon run', legs:7, energy:12, quota:560} };
  const cargo = [{n:'Medicine',w:1,v:45},{n:'Seeds',w:2,v:60},{n:'Lanterns',w:3,v:80}];
  const lowMotion = () => matchMedia('(prefers-reduced-motion: reduce)').matches;
  function ensureStyles(){ if($('#reed-regatta-styles')) return; const st=document.createElement('style'); st.id='reed-regatta-styles'; st.textContent=`.rr-card{animation:rr-rise .24s ease both}.rr-game{max-width:1120px;gap:14px}.rr-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.rr-stat,.rr-river,.rr-panel,.rr-brief{border:1px solid var(--line);border-radius:18px;background:#fff}.rr-stat{padding:10px 12px}.rr-stat span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.rr-stat strong{display:block;margin-top:4px}.rr-layout{display:grid;grid-template-columns:1.05fr .95fr;gap:12px}.rr-river{padding:12px;background:linear-gradient(180deg,#075985,#0f766e);color:#fff;overflow:hidden}.rr-water{width:100%;min-height:330px}.rr-lane{fill:rgba(255,255,255,.08);stroke:rgba(255,255,255,.18);stroke-width:1}.rr-current{stroke:#bae6fd;stroke-width:4;stroke-linecap:round;opacity:.75}.rr-gate{fill:#fef3c7;stroke:#f59e0b;stroke-width:2}.rr-rock{fill:#475569}.rr-boat{fill:#fde68a;stroke:#78350f;stroke-width:2}.rr-ghost{fill:none;stroke:#fff;stroke-width:2;stroke-dasharray:5 5;opacity:.45}.rr-panel{padding:14px;display:grid;gap:12px}.rr-brief{padding:13px;background:#f8fafc}.rr-brief h3{margin:.2rem 0;font-size:1.12rem}.rr-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.rr-actions button:focus-visible,.rr-laneBtn:focus-visible{outline:4px solid var(--accent);outline-offset:2px}.rr-lanes{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.rr-laneBtn{border:1px solid var(--line);border-radius:14px;background:#fff;padding:9px 8px;font-weight:900}.rr-laneBtn.is-picked{background:#dcfce7}.rr-list{display:grid;gap:7px}.rr-chip{border:1px solid var(--line);border-radius:14px;background:#fff;padding:8px 10px;font-size:.82rem}.rr-chip.is-risk{background:#fee2e2}.rr-chip.is-good{background:#dcfce7}.rr-log{min-height:104px;padding:17px 19px}.rr-pulse{animation:rr-pulse .7s ease both}@media(max-width:860px){.rr-hud{grid-template-columns:repeat(2,1fr)}.rr-layout{grid-template-columns:1fr}.rr-actions{grid-template-columns:1fr 1fr}}@media(max-width:520px){.rr-river,.rr-panel{padding:9px}.rr-water{min-height:260px}.rr-actions,.rr-lanes{grid-template-columns:1fr}.rr-stat{padding:9px}}@media(prefers-reduced-motion:reduce){.rr-card,.rr-pulse{animation:none;transition:none}}@keyframes rr-rise{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}@keyframes rr-pulse{0%{transform:scale(.98)}50%{transform:scale(1.03)}100%{transform:none}}`; document.head.append(st); }
  function addCard(){ const grid=$('#app-grid'), template=$('#app-card-template'); if(!grid||!template||$('[data-reed-regatta-card]')) return; const filter=$('.filter.is-active')?.dataset.filter||'all'; if(filter!=='all'&&filter!==APP.category) return; ensureStyles(); const node=template.content.cloneNode(true); const card=$('.app-card',node); card.dataset.category=APP.category; card.dataset.reedRegattaCard='true'; card.classList.add('rr-card'); $('.app-icon',node).textContent=APP.emoji; $('.app-meta',node).textContent=`${label(APP.category)} · v${APP.version}`; $('.app-name',node).textContent=APP.name; $('.app-summary',node).textContent=APP.summary; const b=$('.app-card-button',node); b.setAttribute('aria-label',`Open ${APP.name}`); b.addEventListener('click',open); grid.append(node); }
  function boot(){ ensureStyles(); let tries=0; const retry=()=>{addCard(); if(!$('[data-reed-regatta-card]')&&tries++<20) setTimeout(retry,120);}; retry(); $$('.filter').forEach(btn=>{ if(btn.dataset.reedRegattaRefresh) return; btn.dataset.reedRegattaRefresh='1'; btn.addEventListener('click',()=>setTimeout(addCard,0)); }); }
  function open(){ const dialog=$('#app-dialog'), stage=$('#app-stage'); if(!dialog||!stage) return; $('#dialog-title').textContent=APP.name; $('#dialog-category').textContent=`${label(APP.category)} · ${APP.emoji}`; $('#dialog-description').textContent=APP.description; $('#dialog-feedback').href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Reed%20Regatta'; stage.replaceChildren(); game(stage,dialog); dialog.showModal(); }
  function game(stage, dialog){ const root=document.createElement('section'); root.className='tool-panel rr-game'; root.tabIndex=0; root.innerHTML=`<div class="rr-hud"><div class="rr-stat"><span>Mode</span><strong id="rr-mode"></strong></div><div class="rr-stat"><span>Leg</span><strong id="rr-leg"></strong></div><div class="rr-stat"><span>Lane</span><strong id="rr-lane"></strong></div><div class="rr-stat"><span>Energy</span><strong id="rr-energy"></strong></div><div class="rr-stat"><span>Hull</span><strong id="rr-hull"></strong></div><div class="rr-stat"><span>Score</span><strong id="rr-score"></strong></div></div><div class="rr-layout"><div class="rr-river"><svg class="rr-water" viewBox="0 0 360 360" role="img" aria-label="River course with boat, gates, rocks, and current arrows"></svg></div><div class="rr-panel"><div class="rr-brief"></div><div class="rr-lanes" aria-label="Choose lane"><button class="rr-laneBtn" data-lane="0">Left bank</button><button class="rr-laneBtn" data-lane="1">Center chute</button><button class="rr-laneBtn" data-lane="2">Right reeds</button></div><div class="rr-list"></div><div class="rr-actions"><button class="button" data-act="paddle">Paddle leg</button><button class="button button-secondary" data-act="eddy">Hold in eddy</button><button class="button button-secondary" data-act="patch">Patch hull</button><button class="button button-secondary" data-act="cargo">Swap cargo</button><button class="button button-secondary" data-act="mode">Change mode</button><button class="button button-secondary" data-act="reset">New river</button><button class="button button-secondary" data-act="sound" aria-pressed="false">Sound off</button></div></div></div><div class="result-card rr-log" aria-live="polite"></div>`; stage.append(root);
    const svg=$('.rr-water',root), brief=$('.rr-brief',root), list=$('.rr-list',root), log=$('.rr-log',root); const st={mode:'creek',leg:1,energy:10,hull:3,score:0,lane:1,cargo:0,sound:false,ac:null,unlocked:false,low:lowMotion(),current:0,gate:1,rock:2,gust:0}; dialog.addEventListener('close',()=>{ if(st.ac) st.ac.close().catch(()=>{}); },{once:true}); const m=()=>modes[st.mode]; const weight=()=>cargo[st.cargo].w; const laneName=i=>['Left bank','Center chute','Right reeds'][i];
    function setupLeg(){ st.current=(st.leg+(st.mode==='moon'?1:0))%3; st.gate=(st.leg*2+(st.mode==='gorge'?1:0))%3; st.rock=(st.leg+1)%3; st.gust=st.mode==='creek'?0:(st.leg%2?1:-1); }
    function note(msg){ log.innerHTML=`<strong>${msg}</strong><small>Keyboard: arrows choose a lane, Enter paddles, E eddy, P patches, C swaps cargo, M changes mode.</small>`; }
    function tone(kind){ if(!st.sound&&kind!=='bad') return; const AE=window.AudioContext||window.webkitAudioContext; if(!AE) return; st.ac ||= new AE(); st.ac.resume(); const o=st.ac.createOscillator(), g=st.ac.createGain(); o.type=kind==='bad'?'sawtooth':'sine'; o.frequency.value=kind==='good'?720:kind==='tick'?420:190; g.gain.setValueAtTime(.0001,st.ac.currentTime); g.gain.exponentialRampToValueAtTime(.055,st.ac.currentTime+.02); g.gain.exponentialRampToValueAtTime(.0001,st.ac.currentTime+.23); o.connect(g).connect(st.ac.destination); o.start(); o.stop(st.ac.currentTime+.25); }
    function reset(next){ const keys=Object.keys(modes); st.mode=next||keys[(keys.indexOf(st.mode)+1)%(st.unlocked?3:2)]; st.leg=1; st.energy=m().energy; st.hull=3; st.score=0; st.lane=1; st.cargo=0; setupLeg(); render(); note(`${m().name} ready. Pick lanes that hit gates, ride currents, avoid rocks, and protect the cargo.`); }
    function outcomeCost(){ return 1+weight()+Math.abs(st.lane-st.current); }
    function paddle(){ if(st.leg>m().legs) return reset(st.mode); const drift=Math.max(0,Math.min(2,st.lane+st.gust)); const hitGate=drift===st.gate, hitRock=drift===st.rock, ride=st.lane===st.current; const cost=outcomeCost(); if(st.energy<cost) return note('Too little energy for that push. Hold in an eddy or switch to lighter cargo.'); st.energy-=cost; let gain=35+cargo[st.cargo].v+(ride?18:0)+(hitGate?36:-18); if(hitRock){ st.hull-=1; gain-=45; tone('bad'); } else tone(hitGate?'good':'tick'); st.score+=Math.max(0,gain); st.leg+=1; if(st.leg<=m().legs) setupLeg(); if(st.hull<=0){ st.leg=m().legs+1; note(`Hull cracked on the ${laneName(drift)}. Recover by replaying with eddies and patch timing.`); } else if(st.leg>m().legs) finish(); else note(`${hitGate?'Clean gate.':'Gate missed.'} ${ride?'The current helped.':'The current fought you.'} ${hitRock?'Rock strike damaged the hull.':'Cargo stayed dry.'}`); render(); }
    function eddy(){ if(st.leg>m().legs) return reset(st.mode); st.energy=Math.min(m().energy+2,st.energy+2); st.score=Math.max(0,st.score-12); st.gust=0; tone('tick'); render(); note('Eddy hold restored 2 energy and calmed the next gust, but the clock cost points.'); }
    function patch(){ if(st.hull>=3) return note('Hull is already sound. Save the patch for a rock strike.'); if(st.energy<2) return note('Patching needs 2 energy. Hold in an eddy first.'); st.energy-=2; st.hull+=1; tone('good'); render(); note('Hull patched. You spent energy to preserve the run.'); }
    function swapCargo(){ st.cargo=(st.cargo+1)%cargo.length; tone('tick'); render(); note(`${cargo[st.cargo].n} loaded. Heavier cargo scores more but burns more energy each leg.`); }
    function finish(){ const success=st.score>=m().quota&&st.hull>0; if(success&&!st.unlocked){ st.unlocked=true; note(`River mastered at ${st.score}. Moon run unlocked for this session.`); } else note(success?`Landing reached with ${st.score} points and dry cargo.`:`Landing reached at ${st.score}. Replay with better gate-current timing and lighter cargo.`); render(); }
    function render(){ $('#rr-mode',root).textContent=m().name; $('#rr-leg',root).textContent=`${Math.min(st.leg,m().legs)} / ${m().legs}`; $('#rr-lane',root).textContent=laneName(st.lane); $('#rr-energy',root).textContent=st.energy; $('#rr-hull',root).textContent=st.hull; $('#rr-score',root).textContent=st.score; brief.innerHTML=`<h3>${m().name}</h3><p>Current favors ${laneName(st.current)}. Gate is ${laneName(st.gate)}. Rock hazard near ${laneName(st.rock)}. Gust drift ${st.gust===0?'none':st.gust>0?'right':'left'}.</p>`; list.innerHTML=`<div class="rr-chip is-good">Cargo: ${cargo[st.cargo].n}, value ${cargo[st.cargo].v}, weight ${weight()}</div><div class="rr-chip ${st.lane===st.current?'is-good':'is-risk'}">Paddle cost now: ${outcomeCost()} energy</div><div class="rr-chip">Plan: choose a lane, then paddle, eddy, patch, or swap cargo.</div>`; $$('.rr-laneBtn',root).forEach(b=>b.classList.toggle('is-picked',Number(b.dataset.lane)===st.lane)); svg.innerHTML=''; [0,1,2].forEach(i=>svg.insertAdjacentHTML('beforeend',`<rect class="rr-lane" x="${20+i*110}" y="20" width="98" height="320" rx="22"/>`)); svg.insertAdjacentHTML('beforeend',`<path class="rr-current" d="M${69+st.current*110} 40 C ${45+st.current*110} 120, ${92+st.current*110} 190, ${69+st.current*110} 312"/><circle class="rr-gate" cx="${69+st.gate*110}" cy="92" r="19"/><circle class="rr-rock" cx="${69+st.rock*110}" cy="235" r="21"/><path class="rr-ghost" d="M${69+st.lane*110} 318 L${69+Math.max(0,Math.min(2,st.lane+st.gust))*110} 90"/><path class="rr-boat" d="M${69+st.lane*110} 294 l22 28 h-44 z"/>`); if(!st.low) root.classList.add('rr-pulse'), setTimeout(()=>root.classList.remove('rr-pulse'),220); }
    root.addEventListener('click',e=>{ const b=e.target.closest('button'); if(!b) return; if(b.dataset.lane!==undefined){ st.lane=Number(b.dataset.lane); render(); return; } const a=b.dataset.act; if(a==='paddle') paddle(); if(a==='eddy') eddy(); if(a==='patch') patch(); if(a==='cargo') swapCargo(); if(a==='mode') reset(); if(a==='reset') reset(st.mode); if(a==='sound'){ st.sound=!st.sound; b.textContent=st.sound?'Sound on':'Sound off'; b.setAttribute('aria-pressed',String(st.sound)); if(st.sound) tone('good'); } });
    root.addEventListener('keydown',e=>{ const k=e.key.toLowerCase(); if(['arrowleft','arrowright'].includes(k)){ e.preventDefault(); st.lane=Math.max(0,Math.min(2,st.lane+(k==='arrowright'?1:-1))); render(); } if(e.key==='Enter') paddle(); if(k==='e') eddy(); if(k==='p') patch(); if(k==='c') swapCargo(); if(k==='m') reset(); });
    reset('creek'); setTimeout(()=>root.focus(),60);
  }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',boot,{once:true}); else boot();
})();