(() => {
'use strict';
const APP={name:'Relevance Lab',emoji:'⌕',category:'play',version:'1.0.0',summary:'Tune a search engine across six query sets while balancing relevance, diversity, freshness, and business pressure.',description:'A local-only search-ranking strategy lab with six scenarios, weighted signals, limited experiments, hidden intent, ranking metrics, progression, failure, recovery, a session unlock, keyboard and touch controls, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const SIGNALS=[
{id:'text',label:'Text match',short:'Text',desc:'Rewards exact and semantic query matches.'},
{id:'quality',label:'Quality',short:'Quality',desc:'Rewards trusted and complete results.'},
{id:'fresh',label:'Freshness',short:'Fresh',desc:'Rewards newer results.'},
{id:'popular',label:'Popularity',short:'Popular',desc:'Rewards frequently chosen results.'},
{id:'margin',label:'Commercial value',short:'Value',desc:'Rewards higher-value results.'},
{id:'diversity',label:'Diversity',short:'Diverse',desc:'Penalizes repetitive result types.'}
];
const SCENARIOS=[
{name:'Query set 1 · Clear intent',query:'red running shoes',target:64,budget:5,focus:['text','quality'],twist:'Exact attributes matter more than raw popularity.'},
{name:'Query set 2 · Exploratory',query:'easy weeknight dinner ideas',target:68,budget:5,focus:['diversity','quality'],twist:'Users need variety, not five versions of the same answer.'},
{name:'Query set 3 · Breaking topic',query:'city rail closure today',target:72,budget:4,focus:['fresh','quality'],twist:'Old but popular results can mislead.'},
{name:'Query set 4 · Ambiguous',query:'jaguar',target:75,budget:4,focus:['diversity','text'],twist:'The audience is split between animal, vehicle, and sports intents.'},
{name:'Query set 5 · Marketplace pressure',query:'best cordless drill',target:78,budget:3,focus:['quality','text'],twist:'Commercial value is tempting, but trust is fragile.'},
{name:'Query set 6 · Long-tail rescue',query:'quiet desk fan for a nursery',target:82,budget:3,focus:['text','quality','diversity'],twist:'Specific needs punish generic popularity.'}
];
const RESULTS=[
{id:'a',title:'Exact guide',type:'guide',text:92,quality:78,fresh:62,popular:70,margin:35,intents:['product','howto']},
{id:'b',title:'Trusted comparison',type:'comparison',text:78,quality:94,fresh:72,popular:82,margin:58,intents:['product','research']},
{id:'c',title:'Trending answer',type:'news',text:66,quality:68,fresh:98,popular:94,margin:20,intents:['news','sports']},
{id:'d',title:'High-value listing',type:'product',text:74,quality:61,fresh:80,popular:76,margin:96,intents:['product','vehicle']},
{id:'e',title:'Specialist resource',type:'guide',text:86,quality:88,fresh:48,popular:42,margin:30,intents:['howto','animal']},
{id:'f',title:'Broad overview',type:'overview',text:58,quality:81,fresh:70,popular:86,margin:44,intents:['research','vehicle','animal']}
];
function style(){if($('#relevance-lab-style'))return;const e=document.createElement('style');e.id='relevance-lab-style';e.textContent=`
.relevance-lab{max-width:1120px;display:grid;gap:12px}.rl-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.rl-stat,.rl-panel{border:1px solid var(--line);border-radius:17px;background:#fff}.rl-stat{padding:9px}.rl-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.rl-layout{display:grid;grid-template-columns:1.08fr .92fr;gap:12px}.rl-panel{padding:15px}.rl-query{padding:16px;border-radius:18px;background:linear-gradient(135deg,#171d38,#5b3f7b);color:#fff}.rl-query code{display:block;margin-top:8px;padding:10px;border-radius:10px;background:#ffffff18;color:#fff;font:700 1rem/1.3 ui-monospace,monospace}.rl-focus{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.rl-chip{padding:5px 8px;border-radius:999px;background:#ffffff20;font-size:.72rem}.rl-signals{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:12px}.rl-signal{border:1px solid var(--line);border-radius:13px;padding:10px}.rl-signal-head{display:flex;justify-content:space-between;gap:8px}.rl-stepper{display:grid;grid-template-columns:42px 1fr 42px;gap:6px;align-items:center;margin-top:8px}.rl-stepper button,.rl-actions button{min-height:42px;border:1px solid var(--line);border-radius:10px;background:#fff;font-weight:900}.rl-stepper output{text-align:center;font-weight:900}.rl-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.rl-actions .primary{background:#f0eafa;border-color:#5b3f7b}.rl-stepper button:focus-visible,.rl-actions button:focus-visible{outline:3px solid #5b3f7b;outline-offset:2px}.rl-ranking{display:grid;gap:7px;margin:10px 0}.rl-result{display:grid;grid-template-columns:28px 1fr auto;gap:8px;align-items:center;border:1px solid var(--line);border-radius:12px;padding:9px}.rl-result small{display:block;color:var(--muted)}.rl-meter{height:10px;background:#ece9f2;border-radius:99px;overflow:hidden}.rl-meter span{display:block;height:100%;background:#5b3f7b;transition:width .25s}.rl-row{display:flex;justify-content:space-between;gap:10px}.rl-log{min-height:104px}.rl-hint{font-size:.82rem;color:var(--muted)}.rl-good{color:#1d6f4b}.rl-bad{color:#9f3e24}
@media(max-width:840px){.rl-layout{grid-template-columns:1fr}.rl-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.rl-hud{grid-template-columns:repeat(2,1fr)}.rl-signals,.rl-actions{grid-template-columns:1fr}.rl-stepper{grid-template-columns:48px 1fr 48px}}@media(prefers-reduced-motion:reduce){.relevance-lab *{animation:none!important;transition:none!important}}
`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-relevance-lab]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true),a=$('.app-card',f);a.dataset.relevanceLab='1';a.dataset.category=APP.category;$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-relevance-lab]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.rlBound)return;b.dataset.rlBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · search strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
 const root=document.createElement('section');root.className='tool-panel relevance-lab';root.innerHTML=`<div class="rl-hud">${['Set','Experiments','Trust','Best score','Streak','Total'].map((x,i)=>`<div class="rl-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="rl-layout"><section class="rl-panel"><div class="rl-query"><p class="app-meta" data-set></p><h3 data-title></h3><code data-query></code><p data-twist></p><div class="rl-focus" data-focus></div></div><div class="rl-signals" data-signals></div><p class="rl-hint">Tune weights, run limited experiments, then ship. Keyboard: 1-6 select signal, ↑/↓ adjust, E experiment, Enter ship.</p></section><aside class="rl-panel"><div class="result-card rl-log" aria-live="polite"></div><h3>Current ranking</h3><div class="rl-ranking" data-ranking></div><div class="rl-row"><span>Relevance</span><strong data-rel></strong></div><div class="rl-row"><span>Diversity</span><strong data-div></strong></div><div class="rl-row"><span>Freshness</span><strong data-fresh></strong></div><div class="rl-row"><span>Commercial pressure</span><strong data-bias></strong></div><p><strong>Composite quality</strong></p><div class="rl-meter"><span data-meter></span></div><div class="rl-actions"><button class="primary" data-a="ship">Ship ranking</button><button data-a="experiment">Run experiment</button><button data-a="undo">Undo weight</button><button data-a="recover">Rollback release</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
 let st,ended=false,keyHandler,closeHandler;
 const baseWeights=()=>({text:5,quality:5,fresh:3,popular:3,margin:1,diversity:2});
 function reset(){st={level:0,experiments:SCENARIOS[0].budget,trust:70,best:0,streak:0,total:0,weights:baseWeights(),selected:0,history:[],rollback:true,unlock:false,observed:false};ended=false;log('Lab opened.','Tune the ranking before spending your experiment budget.');draw()}
 function current(){return SCENARIOS[st.level]}
 function scoreResult(r){let v=r.text*st.weights.text+r.quality*st.weights.quality+r.fresh*st.weights.fresh+r.popular*st.weights.popular+r.margin*st.weights.margin;return v}
 function ranking(){const sorted=RESULTS.map(r=>({...r,raw:scoreResult(r)})).sort((a,b)=>b.raw-a.raw);if(st.weights.diversity){for(let i=1;i<sorted.length;i++)if(sorted[i].type===sorted[i-1].type)sorted[i].raw-=st.weights.diversity*22;sorted.sort((a,b)=>b.raw-a.raw)}return sorted}
 function metrics(){const s=current(),rank=ranking(),top=rank.slice(0,4);let rel=0,fresh=0,bias=0;top.forEach((r,i)=>{const discount=1/(i+1);rel+=(r.text*.55+r.quality*.45)*discount;fresh+=r.fresh*discount;bias+=r.margin*discount});rel/=2.08;fresh/=2.08;bias/=2.08;const types=new Set(top.map(r=>r.type)).size;let diversity=types/4*100;const focusBoost=s.focus.reduce((sum,id)=>sum+st.weights[id]*2.1,0);const overfit=Math.max(0,Math.max(...Object.values(st.weights))-8)*5;const commercialPenalty=Math.max(0,bias-62)*.55;let composite=rel*.5+diversity*.2+fresh*.15+focusBoost*.15-commercialPenalty-overfit;if(s.name.includes('Ambiguous'))composite+=diversity*.1;if(s.name.includes('Breaking'))composite+=fresh*.12;if(s.name.includes('Marketplace'))composite-=Math.max(0,st.weights.margin-3)*4;return{rel:clamp(rel,0,100),diversity:clamp(diversity,0,100),fresh:clamp(fresh,0,100),bias:clamp(bias,0,100),composite:clamp(composite,0,100),rank}}
 function adjust(delta){if(ended)return;const id=SIGNALS[st.selected].id,n=clamp(st.weights[id]+delta,0,10);if(n===st.weights[id])return;st.history.push({id,value:st.weights[id]});st.weights[id]=n;st.observed=false;draw()}
 function undo(){if(ended||!st.history.length)return log('Nothing to undo.','No weight change is available.');const h=st.history.pop();st.weights[h.id]=h.value;st.observed=false;log('Weight restored.','The previous tuning change was reversed.');draw()}
 function experiment(){if(ended||st.experiments<=0)return log('Experiment budget spent.','Ship the current ranking or use rollback after a failed release.');st.experiments--;st.observed=true;const m=metrics();const hint=current().focus.map(id=>SIGNALS.find(s=>s.id===id).label).join(' and ');log(`Experiment score: ${Math.round(m.composite)}.`,`Strongest opportunity: ${hint}. Commercial pressure is ${Math.round(m.bias)}.`);draw()}
 function ship(){if(ended)return;const m=metrics(),s=current(),success=m.composite>=s.target&&m.rel>=55&&m.diversity>=50;st.best=Math.max(st.best,Math.round(m.composite));if(success){st.streak++;st.trust=clamp(st.trust+7+(st.observed?2:0),0,100);st.total+=Math.round(m.composite*12+st.experiments*30);if(st.total>=2600)st.unlock=true;if(st.level===SCENARIOS.length-1)return finish(true,`Six query sets shipped. Final score ${st.total}.`);st.level++;st.experiments=current().budget+(st.unlock?1:0);st.weights=baseWeights();st.history=[];st.observed=false;log('Release accepted.',`Quality ${Math.round(m.composite)} cleared the target. The next query set is harder.`);draw();return}st.streak=0;st.trust=clamp(st.trust-13,0,100);st.total=Math.max(0,st.total-180);log('Search quality regressed.',`Needed ${s.target}; achieved ${Math.round(m.composite)}. Trust fell.`);if(st.trust<=18)return finish(false,'Repeated ranking regressions ended the program.');draw()}
 function recover(){if(ended||!st.rollback)return log('Rollback unavailable.','The one session rollback has already been used.');st.rollback=false;st.total=Math.max(0,st.total-260);st.trust=clamp(st.trust-6,0,100);st.experiments+=2;st.weights=baseWeights();st.history=[];st.observed=false;log('Previous ranking restored.','Two experiments returned, but score and trust consequences remain.');draw()}
 function finish(win,msg){ended=true;log(win?'Search program completed.':'Program halted.',msg);draw()}
 function log(a,b){$('.rl-log',root).innerHTML=`<strong>${a}</strong><p>${b}</p>`}
 function draw(){const s=current(),m=metrics();$$('[data-h]',root).forEach((e,i)=>e.textContent=[`${st.level+1}/6`,st.experiments,Math.round(st.trust),st.best,st.streak,st.total][i]);$('[data-set]',root).textContent=s.name;$('[data-title]',root).textContent='Tune before you ship';$('[data-query]',root).textContent=s.query;$('[data-twist]',root).textContent=s.twist;$('[data-focus]',root).innerHTML=s.focus.map(id=>`<span class="rl-chip">Watch: ${SIGNALS.find(x=>x.id===id).label}</span>`).join('')+(st.unlock?'<span class="rl-chip">Unlocked: extra experiment</span>':'');$('[data-signals]',root).innerHTML=SIGNALS.map((x,i)=>`<div class="rl-signal"><div class="rl-signal-head"><strong>${i+1}. ${x.label}</strong><small>${x.desc}</small></div><div class="rl-stepper"><button type="button" data-step="-1" data-i="${i}" aria-label="Decrease ${x.label}">−</button><output>${st.weights[x.id]}</output><button type="button" data-step="1" data-i="${i}" aria-label="Increase ${x.label}">+</button></div></div>`).join('');$('[data-ranking]',root).innerHTML=m.rank.slice(0,4).map((r,i)=>`<div class="rl-result"><strong>${i+1}</strong><span>${r.title}<small>${r.type}</small></span><strong>${Math.round(r.raw/10)}</strong></div>`).join('');$('[data-rel]',root).textContent=Math.round(m.rel);$('[data-div]',root).textContent=Math.round(m.diversity);$('[data-fresh]',root).textContent=Math.round(m.fresh);$('[data-bias]',root).textContent=Math.round(m.bias);$('[data-meter]',root).style.width=`${m.composite}%`;$$('[data-step]',root).forEach(b=>b.addEventListener('click',()=>{st.selected=+b.dataset.i;adjust(+b.dataset.step)}));$$('[data-a]',root).forEach(b=>b.disabled=ended&&b.dataset.a!=='restart')}
 function action(a){({ship,experiment,undo,recover,restart:reset}[a]||(()=>{}))()}
 root.addEventListener('click',e=>{const b=e.target.closest('[data-a]');if(b)action(b.dataset.a)});
 keyHandler=e=>{if(!dialog.open)return;if(/^[1-6]$/.test(e.key)){st.selected=+e.key-1;draw()}else if(e.key==='ArrowUp'){e.preventDefault();adjust(1)}else if(e.key==='ArrowDown'){e.preventDefault();adjust(-1)}else if(e.key.toLowerCase()==='e')experiment();else if(e.key==='Enter')ship()};document.addEventListener('keydown',keyHandler);
 closeHandler=()=>document.removeEventListener('keydown',keyHandler);dialog.addEventListener('close',closeHandler,{once:true});reset()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();