(() => {
  const APP = { name:'Relic Sorter', emoji:'🏺', category:'play', version:'1.0.0', summary:'Arrange fragile exhibits across climate, security, and visitor-flow constraints before opening night.', description:'A local spatial planning mini-game with rotating exhibit sets, climate and security matches, visitor-route pressure, adjacency risks, budgeted moves, session-only hard-mode unlocks, scoring, responsive SVG rendering, touch and keyboard controls, reduced-motion behavior, optional local audio, and clean teardown.' };
  const RELICS = [
    {name:'Amber moth', climate:'dry', security:'low', tags:['quiet']}, {name:'Moon astrolabe', climate:'cool', security:'high', tags:['star']},
    {name:'Painted mask', climate:'warm', security:'mid', tags:['crowd']}, {name:'Glass compass', climate:'cool', security:'high', tags:['fragile']},
    {name:'Desert scroll', climate:'dry', security:'mid', tags:['quiet']}, {name:'Festival drum', climate:'warm', security:'low', tags:['crowd']},
    {name:'Silver beetle', climate:'dry', security:'high', tags:['small']}, {name:'Orchard idol', climate:'warm', security:'mid', tags:['heavy']},
    {name:'Frost cameo', climate:'cool', security:'mid', tags:['fragile']}, {name:'Sun tile', climate:'dry', security:'low', tags:['bright']}
  ];
  const LAYOUTS = [
    {name:'Opening night', path:[0,1,2,7,12,17,18,19], cells:['dry','dry','cool','cool','warm','dry','warm','cool','cool','dry','warm','warm','dry','cool','warm','dry','warm','cool','cool','warm'], sec:['low','mid','high','mid','low','low','high','mid','high','low','mid','low','mid','high','mid','low','mid','high','mid','low']},
    {name:'School rush', path:[15,10,5,6,7,8,13,18,19], cells:['warm','warm','dry','cool','cool','warm','dry','dry','cool','warm','warm','cool','dry','cool','dry','warm','cool','dry','cool','warm'], sec:['low','low','mid','high','mid','low','mid','high','high','low','mid','mid','low','high','mid','low','mid','low','high','mid']},
    {name:'Donor preview', path:[4,3,8,13,12,11,16,17,18], cells:['cool','dry','dry','warm','warm','cool','cool','dry','warm','warm','dry','cool','cool','warm','dry','dry','cool','warm','warm','dry'], sec:['high','mid','low','mid','high','high','mid','low','mid','high','mid','low','high','mid','low','low','mid','high','mid','low']}
  ];
  function installStyles(){ if(document.querySelector('#relic-sorter-styles')) return; const s=document.createElement('style'); s.id='relic-sorter-styles'; s.textContent=`.relic-sorter-card{animation:relic-pop .3s ease both}.relic-sorter{max-width:1080px;gap:14px}.relic-hud{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.relic-stat{border:1px solid var(--line);border-radius:15px;background:white;padding:10px 12px}.relic-stat span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.relic-stat strong{display:block;margin-top:4px;font-size:.96rem}.relic-board{border:0;border-radius:26px;background:#121827;color:white;padding:0;overflow:hidden;box-shadow:inset 0 0 0 1px rgba(255,255,255,.14);touch-action:manipulation}.relic-board:focus-visible{outline:4px solid var(--accent);outline-offset:4px}.relic-board svg{display:block;width:100%;min-height:430px}.relic-cell,.relic-chip{cursor:pointer}.relic-panel{display:grid;grid-template-columns:1.1fr .9fr;gap:10px}.relic-tray,.relic-brief{border:1px solid var(--line);border-radius:18px;background:white;padding:13px}.relic-list{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:9px}.relic-pick{border:1px solid var(--line);border-radius:14px;background:white;color:var(--ink);padding:9px;font-weight:900;text-align:left}.relic-pick[aria-pressed=true]{outline:3px solid var(--accent)}.relic-log{min-height:104px;padding:17px 19px}.relic-tools{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.relic-tools button{border:1px solid var(--line);border-radius:16px;background:white;color:var(--ink);padding:12px 8px;font-weight:900}@media(max-width:760px){.relic-hud{grid-template-columns:repeat(2,1fr)}.relic-panel{grid-template-columns:1fr}.relic-list{grid-template-columns:repeat(2,1fr)}.relic-tools{grid-template-columns:repeat(2,1fr)}.relic-board svg{min-height:360px}}@media(prefers-reduced-motion:reduce){.relic-sorter-card{animation:none}}@keyframes relic-pop{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}}`; document.head.append(s); }
  const labelCategory = v => v==='play'?'Play':v==='useful'?'Useful':'Experiment';
  const filter = () => document.querySelector('.filter.is-active')?.dataset.filter || 'all';
  const eligible = () => filter()==='all' || filter()===APP.category;
  function initCard(){ const grid=document.querySelector('#app-grid'), template=document.querySelector('#app-card-template'); if(!grid||!template||document.querySelector('[data-relic-sorter-card]')||!eligible()) return; installStyles(); const node=template.content.cloneNode(true); const card=node.querySelector('.app-card'); card.dataset.category=APP.category; card.dataset.relicSorterCard='true'; card.classList.add('relic-sorter-card'); node.querySelector('.app-icon').textContent=APP.emoji; node.querySelector('.app-meta').textContent=`${labelCategory(APP.category)} · v${APP.version}`; node.querySelector('.app-name').textContent=APP.name; node.querySelector('.app-summary').textContent=APP.summary; const open=node.querySelector('.app-card-button'); open.setAttribute('aria-label',`Open ${APP.name}`); open.addEventListener('click',openApp); grid.append(node); }
  function wireFilterRefresh(){ document.querySelectorAll('.filter').forEach(b=>{ if(b.dataset.relicSorterRefresh) return; b.dataset.relicSorterRefresh='true'; b.addEventListener('click',()=>setTimeout(initCard,0)); }); }
  function openApp(){ const dialog=document.querySelector('#app-dialog'), stage=document.querySelector('#app-stage'), title=document.querySelector('#dialog-title'), category=document.querySelector('#dialog-category'), description=document.querySelector('#dialog-description'), feedback=document.querySelector('#dialog-feedback'); if(!dialog||!stage||!title||!category||!description||!feedback) return; title.textContent=APP.name; category.textContent=`${labelCategory(APP.category)} · ${APP.emoji}`; description.textContent=APP.description; feedback.href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Relic%20Sorter'; stage.replaceChildren(); renderGame(stage, dialog); dialog.showModal(); }
  function renderGame(stage, dialog){
    const root=document.createElement('section'); root.className='tool-panel relic-sorter';
    const hud=document.createElement('div'); hud.className='relic-hud'; hud.innerHTML='<div class="relic-stat"><span>Scenario</span><strong id="relic-scene">Opening</strong></div><div class="relic-stat"><span>Moves</span><strong id="relic-moves">14</strong></div><div class="relic-stat"><span>Score</span><strong id="relic-score">0</strong></div><div class="relic-stat"><span>Route</span><strong id="relic-route">Open</strong></div><div class="relic-stat"><span>Unlock</span><strong id="relic-unlock">Standard</strong></div>';
    const board=document.createElement('button'); board.type='button'; board.className='relic-board'; board.setAttribute('aria-label','Relic Sorter board. Use arrow keys to move the curator, number keys to choose relics, Enter to place or reclaim, and S to score.'); board.innerHTML='<svg aria-hidden="true"></svg>';
    const panel=document.createElement('div'); panel.className='relic-panel'; panel.innerHTML='<div class="relic-tray"><strong>Relic tray</strong><small>Pick a relic, then choose a room. Matched climate and security score. Crowds, fragile glass, and quiet pieces create adjacency risks.</small><div class="relic-list" id="relic-list"></div></div><div class="relic-brief"><strong>Brief</strong><p id="relic-brief-copy">Place all six relics before opening. Visitor-route rooms score more, but overloaded route cells raise crowd risk.</p></div>';
    const tools=document.createElement('div'); tools.className='relic-tools'; const log=document.createElement('div'); log.className='result-card relic-log'; log.setAttribute('aria-live','polite'); const actions=document.createElement('div'); actions.className='tool-actions'; root.append(hud,board,panel,tools,log,actions); stage.append(root);
    const svg=board.querySelector('svg'), tray=panel.querySelector('#relic-list'), reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    const state={scenario:-1, selectedRelic:0, cursor:0, moves:14, score:0, streak:0, hard:false, placed:Array(20).fill(null), relics:[], audio:false, ctx:null, raf:0, t:0};
    [['Place / reclaim',placeOrReclaim],['Score layout',scoreLayout],['New exhibit',newGame],['Hard mode',toggleHard]].forEach(([txt,fn])=>{const b=document.createElement('button'); b.type='button'; b.textContent=txt; b.addEventListener('click',fn); tools.append(b);});
    const sound=makeButton('Sound off',toggleSound,true); actions.append(sound); dialog.addEventListener('close',teardown,{once:true}); board.addEventListener('click',event=>{ const cell=event.target.closest('[data-cell]'); const relic=event.target.closest('[data-relic]'); if(cell){state.cursor=Number(cell.dataset.cell); placeOrReclaim();} if(relic){state.selectedRelic=Number(relic.dataset.relic); update();}}); board.addEventListener('keydown',onKey);
    function makeButton(text,fn,secondary){const b=document.createElement('button'); b.type='button'; b.className=secondary?'button button-secondary':'button'; b.textContent=text; b.addEventListener('click',fn); return b;}
    function shuffle(a){return [...a].sort(()=>Math.random()-.5);} function scene(){return LAYOUTS[state.scenario%LAYOUTS.length];} function say(html){log.innerHTML=html;} function relicAt(i){return state.placed.findIndex(x=>x===i);} function pulse(kind){ if(!state.audio||!state.ctx) return; const now=state.ctx.currentTime, o=state.ctx.createOscillator(), g=state.ctx.createGain(); o.frequency.value=kind==='good'?740:kind==='bad'?220:480; g.gain.setValueAtTime(.0001,now); g.gain.exponentialRampToValueAtTime(.06,now+.02); g.gain.exponentialRampToValueAtTime(.0001,now+.18); o.connect(g).connect(state.ctx.destination); o.start(now); o.stop(now+.2); }
    function newGame(){ state.scenario=(state.scenario+1)%LAYOUTS.length; state.selectedRelic=0; state.cursor=0; state.moves=state.hard?10:14; state.score=0; state.placed=Array(20).fill(null); state.relics=shuffle(RELICS).slice(0,state.hard?7:6); say(`<strong>${scene().name} is on the loading dock.</strong><small>Match climate and security, protect fragile and quiet pieces, and keep the visitor route interesting without crowding it.</small>`); update(); draw(); }
    function toggleHard(){ state.hard=!state.hard; tools.querySelectorAll('button')[3].textContent=state.hard?'Standard mode':'Hard mode'; newGame(); }
    function toggleSound(){ const AC=window.AudioContext||window.webkitAudioContext; if(!AC){say('<strong>Sound is not available here.</strong><small>The exhibit still works without audio.</small>');return;} state.audio=!state.audio; sound.textContent=state.audio?'Sound on':'Sound off'; sound.setAttribute('aria-pressed',String(state.audio)); if(state.audio){state.ctx ||= new AC(); state.ctx.resume(); pulse('good');} }
    function placeOrReclaim(){ const existing=state.placed[state.cursor]; if(existing!==null){ state.placed[state.cursor]=null; state.moves=Math.max(0,state.moves-1); say(`<strong>${state.relics[existing].name} returned to the tray.</strong><small>Reclaims cost one move but can save a bad opening-night score.</small>`); pulse('bad'); update(); draw(); return; } if(state.moves<=0){say('<strong>No moves left.</strong><small>Score this layout or start a new exhibit.</small>'); return;} if(relicAt(state.selectedRelic)!==-1){say('<strong>That relic is already placed.</strong><small>Pick another tray item or reclaim it from the board.</small>'); return;} state.placed[state.cursor]=state.selectedRelic; state.moves-=1; const r=state.relics[state.selectedRelic]; say(`<strong>${r.name} placed in room ${state.cursor+1}.</strong><small>${roomFit(state.cursor,r)} Score early if the route feels strong, or spend moves to tune adjacencies.</small>`); pulse('good'); update(); draw(); }
    function onKey(e){ const cols=5; if(e.key>='1'&&e.key<='7'){ const n=Number(e.key)-1; if(n<state.relics.length){state.selectedRelic=n; update(); e.preventDefault();} return;} const moves={ArrowLeft:-1,ArrowRight:1,ArrowUp:-cols,ArrowDown:cols}; if(e.key in moves){ state.cursor=(state.cursor+moves[e.key]+20)%20; update(); draw(); e.preventDefault(); } if(e.key==='Enter'||e.key===' '){placeOrReclaim(); e.preventDefault();} if(e.key.toLowerCase()==='s'){scoreLayout(); e.preventDefault();} }
    function roomFit(i,r){ const s=scene(), climate=s.cells[i]===r.climate, sec=s.sec[i]===r.security; return `${climate?'Climate matched':'Climate strain'}, ${sec?'security matched':'security mismatch'}.`; }
    function scoreLayout(){ let total=0, placed=0, risks=0, routeHits=0; const s=scene(); state.placed.forEach((ri,i)=>{ if(ri===null)return; placed++; const r=state.relics[ri]; total+=8; if(s.cells[i]===r.climate) total+=10; else total-=4; if(s.sec[i]===r.security) total+=8; else total-=3; if(s.path.includes(i)){ total+=5; routeHits++; } neighbors(i).forEach(n=>{const oi=state.placed[n]; if(oi===null)return; const o=state.relics[oi]; if((r.tags.includes('fragile')&&o.tags.includes('crowd'))||(r.tags.includes('quiet')&&o.tags.includes('crowd'))){risks++; total-=5;} }); }); total+=Math.max(0,state.moves)*2; if(placed===state.relics.length) total+=15; if(routeHits>=3) total+=10; state.score=Math.max(0,total); state.streak=state.score>=90?state.streak+1:0; if(state.streak>=2&&!state.hard) say(`<strong>${state.score} points. Hard mode is ready.</strong><small>You balanced route appeal with conservation standards across two strong layouts.</small>`); else say(`<strong>${state.score} points.</strong><small>${placed}/${state.relics.length} placed, ${routeHits} route highlights, ${risks} adjacency risks. ${state.score>=90?'Museum board approved.':'Tune climate, security, and crowd pressure before replaying.'}</small>`); pulse(state.score>=90?'good':'bad'); update(); }
    function neighbors(i){ const out=[], x=i%5, y=Math.floor(i/5); [[1,0],[-1,0],[0,1],[0,-1]].forEach(([dx,dy])=>{const nx=x+dx,ny=y+dy;if(nx>=0&&nx<5&&ny>=0&&ny<4)out.push(ny*5+nx);}); return out; }
    function update(){ const s=scene(); hud.querySelector('#relic-scene').textContent=s.name; hud.querySelector('#relic-moves').textContent=String(state.moves); hud.querySelector('#relic-score').textContent=String(state.score); hud.querySelector('#relic-route').textContent=`${state.placed.filter((ri,i)=>ri!==null&&s.path.includes(i)).length} highlights`; hud.querySelector('#relic-unlock').textContent=state.hard?'Hard route':state.streak>=2?'Hard ready':'Standard'; tray.replaceChildren(); state.relics.forEach((r,i)=>{ const b=document.createElement('button'); b.type='button'; b.className='relic-pick'; b.dataset.relic=String(i); b.setAttribute('aria-pressed',String(i===state.selectedRelic)); b.textContent=`${i+1}. ${r.name} · ${r.climate}/${r.security}${relicAt(i)!==-1?' ✓':''}`; b.addEventListener('click',()=>{state.selectedRelic=i; update();}); tray.append(b); }); }
    function draw(){ const s=scene(), w=900,h=560, cw=150,ch=92, ox=70,oy=70; state.t+=1; let html=`<svg viewBox="0 0 ${w} ${h}" role="img"><rect width="${w}" height="${h}" fill="#121827"/><text x="${ox}" y="38" fill="#f8fafc" font-size="24" font-weight="900">${s.name} gallery plan</text>`; for(let y=0;y<4;y++){ for(let x=0;x<5;x++){ const i=y*5+x, climate=s.cells[i], sec=s.sec[i], px=ox+x*cw, py=oy+y*ch, onPath=s.path.includes(i), cur=i===state.cursor; html+=`<g class="relic-cell" data-cell="${i}"><rect x="${px}" y="${py}" width="${cw-10}" height="${ch-10}" rx="16" fill="${climate==='dry'?'#5b3b1f':climate==='cool'?'#183a55':'#513044'}" stroke="${cur?'#facc15':onPath?'#7dd3fc':'rgba(255,255,255,.25)'}" stroke-width="${cur?5:2}"/><text x="${px+12}" y="${py+22}" fill="#dbeafe" font-size="12" font-weight="800">${climate} · ${sec}</text>${onPath?`<circle cx="${px+cw-30}" cy="${py+18}" r="8" fill="#7dd3fc" opacity=".9"/>`:''}</g>`; const ri=state.placed[i]; if(ri!==null){ const r=state.relics[ri], bob=reduced?0:Math.sin((state.t+i)*.08)*2; html+=`<g class="relic-chip" data-relic="${ri}" transform="translate(${px+22} ${py+40+bob})"><rect width="${cw-54}" height="30" rx="12" fill="#fff7ed" stroke="#fed7aa"/><text x="10" y="20" fill="#1f2937" font-size="13" font-weight="900">${r.name}</text></g>`; } } } html+=`<text x="${ox}" y="500" fill="#cbd5e1" font-size="15">Route rooms reward attention. Fragile or quiet relics dislike crowd pieces next door. Number keys choose tray items.</text></svg>`; svg.outerHTML=html; }
    function loop(){ draw(); state.raf=requestAnimationFrame(loop); } function teardown(){ cancelAnimationFrame(state.raf); if(state.ctx&&state.ctx.state!=='closed') state.ctx.close().catch(()=>{}); }
    newGame(); if(!reduced) state.raf=requestAnimationFrame(loop);
  }
  function boot(){ initCard(); wireFilterRefresh(); }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',boot,{once:true}); else boot();
})();
