(() => {
  const APP = { name:'Rover Script', emoji:'🤖', category:'play', version:'1.0.0', summary:'Program a tiny rover with limited commands, solar recharges, samples, hazards, and branching routes.', description:'A local command-sequencing puzzle with programmable rover runs, limited instruction slots, energy, turn planning, samples, solar pads, hazards, adaptive sectors, session-only night-mode unlocks, scoring, responsive canvas rendering, touch, keyboard controls, reduced-motion behavior, optional local audio, and teardown.' };
  const labelCategory = v => v==='play'?'Play':v==='useful'?'Useful':'Experiment';
  const filter = () => document.querySelector('.filter.is-active')?.dataset.filter || 'all';
  const eligible = () => filter()==='all' || filter()===APP.category;
  const commands = [{id:'F',label:'Forward'},{id:'L',label:'Left'},{id:'R',label:'Right'},{id:'S',label:'Sample'},{id:'W',label:'Wait'}];
  const dirs = [[0,-1],[1,0],[0,1],[-1,0]];
  function installStyles(){
    if(document.querySelector('#rover-script-styles')) return;
    const s=document.createElement('style'); s.id='rover-script-styles';
    s.textContent=`.rover-card{animation:rover-rise .3s ease both}.rover-game{max-width:1080px;gap:14px}.rover-hud{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.rover-stat{border:1px solid var(--line);border-radius:15px;background:white;padding:10px 12px}.rover-stat span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.rover-stat strong{display:block;margin-top:4px;font-size:.98rem}.rover-arena{border:0;border-radius:26px;background:#111827;padding:0;overflow:hidden;box-shadow:inset 0 0 0 1px rgba(255,255,255,.14);touch-action:none}.rover-arena:focus-visible{outline:4px solid var(--accent);outline-offset:4px}.rover-arena canvas{display:block;width:100%;height:min(58vh,500px);min-height:370px}.rover-console{display:grid;grid-template-columns:1fr .9fr;gap:10px}.rover-panel,.rover-program{border:1px solid var(--line);border-radius:18px;background:white;padding:13px}.rover-buttons{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.rover-buttons button{border:1px solid var(--line);border-radius:16px;background:white;color:var(--ink);padding:12px 8px;font-weight:900}.rover-code{display:flex;flex-wrap:wrap;gap:6px;margin-top:8px;min-height:34px}.rover-chip{border-radius:999px;border:1px solid var(--line);padding:6px 10px;background:#f8fafc;font-weight:900}.rover-log{min-height:94px;padding:17px 19px}@media(max-width:760px){.rover-hud{grid-template-columns:repeat(2,1fr)}.rover-console{grid-template-columns:1fr}.rover-buttons{grid-template-columns:repeat(2,1fr)}.rover-arena canvas{min-height:330px;height:54vh}}@media(prefers-reduced-motion:reduce){.rover-card{animation:none}.rover-arena canvas{min-height:330px}}@keyframes rover-rise{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}}`;
    document.head.append(s);
  }
  function initCard(){
    const grid=document.querySelector('#app-grid'), template=document.querySelector('#app-card-template');
    if(!grid||!template||document.querySelector('[data-rover-script-card]')||!eligible()) return;
    installStyles();
    const node=template.content.cloneNode(true), card=node.querySelector('.app-card');
    card.dataset.category=APP.category; card.dataset.roverScriptCard='true'; card.classList.add('rover-card');
    node.querySelector('.app-icon').textContent=APP.emoji;
    node.querySelector('.app-meta').textContent=`${labelCategory(APP.category)} · v${APP.version}`;
    node.querySelector('.app-name').textContent=APP.name;
    node.querySelector('.app-summary').textContent=APP.summary;
    const open=node.querySelector('.app-card-button'); open.setAttribute('aria-label',`Open ${APP.name}`); open.addEventListener('click',openApp); grid.append(node);
  }
  function wireFilterRefresh(){ document.querySelectorAll('.filter').forEach(b=>{ if(b.dataset.roverRefresh) return; b.dataset.roverRefresh='true'; b.addEventListener('click',()=>setTimeout(initCard,0)); }); }
  function openApp(){
    const dialog=document.querySelector('#app-dialog'), stage=document.querySelector('#app-stage'), title=document.querySelector('#dialog-title'), category=document.querySelector('#dialog-category'), description=document.querySelector('#dialog-description'), feedback=document.querySelector('#dialog-feedback');
    if(!dialog||!stage||!title||!category||!description||!feedback) return;
    title.textContent=APP.name; category.textContent=`${labelCategory(APP.category)} · ${APP.emoji}`; description.textContent=APP.description;
    feedback.href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Rover%20Script';
    stage.replaceChildren(); renderGame(stage, dialog); dialog.showModal();
  }
  function renderGame(stage, dialog){
    const root=document.createElement('section'); root.className='tool-panel rover-game';
    const hud=document.createElement('div'); hud.className='rover-hud'; hud.innerHTML='<div class="rover-stat"><span>Sector</span><strong id="rover-sector">1 / 5</strong></div><div class="rover-stat"><span>Score</span><strong id="rover-score">0</strong></div><div class="rover-stat"><span>Energy</span><strong id="rover-energy">10</strong></div><div class="rover-stat"><span>Samples</span><strong id="rover-samples">0 / 2</strong></div><div class="rover-stat"><span>Mode</span><strong id="rover-mode">Day</strong></div>';
    const arena=document.createElement('button'); arena.type='button'; arena.className='rover-arena'; arena.setAttribute('aria-label','Rover Script grid. Add commands with F, L, R, S, and W. Backspace removes the last command. Enter runs the program. N starts a new expedition.'); arena.innerHTML='<canvas aria-hidden="true"></canvas>';
    const consoleBox=document.createElement('div'); consoleBox.className='rover-console'; consoleBox.innerHTML='<div class="rover-panel"><strong>Mission rule</strong><p>Write a short command script, collect required samples, then reach the uplink. Solar pads recharge energy. Dust cells cost extra. Rocks block movement. Ice makes the rover slide.</p></div><div class="rover-program"><strong>Program</strong><div class="rover-code" aria-live="polite"></div></div>';
    const buttons=document.createElement('div'); buttons.className='rover-buttons';
    const log=document.createElement('div'); log.className='result-card rover-log'; log.setAttribute('aria-live','polite');
    const foot=document.createElement('div'); foot.className='tool-actions';
    root.append(hud,arena,consoleBox,buttons,log,foot); stage.append(root);
    const canvas=arena.querySelector('canvas'), ctx=canvas.getContext('2d'), codeBox=consoleBox.querySelector('.rover-code'), reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    const state={sector:1,sectors:5,score:0,energy:10,maxEnergy:10,need:2,unlocked:false,night:false,program:[],map:null,pos:null,dir:1,running:false,step:0,last:0,raf:0,audio:false,ac:null,w:900,h:480};
    commands.forEach(c=>{ const b=document.createElement('button'); b.type='button'; b.textContent=c.label; b.addEventListener('click',()=>add(c.id)); buttons.append(b); });
    const runBtn=makeButton('Run script',run,true), undoBtn=makeButton('Undo',undo,true), clearBtn=makeButton('Clear',clear,true), newBtn=makeButton('New expedition',newRun,true), nightBtn=makeButton('Night mode',toggleNight,true), soundBtn=makeButton('Sound off',toggleSound,true);
    foot.append(runBtn,undoBtn,clearBtn,newBtn,nightBtn,soundBtn);
    arena.addEventListener('keydown',onKey); dialog.addEventListener('close',teardown,{once:true});
    function makeButton(text,fn,secondary){ const b=document.createElement('button'); b.type='button'; b.className=secondary?'button button-secondary':'button'; b.textContent=text; b.addEventListener('click',fn); return b; }
    function say(html){ log.innerHTML=html; }
    function beep(kind){ if(!state.audio||!state.ac) return; const now=state.ac.currentTime,o=state.ac.createOscillator(),g=state.ac.createGain(); o.type='triangle'; o.frequency.value=kind==='good'?720:kind==='bad'?180:420; g.gain.setValueAtTime(.0001,now); g.gain.exponentialRampToValueAtTime(.05,now+.02); g.gain.exponentialRampToValueAtTime(.0001,now+.2); o.connect(g).connect(state.ac.destination); o.start(now); o.stop(now+.22); }
    function toggleSound(){ const AC=window.AudioContext||window.webkitAudioContext; if(!AC){say('<strong>Sound is not available here.</strong><small>The rover still runs silently.</small>');return;} state.audio=!state.audio; soundBtn.textContent=state.audio?'Sound on':'Sound off'; soundBtn.setAttribute('aria-pressed',String(state.audio)); if(state.audio){state.ac ||= new AC(); state.ac.resume(); beep('good');} }
    function toggleNight(){ if(!state.unlocked){say('<strong>Night mode is locked.</strong><small>Finish an expedition with 420 points and fewer than three failed scripts to unlock dimmer sectors.</small>');return;} state.night=!state.night; nightBtn.textContent=state.night?'Day mode':'Night mode'; newRun(); }
    function rand(seed){ let x=Math.sin(seed*999)*10000; return x-Math.floor(x); }
    function makeMap(){ const size=6, cells=Array.from({length:size},()=>Array(size).fill('plain')); const seed=state.sector*17+(state.night?91:0)+Math.floor(Math.random()*50); for(let y=0;y<size;y++) for(let x=0;x<size;x++){ const r=rand(seed+x*5+y*11); if((x===0&&y===5)||(x===5&&y===0)) continue; cells[y][x]=r>.88?'rock':r>.74?'dust':r>.63?'ice':r>.55?'solar':'plain'; } cells[5][0]='start'; cells[0][5]='uplink'; let placed=0; while(placed<state.need){ const x=1+Math.floor(rand(seed+placed*31)*4), y=1+Math.floor(rand(seed+placed*43)*4); if(cells[y][x]==='plain'||cells[y][x]==='dust'){cells[y][x]='sample'; placed++;} } return {size,cells,failures:0,collected:new Set()}; }
    function newRun(){ Object.assign(state,{sector:1,score:0,energy:state.night?8:10,maxEnergy:state.night?8:10,need:state.night?3:2,program:[],pos:{x:0,y:5},dir:1,running:false,step:0,last:0}); state.map=makeMap(); say('<strong>Expedition loaded.</strong><small>Program the route before running. Short scripts score better, but solar detours can save a sector.</small>'); renderProgram(); updateHud(); resize(); }
    function add(id){ if(state.running) return; if(state.program.length>=12){say('<strong>Program memory full.</strong><small>Run, undo, or clear before adding another instruction.</small>'); return;} state.program.push(id); renderProgram(); beep('tick'); }
    function undo(){ if(state.running) return; state.program.pop(); renderProgram(); }
    function clear(){ if(state.running) return; state.program=[]; renderProgram(); say('<strong>Program cleared.</strong><small>Try a shorter route with a recharge or wait step.</small>'); }
    function renderProgram(){ codeBox.replaceChildren(); if(!state.program.length){ const span=document.createElement('span'); span.className='rover-chip'; span.textContent='No commands yet'; codeBox.append(span); return; } state.program.forEach((c,i)=>{ const span=document.createElement('span'); span.className='rover-chip'; span.textContent=`${i+1}:${c}`; codeBox.append(span); }); }
    function updateHud(){ hud.querySelector('#rover-sector').textContent=`${state.sector} / ${state.sectors}`; hud.querySelector('#rover-score').textContent=state.score; hud.querySelector('#rover-energy').textContent=state.energy; hud.querySelector('#rover-samples').textContent=`${state.map?.collected.size||0} / ${state.need}`; hud.querySelector('#rover-mode').textContent=state.night?'Night':'Day'; }
    function run(){ if(state.running) return; if(!state.program.length){say('<strong>No program loaded.</strong><small>Add commands first. F moves, L and R turn, S samples, W waits.</small>'); return;} state.running=true; state.step=0; say('<strong>Script running.</strong><small>The rover executes exactly what you wrote. Failure still teaches the next route.</small>'); }
    function finishSector(){ const bonus=Math.max(0,80-state.program.length*3)+state.energy*8; state.score+=100+bonus; beep('good'); if(state.sector>=state.sectors){ state.running=false; if(state.score>=420&&state.map.failures<3) state.unlocked=true; say(`<strong>Expedition complete: ${state.score}.</strong><small>${state.unlocked?'Night mode is unlocked for this session.':'Finish with 420 points and fewer than three failures to unlock night mode.'}</small>`); updateHud(); return; } state.sector++; state.energy=state.maxEnergy; state.program=[]; state.pos={x:0,y:5}; state.dir=1; state.running=false; state.map=makeMap(); say(`<strong>Sector ${state.sector} opened.</strong><small>New terrain, same command memory. Plan before spending energy.</small>`); renderProgram(); updateHud(); }
    function fail(reason){ state.running=false; state.map.failures++; state.energy=Math.max(3,state.maxEnergy-2); state.pos={x:0,y:5}; state.dir=1; beep('bad'); say(`<strong>${reason}</strong><small>Recovered at base with ${state.energy} energy. Revise the script and try the sector again.</small>`); updateHud(); }
    function act(cmd){ let p=state.pos; if(cmd==='L') state.dir=(state.dir+3)%4; if(cmd==='R') state.dir=(state.dir+1)%4; if(cmd==='W') state.energy-=1; if(cmd==='S'){ const key=`${p.x},${p.y}`; if(state.map.cells[p.y][p.x]==='sample'&&!state.map.collected.has(key)){state.map.collected.add(key); state.score+=25; beep('good');} else state.energy-=1; } if(cmd==='F'){ const d=dirs[state.dir], nx=p.x+d[0], ny=p.y+d[1]; if(nx<0||ny<0||nx>=state.map.size||ny>=state.map.size||state.map.cells[ny][nx]==='rock'){ fail('The rover hit a blocked edge.'); return; } p={x:nx,y:ny}; let tile=state.map.cells[p.y][p.x]; state.energy-=tile==='dust'?2:1; if(tile==='solar') state.energy=Math.min(state.maxEnergy,state.energy+4); if(tile==='ice'){ const ix=p.x+d[0], iy=p.y+d[1]; if(ix>=0&&iy>=0&&ix<state.map.size&&iy<state.map.size&&state.map.cells[iy][ix]!=='rock'){p={x:ix,y:iy}; state.energy-=1;} } state.pos=p; }
      if(state.energy<0){ fail('The rover ran out of energy before recovery.'); return; }
      if(state.map.cells[state.pos.y][state.pos.x]==='uplink'&&state.map.collected.size>=state.need){ finishSector(); return; }
      updateHud(); }
    function tick(now){ if(!state.last) state.last=now; const delay=reduced?620:430; resize(); if(state.running&&now-state.last>delay){ state.last=now; if(state.step>=state.program.length){ fail('The script ended before the uplink condition was met.'); } else { act(state.program[state.step++]); } } draw(); state.raf=requestAnimationFrame(tick); }
    function resize(){ const r=canvas.getBoundingClientRect(), dpr=Math.max(1,Math.min(2,window.devicePixelRatio||1)); state.w=Math.max(320,Math.floor(r.width)); state.h=Math.max(320,Math.floor(r.height)); canvas.width=Math.floor(state.w*dpr); canvas.height=Math.floor(state.h*dpr); ctx.setTransform(dpr,0,0,dpr,0,0); }
    function draw(){ const w=state.w,h=state.h,m=24,size=Math.min((w-m*2)/6,(h-m*2)/6), ox=(w-size*6)/2, oy=(h-size*6)/2; ctx.clearRect(0,0,w,h); const bg=ctx.createLinearGradient(0,0,w,h); bg.addColorStop(0,state.night?'#0f172a':'#172554'); bg.addColorStop(1,state.night?'#111827':'#3b2f17'); ctx.fillStyle=bg; ctx.fillRect(0,0,w,h); if(!state.map) return; for(let y=0;y<6;y++) for(let x=0;x<6;x++){ const tile=state.map.cells[y][x], px=ox+x*size, py=oy+y*size; ctx.fillStyle=tile==='rock'?'#334155':tile==='dust'?'#b45309':tile==='ice'?'#7dd3fc':tile==='solar'?'#fde68a':tile==='sample'?'#86efac':tile==='uplink'?'#c4b5fd':'#e5e7eb'; ctx.globalAlpha=state.night&&tile==='plain'?.72:1; ctx.beginPath(); ctx.roundRect(px+3,py+3,size-6,size-6,12); ctx.fill(); ctx.globalAlpha=1; ctx.fillStyle='#0f172a'; ctx.font=`900 ${Math.max(12,size*.16)}px system-ui`; ctx.textAlign='center'; const mark={rock:'■',dust:'dust',ice:'ice',solar:'sun',sample:'sample',uplink:'uplink',start:'base'}[tile]||''; if(mark) ctx.fillText(mark,px+size/2,py+size*.58); }
      ctx.save(); ctx.translate(ox+(state.pos.x+.5)*size,oy+(state.pos.y+.5)*size); ctx.rotate(state.dir*Math.PI/2); ctx.fillStyle='#f8fafc'; ctx.beginPath(); ctx.moveTo(0,-size*.28); ctx.lineTo(size*.24,size*.22); ctx.lineTo(-size*.24,size*.22); ctx.closePath(); ctx.fill(); ctx.strokeStyle='#0f172a'; ctx.lineWidth=3; ctx.stroke(); ctx.restore(); }
    function onKey(e){ const k=e.key.toLowerCase(); if(k==='f') add('F'); if(k==='l') add('L'); if(k==='r') add('R'); if(k==='s') add('S'); if(k==='w') add('W'); if(e.key==='Backspace') undo(); if(e.key==='Enter') run(); if(k==='n') newRun(); if(['f','l','r','s','w','n'].includes(k)||e.key==='Enter'||e.key==='Backspace') e.preventDefault(); }
    function teardown(){ cancelAnimationFrame(state.raf); state.running=false; arena.removeEventListener('keydown',onKey); }
    newRun(); state.raf=requestAnimationFrame(tick);
  }
  window.addEventListener('DOMContentLoaded',()=>{ setTimeout(initCard,0); wireFilterRefresh(); });
})();
