(() => {
  const APP={name:'Seismic Survey',emoji:'〽️',category:'experiment',version:'1.0.0',summary:'Triangulate a hidden fault with scarce sensors, noisy readings, probes, and evacuation calls.',description:'A local spatial inference game with sensor placement, noisy distance bands, limited probes, budget, public trust, aftershocks, false echoes, adaptive survey contracts, session-only deep fault unlock, touch and keyboard controls, reduced-motion behavior, optional local audio, and teardown.'};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const label=v=>v==='play'?'Play':v==='useful'?'Useful':'Experiment';
  function styles(){if($('#seismic-survey-styles'))return;const st=document.createElement('style');st.id='seismic-survey-styles';st.textContent=`.ssv-card{animation:ssv-rise .22s ease both}.ssv-game{max-width:1120px;gap:14px}.ssv-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.ssv-stat,.ssv-map,.ssv-panel{border:1px solid var(--line);border-radius:18px;background:#fff}.ssv-stat{padding:10px 12px}.ssv-stat span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.ssv-stat strong{display:block;margin-top:4px}.ssv-layout{display:grid;grid-template-columns:1.1fr .9fr;gap:12px}.ssv-map{padding:12px;background:linear-gradient(135deg,#fef3c7,#fee2e2);touch-action:none}.ssv-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:5px;max-width:560px;margin:auto}.ssv-cell,.ssv-mode button,.ssv-actions button{min-height:54px;border:1px solid #fed7aa;border-radius:14px;background:#fff7ed;font-weight:900;position:relative;display:grid;place-items:center}.ssv-cell:focus-visible,.ssv-mode button:focus-visible,.ssv-actions button:focus-visible{outline:4px solid var(--accent);outline-offset:2px}.ssv-cell.hot{box-shadow:inset 0 0 0 3px #ea580c}.ssv-cell.known{background:#dcfce7}.ssv-cell.risk{background:#fee2e2}.ssv-cell.sensor{background:#e0f2fe}.ssv-cell.echo{background:#f5f3ff}.ssv-pulse{position:absolute;inset:6px;border-radius:999px;border:2px solid rgba(234,88,12,.35);animation:ssv-pulse 1.2s ease-out infinite}.ssv-panel{padding:14px;display:grid;gap:12px}.ssv-mode,.ssv-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.ssv-mode button{background:white}.ssv-mode button.is-active{box-shadow:0 0 0 3px #fdba74 inset}.ssv-readings,.ssv-contract{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.ssv-chip,.ssv-rule{border:1px solid var(--line);border-radius:14px;padding:10px;background:#f8fafc}.ssv-rule.done{background:#dcfce7}.ssv-log{min-height:104px;padding:17px 19px}.ssv-legend{font-size:.88rem;color:var(--muted)}@media(max-width:880px){.ssv-hud{grid-template-columns:repeat(2,1fr)}.ssv-layout{grid-template-columns:1fr}}@media(max-width:520px){.ssv-cell{min-height:42px}.ssv-panel{padding:9px}.ssv-mode,.ssv-actions,.ssv-readings,.ssv-contract{grid-template-columns:1fr 1fr}}@media(prefers-reduced-motion:reduce){.ssv-card,.ssv-pulse{animation:none;transition:none}}@keyframes ssv-rise{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}@keyframes ssv-pulse{from{opacity:.9;transform:scale(.65)}to{opacity:0;transform:scale(1.3)}}`;document.head.append(st);}
  function addCard(){const grid=$('#app-grid'),template=$('#app-card-template');if(!grid||!template||$('[data-seismic-survey-card]'))return;const f=$('.filter.is-active')?.dataset.filter||'all';if(f!=='all'&&f!==APP.category)return;styles();const node=template.content.cloneNode(true),card=$('.app-card',node);card.dataset.category=APP.category;card.dataset.seismicSurveyCard='true';card.classList.add('ssv-card');$('.app-icon',node).textContent=APP.emoji;$('.app-meta',node).textContent=`${label(APP.category)} · v${APP.version}`;$('.app-name',node).textContent=APP.name;$('.app-summary',node).textContent=APP.summary;const b=$('.app-card-button',node);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);grid.append(node);}
  function boot(){styles();let tries=0;const retry=()=>{addCard();if(!$('[data-seismic-survey-card]')&&tries++<20)setTimeout(retry,120)};retry();$$('.filter').forEach(b=>{if(b.dataset.ssvRefresh)return;b.dataset.ssvRefresh='1';b.addEventListener('click',()=>setTimeout(addCard,0));});}
  function open(){const dialog=$('#app-dialog'),stage=$('#app-stage');if(!dialog||!stage)return;$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent=`${label(APP.category)} · ${APP.emoji}`;$('#dialog-description').textContent=APP.description;$('#dialog-feedback').href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Seismic%20Survey';stage.replaceChildren();game(stage,dialog);dialog.showModal();}
  function game(stage,dialog){
    const root=document.createElement('section');root.className='tool-panel ssv-game';root.innerHTML=`<div class="ssv-hud"><div class="ssv-stat"><span>Survey</span><strong id="ssv-mode-name">City grid</strong></div><div class="ssv-stat"><span>Sensors</span><strong id="ssv-sensors">4</strong></div><div class="ssv-stat"><span>Probes</span><strong id="ssv-probes">3</strong></div><div class="ssv-stat"><span>Budget</span><strong id="ssv-budget">12</strong></div><div class="ssv-stat"><span>Trust</span><strong id="ssv-trust">7</strong></div><div class="ssv-stat"><span>Score</span><strong id="ssv-score">0</strong></div></div><div class="ssv-layout"><div class="ssv-map"><div class="ssv-grid" role="grid" aria-label="Seismic survey grid. Place sensors, probe likely cells, then call the evacuation zone."></div></div><div class="ssv-panel"><div class="ssv-mode" aria-label="Survey contracts"></div><div><strong>Sensor readings</strong><div class="ssv-readings"></div></div><div><strong>Contract</strong><div class="ssv-contract"></div></div><p class="ssv-legend">Readings show distance bands to the hidden fault. Aftershocks can add false echoes. Probe before you declare.</p><div class="ssv-actions"><button class="button" data-act="sensor" type="button">Place sensor</button><button class="button" data-act="probe" type="button">Probe cell</button><button class="button" data-act="call" type="button">Call zone</button><button class="button button-secondary" data-act="aftershock" type="button">Aftershock</button><button class="button button-secondary" data-act="reset" type="button">New survey</button><button class="button button-secondary" data-act="sound" type="button" aria-pressed="false">Sound off</button></div></div></div><div class="result-card ssv-log" aria-live="polite"><strong>Place a sensor.</strong><small>Select a grid cell, then spend a sensor to reveal a distance band.</small></div>`;stage.append(root);
    const modes={city:{name:'City grid',sensors:4,probes:3,budget:12,trust:7,noise:1},ridge:{name:'Ridge line',sensors:3,probes:3,budget:10,trust:6,noise:2},deep:{name:'Deep fault',sensors:3,probes:2,budget:9,trust:5,noise:3}};
    const st={mode:'city',unlocked:false,selected:24,fault:0,sensors:[],probes:[],echoes:[],called:null,sensorsLeft:4,probesLeft:3,budget:12,trust:7,score:0,sound:false,ac:null,done:false,low:matchMedia('(prefers-reduced-motion: reduce)').matches};
    const grid=$('.ssv-grid',root),modeBox=$('.ssv-mode',root),readingBox=$('.ssv-readings',root),contract=$('.ssv-contract',root),log=$('.ssv-log',root);
    const mode=()=>modes[st.mode];
    function tone(kind){if(!st.sound)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;st.ac||=new A();st.ac.resume();const o=st.ac.createOscillator(),g=st.ac.createGain();o.type=kind==='bad'?'sawtooth':'sine';o.frequency.value=kind==='win'?880:kind==='ping'?520:190;g.gain.setValueAtTime(.0001,st.ac.currentTime);g.gain.exponentialRampToValueAtTime(.045,st.ac.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,st.ac.currentTime+.18);o.connect(g).connect(st.ac.destination);o.start();o.stop(st.ac.currentTime+.2);}
    function note(m,s='Use readings to narrow the hidden fault before calling the zone.'){log.innerHTML=`<strong>${m}</strong><small>${s}</small>`;}
    function dist(a,b=st.fault){return Math.abs(Math.floor(a/7)-Math.floor(b/7))+Math.abs(a%7-b%7);}
    function band(d){return d<2?'red':d<4?'orange':d<6?'yellow':'blue';}
    function seed(){st.fault=Math.floor(Math.random()*49);st.selected=24;st.sensors=[];st.probes=[];st.echoes=[];st.called=null;st.done=false;st.sensorsLeft=mode().sensors;st.probesLeft=mode().probes;st.budget=mode().budget;st.trust=mode().trust;st.score=0;note('New tremor map.','Place sensors far apart to triangulate the hidden fault.');render();}
    function render(){const found=st.probes.includes(st.fault),safe=st.called!==null&&dist(st.called)<=1;$('#ssv-mode-name',root).textContent=mode().name;$('#ssv-sensors',root).textContent=st.sensorsLeft;$('#ssv-probes',root).textContent=st.probesLeft;$('#ssv-budget',root).textContent=st.budget;$('#ssv-trust',root).textContent=st.trust;$('#ssv-score',root).textContent=st.score;modeBox.innerHTML='';Object.entries(modes).forEach(([id,m])=>{const b=document.createElement('button');b.type='button';b.textContent=m.name;b.className=id===st.mode?'is-active':'';b.disabled=id==='deep'&&!st.unlocked;b.title=b.disabled?'Find one fault to unlock Deep fault this session.':'';b.addEventListener('click',()=>{st.mode=id;seed();});modeBox.append(b);});readingBox.innerHTML='';if(!st.sensors.length)readingBox.innerHTML='<div class="ssv-chip"><strong>No readings</strong>Place a sensor.</div>';st.sensors.slice(-6).forEach((s,i)=>{const e=document.createElement('div');e.className='ssv-chip';e.innerHTML=`<strong>Sensor ${i+1}</strong>${band(s.reading)} band, ${s.reading} steps`;readingBox.append(e);});contract.innerHTML='';[{a:'Triangulate',d:st.sensors.length>=2},{a:'Ground truth',d:found},{a:'Safe call',d:safe}].forEach(g=>{const e=document.createElement('div');e.className=`ssv-rule${g.d?' done':''}`;e.innerHTML=`<strong>${g.d?'Met':'Open'}</strong>${g.a}`;contract.append(e);});grid.innerHTML='';for(let i=0;i<49;i++){const cell=document.createElement('button');cell.type='button';cell.className=`ssv-cell${i===st.selected?' hot':''}${st.sensors.some(s=>s.i===i)?' sensor':''}${st.probes.includes(i)?' known':''}${st.echoes.includes(i)?' echo':''}${st.called===i?' risk':''}`;cell.setAttribute('role','gridcell');const mark=st.sensors.some(s=>s.i===i)?'⌁':st.probes.includes(i)?(i===st.fault?'◆':'·'):st.echoes.includes(i)?'◌':st.called===i?'!':' ';cell.textContent=mark;cell.setAttribute('aria-label',`Cell ${i+1}${i===st.selected?', selected':''}${st.sensors.some(s=>s.i===i)?', sensor placed':''}${st.probes.includes(i)?', probed':''}${st.called===i?', evacuation call':''}`);if(i===st.selected&&!st.low){const p=document.createElement('span');p.className='ssv-pulse';p.setAttribute('aria-hidden','true');cell.append(p);}cell.addEventListener('click',()=>{st.selected=i;render();});grid.append(cell);}if(found)st.unlocked=true;}
    function spend(n){if(st.budget<n){note('Budget exhausted.','Call the best zone or start a new survey.');tone('bad');return false;}st.budget-=n;return true;}
    function placeSensor(){if(st.done)return;if(st.sensorsLeft<=0){note('No sensors left.','Probe or call with the readings you have.');return;}if(!spend(1))return;let reading=dist(st.selected)+Math.floor(Math.random()*mode().noise);st.sensors.push({i:st.selected,reading});st.sensorsLeft--;st.score+=30;note('Sensor placed.',`Reading reports a ${band(reading)} band about ${reading} steps from the fault.`);tone('ping');render();}
    function probe(){if(st.done)return;if(st.probesLeft<=0){note('No probes left.','Call the zone that best matches the bands.');return;}if(st.probes.includes(st.selected)){note('Already probed.','Choose another cell.');return;}if(!spend(2))return;st.probes.push(st.selected);st.probesLeft--;const hit=st.selected===st.fault;st.score+=hit?260:20-Math.min(18,dist(st.selected)*3);st.trust=Math.max(0,st.trust-(hit?0:1));note(hit?'Fault core found.':'Probe missed.',hit?'Now call this cell or an adjacent zone for a clean evacuation.':`Ground sample is ${dist(st.selected)} steps from the core.`);tone(hit?'win':'bad');render();}
    function callZone(){if(st.done)return;if(!spend(1))return;st.called=st.selected;st.done=true;const d=dist(st.selected);if(d<=1){st.score+=420+st.budget*14+st.trust*20;st.unlocked=true;note('Evacuation zone held.',`Called within ${d} step of the core. Deep fault is unlocked this session.`);tone('win');}else{st.trust=Math.max(0,st.trust-3);st.score=Math.max(0,st.score-90);note('Zone missed.',`The fault was ${d} steps away. Try wider sensor spacing next run.`);tone('bad');}render();}
    function aftershock(){if(st.done)return;if(!spend(1))return;const e=Math.max(0,Math.min(48,st.fault+[-8,-6,-1,1,6,8][Math.floor(Math.random()*6)]));st.echoes=[...new Set([e,...st.echoes])].slice(0,4);st.trust=Math.max(0,st.trust-1);st.score+=15;note('Aftershock echo recorded.',`A false or secondary echo appeared near cell ${e+1}. It may help or mislead.`);tone('ping');render();}
    root.addEventListener('click',e=>{const a=e.target.closest('[data-act]')?.dataset.act;if(!a)return;if(a==='sensor')placeSensor();if(a==='probe')probe();if(a==='call')callZone();if(a==='aftershock')aftershock();if(a==='reset')seed();if(a==='sound'){st.sound=!st.sound;e.target.textContent=st.sound?'Sound on':'Sound off';e.target.setAttribute('aria-pressed',String(st.sound));tone('ping');}});
    root.addEventListener('keydown',e=>{const r=Math.floor(st.selected/7),c=st.selected%7;let n=st.selected;if(e.key==='ArrowUp')n=Math.max(0,r-1)*7+c;if(e.key==='ArrowDown')n=Math.min(6,r+1)*7+c;if(e.key==='ArrowLeft')n=r*7+Math.max(0,c-1);if(e.key==='ArrowRight')n=r*7+Math.min(6,c+1);if(n!==st.selected){e.preventDefault();st.selected=n;render();}if(e.key==='Enter'||e.key===' '){e.preventDefault();placeSensor();}});
    const close=()=>{if(st.ac)st.ac.close().catch(()=>{});dialog.removeEventListener('close',close);};dialog.addEventListener('close',close);seed();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();