(() => {
  const APP={name:'Shelter Shift',emoji:'🏠',category:'useful',version:'1.0.0',summary:'Run an accessible emergency shelter through arrivals, incidents, limited space, and recovery.',description:'A local emergency-shelter operations game with household placement, accessibility and privacy needs, pets, power, supplies, staffing, weather incidents, trust, session progression, adaptive modes, touch, pointer and keyboard controls, reduced-motion behavior, no network activity, and complete teardown.'};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const groups=[
    {name:'Nguyen family',icon:'👨‍👩‍👧',size:3,needs:['quiet'],note:'Child is overwhelmed by noise.'},
    {name:'Ms. Rosa',icon:'🦽',size:1,needs:['accessible','power'],note:'Mobility device needs charging.'},
    {name:'Jordan and Pepper',icon:'🐕',size:1,needs:['pet'],note:'Will not separate from service animal.'},
    {name:'Malik',icon:'🧏',size:1,needs:['visual'],note:'Needs visual alerts and clear sight lines.'},
    {name:'Patel household',icon:'👪',size:4,needs:['privacy'],note:'Needs a family-sized space.'},
    {name:'Evelyn',icon:'🧓',size:1,needs:['quiet','accessible'],note:'Fatigued and uses a walker.'},
    {name:'Kai and Mina',icon:'👩‍👧',size:2,needs:['privacy'],note:'Arrived after a difficult evacuation.'}
  ];
  const zones=[
    {id:'hall',name:'Main hall',icon:'🛏️',cap:8,tags:['visual']},
    {id:'quiet',name:'Quiet room',icon:'🤫',cap:3,tags:['quiet','privacy']},
    {id:'access',name:'Accessible wing',icon:'♿',cap:4,tags:['accessible','power','visual']},
    {id:'family',name:'Family room',icon:'🧸',cap:6,tags:['privacy']},
    {id:'pet',name:'Pet-safe annex',icon:'🐾',cap:3,tags:['pet','visual']}
  ];
  const modes={welcome:{name:'Welcome',days:5,staff:9,arrivals:3,target:420},coordinator:{name:'Coordinator',days:6,staff:8,arrivals:4,target:540},surge:{name:'Surge',days:7,staff:7,arrivals:5,target:680,locked:true}};
  function css(){if($('#ss-styles'))return;const s=document.createElement('style');s.id='ss-styles';s.textContent=`
    .ss-card{animation:ss-in .25s ease both}.ss-game{max-width:1180px;gap:12px}.ss-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.ss-stat,.ss-board,.ss-panel,.ss-log{border:1px solid var(--line);border-radius:18px;background:#fff}.ss-stat{padding:9px 11px}.ss-stat span{display:block;color:var(--muted);font-size:.6rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.ss-layout{display:grid;grid-template-columns:1.25fr .75fr;gap:12px}.ss-board{padding:14px;background:linear-gradient(145deg,#eff6ff,#fdf4ff)}.ss-zones{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.ss-zone{min-height:125px;border:2px dashed #94a3b8;border-radius:16px;padding:10px;background:#ffffffc7}.ss-zone.is-selected{outline:3px solid #2563eb}.ss-zone h4{margin:0 0 6px;display:flex;justify-content:space-between;gap:8px}.ss-residents{display:grid;gap:5px}.ss-chip{border:1px solid var(--line);border-radius:10px;padding:6px;background:#fff;font-size:.72rem}.ss-panel{padding:14px;display:grid;gap:10px;align-content:start}.ss-arrivals{display:grid;gap:7px;max-height:255px;overflow:auto}.ss-arrival{width:100%;border:1px solid var(--line);border-radius:13px;background:#fff;padding:9px;text-align:left;display:grid;grid-template-columns:auto 1fr;gap:8px;align-items:center;min-height:52px}.ss-arrival.is-selected{outline:3px solid #2563eb}.ss-arrival small{display:block;color:var(--muted)}.ss-actions,.ss-modes{display:grid;grid-template-columns:1fr 1fr;gap:8px}.ss-panel button{min-height:44px;border:1px solid var(--line);border-radius:14px;background:#fff;font-weight:900}.ss-panel button.is-active{box-shadow:0 0 0 3px #2563eb inset;background:#eff6ff}.ss-panel button[disabled]{opacity:.45}.ss-log{padding:12px;min-height:88px}.ss-log small{display:block;margin-top:5px;color:var(--muted)}.ss-meter{height:11px;border-radius:99px;background:#e2e8f0;overflow:hidden}.ss-meter span{display:block;height:100%;background:linear-gradient(90deg,#f97316,#2563eb);transition:width .25s ease}.ss-help{font-size:.72rem;color:var(--muted)}@media(max-width:900px){.ss-layout{grid-template-columns:1fr}.ss-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:620px){.ss-hud,.ss-zones,.ss-actions,.ss-modes{grid-template-columns:1fr 1fr}.ss-zone{min-height:110px}.ss-panel button{min-height:48px}}@media(prefers-reduced-motion:reduce){.ss-card{animation:none!important}.ss-meter span{transition:none}}@keyframes ss-in{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}`;document.head.append(s)}
  function addCard(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-ss-card]'))return;const f=$('.filter.is-active')?.dataset.filter||'all';if(f!=='all'&&f!==APP.category)return;css();const n=t.content.cloneNode(true),c=$('.app-card',n);c.dataset.category=APP.category;c.dataset.ssCard='true';c.classList.add('ss-card');$('.app-icon',n).textContent=APP.emoji;$('.app-meta',n).textContent=`Useful · v${APP.version}`;$('.app-name',n).textContent=APP.name;$('.app-summary',n).textContent=APP.summary;const b=$('.app-card-button',n);b.setAttribute('aria-label',`Open ${APP.name}`);b.onclick=open;g.append(n)}
  function boot(){css();let tries=0;const r=()=>{addCard();if(!$('[data-ss-card]')&&tries++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.ssRefresh)return;b.dataset.ssRefresh='1';b.addEventListener('click',()=>setTimeout(addCard,0))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');if(!d||!s)return;$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent=`Useful · ${APP.emoji}`;$('#dialog-description').textContent=APP.description;$('#dialog-feedback').href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Shelter%20Shift';s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){
    const root=document.createElement('section');root.className='tool-panel ss-game';root.innerHTML=`<div class="ss-hud"><div class="ss-stat"><span>Shift</span><strong id="ss-day"></strong></div><div class="ss-stat"><span>Staff</span><strong id="ss-staff"></strong></div><div class="ss-stat"><span>Supplies</span><strong id="ss-supplies"></strong></div><div class="ss-stat"><span>Power</span><strong id="ss-power"></strong></div><div class="ss-stat"><span>Trust</span><strong id="ss-trust"></strong></div><div class="ss-stat"><span>Score</span><strong id="ss-score"></strong></div></div><div class="ss-layout"><div class="ss-board"><small id="ss-mode-label"></small><h3>Shelter floor</h3><div class="ss-zones"></div></div><aside class="ss-panel"><div class="ss-modes"></div><div><strong>Capacity pressure</strong><div class="ss-meter"><span></span></div></div><div class="ss-arrivals" aria-label="Arriving households"></div><div class="ss-actions"><button data-act="place">Place household</button><button data-act="support">Add support</button><button data-act="brief">Run safety briefing</button><button data-act="repair">Restore power</button><button data-act="close">End shift</button><button data-act="recover">Call relief staff · 1</button><button data-act="restart">Restart</button><button data-act="help">How to play</button></div><div class="ss-help">Select an arrival and zone. Keyboard: 1–7 arrivals, Q–T zones, P place, S support, B briefing, R repair, Enter ends shift.</div><div class="ss-log result-card" aria-live="polite"></div></aside></div>`;stage.append(root);
    const state={mode:'coordinator',day:1,staff:8,supplies:10,power:84,trust:66,score:0,arrivals:[],placed:[],selectedArrival:null,selectedZone:'hall',briefed:false,relief:1,unlocked:false,ended:false,handler:null};
    const mode=()=>modes[state.mode],rand=a=>a[Math.floor(Math.random()*a.length)],note=(a,b)=>$('.ss-log',root).innerHTML=`<strong>${a}</strong><small>${b}</small>`;
    function newShift(first=false){state.staff=mode().staff;state.briefed=false;state.arrivals=[];const pool=[...groups].sort(()=>Math.random()-.5);for(let i=0;i<mode().arrivals;i++){const g=pool[i%pool.length];state.arrivals.push({...g,uid:`${state.day}-${i}-${Math.random()}`,supported:false})}state.selectedArrival=state.arrivals[0]?.uid||null;if(!first)incident();render()}
    function incident(){const r=Math.random();if(r<.2){state.power=Math.max(30,state.power-22);note('Generator fault.','Power-dependent and visual-alert needs are at risk until repaired.')}else if(r<.38){state.supplies=Math.max(0,state.supplies-3);note('Delivery delayed.','Blankets and hygiene supplies are tighter this shift.')}else if(r<.55){state.staff=Math.max(3,state.staff-2);note('Road closure.','Two volunteers are delayed. Prioritize placements and safety.')}else note('Doors open.','Place arrivals thoughtfully and preserve capacity for complex needs.')}
    const occupancy=id=>state.placed.filter(p=>p.zone===id).reduce((n,p)=>n+p.size,0);
    function selected(){return state.arrivals.find(a=>a.uid===state.selectedArrival)}
    function spend(n){if(state.staff<n){note('Not enough staff.','End the shift or call relief staff.');return false}state.staff-=n;return true}
    function fit(g,z){const space=occupancy(z.id)+g.size<=z.cap,need=g.needs.every(n=>z.tags.includes(n)||n==='visual'&&state.briefed);return {space,need}}
    function place(){const g=selected(),z=zones.find(x=>x.id===state.selectedZone);if(!g||!z||state.ended||!spend(1))return;const f=fit(g,z);if(!f.space){state.trust-=5;note('Zone is full.','No one moved. Choose a zone with enough room.');render();return}state.arrivals=state.arrivals.filter(a=>a.uid!==g.uid);state.placed.push({...g,zone:z.id});if(f.need){state.score+=28+g.size*4;state.trust=Math.min(100,state.trust+5);note('Good placement.',`${g.name} has a space that fits the stated needs.`)}else{state.score+=8;state.trust-=9;note('Placement has barriers.',`${g.name} is sheltered, but one or more stated needs are not met.`)}state.selectedArrival=state.arrivals[0]?.uid||null;render()}
    function support(){const g=selected();if(!g||state.ended||!spend(1))return;if(state.supplies<2){note('Supplies too low.','Reserve remaining stock or end the shift.');return}state.supplies-=2;g.supported=true;state.score+=14;state.trust=Math.min(100,state.trust+4);note('Support kit prepared.','A labeled kit, orientation card, and check-in plan are ready.');render()}
    function brief(){if(state.ended||state.briefed||!spend(2))return;state.briefed=true;state.score+=18;state.trust=Math.min(100,state.trust+6);note('Accessible briefing complete.','Visual boards, plain-language routes, and quiet check-ins are active.');render()}
    function repair(){if(state.ended||state.power>=85||!spend(2))return;if(state.supplies<2){note('No repair supplies.','You need two supply units for the generator.');return}state.supplies-=2;state.power=Math.min(100,state.power+30);state.score+=16;note('Power stabilized.','Charging, lighting, and alert systems are safer.');render()}
    function recover(){if(state.ended||!state.relief)return;state.relief--;state.staff+=3;state.trust=Math.max(0,state.trust-2);note('Relief staff arrived.','You gained three staff actions, with a small coordination cost.');render()}
    function close(){if(state.ended)return;const unplaced=state.arrivals.reduce((n,g)=>n+g.size,0),barriers=state.placed.filter(p=>!fit(p,zones.find(z=>z.id===p.zone)).need).length;state.score-=unplaced*12+barriers*7;state.trust-=unplaced*4+barriers*3;if(state.power<55){state.trust-=7;state.score-=20}state.supplies=Math.min(14,state.supplies+3);state.power=Math.max(25,state.power-5);if(state.day>=mode().days||state.trust<=0){state.ended=true;const won=state.score>=mode().target&&state.trust>35;if(won&&state.mode==='coordinator'){modes.surge.locked=false;state.unlocked=true}note(won?'Shelter held together.':'Shift review needed.',`${state.score} points · ${Math.max(0,state.trust)} trust.${state.unlocked?' Surge mode unlocked for this session.':''}`);render();return}state.day++;newShift()}
    function restart(m=state.mode){Object.assign(state,{mode:m,day:1,staff:modes[m].staff,supplies:10,power:84,trust:66,score:0,arrivals:[],placed:[],selectedArrival:null,selectedZone:'hall',briefed:false,relief:1,ended:false});newShift(true);note('New shelter opened.','Match needs, protect capacity, and keep systems reliable.')}
    function render(){const used=zones.reduce((n,z)=>n+occupancy(z.id),0),cap=zones.reduce((n,z)=>n+z.cap,0);$('#ss-day',root).textContent=`${state.day}/${mode().days}`;$('#ss-staff',root).textContent=state.staff;$('#ss-supplies',root).textContent=state.supplies;$('#ss-power',root).textContent=`${Math.max(0,state.power)}%`;$('#ss-trust',root).textContent=Math.max(0,state.trust);$('#ss-score',root).textContent=state.score;$('#ss-mode-label',root).textContent=`${mode().name} mode · target ${mode().target}`;$('.ss-meter span',root).style.width=`${Math.min(100,used/cap*100)}%`;
      $('.ss-zones',root).innerHTML=zones.map(z=>`<button class="ss-zone ${state.selectedZone===z.id?'is-selected':''}" data-zone="${z.id}" aria-pressed="${state.selectedZone===z.id}"><h4><span>${z.icon} ${z.name}</span><small>${occupancy(z.id)}/${z.cap}</small></h4><div class="ss-residents">${state.placed.filter(p=>p.zone===z.id).map(p=>`<span class="ss-chip">${p.icon} ${p.name}${p.supported?' · kit':''}</span>`).join('')||'<small>Available space</small>'}</div></button>`).join('');
      $('.ss-arrivals',root).innerHTML=state.arrivals.map((g,i)=>`<button class="ss-arrival ${state.selectedArrival===g.uid?'is-selected':''}" data-arrival="${g.uid}" aria-pressed="${state.selectedArrival===g.uid}"><span>${g.icon}</span><span><strong>${g.name} · ${g.size}</strong><small>${g.needs.join(' · ')}${g.supported?' · support ready':''}</small><small>${g.note}</small></span></button>`).join('')||'<p>All current arrivals have been placed.</p>';
      $('.ss-modes',root).innerHTML=Object.entries(modes).map(([id,m])=>`<button data-mode="${id}" class="${state.mode===id?'is-active':''}" ${m.locked?'disabled':''}>${m.name}${m.locked?' · locked':''}</button>`).join('');$$('[data-zone]',root).forEach(b=>b.onclick=()=>{state.selectedZone=b.dataset.zone;render()});$$('[data-arrival]',root).forEach(b=>b.onclick=()=>{state.selectedArrival=b.dataset.arrival;render()});$$('[data-mode]',root).forEach(b=>b.onclick=()=>restart(b.dataset.mode));$$('[data-act]',root).forEach(b=>{b.disabled=state.ended&&!['restart','help'].includes(b.dataset.act)})}
    const acts={place,support,brief,repair,close,recover,restart:()=>restart(),help:()=>note('How to play','Place households where capacity and needs fit. Support kits improve dignity. Briefings make visual communication reliable. Keep power, trust, supplies, and staff above crisis levels.')};root.addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(b)acts[b.dataset.act]?.()});state.handler=e=>{if(dialog.open&&stage.contains(root)){const k=e.key.toLowerCase(),ai='1234567'.indexOf(k),zi='qwert'.indexOf(k);if(ai>=0&&state.arrivals[ai]){state.selectedArrival=state.arrivals[ai].uid;render()}else if(zi>=0&&zones[zi]){state.selectedZone=zones[zi].id;render()}else if(k==='p')place();else if(k==='s')support();else if(k==='b')brief();else if(k==='r')repair();else if(e.key==='Enter'){e.preventDefault();close()}}};document.addEventListener('keydown',state.handler);dialog.addEventListener('close',()=>{document.removeEventListener('keydown',state.handler);root.remove();$('#ss-styles')?.remove()},{once:true});newShift(true);note('Shelter intake begins.','Select an arriving household and a zone, then balance access, privacy, capacity, and resilience.')
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
