(()=>{'use strict';
const APP={name:'Shift Command',emoji:'🗓️',category:'play',version:'1.0.0',summary:'Staff a live operation through skill gaps, fatigue, morale, overtime, and surprise disruptions.',description:'A local operations-planning game with three escalating sites, worker skills and preferences, drag, touch and keyboard assignment, coverage gates, fatigue and morale tradeoffs, timed disruptions, one-use recovery, scoring, session progression, exact undo, reduced motion, optional audio, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const PEOPLE=[
{id:'maya',name:'Maya',icon:'🧭',skills:['lead','service'],pref:'open',stamina:5},{id:'leo',name:'Leo',icon:'🔧',skills:['tech','safety'],pref:'core',stamina:6},{id:'nia',name:'Nia',icon:'📦',skills:['logistics','service'],pref:'close',stamina:5},{id:'omar',name:'Omar',icon:'🛡️',skills:['safety','lead'],pref:'core',stamina:4},{id:'ivy',name:'Ivy',icon:'💻',skills:['tech','logistics'],pref:'open',stamina:5},{id:'sam',name:'Sam',icon:'🤝',skills:['service','safety'],pref:'close',stamina:6}
];
const SCENARIOS=[
{name:'Community hub',budget:5,target:430,slots:[['open','lead'],['open','service'],['core','tech'],['core','safety'],['close','logistics'],['close','service']],event:'Late delivery',eventText:'The closing logistics post now needs safety support too.',eventSlot:4,eventSkill:'safety'},
{name:'Festival control',budget:4,target:500,slots:[['open','safety'],['open','logistics'],['core','lead'],['core','service'],['core','tech'],['close','safety'],['close','service']],event:'Crowd surge',eventText:'Core service also needs a lead-qualified partner.',eventSlot:3,eventSkill:'lead'},
{name:'Transit recovery',budget:3,target:560,slots:[['open','tech'],['open','lead'],['core','safety'],['core','logistics'],['core','service'],['close','tech'],['close','safety'],['close','lead']],event:'System handoff',eventText:'The final lead post now also requires tech coverage.',eventSlot:7,eventSkill:'tech'}
];
function style(){if($('#shift-command-style'))return;const e=document.createElement('style');e.id='shift-command-style';e.textContent=`.shift-command{max-width:1120px;display:grid;gap:12px}.sc-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.sc-stat,.sc-panel{background:#fff;border:1px solid var(--line);border-radius:18px}.sc-stat{padding:10px}.sc-stat span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.sc-layout{display:grid;grid-template-columns:.9fr 1.1fr;gap:12px}.sc-panel{padding:14px}.sc-brief{padding:14px;border-radius:16px;background:linear-gradient(135deg,#183f56,#49612f);color:#fff}.sc-roster,.sc-board,.sc-actions{display:grid;gap:8px;margin-top:10px}.sc-roster{grid-template-columns:repeat(2,1fr)}.sc-worker,.sc-slot{padding:10px;border:1px solid var(--line);border-radius:14px;text-align:left}.sc-worker[aria-pressed=true]{background:#e8f0df;border-color:#49612f}.sc-worker small,.sc-slot small{display:block;color:var(--muted)}.sc-board{grid-template-columns:repeat(2,1fr)}.sc-slot{min-height:108px;background:#faf9f5}.sc-slot.is-covered{border-color:#3f704d;background:#edf7ef}.sc-slot.is-risk{border-color:#a25d32;background:#fff3ea}.sc-slot:focus-visible,.sc-worker:focus-visible,.sc-actions button:focus-visible{outline:3px solid #49612f;outline-offset:2px}.sc-actions{grid-template-columns:repeat(3,1fr)}.sc-chip{display:inline-block;margin:4px 4px 0 0;padding:3px 7px;border-radius:999px;background:#ece8f1;font-size:.7rem}.sc-worker.is-tired{opacity:.72}.sc-log{min-height:92px}.sc-event{margin-top:10px;padding:10px;border-left:4px solid #a25d32;background:#fff6ef;border-radius:10px}.sc-drop{box-shadow:inset 0 0 0 3px #49612f}.map-note{color:var(--muted)}@media(max-width:850px){.sc-layout{grid-template-columns:1fr}.sc-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.sc-hud,.sc-roster,.sc-board,.sc-actions{grid-template-columns:1fr}.sc-slot{min-height:88px}}@media(prefers-reduced-motion:reduce){.shift-command *{animation:none!important;transition:none!important}}`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-shift-command]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true),a=$('.app-card',f);a.dataset.shiftCommand='1';a.dataset.category=APP.category;$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-shift-command]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.scBound)return;b.dataset.scBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · operations strategy';$('#dialog-description').textContent=APP.description;$('#dialog-feedback').href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Shift%20Command';s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel shift-command';root.innerHTML=`<div class="sc-hud">${['Site','Budget','Coverage','Morale','Score','Rank'].map((x,i)=>`<div class="sc-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="sc-layout"><section class="sc-panel"><div class="sc-brief"><p class="app-meta" data-case></p><h3>Build a resilient shift before the event hits.</h3><p data-brief></p></div><h3>Roster</h3><div class="sc-roster" data-roster></div><p class="map-note">Tap or drag a worker, then choose a post. Keyboard: arrows move, Space selects, Enter assigns, U undoes.</p></section><aside class="sc-panel"><h3>Shift board</h3><div class="sc-board" data-board></div><div class="sc-actions"><button data-a="event">Reveal disruption</button><button data-a="undo">Undo</button><button class="button" data-a="run">Run shift</button><button data-a="recover">Call relief crew</button><button data-a="restart">New session</button><button data-a="sound" aria-pressed="false">Sound off</button></div><div class="result-card sc-log" aria-live="polite"></div></aside></div>`;stage.append(root);
let st,selected=null,focusRoster=0,focusSlot=0,ended=false,failed=false,transitioning=false,audio=false,ac,keyHandler,closeHandler,timer=null;const h=$$('[data-h]',root),roster=$('[data-roster]',root),board=$('[data-board]',root),log=$('.sc-log',root);
function fresh(round=0,score=0,recovery=true){const c=SCENARIOS[round];return{round,score,recovery,budget:c.budget,morale:7,event:false,assign:Array(c.slots.length).fill(null),fatigue:Object.fromEntries(PEOPLE.map(p=>[p.id,0])),history:[],rank:score>=1200?'Operations chief':score>=600?'Shift lead':'Coordinator'}}
function start(round=0){clear();st=fresh(round,st?.score||0,st?.recovery??true);selected=null;ended=false;failed=false;draw();say(SCENARIOS[round].name,'Assign each worker carefully. Matching preferences protects morale; overtime costs budget and stamina.')}
function clear(){if(timer!==null){clearTimeout(timer);timer=null}transitioning=false}
function snap(){return JSON.stringify({budget:st.budget,morale:st.morale,event:st.event,assign:st.assign,fatigue:st.fatigue,score:st.score,rank:st.rank})}
function needs(i){const c=SCENARIOS[st.round],base=[c.slots[i][1]];if(st.event&&i===c.eventSlot)base.push(c.eventSkill);return base}
function coverage(){let hit=0,total=0;st.assign.forEach((id,i)=>{const req=needs(i);total+=req.length;if(!id)return;const p=PEOPLE.find(x=>x.id===id);hit+=req.filter(x=>p.skills.includes(x)).length});return{hit,total}}
function assign(workerId,slot){if(ended||failed||transitioning)return;const p=PEOPLE.find(x=>x.id===workerId);if(!p)return;const previous=st.assign[slot];const existing=st.assign.indexOf(workerId);const overtime=existing!==-1&&existing!==slot;if(overtime&&st.budget<1)return say('No overtime budget.',`${p.name} is already assigned. Remove a post or undo.`);st.history.push(snap());if(previous&&previous!==workerId){st.fatigue[previous]=Math.max(0,st.fatigue[previous]-1)}if(existing!==-1&&existing!==slot){st.budget--;st.fatigue[workerId]++;}else if(existing===-1){st.fatigue[workerId]++;}st.assign[slot]=workerId;const shift=SCENARIOS[st.round].slots[slot][0];if(p.pref===shift)st.morale=clamp(st.morale+1,0,10);else if(p.pref!==shift)st.morale=clamp(st.morale-1,0,10);tone('tick');selected=null;draw()}
function remove(slot){if(ended||failed||transitioning||!st.assign[slot])return;st.history.push(snap());const id=st.assign[slot];st.assign[slot]=null;st.fatigue[id]=Math.max(0,st.fatigue[id]-1);draw();say('Post reopened.','The worker is available again. Preference morale is not refunded; undo restores the exact prior plan.')}
function reveal(){if(ended||failed||transitioning)return;if(st.event)return say('Disruption already active.',SCENARIOS[st.round].eventText);st.history.push(snap());st.event=true;st.morale=clamp(st.morale-1,0,10);tone('bad');draw();say(SCENARIOS[st.round].event,SCENARIOS[st.round].eventText)}
function undo(){if(!st.history.length||ended||failed||transitioning)return say('Nothing to undo.','No reversible plan change remains.');Object.assign(st,JSON.parse(st.history.pop()));selected=null;draw();say('Plan restored.','Assignments, budget, fatigue, morale, disruption state, score, and rank were restored exactly.')}
function run(){if(ended||failed||transitioning)return;const cov=coverage(),empty=st.assign.filter(x=>!x).length,over=Object.values(st.fatigue).filter(x=>x>1).length,skillGap=cov.total-cov.hit;const resilience=st.morale*12+cov.hit*28-st.budget*0-over*18-empty*35;const target=SCENARIOS[st.round].target;if(empty===0&&skillGap===0&&st.morale>=4&&resilience>=target){const gain=120+resilience+st.budget*20-over*10;st.score+=gain;st.rank=st.score>=1200?'Operations chief':st.score>=600?'Shift lead':'Coordinator';st.history=[];tone('good');if(st.round===SCENARIOS.length-1){ended=true;draw();say('Network stabilized.',`All three sites cleared. Final score ${st.score}. Flexible staffing unlocked for this session.`)}else{transitioning=true;draw();say('Shift held.',`Coverage ${cov.hit}/${cov.total}, morale ${st.morale}. Score +${gain}. Preparing the next site.`);timer=setTimeout(()=>{timer=null;st.round++;start(st.round)},300)}}else{failed=true;st.score=Math.max(0,st.score-90);st.history=[];tone('bad');draw();say('Shift broke down.',`${empty} empty posts, ${skillGap} uncovered skills, morale ${st.morale}, resilience ${resilience}/${target}. Use relief crew or restart.`)}}
function recover(){if(transitioning)return;if(!failed||!st.recovery)return say('Relief unavailable.',st.recovery?'It becomes available after a failed shift.':'It was already used this session.');st.recovery=false;failed=false;st.score=Math.max(0,st.score-140);st.budget=SCENARIOS[st.round].budget+1;st.morale=5;st.assign=Array(SCENARIOS[st.round].slots.length).fill(null);st.fatigue=Object.fromEntries(PEOPLE.map(p=>[p.id,0]));st.event=true;st.history=[];draw();say('Relief crew arrived.','The failed plan was cleared. You gained one emergency overtime credit, morale reopened at 5, and the disruption remains active. The 140-point penalty is permanent.')}
function tone(k){if(!audio||!ac)return;const o=ac.createOscillator(),g=ac.createGain(),n=ac.currentTime;o.frequency.value=k==='good'?760:k==='bad'?190:430;g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(.05,n+.02);g.gain.exponentialRampToValueAtTime(.0001,n+.18);o.connect(g).connect(ac.destination);o.start(n);o.stop(n+.2)}
function say(a,b){log.innerHTML=`<strong>${a}</strong><small>${b}</small>`}
function draw(){const c=SCENARIOS[st.round],cov=coverage();h[0].textContent=`${st.round+1} / ${SCENARIOS.length}`;h[1].textContent=st.budget;h[2].textContent=`${cov.hit}/${cov.total}`;h[3].textContent=st.morale;h[4].textContent=st.score;h[5].textContent=st.rank;$('[data-case]',root).textContent=`${c.name} · target ${c.target}`;$('[data-brief]',root).textContent=transitioning?'Shift verified. The next site is loading.':st.event?`${c.event}: ${c.eventText}`:'A disruption will add one surprise skill requirement. You may reveal it before running the shift.';roster.replaceChildren(...PEOPLE.map((p,i)=>{const b=document.createElement('button');b.type='button';b.className='sc-worker'+(st.fatigue[p.id]>=p.stamina?' is-tired':'');b.dataset.worker=p.id;b.draggable=!ended&&!failed&&!transitioning;b.setAttribute('aria-pressed',String(selected===p.id));b.innerHTML=`<strong>${p.icon} ${p.name}</strong><small>${p.skills.join(' + ')} · prefers ${p.pref}</small><span class="sc-chip">load ${st.fatigue[p.id]}/${p.stamina}</span>`;b.disabled=ended||failed||transitioning;b.addEventListener('click',()=>{selected=selected===p.id?null:p.id;focusRoster=i;draw()});b.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',p.id));return b}));board.replaceChildren(...c.slots.map((slot,i)=>{const id=st.assign[i],p=PEOPLE.find(x=>x.id===id),req=needs(i),met=p?req.filter(x=>p.skills.includes(x)).length:0,d=document.createElement('button');d.type='button';d.className='sc-slot '+(p&&met===req.length?'is-covered':p?'is-risk':'');d.dataset.slot=i;d.disabled=ended||failed||transitioning;d.innerHTML=`<strong>${slot[0].toUpperCase()} · ${req.join(' + ')}</strong><small>${p?`${p.icon} ${p.name} · ${met}/${req.length} skills covered`:'Unstaffed'}</small>${p?'<span class="sc-chip">Tap to replace · double tap to remove</span>':''}`;d.addEventListener('click',()=>{focusSlot=i;if(selected)assign(selected,i);else if(id){selected=id;draw()}else say('Choose a worker.','Select or drag a roster member into this post.')});d.addEventListener('dblclick',()=>remove(i));d.addEventListener('dragover',e=>{e.preventDefault();d.classList.add('sc-drop')});d.addEventListener('dragleave',()=>d.classList.remove('sc-drop'));d.addEventListener('drop',e=>{e.preventDefault();d.classList.remove('sc-drop');assign(e.dataTransfer.getData('text/plain'),i)});return d}));$$('[data-a]',root).forEach(b=>{const a=b.dataset.a;b.disabled=transitioning||ended||(failed&&!['recover','restart','sound'].includes(a))||(a==='recover'&&(!failed||!st.recovery));if(a==='undo')b.disabled=b.disabled||!st.history.length});}
function click(e){const a=e.target.closest('[data-a]')?.dataset.a;if(!a)return;if(a==='event')reveal();if(a==='undo')undo();if(a==='run')run();if(a==='recover')recover();if(a==='restart'){st=fresh(0,0,true);start(0)}if(a==='sound'){const A=window.AudioContext||window.webkitAudioContext;if(!A)return say('Sound unavailable.','The simulator remains fully playable without audio.');audio=!audio;e.target.textContent=audio?'Sound on':'Sound off';e.target.setAttribute('aria-pressed',String(audio));if(audio){ac||=new A();ac.resume();tone('tick')}}}
keyHandler=e=>{const interactive=e.target.closest('button,input,select,textarea,a');if(interactive&&!e.target.matches('.sc-worker,.sc-slot'))return;if(e.key.toLowerCase()==='u'){e.preventDefault();undo();return}if(e.key==='ArrowDown'||e.key==='ArrowRight'){e.preventDefault();if(e.target.matches('.sc-worker')){focusRoster=(focusRoster+1)%PEOPLE.length;$$('.sc-worker',root)[focusRoster]?.focus()}else{focusSlot=(focusSlot+1)%SCENARIOS[st.round].slots.length;$$('.sc-slot',root)[focusSlot]?.focus()}}if(e.key==='ArrowUp'||e.key==='ArrowLeft'){e.preventDefault();if(e.target.matches('.sc-worker')){focusRoster=(focusRoster-1+PEOPLE.length)%PEOPLE.length;$$('.sc-worker',root)[focusRoster]?.focus()}else{focusSlot=(focusSlot-1+SCENARIOS[st.round].slots.length)%SCENARIOS[st.round].slots.length;$$('.sc-slot',root)[focusSlot]?.focus()}}if(e.key===' '&&e.target.matches('.sc-worker')){e.preventDefault();selected=e.target.dataset.worker;draw();$$('.sc-worker',root)[focusRoster]?.focus()}if(e.key==='Enter'&&e.target.matches('.sc-slot')&&selected){e.preventDefault();assign(selected,+e.target.dataset.slot);$$('.sc-slot',root)[focusSlot]?.focus()}};
closeHandler=()=>{clear();document.removeEventListener('keydown',keyHandler);root.removeEventListener('click',click);if(ac){ac.close();ac=null}dialog.removeEventListener('close',closeHandler)};root.addEventListener('click',click);document.addEventListener('keydown',keyHandler);dialog.addEventListener('close',closeHandler);st=fresh();start(0)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();