(() => {
  'use strict';
  const APP={name:'Snowpack Lab',emoji:'🏔️',category:'play',version:'1.0.0',summary:'Assess layered snow hazards, spend limited field time on tests, and recommend a safe route before weather closes in.',description:'A local-only alpine risk strategy game with six field days, slope selection, layered snow clues, limited tests, weather shifts, route choices, confidence, credibility, scoring, a session unlock, meaningful failure, one costly recovery, touch, keyboard controls, reduced motion, and teardown.'};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const SLOPES=[{name:'North bowl',aspect:'N',angle:38,wind:3,terrain:3},{name:'East glade',aspect:'E',angle:31,wind:1,terrain:1},{name:'South ridge',aspect:'S',angle:27,wind:2,terrain:2},{name:'West couloir',aspect:'W',angle:42,wind:4,terrain:4}];
  const TESTS=[{name:'Hand shear',cost:1,signal:14},{name:'Compression',cost:2,signal:24},{name:'Extended column',cost:3,signal:36},{name:'Rutschblock',cost:4,signal:46}];
  const ROUTES=[{name:'Valley traverse',risk:-18,reward:35},{name:'Glade ascent',risk:-7,reward:60},{name:'Ridge line',risk:2,reward:82},{name:'Direct couloir',risk:18,reward:120}];
  const DAYS=[
    {brief:'Fresh overnight snow follows a calm, cold week.',storm:18,temp:-12,wind:1,sun:0,weak:'surface hoar',aspect:'N',base:42,target:66},
    {brief:'Strong west wind loads lee slopes after light snowfall.',storm:12,temp:-7,wind:4,sun:1,weak:'wind slab',aspect:'E',base:55,target:70},
    {brief:'Rapid warming reaches a previously shaded alpine face.',storm:4,temp:2,wind:1,sun:4,weak:'wet loose',aspect:'S',base:58,target:73},
    {brief:'A buried crust sits beneath two storm layers.',storm:24,temp:-5,wind:2,sun:1,weak:'persistent slab',aspect:'N',base:66,target:77},
    {brief:'Cross-loading and terrain traps complicate a narrow drainage.',storm:16,temp:-9,wind:4,sun:0,weak:'cross-loaded slab',aspect:'W',base:72,target:81},
    {brief:'A mixed warming, wind, and new-snow cycle challenges the final forecast.',storm:28,temp:1,wind:3,sun:3,weak:'deep persistent slab',aspect:'N',base:79,target:85}
  ];
  function style(){if($('#snowpack-lab-style'))return;const e=document.createElement('style');e.id='snowpack-lab-style';e.textContent=`.snowpack-lab{max-width:1120px;display:grid;gap:12px}.sp-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.sp-stat,.sp-card{border:1px solid var(--line);border-radius:17px;background:#fff}.sp-stat{padding:9px}.sp-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.sp-layout{display:grid;grid-template-columns:1.12fr .88fr;gap:12px}.sp-card{padding:15px}.sp-mountain{min-height:365px;border-radius:24px;background:linear-gradient(#bfe3f5 0 43%,#ecf7fb 44%);position:relative;overflow:hidden;padding:16px}.sp-mountain:before{content:'';position:absolute;left:-8%;right:-8%;bottom:-12%;height:72%;background:linear-gradient(145deg,transparent 0 17%,#d8e8ee 18% 48%,#f8fdff 49%);clip-path:polygon(0 100%,18% 35%,34% 66%,55% 8%,75% 62%,100% 28%,100% 100%)}.sp-grid{position:relative;z-index:1;display:grid;grid-template-columns:repeat(2,1fr);gap:10px;align-content:end;min-height:330px}.sp-slope{min-height:112px;border:2px solid rgba(27,78,99,.28);border-radius:15px;background:rgba(255,255,255,.82);padding:10px;text-align:left;font-weight:850;backdrop-filter:blur(3px)}.sp-slope[aria-pressed=true]{border-color:#075985;background:#e0f2fe;box-shadow:0 0 0 4px rgba(14,116,144,.15)}.sp-slope small,.sp-test small{display:block;color:var(--muted);font-weight:650;margin-top:4px}.sp-controls{display:grid;gap:10px}.sp-tests{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.sp-test{min-height:58px;border:1px solid var(--line);border-radius:12px;background:#fff;padding:9px;text-align:left;font-weight:800}.sp-test[aria-pressed=true]{background:#ecfeff;border-color:#0e7490}.sp-layers{display:grid;gap:5px;margin-top:10px}.sp-layer{height:28px;border-radius:8px;border:1px solid rgba(30,64,175,.15);display:flex;align-items:center;padding:0 9px;font-size:.72rem;font-weight:800}.sp-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.sp-actions button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800;padding:9px}.sp-actions .primary{background:#cffafe;border-color:#0e7490}.sp-log{min-height:115px}.sp-hint{font-size:.72rem;color:var(--muted);margin:0}.sp-selects{display:grid;grid-template-columns:1fr 1fr;gap:8px}.sp-selects label{font-size:.78rem;font-weight:800}@media(max-width:820px){.sp-layout{grid-template-columns:1fr}.sp-hud{grid-template-columns:repeat(3,1fr)}.sp-mountain{min-height:325px}.sp-grid{min-height:290px}}@media(max-width:520px){.sp-hud{grid-template-columns:repeat(2,1fr)}.sp-tests,.sp-actions,.sp-selects{grid-template-columns:1fr 1fr}.sp-mountain{padding:10px;min-height:300px}.sp-grid{gap:7px;min-height:275px}.sp-slope{min-height:106px;padding:8px}}@media(prefers-reduced-motion:reduce){.snowpack-lab *{animation:none!important;transition:none!important}}`;document.head.append(e)}
  function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-snowpack-lab]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.snowpackLab='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
  function boot(){style();let n=0;const r=()=>{card();if(!$('[data-snowpack-lab]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.spBound)return;b.dataset.spBound='1';b.addEventListener('click',()=>setTimeout(card))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · alpine risk strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel snowpack-lab';root.innerHTML=`<div class="sp-hud">${['Day','Time','Credibility','Score','Confidence','Unlock'].map((x,i)=>`<div class="sp-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="sp-layout"><section class="sp-card"><div class="sp-mountain" aria-label="Four candidate snow study slopes"><div class="sp-grid"></div></div><div class="sp-layers" aria-label="Observed snow layers"></div><p class="sp-hint">Choose a slope. Arrow keys move between slopes. Tests consume field time and improve confidence, but conditions may shift while you investigate.</p></section><aside class="sp-card sp-controls"><div class="result-card sp-log" aria-live="polite"></div><div><p class="eyebrow">Field tests</p><div class="sp-tests"></div></div><div class="sp-selects"><label>Hazard rating<select data-rating><option>Low</option><option>Moderate</option><option>Considerable</option><option>High</option><option>Extreme</option></select></label><label>Route recommendation<select data-route></select></label></div><div class="sp-actions"><button class="primary" data-a="forecast">Issue forecast</button><button data-a="probe">Quick probe</button><button data-a="recover">Call resupply</button><button data-a="restart">New field week</button></div></aside></div>`;stage.append(root);let st,timer=0,ended=false;
    function reset(){clearTimeout(timer);st={day:0,time:9,cred:74,score:0,confidence:18,unlock:false,recovery:true,slope:0,tests:[],rating:'Low',route:0,shift:0};ended=false;fill();log(DAYS[0].brief,'Select a representative slope, gather evidence, then issue a hazard rating and route recommendation.');draw()}
    function fill(){ $('[data-route]',root).innerHTML=ROUTES.map((x,i)=>`<option value="${i}">${x.name}</option>`).join('')+(st.unlock?'<option value="4">Adaptive traverse</option>':'') }
    function hazard(day,slope){const d=DAYS[day],s=SLOPES[slope];let h=d.base+d.storm*.45+d.wind*s.wind*2+d.sun*Math.max(0,d.temp+2)*1.5+s.terrain*3+st.shift;if(s.aspect===d.aspect)h+=14;if(s.angle>=35)h+=11;if(s.angle<29)h-=13;return clamp(Math.round(h),8,100)}
    function expectedRating(h){return h<30?0:h<47?1:h<68?2:h<84?3:4}
    function doTest(i){if(ended)return;const t=TESTS[i];if(st.time<t.cost)return log('Not enough field time remains.','Issue the forecast or use the one-time resupply.');st.time-=t.cost;if(!st.tests.includes(i))st.tests.push(i);const trueH=hazard(st.day,st.slope);const noise=Math.max(3,22-t.signal/3-st.tests.length*2);st.confidence=clamp(st.confidence+t.signal-Math.abs(SLOPES[st.slope].angle-35),0,100);st.shift+=DAYS[st.day].temp>0?3:DAYS[st.day].wind>2?2:0;const observed=clamp(Math.round(trueH+(Math.random()-.5)*noise),0,100);log(`${t.name}: instability signal ${observed}/100.`,`Evidence points toward ${DAYS[st.day].weak}; confidence is now ${Math.round(st.confidence)}%.`);draw()}
    function probe(){if(ended||st.time<1)return;st.time--;st.confidence=clamp(st.confidence+8,0,100);log('Quick probe finds layer boundaries.','Useful orientation, but it cannot confirm propagation across the slope.');draw()}
    function issue(){if(ended)return;const d=DAYS[st.day],h=hazard(st.day,st.slope),rated=['Low','Moderate','Considerable','High','Extreme'].indexOf(st.rating),truth=expectedRating(h),route=st.route===4?{risk:-12,reward:95}:ROUTES[st.route];let quality=100-Math.abs(rated-truth)*22;quality-=Math.max(0,52-st.confidence)*.55;quality-=Math.max(0,h+route.risk-68)*.9;if(SLOPES[st.slope].aspect!==d.aspect)quality-=9;if(!st.tests.length)quality-=15;quality=clamp(Math.round(quality),0,100);st.score+=quality*18+route.reward*4;st.cred=clamp(st.cred+(quality>=d.target?8:quality<50?-24:-8),0,100);if(st.score>=4300&&!st.unlock){st.unlock=true;fill()}$$('[data-a]',root).forEach(b=>b.disabled=true);timer=setTimeout(()=>{if(!root.isConnected)return;if(st.cred<=0)return finish(false);if(st.day>=DAYS.length-1)return finish(true);st.day++;st.time=9;st.confidence=16;st.tests=[];st.shift=0;log(quality>=d.target?'The party travels safely and the bulletin matches field conditions.':quality>=58?'The route works, but the bulletin leaves uncertainty unresolved.':'The recommendation exposes the party to avoidable terrain.',`Forecast quality ${quality}; true hazard ${h}/100. Next: ${DAYS[st.day].brief}`);draw()},window.matchMedia('(prefers-reduced-motion: reduce)').matches?80:700)}
    function recover(){if(ended||!st.recovery)return;st.recovery=false;st.cred=clamp(st.cred-13,0,100);st.time+=4;st.confidence=clamp(st.confidence-5,0,100);log('A helicopter resupply extends the field day.','Extra time arrives, but public credibility drops because the plan exceeded its safety margin.');draw()}
    function finish(success){ended=true;clearTimeout(timer);const strong=success&&st.cred>=62&&st.score>=9000;log(strong?'The center promotes you to regional lead forecaster.':success?'The field week closes with a cautious reputation.':'The program suspends operations after repeated unsafe calls.',`Final score ${st.score}, credibility ${st.cred}. Replay with better slope selection, test allocation, and route conservatism.`);draw()}
    function log(a,b){const l=$('.sp-log',root);l.replaceChildren(Object.assign(document.createElement('strong'),{textContent:a}),Object.assign(document.createElement('small'),{textContent:b}))}
    function draw(){const vals=[`${st.day+1}/6`,`${st.time}h`,st.cred,st.score,`${Math.round(st.confidence)}%`,st.unlock?'Adaptive route':'Locked'];$$('[data-h]',root).forEach((e,i)=>e.textContent=vals[i]);$('.sp-grid',root).innerHTML=SLOPES.map((s,i)=>`<button class="sp-slope" data-slope="${i}" aria-pressed="${st.slope===i}">${s.name}<small>${s.aspect} aspect · ${s.angle}° · wind ${s.wind}/4 · trap ${s.terrain}/4</small></button>`).join('');$('.sp-tests',root).innerHTML=TESTS.map((t,i)=>`<button class="sp-test" data-test="${i}" aria-pressed="${st.tests.includes(i)}">${t.name}<small>${t.cost}h · evidence ${t.signal}</small></button>`).join('');const layers=['New snow','Storm slab',DAYS[st.day].weak,'Old snow'];$('.sp-layers',root).innerHTML=layers.map((x,i)=>`<div class="sp-layer" style="background:rgba(186,230,253,${.35+i*.13})">${x}</div>`).join('');$('[data-rating]',root).value=st.rating;$('[data-route]',root).value=st.route;$$('[data-a]',root).forEach(b=>b.disabled=ended);$('[data-a="recover"]',root).disabled=ended||!st.recovery;bindEvents()}
    function bindEvents(){$$('[data-slope]',root).forEach((b,i)=>{b.onclick=()=>{st.slope=i;draw()};b.onkeydown=e=>{if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft'].includes(e.key)){e.preventDefault();const d=e.key==='ArrowDown'||e.key==='ArrowRight'?1:-1;$$('[data-slope]',root)[(i+d+4)%4].focus()}}});$$('[data-test]',root).forEach((b,i)=>b.onclick=()=>doTest(i));$('[data-rating]',root).onchange=e=>st.rating=e.target.value;$('[data-route]',root).onchange=e=>st.route=+e.target.value;$('[data-a="forecast"]',root).onclick=issue;$('[data-a="probe"]',root).onclick=probe;$('[data-a="recover"]',root).onclick=recover;$('[data-a="restart"]',root).onclick=reset}
    dialog.addEventListener('close',()=>clearTimeout(timer),{once:true});reset()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
