(() => {
'use strict';
const APP={name:'Soundscape Steward',emoji:'🎛️',category:'experiment',version:'1.0.0',summary:'Shape six adaptive public soundscapes by balancing calm, clarity, energy, timing, and limited power.',description:'A local-only adaptive audio strategy experience with six venues, layered synthesis, changing audience needs, timed cues, power and attention tradeoffs, scoring, progression, failure, recovery, a session unlock, keyboard and touch controls, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const VENUES=[
{name:'Library atrium',target:{calm:78,clarity:72,energy:28},budget:14,cues:['arrival','focus'],goal:64},
{name:'Children’s museum',target:{calm:48,clarity:62,energy:76},budget:15,cues:['arrival','surge'],goal:66},
{name:'Transit concourse',target:{calm:44,clarity:82,energy:64},budget:16,cues:['arrival','alert'],goal:68},
{name:'Recovery ward',target:{calm:88,clarity:66,energy:18},budget:14,cues:['focus','quiet'],goal:72},
{name:'Night market',target:{calm:36,clarity:58,energy:90},budget:17,cues:['surge','alert'],goal:74},
{name:'Storm shelter',target:{calm:72,clarity:90,energy:42},budget:16,cues:['alert','quiet'],goal:78}
];
const LAYERS=[
{id:'air',name:'Air',icon:'≈',cost:2,calm:20,clarity:3,energy:2,freq:174},
{id:'pulse',name:'Pulse',icon:'•',cost:3,calm:-4,clarity:8,energy:24,freq:110},
{id:'chime',name:'Chime',icon:'✦',cost:3,calm:8,clarity:23,energy:8,freq:523},
{id:'voice',name:'Guide',icon:'◇',cost:4,calm:3,clarity:30,energy:4,freq:246},
{id:'rain',name:'Rain',icon:'⋮',cost:3,calm:25,clarity:-5,energy:1,freq:329},
{id:'bass',name:'Bass',icon:'▰',cost:4,calm:-8,clarity:2,energy:30,freq:82}
];
function style(){if($('#soundscape-steward-style'))return;const e=document.createElement('style');e.id='soundscape-steward-style';e.textContent=`
.soundscape-steward{max-width:1100px;display:grid;gap:12px}.ss-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.ss-stat,.ss-panel{border:1px solid var(--line);border-radius:17px;background:#fff}.ss-stat{padding:9px}.ss-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.ss-layout{display:grid;grid-template-columns:1.1fr .9fr;gap:12px}.ss-panel{padding:15px}.ss-stage{border-radius:20px;padding:18px;color:#fff;background:radial-gradient(circle at 75% 30%,#5d7f9c55,transparent 28%),linear-gradient(135deg,#14213d,#254b62);position:relative;overflow:hidden}.ss-orb{width:128px;height:128px;margin:14px auto;border-radius:50%;border:2px solid #ffffff44;box-shadow:0 0 0 20px #ffffff09,0 0 0 42px #ffffff06;display:grid;place-items:center;font-size:2.2rem;transition:transform .3s,box-shadow .3s}.ss-orb.live{transform:scale(1.04);box-shadow:0 0 0 25px #ffffff12,0 0 0 54px #ffffff08}.ss-targets{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:12px}.ss-target{background:#ffffff17;border-radius:12px;padding:8px}.ss-target span{display:block;font-size:.68rem;text-transform:uppercase}.ss-layers{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:12px}.ss-layer{border:1px solid var(--line);border-radius:13px;padding:10px;background:#fff}.ss-layer button{width:100%;min-height:44px;border:1px solid var(--line);border-radius:10px;background:#fff;font-weight:900}.ss-layer button[aria-pressed=true]{background:#dff3f2;border-color:#1f6f70}.ss-stepper{display:grid;grid-template-columns:42px 1fr 42px;gap:6px;align-items:center;margin-top:7px}.ss-stepper button{min-height:42px;border:1px solid var(--line);border-radius:10px;background:#fff;font-weight:900}.ss-stepper output{text-align:center;font-weight:900}.ss-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.ss-actions button{min-height:46px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800}.ss-actions .primary{background:#e3f5f2;border-color:#1f6f70}.ss-meter{height:11px;background:#e7ebef;border-radius:99px;overflow:hidden}.ss-meter span{display:block;height:100%;background:#1f6f70;transition:width .25s}.ss-row{display:flex;justify-content:space-between;gap:8px}.ss-log{min-height:105px}.ss-chip{display:inline-block;padding:5px 8px;border-radius:999px;background:#eef3f7;font-size:.72rem;margin:2px}.ss-note{font-size:.8rem;color:var(--muted)}.ss-layer button:focus-visible,.ss-stepper button:focus-visible,.ss-actions button:focus-visible{outline:3px solid #1f6f70;outline-offset:2px}
@media(max-width:820px){.ss-layout{grid-template-columns:1fr}.ss-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.ss-hud{grid-template-columns:repeat(2,1fr)}.ss-layers,.ss-actions,.ss-targets{grid-template-columns:1fr}.ss-orb{width:100px;height:100px}.ss-stepper{grid-template-columns:48px 1fr 48px}}@media(prefers-reduced-motion:reduce){.soundscape-steward *{animation:none!important;transition:none!important}}
`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-soundscape-steward]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true),a=$('.app-card',f);a.dataset.soundscapeSteward='1';a.dataset.category=APP.category;$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Experiment · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-soundscape-steward]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.ssBound)return;b.dataset.ssBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Experiment · adaptive audio';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
 const root=document.createElement('section');root.className='tool-panel soundscape-steward';root.innerHTML=`<div class="ss-hud">${['Venue','Power','Trust','Score','Cue','Peak'].map((x,i)=>`<div class="ss-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="ss-layout"><section class="ss-panel"><div class="ss-stage"><p class="app-meta" data-venue></p><h3 data-title></h3><p data-brief></p><div class="ss-orb" aria-hidden="true">◌</div><div class="ss-targets" data-targets></div></div><div class="ss-layers" data-layers></div><p class="ss-note">Keyboard: 1-6 select layer, Space toggle, ↑/↓ intensity, C trigger cue, Enter evaluate, M mute.</p></section><aside class="ss-panel"><div class="result-card ss-log" aria-live="polite"></div><div class="ss-row"><span>Calm</span><strong data-calm></strong></div><div class="ss-meter"><span data-calm-meter></span></div><div class="ss-row"><span>Clarity</span><strong data-clarity></strong></div><div class="ss-meter"><span data-clarity-meter></span></div><div class="ss-row"><span>Energy</span><strong data-energy></strong></div><div class="ss-meter"><span data-energy-meter></span></div><p><strong>Available cues</strong></p><div data-cues></div><div class="ss-actions"><button class="primary" data-a="evaluate">Evaluate scene</button><button data-a="cue">Trigger next cue</button><button data-a="listen">Start audio</button><button data-a="undo">Undo mix</button><button data-a="recover">Engineer assist</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
 let st,ended=false,ctx=null,nodes=[],keyHandler,closeHandler;
 function venue(){return VENUES[st.venue]}
 function reset(){stopAudio();st={venue:0,power:VENUES[0].budget,trust:62,score:0,selected:0,levels:Object.fromEntries(LAYERS.map(x=>[x.id,0])),history:[],cue:0,peak:0,assist:true,unlock:false,muted:false};ended=false;log('Mixer online.','Build a soundscape that matches the venue without exhausting power or attention.');draw()}
 function metrics(){let calm=28,clarity=26,energy=24,power=0;LAYERS.forEach(l=>{const n=st.levels[l.id];power+=n*l.cost;calm+=n*l.calm;clarity+=n*l.clarity;energy+=n*l.energy});const cue=venue().cues[st.cue];if(cue==='arrival'){clarity+=8;energy+=5}if(cue==='focus'){calm+=10;clarity+=6}if(cue==='surge'){energy+=14;calm-=8}if(cue==='alert'){clarity+=14;calm-=4}if(cue==='quiet'){calm+=14;energy-=9}return{calm:clamp(calm,0,100),clarity:clamp(clarity,0,100),energy:clamp(energy,0,100),power}}
 function adjust(delta){if(ended)return;const l=LAYERS[st.selected],old=st.levels[l.id],next=clamp(old+delta,0,3);if(next===old)return;st.history.push({id:l.id,value:old});st.levels[l.id]=next;draw();syncAudio()}
 function toggle(i=st.selected){if(ended)return;st.selected=i;const l=LAYERS[i],old=st.levels[l.id];st.history.push({id:l.id,value:old});st.levels[l.id]=old?0:1;draw();syncAudio()}
 function undo(){if(!st.history.length||ended)return log('Nothing to undo.','The mix history is empty.');const h=st.history.pop();st.levels[h.id]=h.value;log('Mix restored.','The previous layer intensity returned.');draw();syncAudio()}
 function nextCue(){if(ended)return;st.cue=(st.cue+1)%venue().cues.length;st.trust=clamp(st.trust-1,0,100);log('Scene changed.',`The audience now needs a ${venue().cues[st.cue]} response.`);draw();syncAudio()}
 function evaluate(){if(ended)return;const v=venue(),m=metrics();if(m.power>st.power)return log('Power limit exceeded.',`Mix uses ${m.power}; venue supply is ${st.power}.`);const d=Math.abs(m.calm-v.target.calm)+Math.abs(m.clarity-v.target.clarity)+Math.abs(m.energy-v.target.energy);const cueFit=1-Math.min(1,d/180),score=Math.round(cueFit*100);st.peak=Math.max(st.peak,score);const pass=score>=v.goal;st.trust=clamp(st.trust+(pass?8:-10),0,100);st.score+=Math.max(0,score*9-m.power*5);if(st.score>=1800)st.unlock=true;if(!pass){log('Scene drifted.',`Fit ${score}; target ${v.goal}. Rebalance the active layers and cue response.`);if(st.trust<=18)return finish(false,'The venue cancelled the residency.');draw();return}if(st.venue===VENUES.length-1)return finish(true,`All six venues stabilized. Final score ${st.score}.`);st.venue++;st.power=VENUES[st.venue].budget;st.levels=Object.fromEntries(LAYERS.map(x=>[x.id,0]));st.history=[];st.cue=0;log('Venue advanced.',`Next: ${venue().name}.`);draw();syncAudio()}
 function recover(){if(ended||!st.assist)return log('Assist unavailable.','The engineer can intervene once per session.');st.assist=false;st.score=Math.max(0,st.score-240);st.trust=clamp(st.trust-7,0,100);const t=venue().target;LAYERS.forEach(l=>st.levels[l.id]=0);const ranked=[...LAYERS].sort((a,b)=>Math.abs(b.calm-t.calm)+Math.abs(b.clarity-t.clarity)+Math.abs(b.energy-t.energy)-(Math.abs(a.calm-t.calm)+Math.abs(a.clarity-t.clarity)+Math.abs(a.energy-t.energy)));ranked.slice(0,2).forEach(l=>st.levels[l.id]=1);log('Engineer assist used.','A viable two-layer baseline was restored, with score and trust consequences.');draw();syncAudio()}
 function finish(win,msg){ended=true;stopAudio();log(win?'Residency completed.':'Residency ended.',msg);draw()}
 function log(a,b){$('.ss-log',root).innerHTML=`<strong>${a}</strong><p>${b}</p>`}
 function draw(){const v=venue(),m=metrics();$$('[data-h]',root).forEach((e,i)=>e.textContent=[`${st.venue+1}/6`,st.power,Math.round(st.trust),st.score,venue().cues[st.cue],st.peak][i]);$('[data-venue]',root).textContent=v.name;$('[data-title]',root).textContent='Balance the room';$('[data-brief]',root).textContent=`Target fit ${v.goal}. Current cue: ${v.cues[st.cue]}.`;$('[data-targets]',root).innerHTML=['calm','clarity','energy'].map(k=>`<div class="ss-target"><span>${k}</span><strong>${v.target[k]}</strong></div>`).join('');$('[data-layers]',root).innerHTML=LAYERS.map((l,i)=>`<div class="ss-layer"><button type="button" data-layer="${i}" aria-pressed="${st.levels[l.id]>0}">${l.icon} ${l.name}</button><div class="ss-stepper"><button type="button" data-step="${i},-1" aria-label="Decrease ${l.name}">−</button><output>${st.levels[l.id]}</output><button type="button" data-step="${i},1" aria-label="Increase ${l.name}">+</button></div></div>`).join('')+(st.unlock?'<div class="ss-layer"><strong>Unlocked: Harmonic veil</strong><p class="ss-note">All active layers gain +4 calm and clarity.</p></div>':'');if(st.unlock){m.calm=clamp(m.calm+4,0,100);m.clarity=clamp(m.clarity+4,0,100)}['calm','clarity','energy'].forEach(k=>{$(`[data-${k}]`,root).textContent=Math.round(m[k]);$(`[data-${k}-meter]`,root).style.width=`${m[k]}%`});$('[data-cues]',root).innerHTML=v.cues.map((c,i)=>`<span class="ss-chip">${i===st.cue?'● ':'○ '}${c}</span>`).join('');$('.ss-orb',root).classList.toggle('live',!!ctx&&!st.muted);$$('[data-layer]',root).forEach(b=>b.onclick=()=>toggle(+b.dataset.layer));$$('[data-step]',root).forEach(b=>b.onclick=()=>{const[i,d]=b.dataset.step.split(',').map(Number);st.selected=i;adjust(d)});$$('[data-a]',root).forEach(b=>{b.disabled=ended&&b.dataset.a!=='restart';b.onclick=({evaluate,nextCue,listen,undo,recover,restart}:{evaluate,nextCue,listen:toggleAudio,undo,recover,restart:reset})[b.dataset.a]});$('[data-a="listen"]',root).textContent=ctx&&!st.muted?'Mute audio':'Start audio'}
 function toggleAudio(){if(!ctx){ctx=new (window.AudioContext||window.webkitAudioContext)();buildAudio();st.muted=false}else st.muted=!st.muted;syncAudio();draw()}
 function buildAudio(){nodes=LAYERS.map((l,i)=>{const o=ctx.createOscillator(),g=ctx.createGain(),f=ctx.createBiquadFilter();o.type=i%2?'triangle':'sine';o.frequency.value=l.freq;f.type='lowpass';f.frequency.value=900+(i*170);g.gain.value=0;o.connect(f).connect(g).connect(ctx.destination);o.start();return{o,g}})}
 function syncAudio(){if(!ctx)return;nodes.forEach((n,i)=>{const level=st.muted?0:st.levels[LAYERS[i].id];n.g.gain.setTargetAtTime(level*.025,ctx.currentTime,.06);n.o.frequency.setTargetAtTime(LAYERS[i].freq*(1+st.cue*.01),ctx.currentTime,.08)})}
 function stopAudio(){nodes.forEach(n=>{try{n.o.stop()}catch{}});nodes=[];if(ctx){ctx.close();ctx=null}}
 keyHandler=e=>{if(!dialog.open)return;if(/^[1-6]$/.test(e.key)){st.selected=+e.key-1;draw()}else if(e.key===' '){e.preventDefault();toggle()}else if(e.key==='ArrowUp'){e.preventDefault();adjust(1)}else if(e.key==='ArrowDown'){e.preventDefault();adjust(-1)}else if(e.key.toLowerCase()==='c')nextCue();else if(e.key==='Enter')evaluate();else if(e.key.toLowerCase()==='m')toggleAudio()};document.addEventListener('keydown',keyHandler);closeHandler=()=>{document.removeEventListener('keydown',keyHandler);stopAudio();dialog.removeEventListener('close',closeHandler)};dialog.addEventListener('close',closeHandler);reset()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();