(() => {
  const APP = { name:'Stacklight Stow', emoji:'📦', category:'play', version:'1.0.0', summary:'Load a tiny cargo deck while balancing weight, port order, hazards, and crane energy.', description:'A local cargo-stowage puzzle with deck balance, unloading order, fragile and hazard rules, crane energy, adaptive manifests, recoverable inspections, session-only storm mode, scoring, responsive SVG rendering, touch and keyboard controls, optional local audio, reduced-motion behavior, and teardown.' };
  const labelCategory = v => v === 'play' ? 'Play' : v === 'useful' ? 'Useful' : 'Experiment';
  const filter = () => document.querySelector('.filter.is-active')?.dataset.filter || 'all';
  const eligible = () => filter() === 'all' || filter() === APP.category;
  function installStyles(){
    if(document.querySelector('#stacklight-stow-styles')) return;
    const s=document.createElement('style'); s.id='stacklight-stow-styles';
    s.textContent = `.stow-card{animation:stow-rise .28s ease both}.stow-game{max-width:1040px;gap:14px}.stow-hud{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.stow-stat{border:1px solid var(--line);border-radius:15px;background:#fff;padding:10px 12px}.stow-stat span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.stow-stat strong{display:block;margin-top:4px;font-size:.98rem}.stow-board{border:0;border-radius:26px;background:#0f172a;color:white;padding:0;overflow:hidden;touch-action:manipulation;box-shadow:inset 0 0 0 1px rgba(255,255,255,.14)}.stow-board:focus-visible{outline:4px solid var(--accent);outline-offset:4px}.stow-board svg{display:block;width:100%;height:min(58vh,510px);min-height:360px}.stow-console{display:grid;grid-template-columns:1fr 1fr;gap:10px}.stow-panel,.stow-manifest{border:1px solid var(--line);border-radius:18px;background:#fff;padding:13px}.stow-queue,.stow-rules{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.stow-chip,.stow-rules span{border:1px solid var(--line);border-radius:999px;background:#fff;color:var(--ink);padding:8px 11px;font-weight:900}.stow-chip.is-active{background:#111827;color:#fff}.stow-chip.is-loaded{opacity:.45}.stow-log{min-height:92px;padding:17px 19px}@media(max-width:760px){.stow-hud{grid-template-columns:repeat(2,1fr)}.stow-console{grid-template-columns:1fr}.stow-board svg{height:56vh;min-height:340px}}@media(prefers-reduced-motion:reduce){.stow-card{animation:none}.stow-board svg{min-height:330px}}@keyframes stow-rise{from{opacity:0;transform:translateY(12px) scale(.98)}to{opacity:1;transform:translateY(0) scale(1)}}`;
    document.head.append(s);
  }
  function initCard(){
    const grid=document.querySelector('#app-grid'), template=document.querySelector('#app-card-template');
    if(!grid||!template||document.querySelector('[data-stacklight-stow-card]')||!eligible()) return;
    installStyles();
    const node=template.content.cloneNode(true), card=node.querySelector('.app-card');
    card.dataset.category=APP.category; card.dataset.stacklightStowCard='true'; card.classList.add('stow-card');
    node.querySelector('.app-icon').textContent=APP.emoji; node.querySelector('.app-meta').textContent=`${labelCategory(APP.category)} · v${APP.version}`;
    node.querySelector('.app-name').textContent=APP.name; node.querySelector('.app-summary').textContent=APP.summary;
    const open=node.querySelector('.app-card-button'); open.setAttribute('aria-label',`Open ${APP.name}`); open.addEventListener('click',openApp); grid.append(node);
  }
  function wireFilterRefresh(){ document.querySelectorAll('.filter').forEach(b=>{ if(b.dataset.stowRefresh) return; b.dataset.stowRefresh='true'; b.addEventListener('click',()=>setTimeout(initCard,0)); }); }
  function openApp(){
    const dialog=document.querySelector('#app-dialog'), stage=document.querySelector('#app-stage'), title=document.querySelector('#dialog-title'), category=document.querySelector('#dialog-category'), description=document.querySelector('#dialog-description'), feedback=document.querySelector('#dialog-feedback');
    if(!dialog||!stage||!title||!category||!description||!feedback) return;
    title.textContent=APP.name; category.textContent=`${labelCategory(APP.category)} · ${APP.emoji}`; description.textContent=APP.description;
    feedback.href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Stacklight%20Stow';
    stage.replaceChildren(); renderGame(stage, dialog); dialog.showModal();
  }
  function renderGame(stage, dialog){
    const root=document.createElement('section'); root.className='tool-panel stow-game';
    const hud=document.createElement('div'); hud.className='stow-hud'; hud.innerHTML='<div class="stow-stat"><span>Round</span><strong id="st-round">1 / 5</strong></div><div class="stow-stat"><span>Score</span><strong id="st-score">0</strong></div><div class="stow-stat"><span>Energy</span><strong id="st-energy">12</strong></div><div class="stow-stat"><span>Trim</span><strong id="st-trim">Even</strong></div><div class="stow-stat"><span>Inspect</span><strong id="st-risk">0</strong></div>';
    const board=document.createElement('button'); board.type='button'; board.className='stow-board'; board.setAttribute('aria-label','Stacklight Stow deck. Select a container, then choose a deck slot. Use arrow keys to move the crane, Enter to load, Backspace to remove a container, I to inspect, and N for a new run.'); board.innerHTML='<svg aria-hidden="true" viewBox="0 0 940 500"></svg>';
    const consoleBox=document.createElement('div'); consoleBox.className='stow-console'; consoleBox.innerHTML='<div class="stow-panel"><strong>Manifest</strong><p>Load containers so early-port cargo stays reachable, fragile crates are not buried, hazards stay apart, and port/starboard weight stays balanced.</p><div class="stow-queue"></div></div><div class="stow-manifest"><strong>Inspection rules</strong><div class="stow-rules"><span>Trim within 5</span><span>Fragile top-safe</span><span>Hazards separated</span><span>Port A reachable</span></div></div>';
    const log=document.createElement('div'); log.className='result-card stow-log'; log.setAttribute('aria-live','polite');
    const foot=document.createElement('div'); foot.className='tool-actions'; root.append(hud,board,consoleBox,log,foot); stage.append(root);
    const svg=board.querySelector('svg'), queueBox=consoleBox.querySelector('.stow-queue'), reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    const cols=6, rows=4, ports=['A','B','C'];
    const state={round:1,rounds:5,score:0,energy:12,risk:0,selected:0,cursor:0,deck:Array(cols*rows).fill(null),manifest:[],loaded:0,storm:false,unlocked:false,raf:0,pulse:0,audio:false,ac:null};
    const inspectBtn=makeButton('Inspect',inspect,true), undoBtn=makeButton('Unload slot',unload,true), newBtn=makeButton('New run',newRun,true), stormBtn=makeButton('Storm mode',toggleStorm,true), soundBtn=makeButton('Sound off',toggleSound,true);
    foot.append(inspectBtn,undoBtn,newBtn,stormBtn,soundBtn);
    board.addEventListener('click',placeAtCursor); board.addEventListener('keydown',onKey); board.addEventListener('pointermove',onPointer); dialog.addEventListener('close',teardown,{once:true});
    function makeButton(text,fn,secondary){ const b=document.createElement('button'); b.type='button'; b.className=secondary?'button button-secondary':'button'; b.textContent=text; b.addEventListener('click',fn); return b; }
    function say(html){ log.innerHTML=html; }
    function makeManifest(){ const count=6+state.round+(state.storm?1:0); const list=[]; for(let i=0;i<count;i++){ const port=ports[(i+state.round)%3], weight=1+((i*2+state.round)%5), fragile=(i+state.round)%5===0, haz=(i*3+state.round)%7===0; list.push({id:i,port,weight,fragile,haz,loaded:false}); } state.manifest=list.sort((a,b)=>a.port.localeCompare(b.port)||b.weight-a.weight); }
    function generate(){ state.energy=Math.max(8,14-state.round+(state.storm?-2:0)); state.risk=0; state.loaded=0; state.cursor=0; state.selected=0; state.deck=Array(cols*rows).fill(null); makeManifest(); render(); say(`<strong>Round ${state.round}: stow the manifest.</strong><small>Port A unloads first. Heavy boxes improve score only if the ship stays trimmed.</small>`); }
    function cell(c,r){ return r*cols+c; }
    function topOpen(c){ for(let r=rows-1;r>=0;r--) if(!state.deck[cell(c,r)]) return cell(c,r); return -1; }
    function canPlaceAt(idx){ const c=idx%cols, r=Math.floor(idx/cols); return !state.deck[idx] && (r===rows-1 || state.deck[cell(c,r+1)]); }
    function activeCargo(){ return state.manifest[state.selected]; }
    function placeAtCursor(){ const cargo=activeCargo(); if(!cargo||cargo.loaded){ say('<strong>Choose an unloaded container.</strong><small>Loaded chips dim in the manifest.</small>'); return; } const c=state.cursor%cols, idx=canPlaceAt(state.cursor)?state.cursor:topOpen(c); if(idx<0){ say('<strong>That stack is full.</strong><small>Move the crane to another column.</small>'); return; } if(state.energy<=0){ recover('The crane battery is empty.'); return; } state.deck[idx]=cargo.id; cargo.loaded=true; state.loaded++; state.energy--; if(state.storm && Math.random()<.22){ state.risk++; say('<strong>A gust shifted the hoist.</strong><small>Inspection risk rose. Check trim before finishing.</small>'); } else say(`<strong>Loaded ${label(cargo)}.</strong><small>${state.manifest.length-state.loaded} containers remain.</small>`); beep('move'); render(); if(state.loaded===state.manifest.length) inspect(); }
    function unload(){ const id=state.deck[state.cursor]; if(id==null){ say('<strong>No container in the selected slot.</strong><small>Move the crane to a loaded cell before unloading.</small>'); return; } const c=state.cursor%cols, r=Math.floor(state.cursor/cols); if(r>0 && state.deck[cell(c,r-1)]!=null){ say('<strong>Buried container.</strong><small>Only the top container in a stack can be unloaded.</small>'); return; } const cargo=state.manifest.find(x=>x.id===id); cargo.loaded=false; state.deck[state.cursor]=null; state.loaded--; state.energy=Math.max(0,state.energy-1); say(`<strong>Unloaded ${label(cargo)}.</strong><small>Recovery costs one energy but can save the inspection.</small>`); beep('bad'); render(); }
    function inspect(){ const v=violations(); if(v.length){ state.risk+=v.length; state.score=Math.max(0,state.score-10*v.length); recover(`${v.length} inspection issue${v.length>1?'s':''}: ${v[0]}`); return; } const bonus=state.energy*12+Math.max(0,34-state.risk*5)+state.manifest.reduce((s,c)=>s+c.weight,0)*2; state.score+=120+bonus; state.unlocked=state.unlocked||state.score>=620; beep('good'); if(state.round>=state.rounds) say(`<strong>Voyage complete: ${state.score}.</strong><small>${state.unlocked?'Storm mode is unlocked for this session.':'Score 620 to unlock storm mode.'}</small>`); else { state.round++; generate(); } }
    function recover(reason){ state.energy=Math.max(state.energy,2); say(`<strong>${reason}</strong><small>Recovery mode grants enough crane energy for two corrective moves.</small>`); beep('bad'); render(); }
    function violations(){ const out=[]; const trim=trimValue(); if(Math.abs(trim)>5) out.push('ship trim is outside the safe range'); for(let c=0;c<cols;c++){ for(let r=1;r<rows;r++){ const top=state.deck[cell(c,r-1)], below=state.deck[cell(c,r)]; if(top!=null&&below!=null){ const a=byId(top), b=byId(below); if(b.fragile) out.push('a fragile crate is buried'); if(a.haz&&b.haz) out.push('hazards are stacked together'); if(portRank(a.port)>portRank(b.port)) out.push('earlier-port cargo is blocked'); } } } for(let r=0;r<rows;r++) for(let c=0;c<cols-1;c++){ const a=byId(state.deck[cell(c,r)]), b=byId(state.deck[cell(c+1,r)]); if(a&&b&&a.haz&&b.haz) out.push('hazards are adjacent'); } return [...new Set(out)]; }
    function portRank(p){ return ports.indexOf(p); }
    function byId(id){ return id==null?null:state.manifest.find(c=>c.id===id); }
    function trimValue(){ let left=0,right=0; state.deck.forEach((id,i)=>{ const cargo=byId(id); if(!cargo) return; if(i%cols<cols/2) left+=cargo.weight; else right+=cargo.weight; }); return right-left; }
    function label(c){ return `${c.port}${c.weight}${c.fragile?'F':''}${c.haz?'H':''}`; }
    function toggleStorm(){ if(!state.unlocked){ say('<strong>Storm mode is locked.</strong><small>Score 620 in a run to add gusts, tighter energy, and one extra container.</small>'); return; } state.storm=!state.storm; stormBtn.textContent=state.storm?'Calm mode':'Storm mode'; newRun(); }
    function newRun(){ Object.assign(state,{round:1,score:0,risk:0,selected:0,cursor:0,loaded:0}); generate(); }
    function toggleSound(){ const AC=window.AudioContext||window.webkitAudioContext; if(!AC){ say('<strong>Sound is not available here.</strong><small>The stowage puzzle still works silently.</small>'); return; } state.audio=!state.audio; soundBtn.textContent=state.audio?'Sound on':'Sound off'; soundBtn.setAttribute('aria-pressed',String(state.audio)); if(state.audio){ state.ac ||= new AC(); state.ac.resume(); beep('good'); } }
    function beep(kind){ if(!state.audio||!state.ac) return; const now=state.ac.currentTime,o=state.ac.createOscillator(),g=state.ac.createGain(); o.type='triangle'; o.frequency.value=kind==='good'?720:kind==='bad'?160:380; g.gain.setValueAtTime(.0001,now); g.gain.exponentialRampToValueAtTime(.04,now+.02); g.gain.exponentialRampToValueAtTime(.0001,now+.18); o.connect(g).connect(state.ac.destination); o.start(now); o.stop(now+.2); }
    function onPointer(e){ const rect=board.getBoundingClientRect(), x=(e.clientX-rect.left)/rect.width*940, y=(e.clientY-rect.top)/rect.height*500; if(x<120||x>820||y<88||y>408) return; const c=Math.max(0,Math.min(cols-1,Math.floor((x-120)/700*cols))), r=Math.max(0,Math.min(rows-1,Math.floor((y-88)/320*rows))); state.cursor=cell(c,r); draw(); }
    function onKey(e){ const k=e.key.toLowerCase(), c=state.cursor%cols, r=Math.floor(state.cursor/cols); if(k==='arrowright'){e.preventDefault(); state.cursor=cell(Math.min(cols-1,c+1),r); draw();} if(k==='arrowleft'){e.preventDefault(); state.cursor=cell(Math.max(0,c-1),r); draw();} if(k==='arrowdown'){e.preventDefault(); state.cursor=cell(c,Math.min(rows-1,r+1)); draw();} if(k==='arrowup'){e.preventDefault(); state.cursor=cell(c,Math.max(0,r-1)); draw();} if(k==='tab'){ state.selected=(state.selected+(e.shiftKey?-1:1)+state.manifest.length)%state.manifest.length; render(); } if(k==='enter'||k===' '){e.preventDefault(); placeAtCursor();} if(k==='backspace'||k==='delete'){e.preventDefault(); unload();} if(k==='i'){e.preventDefault(); inspect();} if(k==='n'){e.preventDefault(); newRun();} }
    function render(){ updateHud(); renderQueue(); draw(); }
    function updateHud(){ document.querySelector('#st-round').textContent=`${state.round} / ${state.rounds}`; document.querySelector('#st-score').textContent=state.score; document.querySelector('#st-energy').textContent=state.energy; const t=trimValue(); document.querySelector('#st-trim').textContent=t===0?'Even':`${Math.abs(t)} ${t>0?'starboard':'port'}`; document.querySelector('#st-risk').textContent=state.risk; }
    function renderQueue(){ queueBox.replaceChildren(); state.manifest.forEach((cargo,i)=>{ const b=document.createElement('button'); b.type='button'; b.className='stow-chip'; b.textContent=label(cargo); b.setAttribute('aria-pressed',String(i===state.selected)); b.classList.toggle('is-active',i===state.selected); b.classList.toggle('is-loaded',cargo.loaded); b.addEventListener('click',()=>{state.selected=i; render();}); queueBox.append(b); }); }
    function draw(){ const trim=trimValue(), bads=violations().length, cargoColors={A:'#7dd3fc',B:'#c4b5fd',C:'#fcd34d'}; const wave=reduced?0:Math.sin(state.pulse)*6; let html='<rect width="940" height="500" fill="#0f172a"/><path d="M92 420 Q470 '+(450+wave)+' 848 420 L802 468 L138 468 Z" fill="#1e293b" stroke="#67e8f9" stroke-width="3"/><text x="470" y="54" text-anchor="middle" fill="#e0f2fe" font-size="24" font-weight="900">Stacklight Stow</text>';
      html+=`<text x="470" y="82" text-anchor="middle" fill="#bae6fd" font-size="14">Trim ${trim===0?'even':Math.abs(trim)+' '+(trim>0?'starboard':'port')} · ${bads} inspection flags</text>`;
      for(let c=0;c<cols;c++) for(let r=0;r<rows;r++){ const idx=cell(c,r), x=120+c*(700/cols)+8, y=88+r*(320/rows)+8, w=700/cols-16, h=320/rows-16, active=idx===state.cursor; html+=`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="12" fill="${active?'#334155':'#172033'}" stroke="${active?'#fef08a':'#334155'}" stroke-width="${active?4:1}"/>`; const cargo=byId(state.deck[idx]); if(cargo){ html+=`<rect x="${x+7}" y="${y+10}" width="${w-14}" height="${h-20}" rx="10" fill="${cargoColors[cargo.port]}" opacity=".95"/><text x="${x+w/2}" y="${y+h/2-3}" text-anchor="middle" fill="#0f172a" font-size="20" font-weight="900">${label(cargo)}</text><text x="${x+w/2}" y="${y+h/2+18}" text-anchor="middle" fill="#0f172a" font-size="12">${cargo.fragile?'fragile ':''}${cargo.haz?'hazard':''}</text>`; } }
      const active=activeCargo(); if(active) html+=`<g transform="translate(${150+(state.cursor%cols)*(700/cols)} 74)"><path d="M0 0 H74 L58 22 H16 Z" fill="#fef08a"/><text x="37" y="16" text-anchor="middle" fill="#111827" font-size="12" font-weight="900">${label(active)}</text></g>`;
      html+='<text x="96" y="438" text-anchor="middle" fill="#bfdbfe" font-size="12" font-weight="900">PORT</text><text x="844" y="438" text-anchor="middle" fill="#bfdbfe" font-size="12" font-weight="900">STARBOARD</text>';
      svg.innerHTML=html; updateHud(); }
    function loop(){ state.pulse+=.045; draw(); state.raf=requestAnimationFrame(loop); }
    function teardown(){ cancelAnimationFrame(state.raf); if(state.ac&&state.ac.state!=='closed') state.ac.close(); }
    generate(); if(!reduced) loop();
  }
  const boot=()=>{ wireFilterRefresh(); setTimeout(initCard,80); setTimeout(initCard,400); };
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',boot,{once:true}); else boot();
})();
