(() => {
  'use strict';
  const APP={name:'Stage Rig',emoji:'🎭',category:'play',version:'1.0.0',summary:'Design six live-show lighting cues while balancing coverage, mood, heat, power, crew time, and audience trust.',description:'A local-only stage-lighting strategy game with six productions, fixture placement, color and focus choices, cue sequencing, power and heat limits, crew time, audience trust, score, a session unlock, meaningful failure, one costly recovery, touch and keyboard controls, reduced motion, and teardown.'};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const FIXTURES=[{id:'wash',name:'Wash',power:2,heat:2,coverage:4,mood:2},{id:'spot',name:'Spot',power:3,heat:3,coverage:2,mood:4},{id:'bar',name:'LED bar',power:1,heat:1,coverage:3,mood:3},{id:'gobo',name:'Gobo',power:2,heat:2,coverage:1,mood:5}];
  const SHOWS=[
    {name:'Quiet monologue',need:{coverage:5,mood:8,contrast:6,motion:2},note:'Hold attention without flattening the actor.'},
    {name:'Dance quartet',need:{coverage:9,mood:7,contrast:7,motion:8},note:'Track bodies cleanly through fast crossings.'},
    {name:'Storm scene',need:{coverage:7,mood:10,contrast:9,motion:9},note:'Build danger without cooking the rig.'},
    {name:'Comedy set',need:{coverage:8,mood:4,contrast:5,motion:4},note:'Faces must read from every seat.'},
    {name:'Finale reveal',need:{coverage:9,mood:9,contrast:10,motion:7},note:'Save enough power for a decisive last image.'},
    {name:'Touring encore',need:{coverage:8,mood:8,contrast:8,motion:8},note:'Deliver polish with a tired crew and a hot grid.'}
  ];
  function style(){if($('#stage-rig-style'))return;const e=document.createElement('style');e.id='stage-rig-style';e.textContent=`.stage-rig{max-width:1100px;display:grid;gap:12px}.sr-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.sr-stat,.sr-card{border:1px solid var(--line);border-radius:17px;background:#fff}.sr-stat{padding:9px}.sr-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.sr-layout{display:grid;grid-template-columns:1.08fr .92fr;gap:12px}.sr-card{padding:15px}.sr-stage{position:relative;min-height:340px;border-radius:22px;overflow:hidden;background:linear-gradient(#101827,#05070b);display:grid;grid-template-columns:repeat(5,1fr);grid-template-rows:repeat(4,1fr);gap:6px;padding:18px}.sr-cell{position:relative;border:1px solid rgba(255,255,255,.14);border-radius:12px;background:rgba(255,255,255,.03);min-height:60px;color:white}.sr-cell[aria-pressed=true]{outline:3px solid #facc15}.sr-cell b{position:absolute;inset:auto 6px 5px;font-size:.62rem}.sr-beam{position:absolute;inset:8px;border-radius:50%;filter:blur(2px);opacity:.72}.sr-tools,.sr-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.sr-tools button,.sr-actions button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800;padding:9px}.sr-tools button[aria-pressed=true],.sr-actions .primary{background:#fef3c7;border-color:#d97706}.sr-controls{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:10px}.sr-controls label{font-size:.72rem;font-weight:900;text-transform:uppercase;color:var(--muted)}.sr-controls select,.sr-controls input{width:100%}.sr-meters{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:10px}.sr-meter{background:#f5f5f4;border-radius:10px;padding:7px;font-size:.7rem}.sr-meter b{display:block;font-size:1rem}.sr-log{min-height:108px}.sr-actions{margin-top:10px}@media(max-width:820px){.sr-layout{grid-template-columns:1fr}.sr-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:520px){.sr-hud{grid-template-columns:repeat(2,1fr)}.sr-stage{min-height:280px;padding:10px;gap:4px}.sr-cell{min-height:48px}.sr-controls,.sr-tools,.sr-actions{grid-template-columns:1fr 1fr}.sr-meters{grid-template-columns:repeat(2,1fr)}}@media(prefers-reduced-motion:reduce){.stage-rig *{animation:none!important;transition:none!important}}`;document.head.append(e)}
  function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-stage-rig]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.stageRig='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
  function boot(){style();let n=0;const r=()=>{card();if(!$('[data-stage-rig]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.srBound)return;b.dataset.srBound='1';b.addEventListener('click',()=>setTimeout(card))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · theater lighting strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel stage-rig';root.innerHTML=`<div class="sr-hud">${['Show','Power','Heat','Crew','Trust','Score'].map((x,i)=>`<div class="sr-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="sr-layout"><section class="sr-card"><div class="sr-stage" role="grid" aria-label="Lighting rig grid"></div><div class="sr-meters"></div></section><aside class="sr-card"><div class="result-card sr-log" aria-live="polite"></div><p class="eyebrow">Fixture</p><div class="sr-tools"></div><div class="sr-controls"><label>Color<select data-c="color"><option value="amber">Amber</option><option value="blue">Blue</option><option value="magenta">Magenta</option><option value="white">White</option></select></label><label>Focus<select data-c="focus"><option value="wide">Wide</option><option value="medium">Medium</option><option value="tight">Tight</option></select></label><label>Intensity <output data-intensity></output><input data-c="intensity" type="range" min="1" max="5" step="1"></label><label>Cue speed<select data-c="speed"><option value="1">Still</option><option value="2">Slow</option><option value="4">Fast</option></select></label></div><div class="sr-actions"><button class="primary" data-a="run">Run cue</button><button data-a="clear">Clear rig</button><button data-a="recover">Call swing crew</button><button data-a="restart">New tour</button></div></aside></div>`;stage.append(root);
    let st,ended=false;
    function reset(){st={show:0,power:22,heat:0,crew:12,trust:76,score:0,fixture:'wash',color:'amber',focus:'wide',intensity:3,speed:2,placements:Array(20).fill(null),unlock:false,recovery:true};ended=false;log(SHOWS[0].note,'Place fixtures on the grid, then run the cue.');draw()}
    function metrics(){let coverage=0,mood=0,contrast=0,motion=st.speed*2;st.placements.forEach(p=>{if(!p)return;const f=FIXTURES.find(x=>x.id===p.fixture);coverage+=f.coverage+(p.focus==='wide'?2:p.focus==='tight'?-1:0);mood+=f.mood+(p.color==='blue'||p.color==='magenta'?1:0);contrast+=p.focus==='tight'?3:p.focus==='medium'?2:1});const count=st.placements.filter(Boolean).length;return {coverage:clamp(Math.round(coverage/Math.max(1,count)),1,10),mood:clamp(Math.round(mood/Math.max(1,count)+st.intensity/2),1,10),contrast:clamp(Math.round(contrast/Math.max(1,count)+st.intensity),1,10),motion:clamp(motion,1,10)}}
    function place(i){if(ended)return;const f=FIXTURES.find(x=>x.id===st.fixture);if(st.placements[i]){st.placements[i]=null;st.crew=Math.min(12,st.crew+1)}else{if(st.crew<=0)return log('The crew is out of time.','Remove a fixture or run the current cue.');st.placements[i]={fixture:st.fixture,color:st.color,focus:st.focus,intensity:st.intensity};st.crew--}draw()}
    function run(){if(ended)return;const count=st.placements.filter(Boolean).length;if(!count)return log('The stage is dark.','Place at least one fixture before running the cue.');const b=SHOWS[st.show],m=metrics();let power=0,heat=0;st.placements.forEach(p=>{if(!p)return;const f=FIXTURES.find(x=>x.id===p.fixture);power+=f.power+p.intensity;heat+=f.heat+p.intensity/2});if(st.power<power)return log('The dimmer rack trips.','Reduce fixture count or intensity, or use the one swing-crew recovery.');st.power-=power;st.heat+=Math.ceil(heat);const miss=Object.keys(b.need).reduce((s,k)=>s+Math.abs(m[k]-b.need[k]),0);const quality=clamp(100-miss*7-(st.heat>28?12:0),0,100);st.score+=quality*15;st.trust=clamp(st.trust+(quality>=84?8:quality<55?-20:-5),0,100);if(st.score>=3600)st.unlock=true;if(st.trust<=0||st.heat>=42)return end(false);if(st.show>=SHOWS.length-1)return end(true);st.show++;st.crew=Math.min(12,st.crew+3);st.heat=Math.max(0,st.heat-5);st.placements=Array(20).fill(null);log(quality>=84?'The cue lands exactly on the beat.':quality>=64?'The scene reads, but the rig feels cautious.':'The audience loses the visual story.',`Cue ${quality}. Next show: ${SHOWS[st.show].note}`);draw()}
    function recover(){if(ended||!st.recovery)return;st.recovery=false;st.trust=clamp(st.trust-14,0,100);st.power+=10;st.crew+=4;st.heat=Math.max(0,st.heat-10);log('The swing crew stabilizes the rig.','Power and time return, but the emergency call costs trust.');draw()}
    function end(success){ended=true;const strong=success&&st.trust>=60&&st.score>=7200;log(strong?'The tour earns a standing ovation.':success?'The show closes with a fragile lighting plot.':'The production goes dark.',`Final score ${st.score}, trust ${st.trust}, heat ${st.heat}. Replay to find cleaner cue sequences.`);draw()}
    function log(a,b){const l=$('.sr-log',root);l.replaceChildren(Object.assign(document.createElement('strong'),{textContent:a}),Object.assign(document.createElement('small'),{textContent:b}))}
    function draw(){const vals=[`${st.show+1}/6`,st.power,st.heat,st.crew,st.trust,st.score];$$('[data-h]',root).forEach((e,i)=>e.textContent=vals[i]);$('.sr-tools',root).innerHTML=FIXTURES.concat(st.unlock?[{id:'prism',name:'Prism mover',power:2,heat:2,coverage:4,mood:5}]:[]).map(x=>`<button data-fixture="${x.id}" aria-pressed="${st.fixture===x.id}">${x.name}</button>`).join('');$('.sr-stage',root).innerHTML=st.placements.map((p,i)=>`<button class="sr-cell" role="gridcell" data-cell="${i}" aria-label="Rig position ${i+1}${p?`, ${p.fixture} fixture`:''}" aria-pressed="${!!p}">${p?`<span class="sr-beam" style="background:${p.color==='amber'?'#f59e0b':p.color==='blue'?'#3b82f6':p.color==='magenta'?'#d946ef':'#f8fafc'}"></span><b>${p.fixture}</b>`:''}</button>`).join('');const m=metrics();$('.sr-meters',root).innerHTML=['Coverage','Mood','Contrast','Motion'].map(n=>`<div class="sr-meter"><span>${n}</span><b>${m[n.toLowerCase()]}/10</b></div>`).join('');$('[data-intensity]',root).textContent=st.intensity;['color','focus','intensity','speed'].forEach(k=>$(`[data-c="${k}"]`,root).value=st[k]);$('[data-a="run"]',root).disabled=ended;$('[data-a="recover"]',root).disabled=ended||!st.recovery}
    root.addEventListener('click',e=>{const c=e.target.closest('[data-cell]');if(c){place(+c.dataset.cell);return}const f=e.target.closest('[data-fixture]');if(f){st.fixture=f.dataset.fixture;draw();return}const a=e.target.closest('[data-a]')?.dataset.a;if(a==='run')run();if(a==='clear'){st.placements=Array(20).fill(null);draw()}if(a==='recover')recover();if(a==='restart')reset()});root.addEventListener('input',e=>{const k=e.target.dataset.c;if(!k)return;st[k]=['intensity','speed'].includes(k)?+e.target.value:e.target.value;draw()});root.addEventListener('keydown',e=>{const c=e.target.closest('[data-cell]');if(!c)return;const i=+c.dataset.cell;let n=i;if(e.key==='ArrowRight')n=Math.min(19,i+1);if(e.key==='ArrowLeft')n=Math.max(0,i-1);if(e.key==='ArrowDown')n=Math.min(19,i+5);if(e.key==='ArrowUp')n=Math.max(0,i-5);if(n!==i){e.preventDefault();$(`[data-cell="${n}"]`,root)?.focus()}});dialog.addEventListener('close',()=>root.replaceChildren(),{once:true});reset()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
