(() => {
  const APP = { name:'Stairwell Steward', emoji:'🧯', category:'play', version:'1.0.0', summary:'Guide evacuees through a spreading smoke drill with priority needs, doors, stairs, radios, and scarce time.', description:'A local emergency crowd-flow simulation with smoke spread, evacuee groups, priority assistance, door control, radio boosts, scoring, failure recovery, session-only night drill unlock, touch and keyboard controls, reduced-motion behavior, optional local audio, and teardown.' };
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const label=v=>v==='play'?'Play':v==='useful'?'Useful':'Experiment';
  function css(){ if($('#stairwell-steward-styles')) return; const st=document.createElement('style'); st.id='stairwell-steward-styles'; st.textContent=`
    .ss-card{animation:ss-rise .24s ease both}.ss-game{max-width:1120px;gap:14px}.ss-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.ss-stat,.ss-map,.ss-panel,.ss-group,.ss-log{border:1px solid var(--line);border-radius:18px;background:#fff}.ss-stat{padding:10px 12px}.ss-stat span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.ss-stat strong{display:block;margin-top:4px}.ss-layout{display:grid;grid-template-columns:1.1fr .9fr;gap:12px}.ss-map{padding:12px;background:linear-gradient(135deg,#f8fafc,#e0f2fe);display:grid;gap:10px}.ss-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}.ss-cell{min-height:72px;border:1px solid rgba(15,23,42,.14);border-radius:14px;background:#fff;text-align:left;padding:7px;display:grid;align-content:space-between;font-weight:900;position:relative}.ss-cell small{display:block;color:var(--muted);font-weight:800}.ss-cell[data-smoke='1']{background:#e2e8f0}.ss-cell[data-smoke='2']{background:#cbd5e1}.ss-cell[data-smoke='3']{background:#94a3b8;color:white}.ss-cell[data-kind='stair']{box-shadow:inset 0 0 0 3px #22c55e}.ss-cell[data-kind='exit']{box-shadow:inset 0 0 0 3px #2563eb}.ss-cell.is-selected{outline:4px solid var(--accent);outline-offset:2px}.ss-pill{display:inline-flex;align-items:center;justify-content:center;min-width:24px;height:24px;border-radius:999px;background:#111827;color:#fff;font-size:.72rem}.ss-panel{padding:14px;display:grid;gap:12px}.ss-modes,.ss-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.ss-modes button,.ss-actions button,.ss-group{min-height:44px;border:1px solid var(--line);border-radius:14px;background:#fff;font-weight:900}.ss-modes button.is-active{box-shadow:0 0 0 3px #fbbf24 inset}.ss-groups{display:grid;gap:8px}.ss-group{text-align:left;padding:9px}.ss-group.is-active{outline:3px solid var(--accent)}.ss-group small{display:block;color:var(--muted);margin-top:2px}.ss-log{min-height:96px;padding:17px 19px}.ss-help{font-size:.88rem;color:var(--muted)}.ss-actions button:focus-visible,.ss-modes button:focus-visible,.ss-cell:focus-visible,.ss-group:focus-visible{outline:4px solid var(--accent);outline-offset:2px}@media(max-width:900px){.ss-layout{grid-template-columns:1fr}.ss-hud{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.ss-map,.ss-panel{padding:9px}.ss-grid{grid-template-columns:repeat(3,1fr)}.ss-cell{min-height:64px}.ss-actions,.ss-modes{grid-template-columns:1fr 1fr}.ss-hud{gap:6px}.ss-stat{padding:8px}}@media(prefers-reduced-motion:reduce){.ss-card{animation:none!important;transition:none!important}}@keyframes ss-rise{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}`; document.head.append(st); }
  function addCard(){ const grid=$('#app-grid'), template=$('#app-card-template'); if(!grid||!template||$('[data-stairwell-steward-card]')) return; const f=$('.filter.is-active')?.dataset.filter||'all'; if(f!=='all'&&f!==APP.category) return; css(); const node=template.content.cloneNode(true), card=$('.app-card',node); card.dataset.category=APP.category; card.dataset.stairwellStewardCard='true'; card.classList.add('ss-card'); $('.app-icon',node).textContent=APP.emoji; $('.app-meta',node).textContent=`${label(APP.category)} · v${APP.version}`; $('.app-name',node).textContent=APP.name; $('.app-summary',node).textContent=APP.summary; const b=$('.app-card-button',node); b.setAttribute('aria-label',`Open ${APP.name}`); b.addEventListener('click',open); grid.append(node); }
  function boot(){ css(); let tries=0; const retry=()=>{addCard(); if(!$('[data-stairwell-steward-card]')&&tries++<20) setTimeout(retry,120);}; retry(); $$('.filter').forEach(b=>{ if(b.dataset.ssRefresh) return; b.dataset.ssRefresh='1'; b.addEventListener('click',()=>setTimeout(addCard,0));}); }
  function open(){ const dialog=$('#app-dialog'), stage=$('#app-stage'); if(!dialog||!stage) return; $('#dialog-title').textContent=APP.name; $('#dialog-category').textContent=`${label(APP.category)} · ${APP.emoji}`; $('#dialog-description').textContent=APP.description; $('#dialog-feedback').href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Stairwell%20Steward'; stage.replaceChildren(); game(stage,dialog); dialog.showModal(); }
  function game(stage,dialog){
    const root=document.createElement('section'); root.className='tool-panel ss-game'; root.innerHTML=`<div class="ss-hud"><div class="ss-stat"><span>Drill</span><strong id="ss-mode">Day</strong></div><div class="ss-stat"><span>Time</span><strong id="ss-time">20</strong></div><div class="ss-stat"><span>Radio</span><strong id="ss-radio">3</strong></div><div class="ss-stat"><span>Trust</span><strong id="ss-trust">10</strong></div><div class="ss-stat"><span>Evacuated</span><strong id="ss-out">0/0</strong></div><div class="ss-stat"><span>Score</span><strong id="ss-score">0</strong></div></div><div class="ss-layout"><div class="ss-map"><div class="ss-grid" aria-label="Building map"></div><div class="ss-log result-card" aria-live="polite"><strong>Run the floor.</strong><small>Move groups toward stairs and exits while smoke spreads every turn.</small></div></div><div class="ss-panel"><div class="ss-modes" aria-label="Drill modes"></div><p class="ss-help">Select a group, then tap a neighboring safe room. Open doors to slow smoke, use radio to guide one extra step, or triage to move assisted groups safely. Arrow keys move the selected group, Enter opens doors, R uses radio, T triages, and N starts over.</p><div><strong>Groups</strong><div class="ss-groups"></div></div><div class="ss-actions"><button class="button" data-act="door" type="button">Open fire door</button><button class="button button-secondary" data-act="radio" type="button">Radio boost</button><button class="button button-secondary" data-act="triage" type="button">Triage assist</button><button class="button button-secondary" data-act="new" type="button">New drill</button><button class="button button-secondary" data-act="sound" type="button" aria-pressed="false">Sound off</button></div></div></div>`; stage.append(root);
    const modes={day:{name:'Day drill',time:20,radio:3,groups:4},rush:{name:'Crowded rush',time:18,radio:2,groups:5},night:{name:'Night blackout',time:16,radio:2,groups:6,locked:true}};
    const rooms=['Atrium','Clinic','Lab','Office','Storage','Cafeteria','Archive','Studio','Server','Lobby','Exit'];
    const st={mode:'day',unlocked:false,time:20,radio:3,trust:10,score:0,selected:0,boost:false,sound:false,ac:null,smoke:[],groups:[],doors:new Set(),closed:false};
    const grid=$('.ss-grid',root), groupsBox=$('.ss-groups',root), log=$('.ss-log',root), modeBox=$('.ss-modes',root);
    const idx=(x,y)=>y*5+x, xy=i=>[i%5,Math.floor(i/5)], adj=i=>{const [x,y]=xy(i);return [[x+1,y],[x-1,y],[x,y+1],[x,y-1]].filter(([a,b])=>a>=0&&a<5&&b>=0&&b<3).map(([a,b])=>idx(a,b));};
    function kind(i){ if(i===14) return 'exit'; if([4,9].includes(i)) return 'stair'; return 'room'; }
    function tone(k){ if(!st.sound) return; const A=window.AudioContext||window.webkitAudioContext; if(!A) return; st.ac ||= new A(); st.ac.resume(); const o=st.ac.createOscillator(),g=st.ac.createGain(); o.type=k==='bad'?'square':'sine'; o.frequency.value=k==='win'?820:k==='move'?520:210; g.gain.setValueAtTime(.0001,st.ac.currentTime); g.gain.exponentialRampToValueAtTime(.05,st.ac.currentTime+.02); g.gain.exponentialRampToValueAtTime(.0001,st.ac.currentTime+.2); o.connect(g).connect(st.ac.destination); o.start(); o.stop(st.ac.currentTime+.22); }
    function note(a,b='Smoke, time, and trust are all resources.'){ log.innerHTML=`<strong>${a}</strong><small>${b}</small>`; }
    function setup(){ const m=modes[st.mode]; st.time=m.time; st.radio=m.radio; st.trust=10; st.score=0; st.selected=0; st.boost=false; st.doors=new Set(); st.smoke=Array(15).fill(0); st.smoke[0]=2; st.smoke[1]=1; st.groups=[]; const starts=[2,5,6,7,10,11]; for(let i=0;i<m.groups;i++) st.groups.push({id:i,pos:starts[i],size:i%2?3:2,need:i===1||i===4?'assisted':'mobile',out:false,panic:0}); note(`${m.name} started.`, 'Open a route, prioritize assisted groups, and keep the exit clear.'); render(); }
    function spread(){ const next=st.smoke.slice(); st.smoke.forEach((v,i)=>{ if(v>0) adj(i).forEach(n=>{ const key=[i,n].sort().join('-'); if(!st.doors.has(key)&&next[n]<3&&Math.random()<(.38+v*.08)) next[n]++; }); if(v>0&&next[i]<3&&Math.random()<.25) next[i]++; }); st.smoke=next; }
    function tick(){ st.time--; spread(); st.groups.forEach(g=>{ if(!g.out&&st.smoke[g.pos]>1){ g.panic++; st.trust--; } }); if(st.trust<1||st.time<1) finish(); }
    function move(to){ const g=st.groups[st.selected]; if(!g||g.out) return; if(!adj(g.pos).includes(to)){ note('That room is not adjacent.', 'Use the map one step at a time, or spend radio for a longer coordinated move.'); return; } if(st.smoke[to]>2){ note('Smoke blocks that route.', 'Open a fire door or pick a safer stairwell path.'); tone('bad'); return; } const cost=g.need==='assisted'&&!st.boost?2:1; g.pos=to; st.score+=kind(to)==='stair'?8:3; if(kind(to)==='exit'){ g.out=true; st.score+=35+g.size*8+(g.need==='assisted'?15:0); note('Group evacuated.', 'Priority exits protect trust and unlock the harder drill.'); tone('win'); } else { note(`${g.need} group moved to ${rooms[to%rooms.length]}.`, cost>1?'Assisted groups need triage or extra time.':'Clean movement keeps panic low.'); tone('move'); } st.boost=false; for(let i=0;i<cost;i++) tick(); if(st.groups.every(x=>x.out)&&st.score>175&&!st.unlocked){ st.unlocked=true; note('Night blackout unlocked.', 'The next session adds more groups and less time.'); } render(); }
    function door(){ const g=st.groups[st.selected]; if(!g||g.out) return; const near=adj(g.pos).find(n=>st.smoke[n]>0); if(near==null){ note('No nearby smoky door to seal.'); return; } const key=[g.pos,near].sort().join('-'); st.doors.add(key); st.score+=10; tick(); note('Fire door opened and staged.', 'Smoke spread from one adjacent room is slowed for the rest of the drill.'); tone('move'); render(); }
    function radio(){ if(st.radio<1){ note('Radio channel is spent.'); tone('bad'); return; } st.radio--; st.boost=true; note('Radio boost ready.', 'The next assisted move costs one turn and a mobile group can reposition confidently.'); tone('move'); render(); }
    function triage(){ const g=st.groups[st.selected]; if(!g||g.out) return; g.panic=Math.max(0,g.panic-2); st.trust+=2; st.boost=true; tick(); note('Triage assist completed.', 'Trust rises and the next move is safer, but smoke still advances.'); render(); }
    function finish(){ const out=st.groups.filter(g=>g.out).length, trapped=st.groups.length-out, final=Math.max(0,st.score+st.time*5+st.trust*6-trapped*35-st.groups.reduce((s,g)=>s+g.panic*5,0)); st.score=final; st.time=Math.max(0,st.time); note(`Drill complete: ${final} points.`, `${out}/${st.groups.length} groups evacuated. Replay to improve route timing and triage order.`); tone(final>170?'win':'bad'); }
    function render(){ $('#ss-mode',root).textContent=modes[st.mode].name; $('#ss-time',root).textContent=Math.max(0,st.time); $('#ss-radio',root).textContent=st.radio; $('#ss-trust',root).textContent=st.trust; $('#ss-out',root).textContent=`${st.groups.filter(g=>g.out).length}/${st.groups.length}`; $('#ss-score',root).textContent=st.score; modeBox.innerHTML=''; Object.entries(modes).forEach(([k,m])=>{ const b=document.createElement('button'); b.type='button'; b.textContent=m.locked&&!st.unlocked?'Locked':m.name; b.disabled=!!(m.locked&&!st.unlocked); b.className=k===st.mode?'is-active':''; b.onclick=()=>{st.mode=k;setup();}; modeBox.append(b); }); grid.innerHTML=''; for(let i=0;i<15;i++){ const c=document.createElement('button'); c.type='button'; c.className='ss-cell'; c.dataset.smoke=st.smoke[i]; c.dataset.kind=kind(i); const here=st.groups.filter(g=>!g.out&&g.pos===i); c.innerHTML=`<span>${rooms[i%rooms.length]}</span><small>${kind(i)} · smoke ${st.smoke[i]}</small>${here.map(g=>`<b class="ss-pill">${g.need[0].toUpperCase()}${g.size}</b>`).join('')}`; if(here.some(g=>g.id===st.selected)) c.classList.add('is-selected'); c.setAttribute('aria-label',`${rooms[i%rooms.length]}, ${kind(i)}, smoke ${st.smoke[i]}, ${here.length} groups`); c.onclick=()=>move(i); grid.append(c); } groupsBox.innerHTML=''; st.groups.forEach((g,i)=>{ const b=document.createElement('button'); b.type='button'; b.className=`ss-group ${i===st.selected?'is-active':''}`; b.innerHTML=`Group ${i+1}: ${g.out?'evacuated':rooms[g.pos%rooms.length]}<small>${g.size} people · ${g.need} · panic ${g.panic}</small>`; b.onclick=()=>{st.selected=i;render();}; groupsBox.append(b); }); }
    root.addEventListener('click',e=>{ const a=e.target.closest('[data-act]')?.dataset.act; if(a==='door') door(); if(a==='radio') radio(); if(a==='triage') triage(); if(a==='new') setup(); if(a==='sound'){ st.sound=!st.sound; e.target.textContent=st.sound?'Sound on':'Sound off'; e.target.setAttribute('aria-pressed',String(st.sound)); tone('move'); }});
    root.addEventListener('keydown',e=>{ const g=st.groups[st.selected]; if(!g||g.out) return; const [x,y]=xy(g.pos); const map={ArrowRight:idx(Math.min(4,x+1),y),ArrowLeft:idx(Math.max(0,x-1),y),ArrowDown:idx(x,Math.min(2,y+1)),ArrowUp:idx(x,Math.max(0,y-1))}; if(e.key in map){ e.preventDefault(); move(map[e.key]); } if(e.key==='Enter'){ e.preventDefault(); door(); } if(e.key.toLowerCase()==='r'){ e.preventDefault(); radio(); } if(e.key.toLowerCase()==='t'){ e.preventDefault(); triage(); } if(e.key.toLowerCase()==='n'){ e.preventDefault(); setup(); }});
    const close=()=>{ st.closed=true; if(st.ac) st.ac.close().catch(()=>{}); dialog.removeEventListener('close',close); }; dialog.addEventListener('close',close); setup(); }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',boot,{once:true}); else boot();
})();
