(() => {
'use strict';
const APP={name:'Stratosphere Scout',emoji:'🎈',category:'play',version:'1.0.0',summary:'Pilot a research balloon through shifting wind layers, sample target zones, and recover the payload.',description:'A local-only atmospheric mission simulator with six flights, changing winds, altitude control, battery, ballast, venting, payload tradeoffs, timed sampling, drift, scoring, progression, a session unlock, meaningful loss, one costly recovery, touch, keyboard, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const MISSIONS=[
 {title:'Dawn inversion',brief:'Sample the cool inversion layer and land east of the ridge.',targetBand:1,targetX:72,duration:7,wind:[.22,.5,.8,.35],battery:82},
 {title:'Farm moisture map',brief:'Collect two low-altitude readings before recovering near the river.',targetBand:0,targetX:78,duration:8,wind:[.6,.25,-.15,.2],battery:86},
 {title:'Smoke boundary',brief:'Cross the plume edge at mid altitude without lingering in turbulent air.',targetBand:2,targetX:70,duration:8,wind:[.15,.55,1.0,-.2],battery:84},
 {title:'Jetstream postcard',brief:'Reach the upper flow, sample briefly, then descend into a safe corridor.',targetBand:3,targetX:76,duration:9,wind:[.3,.65,1.05,1.35],battery:90},
 {title:'Storm outflow',brief:'Use opposing layers to hold position while gathering three samples.',targetBand:2,targetX:68,duration:10,wind:[-.45,.5,1.15,-.7],battery:92},
 {title:'Polar night relay',brief:'Complete a full profile and recover the instrument package beyond the ice shelf.',targetBand:3,targetX:82,duration:11,wind:[.55,-.35,.85,1.25],battery:96}
];
const PAYLOADS={camera:{name:'Cloud camera',power:2,score:70,band:2},thermo:{name:'Thermal sonde',power:1,score:55,band:0},aerosol:{name:'Aerosol sampler',power:3,score:95,band:2},ozone:{name:'Ozone cell',power:3,score:110,band:3}};
function style(){if($('#stratosphere-scout-style'))return;const e=document.createElement('style');e.id='stratosphere-scout-style';e.textContent=`
.strato{max-width:1120px;display:grid;gap:12px}.ss-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.ss-stat,.ss-card{border:1px solid var(--line);border-radius:17px;background:#fff}.ss-stat{padding:9px}.ss-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.ss-layout{display:grid;grid-template-columns:1.2fr .8fr;gap:12px}.ss-card{padding:15px}.ss-sky{position:relative;min-height:410px;border-radius:24px;overflow:hidden;background:linear-gradient(#15284d 0%,#4776aa 40%,#a8d6e8 72%,#e8d7b0 100%);border:1px solid #29466d;isolation:isolate}.ss-band{position:absolute;left:0;right:0;height:25%;border-top:1px dashed rgba(255,255,255,.35)}.ss-band:nth-child(1){bottom:0}.ss-band:nth-child(2){bottom:25%}.ss-band:nth-child(3){bottom:50%}.ss-band:nth-child(4){bottom:75%}.ss-wind{position:absolute;right:10px;font-size:.7rem;color:white;background:rgba(8,22,45,.48);padding:4px 7px;border-radius:999px}.ss-balloon{position:absolute;width:42px;height:54px;transform:translate(-50%,50%);transition:left .45s linear,bottom .45s linear;z-index:3}.ss-envelope{width:38px;height:42px;border-radius:52% 52% 45% 45%;background:radial-gradient(circle at 34% 28%,#fff7d7,#ef6f5a 55%,#a7313a);border:2px solid rgba(255,255,255,.8);box-shadow:0 8px 18px rgba(0,0,0,.25)}.ss-line{width:1px;height:8px;background:#fff;margin:auto}.ss-payload{width:13px;height:8px;background:#f0c35a;border:1px solid #5d4315;margin:auto}.ss-target{position:absolute;bottom:5%;width:54px;height:20px;border:2px solid #fff;border-radius:50%;background:rgba(77,205,173,.28);transform:translateX(-50%);box-shadow:0 0 20px rgba(101,255,214,.5)}.ss-cloud{position:absolute;width:90px;height:25px;border-radius:50%;background:rgba(255,255,255,.32);filter:blur(1px);animation:ss-drift 8s linear infinite}@keyframes ss-drift{from{transform:translateX(-120px)}to{transform:translateX(780px)}}.ss-trail{position:absolute;inset:0;pointer-events:none}.ss-trail polyline{fill:none;stroke:#fff7b0;stroke-width:2;stroke-dasharray:5 5;opacity:.72}.ss-controls{display:grid;gap:10px}.ss-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.ss-grid button,.ss-actions button{min-height:46px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800;padding:9px}.ss-grid button[aria-pressed=true]{outline:3px solid #8bcfe2;background:#e9f8fc}.ss-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.ss-actions .primary{background:#dff5fb;border-color:#34748b}.ss-log{min-height:116px}.ss-meter{height:10px;border-radius:99px;background:#e7edf2;overflow:hidden}.ss-meter span{display:block;height:100%;background:#4d9bb4;transition:width .25s}.ss-tags{display:flex;gap:6px;flex-wrap:wrap}.ss-tag{font-size:.69rem;padding:4px 7px;border-radius:999px;background:#eaf4f7}.ss-hint{font-size:.82rem;color:var(--muted)}
@media(max-width:820px){.ss-layout{grid-template-columns:1fr}.ss-hud{grid-template-columns:repeat(3,1fr)}.ss-sky{min-height:360px}}@media(max-width:520px){.ss-hud{grid-template-columns:repeat(2,1fr)}.ss-sky{min-height:310px}.ss-actions{grid-template-columns:1fr}.ss-grid button{min-height:50px}}@media(prefers-reduced-motion:reduce){.strato *{animation:none!important;transition:none!important}}
`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-stratosphere-scout]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.stratosphereScout='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-stratosphere-scout]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.ssBound)return;b.dataset.ssBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · atmospheric strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
 const root=document.createElement('section');root.className='tool-panel strato';root.innerHTML=`<div class="ss-hud">${['Flight','Time','Altitude','Battery','Samples','Score'].map((x,i)=>`<div class="ss-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="ss-layout"><section class="ss-card"><div class="ss-sky" role="img" aria-label="Balloon flight showing altitude, drift, winds, and landing target"><div class="ss-band"></div><div class="ss-band"></div><div class="ss-band"></div><div class="ss-band"></div><span class="ss-wind" style="bottom:10%" data-w="0"></span><span class="ss-wind" style="bottom:35%" data-w="1"></span><span class="ss-wind" style="bottom:60%" data-w="2"></span><span class="ss-wind" style="bottom:85%" data-w="3"></span><div class="ss-cloud" style="left:5%;bottom:28%"></div><div class="ss-cloud" style="left:38%;bottom:58%;animation-delay:-3s"></div><svg class="ss-trail" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><polyline data-trail points="10,90"/></svg><div class="ss-target" data-target></div><div class="ss-balloon" data-balloon><div class="ss-envelope"></div><div class="ss-line"></div><div class="ss-payload"></div></div></div><h3 data-title></h3><p data-brief></p><div class="ss-tags" data-tags></div><p class="ss-hint">Raise or lower altitude to ride different wind layers. Sampling consumes battery and only scores inside the requested band. Keyboard: ↑/↓ altitude, S sample, V vent, B ballast, Enter advances time.</p></section><aside class="ss-card ss-controls"><div class="result-card ss-log" aria-live="polite"></div><label>Battery<div class="ss-meter"><span data-battery></span></div></label><div class="ss-grid">${Object.entries(PAYLOADS).map(([k,v],i)=>`<button data-payload="${k}" aria-pressed="false"><span aria-hidden="true">${i+1}</span> ${v.name}</button>`).join('')}</div><div class="ss-actions"><button class="primary" data-a="rise">Rise one layer</button><button data-a="sink">Sink one layer</button><button data-a="sample">Take sample</button><button data-a="advance">Advance 1 minute</button><button data-a="ballast">Drop ballast</button><button data-a="vent">Vent gas</button><button data-a="recover">Recovery drone</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
 let st,timer=0,ended=false;
 function reset(){clearTimeout(timer);st={mission:0,time:0,band:0,x:10,battery:MISSIONS[0].battery,ballast:3,vents:3,samples:0,score:0,trust:3,payload:'thermo',unlock:false,recovery:true,path:[[10,90]],profile:new Set()};ended=false;log('Balloon released.',MISSIONS[0].brief);draw()}
 function mission(){return MISSIONS[st.mission]}
 function wind(){return mission().wind[st.band]}
 function moveBand(delta){if(ended)return;const cost=delta>0?6:3;if(st.battery<cost)return log('Not enough battery.','Use wind drift, vent, or prepare to recover.');st.band=clamp(st.band+delta,0,3);st.battery-=cost;st.profile.add(st.band);log(delta>0?'Burner pulse lifts the balloon.':'The balloon descends into denser air.',`Current wind ${wind()>=0?'east':'west'} at ${Math.abs(wind()).toFixed(2)} drift units.`);advance(true)}
 function advance(fromControl=false){if(ended)return;const m=mission();st.time++;st.x=clamp(st.x+wind()*7,0,100);st.battery=clamp(st.battery-(fromControl?1:2),0,100);st.path.push([st.x,90-st.band*24]);if(st.x<=0||st.x>=100)return finish(false,'The balloon left the recoverable flight corridor.');if(st.time>=m.duration)return evaluate();if(st.battery<=0&&st.band>0)log('Battery exhausted.','You can still vent and ride the wind, but powered ascent and sampling are unavailable.');else log('Wind update.',`Minute ${st.time}. The balloon drifts ${wind()>=0?'east':'west'} in layer ${st.band+1}.`);draw()}
 function sample(){if(ended)return;const p=PAYLOADS[st.payload],cost=8+p.power*2;if(st.battery<cost)return log('Sample aborted.',`The ${p.name} needs ${cost}% battery.`);st.battery-=cost;const m=mission(),bandFit=Math.abs(st.band-m.targetBand),positionFit=Math.abs(st.x-m.targetX);let gain=p.score-bandFit*28-Math.round(positionFit*.8);if(p.band===st.band)gain+=25;if(st.profile.has(st.band))gain+=8;gain=Math.max(10,gain);st.samples++;st.score+=gain;if(st.score>=650)st.unlock=true;log(`${p.name} captured data.`,`Sample +${gain}. ${bandFit===0?'Target altitude confirmed.':'Altitude mismatch reduced value.'}`);draw()}
 function ballast(){if(ended||st.ballast<=0)return log('No ballast left.','Reserve it for a critical climb.');st.ballast--;st.band=clamp(st.band+1,0,3);st.x=clamp(st.x+wind()*3,0,100);st.path.push([st.x,90-st.band*24]);log('Ballast released.','You gain one layer without battery, but the action cannot be reversed.');draw()}
 function vent(){if(ended||st.vents<=0)return log('No vent capacity left.','The envelope has reached its safe vent limit.');st.vents--;st.band=clamp(st.band-1,0,3);st.path.push([st.x,90-st.band*24]);log('Gas vented.','You descend one layer and preserve battery.');draw()}
 function evaluate(){const m=mission(),landing=Math.abs(st.x-m.targetX),sampleNeed=st.mission<2?2:3,profileBonus=st.profile.size*25,ok=landing<=18&&st.samples>=sampleNeed&&st.battery>=0;const gain=Math.max(0,Math.round(300-landing*5+st.samples*75+profileBonus+st.battery*1.5));st.score+=ok?gain:Math.round(gain*.25);if(ok){st.trust=clamp(st.trust+1,0,5);if(st.mission===MISSIONS.length-1)return finish(true,`Final score ${st.score}. All payloads recovered.`);st.mission++;const next=mission();st.time=0;st.band=0;st.x=10;st.battery=next.battery;st.ballast=3;st.vents=3;st.samples=0;st.path=[[10,90]];st.profile=new Set([0]);log('Payload recovered.',`Next flight: ${next.brief}`)}else{st.trust--;log('Recovery window missed.',`Landing error ${Math.round(landing)}. Samples ${st.samples}/${sampleNeed}.`);if(st.trust<=0)return finish(false,'The flight program is suspended after repeated payload losses.');st.time=Math.max(0,m.duration-3)}draw()}
 function recover(){if(ended||!st.recovery)return;st.recovery=false;st.x=clamp(mission().targetX-10,8,92);st.band=1;st.battery=Math.max(st.battery,24);st.score=Math.max(0,st.score-180);st.trust=Math.max(1,st.trust-1);st.path.push([st.x,66]);log('Recovery drone attached.','Position and battery improve, but score and trust fall. This option is available once.');draw()}
 function finish(win,msg){ended=true;clearTimeout(timer);log(win?'Research season complete.':'Mission program ended.',msg);draw()}
 function log(a,b){$('.ss-log',root).innerHTML=`<strong>${a}</strong><p>${b}</p>`}
 function draw(){const m=mission(),p=PAYLOADS[st.payload],hv=[`${st.mission+1}/6`,`${st.time}/${m.duration}`,`Layer ${st.band+1}`,`${Math.round(st.battery)}%`,st.samples,st.score];$$('[data-h]',root).forEach((x,i)=>x.textContent=hv[i]);$('[data-title]',root).textContent=m.title;$('[data-brief]',root).textContent=m.brief;$('[data-tags]',root).innerHTML=`<span class="ss-tag">Target layer ${m.targetBand+1}</span><span class="ss-tag">Target x ${m.targetX}</span><span class="ss-tag">Ballast ${st.ballast}</span><span class="ss-tag">Vents ${st.vents}</span><span class="ss-tag">Trust ${st.trust}</span><span class="ss-tag">${st.unlock?'Ozone cell unlocked':'Ozone cell at 650'}</span>`;$('[data-battery]',root).style.width=`${st.battery}%`;$('[data-balloon]',root).style.left=`${st.x}%`;$('[data-balloon]',root).style.bottom=`${5+st.band*24}%`;$('[data-target]',root).style.left=`${m.targetX}%`;$('[data-trail]',root).setAttribute('points',st.path.map(([x,y])=>`${x},${y}`).join(' '));$$('[data-w]',root).forEach((x,i)=>{const v=m.wind[i];x.textContent=`${v>=0?'→':'←'} ${Math.abs(v).toFixed(2)}`});$$('[data-payload]',root).forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.payload===st.payload));b.disabled=ended||(b.dataset.payload==='ozone'&&!st.unlock)});$('[data-a="rise"]',root).disabled=ended||st.band>=3||st.battery<6;$('[data-a="sink"]',root).disabled=ended||st.band<=0||st.battery<3;$('[data-a="sample"]',root).disabled=ended||st.battery<8+p.power*2;$('[data-a="advance"]',root).disabled=ended;$('[data-a="ballast"]',root).disabled=ended||st.ballast<=0||st.band>=3;$('[data-a="vent"]',root).disabled=ended||st.vents<=0||st.band<=0;$('[data-a="recover"]',root).disabled=ended||!st.recovery;$('[data-a="restart"]',root).disabled=false}
 root.addEventListener('click',e=>{const p=e.target.closest('[data-payload]'),a=e.target.closest('[data-a]');if(p){st.payload=p.dataset.payload;draw()}else if(a){({rise:()=>moveBand(1),sink:()=>moveBand(-1),sample,advance,ballast,vent,recover,restart:reset}[a.dataset.a]||(()=>{}))()}});
 function keys(e){if(!root.isConnected)return;if(/^[1-4]$/.test(e.key)){const k=Object.keys(PAYLOADS)[+e.key-1];if(k!=='ozone'||st.unlock){st.payload=k;draw();e.preventDefault()}}else if(e.key==='ArrowUp'){moveBand(1);e.preventDefault()}else if(e.key==='ArrowDown'){moveBand(-1);e.preventDefault()}else if(e.key.toLowerCase()==='s'){sample()}else if(e.key.toLowerCase()==='v'){vent()}else if(e.key.toLowerCase()==='b'){ballast()}else if(e.key==='Enter'){advance();e.preventDefault()}}
 document.addEventListener('keydown',keys);dialog.addEventListener('close',()=>{clearTimeout(timer);document.removeEventListener('keydown',keys)},{once:true});reset()
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
