(() => {
  'use strict';
  const APP={name:'Tea Atelier',emoji:'🍵',category:'play',version:'1.0.0',summary:'Blend leaves, botanicals, temperature, and steep time to satisfy changing guests without exhausting the pantry.',description:'A local-only tea blending strategy game with six commissions, combinatorial recipes, temperature and steep timing, inventory, aroma, body, brightness, astringency, trust, score, a session unlock, meaningful failure, one recovery, touch and keyboard controls, reduced motion, and teardown.'};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const ING=[
    {id:'green',name:'Green leaf',icon:'🌿',aroma:2,body:1,bright:3,astringent:2,stock:5,cost:1},
    {id:'black',name:'Black leaf',icon:'🍂',aroma:2,body:4,bright:1,astringent:3,stock:5,cost:1},
    {id:'oolong',name:'Oolong',icon:'🫖',aroma:4,body:3,bright:2,astringent:1,stock:4,cost:2},
    {id:'mint',name:'Mint',icon:'🌱',aroma:4,body:0,bright:4,astringent:0,stock:4,cost:1},
    {id:'ginger',name:'Ginger',icon:'🫚',aroma:3,body:3,bright:2,astringent:1,stock:3,cost:2},
    {id:'rose',name:'Rose',icon:'🌹',aroma:5,body:1,bright:2,astringent:0,stock:3,cost:2}
  ];
  const ORDERS=[
    {name:'Morning editor',brief:'Bright and aromatic, with little heaviness.',target:[7,3,8,3],temp:75,time:2},
    {name:'Rain-soaked cyclist',brief:'Warm, full-bodied, and gently spicy.',target:[6,8,4,4],temp:92,time:4},
    {name:'Gallery opening',brief:'Floral aroma and a clean, elegant finish.',target:[9,4,6,2],temp:82,time:3},
    {name:'Late study table',brief:'Strong body without harsh bitterness.',target:[6,9,3,4],temp:95,time:4},
    {name:'Summer courtyard',brief:'Cooling brightness with a soft body.',target:[8,3,10,1],temp:78,time:2},
    {name:'Critic’s flight',brief:'A balanced signature cup with a memorable aroma.',target:[9,7,7,4],temp:88,time:3}
  ];
  function style(){if($('#tea-atelier-style'))return;const e=document.createElement('style');e.id='tea-atelier-style';e.textContent=`.tea-atelier{max-width:1080px;display:grid;gap:12px}.ta-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.ta-stat,.ta-card{border:1px solid var(--line);border-radius:17px;background:#fff}.ta-stat{padding:9px}.ta-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.ta-layout{display:grid;grid-template-columns:1.1fr .9fr;gap:12px}.ta-card{padding:15px}.ta-cup{min-height:260px;border-radius:22px;background:radial-gradient(circle at 50% 25%,rgba(255,255,255,.95),rgba(240,253,244,.82) 35%,rgba(220,252,231,.72));display:grid;place-items:center;overflow:hidden;position:relative}.ta-cup svg{width:min(82%,440px);height:auto}.ta-steam{animation:taFloat 2.8s ease-in-out infinite;transform-origin:center}.ta-ingredients{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.ta-ing{min-height:52px;border:1px solid var(--line);border-radius:12px;background:#fff;padding:9px;text-align:left;font-weight:800}.ta-ing[aria-pressed=true]{background:#dcfce7;border-color:#15803d}.ta-ing:disabled{opacity:.48}.ta-controls{display:grid;grid-template-columns:1fr 1fr;gap:9px}.ta-controls label{font-size:.72rem;font-weight:900;text-transform:uppercase;color:var(--muted)}.ta-controls input{width:100%}.ta-meters{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:10px}.ta-meter{background:#f5f5f4;border-radius:10px;padding:7px;font-size:.7rem}.ta-meter b{display:block;font-size:1rem}.ta-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:10px}.ta-actions button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800;padding:9px}.ta-actions .primary{background:#dcfce7;border-color:#15803d}.ta-log{min-height:106px}.ta-stock{font-size:.72rem;color:var(--muted)}@keyframes taFloat{50%{transform:translateY(-8px);opacity:.55}}@media(max-width:820px){.ta-layout{grid-template-columns:1fr}.ta-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:520px){.ta-hud{grid-template-columns:repeat(2,1fr)}.ta-ingredients,.ta-actions{grid-template-columns:1fr 1fr}.ta-cup{min-height:210px}.ta-meters{grid-template-columns:repeat(2,1fr)}}@media(prefers-reduced-motion:reduce){.tea-atelier *{animation:none!important;transition:none!important}}`;document.head.append(e)}
  function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-tea-atelier]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.teaAtelier='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
  function boot(){style();let n=0;const r=()=>{card();if(!$('[data-tea-atelier]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.taBound)return;b.dataset.taBound='1';b.addEventListener('click',()=>setTimeout(card))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · sensory blending strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel tea-atelier';root.innerHTML=`<div class="ta-hud">${['Guest','Coins','Trust','Score','Cups','Unlock'].map((x,i)=>`<div class="ta-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="ta-layout"><section class="ta-card"><div class="ta-cup" aria-hidden="true"><svg viewBox="0 0 480 280"><defs><linearGradient id="teaFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#fef3c7"/><stop offset="1" stop-color="#92400e"/></linearGradient></defs><g class="ta-steam" fill="none" stroke="#86efac" stroke-width="8" stroke-linecap="round" opacity=".75"><path d="M190 74c-28-28 24-42 0-68"/><path d="M240 70c-24-26 20-38 2-62"/><path d="M290 74c-28-28 24-42 0-68"/></g><path d="M105 105h250v92c0 50-38 75-125 75s-125-25-125-75z" fill="url(#teaFill)"/><path d="M355 132h28c52 0 52 74 0 74h-25" fill="none" stroke="#78716c" stroke-width="18"/><ellipse cx="230" cy="108" rx="126" ry="23" fill="#fde68a" stroke="#78716c" stroke-width="8"/><circle data-leaf cx="190" cy="105" r="8" fill="#16a34a"/><circle data-leaf cx="235" cy="112" r="7" fill="#be123c"/><circle data-leaf cx="275" cy="102" r="8" fill="#15803d"/></svg></div><div class="ta-meters"></div></section><aside class="ta-card"><div class="result-card ta-log" aria-live="polite"></div><p class="eyebrow">Pantry</p><div class="ta-ingredients"></div><div class="ta-controls"><label>Water <output data-temp></output><input data-c="temp" type="range" min="70" max="100" step="1"></label><label>Steep <output data-time></output><input data-c="time" type="range" min="1" max="6" step="1"></label></div><div class="ta-actions"><button class="primary" data-a="serve">Serve cup</button><button data-a="clear">Clear blend</button><button data-a="recover">Open reserve tin</button><button data-a="restart">New service</button></div></aside></div>`;stage.append(root);
    let st,ended=false;const maxBlend=3;
    function reset(){st={order:0,coins:12,trust:72,score:0,cups:7,blend:[],temp:82,time:3,stock:Object.fromEntries(ING.map(x=>[x.id,x.stock])),unlock:false,recovery:true};ended=false;log(ORDERS[0].brief,'Choose up to three ingredients, then tune water temperature and steep time.');draw()}
    function profile(){const p=[0,0,0,0];st.blend.forEach(id=>{const x=ING.find(i=>i.id===id);p[0]+=x.aroma;p[1]+=x.body;p[2]+=x.bright;p[3]+=x.astringent});const heat=(st.temp-70)/30,steep=(st.time-1)/5;p[0]+=Math.round((1-Math.abs(heat-.55))*2);p[1]+=Math.round(heat*2+steep*2);p[2]+=Math.round((1-heat)*2);p[3]+=Math.round(heat*steep*4);return p.map(x=>clamp(x,0,12))}
    function toggle(id){if(ended)return;const i=st.blend.indexOf(id);if(i>=0)st.blend.splice(i,1);else if(st.blend.length<maxBlend&&st.stock[id]>0)st.blend.push(id);else log('The infuser holds three ingredients.','Remove one ingredient or choose something still in stock.');draw()}
    function serve(){if(ended||!st.blend.length)return log('The cup is empty.','Select at least one ingredient before serving.');if(st.cups<=0)return end(false);const order=ORDERS[st.order],p=profile();let distance=p.reduce((s,v,i)=>s+Math.abs(v-order.target[i]),0)+Math.abs(st.temp-order.temp)/8+Math.abs(st.time-order.time)*1.4;let quality=clamp(Math.round(100-distance*5),0,100);const cost=st.blend.reduce((s,id)=>s+ING.find(x=>x.id===id).cost,0);if(cost>st.coins)return log('Not enough coins for that blend.','Clear one premium ingredient or use the reserve tin if available.');st.coins-=cost;st.cups--;st.blend.forEach(id=>st.stock[id]--);st.score+=quality*13;st.trust=clamp(st.trust+(quality>=82?9:quality<55?-17:-5),0,100);if(st.score>=2900)st.unlock=true;if(st.unlock&&st.stock.rose===0)st.stock.rose=1;if(st.trust<=0)return end(false);if(st.order>=ORDERS.length-1)return end(true);st.order++;st.coins+=quality>=82?5:3;st.blend=[];st.temp=82;st.time=3;log(quality>=84?'The guest asks for a second pot.':quality>=64?'The cup is thoughtful, if not exact.':'The balance misses the brief.',`Cup ${quality}. Next guest: ${ORDERS[st.order].brief}`);draw()}
    function recover(){if(ended||!st.recovery)return;st.recovery=false;st.trust=clamp(st.trust-14,0,100);st.coins+=4;st.cups+=2;ING.forEach(x=>st.stock[x.id]++);st.blend=[];log('The reserve tin reopens service.','Two cups and pantry stock returned, but the delay reduced trust.');draw()}
    function end(success){ended=true;const strong=success&&st.trust>=58&&st.score>=5600;log(strong?'The atelier earns a house blend.':success?'Service closes with a fragile reputation.':'The tea room loses the evening.',`Final score ${st.score}, trust ${st.trust}, coins ${st.coins}. Replay to match more briefs with fewer premium ingredients.`);draw()}
    function log(a,b){const l=$('.ta-log',root);l.replaceChildren(Object.assign(document.createElement('strong'),{textContent:a}),Object.assign(document.createElement('small'),{textContent:b}))}
    function draw(){const vals=[`${st.order+1}/6`,st.coins,st.trust,st.score,st.cups,st.unlock?'Prism rose':'Locked'];$$('[data-h]',root).forEach((e,i)=>e.textContent=vals[i]);$('.ta-ingredients',root).innerHTML=ING.map(x=>`<button class="ta-ing" data-ing="${x.id}" aria-pressed="${st.blend.includes(x.id)}" ${st.stock[x.id]<=0?'disabled':''}>${x.icon} ${x.name}<span class="ta-stock"> · ${st.stock[x.id]} left · ${x.cost} coin</span></button>`).join('');$('[data-c="temp"]',root).value=st.temp;$('[data-c="time"]',root).value=st.time;$('[data-temp]',root).textContent=`${st.temp}°C`;$('[data-time]',root).textContent=`${st.time} min`;const p=profile(),names=['Aroma','Body','Brightness','Astringency'];$('.ta-meters',root).innerHTML=names.map((n,i)=>`<div class="ta-meter"><span>${n}</span><b>${p[i]}/12</b></div>`).join('');$$('[data-leaf]',root).forEach((e,i)=>e.style.opacity=st.blend.length>i?'1':'.18');$('[data-a="serve"]',root).disabled=ended;$('[data-a="clear"]',root).disabled=ended||!st.blend.length;$('[data-a="recover"]',root).disabled=ended||!st.recovery}
    root.addEventListener('click',e=>{const ing=e.target.closest('[data-ing]');if(ing)return toggle(ing.dataset.ing);const a=e.target.closest('[data-a]')?.dataset.a;if(a==='serve')serve();if(a==='clear'){st.blend=[];draw()}if(a==='recover')recover();if(a==='restart')reset()});root.addEventListener('input',e=>{if(e.target.dataset.c==='temp')st.temp=+e.target.value;if(e.target.dataset.c==='time')st.time=+e.target.value;draw()});root.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('[data-ing]'))toggle(e.target.dataset.ing)});dialog.addEventListener('close',()=>root.replaceChildren(),{once:true});reset()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();