(() => {
'use strict';
const APP={name:'Trackline Ranger',emoji:'🐾',category:'play',version:'1.0.0',summary:'Read tracks, place cameras, and protect a moving animal before weather erases the trail.',description:'A local-only wildlife tracking strategy game with six expeditions, a hidden moving animal, spatial clues, weather decay, energy and time pressure, camera traps, route prediction, scoring, progression, adaptive difficulty, a session thermal unlock, meaningful failure, one costly ranger assist, touch, keyboard, reduced motion, and teardown.'};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const MISSIONS=[
 {title:'Creek crossing',species:'River otter',size:5,turns:10,weather:'Clear',decay:1,start:[0,4],goal:[4,0],brief:'Confirm the otter route and place one camera near the creek exit.'},
 {title:'Pine corridor',species:'Red fox',size:5,turns:10,weather:'Wind',decay:2,start:[0,2],goal:[4,4],brief:'Follow a fox through wind-scoured pine and predict its final corridor.'},
 {title:'Wetland dusk',species:'Marsh deer',size:6,turns:12,weather:'Rain',decay:2,start:[0,5],goal:[5,1],brief:'Use cameras before rain weakens sign across the marsh.'},
 {title:'Cliff den',species:'Mountain cat',size:6,turns:12,weather:'Cold front',decay:2,start:[0,3],goal:[5,5],brief:'Map a cautious cat while avoiding false rocky sign.'},
 {title:'Fireline return',species:'Black bear',size:7,turns:14,weather:'Ash wind',decay:3,start:[0,6],goal:[6,0],brief:'Track a bear across recovering habitat without overcommitting energy.'},
 {title:'Night migration',species:'Gray wolf',size:7,turns:15,weather:'Snow',decay:3,start:[0,3],goal:[6,6],brief:'Build a complete route model and confirm the final movement corridor.'}
];
function style(){if($('#trackline-ranger-style'))return;const e=document.createElement('style');e.id='trackline-ranger-style';e.textContent=`
.trackline{max-width:1120px;display:grid;gap:12px}.tr-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.tr-stat,.tr-card{border:1px solid var(--line);border-radius:17px;background:#fff}.tr-stat{padding:9px}.tr-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.tr-layout{display:grid;grid-template-columns:1.15fr .85fr;gap:12px}.tr-card{padding:15px}.tr-map{display:grid;gap:4px;padding:9px;border-radius:22px;background:linear-gradient(145deg,#dbe9d3,#b8d4c0);border:1px solid #6c8d74;touch-action:manipulation}.tr-cell{position:relative;aspect-ratio:1;border:1px solid rgba(42,74,51,.22);border-radius:10px;background:rgba(255,255,255,.45);min-width:0}.tr-cell button{position:absolute;inset:0;border:0;background:transparent;border-radius:inherit;cursor:pointer}.tr-cell button:focus-visible{outline:3px solid #244c39;outline-offset:-3px}.tr-cell.is-player{box-shadow:inset 0 0 0 4px #244c39}.tr-cell.is-selected{outline:3px solid #d68b32}.tr-cell.is-camera::after{content:'📷';position:absolute;right:3px;top:1px;font-size:.78rem}.tr-cell.is-track::before{content:'• •';position:absolute;left:5px;bottom:2px;font-weight:900;transform:rotate(-25deg);color:#684928}.tr-cell.is-scent::before{content:'≈';position:absolute;left:7px;bottom:1px;font-size:1.1rem;color:#355d4b}.tr-cell.is-scratch::before{content:'≋';position:absolute;left:6px;bottom:2px;color:#6a5035}.tr-cell.is-confirmed{background:#ffe9a8;box-shadow:inset 0 0 0 3px #cb8e18}.tr-cell.is-decoy{background:repeating-linear-gradient(45deg,rgba(255,255,255,.45),rgba(255,255,255,.45) 5px,rgba(120,91,59,.12) 5px,rgba(120,91,59,.12) 10px)}.tr-controls{display:grid;gap:10px}.tr-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.tr-actions button,.tr-mode button{min-height:46px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800;padding:9px}.tr-actions .primary{background:#e1f2e5;border-color:#3f7350}.tr-mode{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.tr-mode button[aria-pressed=true]{outline:3px solid #8cc49c;background:#eef8f0}.tr-log{min-height:108px}.tr-meter{height:10px;border-radius:99px;background:#e7edf2;overflow:hidden}.tr-meter span{display:block;height:100%;background:#4d8f5f;transition:width .25s}.tr-tags{display:flex;gap:6px;flex-wrap:wrap}.tr-tag{font-size:.69rem;padding:4px 7px;border-radius:999px;background:#edf5ee}.tr-hint{font-size:.82rem;color:var(--muted)}
@media(max-width:820px){.tr-layout{grid-template-columns:1fr}.tr-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:520px){.tr-hud{grid-template-columns:repeat(2,1fr)}.tr-actions{grid-template-columns:1fr}.tr-mode{grid-template-columns:1fr}.tr-cell{border-radius:7px}}@media(prefers-reduced-motion:reduce){.trackline *{animation:none!important;transition:none!important}}
`;document.head.append(e)}
function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-trackline-ranger]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true),a=$('.app-card',f);a.dataset.tracklineRanger='1';a.dataset.category=APP.category;$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
function boot(){style();let n=0;const r=()=>{card();if(!$('[data-trackline-ranger]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.trBound)return;b.dataset.trBound='1';b.addEventListener('click',()=>setTimeout(card))})}
function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · ecological field strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
function game(stage,dialog){
 const root=document.createElement('section');root.className='tool-panel trackline';root.innerHTML=`<div class="tr-hud">${['Expedition','Turns','Energy','Evidence','Trust','Score'].map((x,i)=>`<div class="tr-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="tr-layout"><section class="tr-card"><div class="tr-map" role="grid" aria-label="Wildlife tracking map" data-map></div><h3 data-title></h3><p data-brief></p><div class="tr-tags" data-tags></div><p class="tr-hint">Select a square, then investigate, move, place a camera, or predict the route. Keyboard: arrow keys move selection, I investigate, M move, C camera, P predict.</p></section><aside class="tr-card tr-controls"><div class="result-card tr-log" aria-live="polite"></div><label>Field energy<div class="tr-meter"><span data-energy></span></div></label><div class="tr-mode"><button data-mode="investigate" aria-pressed="true">Investigate</button><button data-mode="move" aria-pressed="false">Move</button><button data-mode="camera" aria-pressed="false">Camera</button></div><div class="tr-actions"><button class="primary" data-a="act">Use selected action</button><button data-a="predict">Predict corridor</button><button data-a="wait">Wait and observe</button><button data-a="assist">Ranger assist</button><button data-a="restart">New session</button></div></aside></div>`;stage.append(root);
 let st,ended=false,observer=0;
 function key(x,y){return `${x},${y}`}
 function mission(){return MISSIONS[st.mission]}
 function makePath(m){let p=[m.start],cur=[...m.start];while(cur[0]!==m.goal[0]||cur[1]!==m.goal[1]){const opts=[];if(cur[0]<m.goal[0])opts.push([cur[0]+1,cur[1]]);if(cur[1]<m.goal[1])opts.push([cur[0],cur[1]+1]);if(cur[1]>m.goal[1])opts.push([cur[0],cur[1]-1]);if(cur[0]>m.goal[0])opts.push([cur[0]-1,cur[1]]);cur=[...opts[Math.floor(Math.random()*opts.length)]];p.push(cur)}return p}
 function reset(){clearTimeout(observer);const m=MISSIONS[0];st={mission:0,turn:0,energy:100,evidence:0,trust:3,score:0,selected:[0,m.size-1],player:[0,m.size-1],mode:'investigate',cameras:new Set(),revealed:new Map(),predictions:new Set(),unlock:false,assist:true,path:makePath(m),animalStep:0};ended=false;log('Expedition begins.',m.brief);draw()}
 function startMission(){const m=mission();st.turn=0;st.energy=Math.min(100,78+st.trust*5);st.selected=[0,m.size-1];st.player=[0,m.size-1];st.cameras=new Set();st.revealed=new Map();st.predictions=new Set();st.path=makePath(m);st.animalStep=0;log(m.title,m.brief);draw()}
 function clueAt(x,y){const idx=st.path.findIndex(p=>p[0]===x&&p[1]===y);if(idx>=0){const age=Math.max(0,st.animalStep-idx);if(age>mission().decay+2)return null;return age===0?'track':age===1?'scent':'scratch'}if(Math.random()<.22)return 'decoy';return null}
 function spend(n){if(st.energy<n){log('Too exhausted.',`This action needs ${n} energy.`);return false}st.energy-=n;return true}
 function advance(){if(ended)return;st.turn++;st.animalStep=Math.min(st.path.length-1,st.animalStep+1);for(const c of st.cameras){const [x,y]=c.split(',').map(Number),a=st.path[st.animalStep];if(x===a[0]&&y===a[1]&&!st.revealed.has(c)){st.revealed.set(c,'confirmed');st.evidence+=2;st.score+=90;log('Camera confirmation.',`${mission().species} crossed the selected square.`)}}if(st.turn>=mission().turns)evaluate();else draw()}
 function act(){if(ended)return;const [x,y]=st.selected,k=key(x,y);if(st.mode==='investigate'){if(!spend(12))return;const c=clueAt(x,y);st.revealed.set(k,c||'empty');if(c&&c!=='decoy'){st.evidence++;st.score+=35}else if(c==='decoy')st.score=Math.max(0,st.score-15);log(c?'Sign found.':'No usable sign.',c==='decoy'?'The mark is unrelated wildlife activity.':c?`Fresh ${c} supports the route model.`:'Weather or distance erased the clue.')}else if(st.mode==='move'){const d=Math.abs(x-st.player[0])+Math.abs(y-st.player[1]);if(d!==1)return log('Move one square.','Choose an adjacent location.');if(!spend(7))return;st.player=[x,y];log('Position changed.',`Ranger moved to ${x+1}, ${y+1}.`)}else{if(st.cameras.has(k))return log('Camera already placed.','Choose another square.');if(st.cameras.size>=3+(st.unlock?1:0))return log('Camera limit reached.',st.unlock?'Four traps are active.':'Three traps are active.');if(!spend(16))return;st.cameras.add(k);log('Camera armed.','It will confirm the animal if the route crosses this square.')}advance()}
 function predict(){if(ended)return;if(!spend(5))return;const k=key(...st.selected);st.predictions.has(k)?st.predictions.delete(k):st.predictions.add(k);log('Route model updated.',`${st.predictions.size} square${st.predictions.size===1?'':'s'} predicted.`);draw()}
 function wait(){if(ended)return;st.energy=Math.min(100,st.energy+8);log('Quiet observation.','Energy recovers, but the animal and weather continue moving.');advance()}
 function assist(){if(ended||!st.assist)return log('Assist unavailable.','The senior ranger can intervene only once.');st.assist=false;st.score=Math.max(0,st.score-160);st.trust=Math.max(1,st.trust-1);const a=st.path[Math.min(st.path.length-1,st.animalStep+1)];st.selected=[...a];st.revealed.set(key(...a),'confirmed');st.evidence+=1;st.energy=Math.max(st.energy,35);log('Senior ranger marks a likely crossing.','Evidence and energy improve, but score and trust fall.');draw()}
 function evaluate(){const m=mission(),pathSet=new Set(st.path.map(p=>key(...p))),hits=[...st.predictions].filter(k=>pathSet.has(k)).length,precision=st.predictions.size?hits/st.predictions.size:0,cameraHits=[...st.revealed.values()].filter(v=>v==='confirmed').length,ok=st.evidence>=3&&hits>=2&&precision>=.45;const gain=Math.round(hits*80+precision*180+cameraHits*90+st.energy*1.2);st.score+=ok?gain:Math.round(gain*.25);if(st.score>=900)st.unlock=true;if(ok){st.trust=clamp(st.trust+1,0,5);if(st.mission===MISSIONS.length-1)return finish(true,`Final score ${st.score}. The migration corridor is protected.`);st.mission++;startMission()}else{st.trust--;log('Route model rejected.',`Evidence ${st.evidence}/3, correct corridor squares ${hits}, precision ${Math.round(precision*100)}%.`);if(st.trust<=0)return finish(false,'Field access is suspended after repeated weak surveys.');st.turn=Math.max(0,m.turns-3);draw()}}
 function finish(win,msg){ended=true;clearTimeout(observer);log(win?'Survey complete.':'Expedition failed.',msg);draw()}
 function log(a,b){const l=$('.tr-log',root);l.innerHTML=`<strong>${a}</strong><p>${b}</p>`}
 function draw(){const m=mission(),map=$('[data-map]',root);map.style.gridTemplateColumns=`repeat(${m.size},1fr)`;map.replaceChildren();for(let y=0;y<m.size;y++)for(let x=0;x<m.size;x++){const c=document.createElement('div'),k=key(x,y),v=st.revealed.get(k);c.className='tr-cell';if(st.player[0]===x&&st.player[1]===y)c.classList.add('is-player');if(st.selected[0]===x&&st.selected[1]===y)c.classList.add('is-selected');if(st.cameras.has(k))c.classList.add('is-camera');if(v)c.classList.add(`is-${v}`);if(st.predictions.has(k))c.style.boxShadow='inset 0 0 0 3px #d68b32';const b=document.createElement('button');b.type='button';b.setAttribute('role','gridcell');b.setAttribute('aria-label',`Map square ${x+1}, ${y+1}${v?`, ${v}`:''}`);b.addEventListener('click',()=>{st.selected=[x,y];draw()});c.append(b);map.append(c)}
 const h=$$('[data-h]',root);h[0].textContent=`${st.mission+1}/${MISSIONS.length}`;h[1].textContent=`${Math.max(0,m.turns-st.turn)}`;h[2].textContent=Math.round(st.energy);h[3].textContent=st.evidence;h[4].textContent=st.trust;h[5].textContent=st.score;$('[data-energy]',root).style.width=`${st.energy}%`;$('[data-title]',root).textContent=`${m.title} · ${m.species}`;$('[data-brief]',root).textContent=m.brief;$('[data-tags]',root).innerHTML=`<span class="tr-tag">${m.weather}</span><span class="tr-tag">Clue decay ${m.decay}</span><span class="tr-tag">${st.cameras.size}/${3+(st.unlock?1:0)} cameras</span>${st.unlock?'<span class="tr-tag">Thermal camera unlocked</span>':''}`;$$('[data-mode]',root).forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===st.mode)));$('[data-a="assist"]',root).disabled=!st.assist||ended;$('[data-a="act"]',root).disabled=ended;$('[data-a="predict"]',root).disabled=ended;$('[data-a="wait"]',root).disabled=ended}
 root.addEventListener('click',e=>{const m=e.target.closest('[data-mode]');if(m){st.mode=m.dataset.mode;draw();return}const a=e.target.closest('[data-a]')?.dataset.a;if(a==='act')act();if(a==='predict')predict();if(a==='wait')wait();if(a==='assist')assist();if(a==='restart')reset()});
 function keydown(e){if(!dialog.open)return;const m=mission();if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const d={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]}[e.key];st.selected=[clamp(st.selected[0]+d[0],0,m.size-1),clamp(st.selected[1]+d[1],0,m.size-1)];draw()}else if(e.key.toLowerCase()==='i'){st.mode='investigate';draw()}else if(e.key.toLowerCase()==='m'){st.mode='move';draw()}else if(e.key.toLowerCase()==='c'){st.mode='camera';draw()}else if(e.key.toLowerCase()==='p')predict()}
 document.addEventListener('keydown',keydown);const mo=new MutationObserver(()=>{if(!dialog.open){document.removeEventListener('keydown',keydown);clearTimeout(observer);mo.disconnect()}});mo.observe(dialog,{attributes:true,attributeFilter:['open']});reset()
}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();
})();
