(() => {
  'use strict';
  const APP={name:'Type Foundry',emoji:'🔠',category:'play',version:'1.0.0',summary:'Compose six editorial briefs by balancing hierarchy, readability, ink, revisions, and client trust.',description:'A local-only typography production game with six commissions, font-system choices, size, leading, tracking, alignment, columns, contrast, limited ink and revisions, trust, score, a session unlock, meaningful failure, one costly recovery, responsive SVG previews, touch and keyboard controls, reduced motion, and teardown.'};
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const FONTS=[{id:'humanist',name:'Humanist sans',family:'system-ui',voice:3,clarity:5,ink:2},{id:'grotesk',name:'Grotesk',family:'Arial, sans-serif',voice:4,clarity:4,ink:2},{id:'serif',name:'Editorial serif',family:'Georgia, serif',voice:5,clarity:3,ink:3},{id:'mono',name:'Technical mono',family:'ui-monospace, monospace',voice:2,clarity:4,ink:2}];
  const BRIEFS=[
    {name:'Transit bulletin',copy:'Night service changes',need:{voice:2,clarity:9,density:4,contrast:8},note:'Fast scanning, high contrast, and calm hierarchy.'},
    {name:'Poetry broadside',copy:'The city remembers rain',need:{voice:9,clarity:5,density:3,contrast:6},note:'Expressive voice with generous breathing room.'},
    {name:'Museum label',copy:'A vessel for ordinary light',need:{voice:6,clarity:8,density:5,contrast:7},note:'Quiet authority and sustained reading comfort.'},
    {name:'Festival schedule',copy:'Three stages. One long evening.',need:{voice:7,clarity:8,density:8,contrast:8},note:'Dense information without losing entry points.'},
    {name:'Emergency card',copy:'Leave now. Use the east stairs.',need:{voice:3,clarity:10,density:6,contrast:10},note:'Immediate action, unmistakable order, no decoration debt.'},
    {name:'Independent journal',copy:'Small systems, lasting consequences',need:{voice:8,clarity:7,density:6,contrast:7},note:'A distinctive cover that still reads at arm’s length.'}
  ];
  function style(){if($('#type-foundry-style'))return;const e=document.createElement('style');e.id='type-foundry-style';e.textContent=`.type-foundry{max-width:1100px;display:grid;gap:12px}.tf-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.tf-stat,.tf-card{border:1px solid var(--line);border-radius:17px;background:#fff}.tf-stat{padding:9px}.tf-stat span{display:block;font-size:.61rem;font-weight:900;letter-spacing:.07em;text-transform:uppercase;color:var(--muted)}.tf-layout{display:grid;grid-template-columns:1.05fr .95fr;gap:12px}.tf-card{padding:15px}.tf-preview{min-height:330px;border-radius:22px;background:#111827;display:grid;place-items:center;overflow:hidden}.tf-preview svg{width:100%;height:auto;max-height:390px}.tf-fonts,.tf-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.tf-font,.tf-actions button{min-height:44px;border:1px solid var(--line);border-radius:11px;background:#fff;font-weight:800;padding:9px}.tf-font[aria-pressed=true]{background:#e0e7ff;border-color:#4338ca}.tf-controls{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:10px}.tf-controls label{font-size:.72rem;font-weight:900;text-transform:uppercase;color:var(--muted)}.tf-controls input,.tf-controls select{width:100%}.tf-meters{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:10px}.tf-meter{background:#f5f5f4;border-radius:10px;padding:7px;font-size:.7rem}.tf-meter b{display:block;font-size:1rem}.tf-actions{margin-top:10px}.tf-actions .primary{background:#e0e7ff;border-color:#4338ca}.tf-log{min-height:108px}.tf-brief{margin:.3rem 0 .8rem;color:var(--muted)}@media(max-width:820px){.tf-layout{grid-template-columns:1fr}.tf-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:520px){.tf-hud{grid-template-columns:repeat(2,1fr)}.tf-controls,.tf-fonts,.tf-actions{grid-template-columns:1fr 1fr}.tf-preview{min-height:250px}.tf-meters{grid-template-columns:repeat(2,1fr)}}@media(prefers-reduced-motion:reduce){.type-foundry *{animation:none!important;transition:none!important}}`;document.head.append(e)}
  function card(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-type-foundry]'))return;const active=$('.filter.is-active')?.dataset.filter||'all';if(active!=='all'&&active!==APP.category)return;const f=t.content.cloneNode(true);$('.app-card',f).dataset.typeFoundry='1';$('.app-icon',f).textContent=APP.emoji;$('.app-meta',f).textContent=`Play · v${APP.version}`;$('.app-name',f).textContent=APP.name;$('.app-summary',f).textContent=APP.summary;const b=$('.app-card-button',f);b.setAttribute('aria-label',`Open ${APP.name}`);b.addEventListener('click',open);g.append(f)}
  function boot(){style();let n=0;const r=()=>{card();if(!$('[data-type-foundry]')&&n++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.tfBound)return;b.dataset.tfBound='1';b.addEventListener('click',()=>setTimeout(card))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent='Play · editorial composition strategy';$('#dialog-description').textContent=APP.description;s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel type-foundry';root.innerHTML=`<div class="tf-hud">${['Brief','Ink','Revisions','Trust','Score','Unlock'].map((x,i)=>`<div class="tf-stat"><span>${x}</span><strong data-h="${i}">—</strong></div>`).join('')}</div><div class="tf-layout"><section class="tf-card"><div class="tf-preview" aria-hidden="true"><svg viewBox="0 0 640 420"><rect width="640" height="420" rx="28" fill="#f8fafc"/><rect x="32" y="30" width="576" height="360" rx="18" data-paper fill="#ffffff"/><text x="64" y="110" data-kicker font-size="18" fill="#64748b">TYPE FOUNDRY PROOF</text><text x="64" y="180" data-title fill="#111827">Preview</text><line x1="64" y1="225" x2="560" y2="225" stroke="#cbd5e1" stroke-width="3"/><text x="64" y="270" data-body font-size="22" fill="#334155">Hierarchy, rhythm, and restraint.</text><text x="64" y="310" data-body2 font-size="22" fill="#334155">Every choice spends something.</text></svg></div><div class="tf-meters"></div></section><aside class="tf-card"><div class="result-card tf-log" aria-live="polite"></div><p class="eyebrow">Type system</p><div class="tf-fonts"></div><div class="tf-controls"><label>Title size <output data-size></output><input data-c="size" type="range" min="42" max="88" step="2"></label><label>Leading <output data-leading></output><input data-c="leading" type="range" min="90" max="150" step="5"></label><label>Tracking <output data-track></output><input data-c="track" type="range" min="-2" max="8" step="1"></label><label>Columns<select data-c="cols"><option value="1">One</option><option value="2">Two</option><option value="3">Three</option></select></label><label>Alignment<select data-c="align"><option value="start">Left</option><option value="middle">Center</option><option value="end">Right</option></select></label><label>Contrast<select data-c="contrast"><option value="6">Soft</option><option value="8">Strong</option><option value="10">Maximum</option></select></label></div><div class="tf-actions"><button class="primary" data-a="submit">Send proof</button><button data-a="reset">Reset proof</button><button data-a="recover">Buy press check</button><button data-a="restart">New edition</button></div></aside></div>`;stage.append(root);
    let st,ended=false;
    function reset(){st={brief:0,ink:18,revisions:5,trust:74,score:0,font:'humanist',size:62,leading:115,track:0,cols:1,align:'start',contrast:8,unlock:false,recovery:true};ended=false;log(BRIEFS[0].note,'Build the first proof. Strong hierarchy should not consume every revision.');draw()}
    function metrics(){const f=FONTS.find(x=>x.id===st.font);const density=clamp(Math.round(st.cols*2.2+(150-st.leading)/16+(st.size<56?2:0)),1,10);const clarity=clamp(Math.round(f.clarity+(st.size-42)/16-(Math.abs(st.track)>5?2:0)+(st.leading>=105&&st.leading<=135?2:0)-(st.cols===3?1:0)),1,10);const voice=clamp(Math.round(f.voice+(st.size-42)/20+(Math.abs(st.track)>=3?1:0)+(st.align==='middle'?1:0)),1,10);return {voice,clarity,density,contrast:st.contrast}}
    function submit(){if(ended)return;const b=BRIEFS[st.brief],m=metrics(),f=FONTS.find(x=>x.id===st.font);const cost=Math.max(1,Math.ceil((f.ink+st.size/40+st.cols)/2));if(st.ink<cost)return log('The press is out of ink.','Reduce size or columns, or use the one press check.');if(st.revisions<=0)return end(false);st.ink-=cost;st.revisions--;const miss=Object.keys(b.need).reduce((s,k)=>s+Math.abs(m[k]-b.need[k]),0);const quality=clamp(100-miss*7,0,100);st.score+=quality*14;st.trust=clamp(st.trust+(quality>=84?9:quality<55?-18:-5),0,100);if(st.score>=3300)st.unlock=true;if(st.trust<=0)return end(false);if(st.brief>=BRIEFS.length-1)return end(true);st.brief++;if(quality>=80)st.revisions++;st.font=st.unlock?'serif':'humanist';st.size=62;st.leading=115;st.track=0;st.cols=1;st.align='start';st.contrast=8;log(quality>=84?'The proof goes straight to press.':quality>=64?'The hierarchy works, but the rhythm feels cautious.':'The client cannot find the intended entry point.',`Proof ${quality}. Next brief: ${BRIEFS[st.brief].note}`);draw()}
    function recover(){if(ended||!st.recovery)return;st.recovery=false;st.trust=clamp(st.trust-15,0,100);st.ink+=6;st.revisions+=2;log('A press check buys another route.','Ink and two revisions return, but the delay costs trust.');draw()}
    function end(success){ended=true;const strong=success&&st.trust>=60&&st.score>=6500;log(strong?'The issue earns a permanent place on the reading table.':success?'The edition ships with a fragile visual system.':'The production schedule collapses.',`Final score ${st.score}, trust ${st.trust}, ink ${st.ink}. Replay to solve briefs with fewer revisions and cleaner hierarchy.`);draw()}
    function log(a,b){const l=$('.tf-log',root);l.replaceChildren(Object.assign(document.createElement('strong'),{textContent:a}),Object.assign(document.createElement('small'),{textContent:b}))}
    function draw(){const vals=[`${st.brief+1}/6`,st.ink,st.revisions,st.trust,st.score,st.unlock?'Variable axis':'Locked'];$$('[data-h]',root).forEach((e,i)=>e.textContent=vals[i]);$('.tf-fonts',root).innerHTML=FONTS.map(x=>`<button class="tf-font" data-font="${x.id}" aria-pressed="${st.font===x.id}">${x.name}</button>`).join('');const b=BRIEFS[st.brief],m=metrics(),names=['Voice','Clarity','Density','Contrast'];$('.tf-meters',root).innerHTML=names.map((n,i)=>`<div class="tf-meter"><span>${n}</span><b>${m[n.toLowerCase()]}/10</b></div>`).join('');$('[data-size]',root).textContent=`${st.size}px`;$('[data-leading]',root).textContent=`${st.leading}%`;$('[data-track]',root).textContent=`${st.track}`;['size','leading','track','cols','align','contrast'].forEach(k=>$(`[data-c="${k}"]`,root).value=st[k]);const f=FONTS.find(x=>x.id===st.font),anchor=st.align==='start'?'start':st.align==='middle'?'middle':'end',x=st.align==='start'?64:st.align==='middle'?320:576;$('[data-title]',root).textContent=b.copy;$('[data-title]',root).setAttribute('x',x);$('[data-title]',root).setAttribute('text-anchor',anchor);$('[data-title]',root).setAttribute('font-family',f.family);$('[data-title]',root).setAttribute('font-size',st.size);$('[data-title]',root).setAttribute('letter-spacing',st.track);$$('[data-body],[data-body2]',root).forEach((e,i)=>{e.setAttribute('x',x);e.setAttribute('text-anchor',anchor);e.setAttribute('font-family',f.family);e.setAttribute('y',270+i*(st.leading/4));});$('[data-paper]',root).setAttribute('fill',st.contrast===10?'#ffffff':st.contrast===8?'#f8fafc':'#f1f5f9');$('[data-a="submit"]',root).disabled=ended;$('[data-a="recover"]',root).disabled=ended||!st.recovery}
    root.addEventListener('click',e=>{const f=e.target.closest('[data-font]');if(f){st.font=f.dataset.font;draw();return}const a=e.target.closest('[data-a]')?.dataset.a;if(a==='submit')submit();if(a==='reset'){st.font='humanist';st.size=62;st.leading=115;st.track=0;st.cols=1;st.align='start';st.contrast=8;draw()}if(a==='recover')recover();if(a==='restart')reset()});root.addEventListener('input',e=>{const k=e.target.dataset.c;if(!k)return;st[k]=['size','leading','track','cols','contrast'].includes(k)?+e.target.value:e.target.value;draw()});dialog.addEventListener('close',()=>root.replaceChildren(),{once:true});reset()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();