(() => {
  const APP = { name: 'Verdict Vault', emoji: '🗝️', category: 'play', version: '1.0.0', summary: 'Solve a rotating vault mystery by spending limited actions on clues, alibis, warrants, and pressure.', description: 'A local deduction game with suspects, evidence strength, alibi pressure, warrants, false leads, adaptive cases, scoring, session-only hard-mode unlocks, responsive SVG, touch and keyboard controls, optional audio, reduced-motion behavior, and teardown.' };
  const $ = (s) => document.querySelector(s);
  const label = (v) => v === 'play' ? 'Play' : v === 'useful' ? 'Useful' : 'Experiment';
  function style() {
    if ($('#verdict-vault-styles')) return;
    const s = document.createElement('style');
    s.id = 'verdict-vault-styles';
    s.textContent = `.vault-card{animation:vault-rise .24s ease both}.vault-game{max-width:1040px;gap:14px}.vault-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.vault-stat{border:1px solid var(--line);border-radius:15px;background:#fff;padding:10px 12px}.vault-stat span{display:block;color:var(--muted);font-size:.62rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.vault-stat strong{display:block;margin-top:4px}.vault-board{border:0;border-radius:26px;background:#10121f;color:white;padding:0;overflow:hidden;touch-action:manipulation;box-shadow:inset 0 0 0 1px rgba(255,255,255,.14)}.vault-board:focus-visible{outline:4px solid var(--accent);outline-offset:4px}.vault-board svg{display:block;width:100%;height:min(54vh,470px);min-height:330px}.vault-console{display:grid;grid-template-columns:1.1fr .9fr;gap:10px}.vault-panel{border:1px solid var(--line);border-radius:18px;background:#fff;padding:13px}.vault-tools,.vault-legend{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.vault-chip,.vault-legend span{border:1px solid var(--line);border-radius:999px;background:#fff;color:var(--ink);padding:8px 11px;font-weight:900}.vault-chip.is-active{background:#111827;color:#fff}.vault-suspects{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:10px}.vault-suspects button{min-height:70px;white-space:pre-line}.vault-log{min-height:106px;padding:17px 19px}.vault-case{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.vault-case span{border-radius:999px;background:#edf7f2;padding:7px 10px;font-weight:900}@media(max-width:760px){.vault-hud{grid-template-columns:repeat(2,1fr)}.vault-console{grid-template-columns:1fr}.vault-suspects{grid-template-columns:repeat(2,1fr)}.vault-board svg{height:52vh;min-height:330px}}@media(prefers-reduced-motion:reduce){.vault-card{animation:none}.vault-board svg{min-height:320px}}@keyframes vault-rise{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}`;
    document.head.append(s);
  }
  function addCard() {
    const grid = $('#app-grid'), tpl = $('#app-card-template');
    if (!grid || !tpl || $('[data-vault-card]')) return;
    const f = $('.filter.is-active')?.dataset.filter || 'all';
    if (f !== 'all' && f !== APP.category) return;
    style();
    const node = tpl.content.cloneNode(true), card = node.querySelector('.app-card');
    card.dataset.category = APP.category; card.dataset.vaultCard = 'true'; card.classList.add('vault-card');
    node.querySelector('.app-icon').textContent = APP.emoji;
    node.querySelector('.app-meta').textContent = `${label(APP.category)} · v${APP.version}`;
    node.querySelector('.app-name').textContent = APP.name;
    node.querySelector('.app-summary').textContent = APP.summary;
    const btn = node.querySelector('.app-card-button');
    btn.setAttribute('aria-label', `Open ${APP.name}`);
    btn.addEventListener('click', open);
    grid.append(node);
  }
  function boot() {
    style(); addCard();
    document.querySelectorAll('.filter').forEach((b) => {
      if (b.dataset.vaultRefresh) return;
      b.dataset.vaultRefresh = '1';
      b.addEventListener('click', () => setTimeout(addCard, 0));
    });
  }
  function open() {
    const dialog = $('#app-dialog'), stage = $('#app-stage'), title = $('#dialog-title'), cat = $('#dialog-category'), desc = $('#dialog-description'), fb = $('#dialog-feedback');
    if (!dialog || !stage) return;
    title.textContent = APP.name; cat.textContent = `${label(APP.category)} · ${APP.emoji}`; desc.textContent = APP.description;
    fb.href = 'https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Verdict%20Vault';
    stage.replaceChildren(); game(stage, dialog); dialog.showModal();
  }
  function game(stage, dialog) {
    const root = document.createElement('section');
    root.className = 'tool-panel vault-game';
    root.innerHTML = `<div class="vault-hud"><div class="vault-stat"><span>Case</span><strong id="vv-case">1 / 5</strong></div><div class="vault-stat"><span>Actions</span><strong id="vv-actions">9</strong></div><div class="vault-stat"><span>Insight</span><strong id="vv-insight">2</strong></div><div class="vault-stat"><span>Heat</span><strong id="vv-heat">0</strong></div><div class="vault-stat"><span>Score</span><strong id="vv-score">0</strong></div><div class="vault-stat"><span>Mode</span><strong id="vv-mode">Standard</strong></div></div><button class="vault-board" type="button" aria-label="Verdict Vault case board. Use arrow keys to choose a suspect, Enter to inspect, Space to test an alibi, W for a warrant, A to accuse, and N for a new case."><svg role="img" aria-label="Animated evidence board"></svg></button><div class="vault-console"><div class="vault-panel"><strong>Case controls</strong><p>Inspect clues, test alibis, request warrants, then accuse before actions run out. Strong evidence matters, but heat rises if you push the wrong person.</p><div class="vault-tools"><button class="button button-secondary vault-chip is-active" type="button" data-act="inspect">Inspect</button><button class="button button-secondary vault-chip" type="button" data-act="alibi">Test alibi</button><button class="button button-secondary vault-chip" type="button" data-act="warrant">Warrant</button><button class="button button-secondary vault-chip" type="button" data-act="accuse">Accuse</button></div><div class="vault-suspects"></div></div><div class="vault-panel"><strong>Case file</strong><div class="vault-case"><span>False lead: +heat</span><span>Warrant: costs insight</span><span>Correct chain: bonus</span><span>Hard vault unlock: 900</span></div><div class="vault-legend"><span>Gold: evidence</span><span>Blue: alibi</span><span>Red: heat</span><span>Green: warrant</span></div></div></div><div class="result-card vault-log" aria-live="polite"></div><div class="tool-actions"></div>`;
    stage.append(root);
    const svg = root.querySelector('svg'), board = root.querySelector('.vault-board'), log = root.querySelector('.vault-log'), suspectsBox = root.querySelector('.vault-suspects'), actions = root.querySelector('.tool-actions'), reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
    const names = ['Mara Vale', 'Otto Finch', 'June Quill', 'Nico Brass'];
    const motives = ['missing blueprint', 'swapped ledger', 'silent alarm', 'locked gallery', 'vanished prototype'];
    const st = { caseNo: 1, cases: 5, actions: 9, insight: 2, heat: 0, score: 0, selected: 0, culprit: 0, hard: false, solved: false, audio: false, ac: null, anim: 0, suspects: [] };
    actions.append(btn('New case', reset, true), btn('Hard vault', hardMode, true), btn('Sound off', sound, true));
    root.querySelectorAll('[data-act]').forEach((b) => b.addEventListener('click', () => act(b.dataset.act)));
    board.addEventListener('keydown', key); board.addEventListener('click', () => act('inspect')); dialog.addEventListener('close', tear, { once: true });
    reset();
    function btn(t, f, sec) { const b = document.createElement('button'); b.type = 'button'; b.className = sec ? 'button button-secondary' : 'button'; b.textContent = t; b.addEventListener('click', f); return b; }
    function say(h) { log.innerHTML = h; }
    function reset() { cancelAnimationFrame(st.anim); Object.assign(st, { actions: st.hard ? 7 : 9, insight: st.hard ? 1 : 2, heat: 0, selected: 0, solved: false }); makeCase(); say(`<strong>${motives[st.caseNo % motives.length]} case opened.</strong><small>Pick a suspect. Build enough confidence before accusing.</small>`); paint(); draw(); }
    function makeCase() { st.culprit = (st.caseNo * 3 + (st.hard ? 1 : 0)) % 4; st.suspects = names.map((name, i) => ({ name, evidence: i === st.culprit ? 2 + (st.caseNo % 2) : (i + st.caseNo) % 2, alibi: i === st.culprit ? 0 : 1 + ((i + st.caseNo) % 2), warrant: false, falseLead: i !== st.culprit && (i + st.caseNo) % 3 === 0, seen: 0 })); }
    function paint() { root.querySelector('#vv-case').textContent = `${st.caseNo} / ${st.cases}`; root.querySelector('#vv-actions').textContent = st.actions; root.querySelector('#vv-insight').textContent = st.insight; root.querySelector('#vv-heat').textContent = st.heat; root.querySelector('#vv-score').textContent = st.score; root.querySelector('#vv-mode').textContent = st.hard ? 'Hard' : 'Standard'; suspectsBox.replaceChildren(...st.suspects.map((s, i) => { const b = btn(`${i === st.selected ? '› ' : ''}${s.name}\n${s.seen ? `clue ${s.evidence} alibi ${s.alibi}${s.warrant ? ' warrant' : ''}` : 'unopened'}`, () => { st.selected = i; paint(); draw(); }, true); b.classList.toggle('is-active', i === st.selected); b.setAttribute('aria-label', `Select ${s.name}`); return b; })); }
    function spend(cost = 1) { if (st.solved) return false; if (st.actions < cost) { say('<strong>No actions remain.</strong><small>Make an accusation or start a new case.</small>'); return false; } st.actions -= cost; return true; }
    function act(kind) { if (kind === 'inspect') inspect(); if (kind === 'alibi') alibi(); if (kind === 'warrant') warrant(); if (kind === 'accuse') accuse(); paint(); draw(); }
    function inspect() { if (!spend()) return; const s = st.suspects[st.selected]; s.seen += 1; if (s.falseLead && s.seen === 1) st.heat += 1; const extra = s.evidence > s.alibi ? 'Evidence outweighs the alibi.' : 'The alibi is still stronger than the clue.'; say(`<strong>${s.name} file inspected.</strong><small>${extra}${s.falseLead ? ' The lead raised heat.' : ''}</small>`); beep(540); }
    function alibi() { if (!spend()) return; const s = st.suspects[st.selected]; s.seen += 1; if (s.alibi > 0) s.alibi -= 1; else { s.evidence += 1; st.heat += st.selected === st.culprit ? 0 : 1; } say(`<strong>${s.name} alibi tested.</strong><small>${s.alibi ? 'Part of the story still holds.' : 'The alibi cracked and evidence pressure rose.'}</small>`); beep(420); }
    function warrant() { if (!spend(2)) return; if (st.insight < 1) { st.actions += 2; return say('<strong>No insight left.</strong><small>Use inspection or alibi tests instead.</small>'); } const s = st.suspects[st.selected]; st.insight -= 1; s.warrant = true; s.seen += 1; s.evidence += st.selected === st.culprit ? 2 : 0; st.heat += st.selected === st.culprit ? 0 : 2; say(`<strong>Warrant served on ${s.name}.</strong><small>${st.selected === st.culprit ? 'A hidden chain of evidence appeared.' : 'The vault pushed back and heat climbed.'}</small>`); beep(700); }
    function accuse() { if (st.solved) return; const s = st.suspects[st.selected]; const confidence = s.evidence + (s.warrant ? 2 : 0) - s.alibi - st.heat; st.solved = true; if (st.selected === st.culprit && confidence >= 2) { const gain = 170 + st.actions * 25 + st.insight * 35 - st.heat * 20 + st.caseNo * 12; st.score += gain; beep(880); if (st.caseNo >= st.cases) say(`<strong>Vault closed: ${st.score}.</strong><small>${st.score >= 900 ? 'Hard vault unlocked for this session.' : 'Reach 900 to unlock hard vault.'}</small>`); else { st.caseNo += 1; st.actions += 1; st.insight += st.caseNo % 2; say(`<strong>Correct accusation.</strong><small>Case ${st.caseNo} opened with momentum and a ${gain}-point chain bonus.</small>`); makeCase(); st.solved = false; } } else { st.score = Math.max(0, st.score - 90); st.heat += 2; const trueName = st.suspects[st.culprit].name; say(`<strong>Case collapsed.</strong><small>The better answer was ${trueName}. Recover by starting a new case with the lesson intact.</small>`); beep(220); } }
    function hardMode() { if (!st.hard && st.score < 900) return say('<strong>Hard vault locked.</strong><small>Solve enough cases to score 900 first.</small>'); st.hard = !st.hard; reset(); say(`<strong>${st.hard ? 'Hard vault' : 'Standard vault'} active.</strong><small>${st.hard ? 'Fewer actions, less insight, harsher false leads.' : 'Standard case pacing restored.'}</small>`); }
    function key(e) { const k = e.key.toLowerCase(); if (k === 'arrowright' || k === 'arrowdown') { e.preventDefault(); st.selected = (st.selected + 1) % 4; paint(); draw(); } if (k === 'arrowleft' || k === 'arrowup') { e.preventDefault(); st.selected = (st.selected + 3) % 4; paint(); draw(); } if (k === 'enter') { e.preventDefault(); act('inspect'); } if (k === ' ') { e.preventDefault(); act('alibi'); } if (k === 'w') { e.preventDefault(); act('warrant'); } if (k === 'a') { e.preventDefault(); act('accuse'); } if (k === 'n') { e.preventDefault(); reset(); } }
    function draw() { const w = 900, h = 430, t = performance.now() / 900; let bits = `<rect width="${w}" height="${h}" rx="28" fill="#10121f"/><circle cx="450" cy="214" r="86" fill="none" stroke="#f3d77a" stroke-width="10" opacity=".8"/><text x="450" y="222" text-anchor="middle" fill="#fff" font-size="26" font-weight="800">Case ${st.caseNo}</text>`; st.suspects.forEach((s, i) => { const a = -Math.PI / 2 + i * Math.PI / 2 + (reduced ? 0 : Math.sin(t) * .03), x = 450 + Math.cos(a) * 250, y = 214 + Math.sin(a) * 142, hot = i === st.selected; bits += `<line x1="450" y1="214" x2="${x}" y2="${y}" stroke="${s.warrant ? '#9bf0c7' : s.seen ? '#f3d77a' : '#5a6078'}" stroke-width="${hot ? 6 : 3}" opacity=".8"/><circle cx="${x}" cy="${y}" r="${hot ? 52 : 44}" fill="${hot ? '#26304a' : '#181c2f'}" stroke="${s.falseLead && s.seen ? '#ff8d7a' : '#9bf0c7'}" stroke-width="3"/><text x="${x}" y="${y - 6}" text-anchor="middle" fill="#fff" font-size="18" font-weight="800">${s.name.split(' ')[0]}</text><text x="${x}" y="${y + 18}" text-anchor="middle" fill="#cdd6f4" font-size="14">E${s.evidence} A${s.alibi}</text>`; }); svg.innerHTML = bits; if (!reduced) st.anim = requestAnimationFrame(draw); }
    function sound(e) { const AC = window.AudioContext || window.webkitAudioContext; if (!AC) return say('<strong>Sound is not available here.</strong><small>The vault still works silently.</small>'); st.audio = !st.audio; e.currentTarget.textContent = st.audio ? 'Sound on' : 'Sound off'; if (st.audio) { st.ac ||= new AC(); st.ac.resume(); beep(600); } }
    function beep(f) { if (!st.audio || !st.ac) return; const o = st.ac.createOscillator(), g = st.ac.createGain(), n = st.ac.currentTime; o.frequency.value = f; g.gain.setValueAtTime(.0001, n); g.gain.exponentialRampToValueAtTime(.07, n + .02); g.gain.exponentialRampToValueAtTime(.0001, n + .18); o.connect(g).connect(st.ac.destination); o.start(n); o.stop(n + .2); }
    function tear() { cancelAnimationFrame(st.anim); board.removeEventListener('keydown', key); try { st.ac?.close(); } catch {} }
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot, { once: true }); else setTimeout(boot, 0);
})();
