(() => {
  const APP={name:'Volcano Watch',emoji:'🌋',category:'play',version:'1.0.0',summary:'Interpret noisy sensors, manage trust, and protect communities before an eruption.',description:'A local volcano-observatory strategy game with uncertain seismic, gas, deformation and thermal signals, limited surveys, branching alert decisions, evacuation capacity, public trust, false-alarm costs, adaptive scenarios, scoring, failure recovery, session-only drone and crisis-mode unlocks, pointer, touch and keyboard controls, reduced-motion behavior, optional local audio, and teardown.'};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const scenarios=[{name:'Basaltic unrest',base:[34,24,28,22],trend:[7,5,6,4],eruption:68,pop:42},{name:'Hydrothermal crisis',base:[26,38,18,42],trend:[4,8,3,7],eruption:72,pop:36},{name:'Dome growth',base:[28,30,44,31],trend:[5,6,9,5],eruption:75,pop:48},{name:'Deep magma intrusion',base:[40,20,35,24],trend:[9,4,7,4],eruption:78,pop:55},{name:'Caldera awakening',base:[31,35,40,32],trend:[7,7,8,6],eruption:82,pop:64}];
  function css(){if($('#vw-styles'))return;const s=document.createElement('style');s.id='vw-styles';s.textContent=`.vw-card{animation:vw-in .24s ease both}.vw-game{max-width:1120px;gap:14px}.vw-hud{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.vw-stat,.vw-chart,.vw-panel,.vw-log{border:1px solid var(--line);border-radius:18px;background:#fff}.vw-stat{padding:9px 11px}.vw-stat span{display:block;color:var(--muted);font-size:.6rem;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.vw-stat strong{display:block;margin-top:3px}.vw-layout{display:grid;grid-template-columns:1.15fr .85fr;gap:12px}.vw-chart{padding:12px;background:linear-gradient(155deg,#171717,#431407);color:#fff}.vw-chart svg{width:100%;height:auto;min-height:360px}.vw-grid{stroke:rgba(255,255,255,.12);stroke-width:1}.vw-line{fill:none;stroke-width:5;stroke-linecap:round;stroke-linejoin:round}.vw-dot{stroke:#fff;stroke-width:2}.vw-legend{display:flex;flex-wrap:wrap;gap:8px;font-size:.72rem}.vw-legend span::before{content:'';display:inline-block;width:.7rem;height:.7rem;border-radius:99px;background:var(--sw);margin-right:5px}.vw-panel{padding:14px;display:grid;gap:10px;align-content:start}.vw-modes,.vw-actions,.vw-alerts{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.vw-panel button{min-height:44px;border:1px solid var(--line);border-radius:14px;background:#fff;font-weight:900}.vw-panel button.is-active{box-shadow:0 0 0 3px #b45309 inset;background:#fffbeb}.vw-panel button[disabled]{opacity:.45}.vw-sensors{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.vw-sensor{border:1px solid var(--line);border-radius:14px;padding:10px;background:#fafafa}.vw-sensor strong,.vw-sensor small{display:block}.vw-meter{height:8px;background:#e5e7eb;border-radius:99px;overflow:hidden;margin-top:6px}.vw-meter i{display:block;height:100%;background:#f97316}.vw-summary{font-size:.82rem;color:var(--muted);border:1px dashed var(--line);border-radius:12px;padding:10px;background:#fafafa}.vw-log{padding:14px;min-height:90px}.vw-log small{display:block;margin-top:5px}@media(max-width:900px){.vw-layout{grid-template-columns:1fr}.vw-hud{grid-template-columns:repeat(3,1fr)}}@media(max-width:620px){.vw-hud{grid-template-columns:repeat(2,1fr)}.vw-actions,.vw-alerts,.vw-sensors{grid-template-columns:1fr}.vw-chart svg{min-height:280px}}@media(prefers-reduced-motion:reduce){.vw-card{animation:none!important}.vw-line{transition:none!important}}@keyframes vw-in{from{opacity:0;transform:translateY(10px) scale(.98)}to{opacity:1;transform:none}}`;document.head.append(s)}
  function addCard(){const g=$('#app-grid'),t=$('#app-card-template');if(!g||!t||$('[data-vw-card]'))return;const f=$('.filter.is-active')?.dataset.filter||'all';if(f!=='all'&&f!==APP.category)return;css();const n=t.content.cloneNode(true),c=$('.app-card',n);c.dataset.category=APP.category;c.dataset.vwCard='true';c.classList.add('vw-card');$('.app-icon',n).textContent=APP.emoji;$('.app-meta',n).textContent=`Play · v${APP.version}`;$('.app-name',n).textContent=APP.name;$('.app-summary',n).textContent=APP.summary;const b=$('.app-card-button',n);b.setAttribute('aria-label',`Open ${APP.name}`);b.onclick=open;g.append(n)}
  function boot(){css();let tries=0;const r=()=>{addCard();if(!$('[data-vw-card]')&&tries++<20)setTimeout(r,120)};r();$$('.filter').forEach(b=>{if(b.dataset.vwRefresh)return;b.dataset.vwRefresh='1';b.addEventListener('click',()=>setTimeout(addCard,0))})}
  function open(){const d=$('#app-dialog'),s=$('#app-stage');if(!d||!s)return;$('#dialog-title').textContent=APP.name;$('#dialog-category').textContent=`Play · ${APP.emoji}`;$('#dialog-description').textContent=APP.description;$('#dialog-feedback').href='https://github.com/JohnPMcGuire/autonomous-tiny-forge/issues/new?template=feedback.yml&title=%5BFeedback%5D%20Volcano%20Watch';s.replaceChildren();game(s,d);d.showModal()}
  function game(stage,dialog){const root=document.createElement('section');root.className='tool-panel vw-game';root.innerHTML=`<div class="vw-hud"><div class="vw-stat"><span>Day</span><strong id="vw-day">1 / 10</strong></div><div class="vw-stat"><span>Budget</span><strong id="vw-budget">12</strong></div><div class="vw-stat"><span>Trust</span><strong id="vw-trust">70</strong></div><div class="vw-stat"><span>Prepared</span><strong id="vw-ready">10%</strong></div><div class="vw-stat"><span>Alert</span><strong id="vw-alert">Green</strong></div><div class="vw-stat"><span>Score</span><strong id="vw-score">0</strong></div></div><div class="vw-layout"><div class="vw-chart"><svg viewBox="0 0 680 410" role="img" aria-label="Ten-day volcano sensor trend chart"></svg><div class="vw-legend"><span style="--sw:#60a5fa">Seismic</span><span style="--sw:#fbbf24">Gas</span><span style="--sw:#a78bfa">Deformation</span><span style="--sw:#fb7185">Thermal</span></div></div><div class="vw-panel"><div class="vw-modes" aria-label="Observatory modes"></div><div class="vw-sensors" aria-live="polite"></div><div class="vw-actions"><button data-act="survey">Ground survey · 2</button><button data-act="sample">Gas sample · 2</button><button data-act="drone">Drone thermal · 2</button><button data-act="prepare">Prepare shelters · 3</button><button data-act="brief">Public briefing</button><button data-act="advance">Advance day</button></div><div class="vw-alerts"><button data-alert="green">Green</button><button data-alert="yellow">Yellow</button><button data-alert="orange">Orange</button><button data-alert="red">Red</button></div><div class="vw-summary" aria-live="polite"></div><div class="vw-actions"><button data-act="recover">Emergency aid</button><button data-act="sound" aria-pressed="false">Sound off</button><button data-act="restart">Restart</button></div><div class="vw-log result-card" aria-live="polite"><strong>Observatory online.</strong><small>Signals are noisy. Combine evidence before escalating or standing down.</small></div></div></div>`;stage.append(root);
    const svg=$('svg',root),sensorBox=$('.vw-sensors',root),log=$('.vw-log',root),summary=$('.vw-summary',root),NS='http://www.w3.org/2000/svg';
    const modes={guided:{name:'Guided',budget:16,noise:5,days:9},standard:{name:'Standard',budget:12,noise:10,days:10},crisis:{name:'Crisis',budget:10,noise:14,days:11,locked:true}};
    const alerts={green:0,yellow:1,orange:2,red:3};
    const state={mode:'standard',day:1,budget:12,trust:70,prepared:10,score:0,alert:'green',scenario:null,trueRisk:20,readings:[],history:[[],[],[],[]],precision:[0,0,0,0],briefed:false,aid:false,drone:false,unlocked:false,sound:false,ac:null,ended:false,erupted:false};
    const note=(a,b)=>log.innerHTML=`<strong>${a}</strong><small>${b}</small>`;
    const tone=(f=440,d=.08)=>{if(!state.sound)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;state.ac||=new AC();state.ac.resume();const o=state.ac.createOscillator(),g=state.ac.createGain();o.frequency.value=f;g.gain.setValueAtTime(.0001,state.ac.currentTime);g.gain.exponentialRampToValueAtTime(.04,state.ac.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,state.ac.currentTime+d);o.connect(g).connect(state.ac.destination);o.start();o.stop(state.ac.currentTime+d+.02)};
    const rand=n=>(Math.random()*2-1)*n;
    function reset(){const m=modes[state.mode];state.day=1;state.budget=m.budget;state.trust=70;state.prepared=10;state.score=0;state.alert='green';state.scenario=scenarios[Math.floor(Math.random()*scenarios.length)];state.trueRisk=18+Math.random()*12;state.history=[[],[],[],[]];state.precision=[0,0,0,0];state.briefed=false;state.aid=false;state.ended=false;state.erupted=false;sampleReadings();render();note('New unrest episode.',`${state.scenario.name}. Watch trends, not isolated spikes, and preserve trust for the moment it matters.`)}
    function sampleReadings(){const m=modes[state.mode],s=state.scenario;state.readings=s.base.map((b,i)=>Math.max(0,Math.min(100,b+(state.day-1)*s.trend[i]+state.trueRisk*.25+rand(Math.max(2,m.noise-state.precision[i])))));state.readings.forEach((v,i)=>state.history[i].push(v))}
    function riskEstimate(){const w=[.3,.24,.28,.18];return Math.round(state.readings.reduce((a,v,i)=>a+v*w[i],0))}
    function expectedAlert(r){return r>=78?3:r>=60?2:r>=42?1:0}
    function setAlert(k){if(state.ended)return;const old=alerts[state.alert],next=alerts[k];state.alert=k;if(next>old){state.trust-=Math.max(0,(next-expectedAlert(riskEstimate()))*3);state.prepared=Math.min(100,state.prepared+(next-old)*8)}else if(next<old)state.trust+=1;note(`${k[0].toUpperCase()+k.slice(1)} alert set.`,next>=2?'Evacuation systems are activating. False alarms will cost trust.':'Monitoring and public guidance adjusted.');tone(420+next*90);render()}
    function spend(kind){if(state.ended)return;const costs={survey:2,sample:2,drone:2,prepare:3},cost=costs[kind];if(state.budget<cost){note('Budget too low.',`This action needs ${cost} budget.`);tone(160);return}if(kind==='drone'&&!state.drone){note('Drone locked.','Reach 900 points in a session to unlock drone thermal surveys.');return}state.budget-=cost;if(kind==='survey')state.precision[0]+=5;if(kind==='sample')state.precision[1]+=6;if(kind==='drone'){state.precision[3]+=8;state.precision[2]+=3}if(kind==='prepare')state.prepared=Math.min(100,state.prepared+18);note('Field action completed.',kind==='prepare'?'Shelter capacity and transport readiness improved.':'One sensor family is now less noisy for future readings.');tone(600);render()}
    function brief(){if(state.ended)return;const est=riskEstimate(),level=alerts[state.alert];state.briefed=true;if(Math.abs(level-expectedAlert(est))<=1){state.trust=Math.min(100,state.trust+5);state.score+=50;note('Briefing landed well.','Evidence, uncertainty, and next steps were explained clearly. Trust increased.')}else{state.trust=Math.max(0,state.trust-7);note('Briefing confused the public.','The alert level did not match the evidence. Trust fell.')}render()}
    function advance(){if(state.ended)return;const est=riskEstimate(),chosen=alerts[state.alert],ideal=expectedAlert(est);state.score+=Math.max(0,120-Math.abs(chosen-ideal)*38)+Math.round(state.trust/5)+Math.round(state.prepared/6);if(chosen>=2)state.prepared=Math.min(100,state.prepared+6);if(chosen===3)state.trust=Math.max(0,state.trust-3);state.trueRisk+=6+Math.random()*9+(state.day>6?4:0);state.day++;state.budget=Math.min(18,state.budget+4);state.briefed=false;const eruptionChance=Math.max(0,(state.trueRisk-state.scenario.eruption)/38);if(Math.random()<eruptionChance||state.trueRisk>105){erupt();return}if(state.day>modes[state.mode].days){finish();return}sampleReadings();if(state.score>=900&&!state.drone){state.drone=true;state.unlocked=true;modes.crisis.locked=false;note('Drone and Crisis mode unlocked.','Strong evidence handling opened precise thermal surveys and a harsher scenario for this session.');renderModes()}else note('New daily packet received.',`Estimated unrest is ${riskEstimate()}%. Sensor disagreement is ${Math.round(Math.max(...state.readings)-Math.min(...state.readings))} points.`);render()}
    function erupt(){state.erupted=true;state.ended=true;const level=alerts[state.alert],coverage=Math.min(100,state.prepared+level*12),loss=Math.max(0,state.scenario.pop*(1-coverage/100));state.score+=Math.round(coverage*12+state.trust*4-loss*25);note(loss<5?'Eruption survived.':'Eruption caused major losses.',`Preparedness covered ${Math.round(coverage)}% of the exposed population. Estimated unprotected impact: ${loss.toFixed(1)} units. Final score ${Math.max(0,Math.round(state.score))}.`);tone(loss<5?820:140,.18);render()}
    function recover(){if(state.aid||state.ended){note('Aid unavailable.','Emergency aid can be used once before the episode ends.');return}state.aid=true;state.budget+=5;state.trust=Math.max(0,state.trust-8);note('Emergency aid accepted.','Budget +5, trust -8. Recovery keeps options open but signals weak planning.');render()}
    function finish(){state.ended=true;const over=alerts[state.alert]>=2&&!state.erupted;state.score+=Math.round(state.trust*5+state.prepared*4-(over?180:0));note('Unrest episode closed.',`${over?'The high alert proved unnecessary and reduced the final score.':'The volcano quieted without eruption.'} Final score ${Math.max(0,Math.round(state.score))}.`);render()}
    function renderModes(){const box=$('.vw-modes',root);box.replaceChildren();Object.entries(modes).forEach(([k,m])=>{const b=document.createElement('button');b.textContent=m.name+(m.locked&&!state.unlocked?' 🔒':'');b.disabled=!!(m.locked&&!state.unlocked);b.classList.toggle('is-active',state.mode===k);b.onclick=()=>{state.mode=k;reset();renderModes()};box.append(b)})}
    function draw(){svg.replaceChildren();for(let y=0;y<=4;y++){const l=document.createElementNS(NS,'line');l.setAttribute('x1','48');l.setAttribute('x2','650');l.setAttribute('y1',String(35+y*80));l.setAttribute('y2',String(35+y*80));l.setAttribute('class','vw-grid');svg.append(l)}const colors=['#60a5fa','#fbbf24','#a78bfa','#fb7185'];state.history.forEach((arr,i)=>{if(!arr.length)return;const pts=arr.map((v,x)=>`${55+x*(585/Math.max(1,modes[state.mode].days-1))},${355-v*3}`).join(' ');const p=document.createElementNS(NS,'polyline');p.setAttribute('points',pts);p.setAttribute('class','vw-line');p.setAttribute('stroke',colors[i]);svg.append(p);arr.forEach((v,x)=>{const c=document.createElementNS(NS,'circle');c.setAttribute('cx',String(55+x*(585/Math.max(1,modes[state.mode].days-1))));c.setAttribute('cy',String(355-v*3));c.setAttribute('r','5');c.setAttribute('fill',colors[i]);c.setAttribute('class','vw-dot');svg.append(c)})})}
    function render(){draw();const names=['Seismic','Gas','Deformation','Thermal'];sensorBox.replaceChildren();state.readings.forEach((v,i)=>{const d=document.createElement('div');d.className='vw-sensor';d.innerHTML=`<strong>${names[i]} ${Math.round(v)}</strong><small>Precision boost ${state.precision[i]}</small><div class="vw-meter"><i style="width:${Math.min(100,v)}%"></i></div>`;sensorBox.append(d)});$('#vw-day',root).textContent=`${Math.min(state.day,modes[state.mode].days)} / ${modes[state.mode].days}`;$('#vw-budget',root).textContent=state.budget;$('#vw-trust',root).textContent=Math.max(0,Math.round(state.trust));$('#vw-ready',root).textContent=`${Math.round(state.prepared)}%`;$('#vw-alert',root).textContent=state.alert[0].toUpperCase()+state.alert.slice(1);$('#vw-score',root).textContent=Math.max(0,Math.round(state.score));$$('[data-alert]',root).forEach(b=>b.classList.toggle('is-active',b.dataset.alert===state.alert));$('[data-act="drone"]',root).disabled=!state.drone||state.ended;summary.textContent=`Estimated unrest ${riskEstimate()}%. Current alert ${state.alert}. ${state.briefed?'Public brief delivered today.':'No public brief today.'} ${state.drone?'Drone available.':'Drone locked.'}`}
    root.addEventListener('click',e=>{const a=e.target.closest('[data-act]')?.dataset.act,k=e.target.closest('[data-alert]')?.dataset.alert;if(k)setAlert(k);if(a==='survey'||a==='sample'||a==='drone'||a==='prepare')spend(a);if(a==='brief')brief();if(a==='advance')advance();if(a==='recover')recover();if(a==='restart')reset();if(a==='sound'){state.sound=!state.sound;e.target.textContent=state.sound?'Sound on':'Sound off';e.target.setAttribute('aria-pressed',String(state.sound));tone(520)}});
    const key=e=>{if(!dialog.open)return;const k=e.key.toLowerCase();if(['1','2','3','4'].includes(k))setAlert(['green','yellow','orange','red'][Number(k)-1]);if(k==='a')advance();if(k==='b')brief()};window.addEventListener('keydown',key);const close=()=>{window.removeEventListener('keydown',key);state.ac?.close();dialog.removeEventListener('close',close)};dialog.addEventListener('close',close);renderModes();reset()
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
